In [1]:
import endomill
from nbmetalog import nbmetalog as nbm

In [2]:
nbm.print_metadata()

context: ci
hostname: 548f50cd4098
interpreter: 3.8.10 (default, Sep 11 2024, 16:02:53)  [GCC 9.4.0]
nbcellexec: 2
nbname: phylogeny_simulation_mill
nbpath: /opt/hereditary-stratigraph-concept/binder/phylogenetic-inference/phylogeny_simulation_mill.ipynb
revision: null
session: 1b642c6b-faf1-4d5e-b8fa-49da00d91f75
timestamp: 2024-11-17T00:35:55Z00:00


IPython==7.16.1
keyname==0.4.1
yaml==5.3.1
endomill==0.1.3
nbmetalog==0.2.6
re==2.2.1
ipython_genutils==0.2.0
logging==0.5.1.2
zmq==22.3.0
json==2.0.9
ipykernel==5.5.3

In [3]:
endomill.instantiate_over(
    parameter_packs=[
        {
            'data_url': data_url,
            'data_filename': data_filename,
        }
        for data_filename, data_url in [
            (
                'nk_ecoeaselection_seed110_pop100_mut.01_snapshot_3000.csv',
                'https://osf.io/5d3be/',
            ),
            (
                'nk_lexicaseselection_seed110_pop165_mut.01_snapshot_500.csv',
                'https://osf.io/8ycq7/',
            ),
            (
                'nk_randomselection_seed7_pop100_mut.01_snapshot_5000.csv',
                'https://osf.io/ydxt7/',
            ),
            (
                'nk_sharingselection_seed10_pop100_mut.01_snapshot_5000.csv',
                'https://osf.io/cz9fk/',
            ),
            (
                'nk_tournamentselection_seed140_pop100_mut.01_snapshot_5000.csv',
                'https://osf.io/5ubn8/',
            )
        ]
    ],
)

detected executing.endomill.ipynb file
skipping instantiate_over

In [4]:
# define papermill parameters
data_url: str
data_filename: str

In [5]:
# Parameters
data_url = "https://osf.io/ydxt7/"
data_filename = "nk_randomselection_seed7_pop100_mut.01_snapshot_5000.csv"

In [6]:
import anytree
from bs4 import BeautifulSoup
from collections import defaultdict
from hstrat import hstrat
from interval_search import doubling_search
from iterpop import iterpop as ip
import itertools as it
from keyname import keyname as kn
import numpy as np
import opytional as opyt
import pandas as pd
import random
import sys
from tqdm import tqdm
from urllib import request

In [7]:
random.seed(1) # ensure reproducibility
sys.setrecursionlimit(100000) # anytree exceeds default recursion limit on our data

In [8]:
from nbmetalog import nbmetalog as nbm
nbm.print_metadata()

context: ci
hostname: 548f50cd4098
interpreter: 3.8.10 (default, Sep 11 2024, 16:02:53)  [GCC 9.4.0]
nbcellexec: 8
nbname: phylogeny_simulation_mill
nbpath: /opt/hereditary-stratigraph-concept/binder/phylogenetic-inference/phylogeny_simulation_mill.ipynb
revision: null
session: 1b642c6b-faf1-4d5e-b8fa-49da00d91f75
timestamp: 2024-11-17T00:35:56Z00:00


IPython==7.16.1
endomill==0.1.3
ipykernel==5.5.3
ipython_genutils==0.2.0
json==2.0.9
keyname==0.4.1
logging==0.5.1.2
nbmetalog==0.2.6
re==2.2.1
yaml==5.3.1
zmq==22.3.0
anytree==2.8.0
hstrat==0.3.2
iterpop==0.4.0
numpy==1.21.5
opytional==0.1.0
pandas==2.0.3

In [9]:
endomill.add_instance_outpath(
    f'a=phylogeny_simulation+source={data_filename}.endomill.ipynb',
)

# Retrieve Target Phylogeny from OSF

In [10]:
target_phylogeny_df = pd.read_csv(
    f'{data_url}/download',
)

nbm.print_dataframe_synopsis(target_phylogeny_df)

digest: 542298015c00bd09372befa775965be67fd83bbdb47a940347c178f5a19083d0
manifest:
  ancestor_list: '    3626#  ex., [316479]'
  depth: '            3153#  ex., 3141'
  destruction_time: ' 2743#  ex., inf'
  id: '               3697#  ex., 316633'
  num_offspring: '    5#     ex., 0'
  num_orgs: '         5#     ex., 1'
  origin_time: '      3211#  ex., 5000'
  phenotype: '        3686#  ex., [ 0.797946 0.536379 0.443815 0.0526468 0.92057 0.91075
    0.30778 0.492666 0.443872 0.822448 0.850668 0.622605 0.862708 0.278087 0.28528
    0.595257 0.709313 0.589555 0.0954585 0.862811 0.681532 0.396538 0.940159 0.466114
    0.964965 0.496943 0.931246 0.459464 0.323874 0.381974 0.457127 0.807726 0.439315
    0.824859 0.57682 0.840605 0.720875 0.501633 0.541537 0.474429 0.260919 0.477315
    0.382976 0.773835 0.691462 0.0166064 0.756788 0.431525 0.341946 0.359509 0.0311168
    0.624921 0.449223 0.775889 0.485843 0.932592 0.949503 0.0422867 0.0536213 0.108818
    0.958998 0.540366 0.456285 0.1875 0.899311 0.59706 0.425936 0.528831 0.537044
    0.720292 0.957068 0.746681 0.392795 0.543939 0.166369 0.805668 0.255746 0.00774763
    0.615083 0.0986629 0.281872 0.9853 0.26639 0.177044 0.341598 0.186309 0.403581
    0.711326 0.62494 0.853904 0.441514 0.0418954 0.963581 0.172946 0.412749 0.86182
    0.168004 0.631794 0.803979 0.449775 0.561051 0.221267 0.614246 0.477457 0.338633
    0.083854 0.0683286 0.93391 0.172241 0.89929 0.103581 0.469125 0.18933 0.785515
    0.816378 0.244662 0.191059 0.683141 0.283228 0.171559 0.621972 0.842445 0.774176
    0.0384827 0.103506 0.916684 0.99534 0.861877 0.593288 0.766542 0.603295 0.830595
    0.689014 0.915103 0.917971 0.415021 0.214791 0.72228 0.175467 0.361024 0.315883
    0.232436 0.197379 0.514892 0.44128 0.784395 0.13556 0.792916 0.0526158 0.893615
    0.437114 0.322495 0.923163 0.675438 0.290099 0.781006 0.791039 0.646287 0.318363
    0.499775 0.322352 0.981775 0.26354 0.501267 0.466449 0.272334 0.239124 0.99981
    0.476893 0.107192 0.128452 0.590622 0.279974 0.586513 0.218291 0.122193 0.554612
    0.55965 0.947409 0.623455 0.0273677 0.422406 0.932761 0.763582 0.478453 0.761483
    0.153003 0.254724 0.433007 0.395966 0.726484 0.450321 0.0919374 0.700726 0.375625
    0.614861 0.759063 0.503891 0.729632 0.983236 ]'
  tot_orgs: '         20#    ex., 1'
  total_offspring: '  21#    ex., 0'
num cols: 10
num cols all na: 0
num cols any na: 0
num na: 0
num rows: 3697
num rows all na: 0
num rows any na: 0
size: 7M

# Create a Tree with Target Phylogeny Structure

In [11]:
# map id to anytree node
nodes = defaultdict(anytree.AnyNode)
for __, row in target_phylogeny_df.iterrows():
    node = nodes[row['id']]
    node.id = row['id']
    node.origin_time = row['origin_time']
    if 'NONE' not in row['ancestor_list']:
        ancestor_id = ip.popsingleton(
            eval(row['ancestor_list'])
        )
        node.parent = nodes[ancestor_id]

roots = {node.root for node in nodes.values()}

In [12]:
root = ip.popsingleton(roots)
root.height

3152

In [13]:
max_origin_time = target_phylogeny_df['origin_time'].max()
max_origin_time

5000

In [14]:
mean_leaf_origin_time = np.mean([
    leaf.origin_time
    for leaf in root.leaves
])
mean_leaf_origin_time

4999.708333333333

# Pick Parameters for Hereditary Stratigraphic Columns

In [15]:
def make_conditions(num_generations: int) -> pd.DataFrame:
    res = []
    for condemner_factory, target_column_bits, differentia_bit_width in it.product(
        [
            hstrat.StratumRetentionCondemnerTaperedDepthProportionalResolution,
            hstrat.StratumRetentionCondemnerRecencyProportionalResolution,
        ],
        [
            64,
            64 * 8,
            64 * 64,
        ],
        [
            1,
            8,
            64,
        ],
    ):
        policy_param = doubling_search(
            lambda x: \
                condemner_factory(x + 1).CalcNumStrataRetainedExact(num_generations)
                * differentia_bit_width > target_column_bits or x >= num_generations,
            {
                hstrat.StratumRetentionCondemnerTaperedDepthProportionalResolution: 1,
                hstrat.StratumRetentionCondemnerRecencyProportionalResolution: 0,
            }[condemner_factory],
        )

        actual_column_strata = condemner_factory(policy_param).CalcNumStrataRetainedExact(num_generations)
        actual_column_bits = actual_column_strata * differentia_bit_width

        res.append({
            'Retention Policy' : condemner_factory.__name__[25:],
            'Differentia Bit Width' : differentia_bit_width,
            'Retention Policy Resolution Parameter' : policy_param,
            'Target Retained Bits' : target_column_bits,
            'Actual Retained Bits' : actual_column_bits,
            'Retained Bits Error' : actual_column_bits - target_column_bits,
            'Actual Retained Strata' : actual_column_strata,
            'condemner' : condemner_factory(policy_param),
        })
    return pd.DataFrame.from_records(res)

In [16]:
conditions_df = make_conditions(int(mean_leaf_origin_time))
conditions_df.drop('condemner', axis=1)

,Retention Policy,Differentia Bit Width,Retention Policy Resolution Parameter,Target Retained Bits,Actual Retained Bits,Retained Bits Error,Actual Retained Strata
0,TaperedDepthProportionalResolution,1,31,64,63,-1,63
1,TaperedDepthProportionalResolution,8,3,64,56,-8,7
2,TaperedDepthProportionalResolution,64,1,64,192,128,3
3,TaperedDepthProportionalResolution,1,255,512,511,-1,511
4,TaperedDepthProportionalResolution,8,31,512,504,-8,63
5,TaperedDepthProportionalResolution,64,3,512,448,-64,7
6,TaperedDepthProportionalResolution,1,2048,4096,4096,0,4096
7,TaperedDepthProportionalResolution,8,255,4096,4088,-8,511
8,TaperedDepthProportionalResolution,64,31,4096,4032,-64,63
9,RecencyProportionalResolution,1,5,64,59,-5,59
10,RecencyProportionalResolution,8,0,64,56,-8,7
11,RecencyProportionalResolution,64,0,64,448,384,7
12,RecencyProportionalResolution,1,71,512,507,-5,507
13,RecencyProportionalResolution,8,5,512,472,-40,59
14,RecencyProportionalResolution,64,0,512,448,-64,7
15,RecencyProportionalResolution,1,1596,4096,4096,0,4096
16,RecencyProportionalResolution,8,71,4096,4056,-40,507
17,RecencyProportionalResolution,64,5,4096,3776,-320,59

# Set Up Ancestor Column

In [17]:
bundle = hstrat.HereditaryStratigraphicColumnBundle({
    kn.pack({
        'differentia' : row['Differentia Bit Width'],
        'policy' : row['Retention Policy'],
        'resolution' : row['Retention Policy Resolution Parameter'],
        'target_bits' : row['Target Retained Bits'],
        'actual_bits' : row['Actual Retained Bits'],
        'bits_error' : row['Retained Bits Error'],
        'actual_strata' : row['Actual Retained Strata'],
    }) \
        : hstrat.HereditaryStratigraphicColumn(
            stratum_differentia_bit_width=row['Differentia Bit Width'],
            stratum_retention_condemner=row['condemner'],
    )
    for __, row in conditions_df.iterrows()
})

# Simulate Inheritance of Ancestor Column Down Phylogenetic Tree

In [18]:
root = ip.popsingleton(roots)
root.hstrat_column = bundle

for node in anytree.LevelOrderIter(ip.popsingleton(roots)):
    parent = node.parent
    if parent is not None:
        node.hstrat_column = parent.hstrat_column.Clone()
        for __ in range(node.origin_time - parent.origin_time): node.hstrat_column.DepositStratum()

# Extract Pairwise MRCA Estimates for Extant Organisms

In [19]:
# impl -> mean retained bits
mean_retained_bits = {
    impl: np.mean([
        node.hstrat_column.GetNumStrataRetained()[impl]
        * int(kn.unpack(impl)['differentia'])
        for node in root.leaves
    ])
    for impl in bundle
}

records = [
    {
        **{
            'Mean Actual Retained Bits': v,
        },
        **kn.unpack(k)
    }
    for k, v in mean_retained_bits.items()
]
actual_retained_bits_df = pd.DataFrame.from_records(records)
actual_retained_bits_df.to_csv(
    f'a=actual_retained_bits+source={data_filename}',
)

actual_retained_bits_df

,Mean Actual Retained Bits,actual_bits,actual_strata,bits_error,differentia,policy,resolution,target_bits,_
0,63.000000,63,63,-1,1,TaperedDepthProportionalResolution,31,64,actual_bits=63+actual_strata=63+bits_error=-1+...
1,56.000000,56,7,-8,8,TaperedDepthProportionalResolution,3,64,actual_bits=56+actual_strata=7+bits_error=-8+d...
2,192.000000,192,3,128,64,TaperedDepthProportionalResolution,1,64,actual_bits=192+actual_strata=3+bits_error=128...
3,510.208333,511,511,-1,1,TaperedDepthProportionalResolution,255,512,actual_bits=511+actual_strata=511+bits_error=-...
4,504.000000,504,63,-8,8,TaperedDepthProportionalResolution,31,512,actual_bits=504+actual_strata=63+bits_error=-8...
5,448.000000,448,7,-64,64,TaperedDepthProportionalResolution,3,512,actual_bits=448+actual_strata=7+bits_error=-64...
6,4096.000000,4096,4096,0,1,TaperedDepthProportionalResolution,2048,4096,actual_bits=4096+actual_strata=4096+bits_error...
7,4081.666667,4088,511,-8,8,TaperedDepthProportionalResolution,255,4096,actual_bits=4088+actual_strata=511+bits_error=...
8,4032.000000,4032,63,-64,64,TaperedDepthProportionalResolution,31,4096,actual_bits=4032+actual_strata=63+bits_error=-...
9,58.361111,59,59,-5,1,RecencyProportionalResolution,5,64,actual_bits=59+actual_strata=59+bits_error=-5+...
10,50.888889,56,7,-8,8,RecencyProportionalResolution,0,64,actual_bits=56+actual_strata=7+bits_error=-8+d...
11,407.111111,448,7,384,64,RecencyProportionalResolution,0,64,actual_bits=448+actual_strata=7+bits_error=384...
12,506.361111,507,507,-5,1,RecencyProportionalResolution,71,512,actual_bits=507+actual_strata=507+bits_error=-...
13,466.888889,472,59,-40,8,RecencyProportionalResolution,5,512,actual_bits=472+actual_strata=59+bits_error=-4...
14,407.111111,448,7,-64,64,RecencyProportionalResolution,0,512,actual_bits=448+actual_strata=7+bits_error=-64...
15,4096.944444,4096,4096,0,1,RecencyProportionalResolution,1596,4096,actual_bits=4096+actual_strata=4096+bits_error...
16,4050.888889,4056,507,-40,8,RecencyProportionalResolution,71,4096,actual_bits=4056+actual_strata=507+bits_error=...
17,3735.111111,3776,59,-320,64,RecencyProportionalResolution,5,4096,actual_bits=3776+actual_strata=59+bits_error=-...

In [20]:
res = []
for extant1, extant2 in tqdm([*it.product(root.leaves, root.leaves)]):
    if extant1 != extant2:
        bounds = extant1.hstrat_column.CalcRankOfMrcaBoundsWith(extant2.hstrat_column)
        for impl in extant1.hstrat_column:
            res.append({
                'Column Configuration' \
                    : impl,
                'Differentia Bit Width' \
                    : kn.unpack(impl)['differentia'],
                'Stratum Retention Policy' \
                    : kn.unpack(impl)['policy'],
                'Stratum Retention Policy Resolution Parameter' \
                    : kn.unpack(impl)['resolution'],
                'Stratigraphic Column Expected Retained Bits' \
                    : kn.unpack(impl)['actual_bits'],
                'Stratigraphic Column Mean Actual Retained Bits' \
                    : mean_retained_bits[impl],
                'Stratigraphic Column Target Retained Bits' \
                    : kn.unpack(impl)['target_bits'],
                'Stratigraphic Column Expected Retained Bits Error' \
                    : kn.unpack(impl)['bits_error'],
                'Stratigraphic Column Actual Num Retained Strata' \
                    : kn.unpack(impl)['actual_strata'],
                'Taxon Compared From' \
                    : extant1.id,
                'Taxon Compared To' \
                    : extant2.id,
                'Generation of Taxon Compared From' \
                    : extant1.hstrat_column.GetNumStrataDeposited(),
                'Generation of Taxon Compared To' \
                    : extant2.hstrat_column.GetNumStrataDeposited(),
                'Generation Of MRCA Lower Bound (inclusive)' \
                    : opyt.apply_if(
                        bounds[impl],
                        lambda x: x[0],
                    ),
                'Generation Of MRCA Upper Bound (exclusive)' \
                    : opyt.apply_if(
                        bounds[impl],
                        lambda x: x[1],
                    ),
                'MRCA Bound Confidence' \
                    : extant1.hstrat_column[impl].CalcRankOfMrcaBoundsWithProvidedConfidenceLevel(),
                'Rank of Earliest Detectable Mrca With' \
                    : extant1.hstrat_column[impl].CalcRankOfEarliestDetectableMrcaWith(extant2.hstrat_column[impl]),
            })

res_df = pd.DataFrame.from_records(res)

  0%|          | 0/5184 [00:00<?, ?it/s]

  0%|          | 3/5184 [00:00<03:10, 27.13it/s]

  0%|          | 5/5184 [00:00<03:37, 23.86it/s]

  0%|          | 7/5184 [00:00<03:54, 22.10it/s]

  0%|          | 9/5184 [00:00<04:05, 21.04it/s]

  0%|          | 11/5184 [00:00<04:13, 20.40it/s]

  0%|          | 13/5184 [00:00<04:19, 19.97it/s]

  0%|          | 15/5184 [00:00<04:22, 19.68it/s]

  0%|          | 17/5184 [00:00<04:25, 19.49it/s]

  0%|          | 19/5184 [00:00<04:27, 19.31it/s]

  0%|          | 21/5184 [00:01<04:28, 19.20it/s]

  0%|          | 23/5184 [00:01<04:30, 19.11it/s]

  0%|          | 25/5184 [00:01<04:30, 19.08it/s]

  1%|          | 27/5184 [00:01<04:30, 19.05it/s]

  1%|          | 29/5184 [00:01<04:31, 19.02it/s]

  1%|          | 31/5184 [00:01<04:32, 18.94it/s]

  1%|          | 33/5184 [00:01<04:33, 18.86it/s]

  1%|          | 35/5184 [00:01<04:30, 19.05it/s]

  1%|          | 37/5184 [00:01<04:28, 19.18it/s]

  1%|          | 39/5184 [00:02<04:27, 19.27it/s]

  1%|          | 41/5184 [00:02<04:26, 19.32it/s]

  1%|          | 43/5184 [00:02<04:25, 19.39it/s]

  1%|          | 45/5184 [00:02<04:24, 19.43it/s]

  1%|          | 47/5184 [00:02<04:23, 19.46it/s]

  1%|          | 49/5184 [00:02<04:23, 19.50it/s]

  1%|          | 51/5184 [00:02<04:23, 19.50it/s]

  1%|          | 53/5184 [00:02<04:22, 19.54it/s]

  1%|          | 56/5184 [00:02<04:20, 19.67it/s]

  1%|          | 59/5184 [00:03<04:18, 19.84it/s]

  1%|          | 61/5184 [00:03<04:19, 19.71it/s]

  1%|          | 64/5184 [00:03<04:17, 19.86it/s]

  1%|▏         | 67/5184 [00:03<04:16, 19.98it/s]

  1%|▏         | 70/5184 [00:03<04:14, 20.07it/s]

  1%|▏         | 73/5184 [00:03<04:16, 19.95it/s]

  1%|▏         | 76/5184 [00:03<03:54, 21.82it/s]

  2%|▏         | 79/5184 [00:03<04:04, 20.88it/s]

  2%|▏         | 82/5184 [00:04<04:11, 20.30it/s]

  2%|▏         | 85/5184 [00:04<04:15, 19.96it/s]

  2%|▏         | 88/5184 [00:04<04:18, 19.71it/s]

  2%|▏         | 90/5184 [00:04<04:21, 19.48it/s]

  2%|▏         | 92/5184 [00:04<04:22, 19.38it/s]

  2%|▏         | 94/5184 [00:04<04:23, 19.29it/s]

  2%|▏         | 96/5184 [00:04<04:24, 19.21it/s]

  2%|▏         | 98/5184 [00:04<04:25, 19.19it/s]

  2%|▏         | 100/5184 [00:05<04:25, 19.14it/s]

  2%|▏         | 102/5184 [00:05<04:26, 19.06it/s]

  2%|▏         | 104/5184 [00:05<04:26, 19.08it/s]

  2%|▏         | 106/5184 [00:05<04:24, 19.17it/s]

  2%|▏         | 108/5184 [00:05<04:22, 19.33it/s]

  2%|▏         | 110/5184 [00:05<04:21, 19.44it/s]

  2%|▏         | 112/5184 [00:05<04:19, 19.53it/s]

  2%|▏         | 114/5184 [00:05<04:18, 19.58it/s]

  2%|▏         | 116/5184 [00:05<04:18, 19.63it/s]

  2%|▏         | 118/5184 [00:06<04:17, 19.67it/s]

  2%|▏         | 120/5184 [00:06<04:17, 19.67it/s]

  2%|▏         | 122/5184 [00:06<04:17, 19.66it/s]

  2%|▏         | 124/5184 [00:06<04:17, 19.65it/s]

  2%|▏         | 127/5184 [00:06<04:14, 19.84it/s]

  3%|▎         | 130/5184 [00:06<04:13, 19.97it/s]

  3%|▎         | 133/5184 [00:06<04:11, 20.06it/s]

  3%|▎         | 136/5184 [00:06<04:10, 20.12it/s]

  3%|▎         | 139/5184 [00:07<04:10, 20.18it/s]

  3%|▎         | 142/5184 [00:07<04:09, 20.19it/s]

  3%|▎         | 145/5184 [00:07<04:11, 20.05it/s]

  3%|▎         | 148/5184 [00:07<03:50, 21.88it/s]

  3%|▎         | 151/5184 [00:07<04:00, 20.92it/s]

  3%|▎         | 154/5184 [00:07<04:05, 20.48it/s]

  3%|▎         | 157/5184 [00:07<04:09, 20.15it/s]

  3%|▎         | 160/5184 [00:08<04:12, 19.90it/s]

  3%|▎         | 163/5184 [00:08<04:14, 19.76it/s]

  3%|▎         | 165/5184 [00:08<04:15, 19.65it/s]

  3%|▎         | 167/5184 [00:08<04:16, 19.57it/s]

  3%|▎         | 169/5184 [00:08<04:17, 19.49it/s]

  3%|▎         | 171/5184 [00:08<04:17, 19.48it/s]

  3%|▎         | 173/5184 [00:08<04:17, 19.45it/s]

  3%|▎         | 175/5184 [00:08<04:18, 19.34it/s]

  3%|▎         | 177/5184 [00:08<04:18, 19.35it/s]

  3%|▎         | 179/5184 [00:09<04:16, 19.54it/s]

  3%|▎         | 181/5184 [00:09<04:14, 19.67it/s]

  4%|▎         | 183/5184 [00:09<04:13, 19.76it/s]

  4%|▎         | 186/5184 [00:09<04:11, 19.86it/s]

  4%|▎         | 189/5184 [00:09<04:10, 19.91it/s]

  4%|▎         | 191/5184 [00:09<04:10, 19.94it/s]

  4%|▎         | 194/5184 [00:09<04:09, 20.00it/s]

  4%|▍         | 196/5184 [00:09<04:09, 19.99it/s]

  4%|▍         | 199/5184 [00:10<04:07, 20.12it/s]

  4%|▍         | 202/5184 [00:10<04:06, 20.18it/s]

  4%|▍         | 205/5184 [00:10<04:04, 20.36it/s]

  4%|▍         | 208/5184 [00:10<04:02, 20.49it/s]

  4%|▍         | 211/5184 [00:10<04:02, 20.55it/s]

  4%|▍         | 214/5184 [00:10<04:00, 20.64it/s]

  4%|▍         | 217/5184 [00:10<04:02, 20.45it/s]

  4%|▍         | 220/5184 [00:11<03:42, 22.35it/s]

  4%|▍         | 223/5184 [00:11<03:52, 21.30it/s]

  4%|▍         | 226/5184 [00:11<03:59, 20.70it/s]

  4%|▍         | 229/5184 [00:11<04:03, 20.35it/s]

  4%|▍         | 232/5184 [00:11<04:06, 20.07it/s]

  5%|▍         | 235/5184 [00:11<04:08, 19.92it/s]

  5%|▍         | 238/5184 [00:11<04:10, 19.76it/s]

  5%|▍         | 240/5184 [00:12<04:11, 19.63it/s]

  5%|▍         | 242/5184 [00:12<04:13, 19.50it/s]

  5%|▍         | 244/5184 [00:12<04:14, 19.43it/s]

  5%|▍         | 246/5184 [00:12<04:14, 19.39it/s]

  5%|▍         | 248/5184 [00:12<04:14, 19.40it/s]

  5%|▍         | 250/5184 [00:12<04:13, 19.47it/s]

  5%|▍         | 253/5184 [00:12<04:10, 19.67it/s]

  5%|▍         | 256/5184 [00:12<04:08, 19.79it/s]

  5%|▍         | 259/5184 [00:13<04:07, 19.89it/s]

  5%|▌         | 262/5184 [00:13<04:06, 19.96it/s]

  5%|▌         | 264/5184 [00:13<04:06, 19.96it/s]

  5%|▌         | 266/5184 [00:13<04:06, 19.94it/s]

  5%|▌         | 268/5184 [00:13<04:06, 19.95it/s]

  5%|▌         | 271/5184 [00:13<04:04, 20.10it/s]

  5%|▌         | 274/5184 [00:13<04:02, 20.29it/s]

  5%|▌         | 277/5184 [00:13<04:00, 20.42it/s]

  5%|▌         | 280/5184 [00:14<03:59, 20.49it/s]

  5%|▌         | 283/5184 [00:14<03:58, 20.54it/s]

  6%|▌         | 286/5184 [00:14<03:58, 20.56it/s]

  6%|▌         | 289/5184 [00:14<04:00, 20.39it/s]

  6%|▌         | 292/5184 [00:14<04:05, 19.95it/s]

  6%|▌         | 295/5184 [00:14<03:42, 21.97it/s]

  6%|▌         | 298/5184 [00:14<03:51, 21.07it/s]

  6%|▌         | 301/5184 [00:15<03:59, 20.40it/s]

  6%|▌         | 304/5184 [00:15<04:03, 20.04it/s]

  6%|▌         | 307/5184 [00:15<04:05, 19.83it/s]

  6%|▌         | 310/5184 [00:15<04:07, 19.72it/s]

  6%|▌         | 312/5184 [00:15<04:08, 19.57it/s]

  6%|▌         | 314/5184 [00:15<04:09, 19.51it/s]

  6%|▌         | 316/5184 [00:15<04:10, 19.45it/s]

  6%|▌         | 318/5184 [00:15<04:10, 19.42it/s]

  6%|▌         | 320/5184 [00:16<04:10, 19.42it/s]

  6%|▌         | 322/5184 [00:16<04:09, 19.48it/s]

  6%|▋         | 324/5184 [00:16<04:08, 19.58it/s]

  6%|▋         | 326/5184 [00:16<04:06, 19.68it/s]

  6%|▋         | 328/5184 [00:16<04:06, 19.68it/s]

  6%|▋         | 331/5184 [00:16<04:04, 19.81it/s]

  6%|▋         | 334/5184 [00:16<04:03, 19.90it/s]

  6%|▋         | 336/5184 [00:16<04:03, 19.92it/s]

  7%|▋         | 338/5184 [00:16<04:08, 19.51it/s]

  7%|▋         | 340/5184 [00:17<04:15, 18.94it/s]

  7%|▋         | 342/5184 [00:17<04:12, 19.15it/s]

  7%|▋         | 345/5184 [00:17<04:06, 19.63it/s]

  7%|▋         | 348/5184 [00:17<04:02, 19.94it/s]

  7%|▋         | 351/5184 [00:17<03:59, 20.15it/s]

  7%|▋         | 354/5184 [00:17<04:00, 20.12it/s]

  7%|▋         | 357/5184 [00:17<03:58, 20.26it/s]

  7%|▋         | 360/5184 [00:18<03:55, 20.44it/s]

  7%|▋         | 363/5184 [00:18<04:01, 20.00it/s]

  7%|▋         | 366/5184 [00:18<03:39, 21.98it/s]

  7%|▋         | 369/5184 [00:18<03:48, 21.11it/s]

  7%|▋         | 372/5184 [00:18<03:54, 20.56it/s]

  7%|▋         | 375/5184 [00:18<03:58, 20.18it/s]

  7%|▋         | 378/5184 [00:18<04:01, 19.94it/s]

  7%|▋         | 381/5184 [00:19<04:02, 19.78it/s]

  7%|▋         | 383/5184 [00:19<04:04, 19.60it/s]

  7%|▋         | 385/5184 [00:19<04:05, 19.53it/s]

  7%|▋         | 387/5184 [00:19<04:06, 19.47it/s]

  8%|▊         | 389/5184 [00:19<04:07, 19.40it/s]

  8%|▊         | 391/5184 [00:19<04:06, 19.42it/s]

  8%|▊         | 393/5184 [00:19<04:06, 19.42it/s]

  8%|▊         | 395/5184 [00:19<04:05, 19.54it/s]

  8%|▊         | 397/5184 [00:19<04:03, 19.64it/s]

  8%|▊         | 399/5184 [00:20<04:02, 19.75it/s]

  8%|▊         | 401/5184 [00:20<04:01, 19.79it/s]

  8%|▊         | 403/5184 [00:20<04:02, 19.68it/s]

  8%|▊         | 406/5184 [00:20<04:01, 19.78it/s]

  8%|▊         | 408/5184 [00:20<04:01, 19.79it/s]

  8%|▊         | 410/5184 [00:20<04:02, 19.70it/s]

  8%|▊         | 412/5184 [00:20<04:01, 19.77it/s]

  8%|▊         | 415/5184 [00:20<03:58, 19.95it/s]

  8%|▊         | 418/5184 [00:20<03:56, 20.13it/s]

  8%|▊         | 421/5184 [00:21<03:54, 20.27it/s]

  8%|▊         | 424/5184 [00:21<03:55, 20.22it/s]

  8%|▊         | 427/5184 [00:21<03:53, 20.35it/s]

  8%|▊         | 430/5184 [00:21<03:52, 20.42it/s]

  8%|▊         | 433/5184 [00:21<03:53, 20.36it/s]

  8%|▊         | 436/5184 [00:21<03:56, 20.06it/s]

  8%|▊         | 439/5184 [00:21<03:34, 22.09it/s]

  9%|▊         | 442/5184 [00:22<03:44, 21.09it/s]

  9%|▊         | 445/5184 [00:22<03:51, 20.46it/s]

  9%|▊         | 448/5184 [00:22<03:56, 20.04it/s]

  9%|▊         | 451/5184 [00:22<03:59, 19.77it/s]

  9%|▉         | 454/5184 [00:22<04:00, 19.63it/s]

  9%|▉         | 456/5184 [00:22<04:02, 19.51it/s]

  9%|▉         | 458/5184 [00:22<04:03, 19.39it/s]

  9%|▉         | 460/5184 [00:23<04:03, 19.36it/s]

  9%|▉         | 462/5184 [00:23<04:04, 19.32it/s]

  9%|▉         | 464/5184 [00:23<04:07, 19.09it/s]

  9%|▉         | 466/5184 [00:23<04:05, 19.24it/s]

  9%|▉         | 469/5184 [00:23<04:02, 19.47it/s]

  9%|▉         | 471/5184 [00:23<04:00, 19.61it/s]

  9%|▉         | 474/5184 [00:23<03:58, 19.76it/s]

  9%|▉         | 476/5184 [00:23<03:57, 19.83it/s]

  9%|▉         | 478/5184 [00:23<03:56, 19.87it/s]

  9%|▉         | 481/5184 [00:24<03:55, 19.93it/s]

  9%|▉         | 484/5184 [00:24<03:55, 19.95it/s]

  9%|▉         | 487/5184 [00:24<03:54, 20.07it/s]

  9%|▉         | 490/5184 [00:24<03:51, 20.29it/s]

 10%|▉         | 493/5184 [00:24<03:49, 20.44it/s]

 10%|▉         | 496/5184 [00:24<03:48, 20.52it/s]

 10%|▉         | 499/5184 [00:24<03:47, 20.56it/s]

 10%|▉         | 502/5184 [00:25<03:47, 20.61it/s]

 10%|▉         | 505/5184 [00:25<03:49, 20.36it/s]

 10%|▉         | 508/5184 [00:25<03:52, 20.08it/s]

 10%|▉         | 511/5184 [00:25<03:55, 19.86it/s]

 10%|▉         | 514/5184 [00:25<03:33, 21.91it/s]

 10%|▉         | 517/5184 [00:25<03:41, 21.04it/s]

 10%|█         | 520/5184 [00:26<03:48, 20.43it/s]

 10%|█         | 523/5184 [00:26<03:52, 20.07it/s]

 10%|█         | 526/5184 [00:26<03:55, 19.77it/s]

 10%|█         | 528/5184 [00:26<03:57, 19.62it/s]

 10%|█         | 530/5184 [00:26<03:58, 19.54it/s]

 10%|█         | 532/5184 [00:26<03:59, 19.42it/s]

 10%|█         | 534/5184 [00:26<04:00, 19.36it/s]

 10%|█         | 536/5184 [00:26<04:00, 19.36it/s]

 10%|█         | 538/5184 [00:26<03:59, 19.43it/s]

 10%|█         | 540/5184 [00:27<03:56, 19.60it/s]

 10%|█         | 543/5184 [00:27<03:54, 19.75it/s]

 11%|█         | 545/5184 [00:27<03:56, 19.65it/s]

 11%|█         | 548/5184 [00:27<03:53, 19.81it/s]

 11%|█         | 551/5184 [00:27<03:52, 19.92it/s]

 11%|█         | 554/5184 [00:27<03:51, 19.97it/s]

 11%|█         | 557/5184 [00:27<03:50, 20.06it/s]

 11%|█         | 560/5184 [00:28<03:49, 20.17it/s]

 11%|█         | 563/5184 [00:28<03:47, 20.34it/s]

 11%|█         | 566/5184 [00:28<03:45, 20.45it/s]

 11%|█         | 569/5184 [00:28<03:49, 20.10it/s]

 11%|█         | 572/5184 [00:28<03:50, 20.02it/s]

 11%|█         | 575/5184 [00:28<03:50, 20.01it/s]

 11%|█         | 578/5184 [00:28<03:53, 19.72it/s]

 11%|█         | 580/5184 [00:29<03:58, 19.27it/s]

 11%|█         | 582/5184 [00:29<03:59, 19.24it/s]

 11%|█▏        | 584/5184 [00:29<04:00, 19.16it/s]

 11%|█▏        | 587/5184 [00:29<03:36, 21.20it/s]

 11%|█▏        | 590/5184 [00:29<03:44, 20.43it/s]

 11%|█▏        | 593/5184 [00:29<03:49, 20.02it/s]

 11%|█▏        | 596/5184 [00:29<03:52, 19.74it/s]

 12%|█▏        | 599/5184 [00:29<03:54, 19.55it/s]

 12%|█▏        | 601/5184 [00:30<03:58, 19.20it/s]

 12%|█▏        | 603/5184 [00:30<03:59, 19.11it/s]

 12%|█▏        | 605/5184 [00:30<04:01, 18.98it/s]

 12%|█▏        | 607/5184 [00:30<04:02, 18.85it/s]

 12%|█▏        | 609/5184 [00:30<04:04, 18.72it/s]

 12%|█▏        | 611/5184 [00:30<04:02, 18.89it/s]

 12%|█▏        | 613/5184 [00:30<04:00, 19.00it/s]

 12%|█▏        | 615/5184 [00:30<03:58, 19.19it/s]

 12%|█▏        | 617/5184 [00:30<03:55, 19.37it/s]

 12%|█▏        | 619/5184 [00:31<03:53, 19.53it/s]

 12%|█▏        | 621/5184 [00:31<03:52, 19.62it/s]

 12%|█▏        | 623/5184 [00:31<03:51, 19.68it/s]

 12%|█▏        | 625/5184 [00:31<03:56, 19.26it/s]

 12%|█▏        | 627/5184 [00:31<03:57, 19.21it/s]

 12%|█▏        | 629/5184 [00:31<03:56, 19.24it/s]

 12%|█▏        | 631/5184 [00:31<03:54, 19.40it/s]

 12%|█▏        | 633/5184 [00:31<03:54, 19.39it/s]

 12%|█▏        | 635/5184 [00:31<03:53, 19.52it/s]

 12%|█▏        | 638/5184 [00:32<03:49, 19.77it/s]

 12%|█▏        | 641/5184 [00:32<03:47, 19.94it/s]

 12%|█▏        | 643/5184 [00:32<03:48, 19.89it/s]

 12%|█▏        | 645/5184 [00:32<03:53, 19.46it/s]

 12%|█▏        | 647/5184 [00:32<03:54, 19.37it/s]

 13%|█▎        | 649/5184 [00:32<03:53, 19.42it/s]

 13%|█▎        | 651/5184 [00:32<03:53, 19.40it/s]

 13%|█▎        | 653/5184 [00:32<03:53, 19.40it/s]

 13%|█▎        | 655/5184 [00:32<03:54, 19.33it/s]

 13%|█▎        | 657/5184 [00:32<03:55, 19.20it/s]

 13%|█▎        | 660/5184 [00:33<03:33, 21.24it/s]

 13%|█▎        | 663/5184 [00:33<03:40, 20.52it/s]

 13%|█▎        | 666/5184 [00:33<03:47, 19.88it/s]

 13%|█▎        | 669/5184 [00:33<03:50, 19.60it/s]

 13%|█▎        | 671/5184 [00:33<03:52, 19.42it/s]

 13%|█▎        | 673/5184 [00:33<03:52, 19.37it/s]

 13%|█▎        | 675/5184 [00:33<03:53, 19.32it/s]

 13%|█▎        | 677/5184 [00:34<03:53, 19.26it/s]

 13%|█▎        | 679/5184 [00:34<03:54, 19.21it/s]

 13%|█▎        | 681/5184 [00:34<03:54, 19.21it/s]

 13%|█▎        | 683/5184 [00:34<03:52, 19.40it/s]

 13%|█▎        | 685/5184 [00:34<03:49, 19.56it/s]

 13%|█▎        | 688/5184 [00:34<03:48, 19.70it/s]

 13%|█▎        | 690/5184 [00:34<03:47, 19.76it/s]

 13%|█▎        | 693/5184 [00:34<03:46, 19.86it/s]

 13%|█▎        | 695/5184 [00:34<03:45, 19.89it/s]

 13%|█▎        | 698/5184 [00:35<03:44, 19.94it/s]

 14%|█▎        | 701/5184 [00:35<03:44, 19.98it/s]

 14%|█▎        | 704/5184 [00:35<03:41, 20.24it/s]

 14%|█▎        | 707/5184 [00:35<03:40, 20.34it/s]

 14%|█▎        | 710/5184 [00:35<03:38, 20.47it/s]

 14%|█▍        | 713/5184 [00:35<03:37, 20.57it/s]

 14%|█▍        | 716/5184 [00:35<03:36, 20.60it/s]

 14%|█▍        | 719/5184 [00:36<03:36, 20.66it/s]

 14%|█▍        | 722/5184 [00:36<03:39, 20.32it/s]

 14%|█▍        | 725/5184 [00:36<03:43, 19.98it/s]

 14%|█▍        | 728/5184 [00:36<03:45, 19.73it/s]

 14%|█▍        | 730/5184 [00:36<03:48, 19.50it/s]

 14%|█▍        | 733/5184 [00:36<03:26, 21.54it/s]

 14%|█▍        | 736/5184 [00:36<03:35, 20.67it/s]

 14%|█▍        | 739/5184 [00:37<03:40, 20.15it/s]

 14%|█▍        | 742/5184 [00:37<03:44, 19.82it/s]

 14%|█▍        | 745/5184 [00:37<03:46, 19.60it/s]

 14%|█▍        | 747/5184 [00:37<03:47, 19.48it/s]

 14%|█▍        | 749/5184 [00:37<03:49, 19.35it/s]

 14%|█▍        | 751/5184 [00:37<03:50, 19.25it/s]

 15%|█▍        | 753/5184 [00:37<03:49, 19.27it/s]

 15%|█▍        | 755/5184 [00:37<03:48, 19.41it/s]

 15%|█▍        | 757/5184 [00:38<03:47, 19.47it/s]

 15%|█▍        | 759/5184 [00:38<03:45, 19.59it/s]

 15%|█▍        | 761/5184 [00:38<03:44, 19.67it/s]

 15%|█▍        | 763/5184 [00:38<03:44, 19.70it/s]

 15%|█▍        | 765/5184 [00:38<03:44, 19.71it/s]

 15%|█▍        | 767/5184 [00:38<03:43, 19.77it/s]

 15%|█▍        | 769/5184 [00:38<03:42, 19.84it/s]

 15%|█▍        | 771/5184 [00:38<03:43, 19.76it/s]

 15%|█▍        | 773/5184 [00:38<03:42, 19.82it/s]

 15%|█▍        | 776/5184 [00:38<03:39, 20.08it/s]

 15%|█▌        | 779/5184 [00:39<03:38, 20.15it/s]

 15%|█▌        | 782/5184 [00:39<03:36, 20.30it/s]

 15%|█▌        | 785/5184 [00:39<03:37, 20.25it/s]

 15%|█▌        | 788/5184 [00:39<03:35, 20.41it/s]

 15%|█▌        | 791/5184 [00:39<03:34, 20.48it/s]

 15%|█▌        | 794/5184 [00:39<03:36, 20.24it/s]

 15%|█▌        | 797/5184 [00:39<03:38, 20.03it/s]

 15%|█▌        | 800/5184 [00:40<03:41, 19.78it/s]

 15%|█▌        | 802/5184 [00:40<03:44, 19.56it/s]

 16%|█▌        | 805/5184 [00:40<03:22, 21.58it/s]

 16%|█▌        | 808/5184 [00:40<03:31, 20.72it/s]

 16%|█▌        | 811/5184 [00:40<03:37, 20.13it/s]

 16%|█▌        | 814/5184 [00:40<03:40, 19.82it/s]

 16%|█▌        | 817/5184 [00:40<03:42, 19.61it/s]

 16%|█▌        | 819/5184 [00:41<03:44, 19.42it/s]

 16%|█▌        | 821/5184 [00:41<03:45, 19.32it/s]

 16%|█▌        | 823/5184 [00:41<03:45, 19.30it/s]

 16%|█▌        | 825/5184 [00:41<03:48, 19.11it/s]

 16%|█▌        | 827/5184 [00:41<03:45, 19.30it/s]

 16%|█▌        | 829/5184 [00:41<03:43, 19.49it/s]

 16%|█▌        | 831/5184 [00:41<03:41, 19.64it/s]

 16%|█▌        | 833/5184 [00:41<03:40, 19.73it/s]

 16%|█▌        | 835/5184 [00:41<03:39, 19.77it/s]

 16%|█▌        | 837/5184 [00:42<03:39, 19.81it/s]

 16%|█▌        | 839/5184 [00:42<03:39, 19.82it/s]

 16%|█▌        | 842/5184 [00:42<03:38, 19.90it/s]

 16%|█▋        | 844/5184 [00:42<03:37, 19.92it/s]

 16%|█▋        | 847/5184 [00:42<03:36, 20.05it/s]

 16%|█▋        | 850/5184 [00:42<03:34, 20.23it/s]

 16%|█▋        | 853/5184 [00:42<03:32, 20.40it/s]

 17%|█▋        | 856/5184 [00:42<03:32, 20.41it/s]

 17%|█▋        | 859/5184 [00:43<03:31, 20.49it/s]

 17%|█▋        | 862/5184 [00:43<03:30, 20.53it/s]

 17%|█▋        | 865/5184 [00:43<03:32, 20.32it/s]

 17%|█▋        | 868/5184 [00:43<03:36, 19.97it/s]

 17%|█▋        | 870/5184 [00:43<03:38, 19.77it/s]

 17%|█▋        | 872/5184 [00:43<03:40, 19.55it/s]

 17%|█▋        | 874/5184 [00:43<03:42, 19.35it/s]

 17%|█▋        | 876/5184 [00:43<03:44, 19.23it/s]

 17%|█▋        | 879/5184 [00:44<03:22, 21.26it/s]

 17%|█▋        | 882/5184 [00:44<03:29, 20.50it/s]

 17%|█▋        | 885/5184 [00:44<03:34, 20.04it/s]

 17%|█▋        | 888/5184 [00:44<03:37, 19.71it/s]

 17%|█▋        | 891/5184 [00:44<03:39, 19.54it/s]

 17%|█▋        | 893/5184 [00:44<03:41, 19.40it/s]

 17%|█▋        | 895/5184 [00:44<03:42, 19.30it/s]

 17%|█▋        | 897/5184 [00:45<03:43, 19.22it/s]

 17%|█▋        | 899/5184 [00:45<03:40, 19.42it/s]

 17%|█▋        | 901/5184 [00:45<03:38, 19.58it/s]

 17%|█▋        | 903/5184 [00:45<03:37, 19.70it/s]

 17%|█▋        | 905/5184 [00:45<03:38, 19.60it/s]

 18%|█▊        | 908/5184 [00:45<03:36, 19.74it/s]

 18%|█▊        | 911/5184 [00:45<03:35, 19.86it/s]

 18%|█▊        | 913/5184 [00:45<03:34, 19.90it/s]

 18%|█▊        | 915/5184 [00:45<03:34, 19.91it/s]

 18%|█▊        | 918/5184 [00:46<03:32, 20.03it/s]

 18%|█▊        | 921/5184 [00:46<03:30, 20.25it/s]

 18%|█▊        | 924/5184 [00:46<03:28, 20.40it/s]

 18%|█▊        | 927/5184 [00:46<03:29, 20.37it/s]

 18%|█▊        | 930/5184 [00:46<03:27, 20.50it/s]

 18%|█▊        | 933/5184 [00:46<03:26, 20.57it/s]

 18%|█▊        | 936/5184 [00:46<03:25, 20.63it/s]

 18%|█▊        | 939/5184 [00:47<03:29, 20.24it/s]

 18%|█▊        | 942/5184 [00:47<03:32, 19.95it/s]

 18%|█▊        | 944/5184 [00:47<03:35, 19.71it/s]

 18%|█▊        | 946/5184 [00:47<03:37, 19.50it/s]

 18%|█▊        | 948/5184 [00:47<03:39, 19.32it/s]

 18%|█▊        | 951/5184 [00:47<03:17, 21.39it/s]

 18%|█▊        | 954/5184 [00:47<03:25, 20.63it/s]

 18%|█▊        | 957/5184 [00:47<03:30, 20.09it/s]

 19%|█▊        | 960/5184 [00:48<03:33, 19.78it/s]

 19%|█▊        | 963/5184 [00:48<03:35, 19.58it/s]

 19%|█▊        | 965/5184 [00:48<03:37, 19.43it/s]

 19%|█▊        | 967/5184 [00:48<03:41, 19.07it/s]

 19%|█▊        | 969/5184 [00:48<03:41, 19.04it/s]

 19%|█▊        | 971/5184 [00:48<03:38, 19.29it/s]

 19%|█▉        | 974/5184 [00:48<03:35, 19.52it/s]

 19%|█▉        | 976/5184 [00:48<03:34, 19.62it/s]

 19%|█▉        | 978/5184 [00:49<03:33, 19.72it/s]

 19%|█▉        | 980/5184 [00:49<03:32, 19.75it/s]

 19%|█▉        | 983/5184 [00:49<03:31, 19.84it/s]

 19%|█▉        | 985/5184 [00:49<03:31, 19.87it/s]

 19%|█▉        | 987/5184 [00:49<03:31, 19.87it/s]

 19%|█▉        | 989/5184 [00:49<03:31, 19.86it/s]

 19%|█▉        | 992/5184 [00:49<03:29, 20.00it/s]

 19%|█▉        | 995/5184 [00:49<03:27, 20.20it/s]

 19%|█▉        | 998/5184 [00:50<03:25, 20.35it/s]

 19%|█▉        | 1001/5184 [00:50<03:24, 20.46it/s]

 19%|█▉        | 1004/5184 [00:50<03:22, 20.61it/s]

 19%|█▉        | 1007/5184 [00:50<03:23, 20.51it/s]

 19%|█▉        | 1010/5184 [00:50<03:26, 20.26it/s]

 20%|█▉        | 1013/5184 [00:50<03:29, 19.94it/s]

 20%|█▉        | 1015/5184 [00:50<03:31, 19.70it/s]

 20%|█▉        | 1017/5184 [00:51<03:35, 19.34it/s]

 20%|█▉        | 1019/5184 [00:51<03:36, 19.20it/s]

 20%|█▉        | 1021/5184 [00:51<03:37, 19.11it/s]

 20%|█▉        | 1024/5184 [00:51<03:16, 21.14it/s]

 20%|█▉        | 1027/5184 [00:51<03:24, 20.37it/s]

 20%|█▉        | 1030/5184 [00:51<03:28, 19.91it/s]

 20%|█▉        | 1033/5184 [00:51<03:31, 19.65it/s]

 20%|█▉        | 1035/5184 [00:51<03:33, 19.47it/s]

 20%|██        | 1037/5184 [00:52<03:34, 19.33it/s]

 20%|██        | 1039/5184 [00:52<03:35, 19.25it/s]

 20%|██        | 1041/5184 [00:52<03:36, 19.16it/s]

 20%|██        | 1043/5184 [00:52<03:34, 19.35it/s]

 20%|██        | 1045/5184 [00:52<03:32, 19.52it/s]

 20%|██        | 1047/5184 [00:52<03:31, 19.58it/s]

 20%|██        | 1049/5184 [00:52<03:30, 19.66it/s]

 20%|██        | 1051/5184 [00:52<03:29, 19.74it/s]

 20%|██        | 1053/5184 [00:52<03:29, 19.76it/s]

 20%|██        | 1055/5184 [00:52<03:28, 19.77it/s]

 20%|██        | 1057/5184 [00:53<03:28, 19.81it/s]

 20%|██        | 1059/5184 [00:53<03:28, 19.80it/s]

 20%|██        | 1061/5184 [00:53<03:27, 19.82it/s]

 21%|██        | 1064/5184 [00:53<03:25, 20.05it/s]

 21%|██        | 1067/5184 [00:53<03:25, 20.04it/s]

 21%|██        | 1070/5184 [00:53<03:23, 20.20it/s]

 21%|██        | 1073/5184 [00:53<03:22, 20.30it/s]

 21%|██        | 1076/5184 [00:53<03:21, 20.38it/s]

 21%|██        | 1079/5184 [00:54<03:21, 20.39it/s]

 21%|██        | 1082/5184 [00:54<03:22, 20.23it/s]

 21%|██        | 1085/5184 [00:54<03:24, 20.00it/s]

 21%|██        | 1088/5184 [00:54<03:27, 19.73it/s]

 21%|██        | 1090/5184 [00:54<03:29, 19.50it/s]

 21%|██        | 1092/5184 [00:54<03:31, 19.36it/s]

 21%|██        | 1094/5184 [00:54<03:32, 19.23it/s]

 21%|██        | 1097/5184 [00:55<03:12, 21.26it/s]

 21%|██        | 1100/5184 [00:55<03:18, 20.53it/s]

 21%|██▏       | 1103/5184 [00:55<03:23, 20.07it/s]

 21%|██▏       | 1106/5184 [00:55<03:25, 19.81it/s]

 21%|██▏       | 1109/5184 [00:55<03:28, 19.57it/s]

 21%|██▏       | 1111/5184 [00:55<03:29, 19.44it/s]

 21%|██▏       | 1113/5184 [00:55<03:30, 19.32it/s]

 22%|██▏       | 1116/5184 [00:55<03:28, 19.54it/s]

 22%|██▏       | 1119/5184 [00:56<03:26, 19.70it/s]

 22%|██▏       | 1121/5184 [00:56<03:25, 19.77it/s]

 22%|██▏       | 1124/5184 [00:56<03:24, 19.86it/s]

 22%|██▏       | 1126/5184 [00:56<03:24, 19.84it/s]

 22%|██▏       | 1128/5184 [00:56<03:24, 19.85it/s]

 22%|██▏       | 1131/5184 [00:56<03:23, 19.96it/s]

 22%|██▏       | 1133/5184 [00:56<03:23, 19.92it/s]

 22%|██▏       | 1136/5184 [00:56<03:20, 20.18it/s]

 22%|██▏       | 1139/5184 [00:57<03:19, 20.26it/s]

 22%|██▏       | 1142/5184 [00:57<03:18, 20.39it/s]

 22%|██▏       | 1145/5184 [00:57<03:17, 20.48it/s]

 22%|██▏       | 1148/5184 [00:57<03:17, 20.45it/s]

 22%|██▏       | 1151/5184 [00:57<03:16, 20.54it/s]

 22%|██▏       | 1154/5184 [00:57<03:18, 20.34it/s]

 22%|██▏       | 1157/5184 [00:58<03:20, 20.04it/s]

 22%|██▏       | 1160/5184 [00:58<03:23, 19.77it/s]

 22%|██▏       | 1162/5184 [00:58<03:25, 19.54it/s]

 22%|██▏       | 1164/5184 [00:58<03:26, 19.43it/s]

 22%|██▏       | 1166/5184 [00:58<03:29, 19.19it/s]

 23%|██▎       | 1168/5184 [00:58<03:30, 19.08it/s]

 23%|██▎       | 1171/5184 [00:58<03:09, 21.17it/s]

 23%|██▎       | 1174/5184 [00:58<03:15, 20.52it/s]

 23%|██▎       | 1177/5184 [00:59<03:18, 20.15it/s]

 23%|██▎       | 1180/5184 [00:59<03:21, 19.89it/s]

 23%|██▎       | 1183/5184 [00:59<03:23, 19.71it/s]

 23%|██▎       | 1185/5184 [00:59<03:24, 19.58it/s]

 23%|██▎       | 1187/5184 [00:59<03:24, 19.51it/s]

 23%|██▎       | 1189/5184 [00:59<03:23, 19.63it/s]

 23%|██▎       | 1192/5184 [00:59<03:22, 19.76it/s]

 23%|██▎       | 1195/5184 [00:59<03:20, 19.88it/s]

 23%|██▎       | 1197/5184 [01:00<03:20, 19.85it/s]

 23%|██▎       | 1200/5184 [01:00<03:19, 19.93it/s]

 23%|██▎       | 1202/5184 [01:00<03:19, 19.93it/s]

 23%|██▎       | 1205/5184 [01:00<03:19, 19.97it/s]

 23%|██▎       | 1208/5184 [01:00<03:18, 20.07it/s]

 23%|██▎       | 1211/5184 [01:00<03:15, 20.27it/s]

 23%|██▎       | 1214/5184 [01:00<03:14, 20.39it/s]

 23%|██▎       | 1217/5184 [01:01<03:13, 20.52it/s]

 24%|██▎       | 1220/5184 [01:01<03:12, 20.59it/s]

 24%|██▎       | 1223/5184 [01:01<03:11, 20.66it/s]

 24%|██▎       | 1226/5184 [01:01<03:13, 20.41it/s]

 24%|██▎       | 1229/5184 [01:01<03:17, 19.99it/s]

 24%|██▍       | 1232/5184 [01:01<03:21, 19.62it/s]

 24%|██▍       | 1234/5184 [01:01<03:24, 19.27it/s]

 24%|██▍       | 1236/5184 [01:01<03:25, 19.18it/s]

 24%|██▍       | 1238/5184 [01:02<03:26, 19.13it/s]

 24%|██▍       | 1240/5184 [01:02<03:26, 19.06it/s]

 24%|██▍       | 1243/5184 [01:02<03:06, 21.16it/s]

 24%|██▍       | 1246/5184 [01:02<03:11, 20.52it/s]

 24%|██▍       | 1249/5184 [01:02<03:16, 19.98it/s]

 24%|██▍       | 1252/5184 [01:02<03:18, 19.77it/s]

 24%|██▍       | 1255/5184 [01:02<03:20, 19.61it/s]

 24%|██▍       | 1257/5184 [01:03<03:22, 19.37it/s]

 24%|██▍       | 1259/5184 [01:03<03:21, 19.49it/s]

 24%|██▍       | 1261/5184 [01:03<03:19, 19.64it/s]

 24%|██▍       | 1263/5184 [01:03<03:19, 19.69it/s]

 24%|██▍       | 1266/5184 [01:03<03:17, 19.79it/s]

 24%|██▍       | 1268/5184 [01:03<03:18, 19.76it/s]

 24%|██▍       | 1270/5184 [01:03<03:17, 19.82it/s]

 25%|██▍       | 1272/5184 [01:03<03:16, 19.87it/s]

 25%|██▍       | 1274/5184 [01:03<03:16, 19.88it/s]

 25%|██▍       | 1276/5184 [01:03<03:16, 19.86it/s]

 25%|██▍       | 1279/5184 [01:04<03:14, 20.04it/s]

 25%|██▍       | 1282/5184 [01:04<03:12, 20.23it/s]

 25%|██▍       | 1285/5184 [01:04<03:11, 20.36it/s]

 25%|██▍       | 1288/5184 [01:04<03:11, 20.33it/s]

 25%|██▍       | 1291/5184 [01:04<03:10, 20.45it/s]

 25%|██▍       | 1294/5184 [01:04<03:09, 20.54it/s]

 25%|██▌       | 1297/5184 [01:05<03:10, 20.45it/s]

 25%|██▌       | 1300/5184 [01:05<03:12, 20.14it/s]

 25%|██▌       | 1303/5184 [01:05<03:15, 19.86it/s]

 25%|██▌       | 1305/5184 [01:05<03:17, 19.62it/s]

 25%|██▌       | 1307/5184 [01:05<03:19, 19.40it/s]

 25%|██▌       | 1309/5184 [01:05<03:21, 19.21it/s]

 25%|██▌       | 1311/5184 [01:05<03:22, 19.10it/s]

 25%|██▌       | 1313/5184 [01:05<03:23, 19.05it/s]

 25%|██▌       | 1316/5184 [01:05<03:03, 21.10it/s]

 25%|██▌       | 1319/5184 [01:06<03:09, 20.40it/s]

 26%|██▌       | 1322/5184 [01:06<03:14, 19.88it/s]

 26%|██▌       | 1325/5184 [01:06<03:16, 19.62it/s]

 26%|██▌       | 1327/5184 [01:06<03:18, 19.43it/s]

 26%|██▌       | 1329/5184 [01:06<03:21, 19.11it/s]

 26%|██▌       | 1331/5184 [01:06<03:19, 19.34it/s]

 26%|██▌       | 1334/5184 [01:06<03:16, 19.55it/s]

 26%|██▌       | 1336/5184 [01:06<03:15, 19.66it/s]

 26%|██▌       | 1338/5184 [01:07<03:15, 19.72it/s]

 26%|██▌       | 1340/5184 [01:07<03:14, 19.79it/s]

 26%|██▌       | 1342/5184 [01:07<03:13, 19.84it/s]

 26%|██▌       | 1344/5184 [01:07<03:13, 19.80it/s]

 26%|██▌       | 1346/5184 [01:07<03:13, 19.84it/s]

 26%|██▌       | 1348/5184 [01:07<03:13, 19.79it/s]

 26%|██▌       | 1351/5184 [01:07<03:12, 19.95it/s]

 26%|██▌       | 1354/5184 [01:07<03:09, 20.19it/s]

 26%|██▌       | 1357/5184 [01:08<03:08, 20.29it/s]

 26%|██▌       | 1360/5184 [01:08<03:07, 20.40it/s]

 26%|██▋       | 1363/5184 [01:08<03:06, 20.49it/s]

 26%|██▋       | 1366/5184 [01:08<03:06, 20.52it/s]

 26%|██▋       | 1369/5184 [01:08<03:08, 20.27it/s]

 26%|██▋       | 1372/5184 [01:08<03:10, 20.01it/s]

 27%|██▋       | 1375/5184 [01:08<03:12, 19.78it/s]

 27%|██▋       | 1377/5184 [01:09<03:15, 19.47it/s]

 27%|██▋       | 1379/5184 [01:09<03:16, 19.32it/s]

 27%|██▋       | 1381/5184 [01:09<03:17, 19.25it/s]

 27%|██▋       | 1383/5184 [01:09<03:18, 19.16it/s]

 27%|██▋       | 1385/5184 [01:09<03:18, 19.13it/s]

 27%|██▋       | 1387/5184 [01:09<03:18, 19.11it/s]

 27%|██▋       | 1390/5184 [01:09<02:58, 21.21it/s]

 27%|██▋       | 1393/5184 [01:09<03:05, 20.47it/s]

 27%|██▋       | 1396/5184 [01:09<03:08, 20.09it/s]

 27%|██▋       | 1399/5184 [01:10<03:10, 19.82it/s]

 27%|██▋       | 1402/5184 [01:10<03:11, 19.71it/s]

 27%|██▋       | 1404/5184 [01:10<03:11, 19.78it/s]

 27%|██▋       | 1407/5184 [01:10<03:09, 19.88it/s]

 27%|██▋       | 1409/5184 [01:10<03:11, 19.72it/s]

 27%|██▋       | 1411/5184 [01:10<03:10, 19.77it/s]

 27%|██▋       | 1414/5184 [01:10<03:09, 19.86it/s]

 27%|██▋       | 1417/5184 [01:11<03:08, 19.95it/s]

 27%|██▋       | 1420/5184 [01:11<03:08, 19.98it/s]

 27%|██▋       | 1423/5184 [01:11<03:06, 20.17it/s]

 28%|██▊       | 1426/5184 [01:11<03:04, 20.37it/s]

 28%|██▊       | 1429/5184 [01:11<03:03, 20.46it/s]

 28%|██▊       | 1432/5184 [01:11<03:03, 20.49it/s]

 28%|██▊       | 1435/5184 [01:11<03:02, 20.57it/s]

 28%|██▊       | 1438/5184 [01:12<03:01, 20.59it/s]

 28%|██▊       | 1441/5184 [01:12<03:02, 20.46it/s]

 28%|██▊       | 1444/5184 [01:12<03:06, 20.08it/s]

 28%|██▊       | 1447/5184 [01:12<03:08, 19.80it/s]

 28%|██▊       | 1449/5184 [01:12<03:12, 19.36it/s]

 28%|██▊       | 1451/5184 [01:12<03:13, 19.28it/s]

 28%|██▊       | 1453/5184 [01:12<03:14, 19.14it/s]

 28%|██▊       | 1455/5184 [01:12<03:16, 18.99it/s]

 28%|██▊       | 1457/5184 [01:13<03:16, 18.94it/s]

 28%|██▊       | 1459/5184 [01:13<03:17, 18.88it/s]

 28%|██▊       | 1462/5184 [01:13<02:57, 20.99it/s]

 28%|██▊       | 1465/5184 [01:13<03:02, 20.33it/s]

 28%|██▊       | 1468/5184 [01:13<03:06, 19.91it/s]

 28%|██▊       | 1471/5184 [01:13<03:09, 19.54it/s]

 28%|██▊       | 1473/5184 [01:13<03:11, 19.35it/s]

 28%|██▊       | 1475/5184 [01:13<03:10, 19.48it/s]

 28%|██▊       | 1477/5184 [01:14<03:09, 19.59it/s]

 29%|██▊       | 1479/5184 [01:14<03:08, 19.70it/s]

 29%|██▊       | 1481/5184 [01:14<03:07, 19.70it/s]

 29%|██▊       | 1483/5184 [01:14<03:07, 19.77it/s]

 29%|██▊       | 1485/5184 [01:14<03:06, 19.82it/s]

 29%|██▊       | 1487/5184 [01:14<03:06, 19.83it/s]

 29%|██▊       | 1489/5184 [01:14<03:06, 19.79it/s]

 29%|██▉       | 1491/5184 [01:14<03:06, 19.81it/s]

 29%|██▉       | 1493/5184 [01:14<03:06, 19.80it/s]

 29%|██▉       | 1496/5184 [01:15<03:04, 20.04it/s]

 29%|██▉       | 1499/5184 [01:15<03:02, 20.14it/s]

 29%|██▉       | 1502/5184 [01:15<03:01, 20.25it/s]

 29%|██▉       | 1505/5184 [01:15<03:00, 20.34it/s]

 29%|██▉       | 1508/5184 [01:15<03:00, 20.41it/s]

 29%|██▉       | 1511/5184 [01:15<03:00, 20.33it/s]

 29%|██▉       | 1514/5184 [01:15<03:02, 20.16it/s]

 29%|██▉       | 1517/5184 [01:16<03:04, 19.89it/s]

 29%|██▉       | 1519/5184 [01:16<03:06, 19.68it/s]

 29%|██▉       | 1521/5184 [01:16<03:08, 19.47it/s]

 29%|██▉       | 1523/5184 [01:16<03:09, 19.31it/s]

 29%|██▉       | 1525/5184 [01:16<03:09, 19.26it/s]

 29%|██▉       | 1527/5184 [01:16<03:10, 19.17it/s]

 29%|██▉       | 1529/5184 [01:16<03:10, 19.15it/s]

 30%|██▉       | 1531/5184 [01:16<03:10, 19.14it/s]

 30%|██▉       | 1533/5184 [01:16<03:10, 19.14it/s]

 30%|██▉       | 1536/5184 [01:16<02:51, 21.22it/s]

 30%|██▉       | 1539/5184 [01:17<02:57, 20.53it/s]

 30%|██▉       | 1542/5184 [01:17<03:02, 19.95it/s]

 30%|██▉       | 1545/5184 [01:17<03:04, 19.71it/s]

 30%|██▉       | 1548/5184 [01:17<03:04, 19.72it/s]

 30%|██▉       | 1550/5184 [01:17<03:06, 19.53it/s]

 30%|██▉       | 1552/5184 [01:17<03:05, 19.61it/s]

 30%|██▉       | 1554/5184 [01:17<03:04, 19.68it/s]

 30%|███       | 1556/5184 [01:18<03:04, 19.66it/s]

 30%|███       | 1558/5184 [01:18<03:04, 19.66it/s]

 30%|███       | 1560/5184 [01:18<03:03, 19.70it/s]

 30%|███       | 1562/5184 [01:18<03:03, 19.69it/s]

 30%|███       | 1564/5184 [01:18<03:03, 19.70it/s]

 30%|███       | 1567/5184 [01:18<03:01, 19.87it/s]

 30%|███       | 1570/5184 [01:18<03:00, 20.05it/s]

 30%|███       | 1573/5184 [01:18<02:59, 20.17it/s]

 30%|███       | 1576/5184 [01:19<02:58, 20.27it/s]

 30%|███       | 1579/5184 [01:19<02:57, 20.27it/s]

 31%|███       | 1582/5184 [01:19<02:57, 20.26it/s]

 31%|███       | 1585/5184 [01:19<02:58, 20.19it/s]

 31%|███       | 1588/5184 [01:19<03:00, 19.87it/s]

 31%|███       | 1590/5184 [01:19<03:04, 19.48it/s]

 31%|███       | 1592/5184 [01:19<03:06, 19.29it/s]

 31%|███       | 1594/5184 [01:19<03:07, 19.17it/s]

 31%|███       | 1596/5184 [01:20<03:08, 19.08it/s]

 31%|███       | 1598/5184 [01:20<03:08, 19.04it/s]

 31%|███       | 1600/5184 [01:20<03:09, 18.93it/s]

 31%|███       | 1602/5184 [01:20<03:09, 18.92it/s]

 31%|███       | 1604/5184 [01:20<03:09, 18.93it/s]

 31%|███       | 1606/5184 [01:20<03:09, 18.92it/s]

 31%|███       | 1609/5184 [01:20<02:50, 21.03it/s]

 31%|███       | 1612/5184 [01:20<02:55, 20.35it/s]

 31%|███       | 1615/5184 [01:21<02:59, 19.94it/s]

 31%|███       | 1618/5184 [01:21<03:01, 19.68it/s]

 31%|███▏      | 1620/5184 [01:21<03:00, 19.72it/s]

 31%|███▏      | 1622/5184 [01:21<03:00, 19.77it/s]

 31%|███▏      | 1624/5184 [01:21<02:59, 19.80it/s]

 31%|███▏      | 1626/5184 [01:21<02:59, 19.82it/s]

 31%|███▏      | 1628/5184 [01:21<02:59, 19.81it/s]

 31%|███▏      | 1630/5184 [01:21<02:59, 19.79it/s]

 31%|███▏      | 1632/5184 [01:21<02:59, 19.84it/s]

 32%|███▏      | 1634/5184 [01:21<02:59, 19.78it/s]

 32%|███▏      | 1636/5184 [01:22<02:59, 19.77it/s]

 32%|███▏      | 1639/5184 [01:22<02:57, 19.95it/s]

 32%|███▏      | 1642/5184 [01:22<02:56, 20.12it/s]

 32%|███▏      | 1645/5184 [01:22<02:54, 20.27it/s]

 32%|███▏      | 1648/5184 [01:22<02:53, 20.33it/s]

 32%|███▏      | 1651/5184 [01:22<02:52, 20.42it/s]

 32%|███▏      | 1654/5184 [01:22<02:52, 20.51it/s]

 32%|███▏      | 1657/5184 [01:23<02:52, 20.39it/s]

 32%|███▏      | 1660/5184 [01:23<02:55, 20.12it/s]

 32%|███▏      | 1663/5184 [01:23<02:57, 19.83it/s]

 32%|███▏      | 1665/5184 [01:23<02:59, 19.62it/s]

 32%|███▏      | 1667/5184 [01:23<03:00, 19.49it/s]

 32%|███▏      | 1669/5184 [01:23<03:01, 19.36it/s]

 32%|███▏      | 1671/5184 [01:23<03:02, 19.29it/s]

 32%|███▏      | 1673/5184 [01:23<03:02, 19.28it/s]

 32%|███▏      | 1675/5184 [01:24<03:02, 19.26it/s]

 32%|███▏      | 1677/5184 [01:24<03:02, 19.25it/s]

 32%|███▏      | 1679/5184 [01:24<03:02, 19.16it/s]

 32%|███▏      | 1682/5184 [01:24<02:45, 21.20it/s]

 33%|███▎      | 1685/5184 [01:24<02:51, 20.45it/s]

 33%|███▎      | 1688/5184 [01:24<02:54, 20.04it/s]

 33%|███▎      | 1691/5184 [01:24<02:55, 19.89it/s]

 33%|███▎      | 1694/5184 [01:24<02:55, 19.93it/s]

 33%|███▎      | 1697/5184 [01:25<02:54, 19.95it/s]

 33%|███▎      | 1700/5184 [01:25<02:54, 19.99it/s]

 33%|███▎      | 1703/5184 [01:25<02:54, 20.00it/s]

 33%|███▎      | 1706/5184 [01:25<02:53, 20.00it/s]

 33%|███▎      | 1709/5184 [01:25<02:53, 20.00it/s]

 33%|███▎      | 1712/5184 [01:25<02:51, 20.23it/s]

 33%|███▎      | 1715/5184 [01:26<02:49, 20.41it/s]

 33%|███▎      | 1718/5184 [01:26<02:48, 20.51it/s]

 33%|███▎      | 1721/5184 [01:26<02:48, 20.59it/s]

 33%|███▎      | 1724/5184 [01:26<02:47, 20.64it/s]

 33%|███▎      | 1727/5184 [01:26<02:46, 20.72it/s]

 33%|███▎      | 1730/5184 [01:26<02:49, 20.43it/s]

 33%|███▎      | 1733/5184 [01:26<02:51, 20.14it/s]

 33%|███▎      | 1736/5184 [01:27<02:53, 19.87it/s]

 34%|███▎      | 1738/5184 [01:27<02:56, 19.55it/s]

 34%|███▎      | 1740/5184 [01:27<02:56, 19.49it/s]

 34%|███▎      | 1742/5184 [01:27<02:57, 19.42it/s]

 34%|███▎      | 1744/5184 [01:27<02:57, 19.33it/s]

 34%|███▎      | 1746/5184 [01:27<02:58, 19.31it/s]

 34%|███▎      | 1748/5184 [01:27<02:58, 19.30it/s]

 34%|███▍      | 1750/5184 [01:27<02:58, 19.21it/s]

 34%|███▍      | 1752/5184 [01:27<02:59, 19.15it/s]

 34%|███▍      | 1755/5184 [01:27<02:41, 21.26it/s]

 34%|███▍      | 1758/5184 [01:28<02:46, 20.53it/s]

 34%|███▍      | 1761/5184 [01:28<02:49, 20.18it/s]

 34%|███▍      | 1764/5184 [01:28<02:49, 20.14it/s]

 34%|███▍      | 1767/5184 [01:28<02:50, 20.09it/s]

 34%|███▍      | 1770/5184 [01:28<02:50, 20.08it/s]

 34%|███▍      | 1773/5184 [01:28<02:49, 20.08it/s]

 34%|███▍      | 1776/5184 [01:29<02:49, 20.06it/s]

 34%|███▍      | 1779/5184 [01:29<02:49, 20.08it/s]

 34%|███▍      | 1782/5184 [01:29<02:48, 20.13it/s]

 34%|███▍      | 1785/5184 [01:29<02:47, 20.29it/s]

 34%|███▍      | 1788/5184 [01:29<02:46, 20.43it/s]

 35%|███▍      | 1791/5184 [01:29<02:46, 20.42it/s]

 35%|███▍      | 1794/5184 [01:29<02:45, 20.47it/s]

 35%|███▍      | 1797/5184 [01:30<02:44, 20.58it/s]

 35%|███▍      | 1800/5184 [01:30<02:44, 20.60it/s]

 35%|███▍      | 1803/5184 [01:30<02:46, 20.27it/s]

 35%|███▍      | 1806/5184 [01:30<02:48, 19.99it/s]

 35%|███▍      | 1809/5184 [01:30<02:50, 19.76it/s]

 35%|███▍      | 1811/5184 [01:30<02:53, 19.47it/s]

 35%|███▍      | 1813/5184 [01:30<02:54, 19.36it/s]

 35%|███▌      | 1815/5184 [01:30<02:54, 19.32it/s]

 35%|███▌      | 1817/5184 [01:31<02:54, 19.27it/s]

 35%|███▌      | 1819/5184 [01:31<02:54, 19.28it/s]

 35%|███▌      | 1821/5184 [01:31<02:54, 19.25it/s]

 35%|███▌      | 1823/5184 [01:31<02:54, 19.21it/s]

 35%|███▌      | 1825/5184 [01:31<02:55, 19.12it/s]

 35%|███▌      | 1828/5184 [01:31<02:38, 21.12it/s]

 35%|███▌      | 1831/5184 [01:31<02:45, 20.32it/s]

 35%|███▌      | 1834/5184 [01:31<02:47, 20.02it/s]

 35%|███▌      | 1837/5184 [01:32<02:47, 20.02it/s]

 35%|███▌      | 1840/5184 [01:32<02:46, 20.07it/s]

 36%|███▌      | 1843/5184 [01:32<02:46, 20.06it/s]

 36%|███▌      | 1846/5184 [01:32<02:46, 20.08it/s]

 36%|███▌      | 1849/5184 [01:32<02:46, 20.00it/s]

 36%|███▌      | 1852/5184 [01:32<02:46, 20.03it/s]

 36%|███▌      | 1855/5184 [01:32<02:44, 20.20it/s]

 36%|███▌      | 1858/5184 [01:33<02:44, 20.26it/s]

 36%|███▌      | 1861/5184 [01:33<02:43, 20.36it/s]

 36%|███▌      | 1864/5184 [01:33<02:42, 20.46it/s]

 36%|███▌      | 1867/5184 [01:33<02:41, 20.54it/s]

 36%|███▌      | 1870/5184 [01:33<02:41, 20.58it/s]

 36%|███▌      | 1873/5184 [01:33<02:42, 20.42it/s]

 36%|███▌      | 1876/5184 [01:34<02:44, 20.10it/s]

 36%|███▌      | 1879/5184 [01:34<02:46, 19.87it/s]

 36%|███▋      | 1881/5184 [01:34<02:48, 19.60it/s]

 36%|███▋      | 1883/5184 [01:34<02:49, 19.45it/s]

 36%|███▋      | 1885/5184 [01:34<02:50, 19.39it/s]

 36%|███▋      | 1887/5184 [01:34<02:51, 19.28it/s]

 36%|███▋      | 1889/5184 [01:34<02:51, 19.24it/s]

 36%|███▋      | 1891/5184 [01:34<02:52, 19.07it/s]

 37%|███▋      | 1893/5184 [01:34<02:53, 18.99it/s]

 37%|███▋      | 1895/5184 [01:35<02:54, 18.87it/s]

 37%|███▋      | 1897/5184 [01:35<02:53, 18.90it/s]

 37%|███▋      | 1900/5184 [01:35<02:36, 21.01it/s]

 37%|███▋      | 1903/5184 [01:35<02:41, 20.36it/s]

 37%|███▋      | 1906/5184 [01:35<02:43, 20.05it/s]

 37%|███▋      | 1909/5184 [01:35<02:43, 20.03it/s]

 37%|███▋      | 1912/5184 [01:35<02:43, 20.03it/s]

 37%|███▋      | 1915/5184 [01:35<02:43, 20.01it/s]

 37%|███▋      | 1918/5184 [01:36<02:43, 19.96it/s]

 37%|███▋      | 1921/5184 [01:36<02:43, 19.98it/s]

 37%|███▋      | 1924/5184 [01:36<02:43, 19.98it/s]

 37%|███▋      | 1927/5184 [01:36<02:42, 20.08it/s]

 37%|███▋      | 1930/5184 [01:36<02:40, 20.33it/s]

 37%|███▋      | 1933/5184 [01:36<02:40, 20.31it/s]

 37%|███▋      | 1936/5184 [01:37<02:39, 20.43it/s]

 37%|███▋      | 1939/5184 [01:37<02:38, 20.48it/s]

 37%|███▋      | 1942/5184 [01:37<02:38, 20.49it/s]

 38%|███▊      | 1945/5184 [01:37<02:38, 20.40it/s]

 38%|███▊      | 1948/5184 [01:37<02:40, 20.11it/s]

 38%|███▊      | 1951/5184 [01:37<02:42, 19.85it/s]

 38%|███▊      | 1953/5184 [01:37<02:44, 19.61it/s]

 38%|███▊      | 1955/5184 [01:37<02:45, 19.47it/s]

 38%|███▊      | 1957/5184 [01:38<02:46, 19.33it/s]

 38%|███▊      | 1959/5184 [01:38<02:47, 19.26it/s]

 38%|███▊      | 1961/5184 [01:38<02:47, 19.24it/s]

 38%|███▊      | 1963/5184 [01:38<02:47, 19.20it/s]

 38%|███▊      | 1965/5184 [01:38<02:47, 19.19it/s]

 38%|███▊      | 1967/5184 [01:38<02:48, 19.13it/s]

 38%|███▊      | 1969/5184 [01:38<02:48, 19.09it/s]

 38%|███▊      | 1971/5184 [01:38<02:50, 18.90it/s]

 38%|███▊      | 1974/5184 [01:38<02:32, 21.02it/s]

 38%|███▊      | 1977/5184 [01:39<02:36, 20.45it/s]

 38%|███▊      | 1980/5184 [01:39<02:38, 20.22it/s]

 38%|███▊      | 1983/5184 [01:39<02:38, 20.14it/s]

 38%|███▊      | 1986/5184 [01:39<02:39, 20.09it/s]

 38%|███▊      | 1989/5184 [01:39<02:39, 20.01it/s]

 38%|███▊      | 1992/5184 [01:39<02:40, 19.85it/s]

 38%|███▊      | 1994/5184 [01:39<02:40, 19.85it/s]

 39%|███▊      | 1996/5184 [01:40<02:41, 19.78it/s]

 39%|███▊      | 1998/5184 [01:40<02:40, 19.83it/s]

 39%|███▊      | 2001/5184 [01:40<02:38, 20.06it/s]

 39%|███▊      | 2004/5184 [01:40<02:36, 20.26it/s]

 39%|███▊      | 2007/5184 [01:40<02:36, 20.36it/s]

 39%|███▉      | 2010/5184 [01:40<02:37, 20.17it/s]

 39%|███▉      | 2013/5184 [01:40<02:36, 20.25it/s]

 39%|███▉      | 2016/5184 [01:41<02:35, 20.39it/s]

 39%|███▉      | 2019/5184 [01:41<02:37, 20.04it/s]

 39%|███▉      | 2022/5184 [01:41<02:39, 19.77it/s]

 39%|███▉      | 2024/5184 [01:41<02:41, 19.57it/s]

 39%|███▉      | 2026/5184 [01:41<02:42, 19.41it/s]

 39%|███▉      | 2028/5184 [01:41<02:43, 19.33it/s]

 39%|███▉      | 2030/5184 [01:41<02:43, 19.29it/s]

 39%|███▉      | 2032/5184 [01:41<02:44, 19.14it/s]

 39%|███▉      | 2034/5184 [01:41<02:44, 19.14it/s]

 39%|███▉      | 2036/5184 [01:42<02:44, 19.14it/s]

 39%|███▉      | 2038/5184 [01:42<02:44, 19.07it/s]

 39%|███▉      | 2040/5184 [01:42<02:45, 19.03it/s]

 39%|███▉      | 2042/5184 [01:42<02:45, 19.03it/s]

 39%|███▉      | 2044/5184 [01:42<02:45, 18.95it/s]

 39%|███▉      | 2047/5184 [01:42<02:28, 21.07it/s]

 40%|███▉      | 2050/5184 [01:42<02:32, 20.59it/s]

 40%|███▉      | 2053/5184 [01:42<02:33, 20.38it/s]

 40%|███▉      | 2056/5184 [01:43<02:34, 20.23it/s]

 40%|███▉      | 2059/5184 [01:43<02:35, 20.12it/s]

 40%|███▉      | 2062/5184 [01:43<02:35, 20.04it/s]

 40%|███▉      | 2065/5184 [01:43<02:35, 20.00it/s]

 40%|███▉      | 2068/5184 [01:43<02:36, 19.97it/s]

 40%|███▉      | 2071/5184 [01:43<02:35, 20.08it/s]

 40%|████      | 2074/5184 [01:43<02:33, 20.23it/s]

 40%|████      | 2077/5184 [01:44<02:32, 20.31it/s]

 40%|████      | 2080/5184 [01:44<02:32, 20.38it/s]

 40%|████      | 2083/5184 [01:44<02:31, 20.45it/s]

 40%|████      | 2086/5184 [01:44<02:31, 20.48it/s]

 40%|████      | 2089/5184 [01:44<02:31, 20.37it/s]

 40%|████      | 2092/5184 [01:44<02:34, 20.04it/s]

 40%|████      | 2095/5184 [01:44<02:36, 19.80it/s]

 40%|████      | 2097/5184 [01:45<02:37, 19.60it/s]

 40%|████      | 2099/5184 [01:45<02:39, 19.36it/s]

 41%|████      | 2101/5184 [01:45<02:39, 19.30it/s]

 41%|████      | 2103/5184 [01:45<02:41, 19.02it/s]

 41%|████      | 2105/5184 [01:45<02:44, 18.68it/s]

 41%|████      | 2107/5184 [01:45<02:46, 18.46it/s]

 41%|████      | 2109/5184 [01:45<02:45, 18.54it/s]

 41%|████      | 2111/5184 [01:45<02:46, 18.41it/s]

 41%|████      | 2113/5184 [01:45<02:47, 18.38it/s]

 41%|████      | 2115/5184 [01:46<02:47, 18.31it/s]

 41%|████      | 2117/5184 [01:46<02:45, 18.50it/s]

 41%|████      | 2120/5184 [01:46<02:27, 20.73it/s]

 41%|████      | 2123/5184 [01:46<02:30, 20.36it/s]

 41%|████      | 2126/5184 [01:46<02:30, 20.29it/s]

 41%|████      | 2129/5184 [01:46<02:30, 20.26it/s]

 41%|████      | 2132/5184 [01:46<02:31, 20.21it/s]

 41%|████      | 2135/5184 [01:47<02:31, 20.15it/s]

 41%|████      | 2138/5184 [01:47<02:31, 20.08it/s]

 41%|████▏     | 2141/5184 [01:47<02:31, 20.06it/s]

 41%|████▏     | 2144/5184 [01:47<02:30, 20.23it/s]

 41%|████▏     | 2147/5184 [01:47<02:29, 20.36it/s]

 41%|████▏     | 2150/5184 [01:47<02:28, 20.43it/s]

 42%|████▏     | 2153/5184 [01:47<02:28, 20.39it/s]

 42%|████▏     | 2156/5184 [01:48<02:28, 20.43it/s]

 42%|████▏     | 2159/5184 [01:48<02:27, 20.51it/s]

 42%|████▏     | 2162/5184 [01:48<02:29, 20.24it/s]

 42%|████▏     | 2165/5184 [01:48<02:31, 19.93it/s]

 42%|████▏     | 2167/5184 [01:48<02:33, 19.63it/s]

 42%|████▏     | 2169/5184 [01:48<02:35, 19.45it/s]

 42%|████▏     | 2171/5184 [01:48<02:35, 19.32it/s]

 42%|████▏     | 2173/5184 [01:48<02:38, 18.95it/s]

 42%|████▏     | 2175/5184 [01:49<02:40, 18.75it/s]

 42%|████▏     | 2177/5184 [01:49<02:40, 18.74it/s]

 42%|████▏     | 2179/5184 [01:49<02:39, 18.83it/s]

 42%|████▏     | 2181/5184 [01:49<02:39, 18.87it/s]

 42%|████▏     | 2183/5184 [01:49<02:38, 18.90it/s]

 42%|████▏     | 2185/5184 [01:49<02:38, 18.94it/s]

 42%|████▏     | 2187/5184 [01:49<02:38, 18.91it/s]

 42%|████▏     | 2189/5184 [01:49<02:38, 18.89it/s]

 42%|████▏     | 2192/5184 [01:49<02:23, 20.81it/s]

 42%|████▏     | 2195/5184 [01:50<02:27, 20.25it/s]

 42%|████▏     | 2198/5184 [01:50<02:29, 19.96it/s]

 42%|████▏     | 2201/5184 [01:50<02:29, 19.91it/s]

 43%|████▎     | 2204/5184 [01:50<02:29, 19.90it/s]

 43%|████▎     | 2207/5184 [01:50<02:29, 19.86it/s]

 43%|████▎     | 2209/5184 [01:50<02:40, 18.57it/s]

 43%|████▎     | 2211/5184 [01:50<02:36, 18.94it/s]

 43%|████▎     | 2214/5184 [01:51<02:33, 19.34it/s]

 43%|████▎     | 2217/5184 [01:51<02:30, 19.69it/s]

 43%|████▎     | 2220/5184 [01:51<02:28, 20.01it/s]

 43%|████▎     | 2223/5184 [01:51<02:26, 20.18it/s]

 43%|████▎     | 2226/5184 [01:51<02:25, 20.38it/s]

 43%|████▎     | 2229/5184 [01:51<02:24, 20.49it/s]

 43%|████▎     | 2232/5184 [01:51<02:23, 20.57it/s]

 43%|████▎     | 2235/5184 [01:52<02:25, 20.22it/s]

 43%|████▎     | 2238/5184 [01:52<02:27, 20.00it/s]

 43%|████▎     | 2241/5184 [01:52<02:29, 19.75it/s]

 43%|████▎     | 2243/5184 [01:52<02:30, 19.59it/s]

 43%|████▎     | 2245/5184 [01:52<02:30, 19.51it/s]

 43%|████▎     | 2247/5184 [01:52<02:31, 19.37it/s]

 43%|████▎     | 2249/5184 [01:52<02:31, 19.31it/s]

 43%|████▎     | 2251/5184 [01:52<02:31, 19.32it/s]

 43%|████▎     | 2253/5184 [01:53<02:31, 19.30it/s]

 43%|████▎     | 2255/5184 [01:53<02:32, 19.23it/s]

 44%|████▎     | 2257/5184 [01:53<02:32, 19.26it/s]

 44%|████▎     | 2259/5184 [01:53<02:31, 19.27it/s]

 44%|████▎     | 2261/5184 [01:53<02:31, 19.24it/s]

 44%|████▎     | 2263/5184 [01:53<02:32, 19.17it/s]

 44%|████▎     | 2266/5184 [01:53<02:16, 21.35it/s]

 44%|████▍     | 2269/5184 [01:53<02:18, 21.00it/s]

 44%|████▍     | 2272/5184 [01:53<02:20, 20.72it/s]

 44%|████▍     | 2275/5184 [01:54<02:21, 20.52it/s]

 44%|████▍     | 2278/5184 [01:54<02:22, 20.38it/s]

 44%|████▍     | 2281/5184 [01:54<02:22, 20.31it/s]

 44%|████▍     | 2284/5184 [01:54<02:23, 20.24it/s]

 44%|████▍     | 2287/5184 [01:54<02:22, 20.37it/s]

 44%|████▍     | 2290/5184 [01:54<02:21, 20.50it/s]

 44%|████▍     | 2293/5184 [01:54<02:20, 20.58it/s]

 44%|████▍     | 2296/5184 [01:55<02:20, 20.61it/s]

 44%|████▍     | 2299/5184 [01:55<02:19, 20.65it/s]

 44%|████▍     | 2302/5184 [01:55<02:19, 20.66it/s]

 44%|████▍     | 2305/5184 [01:55<02:20, 20.56it/s]

 45%|████▍     | 2308/5184 [01:55<02:22, 20.22it/s]

 45%|████▍     | 2311/5184 [01:55<02:23, 19.97it/s]

 45%|████▍     | 2313/5184 [01:55<02:25, 19.77it/s]

 45%|████▍     | 2315/5184 [01:56<02:26, 19.60it/s]

 45%|████▍     | 2317/5184 [01:56<02:27, 19.49it/s]

 45%|████▍     | 2319/5184 [01:56<02:27, 19.41it/s]

 45%|████▍     | 2321/5184 [01:56<02:27, 19.39it/s]

 45%|████▍     | 2323/5184 [01:56<02:27, 19.35it/s]

 45%|████▍     | 2325/5184 [01:56<02:27, 19.36it/s]

 45%|████▍     | 2327/5184 [01:56<02:28, 19.18it/s]

 45%|████▍     | 2329/5184 [01:56<02:29, 19.15it/s]

 45%|████▍     | 2331/5184 [01:56<02:28, 19.19it/s]

 45%|████▌     | 2333/5184 [01:56<02:28, 19.16it/s]

 45%|████▌     | 2335/5184 [01:57<02:28, 19.14it/s]

 45%|████▌     | 2338/5184 [01:57<02:13, 21.30it/s]

 45%|████▌     | 2341/5184 [01:57<02:15, 20.97it/s]

 45%|████▌     | 2344/5184 [01:57<02:16, 20.74it/s]

 45%|████▌     | 2347/5184 [01:57<02:17, 20.56it/s]

 45%|████▌     | 2350/5184 [01:57<02:18, 20.44it/s]

 45%|████▌     | 2353/5184 [01:57<02:19, 20.22it/s]

 45%|████▌     | 2356/5184 [01:58<02:20, 20.19it/s]

 46%|████▌     | 2359/5184 [01:58<02:18, 20.34it/s]

 46%|████▌     | 2362/5184 [01:58<02:17, 20.48it/s]

 46%|████▌     | 2365/5184 [01:58<02:17, 20.58it/s]

 46%|████▌     | 2368/5184 [01:58<02:16, 20.65it/s]

 46%|████▌     | 2371/5184 [01:58<02:17, 20.43it/s]

 46%|████▌     | 2374/5184 [01:58<02:17, 20.46it/s]

 46%|████▌     | 2377/5184 [01:59<02:17, 20.46it/s]

 46%|████▌     | 2380/5184 [01:59<02:18, 20.28it/s]

 46%|████▌     | 2383/5184 [01:59<02:18, 20.22it/s]

 46%|████▌     | 2386/5184 [01:59<02:18, 20.16it/s]

 46%|████▌     | 2389/5184 [01:59<02:19, 20.09it/s]

 46%|████▌     | 2392/5184 [01:59<02:19, 20.00it/s]

 46%|████▌     | 2395/5184 [02:00<02:19, 20.03it/s]

 46%|████▋     | 2398/5184 [02:00<02:19, 19.95it/s]

 46%|████▋     | 2400/5184 [02:00<02:19, 19.95it/s]

 46%|████▋     | 2403/5184 [02:00<02:19, 19.98it/s]

 46%|████▋     | 2405/5184 [02:00<02:19, 19.93it/s]

 46%|████▋     | 2407/5184 [02:00<02:19, 19.94it/s]

 46%|████▋     | 2409/5184 [02:00<02:19, 19.95it/s]

 47%|████▋     | 2412/5184 [02:00<02:06, 21.97it/s]

 47%|████▋     | 2415/5184 [02:00<02:12, 20.86it/s]

 47%|████▋     | 2418/5184 [02:01<02:16, 20.23it/s]

 47%|████▋     | 2421/5184 [02:01<02:18, 19.89it/s]

 47%|████▋     | 2424/5184 [02:01<02:21, 19.51it/s]

 47%|████▋     | 2426/5184 [02:01<02:24, 19.04it/s]

 47%|████▋     | 2428/5184 [02:01<02:27, 18.62it/s]

 47%|████▋     | 2430/5184 [02:01<02:27, 18.61it/s]

 47%|████▋     | 2432/5184 [02:01<02:25, 18.93it/s]

 47%|████▋     | 2435/5184 [02:02<02:22, 19.31it/s]

 47%|████▋     | 2438/5184 [02:02<02:19, 19.69it/s]

 47%|████▋     | 2441/5184 [02:02<02:17, 19.91it/s]

 47%|████▋     | 2444/5184 [02:02<02:16, 20.12it/s]

 47%|████▋     | 2447/5184 [02:02<02:14, 20.28it/s]

 47%|████▋     | 2450/5184 [02:02<02:14, 20.26it/s]

 47%|████▋     | 2453/5184 [02:02<02:17, 19.89it/s]

 47%|████▋     | 2455/5184 [02:03<02:20, 19.49it/s]

 47%|████▋     | 2457/5184 [02:03<02:20, 19.39it/s]

 47%|████▋     | 2459/5184 [02:03<02:20, 19.33it/s]

 47%|████▋     | 2461/5184 [02:03<02:21, 19.25it/s]

 48%|████▊     | 2463/5184 [02:03<02:20, 19.37it/s]

 48%|████▊     | 2465/5184 [02:03<02:19, 19.52it/s]

 48%|████▊     | 2467/5184 [02:03<02:18, 19.64it/s]

 48%|████▊     | 2469/5184 [02:03<02:18, 19.61it/s]

 48%|████▊     | 2471/5184 [02:03<02:19, 19.45it/s]

 48%|████▊     | 2473/5184 [02:03<02:18, 19.54it/s]

 48%|████▊     | 2475/5184 [02:04<02:18, 19.58it/s]

 48%|████▊     | 2477/5184 [02:04<02:17, 19.69it/s]

 48%|████▊     | 2479/5184 [02:04<02:16, 19.78it/s]

 48%|████▊     | 2481/5184 [02:04<02:16, 19.81it/s]

 48%|████▊     | 2484/5184 [02:04<02:03, 21.80it/s]

 48%|████▊     | 2487/5184 [02:04<02:09, 20.84it/s]

 48%|████▊     | 2490/5184 [02:04<02:12, 20.30it/s]

 48%|████▊     | 2493/5184 [02:04<02:15, 19.89it/s]

 48%|████▊     | 2496/5184 [02:05<02:17, 19.57it/s]

 48%|████▊     | 2498/5184 [02:05<02:18, 19.43it/s]

 48%|████▊     | 2500/5184 [02:05<02:19, 19.27it/s]

 48%|████▊     | 2502/5184 [02:05<02:18, 19.39it/s]

 48%|████▊     | 2505/5184 [02:05<02:15, 19.70it/s]

 48%|████▊     | 2508/5184 [02:05<02:14, 19.96it/s]

 48%|████▊     | 2511/5184 [02:05<02:12, 20.17it/s]

 48%|████▊     | 2514/5184 [02:06<02:11, 20.29it/s]

 49%|████▊     | 2517/5184 [02:06<02:10, 20.40it/s]

 49%|████▊     | 2520/5184 [02:06<02:10, 20.46it/s]

 49%|████▊     | 2523/5184 [02:06<02:10, 20.35it/s]

 49%|████▊     | 2526/5184 [02:06<02:11, 20.27it/s]

 49%|████▉     | 2529/5184 [02:06<02:11, 20.19it/s]

 49%|████▉     | 2532/5184 [02:06<02:11, 20.14it/s]

 49%|████▉     | 2535/5184 [02:07<02:13, 19.91it/s]

 49%|████▉     | 2537/5184 [02:07<02:13, 19.89it/s]

 49%|████▉     | 2540/5184 [02:07<02:12, 19.95it/s]

 49%|████▉     | 2542/5184 [02:07<02:12, 19.92it/s]

 49%|████▉     | 2545/5184 [02:07<02:12, 19.98it/s]

 49%|████▉     | 2548/5184 [02:07<02:11, 20.00it/s]

 49%|████▉     | 2551/5184 [02:07<02:11, 20.00it/s]

 49%|████▉     | 2554/5184 [02:07<02:12, 19.90it/s]

 49%|████▉     | 2557/5184 [02:08<02:01, 21.66it/s]

 49%|████▉     | 2560/5184 [02:08<02:08, 20.39it/s]

 49%|████▉     | 2563/5184 [02:08<02:15, 19.37it/s]

 49%|████▉     | 2565/5184 [02:08<02:20, 18.64it/s]

 50%|████▉     | 2567/5184 [02:08<02:23, 18.25it/s]

 50%|████▉     | 2569/5184 [02:08<02:25, 17.92it/s]

 50%|████▉     | 2571/5184 [02:08<02:28, 17.65it/s]

 50%|████▉     | 2573/5184 [02:09<02:29, 17.51it/s]

 50%|████▉     | 2575/5184 [02:09<02:26, 17.87it/s]

 50%|████▉     | 2577/5184 [02:09<02:23, 18.19it/s]

 50%|████▉     | 2579/5184 [02:09<02:20, 18.49it/s]

 50%|████▉     | 2581/5184 [02:09<02:18, 18.82it/s]

 50%|████▉     | 2583/5184 [02:09<02:17, 18.98it/s]

 50%|████▉     | 2585/5184 [02:09<02:16, 19.07it/s]

 50%|████▉     | 2587/5184 [02:09<02:14, 19.24it/s]

 50%|████▉     | 2589/5184 [02:09<02:15, 19.12it/s]

 50%|█████     | 2592/5184 [02:10<02:13, 19.39it/s]

 50%|█████     | 2594/5184 [02:10<02:16, 19.02it/s]

 50%|█████     | 2596/5184 [02:10<02:15, 19.05it/s]

 50%|█████     | 2598/5184 [02:10<02:15, 19.09it/s]

 50%|█████     | 2600/5184 [02:10<02:15, 19.13it/s]

 50%|█████     | 2602/5184 [02:10<02:13, 19.30it/s]

 50%|█████     | 2604/5184 [02:10<02:13, 19.36it/s]

 50%|█████     | 2606/5184 [02:10<02:13, 19.30it/s]

 50%|█████     | 2608/5184 [02:10<02:12, 19.40it/s]

 50%|█████     | 2610/5184 [02:10<02:11, 19.55it/s]

 50%|█████     | 2612/5184 [02:11<02:10, 19.64it/s]

 50%|█████     | 2614/5184 [02:11<02:10, 19.68it/s]

 50%|█████     | 2616/5184 [02:11<02:10, 19.75it/s]

 51%|█████     | 2618/5184 [02:11<02:09, 19.76it/s]

 51%|█████     | 2620/5184 [02:11<02:09, 19.80it/s]

 51%|█████     | 2622/5184 [02:11<02:09, 19.83it/s]

 51%|█████     | 2624/5184 [02:11<02:09, 19.83it/s]

 51%|█████     | 2626/5184 [02:11<02:09, 19.71it/s]

 51%|█████     | 2628/5184 [02:11<02:11, 19.45it/s]

 51%|█████     | 2631/5184 [02:11<01:58, 21.49it/s]

 51%|█████     | 2634/5184 [02:12<02:03, 20.60it/s]

 51%|█████     | 2637/5184 [02:12<02:06, 20.12it/s]

 51%|█████     | 2640/5184 [02:12<02:08, 19.84it/s]

 51%|█████     | 2643/5184 [02:12<02:09, 19.64it/s]

 51%|█████     | 2645/5184 [02:12<02:10, 19.42it/s]

 51%|█████     | 2648/5184 [02:12<02:08, 19.79it/s]

 51%|█████     | 2651/5184 [02:12<02:06, 20.06it/s]

 51%|█████     | 2654/5184 [02:13<02:05, 20.20it/s]

 51%|█████▏    | 2657/5184 [02:13<02:04, 20.33it/s]

 51%|█████▏    | 2660/5184 [02:13<02:03, 20.44it/s]

 51%|█████▏    | 2663/5184 [02:13<02:03, 20.47it/s]

 51%|█████▏    | 2666/5184 [02:13<02:03, 20.31it/s]

 51%|█████▏    | 2669/5184 [02:13<02:04, 20.21it/s]

 52%|█████▏    | 2672/5184 [02:14<02:05, 20.09it/s]

 52%|█████▏    | 2675/5184 [02:14<02:05, 20.05it/s]

 52%|█████▏    | 2678/5184 [02:14<02:05, 20.01it/s]

 52%|█████▏    | 2681/5184 [02:14<02:05, 20.01it/s]

 52%|█████▏    | 2684/5184 [02:14<02:05, 19.97it/s]

 52%|█████▏    | 2686/5184 [02:14<02:05, 19.89it/s]

 52%|█████▏    | 2688/5184 [02:14<02:05, 19.89it/s]

 52%|█████▏    | 2691/5184 [02:14<02:04, 19.97it/s]

 52%|█████▏    | 2693/5184 [02:15<02:05, 19.92it/s]

 52%|█████▏    | 2696/5184 [02:15<02:04, 19.91it/s]

 52%|█████▏    | 2698/5184 [02:15<02:05, 19.76it/s]

 52%|█████▏    | 2700/5184 [02:15<02:07, 19.50it/s]

 52%|█████▏    | 2703/5184 [02:15<01:55, 21.44it/s]

 52%|█████▏    | 2706/5184 [02:15<02:00, 20.63it/s]

 52%|█████▏    | 2709/5184 [02:15<02:02, 20.18it/s]

 52%|█████▏    | 2712/5184 [02:16<02:04, 19.88it/s]

 52%|█████▏    | 2715/5184 [02:16<02:06, 19.57it/s]

 52%|█████▏    | 2717/5184 [02:16<02:06, 19.46it/s]

 52%|█████▏    | 2720/5184 [02:16<02:04, 19.87it/s]

 53%|█████▎    | 2723/5184 [02:16<02:02, 20.12it/s]

 53%|█████▎    | 2726/5184 [02:16<02:04, 19.76it/s]

 53%|█████▎    | 2728/5184 [02:16<02:07, 19.27it/s]

 53%|█████▎    | 2730/5184 [02:16<02:09, 19.02it/s]

 53%|█████▎    | 2732/5184 [02:17<02:07, 19.18it/s]

 53%|█████▎    | 2735/5184 [02:17<02:05, 19.58it/s]

 53%|█████▎    | 2738/5184 [02:17<02:03, 19.75it/s]

 53%|█████▎    | 2740/5184 [02:17<02:03, 19.72it/s]

 53%|█████▎    | 2742/5184 [02:17<02:03, 19.79it/s]

 53%|█████▎    | 2744/5184 [02:17<02:02, 19.84it/s]

 53%|█████▎    | 2746/5184 [02:17<02:02, 19.87it/s]

 53%|█████▎    | 2749/5184 [02:17<02:02, 19.95it/s]

 53%|█████▎    | 2751/5184 [02:17<02:01, 19.96it/s]

 53%|█████▎    | 2753/5184 [02:18<02:02, 19.91it/s]

 53%|█████▎    | 2756/5184 [02:18<02:01, 19.95it/s]

 53%|█████▎    | 2758/5184 [02:18<02:01, 19.93it/s]

 53%|█████▎    | 2761/5184 [02:18<02:01, 19.98it/s]

 53%|█████▎    | 2763/5184 [02:18<02:01, 19.98it/s]

 53%|█████▎    | 2765/5184 [02:18<02:01, 19.97it/s]

 53%|█████▎    | 2767/5184 [02:18<02:01, 19.96it/s]

 53%|█████▎    | 2770/5184 [02:18<02:01, 19.87it/s]

 53%|█████▎    | 2772/5184 [02:19<02:04, 19.34it/s]

 54%|█████▎    | 2774/5184 [02:19<02:06, 19.01it/s]

 54%|█████▎    | 2777/5184 [02:19<01:54, 21.11it/s]

 54%|█████▎    | 2780/5184 [02:19<01:57, 20.44it/s]

 54%|█████▎    | 2783/5184 [02:19<02:00, 20.01it/s]

 54%|█████▎    | 2786/5184 [02:19<02:01, 19.73it/s]

 54%|█████▍    | 2789/5184 [02:19<02:02, 19.52it/s]

 54%|█████▍    | 2792/5184 [02:20<02:00, 19.88it/s]

 54%|█████▍    | 2795/5184 [02:20<01:58, 20.10it/s]

 54%|█████▍    | 2798/5184 [02:20<01:57, 20.27it/s]

 54%|█████▍    | 2801/5184 [02:20<01:56, 20.42it/s]

 54%|█████▍    | 2804/5184 [02:20<01:57, 20.33it/s]

 54%|█████▍    | 2807/5184 [02:20<01:56, 20.40it/s]

 54%|█████▍    | 2810/5184 [02:20<01:56, 20.32it/s]

 54%|█████▍    | 2813/5184 [02:21<01:57, 20.14it/s]

 54%|█████▍    | 2816/5184 [02:21<01:58, 19.96it/s]

 54%|█████▍    | 2818/5184 [02:21<01:58, 19.96it/s]

 54%|█████▍    | 2820/5184 [02:21<01:58, 19.96it/s]

 54%|█████▍    | 2823/5184 [02:21<01:58, 19.97it/s]

 54%|█████▍    | 2825/5184 [02:21<01:58, 19.97it/s]

 55%|█████▍    | 2827/5184 [02:21<01:58, 19.95it/s]

 55%|█████▍    | 2830/5184 [02:21<01:57, 20.00it/s]

 55%|█████▍    | 2833/5184 [02:22<01:57, 19.97it/s]

 55%|█████▍    | 2835/5184 [02:22<01:57, 19.96it/s]

 55%|█████▍    | 2837/5184 [02:22<01:57, 19.97it/s]

 55%|█████▍    | 2840/5184 [02:22<01:57, 20.00it/s]

 55%|█████▍    | 2842/5184 [02:22<01:58, 19.84it/s]

 55%|█████▍    | 2844/5184 [02:22<01:59, 19.57it/s]

 55%|█████▍    | 2846/5184 [02:22<02:00, 19.38it/s]

 55%|█████▍    | 2849/5184 [02:22<01:48, 21.43it/s]

 55%|█████▌    | 2852/5184 [02:23<01:52, 20.66it/s]

 55%|█████▌    | 2855/5184 [02:23<01:55, 20.18it/s]

 55%|█████▌    | 2858/5184 [02:23<01:56, 19.90it/s]

 55%|█████▌    | 2861/5184 [02:23<01:58, 19.66it/s]

 55%|█████▌    | 2864/5184 [02:23<01:56, 19.98it/s]

 55%|█████▌    | 2867/5184 [02:23<01:54, 20.22it/s]

 55%|█████▌    | 2870/5184 [02:23<01:53, 20.37it/s]

 55%|█████▌    | 2873/5184 [02:24<01:52, 20.50it/s]

 55%|█████▌    | 2876/5184 [02:24<01:52, 20.50it/s]

 56%|█████▌    | 2879/5184 [02:24<01:51, 20.59it/s]

 56%|█████▌    | 2882/5184 [02:24<01:52, 20.47it/s]

 56%|█████▌    | 2885/5184 [02:24<01:53, 20.32it/s]

 56%|█████▌    | 2888/5184 [02:24<01:53, 20.26it/s]

 56%|█████▌    | 2891/5184 [02:24<01:53, 20.23it/s]

 56%|█████▌    | 2894/5184 [02:25<01:53, 20.18it/s]

 56%|█████▌    | 2897/5184 [02:25<01:53, 20.15it/s]

 56%|█████▌    | 2900/5184 [02:25<01:53, 20.15it/s]

 56%|█████▌    | 2903/5184 [02:25<01:53, 20.12it/s]

 56%|█████▌    | 2906/5184 [02:25<01:53, 20.12it/s]

 56%|█████▌    | 2909/5184 [02:25<01:53, 20.10it/s]

 56%|█████▌    | 2912/5184 [02:25<01:53, 20.08it/s]

 56%|█████▌    | 2915/5184 [02:26<01:54, 19.77it/s]

 56%|█████▋    | 2917/5184 [02:26<01:55, 19.55it/s]

 56%|█████▋    | 2919/5184 [02:26<01:56, 19.42it/s]

 56%|█████▋    | 2922/5184 [02:26<01:45, 21.49it/s]

 56%|█████▋    | 2925/5184 [02:26<01:49, 20.68it/s]

 56%|█████▋    | 2928/5184 [02:26<01:51, 20.21it/s]

 57%|█████▋    | 2931/5184 [02:26<01:53, 19.87it/s]

 57%|█████▋    | 2934/5184 [02:27<01:53, 19.81it/s]

 57%|█████▋    | 2937/5184 [02:27<01:51, 20.07it/s]

 57%|█████▋    | 2940/5184 [02:27<01:50, 20.26it/s]

 57%|█████▋    | 2943/5184 [02:27<01:49, 20.38it/s]

 57%|█████▋    | 2946/5184 [02:27<01:49, 20.48it/s]

 57%|█████▋    | 2949/5184 [02:27<01:48, 20.54it/s]

 57%|█████▋    | 2952/5184 [02:27<01:48, 20.58it/s]

 57%|█████▋    | 2955/5184 [02:28<01:49, 20.35it/s]

 57%|█████▋    | 2958/5184 [02:28<01:50, 20.20it/s]

 57%|█████▋    | 2961/5184 [02:28<01:50, 20.14it/s]

 57%|█████▋    | 2964/5184 [02:28<01:50, 20.14it/s]

 57%|█████▋    | 2967/5184 [02:28<01:50, 20.06it/s]

 57%|█████▋    | 2970/5184 [02:28<01:50, 20.07it/s]

 57%|█████▋    | 2973/5184 [02:29<01:50, 20.04it/s]

 57%|█████▋    | 2976/5184 [02:29<01:50, 20.05it/s]

 57%|█████▋    | 2979/5184 [02:29<01:49, 20.05it/s]

 58%|█████▊    | 2982/5184 [02:29<01:49, 20.05it/s]

 58%|█████▊    | 2985/5184 [02:29<01:49, 20.03it/s]

 58%|█████▊    | 2988/5184 [02:29<01:51, 19.74it/s]

 58%|█████▊    | 2990/5184 [02:29<01:52, 19.43it/s]

 58%|█████▊    | 2992/5184 [02:29<01:53, 19.33it/s]

 58%|█████▊    | 2995/5184 [02:30<01:42, 21.37it/s]

 58%|█████▊    | 2998/5184 [02:30<01:45, 20.64it/s]

 58%|█████▊    | 3001/5184 [02:30<01:48, 20.16it/s]

 58%|█████▊    | 3004/5184 [02:30<01:49, 19.88it/s]

 58%|█████▊    | 3007/5184 [02:30<01:49, 19.95it/s]

 58%|█████▊    | 3010/5184 [02:30<01:48, 20.12it/s]

 58%|█████▊    | 3013/5184 [02:30<01:47, 20.17it/s]

 58%|█████▊    | 3016/5184 [02:31<01:47, 20.18it/s]

 58%|█████▊    | 3019/5184 [02:31<01:46, 20.30it/s]

 58%|█████▊    | 3022/5184 [02:31<01:45, 20.41it/s]

 58%|█████▊    | 3025/5184 [02:31<01:45, 20.39it/s]

 58%|█████▊    | 3028/5184 [02:31<01:46, 20.15it/s]

 58%|█████▊    | 3031/5184 [02:31<01:47, 20.02it/s]

 59%|█████▊    | 3034/5184 [02:32<01:47, 19.96it/s]

 59%|█████▊    | 3036/5184 [02:32<01:47, 19.90it/s]

 59%|█████▊    | 3038/5184 [02:32<01:47, 19.91it/s]

 59%|█████▊    | 3040/5184 [02:32<01:47, 19.88it/s]

 59%|█████▊    | 3042/5184 [02:32<01:47, 19.87it/s]

 59%|█████▊    | 3044/5184 [02:32<01:47, 19.91it/s]

 59%|█████▉    | 3046/5184 [02:32<01:47, 19.90it/s]

 59%|█████▉    | 3048/5184 [02:32<01:47, 19.93it/s]

 59%|█████▉    | 3051/5184 [02:32<01:46, 19.95it/s]

 59%|█████▉    | 3053/5184 [02:32<01:47, 19.90it/s]

 59%|█████▉    | 3055/5184 [02:33<01:47, 19.88it/s]

 59%|█████▉    | 3057/5184 [02:33<01:47, 19.74it/s]

 59%|█████▉    | 3059/5184 [02:33<01:49, 19.47it/s]

 59%|█████▉    | 3061/5184 [02:33<01:50, 19.30it/s]

 59%|█████▉    | 3063/5184 [02:33<01:50, 19.16it/s]

 59%|█████▉    | 3065/5184 [02:33<01:50, 19.11it/s]

 59%|█████▉    | 3068/5184 [02:33<01:39, 21.18it/s]

 59%|█████▉    | 3071/5184 [02:33<01:43, 20.51it/s]

 59%|█████▉    | 3074/5184 [02:34<01:45, 20.05it/s]

 59%|█████▉    | 3077/5184 [02:34<01:46, 19.73it/s]

 59%|█████▉    | 3080/5184 [02:34<01:45, 19.99it/s]

 59%|█████▉    | 3083/5184 [02:34<01:44, 20.19it/s]

 60%|█████▉    | 3086/5184 [02:34<01:43, 20.29it/s]

 60%|█████▉    | 3089/5184 [02:34<01:42, 20.41it/s]

 60%|█████▉    | 3092/5184 [02:34<01:42, 20.49it/s]

 60%|█████▉    | 3095/5184 [02:35<01:41, 20.53it/s]

 60%|█████▉    | 3098/5184 [02:35<01:42, 20.27it/s]

 60%|█████▉    | 3101/5184 [02:35<01:43, 20.19it/s]

 60%|█████▉    | 3104/5184 [02:35<01:43, 20.12it/s]

 60%|█████▉    | 3107/5184 [02:35<01:43, 20.07it/s]

 60%|█████▉    | 3110/5184 [02:35<01:43, 20.01it/s]

 60%|██████    | 3113/5184 [02:35<01:43, 19.98it/s]

 60%|██████    | 3115/5184 [02:36<01:43, 19.98it/s]

 60%|██████    | 3117/5184 [02:36<01:44, 19.84it/s]

 60%|██████    | 3119/5184 [02:36<01:44, 19.79it/s]

 60%|██████    | 3121/5184 [02:36<01:44, 19.82it/s]

 60%|██████    | 3123/5184 [02:36<01:43, 19.85it/s]

 60%|██████    | 3125/5184 [02:36<01:43, 19.84it/s]

 60%|██████    | 3127/5184 [02:36<01:43, 19.88it/s]

 60%|██████    | 3129/5184 [02:36<01:43, 19.88it/s]

 60%|██████    | 3131/5184 [02:36<01:45, 19.52it/s]

 60%|██████    | 3133/5184 [02:36<01:47, 19.13it/s]

 60%|██████    | 3135/5184 [02:37<01:49, 18.69it/s]

 61%|██████    | 3137/5184 [02:37<01:51, 18.36it/s]

 61%|██████    | 3139/5184 [02:37<01:51, 18.34it/s]

 61%|██████    | 3142/5184 [02:37<01:39, 20.47it/s]

 61%|██████    | 3145/5184 [02:37<01:42, 19.83it/s]

 61%|██████    | 3148/5184 [02:37<01:44, 19.53it/s]

 61%|██████    | 3150/5184 [02:37<01:44, 19.45it/s]

 61%|██████    | 3153/5184 [02:38<01:42, 19.72it/s]

 61%|██████    | 3155/5184 [02:38<01:42, 19.73it/s]

 61%|██████    | 3157/5184 [02:38<01:42, 19.78it/s]

 61%|██████    | 3160/5184 [02:38<01:41, 19.94it/s]

 61%|██████    | 3163/5184 [02:38<01:40, 20.08it/s]

 61%|██████    | 3166/5184 [02:38<01:40, 20.10it/s]

 61%|██████    | 3169/5184 [02:38<01:40, 20.05it/s]

 61%|██████    | 3172/5184 [02:38<01:41, 19.91it/s]

 61%|██████    | 3174/5184 [02:39<01:41, 19.73it/s]

 61%|██████▏   | 3176/5184 [02:39<01:42, 19.60it/s]

 61%|██████▏   | 3178/5184 [02:39<01:43, 19.32it/s]

 61%|██████▏   | 3180/5184 [02:39<01:43, 19.34it/s]

 61%|██████▏   | 3182/5184 [02:39<01:42, 19.45it/s]

 61%|██████▏   | 3184/5184 [02:39<01:42, 19.47it/s]

 61%|██████▏   | 3186/5184 [02:39<01:42, 19.50it/s]

 61%|██████▏   | 3188/5184 [02:39<01:42, 19.54it/s]

 62%|██████▏   | 3190/5184 [02:39<01:41, 19.58it/s]

 62%|██████▏   | 3192/5184 [02:39<01:41, 19.62it/s]

 62%|██████▏   | 3194/5184 [02:40<01:41, 19.55it/s]

 62%|██████▏   | 3196/5184 [02:40<01:41, 19.59it/s]

 62%|██████▏   | 3198/5184 [02:40<01:41, 19.61it/s]

 62%|██████▏   | 3200/5184 [02:40<01:40, 19.65it/s]

 62%|██████▏   | 3202/5184 [02:40<01:41, 19.57it/s]

 62%|██████▏   | 3204/5184 [02:40<01:42, 19.36it/s]

 62%|██████▏   | 3206/5184 [02:40<01:42, 19.21it/s]

 62%|██████▏   | 3208/5184 [02:40<01:43, 19.12it/s]

 62%|██████▏   | 3210/5184 [02:40<01:43, 19.08it/s]

 62%|██████▏   | 3212/5184 [02:41<01:43, 19.02it/s]

 62%|██████▏   | 3215/5184 [02:41<01:34, 20.85it/s]

 62%|██████▏   | 3218/5184 [02:41<01:37, 20.15it/s]

 62%|██████▏   | 3221/5184 [02:41<01:38, 19.86it/s]

 62%|██████▏   | 3224/5184 [02:41<01:37, 20.16it/s]

 62%|██████▏   | 3227/5184 [02:41<01:36, 20.35it/s]

 62%|██████▏   | 3230/5184 [02:41<01:35, 20.47it/s]

 62%|██████▏   | 3233/5184 [02:42<01:34, 20.54it/s]

 62%|██████▏   | 3236/5184 [02:42<01:34, 20.61it/s]

 62%|██████▏   | 3239/5184 [02:42<01:34, 20.63it/s]

 63%|██████▎   | 3242/5184 [02:42<01:34, 20.58it/s]

 63%|██████▎   | 3245/5184 [02:42<01:34, 20.42it/s]

 63%|██████▎   | 3248/5184 [02:42<01:35, 20.36it/s]

 63%|██████▎   | 3251/5184 [02:42<01:35, 20.29it/s]

 63%|██████▎   | 3254/5184 [02:43<01:35, 20.27it/s]

 63%|██████▎   | 3257/5184 [02:43<01:35, 20.12it/s]

 63%|██████▎   | 3260/5184 [02:43<01:35, 20.13it/s]

 63%|██████▎   | 3263/5184 [02:43<01:35, 20.11it/s]

 63%|██████▎   | 3266/5184 [02:43<01:35, 20.13it/s]

 63%|██████▎   | 3269/5184 [02:43<01:35, 20.14it/s]

 63%|██████▎   | 3272/5184 [02:43<01:34, 20.16it/s]

 63%|██████▎   | 3275/5184 [02:44<01:35, 19.92it/s]

 63%|██████▎   | 3277/5184 [02:44<01:36, 19.68it/s]

 63%|██████▎   | 3279/5184 [02:44<01:37, 19.44it/s]

 63%|██████▎   | 3281/5184 [02:44<01:38, 19.34it/s]

 63%|██████▎   | 3283/5184 [02:44<01:38, 19.28it/s]

 63%|██████▎   | 3285/5184 [02:44<01:39, 19.18it/s]

 63%|██████▎   | 3288/5184 [02:44<01:29, 21.30it/s]

 63%|██████▎   | 3291/5184 [02:44<01:31, 20.63it/s]

 64%|██████▎   | 3294/5184 [02:45<01:32, 20.37it/s]

 64%|██████▎   | 3297/5184 [02:45<01:32, 20.49it/s]

 64%|██████▎   | 3300/5184 [02:45<01:31, 20.50it/s]

 64%|██████▎   | 3303/5184 [02:45<01:31, 20.56it/s]

 64%|██████▍   | 3306/5184 [02:45<01:30, 20.65it/s]

 64%|██████▍   | 3309/5184 [02:45<01:30, 20.68it/s]

 64%|██████▍   | 3312/5184 [02:45<01:30, 20.71it/s]

 64%|██████▍   | 3315/5184 [02:46<01:31, 20.43it/s]

 64%|██████▍   | 3318/5184 [02:46<01:32, 20.24it/s]

 64%|██████▍   | 3321/5184 [02:46<01:32, 20.16it/s]

 64%|██████▍   | 3324/5184 [02:46<01:32, 20.09it/s]

 64%|██████▍   | 3327/5184 [02:46<01:32, 20.02it/s]

 64%|██████▍   | 3330/5184 [02:46<01:32, 19.95it/s]

 64%|██████▍   | 3332/5184 [02:46<01:33, 19.80it/s]

 64%|██████▍   | 3335/5184 [02:47<01:33, 19.88it/s]

 64%|██████▍   | 3337/5184 [02:47<01:32, 19.88it/s]

 64%|██████▍   | 3339/5184 [02:47<01:33, 19.68it/s]

 64%|██████▍   | 3341/5184 [02:47<01:33, 19.74it/s]

 65%|██████▍   | 3344/5184 [02:47<01:32, 19.84it/s]

 65%|██████▍   | 3346/5184 [02:47<01:33, 19.74it/s]

 65%|██████▍   | 3348/5184 [02:47<01:33, 19.55it/s]

 65%|██████▍   | 3350/5184 [02:47<01:34, 19.48it/s]

 65%|██████▍   | 3352/5184 [02:47<01:34, 19.38it/s]

 65%|██████▍   | 3354/5184 [02:48<01:34, 19.30it/s]

 65%|██████▍   | 3356/5184 [02:48<01:34, 19.25it/s]

 65%|██████▍   | 3358/5184 [02:48<01:35, 19.21it/s]

 65%|██████▍   | 3361/5184 [02:48<01:25, 21.35it/s]

 65%|██████▍   | 3364/5184 [02:48<01:27, 20.71it/s]

 65%|██████▍   | 3367/5184 [02:48<01:28, 20.50it/s]

 65%|██████▌   | 3370/5184 [02:48<01:27, 20.62it/s]

 65%|██████▌   | 3373/5184 [02:48<01:27, 20.67it/s]

 65%|██████▌   | 3376/5184 [02:49<01:27, 20.69it/s]

 65%|██████▌   | 3379/5184 [02:49<01:27, 20.63it/s]

 65%|██████▌   | 3382/5184 [02:49<01:27, 20.62it/s]

 65%|██████▌   | 3385/5184 [02:49<01:27, 20.64it/s]

 65%|██████▌   | 3388/5184 [02:49<01:27, 20.48it/s]

 65%|██████▌   | 3391/5184 [02:49<01:27, 20.38it/s]

 65%|██████▌   | 3394/5184 [02:49<01:28, 20.34it/s]

 66%|██████▌   | 3397/5184 [02:50<01:28, 20.28it/s]

 66%|██████▌   | 3400/5184 [02:50<01:28, 20.19it/s]

 66%|██████▌   | 3403/5184 [02:50<01:28, 20.20it/s]

 66%|██████▌   | 3406/5184 [02:50<01:28, 20.18it/s]

 66%|██████▌   | 3409/5184 [02:50<01:27, 20.19it/s]

 66%|██████▌   | 3412/5184 [02:50<01:27, 20.20it/s]

 66%|██████▌   | 3415/5184 [02:51<01:27, 20.16it/s]

 66%|██████▌   | 3418/5184 [02:51<01:28, 20.07it/s]

 66%|██████▌   | 3421/5184 [02:51<01:29, 19.60it/s]

 66%|██████▌   | 3423/5184 [02:51<01:30, 19.41it/s]

 66%|██████▌   | 3425/5184 [02:51<01:31, 19.32it/s]

 66%|██████▌   | 3427/5184 [02:51<01:31, 19.26it/s]

 66%|██████▌   | 3429/5184 [02:51<01:31, 19.20it/s]

 66%|██████▌   | 3431/5184 [02:51<01:31, 19.16it/s]

 66%|██████▌   | 3434/5184 [02:51<01:22, 21.32it/s]

 66%|██████▋   | 3437/5184 [02:52<01:24, 20.67it/s]

 66%|██████▋   | 3440/5184 [02:52<01:24, 20.61it/s]

 66%|██████▋   | 3443/5184 [02:52<01:24, 20.62it/s]

 66%|██████▋   | 3446/5184 [02:52<01:24, 20.64it/s]

 67%|██████▋   | 3449/5184 [02:52<01:23, 20.68it/s]

 67%|██████▋   | 3452/5184 [02:52<01:23, 20.68it/s]

 67%|██████▋   | 3455/5184 [02:52<01:23, 20.72it/s]

 67%|██████▋   | 3458/5184 [02:53<01:23, 20.55it/s]

 67%|██████▋   | 3461/5184 [02:53<01:24, 20.34it/s]

 67%|██████▋   | 3464/5184 [02:53<01:24, 20.26it/s]

 67%|██████▋   | 3467/5184 [02:53<01:25, 20.17it/s]

 67%|██████▋   | 3470/5184 [02:53<01:25, 20.13it/s]

 67%|██████▋   | 3473/5184 [02:53<01:25, 20.08it/s]

 67%|██████▋   | 3476/5184 [02:54<01:25, 20.05it/s]

 67%|██████▋   | 3479/5184 [02:54<01:25, 20.01it/s]

 67%|██████▋   | 3482/5184 [02:54<01:25, 20.00it/s]

 67%|██████▋   | 3485/5184 [02:54<01:24, 20.04it/s]

 67%|██████▋   | 3488/5184 [02:54<01:24, 20.06it/s]

 67%|██████▋   | 3491/5184 [02:54<01:25, 19.91it/s]

 67%|██████▋   | 3493/5184 [02:54<01:25, 19.70it/s]

 67%|██████▋   | 3495/5184 [02:55<01:26, 19.53it/s]

 67%|██████▋   | 3497/5184 [02:55<01:26, 19.44it/s]

 67%|██████▋   | 3499/5184 [02:55<01:26, 19.37it/s]

 68%|██████▊   | 3501/5184 [02:55<01:27, 19.27it/s]

 68%|██████▊   | 3503/5184 [02:55<01:27, 19.29it/s]

 68%|██████▊   | 3506/5184 [02:55<01:18, 21.39it/s]

 68%|██████▊   | 3509/5184 [02:55<01:21, 20.59it/s]

 68%|██████▊   | 3512/5184 [02:55<01:20, 20.65it/s]

 68%|██████▊   | 3515/5184 [02:55<01:20, 20.67it/s]

 68%|██████▊   | 3518/5184 [02:56<01:20, 20.68it/s]

 68%|██████▊   | 3521/5184 [02:56<01:20, 20.74it/s]

 68%|██████▊   | 3524/5184 [02:56<01:19, 20.78it/s]

 68%|██████▊   | 3527/5184 [02:56<01:19, 20.78it/s]

 68%|██████▊   | 3530/5184 [02:56<01:20, 20.64it/s]

 68%|██████▊   | 3533/5184 [02:56<01:20, 20.47it/s]

 68%|██████▊   | 3536/5184 [02:56<01:21, 20.34it/s]

 68%|██████▊   | 3539/5184 [02:57<01:21, 20.27it/s]

 68%|██████▊   | 3542/5184 [02:57<01:21, 20.25it/s]

 68%|██████▊   | 3545/5184 [02:57<01:21, 20.18it/s]

 68%|██████▊   | 3548/5184 [02:57<01:20, 20.20it/s]

 68%|██████▊   | 3551/5184 [02:57<01:21, 20.15it/s]

 69%|██████▊   | 3554/5184 [02:57<01:21, 20.12it/s]

 69%|██████▊   | 3557/5184 [02:58<01:21, 20.08it/s]

 69%|██████▊   | 3560/5184 [02:58<01:20, 20.09it/s]

 69%|██████▊   | 3563/5184 [02:58<01:21, 19.85it/s]

 69%|██████▉   | 3565/5184 [02:58<01:22, 19.60it/s]

 69%|██████▉   | 3567/5184 [02:58<01:23, 19.41it/s]

 69%|██████▉   | 3569/5184 [02:58<01:23, 19.29it/s]

 69%|██████▉   | 3571/5184 [02:58<01:23, 19.29it/s]

 69%|██████▉   | 3573/5184 [02:58<01:23, 19.23it/s]

 69%|██████▉   | 3575/5184 [02:58<01:24, 18.93it/s]

 69%|██████▉   | 3577/5184 [02:59<01:25, 18.81it/s]

 69%|██████▉   | 3580/5184 [02:59<01:16, 20.94it/s]

 69%|██████▉   | 3583/5184 [02:59<01:17, 20.69it/s]

 69%|██████▉   | 3586/5184 [02:59<01:17, 20.73it/s]

 69%|██████▉   | 3589/5184 [02:59<01:16, 20.74it/s]

 69%|██████▉   | 3592/5184 [02:59<01:16, 20.72it/s]

 69%|██████▉   | 3595/5184 [02:59<01:16, 20.75it/s]

 69%|██████▉   | 3598/5184 [03:00<01:16, 20.76it/s]

 69%|██████▉   | 3601/5184 [03:00<01:16, 20.66it/s]

 70%|██████▉   | 3604/5184 [03:00<01:17, 20.48it/s]

 70%|██████▉   | 3607/5184 [03:00<01:17, 20.37it/s]

 70%|██████▉   | 3610/5184 [03:00<01:17, 20.26it/s]

 70%|██████▉   | 3613/5184 [03:00<01:17, 20.24it/s]

 70%|██████▉   | 3616/5184 [03:00<01:17, 20.17it/s]

 70%|██████▉   | 3619/5184 [03:01<01:17, 20.12it/s]

 70%|██████▉   | 3622/5184 [03:01<01:17, 20.13it/s]

 70%|██████▉   | 3625/5184 [03:01<01:17, 20.03it/s]

 70%|██████▉   | 3628/5184 [03:01<01:17, 19.97it/s]

 70%|███████   | 3630/5184 [03:01<01:19, 19.58it/s]

 70%|███████   | 3632/5184 [03:01<01:20, 19.25it/s]

 70%|███████   | 3634/5184 [03:01<01:20, 19.16it/s]

 70%|███████   | 3636/5184 [03:01<01:20, 19.14it/s]

 70%|███████   | 3638/5184 [03:02<01:20, 19.11it/s]

 70%|███████   | 3640/5184 [03:02<01:20, 19.14it/s]

 70%|███████   | 3642/5184 [03:02<01:20, 19.09it/s]

 70%|███████   | 3644/5184 [03:02<01:20, 19.06it/s]

 70%|███████   | 3646/5184 [03:02<01:20, 19.11it/s]

 70%|███████   | 3648/5184 [03:02<01:20, 19.15it/s]

 70%|███████   | 3650/5184 [03:02<01:20, 19.11it/s]

 70%|███████   | 3653/5184 [03:02<01:12, 21.23it/s]

 71%|███████   | 3656/5184 [03:02<01:12, 21.13it/s]

 71%|███████   | 3659/5184 [03:03<01:12, 21.04it/s]

 71%|███████   | 3662/5184 [03:03<01:12, 20.94it/s]

 71%|███████   | 3665/5184 [03:03<01:13, 20.76it/s]

 71%|███████   | 3668/5184 [03:03<01:14, 20.28it/s]

 71%|███████   | 3671/5184 [03:03<01:15, 19.98it/s]

 71%|███████   | 3674/5184 [03:03<01:16, 19.64it/s]

 71%|███████   | 3676/5184 [03:03<01:18, 19.28it/s]

 71%|███████   | 3678/5184 [03:04<01:19, 19.00it/s]

 71%|███████   | 3680/5184 [03:04<01:18, 19.24it/s]

 71%|███████   | 3683/5184 [03:04<01:17, 19.49it/s]

 71%|███████   | 3686/5184 [03:04<01:16, 19.67it/s]

 71%|███████   | 3688/5184 [03:04<01:15, 19.75it/s]

 71%|███████   | 3691/5184 [03:04<01:15, 19.86it/s]

 71%|███████▏  | 3694/5184 [03:04<01:14, 19.91it/s]

 71%|███████▏  | 3697/5184 [03:05<01:14, 19.98it/s]

 71%|███████▏  | 3699/5184 [03:05<01:14, 19.95it/s]

 71%|███████▏  | 3701/5184 [03:05<01:14, 19.93it/s]

 71%|███████▏  | 3703/5184 [03:05<01:14, 19.93it/s]

 71%|███████▏  | 3706/5184 [03:05<01:14, 19.89it/s]

 72%|███████▏  | 3708/5184 [03:05<01:15, 19.67it/s]

 72%|███████▏  | 3710/5184 [03:05<01:15, 19.51it/s]

 72%|███████▏  | 3712/5184 [03:05<01:15, 19.39it/s]

 72%|███████▏  | 3714/5184 [03:05<01:16, 19.34it/s]

 72%|███████▏  | 3716/5184 [03:06<01:15, 19.32it/s]

 72%|███████▏  | 3718/5184 [03:06<01:15, 19.29it/s]

 72%|███████▏  | 3720/5184 [03:06<01:15, 19.26it/s]

 72%|███████▏  | 3722/5184 [03:06<01:16, 19.17it/s]

 72%|███████▏  | 3725/5184 [03:06<01:08, 21.25it/s]

 72%|███████▏  | 3728/5184 [03:06<01:09, 21.07it/s]

 72%|███████▏  | 3731/5184 [03:06<01:09, 20.96it/s]

 72%|███████▏  | 3734/5184 [03:06<01:09, 20.89it/s]

 72%|███████▏  | 3737/5184 [03:07<01:09, 20.84it/s]

 72%|███████▏  | 3740/5184 [03:07<01:09, 20.79it/s]

 72%|███████▏  | 3743/5184 [03:07<01:09, 20.71it/s]

 72%|███████▏  | 3746/5184 [03:07<01:09, 20.56it/s]

 72%|███████▏  | 3749/5184 [03:07<01:10, 20.37it/s]

 72%|███████▏  | 3752/5184 [03:07<01:10, 20.27it/s]

 72%|███████▏  | 3755/5184 [03:07<01:10, 20.20it/s]

 72%|███████▏  | 3758/5184 [03:08<01:10, 20.17it/s]

 73%|███████▎  | 3761/5184 [03:08<01:10, 20.10it/s]

 73%|███████▎  | 3764/5184 [03:08<01:10, 20.07it/s]

 73%|███████▎  | 3767/5184 [03:08<01:10, 20.04it/s]

 73%|███████▎  | 3770/5184 [03:08<01:10, 20.04it/s]

 73%|███████▎  | 3773/5184 [03:08<01:10, 20.05it/s]

 73%|███████▎  | 3776/5184 [03:08<01:10, 20.03it/s]

 73%|███████▎  | 3779/5184 [03:09<01:10, 19.85it/s]

 73%|███████▎  | 3781/5184 [03:09<01:11, 19.61it/s]

 73%|███████▎  | 3783/5184 [03:09<01:12, 19.44it/s]

 73%|███████▎  | 3785/5184 [03:09<01:12, 19.33it/s]

 73%|███████▎  | 3787/5184 [03:09<01:12, 19.27it/s]

 73%|███████▎  | 3789/5184 [03:09<01:12, 19.22it/s]

 73%|███████▎  | 3791/5184 [03:09<01:12, 19.23it/s]

 73%|███████▎  | 3793/5184 [03:09<01:12, 19.15it/s]

 73%|███████▎  | 3795/5184 [03:09<01:12, 19.08it/s]

 73%|███████▎  | 3798/5184 [03:10<01:04, 21.39it/s]

 73%|███████▎  | 3801/5184 [03:10<01:05, 21.18it/s]

 73%|███████▎  | 3804/5184 [03:10<01:05, 21.03it/s]

 73%|███████▎  | 3807/5184 [03:10<01:06, 20.84it/s]

 73%|███████▎  | 3810/5184 [03:10<01:06, 20.81it/s]

 74%|███████▎  | 3813/5184 [03:10<01:06, 20.76it/s]

 74%|███████▎  | 3816/5184 [03:10<01:05, 20.78it/s]

 74%|███████▎  | 3819/5184 [03:11<01:05, 20.75it/s]

 74%|███████▎  | 3822/5184 [03:11<01:05, 20.70it/s]

 74%|███████▍  | 3825/5184 [03:11<01:05, 20.71it/s]

 74%|███████▍  | 3828/5184 [03:11<01:05, 20.71it/s]

 74%|███████▍  | 3831/5184 [03:11<01:05, 20.67it/s]

 74%|███████▍  | 3834/5184 [03:11<01:05, 20.65it/s]

 74%|███████▍  | 3837/5184 [03:11<01:05, 20.64it/s]

 74%|███████▍  | 3840/5184 [03:12<01:05, 20.65it/s]

 74%|███████▍  | 3843/5184 [03:12<01:04, 20.70it/s]

 74%|███████▍  | 3846/5184 [03:12<01:04, 20.71it/s]

 74%|███████▍  | 3849/5184 [03:12<01:07, 19.82it/s]

 74%|███████▍  | 3852/5184 [03:12<01:06, 20.04it/s]

 74%|███████▍  | 3855/5184 [03:12<01:05, 20.25it/s]

 74%|███████▍  | 3858/5184 [03:12<01:05, 20.39it/s]

 74%|███████▍  | 3861/5184 [03:13<01:04, 20.44it/s]

 75%|███████▍  | 3864/5184 [03:13<01:04, 20.51it/s]

 75%|███████▍  | 3867/5184 [03:13<01:04, 20.57it/s]

 75%|███████▍  | 3871/5184 [03:13<00:59, 22.08it/s]

 75%|███████▍  | 3874/5184 [03:13<01:02, 21.02it/s]

 75%|███████▍  | 3877/5184 [03:13<01:03, 20.45it/s]

 75%|███████▍  | 3880/5184 [03:14<01:04, 20.09it/s]

 75%|███████▍  | 3883/5184 [03:14<01:05, 19.84it/s]

 75%|███████▍  | 3885/5184 [03:14<01:06, 19.62it/s]

 75%|███████▍  | 3887/5184 [03:14<01:06, 19.54it/s]

 75%|███████▌  | 3889/5184 [03:14<01:06, 19.60it/s]

 75%|███████▌  | 3892/5184 [03:14<01:04, 19.96it/s]

 75%|███████▌  | 3895/5184 [03:14<01:03, 20.19it/s]

 75%|███████▌  | 3898/5184 [03:14<01:03, 20.36it/s]

 75%|███████▌  | 3901/5184 [03:15<01:02, 20.49it/s]

 75%|███████▌  | 3904/5184 [03:15<01:02, 20.53it/s]

 75%|███████▌  | 3907/5184 [03:15<01:01, 20.61it/s]

 75%|███████▌  | 3910/5184 [03:15<01:01, 20.65it/s]

 75%|███████▌  | 3913/5184 [03:15<01:01, 20.59it/s]

 76%|███████▌  | 3916/5184 [03:15<01:01, 20.64it/s]

 76%|███████▌  | 3919/5184 [03:15<01:01, 20.67it/s]

 76%|███████▌  | 3922/5184 [03:16<01:00, 20.70it/s]

 76%|███████▌  | 3925/5184 [03:16<01:00, 20.68it/s]

 76%|███████▌  | 3928/5184 [03:16<01:00, 20.69it/s]

 76%|███████▌  | 3931/5184 [03:16<01:00, 20.72it/s]

 76%|███████▌  | 3934/5184 [03:16<01:00, 20.73it/s]

 76%|███████▌  | 3937/5184 [03:16<01:00, 20.75it/s]

 76%|███████▌  | 3940/5184 [03:16<00:59, 20.77it/s]

 76%|███████▌  | 3943/5184 [03:17<00:54, 22.80it/s]

 76%|███████▌  | 3946/5184 [03:17<00:57, 21.49it/s]

 76%|███████▌  | 3949/5184 [03:17<00:59, 20.67it/s]

 76%|███████▌  | 3952/5184 [03:17<01:00, 20.24it/s]

 76%|███████▋  | 3955/5184 [03:17<01:01, 19.85it/s]

 76%|███████▋  | 3958/5184 [03:17<01:02, 19.73it/s]

 76%|███████▋  | 3960/5184 [03:17<01:02, 19.66it/s]

 76%|███████▋  | 3963/5184 [03:18<01:01, 19.98it/s]

 77%|███████▋  | 3966/5184 [03:18<01:00, 20.19it/s]

 77%|███████▋  | 3969/5184 [03:18<00:59, 20.32it/s]

 77%|███████▋  | 3972/5184 [03:18<00:59, 20.38it/s]

 77%|███████▋  | 3975/5184 [03:18<00:59, 20.32it/s]

 77%|███████▋  | 3978/5184 [03:18<00:59, 20.32it/s]

 77%|███████▋  | 3981/5184 [03:18<00:59, 20.33it/s]

 77%|███████▋  | 3984/5184 [03:19<00:58, 20.36it/s]

 77%|███████▋  | 3987/5184 [03:19<00:58, 20.31it/s]

 77%|███████▋  | 3990/5184 [03:19<00:58, 20.35it/s]

 77%|███████▋  | 3993/5184 [03:19<00:58, 20.40it/s]

 77%|███████▋  | 3996/5184 [03:19<00:58, 20.43it/s]

 77%|███████▋  | 3999/5184 [03:19<00:57, 20.55it/s]

 77%|███████▋  | 4002/5184 [03:19<00:57, 20.55it/s]

 77%|███████▋  | 4005/5184 [03:20<00:57, 20.55it/s]

 77%|███████▋  | 4008/5184 [03:20<00:57, 20.57it/s]

 77%|███████▋  | 4011/5184 [03:20<00:57, 20.53it/s]

 77%|███████▋  | 4014/5184 [03:20<00:57, 20.32it/s]

 77%|███████▋  | 4017/5184 [03:20<00:52, 22.08it/s]

 78%|███████▊  | 4020/5184 [03:20<00:55, 21.04it/s]

 78%|███████▊  | 4023/5184 [03:20<00:56, 20.43it/s]

 78%|███████▊  | 4026/5184 [03:21<00:57, 20.00it/s]

 78%|███████▊  | 4029/5184 [03:21<00:58, 19.70it/s]

 78%|███████▊  | 4031/5184 [03:21<00:58, 19.56it/s]

 78%|███████▊  | 4033/5184 [03:21<00:58, 19.62it/s]

 78%|███████▊  | 4036/5184 [03:21<00:57, 19.88it/s]

 78%|███████▊  | 4039/5184 [03:21<00:57, 20.05it/s]

 78%|███████▊  | 4042/5184 [03:21<00:56, 20.11it/s]

 78%|███████▊  | 4045/5184 [03:22<00:56, 20.10it/s]

 78%|███████▊  | 4048/5184 [03:22<00:56, 20.21it/s]

 78%|███████▊  | 4051/5184 [03:22<00:55, 20.34it/s]

 78%|███████▊  | 4054/5184 [03:22<00:55, 20.41it/s]

 78%|███████▊  | 4057/5184 [03:22<00:55, 20.44it/s]

 78%|███████▊  | 4060/5184 [03:22<00:54, 20.44it/s]

 78%|███████▊  | 4063/5184 [03:22<00:54, 20.49it/s]

 78%|███████▊  | 4066/5184 [03:23<00:54, 20.49it/s]

 78%|███████▊  | 4069/5184 [03:23<00:54, 20.31it/s]

 79%|███████▊  | 4072/5184 [03:23<00:54, 20.32it/s]

 79%|███████▊  | 4075/5184 [03:23<00:54, 20.22it/s]

 79%|███████▊  | 4078/5184 [03:23<00:54, 20.20it/s]

 79%|███████▊  | 4081/5184 [03:23<00:54, 20.31it/s]

 79%|███████▉  | 4084/5184 [03:24<00:53, 20.38it/s]

 79%|███████▉  | 4087/5184 [03:24<00:54, 20.03it/s]

 79%|███████▉  | 4090/5184 [03:24<00:49, 21.89it/s]

 79%|███████▉  | 4093/5184 [03:24<00:52, 20.93it/s]

 79%|███████▉  | 4096/5184 [03:24<00:53, 20.33it/s]

 79%|███████▉  | 4099/5184 [03:24<00:54, 19.93it/s]

 79%|███████▉  | 4102/5184 [03:24<00:54, 19.71it/s]

 79%|███████▉  | 4104/5184 [03:25<00:55, 19.62it/s]

 79%|███████▉  | 4107/5184 [03:25<00:54, 19.89it/s]

 79%|███████▉  | 4110/5184 [03:25<00:53, 20.08it/s]

 79%|███████▉  | 4113/5184 [03:25<00:53, 20.13it/s]

 79%|███████▉  | 4116/5184 [03:25<00:52, 20.23it/s]

 79%|███████▉  | 4119/5184 [03:25<00:52, 20.30it/s]

 80%|███████▉  | 4122/5184 [03:25<00:52, 20.40it/s]

 80%|███████▉  | 4125/5184 [03:26<00:51, 20.50it/s]

 80%|███████▉  | 4128/5184 [03:26<00:51, 20.53it/s]

 80%|███████▉  | 4131/5184 [03:26<00:51, 20.58it/s]

 80%|███████▉  | 4134/5184 [03:26<00:50, 20.61it/s]

 80%|███████▉  | 4137/5184 [03:26<00:50, 20.61it/s]

 80%|███████▉  | 4140/5184 [03:26<00:50, 20.65it/s]

 80%|███████▉  | 4143/5184 [03:26<00:50, 20.67it/s]

 80%|███████▉  | 4146/5184 [03:27<00:50, 20.66it/s]

 80%|████████  | 4149/5184 [03:27<00:50, 20.66it/s]

 80%|████████  | 4152/5184 [03:27<00:49, 20.71it/s]

 80%|████████  | 4155/5184 [03:27<00:49, 20.62it/s]

 80%|████████  | 4158/5184 [03:27<00:50, 20.42it/s]

 80%|████████  | 4161/5184 [03:27<00:51, 19.94it/s]

 80%|████████  | 4164/5184 [03:27<00:46, 21.91it/s]

 80%|████████  | 4167/5184 [03:28<00:48, 21.00it/s]

 80%|████████  | 4170/5184 [03:28<00:49, 20.42it/s]

 80%|████████  | 4173/5184 [03:28<00:50, 20.05it/s]

 81%|████████  | 4176/5184 [03:28<00:50, 19.85it/s]

 81%|████████  | 4179/5184 [03:28<00:50, 20.06it/s]

 81%|████████  | 4182/5184 [03:28<00:49, 20.24it/s]

 81%|████████  | 4185/5184 [03:28<00:49, 20.33it/s]

 81%|████████  | 4188/5184 [03:29<00:48, 20.38it/s]

 81%|████████  | 4191/5184 [03:29<00:48, 20.42it/s]

 81%|████████  | 4194/5184 [03:29<00:48, 20.48it/s]

 81%|████████  | 4197/5184 [03:29<00:48, 20.48it/s]

 81%|████████  | 4200/5184 [03:29<00:47, 20.51it/s]

 81%|████████  | 4203/5184 [03:29<00:47, 20.53it/s]

 81%|████████  | 4206/5184 [03:29<00:47, 20.50it/s]

 81%|████████  | 4209/5184 [03:30<00:47, 20.54it/s]

 81%|████████▏ | 4212/5184 [03:30<00:47, 20.59it/s]

 81%|████████▏ | 4215/5184 [03:30<00:47, 20.58it/s]

 81%|████████▏ | 4218/5184 [03:30<00:46, 20.57it/s]

 81%|████████▏ | 4221/5184 [03:30<00:46, 20.60it/s]

 81%|████████▏ | 4224/5184 [03:30<00:46, 20.63it/s]

 82%|████████▏ | 4227/5184 [03:31<00:46, 20.63it/s]

 82%|████████▏ | 4230/5184 [03:31<00:46, 20.41it/s]

 82%|████████▏ | 4233/5184 [03:31<00:47, 19.90it/s]

 82%|████████▏ | 4236/5184 [03:31<00:43, 21.88it/s]

 82%|████████▏ | 4239/5184 [03:31<00:46, 20.53it/s]

 82%|████████▏ | 4242/5184 [03:31<00:46, 20.06it/s]

 82%|████████▏ | 4245/5184 [03:31<00:47, 19.76it/s]

 82%|████████▏ | 4248/5184 [03:32<00:47, 19.66it/s]

 82%|████████▏ | 4251/5184 [03:32<00:46, 19.98it/s]

 82%|████████▏ | 4254/5184 [03:32<00:46, 20.16it/s]

 82%|████████▏ | 4257/5184 [03:32<00:45, 20.23it/s]

 82%|████████▏ | 4260/5184 [03:32<00:45, 20.36it/s]

 82%|████████▏ | 4263/5184 [03:32<00:44, 20.48it/s]

 82%|████████▏ | 4266/5184 [03:32<00:44, 20.55it/s]

 82%|████████▏ | 4269/5184 [03:33<00:44, 20.52it/s]

 82%|████████▏ | 4272/5184 [03:33<00:44, 20.52it/s]

 82%|████████▏ | 4275/5184 [03:33<00:44, 20.55it/s]

 83%|████████▎ | 4278/5184 [03:33<00:44, 20.32it/s]

 83%|████████▎ | 4281/5184 [03:33<00:44, 20.39it/s]

 83%|████████▎ | 4284/5184 [03:33<00:44, 20.45it/s]

 83%|████████▎ | 4287/5184 [03:33<00:43, 20.50it/s]

 83%|████████▎ | 4290/5184 [03:34<00:43, 20.53it/s]

 83%|████████▎ | 4293/5184 [03:34<00:43, 20.58it/s]

 83%|████████▎ | 4296/5184 [03:34<00:43, 20.60it/s]

 83%|████████▎ | 4299/5184 [03:34<00:42, 20.58it/s]

 83%|████████▎ | 4302/5184 [03:34<00:43, 20.41it/s]

 83%|████████▎ | 4305/5184 [03:34<00:43, 20.00it/s]

 83%|████████▎ | 4308/5184 [03:34<00:39, 21.99it/s]

 83%|████████▎ | 4311/5184 [03:35<00:41, 20.99it/s]

 83%|████████▎ | 4314/5184 [03:35<00:42, 20.43it/s]

 83%|████████▎ | 4317/5184 [03:35<00:43, 20.04it/s]

 83%|████████▎ | 4320/5184 [03:35<00:43, 19.72it/s]

 83%|████████▎ | 4323/5184 [03:35<00:43, 19.95it/s]

 83%|████████▎ | 4326/5184 [03:35<00:42, 20.12it/s]

 84%|████████▎ | 4329/5184 [03:36<00:42, 20.27it/s]

 84%|████████▎ | 4332/5184 [03:36<00:41, 20.35it/s]

 84%|████████▎ | 4335/5184 [03:36<00:41, 20.37it/s]

 84%|████████▎ | 4338/5184 [03:36<00:41, 20.42it/s]

 84%|████████▎ | 4341/5184 [03:36<00:41, 20.46it/s]

 84%|████████▍ | 4344/5184 [03:36<00:41, 20.45it/s]

 84%|████████▍ | 4347/5184 [03:36<00:40, 20.48it/s]

 84%|████████▍ | 4350/5184 [03:37<00:40, 20.46it/s]

 84%|████████▍ | 4353/5184 [03:37<00:40, 20.48it/s]

 84%|████████▍ | 4356/5184 [03:37<00:40, 20.48it/s]

 84%|████████▍ | 4359/5184 [03:37<00:40, 20.47it/s]

 84%|████████▍ | 4362/5184 [03:37<00:40, 20.41it/s]

 84%|████████▍ | 4365/5184 [03:37<00:40, 20.45it/s]

 84%|████████▍ | 4368/5184 [03:37<00:39, 20.51it/s]

 84%|████████▍ | 4371/5184 [03:38<00:39, 20.54it/s]

 84%|████████▍ | 4374/5184 [03:38<00:39, 20.34it/s]

 84%|████████▍ | 4377/5184 [03:38<00:40, 19.93it/s]

 84%|████████▍ | 4379/5184 [03:38<00:40, 19.65it/s]

 85%|████████▍ | 4382/5184 [03:38<00:37, 21.62it/s]

 85%|████████▍ | 4385/5184 [03:38<00:38, 20.82it/s]

 85%|████████▍ | 4388/5184 [03:38<00:39, 20.31it/s]

 85%|████████▍ | 4391/5184 [03:39<00:39, 20.02it/s]

 85%|████████▍ | 4394/5184 [03:39<00:39, 20.04it/s]

 85%|████████▍ | 4397/5184 [03:39<00:38, 20.20it/s]

 85%|████████▍ | 4400/5184 [03:39<00:38, 20.24it/s]

 85%|████████▍ | 4403/5184 [03:39<00:38, 20.25it/s]

 85%|████████▍ | 4406/5184 [03:39<00:38, 20.36it/s]

 85%|████████▌ | 4409/5184 [03:39<00:37, 20.41it/s]

 85%|████████▌ | 4412/5184 [03:40<00:37, 20.46it/s]

 85%|████████▌ | 4415/5184 [03:40<00:37, 20.49it/s]

 85%|████████▌ | 4418/5184 [03:40<00:37, 20.50it/s]

 85%|████████▌ | 4421/5184 [03:40<00:37, 20.48it/s]

 85%|████████▌ | 4424/5184 [03:40<00:37, 20.48it/s]

 85%|████████▌ | 4427/5184 [03:40<00:36, 20.49it/s]

 85%|████████▌ | 4430/5184 [03:40<00:36, 20.54it/s]

 86%|████████▌ | 4433/5184 [03:41<00:36, 20.52it/s]

 86%|████████▌ | 4436/5184 [03:41<00:36, 20.52it/s]

 86%|████████▌ | 4439/5184 [03:41<00:36, 20.57it/s]

 86%|████████▌ | 4442/5184 [03:41<00:36, 20.55it/s]

 86%|████████▌ | 4445/5184 [03:41<00:36, 20.51it/s]

 86%|████████▌ | 4448/5184 [03:41<00:36, 20.09it/s]

 86%|████████▌ | 4451/5184 [03:41<00:37, 19.79it/s]

 86%|████████▌ | 4453/5184 [03:42<00:37, 19.54it/s]

 86%|████████▌ | 4456/5184 [03:42<00:33, 21.51it/s]

 86%|████████▌ | 4459/5184 [03:42<00:35, 20.69it/s]

 86%|████████▌ | 4462/5184 [03:42<00:35, 20.13it/s]

 86%|████████▌ | 4465/5184 [03:42<00:35, 20.09it/s]

 86%|████████▌ | 4468/5184 [03:42<00:35, 20.33it/s]

 86%|████████▌ | 4471/5184 [03:42<00:34, 20.50it/s]

 86%|████████▋ | 4474/5184 [03:43<00:34, 20.63it/s]

 86%|████████▋ | 4477/5184 [03:43<00:34, 20.68it/s]

 86%|████████▋ | 4480/5184 [03:43<00:34, 20.70it/s]

 86%|████████▋ | 4483/5184 [03:43<00:33, 20.76it/s]

 87%|████████▋ | 4486/5184 [03:43<00:33, 20.68it/s]

 87%|████████▋ | 4489/5184 [03:43<00:33, 20.70it/s]

 87%|████████▋ | 4492/5184 [03:43<00:33, 20.73it/s]

 87%|████████▋ | 4495/5184 [03:44<00:33, 20.76it/s]

 87%|████████▋ | 4498/5184 [03:44<00:32, 20.79it/s]

 87%|████████▋ | 4501/5184 [03:44<00:32, 20.79it/s]

 87%|████████▋ | 4504/5184 [03:44<00:32, 20.80it/s]

 87%|████████▋ | 4507/5184 [03:44<00:32, 20.80it/s]

 87%|████████▋ | 4510/5184 [03:44<00:32, 20.84it/s]

 87%|████████▋ | 4513/5184 [03:44<00:32, 20.86it/s]

 87%|████████▋ | 4516/5184 [03:45<00:32, 20.80it/s]

 87%|████████▋ | 4519/5184 [03:45<00:32, 20.52it/s]

 87%|████████▋ | 4522/5184 [03:45<00:32, 20.20it/s]

 87%|████████▋ | 4525/5184 [03:45<00:33, 19.86it/s]

 87%|████████▋ | 4528/5184 [03:45<00:29, 21.89it/s]

 87%|████████▋ | 4531/5184 [03:45<00:31, 21.06it/s]

 87%|████████▋ | 4534/5184 [03:46<00:31, 20.57it/s]

 88%|████████▊ | 4537/5184 [03:46<00:31, 20.42it/s]

 88%|████████▊ | 4540/5184 [03:46<00:31, 20.56it/s]

 88%|████████▊ | 4543/5184 [03:46<00:31, 20.67it/s]

 88%|████████▊ | 4546/5184 [03:46<00:30, 20.70it/s]

 88%|████████▊ | 4549/5184 [03:46<00:30, 20.74it/s]

 88%|████████▊ | 4552/5184 [03:46<00:30, 20.72it/s]

 88%|████████▊ | 4555/5184 [03:47<00:30, 20.77it/s]

 88%|████████▊ | 4558/5184 [03:47<00:30, 20.81it/s]

 88%|████████▊ | 4561/5184 [03:47<00:29, 20.78it/s]

 88%|████████▊ | 4564/5184 [03:47<00:29, 20.80it/s]

 88%|████████▊ | 4567/5184 [03:47<00:29, 20.71it/s]

 88%|████████▊ | 4570/5184 [03:47<00:29, 20.72it/s]

 88%|████████▊ | 4573/5184 [03:47<00:29, 20.75it/s]

 88%|████████▊ | 4576/5184 [03:48<00:29, 20.81it/s]

 88%|████████▊ | 4579/5184 [03:48<00:29, 20.80it/s]

 88%|████████▊ | 4582/5184 [03:48<00:28, 20.84it/s]

 88%|████████▊ | 4585/5184 [03:48<00:28, 20.83it/s]

 89%|████████▊ | 4588/5184 [03:48<00:28, 20.83it/s]

 89%|████████▊ | 4591/5184 [03:48<00:28, 20.54it/s]

 89%|████████▊ | 4594/5184 [03:48<00:29, 20.21it/s]

 89%|████████▊ | 4597/5184 [03:49<00:29, 20.01it/s]

 89%|████████▊ | 4600/5184 [03:49<00:26, 21.99it/s]

 89%|████████▉ | 4603/5184 [03:49<00:27, 21.11it/s]

 89%|████████▉ | 4606/5184 [03:49<00:28, 20.63it/s]

 89%|████████▉ | 4609/5184 [03:49<00:28, 20.35it/s]

 89%|████████▉ | 4612/5184 [03:49<00:27, 20.50it/s]

 89%|████████▉ | 4615/5184 [03:49<00:27, 20.55it/s]

 89%|████████▉ | 4618/5184 [03:50<00:28, 19.99it/s]

 89%|████████▉ | 4621/5184 [03:50<00:28, 19.54it/s]

 89%|████████▉ | 4624/5184 [03:50<00:28, 19.91it/s]

 89%|████████▉ | 4627/5184 [03:50<00:27, 20.19it/s]

 89%|████████▉ | 4630/5184 [03:50<00:27, 20.38it/s]

 89%|████████▉ | 4633/5184 [03:50<00:26, 20.45it/s]

 89%|████████▉ | 4636/5184 [03:50<00:26, 20.51it/s]

 89%|████████▉ | 4639/5184 [03:51<00:26, 20.64it/s]

 90%|████████▉ | 4642/5184 [03:51<00:26, 20.71it/s]

 90%|████████▉ | 4645/5184 [03:51<00:25, 20.78it/s]

 90%|████████▉ | 4648/5184 [03:51<00:25, 20.75it/s]

 90%|████████▉ | 4651/5184 [03:51<00:25, 20.71it/s]

 90%|████████▉ | 4654/5184 [03:51<00:25, 20.79it/s]

 90%|████████▉ | 4657/5184 [03:51<00:25, 20.79it/s]

 90%|████████▉ | 4660/5184 [03:52<00:25, 20.82it/s]

 90%|████████▉ | 4663/5184 [03:52<00:25, 20.53it/s]

 90%|█████████ | 4666/5184 [03:52<00:25, 20.21it/s]

 90%|█████████ | 4669/5184 [03:52<00:25, 20.01it/s]

 90%|█████████ | 4672/5184 [03:52<00:25, 19.78it/s]

 90%|█████████ | 4675/5184 [03:52<00:23, 21.67it/s]

 90%|█████████ | 4678/5184 [03:52<00:24, 21.01it/s]

 90%|█████████ | 4681/5184 [03:53<00:24, 20.76it/s]

 90%|█████████ | 4684/5184 [03:53<00:23, 20.88it/s]

 90%|█████████ | 4687/5184 [03:53<00:23, 20.97it/s]

 90%|█████████ | 4690/5184 [03:53<00:23, 20.99it/s]

 91%|█████████ | 4693/5184 [03:53<00:23, 20.95it/s]

 91%|█████████ | 4696/5184 [03:53<00:23, 20.96it/s]

 91%|█████████ | 4699/5184 [03:53<00:23, 20.99it/s]

 91%|█████████ | 4702/5184 [03:54<00:22, 21.05it/s]

 91%|█████████ | 4705/5184 [03:54<00:22, 21.07it/s]

 91%|█████████ | 4708/5184 [03:54<00:22, 21.06it/s]

 91%|█████████ | 4711/5184 [03:54<00:22, 20.88it/s]

 91%|█████████ | 4714/5184 [03:54<00:22, 20.94it/s]

 91%|█████████ | 4717/5184 [03:54<00:22, 20.99it/s]

 91%|█████████ | 4720/5184 [03:54<00:22, 21.03it/s]

 91%|█████████ | 4723/5184 [03:55<00:21, 21.08it/s]

 91%|█████████ | 4726/5184 [03:55<00:21, 21.11it/s]

 91%|█████████ | 4729/5184 [03:55<00:21, 21.14it/s]

 91%|█████████▏| 4732/5184 [03:55<00:21, 21.17it/s]

 91%|█████████▏| 4735/5184 [03:55<00:21, 20.86it/s]

 91%|█████████▏| 4738/5184 [03:55<00:21, 20.54it/s]

 91%|█████████▏| 4741/5184 [03:56<00:21, 20.27it/s]

 92%|█████████▏| 4744/5184 [03:56<00:21, 20.04it/s]

 92%|█████████▏| 4747/5184 [03:56<00:19, 22.14it/s]

 92%|█████████▏| 4750/5184 [03:56<00:20, 21.37it/s]

 92%|█████████▏| 4753/5184 [03:56<00:20, 21.03it/s]

 92%|█████████▏| 4756/5184 [03:56<00:20, 20.96it/s]

 92%|█████████▏| 4759/5184 [03:56<00:20, 21.02it/s]

 92%|█████████▏| 4762/5184 [03:56<00:20, 21.02it/s]

 92%|█████████▏| 4765/5184 [03:57<00:19, 21.06it/s]

 92%|█████████▏| 4768/5184 [03:57<00:19, 21.02it/s]

 92%|█████████▏| 4771/5184 [03:57<00:19, 21.02it/s]

 92%|█████████▏| 4774/5184 [03:57<00:19, 21.05it/s]

 92%|█████████▏| 4777/5184 [03:57<00:19, 21.05it/s]

 92%|█████████▏| 4780/5184 [03:57<00:19, 21.10it/s]

 92%|█████████▏| 4783/5184 [03:57<00:19, 21.10it/s]

 92%|█████████▏| 4786/5184 [03:58<00:18, 21.12it/s]

 92%|█████████▏| 4789/5184 [03:58<00:18, 21.14it/s]

 92%|█████████▏| 4792/5184 [03:58<00:18, 21.16it/s]

 92%|█████████▏| 4795/5184 [03:58<00:18, 21.11it/s]

 93%|█████████▎| 4798/5184 [03:58<00:18, 21.04it/s]

 93%|█████████▎| 4801/5184 [03:58<00:18, 21.07it/s]

 93%|█████████▎| 4804/5184 [03:58<00:18, 21.04it/s]

 93%|█████████▎| 4807/5184 [03:59<00:18, 20.76it/s]

 93%|█████████▎| 4810/5184 [03:59<00:18, 20.45it/s]

 93%|█████████▎| 4813/5184 [03:59<00:18, 20.22it/s]

 93%|█████████▎| 4816/5184 [03:59<00:18, 19.98it/s]

 93%|█████████▎| 4818/5184 [03:59<00:18, 19.70it/s]

 93%|█████████▎| 4821/5184 [03:59<00:16, 21.86it/s]

 93%|█████████▎| 4824/5184 [03:59<00:16, 21.19it/s]

 93%|█████████▎| 4827/5184 [04:00<00:16, 21.19it/s]

 93%|█████████▎| 4830/5184 [04:00<00:16, 21.15it/s]

 93%|█████████▎| 4833/5184 [04:00<00:16, 21.17it/s]

 93%|█████████▎| 4836/5184 [04:00<00:16, 21.16it/s]

 93%|█████████▎| 4839/5184 [04:00<00:16, 21.11it/s]

 93%|█████████▎| 4842/5184 [04:00<00:16, 21.14it/s]

 93%|█████████▎| 4845/5184 [04:00<00:16, 21.17it/s]

 94%|█████████▎| 4848/5184 [04:01<00:15, 21.10it/s]

 94%|█████████▎| 4851/5184 [04:01<00:15, 21.13it/s]

 94%|█████████▎| 4854/5184 [04:01<00:15, 21.11it/s]

 94%|█████████▎| 4857/5184 [04:01<00:15, 21.15it/s]

 94%|█████████▍| 4860/5184 [04:01<00:15, 21.04it/s]

 94%|█████████▍| 4863/5184 [04:01<00:15, 21.05it/s]

 94%|█████████▍| 4866/5184 [04:01<00:15, 20.94it/s]

 94%|█████████▍| 4869/5184 [04:02<00:14, 21.00it/s]

 94%|█████████▍| 4872/5184 [04:02<00:14, 21.04it/s]

 94%|█████████▍| 4875/5184 [04:02<00:14, 21.11it/s]

 94%|█████████▍| 4878/5184 [04:02<00:14, 20.96it/s]

 94%|█████████▍| 4881/5184 [04:02<00:14, 20.52it/s]

 94%|█████████▍| 4884/5184 [04:02<00:14, 20.27it/s]

 94%|█████████▍| 4887/5184 [04:02<00:14, 20.05it/s]

 94%|█████████▍| 4890/5184 [04:03<00:14, 19.81it/s]

 94%|█████████▍| 4893/5184 [04:03<00:13, 21.95it/s]

 94%|█████████▍| 4896/5184 [04:03<00:13, 21.37it/s]

 95%|█████████▍| 4899/5184 [04:03<00:13, 21.30it/s]

 95%|█████████▍| 4902/5184 [04:03<00:13, 21.25it/s]

 95%|█████████▍| 4905/5184 [04:03<00:13, 21.24it/s]

 95%|█████████▍| 4908/5184 [04:03<00:12, 21.26it/s]

 95%|█████████▍| 4911/5184 [04:04<00:12, 21.24it/s]

 95%|█████████▍| 4914/5184 [04:04<00:12, 21.26it/s]

 95%|█████████▍| 4917/5184 [04:04<00:12, 21.31it/s]

 95%|█████████▍| 4920/5184 [04:04<00:12, 21.31it/s]

 95%|█████████▍| 4923/5184 [04:04<00:12, 21.31it/s]

 95%|█████████▌| 4926/5184 [04:04<00:12, 21.30it/s]

 95%|█████████▌| 4929/5184 [04:04<00:11, 21.30it/s]

 95%|█████████▌| 4932/5184 [04:05<00:11, 21.31it/s]

 95%|█████████▌| 4935/5184 [04:05<00:11, 21.31it/s]

 95%|█████████▌| 4938/5184 [04:05<00:11, 21.32it/s]

 95%|█████████▌| 4941/5184 [04:05<00:11, 21.36it/s]

 95%|█████████▌| 4944/5184 [04:05<00:11, 21.36it/s]

 95%|█████████▌| 4947/5184 [04:05<00:11, 21.38it/s]

 95%|█████████▌| 4950/5184 [04:05<00:11, 21.23it/s]

 96%|█████████▌| 4953/5184 [04:06<00:11, 20.86it/s]

 96%|█████████▌| 4956/5184 [04:06<00:11, 20.55it/s]

 96%|█████████▌| 4959/5184 [04:06<00:11, 20.34it/s]

 96%|█████████▌| 4962/5184 [04:06<00:11, 20.16it/s]

 96%|█████████▌| 4966/5184 [04:06<00:10, 21.79it/s]

 96%|█████████▌| 4969/5184 [04:06<00:10, 21.45it/s]

 96%|█████████▌| 4972/5184 [04:06<00:09, 21.42it/s]

 96%|█████████▌| 4975/5184 [04:07<00:09, 21.43it/s]

 96%|█████████▌| 4978/5184 [04:07<00:09, 21.41it/s]

 96%|█████████▌| 4981/5184 [04:07<00:09, 21.41it/s]

 96%|█████████▌| 4984/5184 [04:07<00:09, 21.40it/s]

 96%|█████████▌| 4987/5184 [04:07<00:09, 21.40it/s]

 96%|█████████▋| 4990/5184 [04:07<00:09, 21.34it/s]

 96%|█████████▋| 4993/5184 [04:07<00:08, 21.34it/s]

 96%|█████████▋| 4996/5184 [04:08<00:08, 21.37it/s]

 96%|█████████▋| 4999/5184 [04:08<00:08, 21.36it/s]

 96%|█████████▋| 5002/5184 [04:08<00:08, 21.36it/s]

 97%|█████████▋| 5005/5184 [04:08<00:08, 21.35it/s]

 97%|█████████▋| 5008/5184 [04:08<00:08, 21.32it/s]

 97%|█████████▋| 5011/5184 [04:08<00:08, 21.31it/s]

 97%|█████████▋| 5014/5184 [04:08<00:07, 21.34it/s]

 97%|█████████▋| 5017/5184 [04:09<00:07, 21.35it/s]

 97%|█████████▋| 5020/5184 [04:09<00:07, 21.32it/s]

 97%|█████████▋| 5023/5184 [04:09<00:07, 21.03it/s]

 97%|█████████▋| 5026/5184 [04:09<00:07, 20.72it/s]

 97%|█████████▋| 5029/5184 [04:09<00:07, 20.39it/s]

 97%|█████████▋| 5032/5184 [04:09<00:07, 20.26it/s]

 97%|█████████▋| 5035/5184 [04:09<00:07, 20.14it/s]

 97%|█████████▋| 5039/5184 [04:10<00:06, 21.73it/s]

 97%|█████████▋| 5042/5184 [04:10<00:06, 21.40it/s]

 97%|█████████▋| 5045/5184 [04:10<00:06, 21.37it/s]

 97%|█████████▋| 5048/5184 [04:10<00:06, 21.34it/s]

 97%|█████████▋| 5051/5184 [04:10<00:06, 21.27it/s]

 97%|█████████▋| 5054/5184 [04:10<00:06, 21.27it/s]

 98%|█████████▊| 5057/5184 [04:10<00:05, 21.30it/s]

 98%|█████████▊| 5060/5184 [04:11<00:05, 21.32it/s]

 98%|█████████▊| 5063/5184 [04:11<00:05, 21.30it/s]

 98%|█████████▊| 5066/5184 [04:11<00:05, 21.34it/s]

 98%|█████████▊| 5069/5184 [04:11<00:05, 21.35it/s]

 98%|█████████▊| 5072/5184 [04:11<00:05, 21.39it/s]

 98%|█████████▊| 5075/5184 [04:11<00:05, 21.39it/s]

 98%|█████████▊| 5078/5184 [04:11<00:04, 21.40it/s]

 98%|█████████▊| 5081/5184 [04:12<00:04, 21.41it/s]

 98%|█████████▊| 5084/5184 [04:12<00:04, 21.42it/s]

 98%|█████████▊| 5087/5184 [04:12<00:04, 21.42it/s]

 98%|█████████▊| 5090/5184 [04:12<00:04, 21.46it/s]

 98%|█████████▊| 5093/5184 [04:12<00:04, 21.44it/s]

 98%|█████████▊| 5096/5184 [04:12<00:04, 21.03it/s]

 98%|█████████▊| 5099/5184 [04:12<00:04, 20.76it/s]

 98%|█████████▊| 5102/5184 [04:13<00:03, 20.55it/s]

 98%|█████████▊| 5105/5184 [04:13<00:03, 20.32it/s]

 99%|█████████▊| 5108/5184 [04:13<00:03, 20.27it/s]

 99%|█████████▊| 5111/5184 [04:13<00:03, 22.45it/s]

 99%|█████████▊| 5114/5184 [04:13<00:03, 21.95it/s]

 99%|█████████▊| 5117/5184 [04:13<00:03, 21.73it/s]

 99%|█████████▉| 5120/5184 [04:13<00:02, 21.65it/s]

 99%|█████████▉| 5123/5184 [04:14<00:02, 21.62it/s]

 99%|█████████▉| 5126/5184 [04:14<00:02, 21.59it/s]

 99%|█████████▉| 5129/5184 [04:14<00:02, 21.56it/s]

 99%|█████████▉| 5132/5184 [04:14<00:02, 21.56it/s]

 99%|█████████▉| 5135/5184 [04:14<00:02, 21.51it/s]

 99%|█████████▉| 5138/5184 [04:14<00:02, 21.50it/s]

 99%|█████████▉| 5141/5184 [04:14<00:02, 21.45it/s]

 99%|█████████▉| 5144/5184 [04:15<00:01, 21.48it/s]

 99%|█████████▉| 5147/5184 [04:15<00:01, 21.49it/s]

 99%|█████████▉| 5150/5184 [04:15<00:01, 21.51it/s]

 99%|█████████▉| 5153/5184 [04:15<00:01, 21.55it/s]

 99%|█████████▉| 5156/5184 [04:15<00:01, 21.59it/s]

100%|█████████▉| 5159/5184 [04:15<00:01, 21.52it/s]

100%|█████████▉| 5162/5184 [04:15<00:01, 21.52it/s]

100%|█████████▉| 5165/5184 [04:15<00:00, 21.54it/s]

100%|█████████▉| 5168/5184 [04:16<00:00, 21.15it/s]

100%|█████████▉| 5171/5184 [04:16<00:00, 20.89it/s]

100%|█████████▉| 5174/5184 [04:16<00:00, 20.64it/s]

100%|█████████▉| 5177/5184 [04:16<00:00, 20.53it/s]

100%|█████████▉| 5180/5184 [04:16<00:00, 20.28it/s]

100%|█████████▉| 5183/5184 [04:16<00:00, 20.01it/s]

100%|██████████| 5184/5184 [04:16<00:00, 20.18it/s]

In [21]:
res_df

,Column Configuration,Differentia Bit Width,Stratum Retention Policy,Stratum Retention Policy Resolution Parameter,Stratigraphic Column Expected Retained Bits,Stratigraphic Column Mean Actual Retained Bits,Stratigraphic Column Target Retained Bits,Stratigraphic Column Expected Retained Bits Error,Stratigraphic Column Actual Num Retained Strata,Taxon Compared From,Taxon Compared To,Generation of Taxon Compared From,Generation of Taxon Compared To,Generation Of MRCA Lower Bound (inclusive),Generation Of MRCA Upper Bound (exclusive),MRCA Bound Confidence,Rank of Earliest Detectable Mrca With
0,actual_bits=63+actual_strata=63+bits_error=-1+...,1,TaperedDepthProportionalResolution,31,63,63.000000,64,-1,63,316552,316596,5000,5001,4736,5000,0.968750,512
1,actual_bits=56+actual_strata=7+bits_error=-8+d...,8,TaperedDepthProportionalResolution,3,56,56.000000,64,-8,7,316552,316596,5000,5001,4608,5000,0.996094,0
2,actual_bits=192+actual_strata=3+bits_error=128...,64,TaperedDepthProportionalResolution,1,192,192.000000,64,128,3,316552,316596,5000,5001,4096,5000,1.000000,0
3,actual_bits=511+actual_strata=511+bits_error=-...,1,TaperedDepthProportionalResolution,255,511,510.208333,512,-1,511,316552,316596,5000,5001,4960,5000,0.968750,64
4,actual_bits=504+actual_strata=63+bits_error=-8...,8,TaperedDepthProportionalResolution,31,504,504.000000,512,-8,63,316552,316596,5000,5001,4992,5000,0.996094,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
92011,actual_bits=472+actual_strata=59+bits_error=-4...,8,RecencyProportionalResolution,5,472,466.888889,512,-40,59,316622,316382,5001,4998,4992,4993,0.996094,0
92012,actual_bits=448+actual_strata=7+bits_error=-64...,64,RecencyProportionalResolution,0,448,407.111111,512,-64,7,316622,316382,5001,4998,4992,4998,1.000000,0
92013,actual_bits=4096+actual_strata=4096+bits_error...,1,RecencyProportionalResolution,1596,4096,4096.944444,4096,0,4096,316622,316382,5001,4998,4992,4997,0.968750,8
92014,actual_bits=4056+actual_strata=507+bits_error=...,8,RecencyProportionalResolution,71,4056,4050.888889,4096,-40,507,316622,316382,5001,4998,4992,4993,0.996094,0
92015,actual_bits=3776+actual_strata=59+bits_error=-...,64,RecencyProportionalResolution,5,3776,3735.111111,4096,-320,59,316622,316382,5001,4998,4992,4993,1.000000,0

In [22]:
nbm.print_dataframe_synopsis(res_df)

digest: c5df3c56863e0f0e9913efaf2b54c8aba949980c45d202301c8d894fa4343733
manifest:
  Column Configuration: '                              18#  ex., actual_bits=63+actual_strata=63+bits_error=-1+differentia=1+policy=TaperedDepthProportionalResolution+resolution=31+target_bits=64'
  Differentia Bit Width: '                             3#   ex., 1'
  Generation Of MRCA Lower Bound (inclusive): '        67#  ex., 4736'
  Generation Of MRCA Upper Bound (exclusive): '        49#  ex., 5000'
  Generation of Taxon Compared From: '                 4#   ex., 5000'
  Generation of Taxon Compared To: '                   4#   ex., 5001'
  MRCA Bound Confidence: '                             3#   ex., 0.96875'
  Rank of Earliest Detectable Mrca With: '             6#   ex., 512'
  Stratigraphic Column Actual Num Retained Strata: '   7#   ex., 63'
  Stratigraphic Column Expected Retained Bits: '       14#  ex., 63'
  Stratigraphic Column Expected Retained Bits Error: ' 9#   ex., -1'
  Stratigraphic Column Mean Actual Retained Bits: '    17#  ex., 63.0'
  Stratigraphic Column Target Retained Bits: '         3#   ex., 64'
  Stratum Retention Policy: '                          2#   ex., TaperedDepthProportionalResolution'
  Stratum Retention Policy Resolution Parameter: '     9#   ex., 31'
  Taxon Compared From: '                               72#  ex., 316552'
  Taxon Compared To: '                                 72#  ex., 316596'
num cols: 17
num cols all na: 0
num cols any na: 0
num na: 0
num rows: 92016
num rows all na: 0
num rows any na: 0
size: 61M

# Save Pairwise MRCA Estimates to File

In [23]:
res_df.to_csv(
    f'a=pairwise_mrca_estimates+source={data_filename}.gz',
    compression='gzip',
)
res_df.to_csv(
    f'a=pairwise_mrca_estimates+source={data_filename}',
)