In [1]:
import endomill
from nbmetalog import nbmetalog as nbm

In [2]:
nbm.print_metadata()

context: ci
hostname: 24716dd6de1b
interpreter: 3.8.10 (default, Sep 11 2024, 16:02:53)  [GCC 9.4.0]
nbcellexec: 2
nbname: phylogeny_simulation_mill
nbpath: /opt/hereditary-stratigraph-concept/binder/phylogenetic-inference/phylogeny_simulation_mill.ipynb
revision: null
session: 556d218d-8c62-48c5-846f-514ca80b1ab3
timestamp: 2024-11-03T00:57:44Z00:00


IPython==7.16.1
keyname==0.4.1
yaml==5.3.1
endomill==0.1.3
nbmetalog==0.2.6
re==2.2.1
ipython_genutils==0.2.0
logging==0.5.1.2
zmq==22.3.0
json==2.0.9
ipykernel==5.5.3

In [3]:
endomill.instantiate_over(
    parameter_packs=[
        {
            'data_url': data_url,
            'data_filename': data_filename,
        }
        for data_filename, data_url in [
            (
                'nk_ecoeaselection_seed110_pop100_mut.01_snapshot_3000.csv',
                'https://osf.io/5d3be/',
            ),
            (
                'nk_lexicaseselection_seed110_pop165_mut.01_snapshot_500.csv',
                'https://osf.io/8ycq7/',
            ),
            (
                'nk_randomselection_seed7_pop100_mut.01_snapshot_5000.csv',
                'https://osf.io/ydxt7/',
            ),
            (
                'nk_sharingselection_seed10_pop100_mut.01_snapshot_5000.csv',
                'https://osf.io/cz9fk/',
            ),
            (
                'nk_tournamentselection_seed140_pop100_mut.01_snapshot_5000.csv',
                'https://osf.io/5ubn8/',
            )
        ]
    ],
)

detected executing.endomill.ipynb file
skipping instantiate_over

In [4]:
# define papermill parameters
data_url: str
data_filename: str

In [5]:
# Parameters
data_url = "https://osf.io/5d3be/"
data_filename = "nk_ecoeaselection_seed110_pop100_mut.01_snapshot_3000.csv"

In [6]:
import anytree
from bs4 import BeautifulSoup
from collections import defaultdict
from hstrat import hstrat
from interval_search import doubling_search
from iterpop import iterpop as ip
import itertools as it
from keyname import keyname as kn
import numpy as np
import opytional as opyt
import pandas as pd
import random
import sys
from tqdm import tqdm
from urllib import request

In [7]:
random.seed(1) # ensure reproducibility
sys.setrecursionlimit(100000) # anytree exceeds default recursion limit on our data

In [8]:
from nbmetalog import nbmetalog as nbm
nbm.print_metadata()

context: ci
hostname: 24716dd6de1b
interpreter: 3.8.10 (default, Sep 11 2024, 16:02:53)  [GCC 9.4.0]
nbcellexec: 8
nbname: phylogeny_simulation_mill
nbpath: /opt/hereditary-stratigraph-concept/binder/phylogenetic-inference/phylogeny_simulation_mill.ipynb
revision: null
session: 556d218d-8c62-48c5-846f-514ca80b1ab3
timestamp: 2024-11-03T00:57:44Z00:00


IPython==7.16.1
endomill==0.1.3
ipykernel==5.5.3
ipython_genutils==0.2.0
json==2.0.9
keyname==0.4.1
logging==0.5.1.2
nbmetalog==0.2.6
re==2.2.1
yaml==5.3.1
zmq==22.3.0
anytree==2.8.0
hstrat==0.3.2
iterpop==0.4.0
numpy==1.21.5
opytional==0.1.0
pandas==2.0.3

In [9]:
endomill.add_instance_outpath(
    f'a=phylogeny_simulation+source={data_filename}.endomill.ipynb',
)

# Retrieve Target Phylogeny from OSF

In [10]:
target_phylogeny_df = pd.read_csv(
    f'{data_url}/download',
)

nbm.print_dataframe_synopsis(target_phylogeny_df)

digest: 31ede04444a8c22e5c81fd700f8d63385862d0125173deb539510e8df81bd6b3
manifest:
  ancestor_list: '    356#  ex., [285064]'
  depth: '            320#  ex., 318'
  destruction_time: ' 308#  ex., inf'
  id: '               492#  ex., 286082'
  num_offspring: '    11#   ex., 0'
  num_orgs: '         18#   ex., 1'
  origin_time: '      337#  ex., 3000'
  phenotype: '        276#  ex., [ 0.212209 0.40814 0.0984858 0.442382 0.480717 0.336601
    0.00856907 0.39548 0.193967 0.12958 0.0293499 0.853584 0.254936 0.949996 0.188853
    0.345937 0.113471 0.399652 0.499309 0.796683 ]'
  tot_orgs: '         279#  ex., 1'
  total_offspring: '  16#   ex., 0'
num cols: 10
num cols all na: 0
num cols any na: 0
num na: 0
num rows: 492
num rows all na: 0
num rows any na: 0
size: 177K

# Create a Tree with Target Phylogeny Structure

In [11]:
# map id to anytree node
nodes = defaultdict(anytree.AnyNode)
for __, row in target_phylogeny_df.iterrows():
    node = nodes[row['id']]
    node.id = row['id']
    node.origin_time = row['origin_time']
    if 'NONE' not in row['ancestor_list']:
        ancestor_id = ip.popsingleton(
            eval(row['ancestor_list'])
        )
        node.parent = nodes[ancestor_id]

roots = {node.root for node in nodes.values()}

In [12]:
root = ip.popsingleton(roots)
root.height

319

In [13]:
max_origin_time = target_phylogeny_df['origin_time'].max()
max_origin_time

3000

In [14]:
mean_leaf_origin_time = np.mean([
    leaf.origin_time
    for leaf in root.leaves
])
mean_leaf_origin_time

2999.5328467153286

# Pick Parameters for Hereditary Stratigraphic Columns

In [15]:
def make_conditions(num_generations: int) -> pd.DataFrame:
    res = []
    for condemner_factory, target_column_bits, differentia_bit_width in it.product(
        [
            hstrat.StratumRetentionCondemnerTaperedDepthProportionalResolution,
            hstrat.StratumRetentionCondemnerRecencyProportionalResolution,
        ],
        [
            64,
            64 * 8,
            64 * 64,
        ],
        [
            1,
            8,
            64,
        ],
    ):
        policy_param = doubling_search(
            lambda x: \
                condemner_factory(x + 1).CalcNumStrataRetainedExact(num_generations)
                * differentia_bit_width > target_column_bits or x >= num_generations,
            {
                hstrat.StratumRetentionCondemnerTaperedDepthProportionalResolution: 1,
                hstrat.StratumRetentionCondemnerRecencyProportionalResolution: 0,
            }[condemner_factory],
        )

        actual_column_strata = condemner_factory(policy_param).CalcNumStrataRetainedExact(num_generations)
        actual_column_bits = actual_column_strata * differentia_bit_width

        res.append({
            'Retention Policy' : condemner_factory.__name__[25:],
            'Differentia Bit Width' : differentia_bit_width,
            'Retention Policy Resolution Parameter' : policy_param,
            'Target Retained Bits' : target_column_bits,
            'Actual Retained Bits' : actual_column_bits,
            'Retained Bits Error' : actual_column_bits - target_column_bits,
            'Actual Retained Strata' : actual_column_strata,
            'condemner' : condemner_factory(policy_param),
        })
    return pd.DataFrame.from_records(res)

In [16]:
conditions_df = make_conditions(int(mean_leaf_origin_time))
conditions_df.drop('condemner', axis=1)

,Retention Policy,Differentia Bit Width,Retention Policy Resolution Parameter,Target Retained Bits,Actual Retained Bits,Retained Bits Error,Actual Retained Strata
0,TaperedDepthProportionalResolution,1,31,64,63,-1,63
1,TaperedDepthProportionalResolution,8,3,64,56,-8,7
2,TaperedDepthProportionalResolution,64,1,64,192,128,3
3,TaperedDepthProportionalResolution,1,255,512,511,-1,511
4,TaperedDepthProportionalResolution,8,31,512,504,-8,63
5,TaperedDepthProportionalResolution,64,3,512,448,-64,7
6,TaperedDepthProportionalResolution,1,2999,4096,2999,-1097,2999
7,TaperedDepthProportionalResolution,8,255,4096,4088,-8,511
8,TaperedDepthProportionalResolution,64,31,4096,4032,-64,63
9,RecencyProportionalResolution,1,5,64,57,-7,57
10,RecencyProportionalResolution,8,0,64,72,8,9
11,RecencyProportionalResolution,64,0,64,576,512,9
12,RecencyProportionalResolution,1,83,512,512,0,512
13,RecencyProportionalResolution,8,5,512,456,-56,57
14,RecencyProportionalResolution,64,0,512,576,64,9
15,RecencyProportionalResolution,1,2999,4096,2999,-1097,2999
16,RecencyProportionalResolution,8,83,4096,4096,0,512
17,RecencyProportionalResolution,64,5,4096,3648,-448,57

# Set Up Ancestor Column

In [17]:
bundle = hstrat.HereditaryStratigraphicColumnBundle({
    kn.pack({
        'differentia' : row['Differentia Bit Width'],
        'policy' : row['Retention Policy'],
        'resolution' : row['Retention Policy Resolution Parameter'],
        'target_bits' : row['Target Retained Bits'],
        'actual_bits' : row['Actual Retained Bits'],
        'bits_error' : row['Retained Bits Error'],
        'actual_strata' : row['Actual Retained Strata'],
    }) \
        : hstrat.HereditaryStratigraphicColumn(
            stratum_differentia_bit_width=row['Differentia Bit Width'],
            stratum_retention_condemner=row['condemner'],
    )
    for __, row in conditions_df.iterrows()
})

# Simulate Inheritance of Ancestor Column Down Phylogenetic Tree

In [18]:
root = ip.popsingleton(roots)
root.hstrat_column = bundle

for node in anytree.LevelOrderIter(ip.popsingleton(roots)):
    parent = node.parent
    if parent is not None:
        node.hstrat_column = parent.hstrat_column.Clone()
        for __ in range(node.origin_time - parent.origin_time): node.hstrat_column.DepositStratum()

# Extract Pairwise MRCA Estimates for Extant Organisms

In [19]:
# impl -> mean retained bits
mean_retained_bits = {
    impl: np.mean([
        node.hstrat_column.GetNumStrataRetained()[impl]
        * int(kn.unpack(impl)['differentia'])
        for node in root.leaves
    ])
    for impl in bundle
}

records = [
    {
        **{
            'Mean Actual Retained Bits': v,
        },
        **kn.unpack(k)
    }
    for k, v in mean_retained_bits.items()
]
actual_retained_bits_df = pd.DataFrame.from_records(records)
actual_retained_bits_df.to_csv(
    f'a=actual_retained_bits+source={data_filename}',
)

actual_retained_bits_df

,Mean Actual Retained Bits,actual_bits,actual_strata,bits_error,differentia,policy,resolution,target_bits,_
0,63.000000,63,63,-1,1,TaperedDepthProportionalResolution,31,64,actual_bits=63+actual_strata=63+bits_error=-1+...
1,56.000000,56,7,-8,8,TaperedDepthProportionalResolution,3,64,actual_bits=56+actual_strata=7+bits_error=-8+d...
2,192.000000,192,3,128,64,TaperedDepthProportionalResolution,1,64,actual_bits=192+actual_strata=3+bits_error=128...
3,510.226277,511,511,-1,1,TaperedDepthProportionalResolution,255,512,actual_bits=511+actual_strata=511+bits_error=-...
4,504.000000,504,63,-8,8,TaperedDepthProportionalResolution,31,512,actual_bits=504+actual_strata=63+bits_error=-8...
5,448.000000,448,7,-64,64,TaperedDepthProportionalResolution,3,512,actual_bits=448+actual_strata=7+bits_error=-64...
6,3000.532847,2999,2999,-1097,1,TaperedDepthProportionalResolution,2999,4096,actual_bits=2999+actual_strata=2999+bits_error...
7,4081.810219,4088,511,-8,8,TaperedDepthProportionalResolution,255,4096,actual_bits=4088+actual_strata=511+bits_error=...
8,4032.000000,4032,63,-64,64,TaperedDepthProportionalResolution,31,4096,actual_bits=4032+actual_strata=63+bits_error=-...
9,56.364964,57,57,-7,1,RecencyProportionalResolution,5,64,actual_bits=57+actual_strata=57+bits_error=-7+...
10,66.919708,72,9,8,8,RecencyProportionalResolution,0,64,actual_bits=72+actual_strata=9+bits_error=8+di...
11,535.357664,576,9,512,64,RecencyProportionalResolution,0,64,actual_bits=576+actual_strata=9+bits_error=512...
12,511.364964,512,512,0,1,RecencyProportionalResolution,83,512,actual_bits=512+actual_strata=512+bits_error=0...
13,450.919708,456,57,-56,8,RecencyProportionalResolution,5,512,actual_bits=456+actual_strata=57+bits_error=-5...
14,535.357664,576,9,64,64,RecencyProportionalResolution,0,512,actual_bits=576+actual_strata=9+bits_error=64+...
15,3000.532847,2999,2999,-1097,1,RecencyProportionalResolution,2999,4096,actual_bits=2999+actual_strata=2999+bits_error...
16,4090.919708,4096,512,0,8,RecencyProportionalResolution,83,4096,actual_bits=4096+actual_strata=512+bits_error=...
17,3607.357664,3648,57,-448,64,RecencyProportionalResolution,5,4096,actual_bits=3648+actual_strata=57+bits_error=-...

In [20]:
res = []
for extant1, extant2 in tqdm([*it.product(root.leaves, root.leaves)]):
    if extant1 != extant2:
        bounds = extant1.hstrat_column.CalcRankOfMrcaBoundsWith(extant2.hstrat_column)
        for impl in extant1.hstrat_column:
            res.append({
                'Column Configuration' \
                    : impl,
                'Differentia Bit Width' \
                    : kn.unpack(impl)['differentia'],
                'Stratum Retention Policy' \
                    : kn.unpack(impl)['policy'],
                'Stratum Retention Policy Resolution Parameter' \
                    : kn.unpack(impl)['resolution'],
                'Stratigraphic Column Expected Retained Bits' \
                    : kn.unpack(impl)['actual_bits'],
                'Stratigraphic Column Mean Actual Retained Bits' \
                    : mean_retained_bits[impl],
                'Stratigraphic Column Target Retained Bits' \
                    : kn.unpack(impl)['target_bits'],
                'Stratigraphic Column Expected Retained Bits Error' \
                    : kn.unpack(impl)['bits_error'],
                'Stratigraphic Column Actual Num Retained Strata' \
                    : kn.unpack(impl)['actual_strata'],
                'Taxon Compared From' \
                    : extant1.id,
                'Taxon Compared To' \
                    : extant2.id,
                'Generation of Taxon Compared From' \
                    : extant1.hstrat_column.GetNumStrataDeposited(),
                'Generation of Taxon Compared To' \
                    : extant2.hstrat_column.GetNumStrataDeposited(),
                'Generation Of MRCA Lower Bound (inclusive)' \
                    : opyt.apply_if(
                        bounds[impl],
                        lambda x: x[0],
                    ),
                'Generation Of MRCA Upper Bound (exclusive)' \
                    : opyt.apply_if(
                        bounds[impl],
                        lambda x: x[1],
                    ),
                'MRCA Bound Confidence' \
                    : extant1.hstrat_column[impl].CalcRankOfMrcaBoundsWithProvidedConfidenceLevel(),
                'Rank of Earliest Detectable Mrca With' \
                    : extant1.hstrat_column[impl].CalcRankOfEarliestDetectableMrcaWith(extant2.hstrat_column[impl]),
            })

res_df = pd.DataFrame.from_records(res)

  0%|          | 0/18769 [00:00<?, ?it/s]

  0%|          | 4/18769 [00:00<10:10, 30.71it/s]

  0%|          | 7/18769 [00:00<11:08, 28.05it/s]

  0%|          | 10/18769 [00:00<11:48, 26.48it/s]

  0%|          | 13/18769 [00:00<12:17, 25.44it/s]

  0%|          | 16/18769 [00:00<12:36, 24.79it/s]

  0%|          | 19/18769 [00:00<12:50, 24.33it/s]

  0%|          | 22/18769 [00:00<12:59, 24.05it/s]

  0%|          | 25/18769 [00:01<13:07, 23.81it/s]

  0%|          | 28/18769 [00:01<13:11, 23.67it/s]

  0%|          | 31/18769 [00:01<13:15, 23.57it/s]

  0%|          | 34/18769 [00:01<13:18, 23.47it/s]

  0%|          | 37/18769 [00:01<13:19, 23.42it/s]

  0%|          | 40/18769 [00:01<13:19, 23.43it/s]

  0%|          | 43/18769 [00:01<13:21, 23.37it/s]

  0%|          | 46/18769 [00:01<13:20, 23.39it/s]

  0%|          | 49/18769 [00:02<13:19, 23.42it/s]

  0%|          | 52/18769 [00:02<13:19, 23.40it/s]

  0%|          | 55/18769 [00:02<13:18, 23.43it/s]

  0%|          | 58/18769 [00:02<13:11, 23.63it/s]

  0%|          | 61/18769 [00:02<13:06, 23.79it/s]

  0%|          | 64/18769 [00:02<13:08, 23.72it/s]

  0%|          | 67/18769 [00:02<13:12, 23.61it/s]

  0%|          | 70/18769 [00:02<13:07, 23.75it/s]

  0%|          | 73/18769 [00:03<13:03, 23.86it/s]

  0%|          | 76/18769 [00:03<13:00, 23.94it/s]

  0%|          | 79/18769 [00:03<12:59, 23.97it/s]

  0%|          | 82/18769 [00:03<12:58, 23.99it/s]

  0%|          | 85/18769 [00:03<12:59, 23.98it/s]

  0%|          | 88/18769 [00:03<12:57, 24.02it/s]

  0%|          | 91/18769 [00:03<13:04, 23.81it/s]

  1%|          | 94/18769 [00:03<13:01, 23.91it/s]

  1%|          | 97/18769 [00:04<12:59, 23.95it/s]

  1%|          | 100/18769 [00:04<12:58, 23.98it/s]

  1%|          | 103/18769 [00:04<12:56, 24.03it/s]

  1%|          | 106/18769 [00:04<12:56, 24.04it/s]

  1%|          | 109/18769 [00:04<12:56, 24.04it/s]

  1%|          | 112/18769 [00:04<12:55, 24.05it/s]

  1%|          | 115/18769 [00:04<12:55, 24.04it/s]

  1%|          | 118/18769 [00:04<12:55, 24.06it/s]

  1%|          | 121/18769 [00:05<12:54, 24.08it/s]

  1%|          | 124/18769 [00:05<12:54, 24.06it/s]

  1%|          | 127/18769 [00:05<12:54, 24.08it/s]

  1%|          | 130/18769 [00:05<12:53, 24.10it/s]

  1%|          | 133/18769 [00:05<12:53, 24.09it/s]

  1%|          | 136/18769 [00:05<12:52, 24.11it/s]

  1%|          | 140/18769 [00:05<12:00, 25.84it/s]

  1%|          | 143/18769 [00:05<12:22, 25.08it/s]

  1%|          | 146/18769 [00:06<12:39, 24.52it/s]

  1%|          | 149/18769 [00:06<12:48, 24.22it/s]

  1%|          | 152/18769 [00:06<12:57, 23.94it/s]

  1%|          | 155/18769 [00:06<13:03, 23.76it/s]

  1%|          | 158/18769 [00:06<13:05, 23.68it/s]

  1%|          | 161/18769 [00:06<13:07, 23.63it/s]

  1%|          | 164/18769 [00:06<13:08, 23.58it/s]

  1%|          | 167/18769 [00:06<13:08, 23.58it/s]

  1%|          | 170/18769 [00:07<13:09, 23.56it/s]

  1%|          | 173/18769 [00:07<13:10, 23.52it/s]

  1%|          | 176/18769 [00:07<13:11, 23.49it/s]

  1%|          | 179/18769 [00:07<13:12, 23.47it/s]

  1%|          | 182/18769 [00:07<13:12, 23.46it/s]

  1%|          | 185/18769 [00:07<13:15, 23.35it/s]

  1%|          | 188/18769 [00:07<13:13, 23.41it/s]

  1%|          | 191/18769 [00:07<13:12, 23.45it/s]

  1%|          | 194/18769 [00:08<13:04, 23.66it/s]

  1%|          | 197/18769 [00:08<12:58, 23.85it/s]

  1%|          | 200/18769 [00:08<12:55, 23.93it/s]

  1%|          | 203/18769 [00:08<12:52, 24.03it/s]

  1%|          | 206/18769 [00:08<12:50, 24.10it/s]

  1%|          | 209/18769 [00:08<12:48, 24.16it/s]

  1%|          | 212/18769 [00:08<12:47, 24.17it/s]

  1%|          | 215/18769 [00:08<12:46, 24.21it/s]

  1%|          | 218/18769 [00:09<12:46, 24.21it/s]

  1%|          | 221/18769 [00:09<12:47, 24.17it/s]

  1%|          | 224/18769 [00:09<12:46, 24.21it/s]

  1%|          | 227/18769 [00:09<12:45, 24.23it/s]

  1%|          | 230/18769 [00:09<12:44, 24.26it/s]

  1%|          | 233/18769 [00:09<12:44, 24.24it/s]

  1%|▏         | 236/18769 [00:09<12:45, 24.23it/s]

  1%|▏         | 239/18769 [00:09<12:44, 24.25it/s]

  1%|▏         | 242/18769 [00:10<12:43, 24.27it/s]

  1%|▏         | 245/18769 [00:10<12:45, 24.20it/s]

  1%|▏         | 248/18769 [00:10<12:45, 24.20it/s]

  1%|▏         | 251/18769 [00:10<12:46, 24.15it/s]

  1%|▏         | 254/18769 [00:10<12:46, 24.15it/s]

  1%|▏         | 257/18769 [00:10<12:45, 24.18it/s]

  1%|▏         | 260/18769 [00:10<12:47, 24.12it/s]

  1%|▏         | 263/18769 [00:10<12:47, 24.10it/s]

  1%|▏         | 266/18769 [00:11<12:46, 24.14it/s]

  1%|▏         | 269/18769 [00:11<12:46, 24.13it/s]

  1%|▏         | 272/18769 [00:11<12:47, 24.09it/s]

  1%|▏         | 275/18769 [00:11<12:50, 24.00it/s]

  1%|▏         | 279/18769 [00:11<11:57, 25.76it/s]

  2%|▏         | 282/18769 [00:11<12:21, 24.92it/s]

  2%|▏         | 285/18769 [00:11<12:35, 24.45it/s]

  2%|▏         | 288/18769 [00:11<12:45, 24.14it/s]

  2%|▏         | 291/18769 [00:12<12:52, 23.91it/s]

  2%|▏         | 294/18769 [00:12<12:57, 23.76it/s]

  2%|▏         | 297/18769 [00:12<13:01, 23.65it/s]

  2%|▏         | 300/18769 [00:12<13:03, 23.58it/s]

  2%|▏         | 303/18769 [00:12<13:04, 23.53it/s]

  2%|▏         | 306/18769 [00:12<13:10, 23.35it/s]

  2%|▏         | 309/18769 [00:12<13:11, 23.33it/s]

  2%|▏         | 312/18769 [00:13<13:10, 23.36it/s]

  2%|▏         | 315/18769 [00:13<13:10, 23.34it/s]

  2%|▏         | 318/18769 [00:13<13:10, 23.35it/s]

  2%|▏         | 321/18769 [00:13<13:10, 23.34it/s]

  2%|▏         | 324/18769 [00:13<13:09, 23.36it/s]

  2%|▏         | 327/18769 [00:13<13:09, 23.35it/s]

  2%|▏         | 330/18769 [00:13<13:05, 23.49it/s]

  2%|▏         | 333/18769 [00:13<12:58, 23.68it/s]

  2%|▏         | 336/18769 [00:14<12:54, 23.81it/s]

  2%|▏         | 339/18769 [00:14<12:51, 23.89it/s]

  2%|▏         | 342/18769 [00:14<12:49, 23.94it/s]

  2%|▏         | 345/18769 [00:14<12:48, 23.98it/s]

  2%|▏         | 348/18769 [00:14<12:46, 24.04it/s]

  2%|▏         | 351/18769 [00:14<12:44, 24.10it/s]

  2%|▏         | 354/18769 [00:14<12:42, 24.14it/s]

  2%|▏         | 357/18769 [00:14<12:42, 24.16it/s]

  2%|▏         | 360/18769 [00:15<12:41, 24.19it/s]

  2%|▏         | 363/18769 [00:15<12:41, 24.17it/s]

  2%|▏         | 366/18769 [00:15<12:41, 24.16it/s]

  2%|▏         | 369/18769 [00:15<12:40, 24.19it/s]

  2%|▏         | 372/18769 [00:15<12:40, 24.18it/s]

  2%|▏         | 375/18769 [00:15<12:41, 24.16it/s]

  2%|▏         | 378/18769 [00:15<12:40, 24.18it/s]

  2%|▏         | 381/18769 [00:15<12:45, 24.03it/s]

  2%|▏         | 384/18769 [00:16<12:44, 24.05it/s]

  2%|▏         | 387/18769 [00:16<12:46, 23.99it/s]

  2%|▏         | 390/18769 [00:16<12:44, 24.05it/s]

  2%|▏         | 393/18769 [00:16<12:42, 24.09it/s]

  2%|▏         | 396/18769 [00:16<12:42, 24.08it/s]

  2%|▏         | 399/18769 [00:16<12:42, 24.10it/s]

  2%|▏         | 402/18769 [00:16<12:41, 24.12it/s]

  2%|▏         | 405/18769 [00:16<12:44, 24.03it/s]

  2%|▏         | 408/18769 [00:17<12:43, 24.06it/s]

  2%|▏         | 411/18769 [00:17<12:41, 24.12it/s]

  2%|▏         | 414/18769 [00:17<12:48, 23.88it/s]

  2%|▏         | 418/18769 [00:17<11:54, 25.70it/s]

  2%|▏         | 421/18769 [00:17<12:15, 24.94it/s]

  2%|▏         | 424/18769 [00:17<12:28, 24.52it/s]

  2%|▏         | 427/18769 [00:17<12:37, 24.20it/s]

  2%|▏         | 430/18769 [00:17<12:45, 23.95it/s]

  2%|▏         | 433/18769 [00:18<12:50, 23.78it/s]

  2%|▏         | 436/18769 [00:18<12:56, 23.62it/s]

  2%|▏         | 439/18769 [00:18<12:58, 23.56it/s]

  2%|▏         | 442/18769 [00:18<12:58, 23.53it/s]

  2%|▏         | 445/18769 [00:18<13:00, 23.47it/s]

  2%|▏         | 448/18769 [00:18<13:00, 23.48it/s]

  2%|▏         | 451/18769 [00:18<13:02, 23.42it/s]

  2%|▏         | 454/18769 [00:18<13:02, 23.40it/s]

  2%|▏         | 457/18769 [00:19<13:01, 23.44it/s]

  2%|▏         | 460/18769 [00:19<13:02, 23.40it/s]

  2%|▏         | 463/18769 [00:19<13:04, 23.33it/s]

  2%|▏         | 466/18769 [00:19<13:05, 23.31it/s]

  2%|▏         | 469/18769 [00:19<12:57, 23.54it/s]

  3%|▎         | 472/18769 [00:19<12:52, 23.68it/s]

  3%|▎         | 475/18769 [00:19<12:52, 23.69it/s]

  3%|▎         | 478/18769 [00:19<12:48, 23.80it/s]

  3%|▎         | 481/18769 [00:20<12:46, 23.86it/s]

  3%|▎         | 484/18769 [00:20<12:45, 23.88it/s]

  3%|▎         | 487/18769 [00:20<12:41, 24.02it/s]

  3%|▎         | 490/18769 [00:20<12:41, 24.02it/s]

  3%|▎         | 493/18769 [00:20<12:38, 24.10it/s]

  3%|▎         | 496/18769 [00:20<12:36, 24.15it/s]

  3%|▎         | 499/18769 [00:20<12:36, 24.16it/s]

  3%|▎         | 502/18769 [00:20<12:35, 24.18it/s]

  3%|▎         | 505/18769 [00:21<12:38, 24.08it/s]

  3%|▎         | 508/18769 [00:21<12:38, 24.09it/s]

  3%|▎         | 511/18769 [00:21<12:36, 24.13it/s]

  3%|▎         | 514/18769 [00:21<12:34, 24.19it/s]

  3%|▎         | 517/18769 [00:21<12:34, 24.21it/s]

  3%|▎         | 520/18769 [00:21<12:33, 24.21it/s]

  3%|▎         | 523/18769 [00:21<12:37, 24.08it/s]

  3%|▎         | 526/18769 [00:21<12:36, 24.10it/s]

  3%|▎         | 529/18769 [00:22<12:35, 24.16it/s]

  3%|▎         | 532/18769 [00:22<12:34, 24.18it/s]

  3%|▎         | 535/18769 [00:22<12:32, 24.22it/s]

  3%|▎         | 538/18769 [00:22<12:33, 24.21it/s]

  3%|▎         | 541/18769 [00:22<12:32, 24.21it/s]

  3%|▎         | 544/18769 [00:22<12:36, 24.09it/s]

  3%|▎         | 547/18769 [00:22<12:33, 24.17it/s]

  3%|▎         | 550/18769 [00:22<12:38, 24.02it/s]

  3%|▎         | 554/18769 [00:23<11:45, 25.84it/s]

  3%|▎         | 557/18769 [00:23<12:06, 25.06it/s]

  3%|▎         | 560/18769 [00:23<12:21, 24.55it/s]

  3%|▎         | 563/18769 [00:23<12:33, 24.17it/s]

  3%|▎         | 566/18769 [00:23<12:39, 23.96it/s]

  3%|▎         | 569/18769 [00:23<12:44, 23.80it/s]

  3%|▎         | 572/18769 [00:23<12:49, 23.65it/s]

  3%|▎         | 575/18769 [00:23<12:52, 23.55it/s]

  3%|▎         | 578/18769 [00:24<12:52, 23.55it/s]

  3%|▎         | 581/18769 [00:24<12:54, 23.49it/s]

  3%|▎         | 584/18769 [00:24<12:53, 23.51it/s]

  3%|▎         | 587/18769 [00:24<12:54, 23.48it/s]

  3%|▎         | 590/18769 [00:24<12:54, 23.48it/s]

  3%|▎         | 593/18769 [00:24<12:53, 23.51it/s]

  3%|▎         | 596/18769 [00:24<12:56, 23.40it/s]

  3%|▎         | 599/18769 [00:24<12:55, 23.42it/s]

  3%|▎         | 602/18769 [00:25<12:56, 23.38it/s]

  3%|▎         | 605/18769 [00:25<12:48, 23.64it/s]

  3%|▎         | 608/18769 [00:25<12:43, 23.80it/s]

  3%|▎         | 611/18769 [00:25<12:39, 23.89it/s]

  3%|▎         | 614/18769 [00:25<12:36, 24.00it/s]

  3%|▎         | 617/18769 [00:25<12:33, 24.10it/s]

  3%|▎         | 620/18769 [00:25<12:32, 24.13it/s]

  3%|▎         | 623/18769 [00:25<12:31, 24.14it/s]

  3%|▎         | 626/18769 [00:26<12:32, 24.12it/s]

  3%|▎         | 629/18769 [00:26<12:31, 24.13it/s]

  3%|▎         | 632/18769 [00:26<12:31, 24.14it/s]

  3%|▎         | 635/18769 [00:26<12:29, 24.19it/s]

  3%|▎         | 638/18769 [00:26<12:29, 24.18it/s]

  3%|▎         | 641/18769 [00:26<12:29, 24.19it/s]

  3%|▎         | 644/18769 [00:26<12:32, 24.09it/s]

  3%|▎         | 647/18769 [00:26<12:30, 24.13it/s]

  3%|▎         | 650/18769 [00:27<12:29, 24.17it/s]

  3%|▎         | 653/18769 [00:27<12:28, 24.22it/s]

  3%|▎         | 656/18769 [00:27<12:29, 24.17it/s]

  4%|▎         | 659/18769 [00:27<12:31, 24.10it/s]

  4%|▎         | 662/18769 [00:27<12:30, 24.14it/s]

  4%|▎         | 665/18769 [00:27<12:30, 24.13it/s]

  4%|▎         | 668/18769 [00:27<12:32, 24.04it/s]

  4%|▎         | 671/18769 [00:27<12:32, 24.06it/s]

  4%|▎         | 674/18769 [00:28<12:30, 24.10it/s]

  4%|▎         | 677/18769 [00:28<12:30, 24.10it/s]

  4%|▎         | 680/18769 [00:28<12:30, 24.12it/s]

  4%|▎         | 683/18769 [00:28<12:30, 24.10it/s]

  4%|▎         | 686/18769 [00:28<12:32, 24.03it/s]

  4%|▎         | 689/18769 [00:28<12:37, 23.85it/s]

  4%|▎         | 693/18769 [00:28<11:46, 25.60it/s]

  4%|▎         | 696/18769 [00:28<12:05, 24.91it/s]

  4%|▎         | 699/18769 [00:29<12:19, 24.45it/s]

  4%|▎         | 702/18769 [00:29<12:27, 24.16it/s]

  4%|▍         | 705/18769 [00:29<12:34, 23.94it/s]

  4%|▍         | 708/18769 [00:29<12:38, 23.82it/s]

  4%|▍         | 711/18769 [00:29<12:41, 23.72it/s]

  4%|▍         | 714/18769 [00:29<12:43, 23.65it/s]

  4%|▍         | 717/18769 [00:29<12:46, 23.56it/s]

  4%|▍         | 720/18769 [00:29<12:46, 23.54it/s]

  4%|▍         | 723/18769 [00:30<12:46, 23.55it/s]

  4%|▍         | 726/18769 [00:30<12:48, 23.49it/s]

  4%|▍         | 729/18769 [00:30<12:48, 23.48it/s]

  4%|▍         | 732/18769 [00:30<12:49, 23.45it/s]

  4%|▍         | 735/18769 [00:30<12:48, 23.47it/s]

  4%|▍         | 738/18769 [00:30<12:49, 23.43it/s]

  4%|▍         | 741/18769 [00:30<12:48, 23.46it/s]

  4%|▍         | 744/18769 [00:31<12:40, 23.70it/s]

  4%|▍         | 747/18769 [00:31<12:34, 23.88it/s]

  4%|▍         | 750/18769 [00:31<12:30, 24.00it/s]

  4%|▍         | 753/18769 [00:31<12:28, 24.07it/s]

  4%|▍         | 756/18769 [00:31<12:27, 24.11it/s]

  4%|▍         | 759/18769 [00:31<12:24, 24.18it/s]

  4%|▍         | 762/18769 [00:31<12:24, 24.19it/s]

  4%|▍         | 765/18769 [00:31<12:24, 24.19it/s]

  4%|▍         | 768/18769 [00:32<12:23, 24.20it/s]

  4%|▍         | 771/18769 [00:32<12:23, 24.22it/s]

  4%|▍         | 774/18769 [00:32<12:23, 24.19it/s]

  4%|▍         | 777/18769 [00:32<12:24, 24.18it/s]

  4%|▍         | 780/18769 [00:32<12:23, 24.18it/s]

  4%|▍         | 783/18769 [00:32<12:24, 24.17it/s]

  4%|▍         | 786/18769 [00:32<12:28, 24.03it/s]

  4%|▍         | 789/18769 [00:32<12:26, 24.09it/s]

  4%|▍         | 792/18769 [00:32<12:26, 24.08it/s]

  4%|▍         | 795/18769 [00:33<12:25, 24.10it/s]

  4%|▍         | 798/18769 [00:33<12:24, 24.13it/s]

  4%|▍         | 801/18769 [00:33<12:24, 24.15it/s]

  4%|▍         | 804/18769 [00:33<12:23, 24.15it/s]

  4%|▍         | 807/18769 [00:33<12:24, 24.12it/s]

  4%|▍         | 810/18769 [00:33<12:23, 24.15it/s]

  4%|▍         | 813/18769 [00:33<12:23, 24.14it/s]

  4%|▍         | 816/18769 [00:33<12:24, 24.11it/s]

  4%|▍         | 819/18769 [00:34<12:23, 24.15it/s]

  4%|▍         | 822/18769 [00:34<12:21, 24.19it/s]

  4%|▍         | 825/18769 [00:34<12:31, 23.88it/s]

  4%|▍         | 828/18769 [00:34<12:35, 23.73it/s]

  4%|▍         | 832/18769 [00:34<11:41, 25.59it/s]

  4%|▍         | 835/18769 [00:34<12:01, 24.87it/s]

  4%|▍         | 838/18769 [00:34<12:16, 24.36it/s]

  4%|▍         | 841/18769 [00:35<12:24, 24.08it/s]

  4%|▍         | 844/18769 [00:35<12:31, 23.85it/s]

  5%|▍         | 847/18769 [00:35<12:35, 23.71it/s]

  5%|▍         | 850/18769 [00:35<12:38, 23.62it/s]

  5%|▍         | 853/18769 [00:35<12:40, 23.56it/s]

  5%|▍         | 856/18769 [00:35<12:40, 23.55it/s]

  5%|▍         | 859/18769 [00:35<12:42, 23.50it/s]

  5%|▍         | 862/18769 [00:35<12:47, 23.34it/s]

  5%|▍         | 865/18769 [00:36<12:46, 23.36it/s]

  5%|▍         | 868/18769 [00:36<12:46, 23.36it/s]

  5%|▍         | 871/18769 [00:36<12:45, 23.37it/s]

  5%|▍         | 874/18769 [00:36<12:45, 23.39it/s]

  5%|▍         | 877/18769 [00:36<12:42, 23.46it/s]

  5%|▍         | 880/18769 [00:36<12:36, 23.65it/s]

  5%|▍         | 883/18769 [00:36<12:32, 23.77it/s]

  5%|▍         | 886/18769 [00:36<12:29, 23.87it/s]

  5%|▍         | 889/18769 [00:37<12:26, 23.96it/s]

  5%|▍         | 892/18769 [00:37<12:23, 24.05it/s]

  5%|▍         | 895/18769 [00:37<12:21, 24.09it/s]

  5%|▍         | 898/18769 [00:37<12:21, 24.12it/s]

  5%|▍         | 901/18769 [00:37<12:21, 24.11it/s]

  5%|▍         | 904/18769 [00:37<12:21, 24.11it/s]

  5%|▍         | 907/18769 [00:37<12:20, 24.12it/s]

  5%|▍         | 910/18769 [00:37<12:25, 23.95it/s]

  5%|▍         | 913/18769 [00:38<12:24, 23.98it/s]

  5%|▍         | 916/18769 [00:38<12:23, 24.01it/s]

  5%|▍         | 919/18769 [00:38<12:23, 24.01it/s]

  5%|▍         | 922/18769 [00:38<12:22, 24.02it/s]

  5%|▍         | 925/18769 [00:38<12:21, 24.07it/s]

  5%|▍         | 928/18769 [00:38<12:20, 24.08it/s]

  5%|▍         | 931/18769 [00:38<12:20, 24.08it/s]

  5%|▍         | 934/18769 [00:38<12:22, 24.02it/s]

  5%|▍         | 937/18769 [00:39<12:20, 24.07it/s]

  5%|▌         | 940/18769 [00:39<12:20, 24.09it/s]

  5%|▌         | 943/18769 [00:39<12:21, 24.05it/s]

  5%|▌         | 946/18769 [00:39<12:20, 24.06it/s]

  5%|▌         | 949/18769 [00:39<12:20, 24.06it/s]

  5%|▌         | 952/18769 [00:39<12:21, 24.04it/s]

  5%|▌         | 955/18769 [00:39<12:19, 24.09it/s]

  5%|▌         | 958/18769 [00:39<12:22, 23.98it/s]

  5%|▌         | 961/18769 [00:40<12:27, 23.83it/s]

  5%|▌         | 964/18769 [00:40<12:33, 23.62it/s]

  5%|▌         | 968/18769 [00:40<11:38, 25.48it/s]

  5%|▌         | 971/18769 [00:40<11:57, 24.82it/s]

  5%|▌         | 974/18769 [00:40<12:09, 24.41it/s]

  5%|▌         | 977/18769 [00:40<12:18, 24.08it/s]

  5%|▌         | 980/18769 [00:40<12:25, 23.86it/s]

  5%|▌         | 983/18769 [00:40<12:30, 23.71it/s]

  5%|▌         | 986/18769 [00:41<12:34, 23.58it/s]

  5%|▌         | 989/18769 [00:41<12:35, 23.52it/s]

  5%|▌         | 992/18769 [00:41<12:38, 23.44it/s]

  5%|▌         | 995/18769 [00:41<12:37, 23.46it/s]

  5%|▌         | 998/18769 [00:41<12:37, 23.47it/s]

  5%|▌         | 1001/18769 [00:41<12:37, 23.45it/s]

  5%|▌         | 1004/18769 [00:41<12:36, 23.47it/s]

  5%|▌         | 1007/18769 [00:41<12:35, 23.50it/s]

  5%|▌         | 1010/18769 [00:42<12:35, 23.51it/s]

  5%|▌         | 1013/18769 [00:42<12:36, 23.48it/s]

  5%|▌         | 1016/18769 [00:42<12:28, 23.72it/s]

  5%|▌         | 1019/18769 [00:42<12:24, 23.85it/s]

  5%|▌         | 1022/18769 [00:42<12:20, 23.97it/s]

  5%|▌         | 1025/18769 [00:42<12:20, 23.96it/s]

  5%|▌         | 1028/18769 [00:42<12:20, 23.97it/s]

  5%|▌         | 1031/18769 [00:42<12:19, 23.98it/s]

  6%|▌         | 1034/18769 [00:43<12:18, 24.02it/s]

  6%|▌         | 1037/18769 [00:43<12:42, 23.26it/s]

  6%|▌         | 1040/18769 [00:43<12:34, 23.49it/s]

  6%|▌         | 1043/18769 [00:43<12:28, 23.68it/s]

  6%|▌         | 1046/18769 [00:43<12:24, 23.81it/s]

  6%|▌         | 1049/18769 [00:43<12:20, 23.92it/s]

  6%|▌         | 1052/18769 [00:43<12:17, 24.01it/s]

  6%|▌         | 1055/18769 [00:43<12:16, 24.06it/s]

  6%|▌         | 1058/18769 [00:44<12:14, 24.11it/s]

  6%|▌         | 1061/18769 [00:44<12:14, 24.11it/s]

  6%|▌         | 1064/18769 [00:44<12:14, 24.11it/s]

  6%|▌         | 1067/18769 [00:44<12:15, 24.07it/s]

  6%|▌         | 1070/18769 [00:44<12:13, 24.13it/s]

  6%|▌         | 1073/18769 [00:44<12:11, 24.18it/s]

  6%|▌         | 1076/18769 [00:44<12:10, 24.23it/s]

  6%|▌         | 1079/18769 [00:44<12:09, 24.25it/s]

  6%|▌         | 1082/18769 [00:45<12:09, 24.23it/s]

  6%|▌         | 1085/18769 [00:45<12:08, 24.26it/s]

  6%|▌         | 1088/18769 [00:45<12:09, 24.23it/s]

  6%|▌         | 1091/18769 [00:45<12:10, 24.20it/s]

  6%|▌         | 1094/18769 [00:45<12:10, 24.19it/s]

  6%|▌         | 1097/18769 [00:45<12:12, 24.13it/s]

  6%|▌         | 1100/18769 [00:45<12:17, 23.94it/s]

  6%|▌         | 1103/18769 [00:45<12:22, 23.79it/s]

  6%|▌         | 1107/18769 [00:46<11:29, 25.62it/s]

  6%|▌         | 1110/18769 [00:46<11:50, 24.84it/s]

  6%|▌         | 1113/18769 [00:46<12:05, 24.35it/s]

  6%|▌         | 1116/18769 [00:46<12:13, 24.07it/s]

  6%|▌         | 1119/18769 [00:46<12:20, 23.82it/s]

  6%|▌         | 1122/18769 [00:46<12:23, 23.73it/s]

  6%|▌         | 1125/18769 [00:46<12:27, 23.62it/s]

  6%|▌         | 1128/18769 [00:47<12:31, 23.48it/s]

  6%|▌         | 1131/18769 [00:47<12:34, 23.37it/s]

  6%|▌         | 1134/18769 [00:47<12:36, 23.32it/s]

  6%|▌         | 1137/18769 [00:47<12:37, 23.29it/s]

  6%|▌         | 1140/18769 [00:47<12:36, 23.31it/s]

  6%|▌         | 1143/18769 [00:47<12:35, 23.34it/s]

  6%|▌         | 1146/18769 [00:47<12:34, 23.36it/s]

  6%|▌         | 1149/18769 [00:47<12:33, 23.39it/s]

  6%|▌         | 1152/18769 [00:48<12:26, 23.59it/s]

  6%|▌         | 1155/18769 [00:48<12:21, 23.76it/s]

  6%|▌         | 1158/18769 [00:48<12:17, 23.87it/s]

  6%|▌         | 1161/18769 [00:48<12:14, 23.96it/s]

  6%|▌         | 1164/18769 [00:48<12:11, 24.05it/s]

  6%|▌         | 1167/18769 [00:48<12:10, 24.11it/s]

  6%|▌         | 1170/18769 [00:48<12:09, 24.14it/s]

  6%|▌         | 1173/18769 [00:48<12:08, 24.16it/s]

  6%|▋         | 1176/18769 [00:49<12:09, 24.12it/s]

  6%|▋         | 1179/18769 [00:49<12:10, 24.08it/s]

  6%|▋         | 1182/18769 [00:49<12:09, 24.10it/s]

  6%|▋         | 1185/18769 [00:49<12:11, 24.05it/s]

  6%|▋         | 1188/18769 [00:49<12:10, 24.07it/s]

  6%|▋         | 1191/18769 [00:49<12:11, 24.04it/s]

  6%|▋         | 1194/18769 [00:49<12:11, 24.03it/s]

  6%|▋         | 1197/18769 [00:49<12:08, 24.12it/s]

  6%|▋         | 1200/18769 [00:50<12:07, 24.15it/s]

  6%|▋         | 1203/18769 [00:50<12:07, 24.16it/s]

  6%|▋         | 1206/18769 [00:50<12:08, 24.11it/s]

  6%|▋         | 1209/18769 [00:50<12:09, 24.09it/s]

  6%|▋         | 1212/18769 [00:50<12:08, 24.10it/s]

  6%|▋         | 1215/18769 [00:50<12:09, 24.08it/s]

  6%|▋         | 1218/18769 [00:50<12:08, 24.09it/s]

  7%|▋         | 1221/18769 [00:50<12:07, 24.11it/s]

  7%|▋         | 1224/18769 [00:51<12:09, 24.06it/s]

  7%|▋         | 1227/18769 [00:51<12:10, 24.00it/s]

  7%|▋         | 1230/18769 [00:51<12:09, 24.03it/s]

  7%|▋         | 1233/18769 [00:51<12:09, 24.03it/s]

  7%|▋         | 1236/18769 [00:51<12:17, 23.77it/s]

  7%|▋         | 1239/18769 [00:51<12:22, 23.62it/s]

  7%|▋         | 1242/18769 [00:51<12:25, 23.52it/s]

  7%|▋         | 1246/18769 [00:51<11:30, 25.38it/s]

  7%|▋         | 1249/18769 [00:52<11:47, 24.75it/s]

  7%|▋         | 1252/18769 [00:52<12:01, 24.26it/s]

  7%|▋         | 1255/18769 [00:52<12:11, 23.93it/s]

  7%|▋         | 1258/18769 [00:52<12:17, 23.74it/s]

  7%|▋         | 1261/18769 [00:52<12:21, 23.61it/s]

  7%|▋         | 1264/18769 [00:52<12:24, 23.53it/s]

  7%|▋         | 1267/18769 [00:52<12:25, 23.49it/s]

  7%|▋         | 1270/18769 [00:52<12:25, 23.47it/s]

  7%|▋         | 1273/18769 [00:53<12:25, 23.47it/s]

  7%|▋         | 1276/18769 [00:53<12:27, 23.39it/s]

  7%|▋         | 1279/18769 [00:53<12:29, 23.35it/s]

  7%|▋         | 1282/18769 [00:53<12:30, 23.29it/s]

  7%|▋         | 1285/18769 [00:53<12:30, 23.29it/s]

  7%|▋         | 1288/18769 [00:53<12:29, 23.32it/s]

  7%|▋         | 1291/18769 [00:53<12:22, 23.53it/s]

  7%|▋         | 1294/18769 [00:53<12:18, 23.66it/s]

  7%|▋         | 1297/18769 [00:54<12:15, 23.75it/s]

  7%|▋         | 1300/18769 [00:54<12:13, 23.82it/s]

  7%|▋         | 1303/18769 [00:54<12:11, 23.87it/s]

  7%|▋         | 1306/18769 [00:54<12:10, 23.90it/s]

  7%|▋         | 1309/18769 [00:54<12:09, 23.94it/s]

  7%|▋         | 1312/18769 [00:54<12:09, 23.92it/s]

  7%|▋         | 1315/18769 [00:54<12:08, 23.96it/s]

  7%|▋         | 1318/18769 [00:54<12:07, 23.98it/s]

  7%|▋         | 1321/18769 [00:55<12:08, 23.95it/s]

  7%|▋         | 1324/18769 [00:55<12:08, 23.95it/s]

  7%|▋         | 1327/18769 [00:55<12:08, 23.93it/s]

  7%|▋         | 1330/18769 [00:55<12:08, 23.95it/s]

  7%|▋         | 1333/18769 [00:55<12:08, 23.93it/s]

  7%|▋         | 1336/18769 [00:55<12:07, 23.97it/s]

  7%|▋         | 1339/18769 [00:55<12:06, 23.98it/s]

  7%|▋         | 1342/18769 [00:55<12:06, 23.99it/s]

  7%|▋         | 1345/18769 [00:56<12:10, 23.86it/s]

  7%|▋         | 1348/18769 [00:56<12:10, 23.86it/s]

  7%|▋         | 1351/18769 [00:56<12:08, 23.90it/s]

  7%|▋         | 1354/18769 [00:56<12:07, 23.95it/s]

  7%|▋         | 1357/18769 [00:56<12:06, 23.98it/s]

  7%|▋         | 1360/18769 [00:56<12:05, 23.98it/s]

  7%|▋         | 1363/18769 [00:56<12:04, 24.02it/s]

  7%|▋         | 1366/18769 [00:56<12:04, 24.01it/s]

  7%|▋         | 1369/18769 [00:57<12:05, 24.00it/s]

  7%|▋         | 1372/18769 [00:57<12:10, 23.83it/s]

  7%|▋         | 1375/18769 [00:57<12:13, 23.70it/s]

  7%|▋         | 1378/18769 [00:57<12:19, 23.52it/s]

  7%|▋         | 1382/18769 [00:57<11:25, 25.38it/s]

  7%|▋         | 1385/18769 [00:57<11:42, 24.75it/s]

  7%|▋         | 1388/18769 [00:57<11:54, 24.32it/s]

  7%|▋         | 1391/18769 [00:57<12:04, 23.99it/s]

  7%|▋         | 1394/18769 [00:58<12:14, 23.65it/s]

  7%|▋         | 1397/18769 [00:58<12:18, 23.54it/s]

  7%|▋         | 1400/18769 [00:58<12:20, 23.47it/s]

  7%|▋         | 1403/18769 [00:58<12:22, 23.38it/s]

  7%|▋         | 1406/18769 [00:58<12:23, 23.36it/s]

  8%|▊         | 1409/18769 [00:58<12:23, 23.36it/s]

  8%|▊         | 1412/18769 [00:58<12:23, 23.35it/s]

  8%|▊         | 1415/18769 [00:59<12:22, 23.39it/s]

  8%|▊         | 1418/18769 [00:59<12:22, 23.36it/s]

  8%|▊         | 1421/18769 [00:59<12:23, 23.35it/s]

  8%|▊         | 1424/18769 [00:59<12:26, 23.24it/s]

  8%|▊         | 1427/18769 [00:59<12:19, 23.46it/s]

  8%|▊         | 1430/18769 [00:59<12:13, 23.64it/s]

  8%|▊         | 1433/18769 [00:59<12:10, 23.75it/s]

  8%|▊         | 1436/18769 [00:59<12:06, 23.87it/s]

  8%|▊         | 1439/18769 [01:00<12:05, 23.90it/s]

  8%|▊         | 1442/18769 [01:00<12:04, 23.90it/s]

  8%|▊         | 1445/18769 [01:00<12:13, 23.63it/s]

  8%|▊         | 1448/18769 [01:00<12:08, 23.78it/s]

  8%|▊         | 1451/18769 [01:00<12:04, 23.91it/s]

  8%|▊         | 1454/18769 [01:00<12:01, 23.99it/s]

  8%|▊         | 1457/18769 [01:00<11:58, 24.09it/s]

  8%|▊         | 1460/18769 [01:00<11:59, 24.05it/s]

  8%|▊         | 1463/18769 [01:01<11:59, 24.07it/s]

  8%|▊         | 1466/18769 [01:01<11:59, 24.06it/s]

  8%|▊         | 1469/18769 [01:01<11:57, 24.11it/s]

  8%|▊         | 1472/18769 [01:01<11:56, 24.14it/s]

  8%|▊         | 1475/18769 [01:01<11:56, 24.13it/s]

  8%|▊         | 1478/18769 [01:01<11:57, 24.09it/s]

  8%|▊         | 1481/18769 [01:01<11:57, 24.08it/s]

  8%|▊         | 1484/18769 [01:01<11:57, 24.10it/s]

  8%|▊         | 1487/18769 [01:02<11:59, 24.03it/s]

  8%|▊         | 1490/18769 [01:02<11:58, 24.06it/s]

  8%|▊         | 1493/18769 [01:02<11:56, 24.11it/s]

  8%|▊         | 1496/18769 [01:02<11:56, 24.12it/s]

  8%|▊         | 1499/18769 [01:02<11:55, 24.14it/s]

  8%|▊         | 1502/18769 [01:02<11:56, 24.11it/s]

  8%|▊         | 1505/18769 [01:02<11:56, 24.10it/s]

  8%|▊         | 1508/18769 [01:02<11:58, 24.03it/s]

  8%|▊         | 1511/18769 [01:03<12:03, 23.85it/s]

  8%|▊         | 1514/18769 [01:03<12:08, 23.69it/s]

  8%|▊         | 1517/18769 [01:03<12:12, 23.57it/s]

  8%|▊         | 1521/18769 [01:03<11:18, 25.40it/s]

  8%|▊         | 1524/18769 [01:03<11:42, 24.55it/s]

  8%|▊         | 1527/18769 [01:03<12:08, 23.67it/s]

  8%|▊         | 1530/18769 [01:03<12:10, 23.60it/s]

  8%|▊         | 1533/18769 [01:03<12:11, 23.58it/s]

  8%|▊         | 1536/18769 [01:04<12:12, 23.51it/s]

  8%|▊         | 1539/18769 [01:04<12:18, 23.33it/s]

  8%|▊         | 1542/18769 [01:04<12:17, 23.37it/s]

  8%|▊         | 1545/18769 [01:04<12:15, 23.42it/s]

  8%|▊         | 1548/18769 [01:04<12:16, 23.40it/s]

  8%|▊         | 1551/18769 [01:04<12:15, 23.40it/s]

  8%|▊         | 1554/18769 [01:04<12:15, 23.41it/s]

  8%|▊         | 1557/18769 [01:04<12:15, 23.41it/s]

  8%|▊         | 1560/18769 [01:05<12:15, 23.38it/s]

  8%|▊         | 1563/18769 [01:05<12:11, 23.53it/s]

  8%|▊         | 1566/18769 [01:05<12:04, 23.73it/s]

  8%|▊         | 1569/18769 [01:05<11:58, 23.94it/s]

  8%|▊         | 1572/18769 [01:05<11:55, 24.03it/s]

  8%|▊         | 1575/18769 [01:05<11:54, 24.06it/s]

  8%|▊         | 1578/18769 [01:05<11:53, 24.09it/s]

  8%|▊         | 1581/18769 [01:05<11:52, 24.12it/s]

  8%|▊         | 1584/18769 [01:06<11:56, 23.99it/s]

  8%|▊         | 1587/18769 [01:06<11:54, 24.05it/s]

  8%|▊         | 1590/18769 [01:06<11:53, 24.07it/s]

  8%|▊         | 1593/18769 [01:06<11:52, 24.10it/s]

  9%|▊         | 1596/18769 [01:06<11:52, 24.11it/s]

  9%|▊         | 1599/18769 [01:06<11:51, 24.13it/s]

  9%|▊         | 1602/18769 [01:06<11:49, 24.19it/s]

  9%|▊         | 1605/18769 [01:06<11:48, 24.22it/s]

  9%|▊         | 1608/18769 [01:07<11:49, 24.19it/s]

  9%|▊         | 1611/18769 [01:07<11:49, 24.20it/s]

  9%|▊         | 1614/18769 [01:07<11:52, 24.08it/s]

  9%|▊         | 1617/18769 [01:07<11:53, 24.03it/s]

  9%|▊         | 1620/18769 [01:07<11:51, 24.11it/s]

  9%|▊         | 1623/18769 [01:07<11:49, 24.16it/s]

  9%|▊         | 1626/18769 [01:07<11:48, 24.18it/s]

  9%|▊         | 1629/18769 [01:07<11:47, 24.21it/s]

  9%|▊         | 1632/18769 [01:08<11:51, 24.09it/s]

  9%|▊         | 1635/18769 [01:08<11:50, 24.10it/s]

  9%|▊         | 1638/18769 [01:08<11:50, 24.11it/s]

  9%|▊         | 1641/18769 [01:08<11:50, 24.10it/s]

  9%|▉         | 1644/18769 [01:08<11:50, 24.10it/s]

  9%|▉         | 1647/18769 [01:08<11:57, 23.87it/s]

  9%|▉         | 1650/18769 [01:08<12:00, 23.76it/s]

  9%|▉         | 1653/18769 [01:08<12:04, 23.64it/s]

  9%|▉         | 1656/18769 [01:09<12:06, 23.57it/s]

  9%|▉         | 1660/18769 [01:09<11:16, 25.30it/s]

  9%|▉         | 1663/18769 [01:09<11:37, 24.53it/s]

  9%|▉         | 1666/18769 [01:09<11:46, 24.22it/s]

  9%|▉         | 1669/18769 [01:09<11:52, 23.99it/s]

  9%|▉         | 1672/18769 [01:09<11:57, 23.84it/s]

  9%|▉         | 1675/18769 [01:09<12:00, 23.71it/s]

  9%|▉         | 1678/18769 [01:09<12:05, 23.56it/s]

  9%|▉         | 1681/18769 [01:10<12:07, 23.50it/s]

  9%|▉         | 1684/18769 [01:10<12:08, 23.46it/s]

  9%|▉         | 1687/18769 [01:10<12:07, 23.49it/s]

  9%|▉         | 1690/18769 [01:10<12:06, 23.50it/s]

  9%|▉         | 1693/18769 [01:10<12:06, 23.50it/s]

  9%|▉         | 1696/18769 [01:10<12:07, 23.47it/s]

  9%|▉         | 1699/18769 [01:10<12:04, 23.56it/s]

  9%|▉         | 1702/18769 [01:11<11:58, 23.74it/s]

  9%|▉         | 1705/18769 [01:11<11:59, 23.71it/s]

  9%|▉         | 1708/18769 [01:11<11:55, 23.86it/s]

  9%|▉         | 1711/18769 [01:11<11:51, 23.96it/s]

  9%|▉         | 1714/18769 [01:11<11:48, 24.07it/s]

  9%|▉         | 1717/18769 [01:11<11:45, 24.16it/s]

  9%|▉         | 1720/18769 [01:11<11:43, 24.22it/s]

  9%|▉         | 1723/18769 [01:11<11:43, 24.24it/s]

  9%|▉         | 1726/18769 [01:11<11:44, 24.19it/s]

  9%|▉         | 1729/18769 [01:12<11:49, 24.03it/s]

  9%|▉         | 1732/18769 [01:12<11:46, 24.10it/s]

  9%|▉         | 1735/18769 [01:12<11:46, 24.10it/s]

  9%|▉         | 1738/18769 [01:12<11:46, 24.11it/s]

  9%|▉         | 1741/18769 [01:12<11:45, 24.15it/s]

  9%|▉         | 1744/18769 [01:12<11:43, 24.22it/s]

  9%|▉         | 1747/18769 [01:12<11:43, 24.21it/s]

  9%|▉         | 1750/18769 [01:12<11:43, 24.19it/s]

  9%|▉         | 1753/18769 [01:13<11:44, 24.16it/s]

  9%|▉         | 1756/18769 [01:13<11:44, 24.16it/s]

  9%|▉         | 1759/18769 [01:13<11:42, 24.20it/s]

  9%|▉         | 1762/18769 [01:13<11:42, 24.22it/s]

  9%|▉         | 1765/18769 [01:13<11:43, 24.18it/s]

  9%|▉         | 1768/18769 [01:13<11:42, 24.19it/s]

  9%|▉         | 1771/18769 [01:13<11:42, 24.19it/s]

  9%|▉         | 1774/18769 [01:13<11:42, 24.20it/s]

  9%|▉         | 1777/18769 [01:14<11:46, 24.06it/s]

  9%|▉         | 1780/18769 [01:14<11:45, 24.09it/s]

  9%|▉         | 1783/18769 [01:14<11:48, 23.96it/s]

 10%|▉         | 1786/18769 [01:14<11:52, 23.85it/s]

 10%|▉         | 1789/18769 [01:14<11:55, 23.73it/s]

 10%|▉         | 1792/18769 [01:14<11:56, 23.70it/s]

 10%|▉         | 1796/18769 [01:14<11:03, 25.57it/s]

 10%|▉         | 1799/18769 [01:14<11:21, 24.92it/s]

 10%|▉         | 1802/18769 [01:15<11:33, 24.46it/s]

 10%|▉         | 1805/18769 [01:15<11:41, 24.18it/s]

 10%|▉         | 1808/18769 [01:15<11:47, 23.96it/s]

 10%|▉         | 1811/18769 [01:15<11:51, 23.82it/s]

 10%|▉         | 1814/18769 [01:15<11:54, 23.72it/s]

 10%|▉         | 1817/18769 [01:15<11:56, 23.66it/s]

 10%|▉         | 1820/18769 [01:15<11:57, 23.63it/s]

 10%|▉         | 1823/18769 [01:16<12:01, 23.50it/s]

 10%|▉         | 1826/18769 [01:16<12:07, 23.30it/s]

 10%|▉         | 1829/18769 [01:16<12:04, 23.38it/s]

 10%|▉         | 1832/18769 [01:16<12:02, 23.45it/s]

 10%|▉         | 1835/18769 [01:16<12:03, 23.42it/s]

 10%|▉         | 1838/18769 [01:16<11:54, 23.69it/s]

 10%|▉         | 1841/18769 [01:16<11:48, 23.90it/s]

 10%|▉         | 1844/18769 [01:16<11:44, 24.02it/s]

 10%|▉         | 1847/18769 [01:17<11:41, 24.12it/s]

 10%|▉         | 1850/18769 [01:17<11:39, 24.18it/s]

 10%|▉         | 1853/18769 [01:17<11:38, 24.23it/s]

 10%|▉         | 1856/18769 [01:17<11:37, 24.26it/s]

 10%|▉         | 1859/18769 [01:17<11:35, 24.33it/s]

 10%|▉         | 1862/18769 [01:17<11:34, 24.34it/s]

 10%|▉         | 1865/18769 [01:17<11:34, 24.33it/s]

 10%|▉         | 1868/18769 [01:17<11:35, 24.29it/s]

 10%|▉         | 1871/18769 [01:18<11:35, 24.28it/s]

 10%|▉         | 1874/18769 [01:18<11:40, 24.13it/s]

 10%|█         | 1877/18769 [01:18<11:39, 24.17it/s]

 10%|█         | 1880/18769 [01:18<11:38, 24.18it/s]

 10%|█         | 1883/18769 [01:18<11:38, 24.18it/s]

 10%|█         | 1886/18769 [01:18<11:37, 24.21it/s]

 10%|█         | 1889/18769 [01:18<11:37, 24.21it/s]

 10%|█         | 1892/18769 [01:18<11:36, 24.23it/s]

 10%|█         | 1895/18769 [01:19<11:35, 24.25it/s]

 10%|█         | 1898/18769 [01:19<11:35, 24.25it/s]

 10%|█         | 1901/18769 [01:19<11:37, 24.17it/s]

 10%|█         | 1904/18769 [01:19<11:40, 24.06it/s]

 10%|█         | 1907/18769 [01:19<11:39, 24.09it/s]

 10%|█         | 1910/18769 [01:19<11:37, 24.16it/s]

 10%|█         | 1913/18769 [01:19<11:36, 24.20it/s]

 10%|█         | 1916/18769 [01:19<11:36, 24.20it/s]

 10%|█         | 1919/18769 [01:20<11:38, 24.13it/s]

 10%|█         | 1922/18769 [01:20<11:51, 23.68it/s]

 10%|█         | 1925/18769 [01:20<11:55, 23.53it/s]

 10%|█         | 1928/18769 [01:20<11:59, 23.39it/s]

 10%|█         | 1931/18769 [01:20<12:00, 23.38it/s]

 10%|█         | 1935/18769 [01:20<11:05, 25.29it/s]

 10%|█         | 1938/18769 [01:20<11:21, 24.70it/s]

 10%|█         | 1941/18769 [01:20<11:31, 24.34it/s]

 10%|█         | 1944/18769 [01:21<11:40, 24.02it/s]

 10%|█         | 1947/18769 [01:21<11:47, 23.76it/s]

 10%|█         | 1950/18769 [01:21<11:52, 23.61it/s]

 10%|█         | 1953/18769 [01:21<11:54, 23.53it/s]

 10%|█         | 1956/18769 [01:21<11:55, 23.51it/s]

 10%|█         | 1959/18769 [01:21<11:57, 23.41it/s]

 10%|█         | 1962/18769 [01:21<12:00, 23.33it/s]

 10%|█         | 1965/18769 [01:21<11:59, 23.35it/s]

 10%|█         | 1968/18769 [01:22<12:00, 23.33it/s]

 11%|█         | 1971/18769 [01:22<12:04, 23.17it/s]

 11%|█         | 1974/18769 [01:22<11:58, 23.37it/s]

 11%|█         | 1977/18769 [01:22<11:51, 23.59it/s]

 11%|█         | 1980/18769 [01:22<11:47, 23.73it/s]

 11%|█         | 1983/18769 [01:22<11:45, 23.78it/s]

 11%|█         | 1986/18769 [01:22<11:42, 23.88it/s]

 11%|█         | 1989/18769 [01:22<11:39, 23.99it/s]

 11%|█         | 1992/18769 [01:23<11:37, 24.07it/s]

 11%|█         | 1995/18769 [01:23<11:36, 24.07it/s]

 11%|█         | 1998/18769 [01:23<11:37, 24.05it/s]

 11%|█         | 2001/18769 [01:23<11:37, 24.04it/s]

 11%|█         | 2004/18769 [01:23<11:36, 24.07it/s]

 11%|█         | 2007/18769 [01:23<11:36, 24.08it/s]

 11%|█         | 2010/18769 [01:23<11:35, 24.10it/s]

 11%|█         | 2013/18769 [01:23<11:35, 24.11it/s]

 11%|█         | 2016/18769 [01:24<11:34, 24.12it/s]

 11%|█         | 2019/18769 [01:24<11:34, 24.11it/s]

 11%|█         | 2022/18769 [01:24<11:33, 24.14it/s]

 11%|█         | 2025/18769 [01:24<11:32, 24.17it/s]

 11%|█         | 2028/18769 [01:24<11:35, 24.08it/s]

 11%|█         | 2031/18769 [01:24<11:34, 24.10it/s]

 11%|█         | 2034/18769 [01:24<11:33, 24.14it/s]

 11%|█         | 2037/18769 [01:24<11:33, 24.13it/s]

 11%|█         | 2040/18769 [01:25<11:33, 24.11it/s]

 11%|█         | 2043/18769 [01:25<11:33, 24.13it/s]

 11%|█         | 2046/18769 [01:25<11:33, 24.12it/s]

 11%|█         | 2049/18769 [01:25<11:32, 24.16it/s]

 11%|█         | 2052/18769 [01:25<11:31, 24.18it/s]

 11%|█         | 2055/18769 [01:25<11:30, 24.21it/s]

 11%|█         | 2058/18769 [01:25<11:37, 23.97it/s]

 11%|█         | 2061/18769 [01:25<11:40, 23.86it/s]

 11%|█         | 2064/18769 [01:26<11:44, 23.71it/s]

 11%|█         | 2067/18769 [01:26<11:47, 23.60it/s]

 11%|█         | 2070/18769 [01:26<11:49, 23.53it/s]

 11%|█         | 2074/18769 [01:26<10:56, 25.43it/s]

 11%|█         | 2077/18769 [01:26<11:13, 24.80it/s]

 11%|█         | 2080/18769 [01:26<11:25, 24.36it/s]

 11%|█         | 2083/18769 [01:26<11:32, 24.08it/s]

 11%|█         | 2086/18769 [01:26<11:38, 23.88it/s]

 11%|█         | 2089/18769 [01:27<11:42, 23.74it/s]

 11%|█         | 2092/18769 [01:27<11:46, 23.62it/s]

 11%|█         | 2095/18769 [01:27<11:48, 23.53it/s]

 11%|█         | 2098/18769 [01:27<11:51, 23.43it/s]

 11%|█         | 2101/18769 [01:27<11:51, 23.42it/s]

 11%|█         | 2104/18769 [01:27<11:50, 23.46it/s]

 11%|█         | 2107/18769 [01:27<11:50, 23.47it/s]

 11%|█         | 2110/18769 [01:27<11:47, 23.54it/s]

 11%|█▏        | 2113/18769 [01:28<11:42, 23.70it/s]

 11%|█▏        | 2116/18769 [01:28<11:39, 23.82it/s]

 11%|█▏        | 2119/18769 [01:28<11:34, 23.96it/s]

 11%|█▏        | 2122/18769 [01:28<11:33, 24.00it/s]

 11%|█▏        | 2125/18769 [01:28<11:31, 24.05it/s]

 11%|█▏        | 2128/18769 [01:28<11:29, 24.15it/s]

 11%|█▏        | 2131/18769 [01:28<11:26, 24.23it/s]

 11%|█▏        | 2134/18769 [01:28<11:26, 24.25it/s]

 11%|█▏        | 2137/18769 [01:29<11:26, 24.24it/s]

 11%|█▏        | 2140/18769 [01:29<11:27, 24.19it/s]

 11%|█▏        | 2143/18769 [01:29<11:28, 24.16it/s]

 11%|█▏        | 2146/18769 [01:29<11:27, 24.17it/s]

 11%|█▏        | 2149/18769 [01:29<11:27, 24.16it/s]

 11%|█▏        | 2152/18769 [01:29<11:27, 24.18it/s]

 11%|█▏        | 2155/18769 [01:29<11:25, 24.22it/s]

 11%|█▏        | 2158/18769 [01:29<11:24, 24.27it/s]

 12%|█▏        | 2161/18769 [01:30<11:23, 24.29it/s]

 12%|█▏        | 2164/18769 [01:30<11:24, 24.25it/s]

 12%|█▏        | 2167/18769 [01:30<11:24, 24.24it/s]

 12%|█▏        | 2170/18769 [01:30<11:25, 24.21it/s]

 12%|█▏        | 2173/18769 [01:30<11:25, 24.22it/s]

 12%|█▏        | 2176/18769 [01:30<11:24, 24.23it/s]

 12%|█▏        | 2179/18769 [01:30<11:24, 24.25it/s]

 12%|█▏        | 2182/18769 [01:30<11:24, 24.22it/s]

 12%|█▏        | 2185/18769 [01:31<11:24, 24.21it/s]

 12%|█▏        | 2188/18769 [01:31<11:29, 24.06it/s]

 12%|█▏        | 2191/18769 [01:31<11:28, 24.08it/s]

 12%|█▏        | 2194/18769 [01:31<11:32, 23.94it/s]

 12%|█▏        | 2197/18769 [01:31<11:38, 23.73it/s]

 12%|█▏        | 2200/18769 [01:31<11:40, 23.64it/s]

 12%|█▏        | 2203/18769 [01:31<11:44, 23.53it/s]

 12%|█▏        | 2206/18769 [01:31<11:45, 23.48it/s]

 12%|█▏        | 2210/18769 [01:32<10:54, 25.30it/s]

 12%|█▏        | 2213/18769 [01:32<11:12, 24.61it/s]

 12%|█▏        | 2216/18769 [01:32<11:24, 24.17it/s]

 12%|█▏        | 2219/18769 [01:32<11:33, 23.85it/s]

 12%|█▏        | 2222/18769 [01:32<11:38, 23.69it/s]

 12%|█▏        | 2225/18769 [01:32<11:46, 23.43it/s]

 12%|█▏        | 2228/18769 [01:32<11:46, 23.40it/s]

 12%|█▏        | 2231/18769 [01:33<11:48, 23.35it/s]

 12%|█▏        | 2234/18769 [01:33<11:50, 23.27it/s]

 12%|█▏        | 2237/18769 [01:33<11:54, 23.15it/s]

 12%|█▏        | 2240/18769 [01:33<11:51, 23.22it/s]

 12%|█▏        | 2243/18769 [01:33<11:50, 23.25it/s]

 12%|█▏        | 2246/18769 [01:33<11:49, 23.30it/s]

 12%|█▏        | 2249/18769 [01:33<11:41, 23.55it/s]

 12%|█▏        | 2252/18769 [01:33<11:36, 23.71it/s]

 12%|█▏        | 2255/18769 [01:34<11:35, 23.73it/s]

 12%|█▏        | 2258/18769 [01:34<11:33, 23.80it/s]

 12%|█▏        | 2261/18769 [01:34<11:34, 23.77it/s]

 12%|█▏        | 2264/18769 [01:34<11:32, 23.82it/s]

 12%|█▏        | 2267/18769 [01:34<11:30, 23.90it/s]

 12%|█▏        | 2270/18769 [01:34<11:29, 23.95it/s]

 12%|█▏        | 2273/18769 [01:34<11:27, 24.00it/s]

 12%|█▏        | 2276/18769 [01:34<11:26, 24.01it/s]

 12%|█▏        | 2279/18769 [01:35<11:26, 24.02it/s]

 12%|█▏        | 2282/18769 [01:35<11:26, 24.01it/s]

 12%|█▏        | 2285/18769 [01:35<11:29, 23.92it/s]

 12%|█▏        | 2288/18769 [01:35<11:28, 23.95it/s]

 12%|█▏        | 2291/18769 [01:35<11:27, 23.95it/s]

 12%|█▏        | 2294/18769 [01:35<11:27, 23.98it/s]

 12%|█▏        | 2297/18769 [01:35<11:26, 23.99it/s]

 12%|█▏        | 2300/18769 [01:35<11:25, 24.04it/s]

 12%|█▏        | 2303/18769 [01:36<11:24, 24.07it/s]

 12%|█▏        | 2306/18769 [01:36<11:27, 23.96it/s]

 12%|█▏        | 2309/18769 [01:36<11:30, 23.85it/s]

 12%|█▏        | 2312/18769 [01:36<11:27, 23.93it/s]

 12%|█▏        | 2315/18769 [01:36<11:26, 23.95it/s]

 12%|█▏        | 2318/18769 [01:36<11:26, 23.96it/s]

 12%|█▏        | 2321/18769 [01:36<11:24, 24.01it/s]

 12%|█▏        | 2324/18769 [01:36<11:28, 23.87it/s]

 12%|█▏        | 2327/18769 [01:37<11:26, 23.94it/s]

 12%|█▏        | 2330/18769 [01:37<11:28, 23.88it/s]

 12%|█▏        | 2333/18769 [01:37<11:32, 23.72it/s]

 12%|█▏        | 2336/18769 [01:37<11:35, 23.63it/s]

 12%|█▏        | 2339/18769 [01:37<11:36, 23.59it/s]

 12%|█▏        | 2342/18769 [01:37<11:38, 23.50it/s]

 12%|█▏        | 2345/18769 [01:37<11:39, 23.47it/s]

 13%|█▎        | 2349/18769 [01:37<10:49, 25.28it/s]

 13%|█▎        | 2352/18769 [01:38<11:03, 24.73it/s]

 13%|█▎        | 2355/18769 [01:38<11:15, 24.31it/s]

 13%|█▎        | 2358/18769 [01:38<11:28, 23.85it/s]

 13%|█▎        | 2361/18769 [01:38<11:32, 23.69it/s]

 13%|█▎        | 2364/18769 [01:38<11:35, 23.59it/s]

 13%|█▎        | 2367/18769 [01:38<11:36, 23.53it/s]

 13%|█▎        | 2370/18769 [01:38<11:38, 23.48it/s]

 13%|█▎        | 2373/18769 [01:38<11:38, 23.47it/s]

 13%|█▎        | 2376/18769 [01:39<12:54, 21.17it/s]

 13%|█▎        | 2379/18769 [01:39<12:31, 21.80it/s]

 13%|█▎        | 2382/18769 [01:39<12:16, 22.24it/s]

 13%|█▎        | 2385/18769 [01:39<12:01, 22.72it/s]

 13%|█▎        | 2388/18769 [01:39<11:47, 23.14it/s]

 13%|█▎        | 2391/18769 [01:39<11:39, 23.43it/s]

 13%|█▎        | 2394/18769 [01:39<11:31, 23.66it/s]

 13%|█▎        | 2397/18769 [01:40<11:27, 23.80it/s]

 13%|█▎        | 2400/18769 [01:40<11:25, 23.86it/s]

 13%|█▎        | 2403/18769 [01:40<11:28, 23.77it/s]

 13%|█▎        | 2406/18769 [01:40<11:26, 23.82it/s]

 13%|█▎        | 2409/18769 [01:40<11:24, 23.90it/s]

 13%|█▎        | 2412/18769 [01:40<11:24, 23.90it/s]

 13%|█▎        | 2415/18769 [01:40<11:23, 23.93it/s]

 13%|█▎        | 2418/18769 [01:40<11:23, 23.93it/s]

 13%|█▎        | 2421/18769 [01:41<11:21, 23.99it/s]

 13%|█▎        | 2424/18769 [01:41<11:20, 24.03it/s]

 13%|█▎        | 2427/18769 [01:41<11:19, 24.05it/s]

 13%|█▎        | 2430/18769 [01:41<11:19, 24.06it/s]

 13%|█▎        | 2433/18769 [01:41<11:18, 24.09it/s]

 13%|█▎        | 2436/18769 [01:41<11:17, 24.10it/s]

 13%|█▎        | 2439/18769 [01:41<11:18, 24.07it/s]

 13%|█▎        | 2442/18769 [01:41<11:17, 24.09it/s]

 13%|█▎        | 2445/18769 [01:42<11:17, 24.11it/s]

 13%|█▎        | 2448/18769 [01:42<11:17, 24.10it/s]

 13%|█▎        | 2451/18769 [01:42<11:21, 23.96it/s]

 13%|█▎        | 2454/18769 [01:42<11:20, 23.99it/s]

 13%|█▎        | 2457/18769 [01:42<11:18, 24.03it/s]

 13%|█▎        | 2460/18769 [01:42<11:19, 24.00it/s]

 13%|█▎        | 2463/18769 [01:42<11:19, 23.99it/s]

 13%|█▎        | 2466/18769 [01:42<11:17, 24.06it/s]

 13%|█▎        | 2469/18769 [01:43<11:26, 23.73it/s]

 13%|█▎        | 2472/18769 [01:43<11:31, 23.57it/s]

 13%|█▎        | 2475/18769 [01:43<11:35, 23.42it/s]

 13%|█▎        | 2478/18769 [01:43<11:38, 23.32it/s]

 13%|█▎        | 2481/18769 [01:43<11:38, 23.32it/s]

 13%|█▎        | 2484/18769 [01:43<11:39, 23.27it/s]

 13%|█▎        | 2488/18769 [01:43<10:47, 25.15it/s]

 13%|█▎        | 2491/18769 [01:43<11:01, 24.60it/s]

 13%|█▎        | 2494/18769 [01:44<11:13, 24.17it/s]

 13%|█▎        | 2497/18769 [01:44<11:22, 23.85it/s]

 13%|█▎        | 2500/18769 [01:44<11:31, 23.53it/s]

 13%|█▎        | 2503/18769 [01:44<11:32, 23.49it/s]

 13%|█▎        | 2506/18769 [01:44<11:34, 23.42it/s]

 13%|█▎        | 2509/18769 [01:44<11:36, 23.35it/s]

 13%|█▎        | 2512/18769 [01:44<11:35, 23.36it/s]

 13%|█▎        | 2515/18769 [01:44<11:35, 23.38it/s]

 13%|█▎        | 2518/18769 [01:45<11:35, 23.37it/s]

 13%|█▎        | 2521/18769 [01:45<11:33, 23.43it/s]

 13%|█▎        | 2524/18769 [01:45<11:27, 23.62it/s]

 13%|█▎        | 2527/18769 [01:45<11:24, 23.74it/s]

 13%|█▎        | 2530/18769 [01:45<11:20, 23.87it/s]

 13%|█▎        | 2533/18769 [01:45<11:19, 23.91it/s]

 14%|█▎        | 2536/18769 [01:45<11:17, 23.96it/s]

 14%|█▎        | 2539/18769 [01:45<11:16, 24.00it/s]

 14%|█▎        | 2542/18769 [01:46<11:17, 23.94it/s]

 14%|█▎        | 2545/18769 [01:46<11:17, 23.95it/s]

 14%|█▎        | 2548/18769 [01:46<11:20, 23.83it/s]

 14%|█▎        | 2551/18769 [01:46<11:19, 23.86it/s]

 14%|█▎        | 2554/18769 [01:46<11:18, 23.90it/s]

 14%|█▎        | 2557/18769 [01:46<11:17, 23.93it/s]

 14%|█▎        | 2560/18769 [01:46<11:16, 23.97it/s]

 14%|█▎        | 2563/18769 [01:46<11:15, 24.01it/s]

 14%|█▎        | 2566/18769 [01:47<11:14, 24.04it/s]

 14%|█▎        | 2569/18769 [01:47<11:13, 24.07it/s]

 14%|█▎        | 2572/18769 [01:47<11:13, 24.04it/s]

 14%|█▎        | 2575/18769 [01:47<11:13, 24.04it/s]

 14%|█▎        | 2578/18769 [01:47<11:12, 24.06it/s]

 14%|█▍        | 2581/18769 [01:47<11:13, 24.04it/s]

 14%|█▍        | 2584/18769 [01:47<11:12, 24.06it/s]

 14%|█▍        | 2587/18769 [01:47<11:11, 24.09it/s]

 14%|█▍        | 2590/18769 [01:48<11:11, 24.10it/s]

 14%|█▍        | 2593/18769 [01:48<11:12, 24.06it/s]

 14%|█▍        | 2596/18769 [01:48<11:12, 24.05it/s]

 14%|█▍        | 2599/18769 [01:48<11:13, 24.02it/s]

 14%|█▍        | 2602/18769 [01:48<11:13, 23.99it/s]

 14%|█▍        | 2605/18769 [01:48<11:18, 23.81it/s]

 14%|█▍        | 2608/18769 [01:48<11:23, 23.66it/s]

 14%|█▍        | 2611/18769 [01:48<11:27, 23.51it/s]

 14%|█▍        | 2614/18769 [01:49<11:28, 23.47it/s]

 14%|█▍        | 2617/18769 [01:49<11:29, 23.44it/s]

 14%|█▍        | 2620/18769 [01:49<11:30, 23.38it/s]

 14%|█▍        | 2624/18769 [01:49<10:39, 25.26it/s]

 14%|█▍        | 2627/18769 [01:49<10:56, 24.61it/s]

 14%|█▍        | 2630/18769 [01:49<11:06, 24.22it/s]

 14%|█▍        | 2633/18769 [01:49<11:14, 23.92it/s]

 14%|█▍        | 2636/18769 [01:49<11:20, 23.70it/s]

 14%|█▍        | 2639/18769 [01:50<11:24, 23.55it/s]

 14%|█▍        | 2642/18769 [01:50<11:28, 23.43it/s]

 14%|█▍        | 2645/18769 [01:50<11:32, 23.28it/s]

 14%|█▍        | 2648/18769 [01:50<11:33, 23.26it/s]

 14%|█▍        | 2651/18769 [01:50<11:32, 23.28it/s]

 14%|█▍        | 2654/18769 [01:50<11:32, 23.27it/s]

 14%|█▍        | 2657/18769 [01:50<11:30, 23.32it/s]

 14%|█▍        | 2660/18769 [01:51<11:24, 23.52it/s]

 14%|█▍        | 2663/18769 [01:51<11:20, 23.65it/s]

 14%|█▍        | 2666/18769 [01:51<11:17, 23.76it/s]

 14%|█▍        | 2669/18769 [01:51<11:16, 23.81it/s]

 14%|█▍        | 2672/18769 [01:51<11:14, 23.87it/s]

 14%|█▍        | 2675/18769 [01:51<11:13, 23.91it/s]

 14%|█▍        | 2678/18769 [01:51<11:12, 23.93it/s]

 14%|█▍        | 2681/18769 [01:51<11:11, 23.94it/s]

 14%|█▍        | 2684/18769 [01:52<11:09, 24.02it/s]

 14%|█▍        | 2687/18769 [01:52<11:11, 23.94it/s]

 14%|█▍        | 2690/18769 [01:52<11:09, 24.00it/s]

 14%|█▍        | 2693/18769 [01:52<11:09, 24.02it/s]

 14%|█▍        | 2696/18769 [01:52<11:08, 24.04it/s]

 14%|█▍        | 2699/18769 [01:52<11:07, 24.06it/s]

 14%|█▍        | 2702/18769 [01:52<11:07, 24.07it/s]

 14%|█▍        | 2705/18769 [01:52<11:06, 24.09it/s]

 14%|█▍        | 2708/18769 [01:53<11:06, 24.10it/s]

 14%|█▍        | 2711/18769 [01:53<11:06, 24.10it/s]

 14%|█▍        | 2714/18769 [01:53<11:07, 24.07it/s]

 14%|█▍        | 2717/18769 [01:53<11:07, 24.05it/s]

 14%|█▍        | 2720/18769 [01:53<11:05, 24.11it/s]

 15%|█▍        | 2723/18769 [01:53<11:04, 24.13it/s]

 15%|█▍        | 2726/18769 [01:53<11:05, 24.11it/s]

 15%|█▍        | 2729/18769 [01:53<11:04, 24.14it/s]

 15%|█▍        | 2732/18769 [01:54<11:04, 24.14it/s]

 15%|█▍        | 2735/18769 [01:54<11:04, 24.12it/s]

 15%|█▍        | 2738/18769 [01:54<11:04, 24.14it/s]

 15%|█▍        | 2741/18769 [01:54<11:05, 24.07it/s]

 15%|█▍        | 2744/18769 [01:54<11:10, 23.90it/s]

 15%|█▍        | 2747/18769 [01:54<11:14, 23.77it/s]

 15%|█▍        | 2750/18769 [01:54<11:17, 23.66it/s]

 15%|█▍        | 2753/18769 [01:54<11:18, 23.59it/s]

 15%|█▍        | 2756/18769 [01:55<11:19, 23.56it/s]

 15%|█▍        | 2759/18769 [01:55<11:21, 23.50it/s]

 15%|█▍        | 2763/18769 [01:55<10:30, 25.39it/s]

 15%|█▍        | 2766/18769 [01:55<10:46, 24.76it/s]

 15%|█▍        | 2769/18769 [01:55<10:57, 24.34it/s]

 15%|█▍        | 2772/18769 [01:55<11:03, 24.10it/s]

 15%|█▍        | 2775/18769 [01:55<11:09, 23.90it/s]

 15%|█▍        | 2778/18769 [01:55<11:13, 23.73it/s]

 15%|█▍        | 2781/18769 [01:56<11:17, 23.59it/s]

 15%|█▍        | 2784/18769 [01:56<11:19, 23.52it/s]

 15%|█▍        | 2787/18769 [01:56<11:20, 23.50it/s]

 15%|█▍        | 2790/18769 [01:56<11:20, 23.48it/s]

 15%|█▍        | 2793/18769 [01:56<11:21, 23.45it/s]

 15%|█▍        | 2796/18769 [01:56<11:17, 23.58it/s]

 15%|█▍        | 2799/18769 [01:56<11:11, 23.77it/s]

 15%|█▍        | 2802/18769 [01:56<11:09, 23.84it/s]

 15%|█▍        | 2805/18769 [01:57<11:07, 23.93it/s]

 15%|█▍        | 2808/18769 [01:57<11:05, 23.99it/s]

 15%|█▍        | 2811/18769 [01:57<11:03, 24.07it/s]

 15%|█▍        | 2814/18769 [01:57<11:02, 24.09it/s]

 15%|█▌        | 2817/18769 [01:57<11:01, 24.10it/s]

 15%|█▌        | 2820/18769 [01:57<11:00, 24.14it/s]

 15%|█▌        | 2823/18769 [01:57<10:59, 24.18it/s]

 15%|█▌        | 2826/18769 [01:57<10:59, 24.17it/s]

 15%|█▌        | 2829/18769 [01:58<11:02, 24.05it/s]

 15%|█▌        | 2832/18769 [01:58<11:02, 24.07it/s]

 15%|█▌        | 2835/18769 [01:58<11:00, 24.11it/s]

 15%|█▌        | 2838/18769 [01:58<10:59, 24.16it/s]

 15%|█▌        | 2841/18769 [01:58<10:58, 24.19it/s]

 15%|█▌        | 2844/18769 [01:58<10:58, 24.20it/s]

 15%|█▌        | 2847/18769 [01:58<10:57, 24.23it/s]

 15%|█▌        | 2850/18769 [01:58<10:56, 24.25it/s]

 15%|█▌        | 2853/18769 [01:59<10:55, 24.29it/s]

 15%|█▌        | 2856/18769 [01:59<10:55, 24.29it/s]

 15%|█▌        | 2859/18769 [01:59<10:56, 24.25it/s]

 15%|█▌        | 2862/18769 [01:59<10:57, 24.18it/s]

 15%|█▌        | 2865/18769 [01:59<10:56, 24.23it/s]

 15%|█▌        | 2868/18769 [01:59<10:55, 24.25it/s]

 15%|█▌        | 2871/18769 [01:59<10:55, 24.27it/s]

 15%|█▌        | 2874/18769 [01:59<10:55, 24.25it/s]

 15%|█▌        | 2877/18769 [02:00<10:54, 24.26it/s]

 15%|█▌        | 2880/18769 [02:00<11:02, 23.97it/s]

 15%|█▌        | 2883/18769 [02:00<11:05, 23.85it/s]

 15%|█▌        | 2886/18769 [02:00<11:09, 23.74it/s]

 15%|█▌        | 2889/18769 [02:00<11:10, 23.67it/s]

 15%|█▌        | 2892/18769 [02:00<11:42, 22.61it/s]

 15%|█▌        | 2895/18769 [02:00<11:35, 22.83it/s]

 15%|█▌        | 2898/18769 [02:00<11:30, 22.99it/s]

 15%|█▌        | 2902/18769 [02:01<10:33, 25.03it/s]

 15%|█▌        | 2905/18769 [02:01<10:46, 24.53it/s]

 15%|█▌        | 2908/18769 [02:01<10:55, 24.20it/s]

 16%|█▌        | 2911/18769 [02:01<11:01, 23.96it/s]

 16%|█▌        | 2914/18769 [02:01<11:05, 23.81it/s]

 16%|█▌        | 2917/18769 [02:01<11:07, 23.73it/s]

 16%|█▌        | 2920/18769 [02:01<11:10, 23.65it/s]

 16%|█▌        | 2923/18769 [02:01<11:10, 23.64it/s]

 16%|█▌        | 2926/18769 [02:02<11:11, 23.60it/s]

 16%|█▌        | 2929/18769 [02:02<11:12, 23.56it/s]

 16%|█▌        | 2932/18769 [02:02<11:09, 23.64it/s]

 16%|█▌        | 2935/18769 [02:02<11:04, 23.83it/s]

 16%|█▌        | 2938/18769 [02:02<11:01, 23.93it/s]

 16%|█▌        | 2941/18769 [02:02<11:00, 23.98it/s]

 16%|█▌        | 2944/18769 [02:02<10:57, 24.07it/s]

 16%|█▌        | 2947/18769 [02:02<10:56, 24.10it/s]

 16%|█▌        | 2950/18769 [02:03<10:54, 24.16it/s]

 16%|█▌        | 2953/18769 [02:03<10:54, 24.16it/s]

 16%|█▌        | 2956/18769 [02:03<10:54, 24.16it/s]

 16%|█▌        | 2959/18769 [02:03<10:55, 24.10it/s]

 16%|█▌        | 2962/18769 [02:03<10:55, 24.12it/s]

 16%|█▌        | 2965/18769 [02:03<10:53, 24.19it/s]

 16%|█▌        | 2968/18769 [02:03<10:52, 24.20it/s]

 16%|█▌        | 2971/18769 [02:03<10:51, 24.27it/s]

 16%|█▌        | 2974/18769 [02:04<10:54, 24.14it/s]

 16%|█▌        | 2977/18769 [02:04<10:52, 24.19it/s]

 16%|█▌        | 2980/18769 [02:04<10:52, 24.21it/s]

 16%|█▌        | 2983/18769 [02:04<10:51, 24.24it/s]

 16%|█▌        | 2986/18769 [02:04<10:50, 24.27it/s]

 16%|█▌        | 2989/18769 [02:04<10:50, 24.25it/s]

 16%|█▌        | 2992/18769 [02:04<10:50, 24.24it/s]

 16%|█▌        | 2995/18769 [02:04<10:50, 24.25it/s]

 16%|█▌        | 2998/18769 [02:05<10:49, 24.27it/s]

 16%|█▌        | 3001/18769 [02:05<10:49, 24.26it/s]

 16%|█▌        | 3004/18769 [02:05<10:50, 24.22it/s]

 16%|█▌        | 3007/18769 [02:05<10:51, 24.19it/s]

 16%|█▌        | 3010/18769 [02:05<10:51, 24.20it/s]

 16%|█▌        | 3013/18769 [02:05<10:51, 24.18it/s]

 16%|█▌        | 3016/18769 [02:05<10:55, 24.03it/s]

 16%|█▌        | 3019/18769 [02:05<11:01, 23.82it/s]

 16%|█▌        | 3022/18769 [02:06<11:04, 23.71it/s]

 16%|█▌        | 3025/18769 [02:06<11:06, 23.63it/s]

 16%|█▌        | 3028/18769 [02:06<11:09, 23.53it/s]

 16%|█▌        | 3031/18769 [02:06<11:10, 23.49it/s]

 16%|█▌        | 3034/18769 [02:06<11:10, 23.47it/s]

 16%|█▌        | 3038/18769 [02:06<10:19, 25.38it/s]

 16%|█▌        | 3041/18769 [02:06<10:35, 24.75it/s]

 16%|█▌        | 3044/18769 [02:06<10:44, 24.40it/s]

 16%|█▌        | 3047/18769 [02:07<10:52, 24.10it/s]

 16%|█▋        | 3050/18769 [02:07<10:57, 23.89it/s]

 16%|█▋        | 3053/18769 [02:07<11:00, 23.78it/s]

 16%|█▋        | 3056/18769 [02:07<11:03, 23.69it/s]

 16%|█▋        | 3059/18769 [02:07<11:04, 23.62it/s]

 16%|█▋        | 3062/18769 [02:07<11:20, 23.08it/s]

 16%|█▋        | 3065/18769 [02:07<11:17, 23.17it/s]

 16%|█▋        | 3068/18769 [02:08<11:15, 23.25it/s]

 16%|█▋        | 3071/18769 [02:08<11:09, 23.44it/s]

 16%|█▋        | 3074/18769 [02:08<11:04, 23.62it/s]

 16%|█▋        | 3077/18769 [02:08<10:58, 23.82it/s]

 16%|█▋        | 3080/18769 [02:08<10:55, 23.93it/s]

 16%|█▋        | 3083/18769 [02:08<10:53, 24.00it/s]

 16%|█▋        | 3086/18769 [02:08<10:52, 24.02it/s]

 16%|█▋        | 3089/18769 [02:08<10:50, 24.09it/s]

 16%|█▋        | 3092/18769 [02:09<10:49, 24.13it/s]

 16%|█▋        | 3095/18769 [02:09<10:49, 24.14it/s]

 17%|█▋        | 3098/18769 [02:09<10:49, 24.13it/s]

 17%|█▋        | 3101/18769 [02:09<10:49, 24.12it/s]

 17%|█▋        | 3104/18769 [02:09<10:50, 24.08it/s]

 17%|█▋        | 3107/18769 [02:09<10:50, 24.08it/s]

 17%|█▋        | 3110/18769 [02:09<10:49, 24.11it/s]

 17%|█▋        | 3113/18769 [02:09<10:49, 24.10it/s]

 17%|█▋        | 3116/18769 [02:10<10:50, 24.07it/s]

 17%|█▋        | 3119/18769 [02:10<10:52, 23.99it/s]

 17%|█▋        | 3122/18769 [02:10<10:51, 24.01it/s]

 17%|█▋        | 3125/18769 [02:10<10:49, 24.07it/s]

 17%|█▋        | 3128/18769 [02:10<10:49, 24.09it/s]

 17%|█▋        | 3131/18769 [02:10<10:48, 24.12it/s]

 17%|█▋        | 3134/18769 [02:10<10:47, 24.13it/s]

 17%|█▋        | 3137/18769 [02:10<10:47, 24.16it/s]

 17%|█▋        | 3140/18769 [02:11<10:47, 24.15it/s]

 17%|█▋        | 3143/18769 [02:11<10:47, 24.15it/s]

 17%|█▋        | 3146/18769 [02:11<10:47, 24.13it/s]

 17%|█▋        | 3149/18769 [02:11<10:50, 24.00it/s]

 17%|█▋        | 3152/18769 [02:11<10:53, 23.90it/s]

 17%|█▋        | 3155/18769 [02:11<10:59, 23.66it/s]

 17%|█▋        | 3158/18769 [02:11<11:05, 23.45it/s]

 17%|█▋        | 3161/18769 [02:11<11:10, 23.29it/s]

 17%|█▋        | 3164/18769 [02:12<11:10, 23.26it/s]

 17%|█▋        | 3167/18769 [02:12<11:15, 23.11it/s]

 17%|█▋        | 3170/18769 [02:12<11:13, 23.15it/s]

 17%|█▋        | 3173/18769 [02:12<11:10, 23.25it/s]

 17%|█▋        | 3177/18769 [02:12<10:19, 25.15it/s]

 17%|█▋        | 3180/18769 [02:12<10:33, 24.62it/s]

 17%|█▋        | 3183/18769 [02:12<10:43, 24.23it/s]

 17%|█▋        | 3186/18769 [02:12<10:51, 23.90it/s]

 17%|█▋        | 3189/18769 [02:13<10:59, 23.62it/s]

 17%|█▋        | 3192/18769 [02:13<11:06, 23.37it/s]

 17%|█▋        | 3195/18769 [02:13<11:10, 23.24it/s]

 17%|█▋        | 3198/18769 [02:13<11:12, 23.15it/s]

 17%|█▋        | 3201/18769 [02:13<11:10, 23.22it/s]

 17%|█▋        | 3204/18769 [02:13<11:07, 23.31it/s]

 17%|█▋        | 3207/18769 [02:13<11:02, 23.50it/s]

 17%|█▋        | 3210/18769 [02:13<10:56, 23.71it/s]

 17%|█▋        | 3213/18769 [02:14<10:51, 23.88it/s]

 17%|█▋        | 3216/18769 [02:14<10:49, 23.95it/s]

 17%|█▋        | 3219/18769 [02:14<10:46, 24.04it/s]

 17%|█▋        | 3222/18769 [02:14<10:46, 24.06it/s]

 17%|█▋        | 3225/18769 [02:14<10:45, 24.10it/s]

 17%|█▋        | 3228/18769 [02:14<10:44, 24.10it/s]

 17%|█▋        | 3231/18769 [02:14<10:43, 24.13it/s]

 17%|█▋        | 3234/18769 [02:14<10:42, 24.19it/s]

 17%|█▋        | 3237/18769 [02:15<10:40, 24.23it/s]

 17%|█▋        | 3240/18769 [02:15<10:42, 24.18it/s]

 17%|█▋        | 3243/18769 [02:15<10:42, 24.16it/s]

 17%|█▋        | 3246/18769 [02:15<10:42, 24.15it/s]

 17%|█▋        | 3249/18769 [02:15<10:43, 24.13it/s]

 17%|█▋        | 3252/18769 [02:15<10:42, 24.16it/s]

 17%|█▋        | 3255/18769 [02:15<10:42, 24.15it/s]

 17%|█▋        | 3258/18769 [02:15<10:41, 24.16it/s]

 17%|█▋        | 3261/18769 [02:16<10:42, 24.13it/s]

 17%|█▋        | 3264/18769 [02:16<10:47, 23.95it/s]

 17%|█▋        | 3267/18769 [02:16<10:45, 24.00it/s]

 17%|█▋        | 3270/18769 [02:16<10:45, 24.02it/s]

 17%|█▋        | 3273/18769 [02:16<10:44, 24.03it/s]

 17%|█▋        | 3276/18769 [02:16<10:44, 24.03it/s]

 17%|█▋        | 3279/18769 [02:16<10:43, 24.07it/s]

 17%|█▋        | 3282/18769 [02:16<10:43, 24.08it/s]

 18%|█▊        | 3285/18769 [02:17<10:42, 24.10it/s]

 18%|█▊        | 3288/18769 [02:17<10:42, 24.08it/s]

 18%|█▊        | 3291/18769 [02:17<10:49, 23.83it/s]

 18%|█▊        | 3294/18769 [02:17<10:53, 23.67it/s]

 18%|█▊        | 3297/18769 [02:17<10:55, 23.61it/s]

 18%|█▊        | 3300/18769 [02:17<10:57, 23.54it/s]

 18%|█▊        | 3303/18769 [02:17<10:57, 23.53it/s]

 18%|█▊        | 3306/18769 [02:17<10:58, 23.49it/s]

 18%|█▊        | 3309/18769 [02:18<10:58, 23.46it/s]

 18%|█▊        | 3312/18769 [02:18<10:59, 23.43it/s]

 18%|█▊        | 3316/18769 [02:18<10:10, 25.32it/s]

 18%|█▊        | 3319/18769 [02:18<10:28, 24.58it/s]

 18%|█▊        | 3322/18769 [02:18<10:38, 24.20it/s]

 18%|█▊        | 3325/18769 [02:18<10:46, 23.88it/s]

 18%|█▊        | 3328/18769 [02:18<10:51, 23.72it/s]

 18%|█▊        | 3331/18769 [02:18<10:54, 23.59it/s]

 18%|█▊        | 3334/18769 [02:19<10:55, 23.55it/s]

 18%|█▊        | 3337/18769 [02:19<10:58, 23.45it/s]

 18%|█▊        | 3340/18769 [02:19<10:59, 23.40it/s]

 18%|█▊        | 3343/18769 [02:19<10:58, 23.42it/s]

 18%|█▊        | 3346/18769 [02:19<10:53, 23.61it/s]

 18%|█▊        | 3349/18769 [02:19<10:49, 23.76it/s]

 18%|█▊        | 3352/18769 [02:19<10:46, 23.86it/s]

 18%|█▊        | 3355/18769 [02:20<10:44, 23.90it/s]

 18%|█▊        | 3358/18769 [02:20<10:44, 23.92it/s]

 18%|█▊        | 3361/18769 [02:20<10:43, 23.96it/s]

 18%|█▊        | 3364/18769 [02:20<10:40, 24.03it/s]

 18%|█▊        | 3367/18769 [02:20<10:39, 24.09it/s]

 18%|█▊        | 3370/18769 [02:20<10:38, 24.12it/s]

 18%|█▊        | 3373/18769 [02:20<10:44, 23.90it/s]

 18%|█▊        | 3376/18769 [02:20<10:41, 24.00it/s]

 18%|█▊        | 3379/18769 [02:21<10:41, 24.00it/s]

 18%|█▊        | 3382/18769 [02:21<10:39, 24.06it/s]

 18%|█▊        | 3385/18769 [02:21<10:39, 24.06it/s]

 18%|█▊        | 3388/18769 [02:21<10:39, 24.06it/s]

 18%|█▊        | 3391/18769 [02:21<10:38, 24.09it/s]

 18%|█▊        | 3394/18769 [02:21<10:37, 24.13it/s]

 18%|█▊        | 3397/18769 [02:21<10:36, 24.14it/s]

 18%|█▊        | 3400/18769 [02:21<10:36, 24.16it/s]

 18%|█▊        | 3403/18769 [02:21<10:35, 24.16it/s]

 18%|█▊        | 3406/18769 [02:22<10:38, 24.06it/s]

 18%|█▊        | 3409/18769 [02:22<10:37, 24.09it/s]

 18%|█▊        | 3412/18769 [02:22<10:37, 24.10it/s]

 18%|█▊        | 3415/18769 [02:22<10:36, 24.11it/s]

 18%|█▊        | 3418/18769 [02:22<10:35, 24.14it/s]

 18%|█▊        | 3421/18769 [02:22<10:36, 24.11it/s]

 18%|█▊        | 3424/18769 [02:22<10:36, 24.12it/s]

 18%|█▊        | 3427/18769 [02:22<10:40, 23.94it/s]

 18%|█▊        | 3430/18769 [02:23<10:45, 23.77it/s]

 18%|█▊        | 3433/18769 [02:23<10:49, 23.63it/s]

 18%|█▊        | 3436/18769 [02:23<10:52, 23.49it/s]

 18%|█▊        | 3439/18769 [02:23<10:53, 23.47it/s]

 18%|█▊        | 3442/18769 [02:23<10:53, 23.44it/s]

 18%|█▊        | 3445/18769 [02:23<10:53, 23.45it/s]

 18%|█▊        | 3448/18769 [02:23<10:54, 23.40it/s]

 18%|█▊        | 3452/18769 [02:24<10:05, 25.31it/s]

 18%|█▊        | 3455/18769 [02:24<10:20, 24.69it/s]

 18%|█▊        | 3458/18769 [02:24<10:30, 24.28it/s]

 18%|█▊        | 3461/18769 [02:24<10:36, 24.05it/s]

 18%|█▊        | 3464/18769 [02:24<10:42, 23.81it/s]

 18%|█▊        | 3467/18769 [02:24<10:46, 23.68it/s]

 18%|█▊        | 3470/18769 [02:24<10:46, 23.65it/s]

 19%|█▊        | 3473/18769 [02:24<10:47, 23.62it/s]

 19%|█▊        | 3476/18769 [02:25<10:47, 23.61it/s]

 19%|█▊        | 3479/18769 [02:25<10:48, 23.59it/s]

 19%|█▊        | 3482/18769 [02:25<10:43, 23.74it/s]

 19%|█▊        | 3485/18769 [02:25<10:39, 23.90it/s]

 19%|█▊        | 3488/18769 [02:25<10:36, 24.02it/s]

 19%|█▊        | 3491/18769 [02:25<10:35, 24.05it/s]

 19%|█▊        | 3494/18769 [02:25<10:32, 24.14it/s]

 19%|█▊        | 3497/18769 [02:25<10:33, 24.12it/s]

 19%|█▊        | 3500/18769 [02:26<10:32, 24.13it/s]

 19%|█▊        | 3503/18769 [02:26<10:33, 24.10it/s]

 19%|█▊        | 3506/18769 [02:26<10:32, 24.13it/s]

 19%|█▊        | 3509/18769 [02:26<10:32, 24.14it/s]

 19%|█▊        | 3512/18769 [02:26<10:33, 24.10it/s]

 19%|█▊        | 3515/18769 [02:26<10:32, 24.12it/s]

 19%|█▊        | 3518/18769 [02:26<10:31, 24.15it/s]

 19%|█▉        | 3521/18769 [02:26<10:30, 24.20it/s]

 19%|█▉        | 3524/18769 [02:27<10:29, 24.20it/s]

 19%|█▉        | 3527/18769 [02:27<10:28, 24.26it/s]

 19%|█▉        | 3530/18769 [02:27<10:28, 24.25it/s]

 19%|█▉        | 3533/18769 [02:27<10:29, 24.19it/s]

 19%|█▉        | 3536/18769 [02:27<10:30, 24.14it/s]

 19%|█▉        | 3539/18769 [02:27<10:30, 24.14it/s]

 19%|█▉        | 3542/18769 [02:27<10:29, 24.19it/s]

 19%|█▉        | 3545/18769 [02:27<10:29, 24.20it/s]

 19%|█▉        | 3548/18769 [02:28<10:29, 24.18it/s]

 19%|█▉        | 3551/18769 [02:28<10:30, 24.14it/s]

 19%|█▉        | 3554/18769 [02:28<10:30, 24.15it/s]

 19%|█▉        | 3557/18769 [02:28<10:29, 24.18it/s]

 19%|█▉        | 3560/18769 [02:28<10:29, 24.17it/s]

 19%|█▉        | 3563/18769 [02:28<10:30, 24.11it/s]

 19%|█▉        | 3566/18769 [02:28<10:35, 23.91it/s]

 19%|█▉        | 3569/18769 [02:28<10:39, 23.77it/s]

 19%|█▉        | 3572/18769 [02:29<10:41, 23.70it/s]

 19%|█▉        | 3575/18769 [02:29<10:42, 23.64it/s]

 19%|█▉        | 3578/18769 [02:29<10:43, 23.60it/s]

 19%|█▉        | 3581/18769 [02:29<10:45, 23.53it/s]

 19%|█▉        | 3584/18769 [02:29<10:51, 23.31it/s]

 19%|█▉        | 3587/18769 [02:29<10:50, 23.33it/s]

 19%|█▉        | 3591/18769 [02:29<10:01, 25.25it/s]

 19%|█▉        | 3594/18769 [02:29<10:14, 24.71it/s]

 19%|█▉        | 3597/18769 [02:30<10:23, 24.32it/s]

 19%|█▉        | 3600/18769 [02:30<10:30, 24.06it/s]

 19%|█▉        | 3603/18769 [02:30<10:35, 23.88it/s]

 19%|█▉        | 3606/18769 [02:30<10:37, 23.78it/s]

 19%|█▉        | 3609/18769 [02:30<10:38, 23.73it/s]

 19%|█▉        | 3612/18769 [02:30<10:40, 23.65it/s]

 19%|█▉        | 3615/18769 [02:30<10:41, 23.61it/s]

 19%|█▉        | 3618/18769 [02:30<10:39, 23.70it/s]

 19%|█▉        | 3621/18769 [02:31<10:35, 23.83it/s]

 19%|█▉        | 3624/18769 [02:31<10:32, 23.95it/s]

 19%|█▉        | 3627/18769 [02:31<10:30, 24.01it/s]

 19%|█▉        | 3630/18769 [02:31<10:29, 24.03it/s]

 19%|█▉        | 3633/18769 [02:31<10:29, 24.05it/s]

 19%|█▉        | 3636/18769 [02:31<10:29, 24.05it/s]

 19%|█▉        | 3639/18769 [02:31<10:28, 24.08it/s]

 19%|█▉        | 3642/18769 [02:31<10:28, 24.08it/s]

 19%|█▉        | 3645/18769 [02:32<10:28, 24.07it/s]

 19%|█▉        | 3648/18769 [02:32<10:28, 24.07it/s]

 19%|█▉        | 3651/18769 [02:32<10:28, 24.06it/s]

 19%|█▉        | 3654/18769 [02:32<10:27, 24.09it/s]

 19%|█▉        | 3657/18769 [02:32<10:27, 24.09it/s]

 20%|█▉        | 3660/18769 [02:32<10:27, 24.08it/s]

 20%|█▉        | 3663/18769 [02:32<10:27, 24.07it/s]

 20%|█▉        | 3666/18769 [02:32<10:27, 24.08it/s]

 20%|█▉        | 3669/18769 [02:33<10:26, 24.10it/s]

 20%|█▉        | 3672/18769 [02:33<10:27, 24.08it/s]

 20%|█▉        | 3675/18769 [02:33<10:26, 24.08it/s]

 20%|█▉        | 3678/18769 [02:33<10:25, 24.11it/s]

 20%|█▉        | 3681/18769 [02:33<10:25, 24.11it/s]

 20%|█▉        | 3684/18769 [02:33<10:26, 24.09it/s]

 20%|█▉        | 3687/18769 [02:33<10:26, 24.09it/s]

 20%|█▉        | 3690/18769 [02:33<10:26, 24.09it/s]

 20%|█▉        | 3693/18769 [02:34<10:25, 24.09it/s]

 20%|█▉        | 3696/18769 [02:34<10:27, 24.03it/s]

 20%|█▉        | 3699/18769 [02:34<10:26, 24.04it/s]

 20%|█▉        | 3702/18769 [02:34<10:33, 23.78it/s]

 20%|█▉        | 3705/18769 [02:34<10:39, 23.55it/s]

 20%|█▉        | 3708/18769 [02:34<10:41, 23.48it/s]

 20%|█▉        | 3711/18769 [02:34<10:41, 23.45it/s]

 20%|█▉        | 3714/18769 [02:34<10:44, 23.35it/s]

 20%|█▉        | 3717/18769 [02:35<10:44, 23.34it/s]

 20%|█▉        | 3720/18769 [02:35<10:44, 23.35it/s]

 20%|█▉        | 3723/18769 [02:35<10:47, 23.23it/s]

 20%|█▉        | 3726/18769 [02:35<10:47, 23.22it/s]

 20%|█▉        | 3730/18769 [02:35<09:58, 25.13it/s]

 20%|█▉        | 3733/18769 [02:35<10:12, 24.56it/s]

 20%|█▉        | 3736/18769 [02:35<10:22, 24.17it/s]

 20%|█▉        | 3739/18769 [02:35<10:29, 23.89it/s]

 20%|█▉        | 3742/18769 [02:36<10:35, 23.66it/s]

 20%|█▉        | 3745/18769 [02:36<10:37, 23.58it/s]

 20%|█▉        | 3748/18769 [02:36<10:38, 23.54it/s]

 20%|█▉        | 3751/18769 [02:36<10:38, 23.53it/s]

 20%|██        | 3754/18769 [02:36<10:36, 23.58it/s]

 20%|██        | 3757/18769 [02:36<10:31, 23.78it/s]

 20%|██        | 3760/18769 [02:36<10:27, 23.91it/s]

 20%|██        | 3763/18769 [02:37<10:25, 23.99it/s]

 20%|██        | 3766/18769 [02:37<10:23, 24.08it/s]

 20%|██        | 3769/18769 [02:37<10:21, 24.13it/s]

 20%|██        | 3772/18769 [02:37<10:21, 24.13it/s]

 20%|██        | 3775/18769 [02:37<10:20, 24.17it/s]

 20%|██        | 3778/18769 [02:37<10:21, 24.14it/s]

 20%|██        | 3781/18769 [02:37<10:21, 24.11it/s]

 20%|██        | 3784/18769 [02:37<10:20, 24.16it/s]

 20%|██        | 3787/18769 [02:37<10:19, 24.18it/s]

 20%|██        | 3790/18769 [02:38<10:21, 24.11it/s]

 20%|██        | 3793/18769 [02:38<10:20, 24.12it/s]

 20%|██        | 3796/18769 [02:38<10:20, 24.15it/s]

 20%|██        | 3799/18769 [02:38<10:20, 24.14it/s]

 20%|██        | 3802/18769 [02:38<10:20, 24.14it/s]

 20%|██        | 3805/18769 [02:38<10:20, 24.13it/s]

 20%|██        | 3808/18769 [02:38<10:20, 24.12it/s]

 20%|██        | 3811/18769 [02:38<10:20, 24.12it/s]

 20%|██        | 3814/18769 [02:39<10:20, 24.10it/s]

 20%|██        | 3817/18769 [02:39<10:20, 24.11it/s]

 20%|██        | 3820/18769 [02:39<10:19, 24.12it/s]

 20%|██        | 3823/18769 [02:39<10:19, 24.11it/s]

 20%|██        | 3826/18769 [02:39<10:20, 24.09it/s]

 20%|██        | 3829/18769 [02:39<10:19, 24.12it/s]

 20%|██        | 3832/18769 [02:39<10:18, 24.14it/s]

 20%|██        | 3835/18769 [02:39<10:18, 24.14it/s]

 20%|██        | 3838/18769 [02:40<10:23, 23.95it/s]

 20%|██        | 3841/18769 [02:40<10:28, 23.75it/s]

 20%|██        | 3844/18769 [02:40<10:31, 23.62it/s]

 20%|██        | 3847/18769 [02:40<10:33, 23.57it/s]

 21%|██        | 3850/18769 [02:40<10:34, 23.51it/s]

 21%|██        | 3853/18769 [02:40<10:35, 23.47it/s]

 21%|██        | 3856/18769 [02:40<10:35, 23.47it/s]

 21%|██        | 3859/18769 [02:41<10:36, 23.43it/s]

 21%|██        | 3862/18769 [02:41<10:37, 23.39it/s]

 21%|██        | 3866/18769 [02:41<09:50, 25.26it/s]

 21%|██        | 3869/18769 [02:41<10:04, 24.66it/s]

 21%|██        | 3872/18769 [02:41<10:13, 24.28it/s]

 21%|██        | 3875/18769 [02:41<10:20, 23.99it/s]

 21%|██        | 3878/18769 [02:41<10:26, 23.78it/s]

 21%|██        | 3881/18769 [02:41<10:29, 23.66it/s]

 21%|██        | 3884/18769 [02:42<10:30, 23.62it/s]

 21%|██        | 3887/18769 [02:42<10:32, 23.53it/s]

 21%|██        | 3890/18769 [02:42<10:33, 23.50it/s]

 21%|██        | 3893/18769 [02:42<10:27, 23.69it/s]

 21%|██        | 3896/18769 [02:42<10:23, 23.86it/s]

 21%|██        | 3899/18769 [02:42<10:21, 23.92it/s]

 21%|██        | 3902/18769 [02:42<10:20, 23.97it/s]

 21%|██        | 3905/18769 [02:42<10:18, 24.04it/s]

 21%|██        | 3908/18769 [02:43<10:17, 24.07it/s]

 21%|██        | 3911/18769 [02:43<10:17, 24.08it/s]

 21%|██        | 3914/18769 [02:43<10:27, 23.66it/s]

 21%|██        | 3917/18769 [02:43<10:26, 23.72it/s]

 21%|██        | 3920/18769 [02:43<10:22, 23.84it/s]

 21%|██        | 3923/18769 [02:43<10:20, 23.94it/s]

 21%|██        | 3926/18769 [02:43<10:18, 23.98it/s]

 21%|██        | 3929/18769 [02:43<10:17, 24.03it/s]

 21%|██        | 3932/18769 [02:44<10:16, 24.05it/s]

 21%|██        | 3935/18769 [02:44<10:17, 24.02it/s]

 21%|██        | 3938/18769 [02:44<10:17, 24.02it/s]

 21%|██        | 3941/18769 [02:44<10:15, 24.09it/s]

 21%|██        | 3944/18769 [02:44<10:16, 24.06it/s]

 21%|██        | 3947/18769 [02:44<10:16, 24.05it/s]

 21%|██        | 3950/18769 [02:44<10:16, 24.02it/s]

 21%|██        | 3953/18769 [02:44<10:15, 24.09it/s]

 21%|██        | 3956/18769 [02:45<10:14, 24.12it/s]

 21%|██        | 3959/18769 [02:45<10:15, 24.08it/s]

 21%|██        | 3962/18769 [02:45<10:14, 24.11it/s]

 21%|██        | 3965/18769 [02:45<10:14, 24.10it/s]

 21%|██        | 3968/18769 [02:45<10:15, 24.07it/s]

 21%|██        | 3971/18769 [02:45<10:15, 24.05it/s]

 21%|██        | 3974/18769 [02:45<10:16, 23.98it/s]

 21%|██        | 3977/18769 [02:45<10:22, 23.78it/s]

 21%|██        | 3980/18769 [02:46<10:24, 23.69it/s]

 21%|██        | 3983/18769 [02:46<10:27, 23.55it/s]

 21%|██        | 3986/18769 [02:46<10:32, 23.39it/s]

 21%|██▏       | 3989/18769 [02:46<10:31, 23.39it/s]

 21%|██▏       | 3992/18769 [02:46<10:31, 23.41it/s]

 21%|██▏       | 3995/18769 [02:46<10:34, 23.29it/s]

 21%|██▏       | 3998/18769 [02:46<10:33, 23.33it/s]

 21%|██▏       | 4001/18769 [02:46<10:32, 23.36it/s]

 21%|██▏       | 4005/18769 [02:47<09:43, 25.31it/s]

 21%|██▏       | 4008/18769 [02:47<09:58, 24.68it/s]

 21%|██▏       | 4011/18769 [02:47<10:08, 24.23it/s]

 21%|██▏       | 4014/18769 [02:47<10:17, 23.89it/s]

 21%|██▏       | 4017/18769 [02:47<10:22, 23.70it/s]

 21%|██▏       | 4020/18769 [02:47<10:27, 23.51it/s]

 21%|██▏       | 4023/18769 [02:47<10:29, 23.43it/s]

 21%|██▏       | 4026/18769 [02:47<10:33, 23.28it/s]

 21%|██▏       | 4029/18769 [02:48<10:31, 23.35it/s]

 21%|██▏       | 4032/18769 [02:48<10:27, 23.48it/s]

 21%|██▏       | 4035/18769 [02:48<10:23, 23.64it/s]

 22%|██▏       | 4038/18769 [02:48<10:20, 23.74it/s]

 22%|██▏       | 4041/18769 [02:48<10:18, 23.82it/s]

 22%|██▏       | 4044/18769 [02:48<10:19, 23.77it/s]

 22%|██▏       | 4047/18769 [02:48<10:16, 23.87it/s]

 22%|██▏       | 4050/18769 [02:48<10:14, 23.95it/s]

 22%|██▏       | 4053/18769 [02:49<10:12, 24.02it/s]

 22%|██▏       | 4056/18769 [02:49<10:12, 24.03it/s]

 22%|██▏       | 4059/18769 [02:49<10:10, 24.08it/s]

 22%|██▏       | 4062/18769 [02:49<10:10, 24.08it/s]

 22%|██▏       | 4065/18769 [02:49<10:11, 24.05it/s]

 22%|██▏       | 4068/18769 [02:49<10:10, 24.06it/s]

 22%|██▏       | 4071/18769 [02:49<10:09, 24.11it/s]

 22%|██▏       | 4074/18769 [02:49<10:09, 24.10it/s]

 22%|██▏       | 4077/18769 [02:50<10:09, 24.10it/s]

 22%|██▏       | 4080/18769 [02:50<10:09, 24.12it/s]

 22%|██▏       | 4083/18769 [02:50<10:08, 24.13it/s]

 22%|██▏       | 4086/18769 [02:50<10:08, 24.14it/s]

 22%|██▏       | 4089/18769 [02:50<10:08, 24.14it/s]

 22%|██▏       | 4092/18769 [02:50<10:11, 24.00it/s]

 22%|██▏       | 4095/18769 [02:50<10:10, 24.05it/s]

 22%|██▏       | 4098/18769 [02:50<10:08, 24.11it/s]

 22%|██▏       | 4101/18769 [02:51<10:08, 24.12it/s]

 22%|██▏       | 4104/18769 [02:51<10:08, 24.09it/s]

 22%|██▏       | 4107/18769 [02:51<10:09, 24.04it/s]

 22%|██▏       | 4110/18769 [02:51<10:09, 24.05it/s]

 22%|██▏       | 4113/18769 [02:51<10:15, 23.81it/s]

 22%|██▏       | 4116/18769 [02:51<10:19, 23.67it/s]

 22%|██▏       | 4119/18769 [02:51<10:21, 23.58it/s]

 22%|██▏       | 4122/18769 [02:51<10:22, 23.53it/s]

 22%|██▏       | 4125/18769 [02:52<10:24, 23.44it/s]

 22%|██▏       | 4128/18769 [02:52<10:25, 23.41it/s]

 22%|██▏       | 4131/18769 [02:52<10:25, 23.40it/s]

 22%|██▏       | 4134/18769 [02:52<10:25, 23.40it/s]

 22%|██▏       | 4137/18769 [02:52<10:25, 23.40it/s]

 22%|██▏       | 4140/18769 [02:52<10:30, 23.21it/s]

 22%|██▏       | 4144/18769 [02:52<09:41, 25.15it/s]

 22%|██▏       | 4147/18769 [02:53<09:54, 24.59it/s]

 22%|██▏       | 4150/18769 [02:53<10:01, 24.28it/s]

 22%|██▏       | 4153/18769 [02:53<10:08, 24.01it/s]

 22%|██▏       | 4156/18769 [02:53<10:12, 23.87it/s]

 22%|██▏       | 4159/18769 [02:53<10:15, 23.75it/s]

 22%|██▏       | 4162/18769 [02:53<10:16, 23.68it/s]

 22%|██▏       | 4165/18769 [02:53<10:17, 23.65it/s]

 22%|██▏       | 4168/18769 [02:53<10:13, 23.80it/s]

 22%|██▏       | 4171/18769 [02:54<10:10, 23.91it/s]

 22%|██▏       | 4174/18769 [02:54<10:08, 23.98it/s]

 22%|██▏       | 4177/18769 [02:54<10:06, 24.04it/s]

 22%|██▏       | 4180/18769 [02:54<10:05, 24.10it/s]

 22%|██▏       | 4183/18769 [02:54<10:06, 24.06it/s]

 22%|██▏       | 4186/18769 [02:54<10:05, 24.08it/s]

 22%|██▏       | 4189/18769 [02:54<10:05, 24.06it/s]

 22%|██▏       | 4192/18769 [02:54<10:05, 24.08it/s]

 22%|██▏       | 4195/18769 [02:55<10:03, 24.16it/s]

 22%|██▏       | 4198/18769 [02:55<10:02, 24.20it/s]

 22%|██▏       | 4201/18769 [02:55<10:03, 24.15it/s]

 22%|██▏       | 4204/18769 [02:55<10:03, 24.14it/s]

 22%|██▏       | 4207/18769 [02:55<10:02, 24.16it/s]

 22%|██▏       | 4210/18769 [02:55<10:02, 24.18it/s]

 22%|██▏       | 4213/18769 [02:55<10:02, 24.14it/s]

 22%|██▏       | 4216/18769 [02:55<10:02, 24.16it/s]

 22%|██▏       | 4219/18769 [02:56<10:02, 24.14it/s]

 22%|██▏       | 4222/18769 [02:56<10:02, 24.14it/s]

 23%|██▎       | 4225/18769 [02:56<10:02, 24.14it/s]

 23%|██▎       | 4228/18769 [02:56<10:00, 24.20it/s]

 23%|██▎       | 4231/18769 [02:56<10:00, 24.21it/s]

 23%|██▎       | 4234/18769 [02:56<10:00, 24.21it/s]

 23%|██▎       | 4237/18769 [02:56<10:00, 24.20it/s]

 23%|██▎       | 4240/18769 [02:56<09:59, 24.23it/s]

 23%|██▎       | 4243/18769 [02:57<09:59, 24.24it/s]

 23%|██▎       | 4246/18769 [02:57<09:59, 24.22it/s]

 23%|██▎       | 4249/18769 [02:57<10:02, 24.09it/s]

 23%|██▎       | 4252/18769 [02:57<10:07, 23.91it/s]

 23%|██▎       | 4255/18769 [02:57<10:10, 23.78it/s]

 23%|██▎       | 4258/18769 [02:57<10:12, 23.70it/s]

 23%|██▎       | 4261/18769 [02:57<10:14, 23.62it/s]

 23%|██▎       | 4264/18769 [02:57<10:14, 23.59it/s]

 23%|██▎       | 4267/18769 [02:58<10:16, 23.52it/s]

 23%|██▎       | 4270/18769 [02:58<10:16, 23.51it/s]

 23%|██▎       | 4273/18769 [02:58<10:20, 23.36it/s]

 23%|██▎       | 4276/18769 [02:58<10:18, 23.42it/s]

 23%|██▎       | 4280/18769 [02:58<09:31, 25.34it/s]

 23%|██▎       | 4283/18769 [02:58<09:45, 24.74it/s]

 23%|██▎       | 4286/18769 [02:58<09:54, 24.35it/s]

 23%|██▎       | 4289/18769 [02:58<10:01, 24.05it/s]

 23%|██▎       | 4292/18769 [02:59<10:05, 23.90it/s]

 23%|██▎       | 4295/18769 [02:59<10:08, 23.78it/s]

 23%|██▎       | 4298/18769 [02:59<10:10, 23.70it/s]

 23%|██▎       | 4301/18769 [02:59<10:13, 23.60it/s]

 23%|██▎       | 4304/18769 [02:59<10:08, 23.78it/s]

 23%|██▎       | 4307/18769 [02:59<10:05, 23.87it/s]

 23%|██▎       | 4310/18769 [02:59<10:04, 23.94it/s]

 23%|██▎       | 4313/18769 [02:59<10:03, 23.96it/s]

 23%|██▎       | 4316/18769 [03:00<10:01, 24.02it/s]

 23%|██▎       | 4319/18769 [03:00<10:01, 24.03it/s]

 23%|██▎       | 4322/18769 [03:00<10:02, 23.98it/s]

 23%|██▎       | 4325/18769 [03:00<10:00, 24.06it/s]

 23%|██▎       | 4328/18769 [03:00<10:00, 24.05it/s]

 23%|██▎       | 4331/18769 [03:00<10:00, 24.04it/s]

 23%|██▎       | 4334/18769 [03:00<10:01, 24.02it/s]

 23%|██▎       | 4337/18769 [03:00<10:00, 24.02it/s]

 23%|██▎       | 4340/18769 [03:01<10:00, 24.01it/s]

 23%|██▎       | 4343/18769 [03:01<10:08, 23.72it/s]

 23%|██▎       | 4346/18769 [03:01<10:09, 23.65it/s]

 23%|██▎       | 4349/18769 [03:01<10:08, 23.71it/s]

 23%|██▎       | 4352/18769 [03:01<10:04, 23.83it/s]

 23%|██▎       | 4355/18769 [03:01<10:03, 23.87it/s]

 23%|██▎       | 4358/18769 [03:01<10:02, 23.93it/s]

 23%|██▎       | 4361/18769 [03:01<10:00, 23.99it/s]

 23%|██▎       | 4364/18769 [03:02<09:59, 24.04it/s]

 23%|██▎       | 4367/18769 [03:02<09:58, 24.07it/s]

 23%|██▎       | 4370/18769 [03:02<09:58, 24.06it/s]

 23%|██▎       | 4373/18769 [03:02<09:58, 24.05it/s]

 23%|██▎       | 4376/18769 [03:02<09:57, 24.10it/s]

 23%|██▎       | 4379/18769 [03:02<09:57, 24.08it/s]

 23%|██▎       | 4382/18769 [03:02<10:03, 23.82it/s]

 23%|██▎       | 4385/18769 [03:02<10:05, 23.77it/s]

 23%|██▎       | 4388/18769 [03:03<10:09, 23.59it/s]

 23%|██▎       | 4391/18769 [03:03<10:12, 23.46it/s]

 23%|██▎       | 4394/18769 [03:03<10:16, 23.31it/s]

 23%|██▎       | 4397/18769 [03:03<10:19, 23.19it/s]

 23%|██▎       | 4400/18769 [03:03<10:20, 23.16it/s]

 23%|██▎       | 4403/18769 [03:03<10:20, 23.16it/s]

 23%|██▎       | 4406/18769 [03:03<10:19, 23.18it/s]

 23%|██▎       | 4409/18769 [03:03<10:19, 23.20it/s]

 24%|██▎       | 4412/18769 [03:04<10:21, 23.11it/s]

 24%|██▎       | 4415/18769 [03:04<10:23, 23.01it/s]

 24%|██▎       | 4419/18769 [03:04<09:35, 24.94it/s]

 24%|██▎       | 4422/18769 [03:04<09:48, 24.40it/s]

 24%|██▎       | 4425/18769 [03:04<09:57, 23.99it/s]

 24%|██▎       | 4428/18769 [03:04<10:07, 23.61it/s]

 24%|██▎       | 4431/18769 [03:04<10:09, 23.52it/s]

 24%|██▎       | 4434/18769 [03:05<10:10, 23.49it/s]

 24%|██▎       | 4437/18769 [03:05<10:11, 23.42it/s]

 24%|██▎       | 4440/18769 [03:05<10:08, 23.55it/s]

 24%|██▎       | 4443/18769 [03:05<10:06, 23.64it/s]

 24%|██▎       | 4446/18769 [03:05<10:03, 23.75it/s]

 24%|██▎       | 4449/18769 [03:05<10:01, 23.83it/s]

 24%|██▎       | 4452/18769 [03:05<09:59, 23.87it/s]

 24%|██▎       | 4455/18769 [03:05<09:58, 23.93it/s]

 24%|██▍       | 4458/18769 [03:06<09:57, 23.94it/s]

 24%|██▍       | 4461/18769 [03:06<09:58, 23.90it/s]

 24%|██▍       | 4464/18769 [03:06<09:58, 23.90it/s]

 24%|██▍       | 4467/18769 [03:06<10:00, 23.83it/s]

 24%|██▍       | 4470/18769 [03:06<09:58, 23.89it/s]

 24%|██▍       | 4473/18769 [03:06<09:59, 23.86it/s]

 24%|██▍       | 4476/18769 [03:06<10:01, 23.78it/s]

 24%|██▍       | 4479/18769 [03:06<09:58, 23.86it/s]

 24%|██▍       | 4482/18769 [03:07<09:57, 23.92it/s]

 24%|██▍       | 4485/18769 [03:07<09:58, 23.88it/s]

 24%|██▍       | 4488/18769 [03:07<09:58, 23.87it/s]

 24%|██▍       | 4491/18769 [03:07<09:58, 23.86it/s]

 24%|██▍       | 4494/18769 [03:07<09:58, 23.86it/s]

 24%|██▍       | 4497/18769 [03:07<09:57, 23.90it/s]

 24%|██▍       | 4500/18769 [03:07<09:55, 23.96it/s]

 24%|██▍       | 4503/18769 [03:07<09:55, 23.96it/s]

 24%|██▍       | 4506/18769 [03:08<09:56, 23.92it/s]

 24%|██▍       | 4509/18769 [03:08<09:56, 23.89it/s]

 24%|██▍       | 4512/18769 [03:08<09:55, 23.92it/s]

 24%|██▍       | 4515/18769 [03:08<09:55, 23.94it/s]

 24%|██▍       | 4518/18769 [03:08<09:54, 23.99it/s]

 24%|██▍       | 4521/18769 [03:08<09:53, 24.00it/s]

 24%|██▍       | 4524/18769 [03:08<09:58, 23.78it/s]

 24%|██▍       | 4527/18769 [03:08<10:01, 23.67it/s]

 24%|██▍       | 4530/18769 [03:09<10:03, 23.61it/s]

 24%|██▍       | 4533/18769 [03:09<10:05, 23.53it/s]

 24%|██▍       | 4536/18769 [03:09<10:06, 23.46it/s]

 24%|██▍       | 4539/18769 [03:09<10:07, 23.42it/s]

 24%|██▍       | 4542/18769 [03:09<10:07, 23.40it/s]

 24%|██▍       | 4545/18769 [03:09<10:07, 23.42it/s]

 24%|██▍       | 4548/18769 [03:09<10:07, 23.42it/s]

 24%|██▍       | 4551/18769 [03:09<10:06, 23.44it/s]

 24%|██▍       | 4554/18769 [03:10<10:07, 23.40it/s]

 24%|██▍       | 4558/18769 [03:10<09:21, 25.29it/s]

 24%|██▍       | 4561/18769 [03:10<09:39, 24.53it/s]

 24%|██▍       | 4564/18769 [03:10<09:48, 24.12it/s]

 24%|██▍       | 4567/18769 [03:10<09:54, 23.90it/s]

 24%|██▍       | 4570/18769 [03:10<09:59, 23.70it/s]

 24%|██▍       | 4573/18769 [03:10<10:05, 23.44it/s]

 24%|██▍       | 4576/18769 [03:10<10:06, 23.41it/s]

 24%|██▍       | 4579/18769 [03:11<10:01, 23.59it/s]

 24%|██▍       | 4582/18769 [03:11<09:58, 23.70it/s]

 24%|██▍       | 4585/18769 [03:11<09:55, 23.81it/s]

 24%|██▍       | 4588/18769 [03:11<09:54, 23.86it/s]

 24%|██▍       | 4591/18769 [03:11<09:53, 23.91it/s]

 24%|██▍       | 4594/18769 [03:11<09:52, 23.93it/s]

 24%|██▍       | 4597/18769 [03:11<09:51, 23.96it/s]

 25%|██▍       | 4600/18769 [03:11<09:49, 24.04it/s]

 25%|██▍       | 4603/18769 [03:12<09:48, 24.05it/s]

 25%|██▍       | 4606/18769 [03:12<09:53, 23.86it/s]

 25%|██▍       | 4609/18769 [03:12<09:57, 23.68it/s]

 25%|██▍       | 4612/18769 [03:12<09:58, 23.65it/s]

 25%|██▍       | 4615/18769 [03:12<10:06, 23.33it/s]

 25%|██▍       | 4618/18769 [03:12<10:07, 23.28it/s]

 25%|██▍       | 4621/18769 [03:12<10:08, 23.26it/s]

 25%|██▍       | 4624/18769 [03:13<10:05, 23.37it/s]

 25%|██▍       | 4627/18769 [03:13<09:59, 23.58it/s]

 25%|██▍       | 4630/18769 [03:13<09:56, 23.70it/s]

 25%|██▍       | 4633/18769 [03:13<09:54, 23.79it/s]

 25%|██▍       | 4636/18769 [03:13<09:52, 23.86it/s]

 25%|██▍       | 4639/18769 [03:13<09:50, 23.91it/s]

 25%|██▍       | 4642/18769 [03:13<09:49, 23.96it/s]

 25%|██▍       | 4645/18769 [03:13<09:48, 23.99it/s]

 25%|██▍       | 4648/18769 [03:14<09:48, 24.01it/s]

 25%|██▍       | 4651/18769 [03:14<09:48, 24.01it/s]

 25%|██▍       | 4654/18769 [03:14<09:48, 24.00it/s]

 25%|██▍       | 4657/18769 [03:14<09:47, 24.01it/s]

 25%|██▍       | 4660/18769 [03:14<09:51, 23.87it/s]

 25%|██▍       | 4663/18769 [03:14<09:54, 23.71it/s]

 25%|██▍       | 4666/18769 [03:14<09:58, 23.57it/s]

 25%|██▍       | 4669/18769 [03:14<09:59, 23.52it/s]

 25%|██▍       | 4672/18769 [03:15<10:00, 23.46it/s]

 25%|██▍       | 4675/18769 [03:15<10:02, 23.39it/s]

 25%|██▍       | 4678/18769 [03:15<10:02, 23.38it/s]

 25%|██▍       | 4681/18769 [03:15<10:04, 23.32it/s]

 25%|██▍       | 4684/18769 [03:15<10:04, 23.30it/s]

 25%|██▍       | 4687/18769 [03:15<10:03, 23.32it/s]

 25%|██▍       | 4690/18769 [03:15<10:03, 23.34it/s]

 25%|██▌       | 4694/18769 [03:15<09:18, 25.21it/s]

 25%|██▌       | 4697/18769 [03:16<09:45, 24.05it/s]

 25%|██▌       | 4700/18769 [03:16<10:00, 23.44it/s]

 25%|██▌       | 4703/18769 [03:16<10:01, 23.38it/s]

 25%|██▌       | 4706/18769 [03:16<10:02, 23.34it/s]

 25%|██▌       | 4709/18769 [03:16<10:02, 23.35it/s]

 25%|██▌       | 4712/18769 [03:16<10:00, 23.40it/s]

 25%|██▌       | 4715/18769 [03:16<09:55, 23.61it/s]

 25%|██▌       | 4718/18769 [03:16<09:50, 23.78it/s]

 25%|██▌       | 4721/18769 [03:17<09:48, 23.88it/s]

 25%|██▌       | 4724/18769 [03:17<09:47, 23.92it/s]

 25%|██▌       | 4727/18769 [03:17<09:45, 23.99it/s]

 25%|██▌       | 4730/18769 [03:17<09:44, 24.03it/s]

 25%|██▌       | 4733/18769 [03:17<09:42, 24.08it/s]

 25%|██▌       | 4736/18769 [03:17<09:42, 24.10it/s]

 25%|██▌       | 4739/18769 [03:17<09:41, 24.11it/s]

 25%|██▌       | 4742/18769 [03:17<09:41, 24.11it/s]

 25%|██▌       | 4745/18769 [03:18<09:41, 24.12it/s]

 25%|██▌       | 4748/18769 [03:18<09:41, 24.11it/s]

 25%|██▌       | 4751/18769 [03:18<09:41, 24.10it/s]

 25%|██▌       | 4754/18769 [03:18<09:42, 24.07it/s]

 25%|██▌       | 4757/18769 [03:18<09:42, 24.07it/s]

 25%|██▌       | 4760/18769 [03:18<09:41, 24.10it/s]

 25%|██▌       | 4763/18769 [03:18<09:41, 24.08it/s]

 25%|██▌       | 4766/18769 [03:18<09:42, 24.05it/s]

 25%|██▌       | 4769/18769 [03:19<09:41, 24.07it/s]

 25%|██▌       | 4772/18769 [03:19<09:41, 24.08it/s]

 25%|██▌       | 4775/18769 [03:19<09:41, 24.07it/s]

 25%|██▌       | 4778/18769 [03:19<09:41, 24.06it/s]

 25%|██▌       | 4781/18769 [03:19<09:41, 24.04it/s]

 25%|██▌       | 4784/18769 [03:19<09:41, 24.05it/s]

 26%|██▌       | 4787/18769 [03:19<09:40, 24.10it/s]

 26%|██▌       | 4790/18769 [03:19<09:39, 24.11it/s]

 26%|██▌       | 4793/18769 [03:20<09:39, 24.10it/s]

 26%|██▌       | 4796/18769 [03:20<09:42, 24.00it/s]

 26%|██▌       | 4799/18769 [03:20<09:47, 23.79it/s]

 26%|██▌       | 4802/18769 [03:20<09:50, 23.64it/s]

 26%|██▌       | 4805/18769 [03:20<09:52, 23.56it/s]

 26%|██▌       | 4808/18769 [03:20<09:54, 23.47it/s]

 26%|██▌       | 4811/18769 [03:20<09:55, 23.42it/s]

 26%|██▌       | 4814/18769 [03:20<09:55, 23.41it/s]

 26%|██▌       | 4817/18769 [03:21<09:56, 23.39it/s]

 26%|██▌       | 4820/18769 [03:21<09:56, 23.38it/s]

 26%|██▌       | 4823/18769 [03:21<09:57, 23.35it/s]

 26%|██▌       | 4826/18769 [03:21<09:57, 23.33it/s]

 26%|██▌       | 4829/18769 [03:21<09:58, 23.28it/s]

 26%|██▌       | 4833/18769 [03:21<09:14, 25.15it/s]

 26%|██▌       | 4836/18769 [03:21<09:27, 24.57it/s]

 26%|██▌       | 4839/18769 [03:22<09:35, 24.19it/s]

 26%|██▌       | 4842/18769 [03:22<09:42, 23.92it/s]

 26%|██▌       | 4845/18769 [03:22<09:46, 23.75it/s]

 26%|██▌       | 4848/18769 [03:22<09:51, 23.53it/s]

 26%|██▌       | 4851/18769 [03:22<09:48, 23.63it/s]

 26%|██▌       | 4854/18769 [03:22<09:45, 23.76it/s]

 26%|██▌       | 4857/18769 [03:22<09:42, 23.87it/s]

 26%|██▌       | 4860/18769 [03:22<09:41, 23.94it/s]

 26%|██▌       | 4863/18769 [03:23<09:40, 23.94it/s]

 26%|██▌       | 4866/18769 [03:23<09:40, 23.95it/s]

 26%|██▌       | 4869/18769 [03:23<09:40, 23.94it/s]

 26%|██▌       | 4872/18769 [03:23<09:41, 23.92it/s]

 26%|██▌       | 4875/18769 [03:23<09:40, 23.93it/s]

 26%|██▌       | 4878/18769 [03:23<09:39, 23.96it/s]

 26%|██▌       | 4881/18769 [03:23<09:38, 23.99it/s]

 26%|██▌       | 4884/18769 [03:23<09:39, 23.97it/s]

 26%|██▌       | 4887/18769 [03:24<09:39, 23.97it/s]

 26%|██▌       | 4890/18769 [03:24<09:38, 23.99it/s]

 26%|██▌       | 4893/18769 [03:24<09:38, 24.00it/s]

 26%|██▌       | 4896/18769 [03:24<09:37, 24.04it/s]

 26%|██▌       | 4899/18769 [03:24<09:36, 24.07it/s]

 26%|██▌       | 4902/18769 [03:24<09:36, 24.07it/s]

 26%|██▌       | 4905/18769 [03:24<09:37, 24.01it/s]

 26%|██▌       | 4908/18769 [03:24<09:36, 24.04it/s]

 26%|██▌       | 4911/18769 [03:25<09:36, 24.05it/s]

 26%|██▌       | 4914/18769 [03:25<09:35, 24.08it/s]

 26%|██▌       | 4917/18769 [03:25<09:35, 24.08it/s]

 26%|██▌       | 4920/18769 [03:25<09:35, 24.07it/s]

 26%|██▌       | 4923/18769 [03:25<09:33, 24.15it/s]

 26%|██▌       | 4926/18769 [03:25<09:33, 24.15it/s]

 26%|██▋       | 4929/18769 [03:25<09:33, 24.14it/s]

 26%|██▋       | 4932/18769 [03:25<09:32, 24.16it/s]

 26%|██▋       | 4935/18769 [03:26<09:38, 23.91it/s]

 26%|██▋       | 4938/18769 [03:26<09:43, 23.72it/s]

 26%|██▋       | 4941/18769 [03:26<09:45, 23.60it/s]

 26%|██▋       | 4944/18769 [03:26<09:47, 23.53it/s]

 26%|██▋       | 4947/18769 [03:26<09:48, 23.50it/s]

 26%|██▋       | 4950/18769 [03:26<09:48, 23.47it/s]

 26%|██▋       | 4953/18769 [03:26<09:48, 23.47it/s]

 26%|██▋       | 4956/18769 [03:26<09:52, 23.32it/s]

 26%|██▋       | 4959/18769 [03:27<09:52, 23.32it/s]

 26%|██▋       | 4962/18769 [03:27<11:58, 19.21it/s]

 26%|██▋       | 4965/18769 [03:27<11:20, 20.28it/s]

 26%|██▋       | 4968/18769 [03:27<10:53, 21.11it/s]

 26%|██▋       | 4972/18769 [03:27<09:50, 23.37it/s]

 27%|██▋       | 4975/18769 [03:27<09:50, 23.35it/s]

 27%|██▋       | 4978/18769 [03:27<09:50, 23.37it/s]

 27%|██▋       | 4981/18769 [03:28<09:49, 23.39it/s]

 27%|██▋       | 4984/18769 [03:28<09:49, 23.37it/s]

 27%|██▋       | 4987/18769 [03:28<09:48, 23.42it/s]

 27%|██▋       | 4990/18769 [03:28<09:44, 23.56it/s]

 27%|██▋       | 4993/18769 [03:28<09:40, 23.72it/s]

 27%|██▋       | 4996/18769 [03:28<09:38, 23.82it/s]

 27%|██▋       | 4999/18769 [03:28<09:36, 23.88it/s]

 27%|██▋       | 5002/18769 [03:28<09:37, 23.83it/s]

 27%|██▋       | 5005/18769 [03:29<09:35, 23.92it/s]

 27%|██▋       | 5008/18769 [03:29<09:33, 23.98it/s]

 27%|██▋       | 5011/18769 [03:29<09:32, 24.05it/s]

 27%|██▋       | 5014/18769 [03:29<09:31, 24.07it/s]

 27%|██▋       | 5017/18769 [03:29<09:29, 24.13it/s]

 27%|██▋       | 5020/18769 [03:29<09:29, 24.14it/s]

 27%|██▋       | 5023/18769 [03:29<09:30, 24.10it/s]

 27%|██▋       | 5026/18769 [03:29<09:30, 24.11it/s]

 27%|██▋       | 5029/18769 [03:30<09:29, 24.12it/s]

 27%|██▋       | 5032/18769 [03:30<09:29, 24.12it/s]

 27%|██▋       | 5035/18769 [03:30<09:28, 24.14it/s]

 27%|██▋       | 5038/18769 [03:30<09:28, 24.17it/s]

 27%|██▋       | 5041/18769 [03:30<09:28, 24.13it/s]

 27%|██▋       | 5044/18769 [03:30<09:29, 24.11it/s]

 27%|██▋       | 5047/18769 [03:30<09:29, 24.12it/s]

 27%|██▋       | 5050/18769 [03:30<09:31, 24.00it/s]

 27%|██▋       | 5053/18769 [03:31<09:30, 24.03it/s]

 27%|██▋       | 5056/18769 [03:31<09:29, 24.09it/s]

 27%|██▋       | 5059/18769 [03:31<09:29, 24.08it/s]

 27%|██▋       | 5062/18769 [03:31<09:30, 24.04it/s]

 27%|██▋       | 5065/18769 [03:31<09:30, 24.03it/s]

 27%|██▋       | 5068/18769 [03:31<09:30, 24.01it/s]

 27%|██▋       | 5071/18769 [03:31<09:36, 23.77it/s]

 27%|██▋       | 5074/18769 [03:31<09:39, 23.64it/s]

 27%|██▋       | 5077/18769 [03:32<09:41, 23.55it/s]

 27%|██▋       | 5080/18769 [03:32<09:41, 23.52it/s]

 27%|██▋       | 5083/18769 [03:32<09:43, 23.45it/s]

 27%|██▋       | 5086/18769 [03:32<09:44, 23.41it/s]

 27%|██▋       | 5089/18769 [03:32<09:44, 23.42it/s]

 27%|██▋       | 5092/18769 [03:32<09:45, 23.38it/s]

 27%|██▋       | 5095/18769 [03:32<09:48, 23.23it/s]

 27%|██▋       | 5098/18769 [03:32<09:51, 23.11it/s]

 27%|██▋       | 5101/18769 [03:33<09:50, 23.16it/s]

 27%|██▋       | 5104/18769 [03:33<09:49, 23.17it/s]

 27%|██▋       | 5108/18769 [03:33<09:04, 25.09it/s]

 27%|██▋       | 5111/18769 [03:33<09:17, 24.50it/s]

 27%|██▋       | 5114/18769 [03:33<09:25, 24.16it/s]

 27%|██▋       | 5117/18769 [03:33<09:30, 23.91it/s]

 27%|██▋       | 5120/18769 [03:33<09:35, 23.73it/s]

 27%|██▋       | 5123/18769 [03:33<09:41, 23.46it/s]

 27%|██▋       | 5126/18769 [03:34<09:37, 23.62it/s]

 27%|██▋       | 5129/18769 [03:34<09:34, 23.72it/s]

 27%|██▋       | 5132/18769 [03:34<09:35, 23.68it/s]

 27%|██▋       | 5135/18769 [03:34<09:32, 23.81it/s]

 27%|██▋       | 5138/18769 [03:34<09:30, 23.90it/s]

 27%|██▋       | 5141/18769 [03:34<09:28, 23.97it/s]

 27%|██▋       | 5144/18769 [03:34<09:28, 23.96it/s]

 27%|██▋       | 5147/18769 [03:34<09:27, 23.99it/s]

 27%|██▋       | 5150/18769 [03:35<09:27, 23.98it/s]

 27%|██▋       | 5153/18769 [03:35<09:29, 23.92it/s]

 27%|██▋       | 5156/18769 [03:35<09:29, 23.89it/s]

 27%|██▋       | 5159/18769 [03:35<09:30, 23.85it/s]

 28%|██▊       | 5162/18769 [03:35<09:29, 23.87it/s]

 28%|██▊       | 5165/18769 [03:35<09:28, 23.91it/s]

 28%|██▊       | 5168/18769 [03:35<09:27, 23.96it/s]

 28%|██▊       | 5171/18769 [03:35<09:30, 23.83it/s]

 28%|██▊       | 5174/18769 [03:36<09:30, 23.84it/s]

 28%|██▊       | 5177/18769 [03:36<09:30, 23.81it/s]

 28%|██▊       | 5180/18769 [03:36<09:29, 23.86it/s]

 28%|██▊       | 5183/18769 [03:36<09:28, 23.88it/s]

 28%|██▊       | 5186/18769 [03:36<09:27, 23.96it/s]

 28%|██▊       | 5189/18769 [03:36<09:25, 24.00it/s]

 28%|██▊       | 5192/18769 [03:36<09:25, 24.03it/s]

 28%|██▊       | 5195/18769 [03:36<09:24, 24.03it/s]

 28%|██▊       | 5198/18769 [03:37<09:23, 24.08it/s]

 28%|██▊       | 5201/18769 [03:37<09:23, 24.07it/s]

 28%|██▊       | 5204/18769 [03:37<09:24, 24.03it/s]

 28%|██▊       | 5207/18769 [03:37<09:26, 23.96it/s]

 28%|██▊       | 5210/18769 [03:37<09:31, 23.73it/s]

 28%|██▊       | 5213/18769 [03:37<09:34, 23.60it/s]

 28%|██▊       | 5216/18769 [03:37<09:36, 23.52it/s]

 28%|██▊       | 5219/18769 [03:37<09:38, 23.43it/s]

 28%|██▊       | 5222/18769 [03:38<09:38, 23.43it/s]

 28%|██▊       | 5225/18769 [03:38<09:38, 23.39it/s]

 28%|██▊       | 5228/18769 [03:38<09:38, 23.39it/s]

 28%|██▊       | 5231/18769 [03:38<09:39, 23.37it/s]

 28%|██▊       | 5234/18769 [03:38<09:39, 23.37it/s]

 28%|██▊       | 5237/18769 [03:38<09:38, 23.40it/s]

 28%|██▊       | 5240/18769 [03:38<09:38, 23.37it/s]

 28%|██▊       | 5243/18769 [03:39<09:41, 23.25it/s]

 28%|██▊       | 5247/18769 [03:39<08:57, 25.14it/s]

 28%|██▊       | 5250/18769 [03:39<09:10, 24.57it/s]

 28%|██▊       | 5253/18769 [03:39<09:19, 24.15it/s]

 28%|██▊       | 5256/18769 [03:39<09:25, 23.91it/s]

 28%|██▊       | 5259/18769 [03:39<09:29, 23.72it/s]

 28%|██▊       | 5262/18769 [03:39<09:29, 23.70it/s]

 28%|██▊       | 5265/18769 [03:39<09:27, 23.78it/s]

 28%|██▊       | 5268/18769 [03:40<09:25, 23.87it/s]

 28%|██▊       | 5271/18769 [03:40<09:25, 23.88it/s]

 28%|██▊       | 5274/18769 [03:40<09:23, 23.93it/s]

 28%|██▊       | 5277/18769 [03:40<09:25, 23.87it/s]

 28%|██▊       | 5280/18769 [03:40<09:23, 23.94it/s]

 28%|██▊       | 5283/18769 [03:40<09:21, 24.01it/s]

 28%|██▊       | 5286/18769 [03:40<09:20, 24.07it/s]

 28%|██▊       | 5289/18769 [03:40<09:18, 24.12it/s]

 28%|██▊       | 5292/18769 [03:41<09:18, 24.14it/s]

 28%|██▊       | 5295/18769 [03:41<09:19, 24.10it/s]

 28%|██▊       | 5298/18769 [03:41<09:18, 24.11it/s]

 28%|██▊       | 5301/18769 [03:41<09:18, 24.12it/s]

 28%|██▊       | 5304/18769 [03:41<09:18, 24.12it/s]

 28%|██▊       | 5307/18769 [03:41<09:18, 24.13it/s]

 28%|██▊       | 5310/18769 [03:41<09:18, 24.12it/s]

 28%|██▊       | 5313/18769 [03:41<09:17, 24.12it/s]

 28%|██▊       | 5316/18769 [03:42<09:18, 24.10it/s]

 28%|██▊       | 5319/18769 [03:42<09:18, 24.07it/s]

 28%|██▊       | 5322/18769 [03:42<09:18, 24.08it/s]

 28%|██▊       | 5325/18769 [03:42<09:18, 24.09it/s]

 28%|██▊       | 5328/18769 [03:42<09:17, 24.09it/s]

 28%|██▊       | 5331/18769 [03:42<09:18, 24.07it/s]

 28%|██▊       | 5334/18769 [03:42<09:18, 24.07it/s]

 28%|██▊       | 5337/18769 [03:42<09:18, 24.05it/s]

 28%|██▊       | 5340/18769 [03:43<09:19, 24.02it/s]

 28%|██▊       | 5343/18769 [03:43<09:18, 24.03it/s]

 28%|██▊       | 5346/18769 [03:43<09:28, 23.62it/s]

 28%|██▊       | 5349/18769 [03:43<09:30, 23.53it/s]

 29%|██▊       | 5352/18769 [03:43<09:31, 23.49it/s]

 29%|██▊       | 5355/18769 [03:43<09:31, 23.45it/s]

 29%|██▊       | 5358/18769 [03:43<09:31, 23.45it/s]

 29%|██▊       | 5361/18769 [03:43<09:31, 23.47it/s]

 29%|██▊       | 5364/18769 [03:44<09:31, 23.46it/s]

 29%|██▊       | 5367/18769 [03:44<09:32, 23.41it/s]

 29%|██▊       | 5370/18769 [03:44<09:32, 23.42it/s]

 29%|██▊       | 5373/18769 [03:44<09:31, 23.43it/s]

 29%|██▊       | 5376/18769 [03:44<09:31, 23.42it/s]

 29%|██▊       | 5379/18769 [03:44<09:31, 23.43it/s]

 29%|██▊       | 5382/18769 [03:44<09:32, 23.40it/s]

 29%|██▊       | 5386/18769 [03:44<08:49, 25.29it/s]

 29%|██▊       | 5389/18769 [03:45<09:05, 24.51it/s]

 29%|██▊       | 5392/18769 [03:45<09:13, 24.17it/s]

 29%|██▊       | 5395/18769 [03:45<09:18, 23.94it/s]

 29%|██▉       | 5398/18769 [03:45<09:20, 23.88it/s]

 29%|██▉       | 5401/18769 [03:45<09:17, 23.96it/s]

 29%|██▉       | 5404/18769 [03:45<09:17, 23.96it/s]

 29%|██▉       | 5407/18769 [03:45<09:16, 24.01it/s]

 29%|██▉       | 5410/18769 [03:45<09:16, 24.02it/s]

 29%|██▉       | 5413/18769 [03:46<09:15, 24.04it/s]

 29%|██▉       | 5416/18769 [03:46<09:14, 24.06it/s]

 29%|██▉       | 5419/18769 [03:46<09:14, 24.09it/s]

 29%|██▉       | 5422/18769 [03:46<09:14, 24.09it/s]

 29%|██▉       | 5425/18769 [03:46<09:13, 24.11it/s]

 29%|██▉       | 5428/18769 [03:46<09:12, 24.13it/s]

 29%|██▉       | 5431/18769 [03:46<09:12, 24.12it/s]

 29%|██▉       | 5434/18769 [03:46<09:12, 24.14it/s]

 29%|██▉       | 5437/18769 [03:47<09:15, 24.01it/s]

 29%|██▉       | 5440/18769 [03:47<09:13, 24.10it/s]

 29%|██▉       | 5443/18769 [03:47<09:13, 24.09it/s]

 29%|██▉       | 5446/18769 [03:47<09:12, 24.12it/s]

 29%|██▉       | 5449/18769 [03:47<09:11, 24.15it/s]

 29%|██▉       | 5452/18769 [03:47<09:11, 24.15it/s]

 29%|██▉       | 5455/18769 [03:47<09:10, 24.18it/s]

 29%|██▉       | 5458/18769 [03:47<09:09, 24.20it/s]

 29%|██▉       | 5461/18769 [03:48<09:10, 24.19it/s]

 29%|██▉       | 5464/18769 [03:48<09:11, 24.13it/s]

 29%|██▉       | 5467/18769 [03:48<09:10, 24.15it/s]

 29%|██▉       | 5470/18769 [03:48<09:11, 24.11it/s]

 29%|██▉       | 5473/18769 [03:48<09:10, 24.16it/s]

 29%|██▉       | 5476/18769 [03:48<09:10, 24.15it/s]

 29%|██▉       | 5479/18769 [03:48<09:10, 24.15it/s]

 29%|██▉       | 5482/18769 [03:48<09:14, 23.98it/s]

 29%|██▉       | 5485/18769 [03:49<09:19, 23.75it/s]

 29%|██▉       | 5488/18769 [03:49<09:23, 23.58it/s]

 29%|██▉       | 5491/18769 [03:49<09:25, 23.49it/s]

 29%|██▉       | 5494/18769 [03:49<09:26, 23.43it/s]

 29%|██▉       | 5497/18769 [03:49<09:27, 23.37it/s]

 29%|██▉       | 5500/18769 [03:49<09:28, 23.34it/s]

 29%|██▉       | 5503/18769 [03:49<09:28, 23.33it/s]

 29%|██▉       | 5506/18769 [03:49<09:28, 23.31it/s]

 29%|██▉       | 5509/18769 [03:50<09:29, 23.27it/s]

 29%|██▉       | 5512/18769 [03:50<09:29, 23.28it/s]

 29%|██▉       | 5515/18769 [03:50<09:29, 23.29it/s]

 29%|██▉       | 5518/18769 [03:50<09:28, 23.30it/s]

 29%|██▉       | 5522/18769 [03:50<08:46, 25.18it/s]

 29%|██▉       | 5525/18769 [03:50<08:58, 24.59it/s]

 29%|██▉       | 5528/18769 [03:50<09:07, 24.19it/s]

 29%|██▉       | 5531/18769 [03:51<09:13, 23.92it/s]

 29%|██▉       | 5534/18769 [03:51<09:17, 23.72it/s]

 30%|██▉       | 5537/18769 [03:51<09:15, 23.82it/s]

 30%|██▉       | 5540/18769 [03:51<09:14, 23.84it/s]

 30%|██▉       | 5543/18769 [03:51<09:13, 23.90it/s]

 30%|██▉       | 5546/18769 [03:51<09:12, 23.93it/s]

 30%|██▉       | 5549/18769 [03:51<09:11, 23.95it/s]

 30%|██▉       | 5552/18769 [03:51<09:10, 23.99it/s]

 30%|██▉       | 5555/18769 [03:52<09:10, 24.02it/s]

 30%|██▉       | 5558/18769 [03:52<09:12, 23.91it/s]

 30%|██▉       | 5561/18769 [03:52<09:12, 23.92it/s]

 30%|██▉       | 5564/18769 [03:52<09:11, 23.94it/s]

 30%|██▉       | 5567/18769 [03:52<09:11, 23.93it/s]

 30%|██▉       | 5570/18769 [03:52<09:11, 23.94it/s]

 30%|██▉       | 5573/18769 [03:52<09:15, 23.77it/s]

 30%|██▉       | 5576/18769 [03:52<09:13, 23.84it/s]

 30%|██▉       | 5579/18769 [03:53<09:12, 23.89it/s]

 30%|██▉       | 5582/18769 [03:53<09:14, 23.78it/s]

 30%|██▉       | 5585/18769 [03:53<09:12, 23.84it/s]

 30%|██▉       | 5588/18769 [03:53<09:12, 23.87it/s]

 30%|██▉       | 5591/18769 [03:53<09:11, 23.92it/s]

 30%|██▉       | 5594/18769 [03:53<09:10, 23.94it/s]

 30%|██▉       | 5597/18769 [03:53<09:09, 23.98it/s]

 30%|██▉       | 5600/18769 [03:53<09:09, 23.97it/s]

 30%|██▉       | 5603/18769 [03:54<09:09, 23.97it/s]

 30%|██▉       | 5606/18769 [03:54<09:09, 23.96it/s]

 30%|██▉       | 5609/18769 [03:54<09:07, 24.01it/s]

 30%|██▉       | 5612/18769 [03:54<09:08, 24.00it/s]

 30%|██▉       | 5615/18769 [03:54<09:07, 24.02it/s]

 30%|██▉       | 5618/18769 [03:54<09:08, 23.97it/s]

 30%|██▉       | 5621/18769 [03:54<09:12, 23.80it/s]

 30%|██▉       | 5624/18769 [03:54<09:15, 23.68it/s]

 30%|██▉       | 5627/18769 [03:55<09:15, 23.65it/s]

 30%|██▉       | 5630/18769 [03:55<09:20, 23.43it/s]

 30%|███       | 5633/18769 [03:55<09:20, 23.44it/s]

 30%|███       | 5636/18769 [03:55<09:21, 23.41it/s]

 30%|███       | 5639/18769 [03:55<09:20, 23.44it/s]

 30%|███       | 5642/18769 [03:55<09:19, 23.46it/s]

 30%|███       | 5645/18769 [03:55<09:19, 23.44it/s]

 30%|███       | 5648/18769 [03:55<09:19, 23.47it/s]

 30%|███       | 5651/18769 [03:56<09:19, 23.46it/s]

 30%|███       | 5654/18769 [03:56<09:21, 23.37it/s]

 30%|███       | 5657/18769 [03:56<09:20, 23.39it/s]

 30%|███       | 5661/18769 [03:56<08:38, 25.29it/s]

 30%|███       | 5664/18769 [03:56<08:50, 24.69it/s]

 30%|███       | 5667/18769 [03:56<08:58, 24.31it/s]

 30%|███       | 5670/18769 [03:56<09:05, 24.01it/s]

 30%|███       | 5673/18769 [03:56<09:06, 23.97it/s]

 30%|███       | 5676/18769 [03:57<09:07, 23.92it/s]

 30%|███       | 5679/18769 [03:57<09:05, 24.00it/s]

 30%|███       | 5682/18769 [03:57<09:04, 24.06it/s]

 30%|███       | 5685/18769 [03:57<09:03, 24.08it/s]

 30%|███       | 5688/18769 [03:57<09:02, 24.11it/s]

 30%|███       | 5691/18769 [03:57<09:01, 24.13it/s]

 30%|███       | 5694/18769 [03:57<09:01, 24.14it/s]

 30%|███       | 5697/18769 [03:57<09:02, 24.10it/s]

 30%|███       | 5700/18769 [03:58<09:01, 24.14it/s]

 30%|███       | 5703/18769 [03:58<09:01, 24.15it/s]

 30%|███       | 5706/18769 [03:58<09:01, 24.11it/s]

 30%|███       | 5709/18769 [03:58<09:02, 24.09it/s]

 30%|███       | 5712/18769 [03:58<09:03, 24.02it/s]

 30%|███       | 5715/18769 [03:58<09:03, 24.03it/s]

 30%|███       | 5718/18769 [03:58<09:02, 24.08it/s]

 30%|███       | 5721/18769 [03:58<09:02, 24.07it/s]

 30%|███       | 5724/18769 [03:59<09:02, 24.03it/s]

 31%|███       | 5727/18769 [03:59<09:03, 23.99it/s]

 31%|███       | 5730/18769 [03:59<09:02, 24.03it/s]

 31%|███       | 5733/18769 [03:59<09:01, 24.05it/s]

 31%|███       | 5736/18769 [03:59<09:00, 24.11it/s]

 31%|███       | 5739/18769 [03:59<08:59, 24.13it/s]

 31%|███       | 5742/18769 [03:59<09:00, 24.11it/s]

 31%|███       | 5745/18769 [03:59<08:59, 24.14it/s]

 31%|███       | 5748/18769 [04:00<08:59, 24.15it/s]

 31%|███       | 5751/18769 [04:00<09:02, 23.98it/s]

 31%|███       | 5754/18769 [04:00<09:02, 23.97it/s]

 31%|███       | 5757/18769 [04:00<09:08, 23.70it/s]

 31%|███       | 5760/18769 [04:00<09:11, 23.58it/s]

 31%|███       | 5763/18769 [04:00<09:13, 23.52it/s]

 31%|███       | 5766/18769 [04:00<09:14, 23.45it/s]

 31%|███       | 5769/18769 [04:00<09:15, 23.39it/s]

 31%|███       | 5772/18769 [04:01<09:15, 23.38it/s]

 31%|███       | 5775/18769 [04:01<09:15, 23.37it/s]

 31%|███       | 5778/18769 [04:01<09:15, 23.37it/s]

 31%|███       | 5781/18769 [04:01<09:15, 23.39it/s]

 31%|███       | 5784/18769 [04:01<09:14, 23.40it/s]

 31%|███       | 5787/18769 [04:01<09:14, 23.39it/s]

 31%|███       | 5790/18769 [04:01<09:14, 23.40it/s]

 31%|███       | 5793/18769 [04:02<09:14, 23.40it/s]

 31%|███       | 5796/18769 [04:02<09:16, 23.31it/s]

 31%|███       | 5800/18769 [04:02<08:33, 25.23it/s]

 31%|███       | 5803/18769 [04:02<08:45, 24.68it/s]

 31%|███       | 5806/18769 [04:02<08:54, 24.24it/s]

 31%|███       | 5809/18769 [04:02<08:58, 24.05it/s]

 31%|███       | 5812/18769 [04:02<08:59, 24.01it/s]

 31%|███       | 5815/18769 [04:02<08:58, 24.04it/s]

 31%|███       | 5818/18769 [04:03<08:58, 24.05it/s]

 31%|███       | 5821/18769 [04:03<08:58, 24.04it/s]

 31%|███       | 5824/18769 [04:03<08:58, 24.04it/s]

 31%|███       | 5827/18769 [04:03<08:58, 24.03it/s]

 31%|███       | 5830/18769 [04:03<08:59, 23.99it/s]

 31%|███       | 5833/18769 [04:03<08:58, 24.02it/s]

 31%|███       | 5836/18769 [04:03<08:57, 24.05it/s]

 31%|███       | 5839/18769 [04:03<08:58, 24.03it/s]

 31%|███       | 5842/18769 [04:04<08:58, 24.02it/s]

 31%|███       | 5845/18769 [04:04<09:02, 23.80it/s]

 31%|███       | 5848/18769 [04:04<09:02, 23.83it/s]

 31%|███       | 5851/18769 [04:04<09:00, 23.92it/s]

 31%|███       | 5854/18769 [04:04<08:59, 23.94it/s]

 31%|███       | 5857/18769 [04:04<08:58, 23.97it/s]

 31%|███       | 5860/18769 [04:04<08:58, 23.95it/s]

 31%|███       | 5863/18769 [04:04<08:58, 23.99it/s]

 31%|███▏      | 5866/18769 [04:05<08:57, 24.01it/s]

 31%|███▏      | 5869/18769 [04:05<08:57, 24.00it/s]

 31%|███▏      | 5872/18769 [04:05<08:56, 24.04it/s]

 31%|███▏      | 5875/18769 [04:05<08:56, 24.01it/s]

 31%|███▏      | 5878/18769 [04:05<08:57, 24.00it/s]

 31%|███▏      | 5881/18769 [04:05<08:56, 24.04it/s]

 31%|███▏      | 5884/18769 [04:05<08:56, 24.03it/s]

 31%|███▏      | 5887/18769 [04:05<08:56, 24.03it/s]

 31%|███▏      | 5890/18769 [04:06<08:55, 24.03it/s]

 31%|███▏      | 5893/18769 [04:06<09:02, 23.72it/s]

 31%|███▏      | 5896/18769 [04:06<09:05, 23.60it/s]

 31%|███▏      | 5899/18769 [04:06<09:07, 23.51it/s]

 31%|███▏      | 5902/18769 [04:06<09:09, 23.43it/s]

 31%|███▏      | 5905/18769 [04:06<09:09, 23.41it/s]

 31%|███▏      | 5908/18769 [04:06<09:09, 23.42it/s]

 31%|███▏      | 5911/18769 [04:06<09:08, 23.43it/s]

 32%|███▏      | 5914/18769 [04:07<09:09, 23.41it/s]

 32%|███▏      | 5917/18769 [04:07<09:09, 23.37it/s]

 32%|███▏      | 5920/18769 [04:07<09:10, 23.33it/s]

 32%|███▏      | 5923/18769 [04:07<09:11, 23.29it/s]

 32%|███▏      | 5926/18769 [04:07<09:10, 23.33it/s]

 32%|███▏      | 5929/18769 [04:07<09:10, 23.35it/s]

 32%|███▏      | 5932/18769 [04:07<09:10, 23.31it/s]

 32%|███▏      | 5936/18769 [04:07<08:29, 25.20it/s]

 32%|███▏      | 5939/18769 [04:08<08:41, 24.60it/s]

 32%|███▏      | 5942/18769 [04:08<08:53, 24.02it/s]

 32%|███▏      | 5945/18769 [04:08<09:00, 23.75it/s]

 32%|███▏      | 5948/18769 [04:08<08:57, 23.85it/s]

 32%|███▏      | 5951/18769 [04:08<08:55, 23.95it/s]

 32%|███▏      | 5954/18769 [04:08<08:53, 24.00it/s]

 32%|███▏      | 5957/18769 [04:08<08:53, 24.03it/s]

 32%|███▏      | 5960/18769 [04:08<08:52, 24.06it/s]

 32%|███▏      | 5963/18769 [04:09<08:51, 24.09it/s]

 32%|███▏      | 5966/18769 [04:09<08:52, 24.06it/s]

 32%|███▏      | 5969/18769 [04:09<08:52, 24.04it/s]

 32%|███▏      | 5972/18769 [04:09<08:53, 24.01it/s]

 32%|███▏      | 5975/18769 [04:09<08:52, 24.01it/s]

 32%|███▏      | 5978/18769 [04:09<08:52, 24.02it/s]

 32%|███▏      | 5981/18769 [04:09<08:52, 24.02it/s]

 32%|███▏      | 5984/18769 [04:09<08:51, 24.04it/s]

 32%|███▏      | 5987/18769 [04:10<08:51, 24.04it/s]

 32%|███▏      | 5990/18769 [04:10<08:55, 23.88it/s]

 32%|███▏      | 5993/18769 [04:10<08:53, 23.94it/s]

 32%|███▏      | 5996/18769 [04:10<08:53, 23.95it/s]

 32%|███▏      | 5999/18769 [04:10<08:52, 24.00it/s]

 32%|███▏      | 6002/18769 [04:10<08:51, 24.02it/s]

 32%|███▏      | 6005/18769 [04:10<08:52, 23.99it/s]

 32%|███▏      | 6008/18769 [04:10<08:50, 24.05it/s]

 32%|███▏      | 6011/18769 [04:11<08:50, 24.04it/s]

 32%|███▏      | 6014/18769 [04:11<08:53, 23.90it/s]

 32%|███▏      | 6017/18769 [04:11<08:52, 23.96it/s]

 32%|███▏      | 6020/18769 [04:11<08:51, 24.00it/s]

 32%|███▏      | 6023/18769 [04:11<08:50, 24.03it/s]

 32%|███▏      | 6026/18769 [04:11<08:49, 24.04it/s]

 32%|███▏      | 6029/18769 [04:11<08:51, 23.96it/s]

 32%|███▏      | 6032/18769 [04:11<08:57, 23.72it/s]

 32%|███▏      | 6035/18769 [04:12<08:59, 23.61it/s]

 32%|███▏      | 6038/18769 [04:12<09:05, 23.34it/s]

 32%|███▏      | 6041/18769 [04:12<09:05, 23.33it/s]

 32%|███▏      | 6044/18769 [04:12<09:05, 23.33it/s]

 32%|███▏      | 6047/18769 [04:12<09:03, 23.40it/s]

 32%|███▏      | 6050/18769 [04:12<09:04, 23.38it/s]

 32%|███▏      | 6053/18769 [04:12<09:06, 23.29it/s]

 32%|███▏      | 6056/18769 [04:12<09:05, 23.32it/s]

 32%|███▏      | 6059/18769 [04:13<09:04, 23.33it/s]

 32%|███▏      | 6062/18769 [04:13<09:04, 23.36it/s]

 32%|███▏      | 6065/18769 [04:13<09:03, 23.36it/s]

 32%|███▏      | 6068/18769 [04:13<09:03, 23.36it/s]

 32%|███▏      | 6071/18769 [04:13<09:03, 23.36it/s]

 32%|███▏      | 6075/18769 [04:13<08:23, 25.23it/s]

 32%|███▏      | 6078/18769 [04:13<08:34, 24.67it/s]

 32%|███▏      | 6081/18769 [04:14<08:42, 24.30it/s]

 32%|███▏      | 6084/18769 [04:14<08:44, 24.17it/s]

 32%|███▏      | 6087/18769 [04:14<08:44, 24.17it/s]

 32%|███▏      | 6090/18769 [04:14<08:44, 24.19it/s]

 32%|███▏      | 6093/18769 [04:14<08:43, 24.19it/s]

 32%|███▏      | 6096/18769 [04:14<08:44, 24.16it/s]

 32%|███▏      | 6099/18769 [04:14<08:44, 24.13it/s]

 33%|███▎      | 6102/18769 [04:14<08:45, 24.09it/s]

 33%|███▎      | 6105/18769 [04:15<08:45, 24.11it/s]

 33%|███▎      | 6108/18769 [04:15<08:46, 24.07it/s]

 33%|███▎      | 6111/18769 [04:15<08:47, 24.02it/s]

 33%|███▎      | 6114/18769 [04:15<08:47, 23.99it/s]

 33%|███▎      | 6117/18769 [04:15<08:47, 23.96it/s]

 33%|███▎      | 6120/18769 [04:15<08:46, 24.01it/s]

 33%|███▎      | 6123/18769 [04:15<08:45, 24.05it/s]

 33%|███▎      | 6126/18769 [04:15<08:44, 24.08it/s]

 33%|███▎      | 6129/18769 [04:16<08:45, 24.07it/s]

 33%|███▎      | 6132/18769 [04:16<08:45, 24.06it/s]

 33%|███▎      | 6135/18769 [04:16<08:44, 24.07it/s]

 33%|███▎      | 6138/18769 [04:16<08:45, 24.05it/s]

 33%|███▎      | 6141/18769 [04:16<08:45, 24.05it/s]

 33%|███▎      | 6144/18769 [04:16<08:44, 24.08it/s]

 33%|███▎      | 6147/18769 [04:16<08:43, 24.10it/s]

 33%|███▎      | 6150/18769 [04:16<08:43, 24.12it/s]

 33%|███▎      | 6153/18769 [04:17<08:42, 24.13it/s]

 33%|███▎      | 6156/18769 [04:17<08:42, 24.15it/s]

 33%|███▎      | 6159/18769 [04:17<08:42, 24.14it/s]

 33%|███▎      | 6162/18769 [04:17<08:42, 24.15it/s]

 33%|███▎      | 6165/18769 [04:17<08:41, 24.16it/s]

 33%|███▎      | 6168/18769 [04:17<08:47, 23.91it/s]

 33%|███▎      | 6171/18769 [04:17<08:51, 23.72it/s]

 33%|███▎      | 6174/18769 [04:17<08:53, 23.62it/s]

 33%|███▎      | 6177/18769 [04:18<08:55, 23.53it/s]

 33%|███▎      | 6180/18769 [04:18<08:56, 23.48it/s]

 33%|███▎      | 6183/18769 [04:18<08:57, 23.39it/s]

 33%|███▎      | 6186/18769 [04:18<08:58, 23.37it/s]

 33%|███▎      | 6189/18769 [04:18<08:59, 23.30it/s]

 33%|███▎      | 6192/18769 [04:18<08:59, 23.31it/s]

 33%|███▎      | 6195/18769 [04:18<08:58, 23.34it/s]

 33%|███▎      | 6198/18769 [04:18<08:59, 23.31it/s]

 33%|███▎      | 6201/18769 [04:19<08:59, 23.31it/s]

 33%|███▎      | 6204/18769 [04:19<09:00, 23.25it/s]

 33%|███▎      | 6207/18769 [04:19<09:00, 23.25it/s]

 33%|███▎      | 6210/18769 [04:19<09:00, 23.24it/s]

 33%|███▎      | 6214/18769 [04:19<08:19, 25.15it/s]

 33%|███▎      | 6217/18769 [04:19<08:30, 24.58it/s]

 33%|███▎      | 6220/18769 [04:19<08:37, 24.24it/s]

 33%|███▎      | 6223/18769 [04:19<08:39, 24.17it/s]

 33%|███▎      | 6226/18769 [04:20<08:39, 24.12it/s]

 33%|███▎      | 6229/18769 [04:20<08:40, 24.07it/s]

 33%|███▎      | 6232/18769 [04:20<08:49, 23.69it/s]

 33%|███▎      | 6235/18769 [04:20<08:47, 23.76it/s]

 33%|███▎      | 6238/18769 [04:20<08:43, 23.92it/s]

 33%|███▎      | 6241/18769 [04:20<08:41, 24.04it/s]

 33%|███▎      | 6244/18769 [04:20<08:40, 24.07it/s]

 33%|███▎      | 6247/18769 [04:20<08:39, 24.11it/s]

 33%|███▎      | 6250/18769 [04:21<08:38, 24.13it/s]

 33%|███▎      | 6253/18769 [04:21<08:38, 24.14it/s]

 33%|███▎      | 6256/18769 [04:21<08:38, 24.11it/s]

 33%|███▎      | 6259/18769 [04:21<08:37, 24.15it/s]

 33%|███▎      | 6262/18769 [04:21<08:37, 24.18it/s]

 33%|███▎      | 6265/18769 [04:21<08:36, 24.19it/s]

 33%|███▎      | 6268/18769 [04:21<08:36, 24.20it/s]

 33%|███▎      | 6271/18769 [04:21<08:36, 24.20it/s]

 33%|███▎      | 6274/18769 [04:22<08:36, 24.20it/s]

 33%|███▎      | 6277/18769 [04:22<08:36, 24.21it/s]

 33%|███▎      | 6280/18769 [04:22<08:39, 24.05it/s]

 33%|███▎      | 6283/18769 [04:22<08:37, 24.13it/s]

 33%|███▎      | 6286/18769 [04:22<08:37, 24.14it/s]

 34%|███▎      | 6289/18769 [04:22<08:36, 24.15it/s]

 34%|███▎      | 6292/18769 [04:22<08:37, 24.12it/s]

 34%|███▎      | 6295/18769 [04:22<08:36, 24.16it/s]

 34%|███▎      | 6298/18769 [04:23<08:36, 24.13it/s]

 34%|███▎      | 6301/18769 [04:23<08:36, 24.15it/s]

 34%|███▎      | 6304/18769 [04:23<08:40, 23.94it/s]

 34%|███▎      | 6307/18769 [04:23<08:45, 23.73it/s]

 34%|███▎      | 6310/18769 [04:23<08:47, 23.64it/s]

 34%|███▎      | 6313/18769 [04:23<08:48, 23.58it/s]

 34%|███▎      | 6316/18769 [04:23<08:48, 23.57it/s]

 34%|███▎      | 6319/18769 [04:23<08:48, 23.56it/s]

 34%|███▎      | 6322/18769 [04:24<08:49, 23.52it/s]

 34%|███▎      | 6325/18769 [04:24<08:50, 23.47it/s]

 34%|███▎      | 6328/18769 [04:24<08:51, 23.42it/s]

 34%|███▎      | 6331/18769 [04:24<08:50, 23.44it/s]

 34%|███▎      | 6334/18769 [04:24<08:50, 23.42it/s]

 34%|███▍      | 6337/18769 [04:24<08:51, 23.41it/s]

 34%|███▍      | 6340/18769 [04:24<08:51, 23.41it/s]

 34%|███▍      | 6343/18769 [04:24<08:51, 23.40it/s]

 34%|███▍      | 6346/18769 [04:25<08:50, 23.42it/s]

 34%|███▍      | 6350/18769 [04:25<08:10, 25.30it/s]

 34%|███▍      | 6353/18769 [04:25<08:23, 24.68it/s]

 34%|███▍      | 6356/18769 [04:25<08:30, 24.29it/s]

 34%|███▍      | 6359/18769 [04:25<08:31, 24.26it/s]

 34%|███▍      | 6362/18769 [04:25<08:32, 24.22it/s]

 34%|███▍      | 6365/18769 [04:25<08:32, 24.20it/s]

 34%|███▍      | 6368/18769 [04:25<08:32, 24.20it/s]

 34%|███▍      | 6371/18769 [04:26<08:34, 24.09it/s]

 34%|███▍      | 6374/18769 [04:26<08:34, 24.11it/s]

 34%|███▍      | 6377/18769 [04:26<08:33, 24.15it/s]

 34%|███▍      | 6380/18769 [04:26<08:33, 24.14it/s]

 34%|███▍      | 6383/18769 [04:26<08:32, 24.15it/s]

 34%|███▍      | 6386/18769 [04:26<08:32, 24.15it/s]

 34%|███▍      | 6389/18769 [04:26<08:32, 24.16it/s]

 34%|███▍      | 6392/18769 [04:26<08:32, 24.16it/s]

 34%|███▍      | 6395/18769 [04:27<08:32, 24.16it/s]

 34%|███▍      | 6398/18769 [04:27<08:31, 24.17it/s]

 34%|███▍      | 6401/18769 [04:27<08:33, 24.10it/s]

 34%|███▍      | 6404/18769 [04:27<08:33, 24.09it/s]

 34%|███▍      | 6407/18769 [04:27<08:32, 24.10it/s]

 34%|███▍      | 6410/18769 [04:27<08:33, 24.08it/s]

 34%|███▍      | 6413/18769 [04:27<08:32, 24.10it/s]

 34%|███▍      | 6416/18769 [04:27<08:31, 24.14it/s]

 34%|███▍      | 6419/18769 [04:28<08:30, 24.18it/s]

 34%|███▍      | 6422/18769 [04:28<08:32, 24.11it/s]

 34%|███▍      | 6425/18769 [04:28<08:35, 23.94it/s]

 34%|███▍      | 6428/18769 [04:28<08:35, 23.93it/s]

 34%|███▍      | 6431/18769 [04:28<08:35, 23.93it/s]

 34%|███▍      | 6434/18769 [04:28<08:34, 23.99it/s]

 34%|███▍      | 6437/18769 [04:28<08:32, 24.05it/s]

 34%|███▍      | 6440/18769 [04:28<08:32, 24.05it/s]

 34%|███▍      | 6443/18769 [04:29<08:36, 23.86it/s]

 34%|███▍      | 6446/18769 [04:29<08:39, 23.72it/s]

 34%|███▍      | 6449/18769 [04:29<08:41, 23.63it/s]

 34%|███▍      | 6452/18769 [04:29<08:41, 23.60it/s]

 34%|███▍      | 6455/18769 [04:29<08:42, 23.57it/s]

 34%|███▍      | 6458/18769 [04:29<08:44, 23.48it/s]

 34%|███▍      | 6461/18769 [04:29<08:44, 23.48it/s]

 34%|███▍      | 6464/18769 [04:30<08:44, 23.47it/s]

 34%|███▍      | 6467/18769 [04:30<08:44, 23.44it/s]

 34%|███▍      | 6470/18769 [04:30<08:44, 23.47it/s]

 34%|███▍      | 6473/18769 [04:30<08:47, 23.29it/s]

 35%|███▍      | 6476/18769 [04:30<08:46, 23.36it/s]

 35%|███▍      | 6479/18769 [04:30<08:45, 23.39it/s]

 35%|███▍      | 6482/18769 [04:30<08:45, 23.38it/s]

 35%|███▍      | 6485/18769 [04:30<08:45, 23.38it/s]

 35%|███▍      | 6489/18769 [04:31<08:05, 25.31it/s]

 35%|███▍      | 6492/18769 [04:31<08:17, 24.67it/s]

 35%|███▍      | 6495/18769 [04:31<08:22, 24.43it/s]

 35%|███▍      | 6498/18769 [04:31<08:25, 24.30it/s]

 35%|███▍      | 6501/18769 [04:31<08:26, 24.24it/s]

 35%|███▍      | 6504/18769 [04:31<08:26, 24.21it/s]

 35%|███▍      | 6507/18769 [04:31<08:25, 24.24it/s]

 35%|███▍      | 6510/18769 [04:31<08:25, 24.24it/s]

 35%|███▍      | 6513/18769 [04:32<08:25, 24.26it/s]

 35%|███▍      | 6516/18769 [04:32<08:25, 24.25it/s]

 35%|███▍      | 6519/18769 [04:32<08:26, 24.18it/s]

 35%|███▍      | 6522/18769 [04:32<08:31, 23.96it/s]

 35%|███▍      | 6525/18769 [04:32<08:30, 23.98it/s]

 35%|███▍      | 6528/18769 [04:32<08:30, 23.98it/s]

 35%|███▍      | 6531/18769 [04:32<08:31, 23.92it/s]

 35%|███▍      | 6534/18769 [04:32<08:30, 23.95it/s]

 35%|███▍      | 6537/18769 [04:33<08:30, 23.94it/s]

 35%|███▍      | 6540/18769 [04:33<08:30, 23.97it/s]

 35%|███▍      | 6543/18769 [04:33<08:28, 24.02it/s]

 35%|███▍      | 6546/18769 [04:33<08:32, 23.87it/s]

 35%|███▍      | 6549/18769 [04:33<08:29, 23.97it/s]

 35%|███▍      | 6552/18769 [04:33<08:28, 24.02it/s]

 35%|███▍      | 6555/18769 [04:33<08:27, 24.08it/s]

 35%|███▍      | 6558/18769 [04:33<08:26, 24.10it/s]

 35%|███▍      | 6561/18769 [04:34<08:26, 24.12it/s]

 35%|███▍      | 6564/18769 [04:34<08:25, 24.13it/s]

 35%|███▍      | 6567/18769 [04:34<08:24, 24.17it/s]

 35%|███▌      | 6570/18769 [04:34<08:25, 24.15it/s]

 35%|███▌      | 6573/18769 [04:34<08:25, 24.14it/s]

 35%|███▌      | 6576/18769 [04:34<08:24, 24.18it/s]

 35%|███▌      | 6579/18769 [04:34<08:29, 23.92it/s]

 35%|███▌      | 6582/18769 [04:34<08:31, 23.82it/s]

 35%|███▌      | 6585/18769 [04:35<08:34, 23.70it/s]

 35%|███▌      | 6588/18769 [04:35<08:35, 23.61it/s]

 35%|███▌      | 6591/18769 [04:35<08:36, 23.58it/s]

 35%|███▌      | 6594/18769 [04:35<08:42, 23.30it/s]

 35%|███▌      | 6597/18769 [04:35<08:41, 23.33it/s]

 35%|███▌      | 6600/18769 [04:35<08:41, 23.35it/s]

 35%|███▌      | 6603/18769 [04:35<08:40, 23.38it/s]

 35%|███▌      | 6606/18769 [04:35<08:40, 23.36it/s]

 35%|███▌      | 6609/18769 [04:36<08:40, 23.36it/s]

 35%|███▌      | 6612/18769 [04:36<08:41, 23.31it/s]

 35%|███▌      | 6615/18769 [04:36<08:41, 23.31it/s]

 35%|███▌      | 6618/18769 [04:36<08:41, 23.29it/s]

 35%|███▌      | 6621/18769 [04:36<08:40, 23.36it/s]

 35%|███▌      | 6624/18769 [04:36<08:39, 23.40it/s]

 35%|███▌      | 6628/18769 [04:36<07:59, 25.31it/s]

 35%|███▌      | 6631/18769 [04:36<08:09, 24.82it/s]

 35%|███▌      | 6634/18769 [04:37<08:11, 24.69it/s]

 35%|███▌      | 6637/18769 [04:37<08:13, 24.58it/s]

 35%|███▌      | 6640/18769 [04:37<08:15, 24.47it/s]

 35%|███▌      | 6643/18769 [04:37<08:20, 24.22it/s]

 35%|███▌      | 6646/18769 [04:37<08:20, 24.24it/s]

 35%|███▌      | 6649/18769 [04:37<08:19, 24.26it/s]

 35%|███▌      | 6652/18769 [04:37<08:18, 24.28it/s]

 35%|███▌      | 6655/18769 [04:37<08:19, 24.27it/s]

 35%|███▌      | 6658/18769 [04:38<08:18, 24.31it/s]

 35%|███▌      | 6661/18769 [04:38<08:17, 24.33it/s]

 36%|███▌      | 6664/18769 [04:38<08:16, 24.38it/s]

 36%|███▌      | 6667/18769 [04:38<08:17, 24.31it/s]

 36%|███▌      | 6670/18769 [04:38<08:17, 24.30it/s]

 36%|███▌      | 6673/18769 [04:38<08:18, 24.28it/s]

 36%|███▌      | 6676/18769 [04:38<08:17, 24.30it/s]

 36%|███▌      | 6679/18769 [04:38<08:17, 24.28it/s]

 36%|███▌      | 6682/18769 [04:39<08:18, 24.25it/s]

 36%|███▌      | 6685/18769 [04:39<08:19, 24.21it/s]

 36%|███▌      | 6688/18769 [04:39<08:20, 24.15it/s]

 36%|███▌      | 6691/18769 [04:39<08:20, 24.13it/s]

 36%|███▌      | 6694/18769 [04:39<08:20, 24.15it/s]

 36%|███▌      | 6697/18769 [04:39<08:20, 24.12it/s]

 36%|███▌      | 6700/18769 [04:39<08:19, 24.14it/s]

 36%|███▌      | 6703/18769 [04:39<08:19, 24.13it/s]

 36%|███▌      | 6706/18769 [04:40<08:19, 24.16it/s]

 36%|███▌      | 6709/18769 [04:40<08:19, 24.14it/s]

 36%|███▌      | 6712/18769 [04:40<08:20, 24.09it/s]

 36%|███▌      | 6715/18769 [04:40<08:27, 23.77it/s]

 36%|███▌      | 6718/18769 [04:40<08:30, 23.63it/s]

 36%|███▌      | 6721/18769 [04:40<08:31, 23.54it/s]

 36%|███▌      | 6724/18769 [04:40<08:32, 23.51it/s]

 36%|███▌      | 6727/18769 [04:40<08:33, 23.47it/s]

 36%|███▌      | 6730/18769 [04:41<08:32, 23.47it/s]

 36%|███▌      | 6733/18769 [04:41<08:34, 23.41it/s]

 36%|███▌      | 6736/18769 [04:41<08:34, 23.38it/s]

 36%|███▌      | 6739/18769 [04:41<08:35, 23.34it/s]

 36%|███▌      | 6742/18769 [04:41<08:36, 23.29it/s]

 36%|███▌      | 6745/18769 [04:41<08:36, 23.27it/s]

 36%|███▌      | 6748/18769 [04:41<08:37, 23.25it/s]

 36%|███▌      | 6751/18769 [04:41<08:36, 23.26it/s]

 36%|███▌      | 6754/18769 [04:42<08:37, 23.22it/s]

 36%|███▌      | 6757/18769 [04:42<08:36, 23.24it/s]

 36%|███▌      | 6760/18769 [04:42<08:36, 23.23it/s]

 36%|███▌      | 6764/18769 [04:42<08:00, 24.97it/s]

 36%|███▌      | 6767/18769 [04:42<08:11, 24.43it/s]

 36%|███▌      | 6770/18769 [04:42<08:12, 24.34it/s]

 36%|███▌      | 6773/18769 [04:42<08:14, 24.25it/s]

 36%|███▌      | 6776/18769 [04:43<08:13, 24.29it/s]

 36%|███▌      | 6779/18769 [04:43<08:13, 24.28it/s]

 36%|███▌      | 6782/18769 [04:43<08:17, 24.08it/s]

 36%|███▌      | 6785/18769 [04:43<08:17, 24.10it/s]

 36%|███▌      | 6788/18769 [04:43<08:17, 24.09it/s]

 36%|███▌      | 6791/18769 [04:43<08:16, 24.12it/s]

 36%|███▌      | 6794/18769 [04:43<08:15, 24.16it/s]

 36%|███▌      | 6797/18769 [04:43<08:14, 24.21it/s]

 36%|███▌      | 6800/18769 [04:44<08:14, 24.20it/s]

 36%|███▌      | 6803/18769 [04:44<08:15, 24.16it/s]

 36%|███▋      | 6806/18769 [04:44<08:15, 24.15it/s]

 36%|███▋      | 6809/18769 [04:44<08:14, 24.17it/s]

 36%|███▋      | 6812/18769 [04:44<08:17, 24.02it/s]

 36%|███▋      | 6815/18769 [04:44<08:16, 24.10it/s]

 36%|███▋      | 6818/18769 [04:44<08:14, 24.16it/s]

 36%|███▋      | 6821/18769 [04:44<08:14, 24.15it/s]

 36%|███▋      | 6824/18769 [04:44<08:14, 24.17it/s]

 36%|███▋      | 6827/18769 [04:45<08:14, 24.13it/s]

 36%|███▋      | 6830/18769 [04:45<08:14, 24.12it/s]

 36%|███▋      | 6833/18769 [04:45<08:15, 24.08it/s]

 36%|███▋      | 6836/18769 [04:45<08:15, 24.10it/s]

 36%|███▋      | 6839/18769 [04:45<08:14, 24.12it/s]

 36%|███▋      | 6842/18769 [04:45<08:13, 24.18it/s]

 36%|███▋      | 6845/18769 [04:45<08:12, 24.19it/s]

 36%|███▋      | 6848/18769 [04:45<08:13, 24.17it/s]

 37%|███▋      | 6851/18769 [04:46<08:15, 24.08it/s]

 37%|███▋      | 6854/18769 [04:46<08:18, 23.88it/s]

 37%|███▋      | 6857/18769 [04:46<08:21, 23.74it/s]

 37%|███▋      | 6860/18769 [04:46<08:26, 23.50it/s]

 37%|███▋      | 6863/18769 [04:46<08:27, 23.45it/s]

 37%|███▋      | 6866/18769 [04:46<08:26, 23.48it/s]

 37%|███▋      | 6869/18769 [04:46<08:27, 23.46it/s]

 37%|███▋      | 6872/18769 [04:47<08:26, 23.47it/s]

 37%|███▋      | 6875/18769 [04:47<08:27, 23.42it/s]

 37%|███▋      | 6878/18769 [04:47<08:28, 23.41it/s]

 37%|███▋      | 6881/18769 [04:47<08:29, 23.35it/s]

 37%|███▋      | 6884/18769 [04:47<08:28, 23.36it/s]

 37%|███▋      | 6887/18769 [04:47<08:28, 23.39it/s]

 37%|███▋      | 6890/18769 [04:47<08:27, 23.40it/s]

 37%|███▋      | 6893/18769 [04:47<08:27, 23.38it/s]

 37%|███▋      | 6896/18769 [04:48<08:27, 23.39it/s]

 37%|███▋      | 6899/18769 [04:48<08:28, 23.34it/s]

 37%|███▋      | 6903/18769 [04:48<07:50, 25.22it/s]

 37%|███▋      | 6906/18769 [04:48<07:58, 24.81it/s]

 37%|███▋      | 6909/18769 [04:48<08:04, 24.46it/s]

 37%|███▋      | 6912/18769 [04:48<08:06, 24.39it/s]

 37%|███▋      | 6915/18769 [04:48<08:06, 24.34it/s]

 37%|███▋      | 6918/18769 [04:48<08:07, 24.33it/s]

 37%|███▋      | 6921/18769 [04:49<08:07, 24.28it/s]

 37%|███▋      | 6924/18769 [04:49<08:08, 24.24it/s]

 37%|███▋      | 6927/18769 [04:49<08:09, 24.21it/s]

 37%|███▋      | 6930/18769 [04:49<08:09, 24.20it/s]

 37%|███▋      | 6933/18769 [04:49<08:09, 24.16it/s]

 37%|███▋      | 6936/18769 [04:49<08:10, 24.13it/s]

 37%|███▋      | 6939/18769 [04:49<08:10, 24.10it/s]

 37%|███▋      | 6942/18769 [04:49<08:10, 24.11it/s]

 37%|███▋      | 6945/18769 [04:50<08:10, 24.12it/s]

 37%|███▋      | 6948/18769 [04:50<08:10, 24.10it/s]

 37%|███▋      | 6951/18769 [04:50<08:10, 24.12it/s]

 37%|███▋      | 6954/18769 [04:50<08:10, 24.11it/s]

 37%|███▋      | 6957/18769 [04:50<08:09, 24.11it/s]

 37%|███▋      | 6960/18769 [04:50<08:10, 24.07it/s]

 37%|███▋      | 6963/18769 [04:50<08:10, 24.07it/s]

 37%|███▋      | 6966/18769 [04:50<08:09, 24.09it/s]

 37%|███▋      | 6969/18769 [04:51<08:09, 24.11it/s]

 37%|███▋      | 6972/18769 [04:51<08:09, 24.10it/s]

 37%|███▋      | 6975/18769 [04:51<08:09, 24.09it/s]

 37%|███▋      | 6978/18769 [04:51<08:10, 24.05it/s]

 37%|███▋      | 6981/18769 [04:51<08:10, 24.03it/s]

 37%|███▋      | 6984/18769 [04:51<08:10, 24.04it/s]

 37%|███▋      | 6987/18769 [04:51<08:10, 24.04it/s]

 37%|███▋      | 6990/18769 [04:51<08:14, 23.84it/s]

 37%|███▋      | 6993/18769 [04:52<08:15, 23.78it/s]

 37%|███▋      | 6996/18769 [04:52<08:18, 23.60it/s]

 37%|███▋      | 6999/18769 [04:52<08:19, 23.58it/s]

 37%|███▋      | 7002/18769 [04:52<08:19, 23.55it/s]

 37%|███▋      | 7005/18769 [04:52<08:20, 23.49it/s]

 37%|███▋      | 7008/18769 [04:52<08:26, 23.23it/s]

 37%|███▋      | 7011/18769 [04:52<08:35, 22.83it/s]

 37%|███▋      | 7014/18769 [04:52<08:30, 23.02it/s]

 37%|███▋      | 7017/18769 [04:53<08:27, 23.14it/s]

 37%|███▋      | 7020/18769 [04:53<08:25, 23.22it/s]

 37%|███▋      | 7023/18769 [04:53<08:25, 23.23it/s]

 37%|███▋      | 7026/18769 [04:53<08:25, 23.24it/s]

 37%|███▋      | 7029/18769 [04:53<08:26, 23.19it/s]

 37%|███▋      | 7032/18769 [04:53<08:25, 23.23it/s]

 37%|███▋      | 7035/18769 [04:53<08:24, 23.25it/s]

 37%|███▋      | 7038/18769 [04:53<08:25, 23.21it/s]

 38%|███▊      | 7042/18769 [04:54<07:45, 25.18it/s]

 38%|███▊      | 7045/18769 [04:54<07:52, 24.83it/s]

 38%|███▊      | 7048/18769 [04:54<07:56, 24.58it/s]

 38%|███▊      | 7051/18769 [04:54<07:59, 24.45it/s]

 38%|███▊      | 7054/18769 [04:54<08:01, 24.35it/s]

 38%|███▊      | 7057/18769 [04:54<08:02, 24.28it/s]

 38%|███▊      | 7060/18769 [04:54<08:03, 24.23it/s]

 38%|███▊      | 7063/18769 [04:54<08:03, 24.23it/s]

 38%|███▊      | 7066/18769 [04:55<08:03, 24.22it/s]

 38%|███▊      | 7069/18769 [04:55<08:04, 24.15it/s]

 38%|███▊      | 7072/18769 [04:55<08:05, 24.11it/s]

 38%|███▊      | 7075/18769 [04:55<08:07, 24.00it/s]

 38%|███▊      | 7078/18769 [04:55<08:07, 23.96it/s]

 38%|███▊      | 7081/18769 [04:55<08:07, 23.96it/s]

 38%|███▊      | 7084/18769 [04:55<08:06, 24.00it/s]

 38%|███▊      | 7087/18769 [04:55<08:08, 23.91it/s]

 38%|███▊      | 7090/18769 [04:56<08:10, 23.81it/s]

 38%|███▊      | 7093/18769 [04:56<08:11, 23.78it/s]

 38%|███▊      | 7096/18769 [04:56<08:10, 23.80it/s]

 38%|███▊      | 7099/18769 [04:56<08:09, 23.86it/s]

 38%|███▊      | 7102/18769 [04:56<08:08, 23.90it/s]

 38%|███▊      | 7105/18769 [04:56<08:07, 23.91it/s]

 38%|███▊      | 7108/18769 [04:56<08:07, 23.94it/s]

 38%|███▊      | 7111/18769 [04:56<08:06, 23.95it/s]

 38%|███▊      | 7114/18769 [04:57<08:06, 23.96it/s]

 38%|███▊      | 7117/18769 [04:57<08:06, 23.93it/s]

 38%|███▊      | 7120/18769 [04:57<08:06, 23.93it/s]

 38%|███▊      | 7123/18769 [04:57<08:06, 23.93it/s]

 38%|███▊      | 7126/18769 [04:57<08:08, 23.81it/s]

 38%|███▊      | 7129/18769 [04:57<08:12, 23.64it/s]

 38%|███▊      | 7132/18769 [04:57<08:14, 23.56it/s]

 38%|███▊      | 7135/18769 [04:58<08:15, 23.50it/s]

 38%|███▊      | 7138/18769 [04:58<08:15, 23.46it/s]

 38%|███▊      | 7141/18769 [04:58<08:16, 23.42it/s]

 38%|███▊      | 7144/18769 [04:58<08:17, 23.38it/s]

 38%|███▊      | 7147/18769 [04:58<08:17, 23.37it/s]

 38%|███▊      | 7150/18769 [04:58<08:19, 23.27it/s]

 38%|███▊      | 7153/18769 [04:58<08:19, 23.27it/s]

 38%|███▊      | 7156/18769 [04:58<08:18, 23.29it/s]

 38%|███▊      | 7159/18769 [04:59<08:17, 23.31it/s]

 38%|███▊      | 7162/18769 [04:59<08:17, 23.33it/s]

 38%|███▊      | 7165/18769 [04:59<08:18, 23.30it/s]

 38%|███▊      | 7168/18769 [04:59<08:19, 23.25it/s]

 38%|███▊      | 7171/18769 [04:59<08:18, 23.24it/s]

 38%|███▊      | 7174/18769 [04:59<08:17, 23.30it/s]

 38%|███▊      | 7178/18769 [04:59<07:40, 25.18it/s]

 38%|███▊      | 7181/18769 [04:59<07:46, 24.85it/s]

 38%|███▊      | 7184/18769 [05:00<07:50, 24.63it/s]

 38%|███▊      | 7187/18769 [05:00<07:54, 24.40it/s]

 38%|███▊      | 7190/18769 [05:00<07:56, 24.32it/s]

 38%|███▊      | 7193/18769 [05:00<07:57, 24.25it/s]

 38%|███▊      | 7196/18769 [05:00<07:58, 24.21it/s]

 38%|███▊      | 7199/18769 [05:00<07:58, 24.18it/s]

 38%|███▊      | 7202/18769 [05:00<07:59, 24.14it/s]

 38%|███▊      | 7205/18769 [05:00<07:58, 24.14it/s]

 38%|███▊      | 7208/18769 [05:01<07:58, 24.15it/s]

 38%|███▊      | 7211/18769 [05:01<07:59, 24.11it/s]

 38%|███▊      | 7214/18769 [05:01<08:00, 24.06it/s]

 38%|███▊      | 7217/18769 [05:01<07:58, 24.13it/s]

 38%|███▊      | 7220/18769 [05:01<08:01, 23.97it/s]

 38%|███▊      | 7223/18769 [05:01<08:00, 24.03it/s]

 38%|███▊      | 7226/18769 [05:01<07:59, 24.10it/s]

 39%|███▊      | 7229/18769 [05:01<07:59, 24.08it/s]

 39%|███▊      | 7232/18769 [05:02<07:58, 24.10it/s]

 39%|███▊      | 7235/18769 [05:02<07:57, 24.15it/s]

 39%|███▊      | 7238/18769 [05:02<07:56, 24.18it/s]

 39%|███▊      | 7241/18769 [05:02<07:57, 24.13it/s]

 39%|███▊      | 7244/18769 [05:02<07:57, 24.13it/s]

 39%|███▊      | 7247/18769 [05:02<07:58, 24.08it/s]

 39%|███▊      | 7250/18769 [05:02<08:07, 23.61it/s]

 39%|███▊      | 7253/18769 [05:02<08:05, 23.74it/s]

 39%|███▊      | 7256/18769 [05:03<08:08, 23.55it/s]

 39%|███▊      | 7259/18769 [05:03<08:05, 23.72it/s]

 39%|███▊      | 7262/18769 [05:03<08:04, 23.76it/s]

 39%|███▊      | 7265/18769 [05:03<08:08, 23.57it/s]

 39%|███▊      | 7268/18769 [05:03<08:08, 23.52it/s]

 39%|███▊      | 7271/18769 [05:03<08:09, 23.47it/s]

 39%|███▉      | 7274/18769 [05:03<08:09, 23.47it/s]

 39%|███▉      | 7277/18769 [05:03<08:09, 23.47it/s]

 39%|███▉      | 7280/18769 [05:04<08:09, 23.46it/s]

 39%|███▉      | 7283/18769 [05:04<08:11, 23.36it/s]

 39%|███▉      | 7286/18769 [05:04<08:11, 23.37it/s]

 39%|███▉      | 7289/18769 [05:04<08:11, 23.38it/s]

 39%|███▉      | 7292/18769 [05:04<08:10, 23.39it/s]

 39%|███▉      | 7295/18769 [05:04<08:10, 23.40it/s]

 39%|███▉      | 7298/18769 [05:04<08:10, 23.41it/s]

 39%|███▉      | 7301/18769 [05:04<08:10, 23.39it/s]

 39%|███▉      | 7304/18769 [05:05<08:09, 23.41it/s]

 39%|███▉      | 7307/18769 [05:05<08:09, 23.44it/s]

 39%|███▉      | 7310/18769 [05:05<08:08, 23.45it/s]

 39%|███▉      | 7313/18769 [05:05<08:08, 23.45it/s]

 39%|███▉      | 7317/18769 [05:05<07:30, 25.44it/s]

 39%|███▉      | 7320/18769 [05:05<07:37, 25.01it/s]

 39%|███▉      | 7323/18769 [05:05<07:41, 24.78it/s]

 39%|███▉      | 7326/18769 [05:05<07:45, 24.57it/s]

 39%|███▉      | 7329/18769 [05:06<07:48, 24.43it/s]

 39%|███▉      | 7332/18769 [05:06<07:49, 24.35it/s]

 39%|███▉      | 7335/18769 [05:06<07:49, 24.33it/s]

 39%|███▉      | 7338/18769 [05:06<07:50, 24.29it/s]

 39%|███▉      | 7341/18769 [05:06<07:54, 24.09it/s]

 39%|███▉      | 7344/18769 [05:06<07:53, 24.14it/s]

 39%|███▉      | 7347/18769 [05:06<07:52, 24.18it/s]

 39%|███▉      | 7350/18769 [05:06<07:51, 24.21it/s]

 39%|███▉      | 7353/18769 [05:07<07:51, 24.22it/s]

 39%|███▉      | 7356/18769 [05:07<07:51, 24.22it/s]

 39%|███▉      | 7359/18769 [05:07<07:51, 24.20it/s]

 39%|███▉      | 7362/18769 [05:07<07:52, 24.15it/s]

 39%|███▉      | 7365/18769 [05:07<07:55, 23.98it/s]

 39%|███▉      | 7368/18769 [05:07<07:54, 24.05it/s]

 39%|███▉      | 7371/18769 [05:07<07:53, 24.05it/s]

 39%|███▉      | 7374/18769 [05:07<07:52, 24.10it/s]

 39%|███▉      | 7377/18769 [05:08<07:52, 24.12it/s]

 39%|███▉      | 7380/18769 [05:08<07:52, 24.12it/s]

 39%|███▉      | 7383/18769 [05:08<07:52, 24.10it/s]

 39%|███▉      | 7386/18769 [05:08<07:52, 24.10it/s]

 39%|███▉      | 7389/18769 [05:08<07:52, 24.09it/s]

 39%|███▉      | 7392/18769 [05:08<07:51, 24.11it/s]

 39%|███▉      | 7395/18769 [05:08<07:51, 24.10it/s]

 39%|███▉      | 7398/18769 [05:08<07:50, 24.16it/s]

 39%|███▉      | 7401/18769 [05:09<07:50, 24.15it/s]

 39%|███▉      | 7404/18769 [05:09<07:51, 24.11it/s]

 39%|███▉      | 7407/18769 [05:09<07:52, 24.05it/s]

 39%|███▉      | 7410/18769 [05:09<07:51, 24.08it/s]

 39%|███▉      | 7413/18769 [05:09<07:55, 23.87it/s]

 40%|███▉      | 7416/18769 [05:09<07:55, 23.86it/s]

 40%|███▉      | 7419/18769 [05:09<07:55, 23.85it/s]

 40%|███▉      | 7422/18769 [05:09<07:56, 23.84it/s]

 40%|███▉      | 7425/18769 [05:10<07:55, 23.84it/s]

 40%|███▉      | 7428/18769 [05:10<07:56, 23.81it/s]

 40%|███▉      | 7431/18769 [05:10<07:56, 23.80it/s]

 40%|███▉      | 7434/18769 [05:10<07:56, 23.80it/s]

 40%|███▉      | 7437/18769 [05:10<07:59, 23.64it/s]

 40%|███▉      | 7440/18769 [05:10<07:58, 23.67it/s]

 40%|███▉      | 7443/18769 [05:10<07:57, 23.73it/s]

 40%|███▉      | 7446/18769 [05:10<07:56, 23.78it/s]

 40%|███▉      | 7449/18769 [05:11<07:55, 23.81it/s]

 40%|███▉      | 7452/18769 [05:11<07:55, 23.78it/s]

 40%|███▉      | 7456/18769 [05:11<07:23, 25.52it/s]

 40%|███▉      | 7459/18769 [05:11<07:37, 24.73it/s]

 40%|███▉      | 7462/18769 [05:11<07:46, 24.26it/s]

 40%|███▉      | 7465/18769 [05:11<07:51, 23.98it/s]

 40%|███▉      | 7468/18769 [05:11<07:54, 23.79it/s]

 40%|███▉      | 7471/18769 [05:12<07:58, 23.61it/s]

 40%|███▉      | 7474/18769 [05:12<08:01, 23.46it/s]

 40%|███▉      | 7477/18769 [05:12<08:01, 23.44it/s]

 40%|███▉      | 7480/18769 [05:12<08:00, 23.51it/s]

 40%|███▉      | 7483/18769 [05:12<07:59, 23.55it/s]

 40%|███▉      | 7486/18769 [05:12<08:01, 23.43it/s]

 40%|███▉      | 7489/18769 [05:12<08:00, 23.48it/s]

 40%|███▉      | 7492/18769 [05:12<08:00, 23.46it/s]

 40%|███▉      | 7495/18769 [05:13<07:59, 23.53it/s]

 40%|███▉      | 7498/18769 [05:13<07:58, 23.55it/s]

 40%|███▉      | 7501/18769 [05:13<07:57, 23.61it/s]

 40%|███▉      | 7504/18769 [05:13<07:57, 23.59it/s]

 40%|███▉      | 7507/18769 [05:13<07:56, 23.64it/s]

 40%|████      | 7510/18769 [05:13<07:59, 23.49it/s]

 40%|████      | 7513/18769 [05:13<07:57, 23.56it/s]

 40%|████      | 7516/18769 [05:13<07:56, 23.63it/s]

 40%|████      | 7519/18769 [05:14<07:55, 23.64it/s]

 40%|████      | 7522/18769 [05:14<07:54, 23.68it/s]

 40%|████      | 7525/18769 [05:14<07:54, 23.68it/s]

 40%|████      | 7528/18769 [05:14<07:55, 23.66it/s]

 40%|████      | 7531/18769 [05:14<07:55, 23.63it/s]

 40%|████      | 7534/18769 [05:14<07:54, 23.68it/s]

 40%|████      | 7537/18769 [05:14<07:52, 23.76it/s]

 40%|████      | 7540/18769 [05:14<07:50, 23.88it/s]

 40%|████      | 7543/18769 [05:15<07:48, 23.94it/s]

 40%|████      | 7546/18769 [05:15<07:47, 24.00it/s]

 40%|████      | 7549/18769 [05:15<07:46, 24.06it/s]

 40%|████      | 7552/18769 [05:15<07:46, 24.06it/s]

 40%|████      | 7555/18769 [05:15<07:45, 24.10it/s]

 40%|████      | 7558/18769 [05:15<07:45, 24.10it/s]

 40%|████      | 7561/18769 [05:15<07:45, 24.09it/s]

 40%|████      | 7564/18769 [05:15<07:44, 24.10it/s]

 40%|████      | 7567/18769 [05:16<07:44, 24.13it/s]

 40%|████      | 7570/18769 [05:16<07:46, 24.02it/s]

 40%|████      | 7573/18769 [05:16<07:45, 24.06it/s]

 40%|████      | 7576/18769 [05:16<07:44, 24.08it/s]

 40%|████      | 7579/18769 [05:16<07:43, 24.12it/s]

 40%|████      | 7582/18769 [05:16<07:45, 24.03it/s]

 40%|████      | 7585/18769 [05:16<07:45, 24.04it/s]

 40%|████      | 7588/18769 [05:16<07:44, 24.08it/s]

 40%|████      | 7592/18769 [05:17<07:10, 25.95it/s]

 40%|████      | 7595/18769 [05:17<07:23, 25.18it/s]

 40%|████      | 7598/18769 [05:17<07:33, 24.63it/s]

 40%|████      | 7601/18769 [05:17<07:40, 24.26it/s]

 41%|████      | 7604/18769 [05:17<07:45, 24.01it/s]

 41%|████      | 7607/18769 [05:17<07:48, 23.81it/s]

 41%|████      | 7610/18769 [05:17<07:50, 23.71it/s]

 41%|████      | 7613/18769 [05:17<07:51, 23.65it/s]

 41%|████      | 7616/18769 [05:18<07:51, 23.66it/s]

 41%|████      | 7619/18769 [05:18<07:51, 23.66it/s]

 41%|████      | 7622/18769 [05:18<07:51, 23.64it/s]

 41%|████      | 7625/18769 [05:18<07:51, 23.63it/s]

 41%|████      | 7628/18769 [05:18<07:51, 23.62it/s]

 41%|████      | 7631/18769 [05:18<07:51, 23.62it/s]

 41%|████      | 7634/18769 [05:18<07:51, 23.64it/s]

 41%|████      | 7637/18769 [05:18<07:50, 23.66it/s]

 41%|████      | 7640/18769 [05:19<07:50, 23.68it/s]

 41%|████      | 7643/18769 [05:19<07:49, 23.68it/s]

 41%|████      | 7646/18769 [05:19<07:49, 23.67it/s]

 41%|████      | 7649/18769 [05:19<07:50, 23.64it/s]

 41%|████      | 7652/18769 [05:19<07:50, 23.64it/s]

 41%|████      | 7655/18769 [05:19<07:49, 23.67it/s]

 41%|████      | 7658/18769 [05:19<07:49, 23.66it/s]

 41%|████      | 7661/18769 [05:19<07:48, 23.70it/s]

 41%|████      | 7664/18769 [05:20<07:48, 23.70it/s]

 41%|████      | 7667/18769 [05:20<07:50, 23.62it/s]

 41%|████      | 7670/18769 [05:20<07:49, 23.62it/s]

 41%|████      | 7673/18769 [05:20<07:47, 23.75it/s]

 41%|████      | 7676/18769 [05:20<07:45, 23.84it/s]

 41%|████      | 7679/18769 [05:20<07:46, 23.80it/s]

 41%|████      | 7682/18769 [05:20<07:45, 23.82it/s]

 41%|████      | 7685/18769 [05:20<07:44, 23.89it/s]

 41%|████      | 7688/18769 [05:21<07:43, 23.93it/s]

 41%|████      | 7691/18769 [05:21<07:42, 23.93it/s]

 41%|████      | 7694/18769 [05:21<07:42, 23.93it/s]

 41%|████      | 7697/18769 [05:21<07:41, 23.98it/s]

 41%|████      | 7700/18769 [05:21<07:41, 23.99it/s]

 41%|████      | 7703/18769 [05:21<07:43, 23.87it/s]

 41%|████      | 7706/18769 [05:21<07:42, 23.92it/s]

 41%|████      | 7709/18769 [05:21<07:40, 23.99it/s]

 41%|████      | 7712/18769 [05:22<07:41, 23.94it/s]

 41%|████      | 7715/18769 [05:22<07:40, 23.98it/s]

 41%|████      | 7718/18769 [05:22<07:39, 24.04it/s]

 41%|████      | 7721/18769 [05:22<07:39, 24.06it/s]

 41%|████      | 7724/18769 [05:22<07:38, 24.11it/s]

 41%|████      | 7727/18769 [05:22<07:41, 23.93it/s]

 41%|████      | 7731/18769 [05:22<07:10, 25.63it/s]

 41%|████      | 7734/18769 [05:23<07:22, 24.91it/s]

 41%|████      | 7737/18769 [05:23<07:30, 24.47it/s]

 41%|████      | 7740/18769 [05:23<07:35, 24.22it/s]

 41%|████▏     | 7743/18769 [05:23<07:38, 24.03it/s]

 41%|████▏     | 7746/18769 [05:23<07:42, 23.86it/s]

 41%|████▏     | 7749/18769 [05:23<07:43, 23.76it/s]

 41%|████▏     | 7752/18769 [05:23<07:47, 23.58it/s]

 41%|████▏     | 7755/18769 [05:23<07:46, 23.63it/s]

 41%|████▏     | 7758/18769 [05:24<07:45, 23.65it/s]

 41%|████▏     | 7761/18769 [05:24<07:46, 23.59it/s]

 41%|████▏     | 7764/18769 [05:24<07:46, 23.60it/s]

 41%|████▏     | 7767/18769 [05:24<07:45, 23.65it/s]

 41%|████▏     | 7770/18769 [05:24<07:44, 23.69it/s]

 41%|████▏     | 7773/18769 [05:24<07:44, 23.68it/s]

 41%|████▏     | 7776/18769 [05:24<07:44, 23.67it/s]

 41%|████▏     | 7779/18769 [05:24<07:44, 23.68it/s]

 41%|████▏     | 7782/18769 [05:25<07:44, 23.65it/s]

 41%|████▏     | 7785/18769 [05:25<07:43, 23.68it/s]

 41%|████▏     | 7788/18769 [05:25<07:43, 23.71it/s]

 42%|████▏     | 7791/18769 [05:25<07:42, 23.72it/s]

 42%|████▏     | 7794/18769 [05:25<07:42, 23.73it/s]

 42%|████▏     | 7797/18769 [05:25<07:42, 23.72it/s]

 42%|████▏     | 7800/18769 [05:25<07:42, 23.71it/s]

 42%|████▏     | 7803/18769 [05:25<07:43, 23.68it/s]

 42%|████▏     | 7806/18769 [05:26<07:43, 23.67it/s]

 42%|████▏     | 7809/18769 [05:26<07:41, 23.72it/s]

 42%|████▏     | 7812/18769 [05:26<07:39, 23.84it/s]

 42%|████▏     | 7815/18769 [05:26<07:38, 23.90it/s]

 42%|████▏     | 7818/18769 [05:26<07:36, 24.01it/s]

 42%|████▏     | 7821/18769 [05:26<07:34, 24.07it/s]

 42%|████▏     | 7824/18769 [05:26<07:34, 24.09it/s]

 42%|████▏     | 7827/18769 [05:26<07:33, 24.10it/s]

 42%|████▏     | 7830/18769 [05:27<07:32, 24.15it/s]

 42%|████▏     | 7833/18769 [05:27<07:32, 24.17it/s]

 42%|████▏     | 7836/18769 [05:27<07:32, 24.17it/s]

 42%|████▏     | 7839/18769 [05:27<07:33, 24.13it/s]

 42%|████▏     | 7842/18769 [05:27<07:32, 24.14it/s]

 42%|████▏     | 7845/18769 [05:27<07:32, 24.17it/s]

 42%|████▏     | 7848/18769 [05:27<07:32, 24.15it/s]

 42%|████▏     | 7851/18769 [05:27<07:32, 24.13it/s]

 42%|████▏     | 7854/18769 [05:28<07:31, 24.17it/s]

 42%|████▏     | 7857/18769 [05:28<07:32, 24.11it/s]

 42%|████▏     | 7860/18769 [05:28<07:32, 24.13it/s]

 42%|████▏     | 7863/18769 [05:28<07:31, 24.18it/s]

 42%|████▏     | 7866/18769 [05:28<07:34, 24.00it/s]

 42%|████▏     | 7870/18769 [05:28<07:02, 25.77it/s]

 42%|████▏     | 7873/18769 [05:28<07:14, 25.10it/s]

 42%|████▏     | 7876/18769 [05:28<07:21, 24.67it/s]

 42%|████▏     | 7879/18769 [05:29<07:26, 24.36it/s]

 42%|████▏     | 7882/18769 [05:29<07:30, 24.14it/s]

 42%|████▏     | 7885/18769 [05:29<07:33, 23.98it/s]

 42%|████▏     | 7888/18769 [05:29<07:35, 23.89it/s]

 42%|████▏     | 7891/18769 [05:29<07:35, 23.89it/s]

 42%|████▏     | 7894/18769 [05:29<07:35, 23.88it/s]

 42%|████▏     | 7897/18769 [05:29<07:38, 23.70it/s]

 42%|████▏     | 7900/18769 [05:29<07:38, 23.73it/s]

 42%|████▏     | 7903/18769 [05:30<07:37, 23.74it/s]

 42%|████▏     | 7906/18769 [05:30<07:36, 23.79it/s]

 42%|████▏     | 7909/18769 [05:30<07:36, 23.80it/s]

 42%|████▏     | 7912/18769 [05:30<07:35, 23.81it/s]

 42%|████▏     | 7915/18769 [05:30<07:36, 23.80it/s]

 42%|████▏     | 7918/18769 [05:30<07:35, 23.81it/s]

 42%|████▏     | 7921/18769 [05:30<07:35, 23.81it/s]

 42%|████▏     | 7924/18769 [05:30<07:35, 23.83it/s]

 42%|████▏     | 7927/18769 [05:31<07:34, 23.86it/s]

 42%|████▏     | 7930/18769 [05:31<07:34, 23.86it/s]

 42%|████▏     | 7933/18769 [05:31<07:34, 23.84it/s]

 42%|████▏     | 7936/18769 [05:31<07:36, 23.74it/s]

 42%|████▏     | 7939/18769 [05:31<07:35, 23.75it/s]

 42%|████▏     | 7942/18769 [05:31<07:36, 23.72it/s]

 42%|████▏     | 7945/18769 [05:31<07:38, 23.63it/s]

 42%|████▏     | 7948/18769 [05:31<07:34, 23.81it/s]

 42%|████▏     | 7951/18769 [05:32<07:32, 23.92it/s]

 42%|████▏     | 7954/18769 [05:32<07:31, 23.95it/s]

 42%|████▏     | 7957/18769 [05:32<07:29, 24.07it/s]

 42%|████▏     | 7960/18769 [05:32<07:27, 24.13it/s]

 42%|████▏     | 7963/18769 [05:32<07:27, 24.12it/s]

 42%|████▏     | 7966/18769 [05:32<07:26, 24.18it/s]

 42%|████▏     | 7969/18769 [05:32<07:29, 24.03it/s]

 42%|████▏     | 7972/18769 [05:32<07:28, 24.08it/s]

 42%|████▏     | 7975/18769 [05:33<07:27, 24.14it/s]

 43%|████▎     | 7978/18769 [05:33<07:25, 24.21it/s]

 43%|████▎     | 7981/18769 [05:33<07:25, 24.21it/s]

 43%|████▎     | 7984/18769 [05:33<07:25, 24.19it/s]

 43%|████▎     | 7987/18769 [05:33<07:25, 24.19it/s]

 43%|████▎     | 7990/18769 [05:33<07:25, 24.19it/s]

 43%|████▎     | 7993/18769 [05:33<07:26, 24.15it/s]

 43%|████▎     | 7996/18769 [05:33<07:25, 24.19it/s]

 43%|████▎     | 7999/18769 [05:34<07:25, 24.18it/s]

 43%|████▎     | 8002/18769 [05:34<07:27, 24.05it/s]

 43%|████▎     | 8006/18769 [05:34<06:56, 25.82it/s]

 43%|████▎     | 8009/18769 [05:34<07:09, 25.05it/s]

 43%|████▎     | 8012/18769 [05:34<07:17, 24.60it/s]

 43%|████▎     | 8015/18769 [05:34<07:23, 24.25it/s]

 43%|████▎     | 8018/18769 [05:34<07:31, 23.83it/s]

 43%|████▎     | 8021/18769 [05:34<07:33, 23.72it/s]

 43%|████▎     | 8024/18769 [05:35<07:34, 23.65it/s]

 43%|████▎     | 8027/18769 [05:35<07:34, 23.63it/s]

 43%|████▎     | 8030/18769 [05:35<07:34, 23.61it/s]

 43%|████▎     | 8033/18769 [05:35<07:34, 23.61it/s]

 43%|████▎     | 8036/18769 [05:35<07:35, 23.57it/s]

 43%|████▎     | 8039/18769 [05:35<07:35, 23.56it/s]

 43%|████▎     | 8042/18769 [05:35<07:35, 23.55it/s]

 43%|████▎     | 8045/18769 [05:35<07:34, 23.57it/s]

 43%|████▎     | 8048/18769 [05:36<07:34, 23.59it/s]

 43%|████▎     | 8051/18769 [05:36<07:34, 23.57it/s]

 43%|████▎     | 8054/18769 [05:36<07:35, 23.55it/s]

 43%|████▎     | 8057/18769 [05:36<07:33, 23.60it/s]

 43%|████▎     | 8060/18769 [05:36<07:33, 23.62it/s]

 43%|████▎     | 8063/18769 [05:36<07:32, 23.64it/s]

 43%|████▎     | 8066/18769 [05:36<07:35, 23.50it/s]

 43%|████▎     | 8069/18769 [05:36<07:34, 23.57it/s]

 43%|████▎     | 8072/18769 [05:37<07:33, 23.61it/s]

 43%|████▎     | 8075/18769 [05:37<07:31, 23.66it/s]

 43%|████▎     | 8078/18769 [05:37<07:31, 23.68it/s]

 43%|████▎     | 8081/18769 [05:37<07:32, 23.64it/s]

 43%|████▎     | 8084/18769 [05:37<07:29, 23.78it/s]

 43%|████▎     | 8087/18769 [05:37<07:27, 23.88it/s]

 43%|████▎     | 8090/18769 [05:37<07:27, 23.88it/s]

 43%|████▎     | 8093/18769 [05:37<07:26, 23.93it/s]

 43%|████▎     | 8096/18769 [05:38<07:25, 23.96it/s]

 43%|████▎     | 8099/18769 [05:38<07:25, 23.96it/s]

 43%|████▎     | 8102/18769 [05:38<07:24, 23.99it/s]

 43%|████▎     | 8105/18769 [05:38<07:23, 24.07it/s]

 43%|████▎     | 8108/18769 [05:38<07:22, 24.08it/s]

 43%|████▎     | 8111/18769 [05:38<07:22, 24.09it/s]

 43%|████▎     | 8114/18769 [05:38<07:25, 23.90it/s]

 43%|████▎     | 8117/18769 [05:38<07:25, 23.93it/s]

 43%|████▎     | 8120/18769 [05:39<07:24, 23.96it/s]

 43%|████▎     | 8123/18769 [05:39<07:23, 24.00it/s]

 43%|████▎     | 8126/18769 [05:39<07:23, 23.99it/s]

 43%|████▎     | 8129/18769 [05:39<07:23, 24.00it/s]

 43%|████▎     | 8132/18769 [05:39<07:23, 23.99it/s]

 43%|████▎     | 8135/18769 [05:39<07:22, 24.02it/s]

 43%|████▎     | 8138/18769 [05:39<07:24, 23.93it/s]

 43%|████▎     | 8141/18769 [05:40<07:27, 23.74it/s]

 43%|████▎     | 8145/18769 [05:40<06:56, 25.52it/s]

 43%|████▎     | 8148/18769 [05:40<07:08, 24.78it/s]

 43%|████▎     | 8151/18769 [05:40<07:16, 24.33it/s]

 43%|████▎     | 8154/18769 [05:40<07:22, 24.01it/s]

 43%|████▎     | 8157/18769 [05:40<07:25, 23.82it/s]

 43%|████▎     | 8160/18769 [05:40<07:27, 23.70it/s]

 43%|████▎     | 8163/18769 [05:40<07:31, 23.48it/s]

 44%|████▎     | 8166/18769 [05:41<07:31, 23.50it/s]

 44%|████▎     | 8169/18769 [05:41<07:30, 23.51it/s]

 44%|████▎     | 8172/18769 [05:41<07:30, 23.51it/s]

 44%|████▎     | 8175/18769 [05:41<07:31, 23.48it/s]

 44%|████▎     | 8178/18769 [05:41<07:30, 23.50it/s]

 44%|████▎     | 8181/18769 [05:41<07:30, 23.52it/s]

 44%|████▎     | 8184/18769 [05:41<07:29, 23.55it/s]

 44%|████▎     | 8187/18769 [05:41<07:29, 23.54it/s]

 44%|████▎     | 8190/18769 [05:42<07:29, 23.55it/s]

 44%|████▎     | 8193/18769 [05:42<07:28, 23.56it/s]

 44%|████▎     | 8196/18769 [05:42<07:28, 23.56it/s]

 44%|████▎     | 8199/18769 [05:42<07:28, 23.58it/s]

 44%|████▎     | 8202/18769 [05:42<07:27, 23.59it/s]

 44%|████▎     | 8205/18769 [05:42<07:27, 23.59it/s]

 44%|████▎     | 8208/18769 [05:42<07:29, 23.52it/s]

 44%|████▎     | 8211/18769 [05:42<07:31, 23.39it/s]

 44%|████▍     | 8214/18769 [05:43<07:30, 23.42it/s]

 44%|████▍     | 8217/18769 [05:43<07:37, 23.05it/s]

 44%|████▍     | 8220/18769 [05:43<07:33, 23.24it/s]

 44%|████▍     | 8223/18769 [05:43<07:30, 23.41it/s]

 44%|████▍     | 8226/18769 [05:43<07:27, 23.57it/s]

 44%|████▍     | 8229/18769 [05:43<07:24, 23.72it/s]

 44%|████▍     | 8232/18769 [05:43<07:24, 23.69it/s]

 44%|████▍     | 8235/18769 [05:43<07:23, 23.77it/s]

 44%|████▍     | 8238/18769 [05:44<07:21, 23.85it/s]

 44%|████▍     | 8241/18769 [05:44<07:24, 23.69it/s]

 44%|████▍     | 8244/18769 [05:44<07:22, 23.80it/s]

 44%|████▍     | 8247/18769 [05:44<07:21, 23.85it/s]

 44%|████▍     | 8250/18769 [05:44<07:19, 23.95it/s]

 44%|████▍     | 8253/18769 [05:44<07:18, 23.98it/s]

 44%|████▍     | 8256/18769 [05:44<07:17, 24.01it/s]

 44%|████▍     | 8259/18769 [05:44<07:18, 23.98it/s]

 44%|████▍     | 8262/18769 [05:45<07:18, 23.99it/s]

 44%|████▍     | 8265/18769 [05:45<07:26, 23.50it/s]

 44%|████▍     | 8268/18769 [05:45<07:22, 23.71it/s]

 44%|████▍     | 8271/18769 [05:45<07:20, 23.83it/s]

 44%|████▍     | 8274/18769 [05:45<07:18, 23.92it/s]

 44%|████▍     | 8277/18769 [05:45<07:21, 23.79it/s]

 44%|████▍     | 8280/18769 [05:45<07:26, 23.49it/s]

 44%|████▍     | 8284/18769 [05:45<06:53, 25.37it/s]

 44%|████▍     | 8287/18769 [05:46<07:03, 24.75it/s]

 44%|████▍     | 8290/18769 [05:46<07:10, 24.35it/s]

 44%|████▍     | 8293/18769 [05:46<07:15, 24.07it/s]

 44%|████▍     | 8296/18769 [05:46<07:18, 23.90it/s]

 44%|████▍     | 8299/18769 [05:46<07:20, 23.79it/s]

 44%|████▍     | 8302/18769 [05:46<07:20, 23.74it/s]

 44%|████▍     | 8305/18769 [05:46<07:21, 23.69it/s]

 44%|████▍     | 8308/18769 [05:47<07:22, 23.66it/s]

 44%|████▍     | 8311/18769 [05:47<07:23, 23.59it/s]

 44%|████▍     | 8314/18769 [05:47<07:23, 23.59it/s]

 44%|████▍     | 8317/18769 [05:47<07:22, 23.59it/s]

 44%|████▍     | 8320/18769 [05:47<07:23, 23.54it/s]

 44%|████▍     | 8323/18769 [05:47<07:22, 23.58it/s]

 44%|████▍     | 8326/18769 [05:47<07:22, 23.59it/s]

 44%|████▍     | 8329/18769 [05:47<07:22, 23.58it/s]

 44%|████▍     | 8332/18769 [05:48<07:22, 23.58it/s]

 44%|████▍     | 8335/18769 [05:48<07:22, 23.60it/s]

 44%|████▍     | 8338/18769 [05:48<07:21, 23.61it/s]

 44%|████▍     | 8341/18769 [05:48<07:21, 23.59it/s]

 44%|████▍     | 8344/18769 [05:48<07:26, 23.33it/s]

 44%|████▍     | 8347/18769 [05:48<07:24, 23.43it/s]

 44%|████▍     | 8350/18769 [05:48<07:25, 23.38it/s]

 45%|████▍     | 8353/18769 [05:48<07:27, 23.26it/s]

 45%|████▍     | 8356/18769 [05:49<07:24, 23.43it/s]

 45%|████▍     | 8359/18769 [05:49<07:21, 23.57it/s]

 45%|████▍     | 8362/18769 [05:49<07:18, 23.76it/s]

 45%|████▍     | 8365/18769 [05:49<07:15, 23.87it/s]

 45%|████▍     | 8368/18769 [05:49<07:13, 23.98it/s]

 45%|████▍     | 8371/18769 [05:49<07:13, 23.99it/s]

 45%|████▍     | 8374/18769 [05:49<07:13, 23.99it/s]

 45%|████▍     | 8377/18769 [05:49<07:12, 24.05it/s]

 45%|████▍     | 8380/18769 [05:50<07:11, 24.09it/s]

 45%|████▍     | 8383/18769 [05:50<07:10, 24.10it/s]

 45%|████▍     | 8386/18769 [05:50<07:10, 24.10it/s]

 45%|████▍     | 8389/18769 [05:50<07:09, 24.15it/s]

 45%|████▍     | 8392/18769 [05:50<07:10, 24.13it/s]

 45%|████▍     | 8395/18769 [05:50<07:09, 24.14it/s]

 45%|████▍     | 8398/18769 [05:50<07:09, 24.12it/s]

 45%|████▍     | 8401/18769 [05:50<07:12, 23.96it/s]

 45%|████▍     | 8404/18769 [05:51<07:12, 23.99it/s]

 45%|████▍     | 8407/18769 [05:51<07:11, 24.02it/s]

 45%|████▍     | 8410/18769 [05:51<07:10, 24.04it/s]

 45%|████▍     | 8413/18769 [05:51<07:12, 23.97it/s]

 45%|████▍     | 8416/18769 [05:51<07:14, 23.84it/s]

 45%|████▍     | 8420/18769 [05:51<06:42, 25.70it/s]

 45%|████▍     | 8423/18769 [05:51<06:54, 24.96it/s]

 45%|████▍     | 8426/18769 [05:51<07:02, 24.46it/s]

 45%|████▍     | 8429/18769 [05:52<07:07, 24.16it/s]

 45%|████▍     | 8432/18769 [05:52<07:13, 23.85it/s]

 45%|████▍     | 8435/18769 [05:52<07:15, 23.70it/s]

 45%|████▍     | 8438/18769 [05:52<07:15, 23.70it/s]

 45%|████▍     | 8441/18769 [05:52<07:15, 23.69it/s]

 45%|████▍     | 8444/18769 [05:52<07:16, 23.66it/s]

 45%|████▌     | 8447/18769 [05:52<07:19, 23.49it/s]

 45%|████▌     | 8450/18769 [05:52<07:18, 23.52it/s]

 45%|████▌     | 8453/18769 [05:53<07:17, 23.58it/s]

 45%|████▌     | 8456/18769 [05:53<07:17, 23.59it/s]

 45%|████▌     | 8459/18769 [05:53<07:16, 23.62it/s]

 45%|████▌     | 8462/18769 [05:53<07:15, 23.65it/s]

 45%|████▌     | 8465/18769 [05:53<07:14, 23.69it/s]

 45%|████▌     | 8468/18769 [05:53<07:14, 23.71it/s]

 45%|████▌     | 8471/18769 [05:53<07:14, 23.69it/s]

 45%|████▌     | 8474/18769 [05:53<07:13, 23.73it/s]

 45%|████▌     | 8477/18769 [05:54<07:13, 23.74it/s]

 45%|████▌     | 8480/18769 [05:54<07:13, 23.72it/s]

 45%|████▌     | 8483/18769 [05:54<07:13, 23.72it/s]

 45%|████▌     | 8486/18769 [05:54<07:13, 23.75it/s]

 45%|████▌     | 8489/18769 [05:54<07:12, 23.76it/s]

 45%|████▌     | 8492/18769 [05:54<07:12, 23.76it/s]

 45%|████▌     | 8495/18769 [05:54<07:10, 23.89it/s]

 45%|████▌     | 8498/18769 [05:54<07:07, 24.05it/s]

 45%|████▌     | 8501/18769 [05:55<07:06, 24.10it/s]

 45%|████▌     | 8504/18769 [05:55<07:05, 24.15it/s]

 45%|████▌     | 8507/18769 [05:55<07:04, 24.17it/s]

 45%|████▌     | 8510/18769 [05:55<07:04, 24.19it/s]

 45%|████▌     | 8513/18769 [05:55<07:03, 24.23it/s]

 45%|████▌     | 8516/18769 [05:55<07:02, 24.25it/s]

 45%|████▌     | 8519/18769 [05:55<07:03, 24.22it/s]

 45%|████▌     | 8522/18769 [05:55<07:03, 24.19it/s]

 45%|████▌     | 8525/18769 [05:56<07:02, 24.25it/s]

 45%|████▌     | 8528/18769 [05:56<07:03, 24.19it/s]

 45%|████▌     | 8531/18769 [05:56<07:02, 24.24it/s]

 45%|████▌     | 8534/18769 [05:56<07:02, 24.24it/s]

 45%|████▌     | 8537/18769 [05:56<07:02, 24.22it/s]

 46%|████▌     | 8540/18769 [05:56<07:01, 24.25it/s]

 46%|████▌     | 8543/18769 [05:56<07:01, 24.26it/s]

 46%|████▌     | 8546/18769 [05:56<07:03, 24.14it/s]

 46%|████▌     | 8549/18769 [05:57<07:04, 24.07it/s]

 46%|████▌     | 8552/18769 [05:57<07:07, 23.92it/s]

 46%|████▌     | 8555/18769 [05:57<07:09, 23.80it/s]

 46%|████▌     | 8559/18769 [05:57<06:38, 25.63it/s]

 46%|████▌     | 8562/18769 [05:57<06:49, 24.92it/s]

 46%|████▌     | 8565/18769 [05:57<06:57, 24.42it/s]

 46%|████▌     | 8568/18769 [05:57<07:03, 24.08it/s]

 46%|████▌     | 8571/18769 [05:57<07:07, 23.83it/s]

 46%|████▌     | 8574/18769 [05:58<07:09, 23.76it/s]

 46%|████▌     | 8577/18769 [05:58<07:08, 23.77it/s]

 46%|████▌     | 8580/18769 [05:58<07:08, 23.75it/s]

 46%|████▌     | 8583/18769 [05:58<07:09, 23.73it/s]

 46%|████▌     | 8586/18769 [05:58<07:08, 23.75it/s]

 46%|████▌     | 8589/18769 [05:58<07:08, 23.74it/s]

 46%|████▌     | 8592/18769 [05:58<07:08, 23.73it/s]

 46%|████▌     | 8595/18769 [05:58<07:09, 23.69it/s]

 46%|████▌     | 8598/18769 [05:59<07:08, 23.71it/s]

 46%|████▌     | 8601/18769 [05:59<07:08, 23.74it/s]

 46%|████▌     | 8604/18769 [05:59<07:08, 23.72it/s]

 46%|████▌     | 8607/18769 [05:59<07:09, 23.67it/s]

 46%|████▌     | 8610/18769 [05:59<07:08, 23.70it/s]

 46%|████▌     | 8613/18769 [05:59<07:07, 23.74it/s]

 46%|████▌     | 8616/18769 [05:59<07:07, 23.73it/s]

 46%|████▌     | 8619/18769 [05:59<07:07, 23.74it/s]

 46%|████▌     | 8622/18769 [06:00<07:06, 23.77it/s]

 46%|████▌     | 8625/18769 [06:00<07:06, 23.77it/s]

 46%|████▌     | 8628/18769 [06:00<07:06, 23.79it/s]

 46%|████▌     | 8631/18769 [06:00<07:03, 23.95it/s]

 46%|████▌     | 8634/18769 [06:00<07:02, 24.01it/s]

 46%|████▌     | 8637/18769 [06:00<07:00, 24.07it/s]

 46%|████▌     | 8640/18769 [06:00<07:00, 24.11it/s]

 46%|████▌     | 8643/18769 [06:00<06:59, 24.13it/s]

 46%|████▌     | 8646/18769 [06:01<06:59, 24.14it/s]

 46%|████▌     | 8649/18769 [06:01<06:58, 24.17it/s]

 46%|████▌     | 8652/18769 [06:01<06:58, 24.19it/s]

 46%|████▌     | 8655/18769 [06:01<06:57, 24.21it/s]

 46%|████▌     | 8658/18769 [06:01<06:57, 24.22it/s]

 46%|████▌     | 8661/18769 [06:01<06:57, 24.21it/s]

 46%|████▌     | 8664/18769 [06:01<06:56, 24.24it/s]

 46%|████▌     | 8667/18769 [06:01<06:56, 24.25it/s]

 46%|████▌     | 8670/18769 [06:02<06:56, 24.23it/s]

 46%|████▌     | 8673/18769 [06:02<06:56, 24.22it/s]

 46%|████▌     | 8676/18769 [06:02<06:55, 24.28it/s]

 46%|████▌     | 8679/18769 [06:02<06:55, 24.29it/s]

 46%|████▋     | 8682/18769 [06:02<06:55, 24.28it/s]

 46%|████▋     | 8685/18769 [06:02<06:55, 24.27it/s]

 46%|████▋     | 8688/18769 [06:02<06:58, 24.08it/s]

 46%|████▋     | 8691/18769 [06:02<07:00, 23.96it/s]

 46%|████▋     | 8694/18769 [06:03<07:02, 23.85it/s]

 46%|████▋     | 8698/18769 [06:03<06:31, 25.71it/s]

 46%|████▋     | 8701/18769 [06:03<06:42, 25.01it/s]

 46%|████▋     | 8704/18769 [06:03<06:51, 24.48it/s]

 46%|████▋     | 8707/18769 [06:03<06:56, 24.18it/s]

 46%|████▋     | 8710/18769 [06:03<06:59, 23.98it/s]

 46%|████▋     | 8713/18769 [06:03<06:59, 23.95it/s]

 46%|████▋     | 8716/18769 [06:03<07:01, 23.87it/s]

 46%|████▋     | 8719/18769 [06:04<07:01, 23.82it/s]

 46%|████▋     | 8722/18769 [06:04<07:03, 23.74it/s]

 46%|████▋     | 8725/18769 [06:04<07:05, 23.63it/s]

 47%|████▋     | 8728/18769 [06:04<07:04, 23.64it/s]

 47%|████▋     | 8731/18769 [06:04<07:03, 23.69it/s]

 47%|████▋     | 8734/18769 [06:04<07:03, 23.70it/s]

 47%|████▋     | 8737/18769 [06:04<07:05, 23.56it/s]

 47%|████▋     | 8740/18769 [06:05<07:08, 23.42it/s]

 47%|████▋     | 8743/18769 [06:05<07:07, 23.47it/s]

 47%|████▋     | 8746/18769 [06:05<07:06, 23.51it/s]

 47%|████▋     | 8749/18769 [06:05<07:04, 23.58it/s]

 47%|████▋     | 8752/18769 [06:05<07:03, 23.63it/s]

 47%|████▋     | 8755/18769 [06:05<07:03, 23.65it/s]

 47%|████▋     | 8758/18769 [06:05<07:03, 23.63it/s]

 47%|████▋     | 8761/18769 [06:05<07:03, 23.65it/s]

 47%|████▋     | 8764/18769 [06:06<07:03, 23.64it/s]

 47%|████▋     | 8767/18769 [06:06<07:03, 23.64it/s]

 47%|████▋     | 8770/18769 [06:06<07:00, 23.77it/s]

 47%|████▋     | 8773/18769 [06:06<06:58, 23.86it/s]

 47%|████▋     | 8776/18769 [06:06<06:57, 23.93it/s]

 47%|████▋     | 8779/18769 [06:06<06:56, 23.99it/s]

 47%|████▋     | 8782/18769 [06:06<06:55, 24.02it/s]

 47%|████▋     | 8785/18769 [06:06<06:54, 24.10it/s]

 47%|████▋     | 8788/18769 [06:07<06:53, 24.13it/s]

 47%|████▋     | 8791/18769 [06:07<06:53, 24.14it/s]

 47%|████▋     | 8794/18769 [06:07<06:53, 24.14it/s]

 47%|████▋     | 8797/18769 [06:07<06:53, 24.11it/s]

 47%|████▋     | 8800/18769 [06:07<06:53, 24.11it/s]

 47%|████▋     | 8803/18769 [06:07<06:53, 24.11it/s]

 47%|████▋     | 8806/18769 [06:07<06:52, 24.14it/s]

 47%|████▋     | 8809/18769 [06:07<06:53, 24.10it/s]

 47%|████▋     | 8812/18769 [06:08<06:53, 24.08it/s]

 47%|████▋     | 8815/18769 [06:08<06:54, 24.04it/s]

 47%|████▋     | 8818/18769 [06:08<06:53, 24.06it/s]

 47%|████▋     | 8821/18769 [06:08<06:52, 24.10it/s]

 47%|████▋     | 8824/18769 [06:08<06:54, 23.99it/s]

 47%|████▋     | 8827/18769 [06:08<06:56, 23.88it/s]

 47%|████▋     | 8830/18769 [06:08<06:57, 23.79it/s]

 47%|████▋     | 8834/18769 [06:08<06:27, 25.62it/s]

 47%|████▋     | 8837/18769 [06:09<06:38, 24.94it/s]

 47%|████▋     | 8840/18769 [06:09<06:46, 24.45it/s]

 47%|████▋     | 8843/18769 [06:09<06:51, 24.11it/s]

 47%|████▋     | 8846/18769 [06:09<06:54, 23.94it/s]

 47%|████▋     | 8849/18769 [06:09<06:55, 23.90it/s]

 47%|████▋     | 8852/18769 [06:09<06:55, 23.85it/s]

 47%|████▋     | 8855/18769 [06:09<06:56, 23.80it/s]

 47%|████▋     | 8858/18769 [06:09<06:56, 23.80it/s]

 47%|████▋     | 8861/18769 [06:10<06:59, 23.64it/s]

 47%|████▋     | 8864/18769 [06:10<07:02, 23.45it/s]

 47%|████▋     | 8867/18769 [06:10<07:10, 23.00it/s]

 47%|████▋     | 8870/18769 [06:10<07:11, 22.92it/s]

 47%|████▋     | 8873/18769 [06:10<07:07, 23.16it/s]

 47%|████▋     | 8876/18769 [06:10<07:04, 23.30it/s]

 47%|████▋     | 8879/18769 [06:10<07:03, 23.36it/s]

 47%|████▋     | 8882/18769 [06:10<07:01, 23.45it/s]

 47%|████▋     | 8885/18769 [06:11<07:00, 23.51it/s]

 47%|████▋     | 8888/18769 [06:11<07:00, 23.52it/s]

 47%|████▋     | 8891/18769 [06:11<07:00, 23.49it/s]

 47%|████▋     | 8894/18769 [06:11<07:01, 23.44it/s]

 47%|████▋     | 8897/18769 [06:11<07:00, 23.49it/s]

 47%|████▋     | 8900/18769 [06:11<06:59, 23.53it/s]

 47%|████▋     | 8903/18769 [06:11<06:58, 23.57it/s]

 47%|████▋     | 8906/18769 [06:11<06:55, 23.77it/s]

 47%|████▋     | 8909/18769 [06:12<06:56, 23.68it/s]

 47%|████▋     | 8912/18769 [06:12<06:58, 23.58it/s]

 47%|████▋     | 8915/18769 [06:12<06:55, 23.70it/s]

 48%|████▊     | 8918/18769 [06:12<06:53, 23.80it/s]

 48%|████▊     | 8921/18769 [06:12<06:51, 23.91it/s]

 48%|████▊     | 8924/18769 [06:12<06:50, 23.98it/s]

 48%|████▊     | 8927/18769 [06:12<06:51, 23.94it/s]

 48%|████▊     | 8930/18769 [06:12<06:50, 23.99it/s]

 48%|████▊     | 8933/18769 [06:13<06:49, 24.04it/s]

 48%|████▊     | 8936/18769 [06:13<06:49, 24.04it/s]

 48%|████▊     | 8939/18769 [06:13<06:55, 23.69it/s]

 48%|████▊     | 8942/18769 [06:13<06:52, 23.80it/s]

 48%|████▊     | 8945/18769 [06:13<06:51, 23.88it/s]

 48%|████▊     | 8948/18769 [06:13<06:49, 23.98it/s]

 48%|████▊     | 8951/18769 [06:13<06:48, 24.05it/s]

 48%|████▊     | 8954/18769 [06:13<06:46, 24.12it/s]

 48%|████▊     | 8957/18769 [06:14<06:46, 24.12it/s]

 48%|████▊     | 8960/18769 [06:14<06:47, 24.08it/s]

 48%|████▊     | 8963/18769 [06:14<06:49, 23.94it/s]

 48%|████▊     | 8966/18769 [06:14<06:51, 23.82it/s]

 48%|████▊     | 8969/18769 [06:14<06:53, 23.73it/s]

 48%|████▊     | 8973/18769 [06:14<06:22, 25.60it/s]

 48%|████▊     | 8976/18769 [06:14<06:32, 24.92it/s]

 48%|████▊     | 8979/18769 [06:14<06:39, 24.49it/s]

 48%|████▊     | 8982/18769 [06:15<06:44, 24.17it/s]

 48%|████▊     | 8985/18769 [06:15<06:47, 24.02it/s]

 48%|████▊     | 8988/18769 [06:15<06:48, 23.96it/s]

 48%|████▊     | 8991/18769 [06:15<06:49, 23.90it/s]

 48%|████▊     | 8994/18769 [06:15<06:50, 23.83it/s]

 48%|████▊     | 8997/18769 [06:15<06:49, 23.85it/s]

 48%|████▊     | 9000/18769 [06:15<06:50, 23.82it/s]

 48%|████▊     | 9003/18769 [06:16<06:49, 23.82it/s]

 48%|████▊     | 9006/18769 [06:16<06:53, 23.62it/s]

 48%|████▊     | 9009/18769 [06:16<06:52, 23.64it/s]

 48%|████▊     | 9012/18769 [06:16<06:51, 23.69it/s]

 48%|████▊     | 9015/18769 [06:16<06:52, 23.67it/s]

 48%|████▊     | 9018/18769 [06:16<06:51, 23.69it/s]

 48%|████▊     | 9021/18769 [06:16<06:51, 23.68it/s]

 48%|████▊     | 9024/18769 [06:16<06:52, 23.60it/s]

 48%|████▊     | 9027/18769 [06:17<06:52, 23.64it/s]

 48%|████▊     | 9030/18769 [06:17<06:50, 23.71it/s]

 48%|████▊     | 9033/18769 [06:17<06:49, 23.75it/s]

 48%|████▊     | 9036/18769 [06:17<06:50, 23.73it/s]

 48%|████▊     | 9039/18769 [06:17<06:49, 23.77it/s]

 48%|████▊     | 9042/18769 [06:17<06:47, 23.89it/s]

 48%|████▊     | 9045/18769 [06:17<06:45, 24.01it/s]

 48%|████▊     | 9048/18769 [06:17<06:42, 24.13it/s]

 48%|████▊     | 9051/18769 [06:18<06:41, 24.20it/s]

 48%|████▊     | 9054/18769 [06:18<06:40, 24.24it/s]

 48%|████▊     | 9057/18769 [06:18<06:40, 24.28it/s]

 48%|████▊     | 9060/18769 [06:18<06:39, 24.30it/s]

 48%|████▊     | 9063/18769 [06:18<06:39, 24.32it/s]

 48%|████▊     | 9066/18769 [06:18<06:38, 24.35it/s]

 48%|████▊     | 9069/18769 [06:18<06:37, 24.38it/s]

 48%|████▊     | 9072/18769 [06:18<06:38, 24.36it/s]

 48%|████▊     | 9075/18769 [06:19<06:37, 24.37it/s]

 48%|████▊     | 9078/18769 [06:19<06:37, 24.35it/s]

 48%|████▊     | 9081/18769 [06:19<06:39, 24.27it/s]

 48%|████▊     | 9084/18769 [06:19<06:39, 24.25it/s]

 48%|████▊     | 9087/18769 [06:19<06:39, 24.25it/s]

 48%|████▊     | 9090/18769 [06:19<06:38, 24.27it/s]

 48%|████▊     | 9093/18769 [06:19<06:37, 24.32it/s]

 48%|████▊     | 9096/18769 [06:19<06:37, 24.34it/s]

 48%|████▊     | 9099/18769 [06:19<06:40, 24.13it/s]

 48%|████▊     | 9102/18769 [06:20<06:45, 23.84it/s]

 49%|████▊     | 9105/18769 [06:20<06:47, 23.70it/s]

 49%|████▊     | 9108/18769 [06:20<06:48, 23.67it/s]

 49%|████▊     | 9112/18769 [06:20<06:17, 25.57it/s]

 49%|████▊     | 9115/18769 [06:20<06:27, 24.90it/s]

 49%|████▊     | 9118/18769 [06:20<06:43, 23.93it/s]

 49%|████▊     | 9121/18769 [06:20<06:44, 23.83it/s]

 49%|████▊     | 9124/18769 [06:21<06:44, 23.84it/s]

 49%|████▊     | 9127/18769 [06:21<06:45, 23.75it/s]

 49%|████▊     | 9130/18769 [06:21<06:46, 23.73it/s]

 49%|████▊     | 9133/18769 [06:21<06:45, 23.76it/s]

 49%|████▊     | 9136/18769 [06:21<06:45, 23.78it/s]

 49%|████▊     | 9139/18769 [06:21<06:44, 23.83it/s]

 49%|████▊     | 9142/18769 [06:21<06:44, 23.82it/s]

 49%|████▊     | 9145/18769 [06:21<06:43, 23.87it/s]

 49%|████▊     | 9148/18769 [06:22<06:43, 23.86it/s]

 49%|████▉     | 9151/18769 [06:22<06:46, 23.67it/s]

 49%|████▉     | 9154/18769 [06:22<06:45, 23.73it/s]

 49%|████▉     | 9157/18769 [06:22<06:44, 23.77it/s]

 49%|████▉     | 9160/18769 [06:22<06:42, 23.86it/s]

 49%|████▉     | 9163/18769 [06:22<06:42, 23.86it/s]

 49%|████▉     | 9166/18769 [06:22<06:42, 23.88it/s]

 49%|████▉     | 9169/18769 [06:22<06:43, 23.79it/s]

 49%|████▉     | 9172/18769 [06:23<06:42, 23.86it/s]

 49%|████▉     | 9175/18769 [06:23<06:42, 23.85it/s]

 49%|████▉     | 9178/18769 [06:23<06:41, 23.89it/s]

 49%|████▉     | 9181/18769 [06:23<06:40, 23.95it/s]

 49%|████▉     | 9184/18769 [06:23<06:39, 23.98it/s]

 49%|████▉     | 9187/18769 [06:23<06:38, 24.03it/s]

 49%|████▉     | 9190/18769 [06:23<06:40, 23.94it/s]

 49%|████▉     | 9193/18769 [06:23<06:39, 23.94it/s]

 49%|████▉     | 9196/18769 [06:24<06:38, 23.99it/s]

 49%|████▉     | 9199/18769 [06:24<06:40, 23.92it/s]

 49%|████▉     | 9202/18769 [06:24<06:38, 23.98it/s]

 49%|████▉     | 9205/18769 [06:24<06:37, 24.06it/s]

 49%|████▉     | 9208/18769 [06:24<06:36, 24.11it/s]

 49%|████▉     | 9211/18769 [06:24<06:35, 24.15it/s]

 49%|████▉     | 9214/18769 [06:24<06:35, 24.15it/s]

 49%|████▉     | 9217/18769 [06:24<06:35, 24.15it/s]

 49%|████▉     | 9220/18769 [06:25<06:35, 24.14it/s]

 49%|████▉     | 9223/18769 [06:25<06:35, 24.15it/s]

 49%|████▉     | 9226/18769 [06:25<06:35, 24.14it/s]

 49%|████▉     | 9229/18769 [06:25<06:35, 24.10it/s]

 49%|████▉     | 9232/18769 [06:25<06:35, 24.12it/s]

 49%|████▉     | 9235/18769 [06:25<06:36, 24.04it/s]

 49%|████▉     | 9238/18769 [06:25<06:39, 23.87it/s]

 49%|████▉     | 9241/18769 [06:25<06:40, 23.78it/s]

 49%|████▉     | 9244/18769 [06:26<06:42, 23.69it/s]

 49%|████▉     | 9248/18769 [06:26<06:13, 25.50it/s]

 49%|████▉     | 9251/18769 [06:26<06:23, 24.84it/s]

 49%|████▉     | 9254/18769 [06:26<06:30, 24.38it/s]

 49%|████▉     | 9257/18769 [06:26<06:34, 24.09it/s]

 49%|████▉     | 9260/18769 [06:26<06:35, 24.02it/s]

 49%|████▉     | 9263/18769 [06:26<06:37, 23.93it/s]

 49%|████▉     | 9266/18769 [06:26<06:37, 23.88it/s]

 49%|████▉     | 9269/18769 [06:27<06:38, 23.82it/s]

 49%|████▉     | 9272/18769 [06:27<06:39, 23.78it/s]

 49%|████▉     | 9275/18769 [06:27<06:39, 23.77it/s]

 49%|████▉     | 9278/18769 [06:27<06:39, 23.74it/s]

 49%|████▉     | 9281/18769 [06:27<06:39, 23.73it/s]

 49%|████▉     | 9284/18769 [06:27<06:39, 23.76it/s]

 49%|████▉     | 9287/18769 [06:27<06:39, 23.71it/s]

 49%|████▉     | 9290/18769 [06:27<06:40, 23.69it/s]

 50%|████▉     | 9293/18769 [06:28<06:39, 23.74it/s]

 50%|████▉     | 9296/18769 [06:28<06:42, 23.55it/s]

 50%|████▉     | 9299/18769 [06:28<06:41, 23.60it/s]

 50%|████▉     | 9302/18769 [06:28<06:40, 23.64it/s]

 50%|████▉     | 9305/18769 [06:28<06:40, 23.65it/s]

 50%|████▉     | 9308/18769 [06:28<06:38, 23.73it/s]

 50%|████▉     | 9311/18769 [06:28<06:38, 23.73it/s]

 50%|████▉     | 9314/18769 [06:28<06:38, 23.72it/s]

 50%|████▉     | 9317/18769 [06:29<06:36, 23.83it/s]

 50%|████▉     | 9320/18769 [06:29<06:35, 23.87it/s]

 50%|████▉     | 9323/18769 [06:29<06:34, 23.94it/s]

 50%|████▉     | 9326/18769 [06:29<06:32, 24.03it/s]

 50%|████▉     | 9329/18769 [06:29<06:32, 24.05it/s]

 50%|████▉     | 9332/18769 [06:29<06:31, 24.07it/s]

 50%|████▉     | 9335/18769 [06:29<06:31, 24.08it/s]

 50%|████▉     | 9338/18769 [06:29<06:30, 24.13it/s]

 50%|████▉     | 9341/18769 [06:30<06:29, 24.18it/s]

 50%|████▉     | 9344/18769 [06:30<06:33, 23.92it/s]

 50%|████▉     | 9347/18769 [06:30<06:33, 23.96it/s]

 50%|████▉     | 9350/18769 [06:30<06:32, 23.98it/s]

 50%|████▉     | 9353/18769 [06:30<06:31, 24.03it/s]

 50%|████▉     | 9356/18769 [06:30<06:30, 24.08it/s]

 50%|████▉     | 9359/18769 [06:30<06:30, 24.10it/s]

 50%|████▉     | 9362/18769 [06:30<06:30, 24.12it/s]

 50%|████▉     | 9365/18769 [06:31<06:29, 24.17it/s]

 50%|████▉     | 9368/18769 [06:31<06:29, 24.15it/s]

 50%|████▉     | 9371/18769 [06:31<06:30, 24.04it/s]

 50%|████▉     | 9374/18769 [06:31<06:33, 23.89it/s]

 50%|████▉     | 9377/18769 [06:31<06:34, 23.81it/s]

 50%|████▉     | 9380/18769 [06:31<06:35, 23.74it/s]

 50%|████▉     | 9383/18769 [06:31<06:36, 23.70it/s]

 50%|█████     | 9387/18769 [06:31<06:06, 25.58it/s]

 50%|█████     | 9390/18769 [06:32<06:16, 24.93it/s]

 50%|█████     | 9393/18769 [06:32<06:26, 24.26it/s]

 50%|█████     | 9396/18769 [06:32<06:29, 24.06it/s]

 50%|█████     | 9399/18769 [06:32<06:30, 24.02it/s]

 50%|█████     | 9402/18769 [06:32<06:30, 23.96it/s]

 50%|█████     | 9405/18769 [06:32<06:31, 23.92it/s]

 50%|█████     | 9408/18769 [06:32<06:32, 23.84it/s]

 50%|█████     | 9411/18769 [06:32<06:32, 23.85it/s]

 50%|█████     | 9414/18769 [06:33<06:32, 23.86it/s]

 50%|█████     | 9417/18769 [06:33<06:34, 23.72it/s]

 50%|█████     | 9420/18769 [06:33<06:33, 23.77it/s]

 50%|█████     | 9423/18769 [06:33<06:32, 23.81it/s]

 50%|█████     | 9426/18769 [06:33<06:32, 23.80it/s]

 50%|█████     | 9429/18769 [06:33<06:31, 23.83it/s]

 50%|█████     | 9432/18769 [06:33<06:31, 23.83it/s]

 50%|█████     | 9435/18769 [06:33<06:32, 23.78it/s]

 50%|█████     | 9438/18769 [06:34<06:32, 23.78it/s]

 50%|█████     | 9441/18769 [06:34<06:34, 23.62it/s]

 50%|█████     | 9444/18769 [06:34<06:33, 23.67it/s]

 50%|█████     | 9447/18769 [06:34<06:33, 23.69it/s]

 50%|█████     | 9450/18769 [06:34<06:33, 23.70it/s]

 50%|█████     | 9453/18769 [06:34<06:31, 23.80it/s]

 50%|█████     | 9456/18769 [06:34<06:30, 23.85it/s]

 50%|█████     | 9459/18769 [06:34<06:29, 23.92it/s]

 50%|█████     | 9462/18769 [06:35<06:28, 23.97it/s]

 50%|█████     | 9465/18769 [06:35<06:27, 23.99it/s]

 50%|█████     | 9468/18769 [06:35<06:27, 23.98it/s]

 50%|█████     | 9471/18769 [06:35<06:27, 24.00it/s]

 50%|█████     | 9474/18769 [06:35<06:27, 24.01it/s]

 50%|█████     | 9477/18769 [06:35<06:26, 24.05it/s]

 51%|█████     | 9480/18769 [06:35<06:25, 24.07it/s]

 51%|█████     | 9483/18769 [06:35<06:25, 24.08it/s]

 51%|█████     | 9486/18769 [06:36<06:26, 24.04it/s]

 51%|█████     | 9489/18769 [06:36<06:29, 23.85it/s]

 51%|█████     | 9492/18769 [06:36<06:27, 23.92it/s]

 51%|█████     | 9495/18769 [06:36<06:27, 23.94it/s]

 51%|█████     | 9498/18769 [06:36<06:26, 23.99it/s]

 51%|█████     | 9501/18769 [06:36<06:26, 24.01it/s]

 51%|█████     | 9504/18769 [06:36<06:25, 24.03it/s]

 51%|█████     | 9507/18769 [06:36<06:25, 24.05it/s]

 51%|█████     | 9510/18769 [06:37<06:27, 23.87it/s]

 51%|█████     | 9513/18769 [06:37<06:29, 23.75it/s]

 51%|█████     | 9516/18769 [06:37<06:32, 23.58it/s]

 51%|█████     | 9519/18769 [06:37<06:33, 23.53it/s]

 51%|█████     | 9522/18769 [06:37<06:33, 23.50it/s]

 51%|█████     | 9526/18769 [06:37<06:04, 25.35it/s]

 51%|█████     | 9529/18769 [06:37<06:13, 24.72it/s]

 51%|█████     | 9532/18769 [06:38<06:20, 24.30it/s]

 51%|█████     | 9535/18769 [06:38<06:23, 24.10it/s]

 51%|█████     | 9538/18769 [06:38<06:27, 23.80it/s]

 51%|█████     | 9541/18769 [06:38<06:28, 23.74it/s]

 51%|█████     | 9544/18769 [06:38<06:29, 23.69it/s]

 51%|█████     | 9547/18769 [06:38<06:29, 23.69it/s]

 51%|█████     | 9550/18769 [06:38<06:28, 23.72it/s]

 51%|█████     | 9553/18769 [06:38<06:28, 23.71it/s]

 51%|█████     | 9556/18769 [06:39<06:28, 23.71it/s]

 51%|█████     | 9559/18769 [06:39<06:28, 23.71it/s]

 51%|█████     | 9562/18769 [06:39<06:28, 23.69it/s]

 51%|█████     | 9565/18769 [06:39<06:28, 23.68it/s]

 51%|█████     | 9568/18769 [06:39<06:28, 23.66it/s]

 51%|█████     | 9571/18769 [06:39<06:28, 23.66it/s]

 51%|█████     | 9574/18769 [06:39<06:28, 23.67it/s]

 51%|█████     | 9577/18769 [06:39<06:27, 23.71it/s]

 51%|█████     | 9580/18769 [06:40<06:26, 23.76it/s]

 51%|█████     | 9583/18769 [06:40<06:26, 23.76it/s]

 51%|█████     | 9586/18769 [06:40<06:27, 23.71it/s]

 51%|█████     | 9589/18769 [06:40<06:26, 23.77it/s]

 51%|█████     | 9592/18769 [06:40<06:24, 23.87it/s]

 51%|█████     | 9595/18769 [06:40<06:22, 23.96it/s]

 51%|█████     | 9598/18769 [06:40<06:21, 24.02it/s]

 51%|█████     | 9601/18769 [06:40<06:22, 23.98it/s]

 51%|█████     | 9604/18769 [06:41<06:21, 24.02it/s]

 51%|█████     | 9607/18769 [06:41<06:20, 24.06it/s]

 51%|█████     | 9610/18769 [06:41<06:20, 24.05it/s]

 51%|█████     | 9613/18769 [06:41<06:19, 24.13it/s]

 51%|█████     | 9616/18769 [06:41<06:19, 24.14it/s]

 51%|█████     | 9619/18769 [06:41<06:19, 24.14it/s]

 51%|█████▏    | 9622/18769 [06:41<06:18, 24.15it/s]

 51%|█████▏    | 9625/18769 [06:41<06:18, 24.17it/s]

 51%|█████▏    | 9628/18769 [06:42<06:17, 24.23it/s]

 51%|█████▏    | 9631/18769 [06:42<06:17, 24.21it/s]

 51%|█████▏    | 9634/18769 [06:42<06:18, 24.14it/s]

 51%|█████▏    | 9637/18769 [06:42<06:17, 24.18it/s]

 51%|█████▏    | 9640/18769 [06:42<06:17, 24.18it/s]

 51%|█████▏    | 9643/18769 [06:42<06:17, 24.18it/s]

 51%|█████▏    | 9646/18769 [06:42<06:19, 24.03it/s]

 51%|█████▏    | 9649/18769 [06:42<06:24, 23.74it/s]

 51%|█████▏    | 9652/18769 [06:43<06:24, 23.69it/s]

 51%|█████▏    | 9655/18769 [06:43<06:26, 23.57it/s]

 51%|█████▏    | 9658/18769 [06:43<06:28, 23.47it/s]

 51%|█████▏    | 9662/18769 [06:43<05:59, 25.30it/s]

 51%|█████▏    | 9665/18769 [06:43<06:09, 24.67it/s]

 52%|█████▏    | 9668/18769 [06:43<06:14, 24.28it/s]

 52%|█████▏    | 9671/18769 [06:43<06:18, 24.06it/s]

 52%|█████▏    | 9674/18769 [06:43<06:19, 23.95it/s]

 52%|█████▏    | 9677/18769 [06:44<06:21, 23.86it/s]

 52%|█████▏    | 9680/18769 [06:44<06:22, 23.77it/s]

 52%|█████▏    | 9683/18769 [06:44<06:23, 23.71it/s]

 52%|█████▏    | 9686/18769 [06:44<06:23, 23.71it/s]

 52%|█████▏    | 9689/18769 [06:44<06:23, 23.70it/s]

 52%|█████▏    | 9692/18769 [06:44<06:22, 23.74it/s]

 52%|█████▏    | 9695/18769 [06:44<06:22, 23.73it/s]

 52%|█████▏    | 9698/18769 [06:44<06:22, 23.73it/s]

 52%|█████▏    | 9701/18769 [06:45<06:21, 23.77it/s]

 52%|█████▏    | 9704/18769 [06:45<06:21, 23.77it/s]

 52%|█████▏    | 9707/18769 [06:45<06:21, 23.73it/s]

 52%|█████▏    | 9710/18769 [06:45<06:22, 23.70it/s]

 52%|█████▏    | 9713/18769 [06:45<06:21, 23.71it/s]

 52%|█████▏    | 9716/18769 [06:45<06:22, 23.67it/s]

 52%|█████▏    | 9719/18769 [06:45<06:21, 23.71it/s]

 52%|█████▏    | 9722/18769 [06:45<06:21, 23.70it/s]

 52%|█████▏    | 9725/18769 [06:46<06:21, 23.73it/s]

 52%|█████▏    | 9728/18769 [06:46<06:19, 23.81it/s]

 52%|█████▏    | 9731/18769 [06:46<06:21, 23.70it/s]

 52%|█████▏    | 9734/18769 [06:46<06:19, 23.78it/s]

 52%|█████▏    | 9737/18769 [06:46<06:18, 23.88it/s]

 52%|█████▏    | 9740/18769 [06:46<06:16, 23.96it/s]

 52%|█████▏    | 9743/18769 [06:46<06:16, 24.00it/s]

 52%|█████▏    | 9746/18769 [06:46<06:16, 23.95it/s]

 52%|█████▏    | 9749/18769 [06:47<06:15, 24.03it/s]

 52%|█████▏    | 9752/18769 [06:47<06:14, 24.06it/s]

 52%|█████▏    | 9755/18769 [06:47<06:14, 24.09it/s]

 52%|█████▏    | 9758/18769 [06:47<06:14, 24.09it/s]

 52%|█████▏    | 9761/18769 [06:47<06:13, 24.13it/s]

 52%|█████▏    | 9764/18769 [06:47<06:13, 24.14it/s]

 52%|█████▏    | 9767/18769 [06:47<06:12, 24.18it/s]

 52%|█████▏    | 9770/18769 [06:47<06:12, 24.13it/s]

 52%|█████▏    | 9773/18769 [06:48<06:12, 24.14it/s]

 52%|█████▏    | 9776/18769 [06:48<06:13, 24.11it/s]

 52%|█████▏    | 9779/18769 [06:48<06:15, 23.95it/s]

 52%|█████▏    | 9782/18769 [06:48<06:14, 23.97it/s]

 52%|█████▏    | 9785/18769 [06:48<06:16, 23.84it/s]

 52%|█████▏    | 9788/18769 [06:48<06:18, 23.74it/s]

 52%|█████▏    | 9791/18769 [06:48<06:19, 23.66it/s]

 52%|█████▏    | 9794/18769 [06:48<06:20, 23.61it/s]

 52%|█████▏    | 9797/18769 [06:49<06:20, 23.55it/s]

 52%|█████▏    | 9801/18769 [06:49<05:53, 25.37it/s]

 52%|█████▏    | 9804/18769 [06:49<06:03, 24.69it/s]

 52%|█████▏    | 9807/18769 [06:49<06:07, 24.38it/s]

 52%|█████▏    | 9810/18769 [06:49<06:10, 24.17it/s]

 52%|█████▏    | 9813/18769 [06:49<06:13, 24.01it/s]

 52%|█████▏    | 9816/18769 [06:49<06:15, 23.87it/s]

 52%|█████▏    | 9819/18769 [06:50<06:17, 23.73it/s]

 52%|█████▏    | 9822/18769 [06:50<06:16, 23.75it/s]

 52%|█████▏    | 9825/18769 [06:50<06:16, 23.73it/s]

 52%|█████▏    | 9828/18769 [06:50<06:18, 23.60it/s]

 52%|█████▏    | 9831/18769 [06:50<06:17, 23.67it/s]

 52%|█████▏    | 9834/18769 [06:50<06:16, 23.73it/s]

 52%|█████▏    | 9837/18769 [06:50<06:16, 23.71it/s]

 52%|█████▏    | 9840/18769 [06:50<06:16, 23.74it/s]

 52%|█████▏    | 9843/18769 [06:51<06:16, 23.71it/s]

 52%|█████▏    | 9846/18769 [06:51<06:16, 23.69it/s]

 52%|█████▏    | 9849/18769 [06:51<06:16, 23.70it/s]

 52%|█████▏    | 9852/18769 [06:51<06:16, 23.65it/s]

 53%|█████▎    | 9855/18769 [06:51<06:16, 23.69it/s]

 53%|█████▎    | 9858/18769 [06:51<06:15, 23.72it/s]

 53%|█████▎    | 9861/18769 [06:51<06:15, 23.73it/s]

 53%|█████▎    | 9864/18769 [06:51<06:13, 23.83it/s]

 53%|█████▎    | 9867/18769 [06:52<06:13, 23.86it/s]

 53%|█████▎    | 9870/18769 [06:52<06:12, 23.91it/s]

 53%|█████▎    | 9873/18769 [06:52<06:11, 23.98it/s]

 53%|█████▎    | 9876/18769 [06:52<06:13, 23.81it/s]

 53%|█████▎    | 9879/18769 [06:52<06:11, 23.90it/s]

 53%|█████▎    | 9882/18769 [06:52<06:10, 23.99it/s]

 53%|█████▎    | 9885/18769 [06:52<06:09, 24.05it/s]

 53%|█████▎    | 9888/18769 [06:52<06:10, 23.99it/s]

 53%|█████▎    | 9891/18769 [06:53<06:11, 23.92it/s]

 53%|█████▎    | 9894/18769 [06:53<06:09, 23.99it/s]

 53%|█████▎    | 9897/18769 [06:53<06:09, 24.00it/s]

 53%|█████▎    | 9900/18769 [06:53<06:09, 24.01it/s]

 53%|█████▎    | 9903/18769 [06:53<06:08, 24.08it/s]

 53%|█████▎    | 9906/18769 [06:53<06:07, 24.10it/s]

 53%|█████▎    | 9909/18769 [06:53<06:06, 24.14it/s]

 53%|█████▎    | 9912/18769 [06:53<06:06, 24.18it/s]

 53%|█████▎    | 9915/18769 [06:54<06:06, 24.13it/s]

 53%|█████▎    | 9918/18769 [06:54<06:07, 24.11it/s]

 53%|█████▎    | 9921/18769 [06:54<06:09, 23.95it/s]

 53%|█████▎    | 9924/18769 [06:54<06:12, 23.77it/s]

 53%|█████▎    | 9927/18769 [06:54<06:13, 23.68it/s]

 53%|█████▎    | 9930/18769 [06:54<06:14, 23.58it/s]

 53%|█████▎    | 9933/18769 [06:54<06:15, 23.56it/s]

 53%|█████▎    | 9936/18769 [06:54<06:16, 23.47it/s]

 53%|█████▎    | 9940/18769 [06:55<05:48, 25.37it/s]

 53%|█████▎    | 9943/18769 [06:55<05:56, 24.76it/s]

 53%|█████▎    | 9946/18769 [06:55<06:01, 24.43it/s]

 53%|█████▎    | 9949/18769 [06:55<06:08, 23.96it/s]

 53%|█████▎    | 9952/18769 [06:55<06:08, 23.91it/s]

 53%|█████▎    | 9955/18769 [06:55<06:09, 23.84it/s]

 53%|█████▎    | 9958/18769 [06:55<06:10, 23.78it/s]

 53%|█████▎    | 9961/18769 [06:55<06:10, 23.79it/s]

 53%|█████▎    | 9964/18769 [06:56<06:10, 23.76it/s]

 53%|█████▎    | 9967/18769 [06:56<06:10, 23.73it/s]

 53%|█████▎    | 9970/18769 [06:56<06:10, 23.72it/s]

 53%|█████▎    | 9973/18769 [06:56<06:11, 23.70it/s]

 53%|█████▎    | 9976/18769 [06:56<06:10, 23.72it/s]

 53%|█████▎    | 9979/18769 [06:56<06:10, 23.73it/s]

 53%|█████▎    | 9982/18769 [06:56<06:10, 23.71it/s]

 53%|█████▎    | 9985/18769 [06:56<06:09, 23.75it/s]

 53%|█████▎    | 9988/18769 [06:57<06:09, 23.80it/s]

 53%|█████▎    | 9991/18769 [06:57<06:08, 23.80it/s]

 53%|█████▎    | 9994/18769 [06:57<06:08, 23.80it/s]

 53%|█████▎    | 9997/18769 [06:57<06:09, 23.74it/s]

 53%|█████▎    | 10000/18769 [06:57<06:08, 23.82it/s]

 53%|█████▎    | 10003/18769 [06:57<06:06, 23.89it/s]

 53%|█████▎    | 10006/18769 [06:57<06:06, 23.92it/s]

 53%|█████▎    | 10009/18769 [06:57<06:04, 24.00it/s]

 53%|█████▎    | 10012/18769 [06:58<06:03, 24.09it/s]

 53%|█████▎    | 10015/18769 [06:58<06:03, 24.11it/s]

 53%|█████▎    | 10018/18769 [06:58<06:02, 24.13it/s]

 53%|█████▎    | 10021/18769 [06:58<06:02, 24.14it/s]

 53%|█████▎    | 10024/18769 [06:58<06:01, 24.17it/s]

 53%|█████▎    | 10027/18769 [06:58<06:01, 24.21it/s]

 53%|█████▎    | 10030/18769 [06:58<06:00, 24.22it/s]

 53%|█████▎    | 10033/18769 [06:58<06:00, 24.21it/s]

 53%|█████▎    | 10036/18769 [06:59<06:00, 24.21it/s]

 53%|█████▎    | 10039/18769 [06:59<06:00, 24.20it/s]

 54%|█████▎    | 10042/18769 [06:59<06:00, 24.19it/s]

 54%|█████▎    | 10045/18769 [06:59<06:01, 24.13it/s]

 54%|█████▎    | 10048/18769 [06:59<06:00, 24.18it/s]

 54%|█████▎    | 10051/18769 [06:59<06:00, 24.21it/s]

 54%|█████▎    | 10054/18769 [06:59<06:00, 24.17it/s]

 54%|█████▎    | 10057/18769 [06:59<06:02, 24.05it/s]

 54%|█████▎    | 10060/18769 [07:00<06:03, 23.93it/s]

 54%|█████▎    | 10063/18769 [07:00<06:05, 23.80it/s]

 54%|█████▎    | 10066/18769 [07:00<06:07, 23.69it/s]

 54%|█████▎    | 10069/18769 [07:00<06:08, 23.62it/s]

 54%|█████▎    | 10072/18769 [07:00<06:08, 23.57it/s]

 54%|█████▎    | 10076/18769 [07:00<05:41, 25.47it/s]

 54%|█████▎    | 10079/18769 [07:00<05:49, 24.84it/s]

 54%|█████▎    | 10082/18769 [07:00<05:54, 24.51it/s]

 54%|█████▎    | 10085/18769 [07:01<05:57, 24.29it/s]

 54%|█████▎    | 10088/18769 [07:01<05:59, 24.13it/s]

 54%|█████▍    | 10091/18769 [07:01<06:01, 23.99it/s]

 54%|█████▍    | 10094/18769 [07:01<06:03, 23.89it/s]

 54%|█████▍    | 10097/18769 [07:01<06:03, 23.87it/s]

 54%|█████▍    | 10100/18769 [07:01<06:03, 23.86it/s]

 54%|█████▍    | 10103/18769 [07:01<06:03, 23.84it/s]

 54%|█████▍    | 10106/18769 [07:01<06:03, 23.81it/s]

 54%|█████▍    | 10109/18769 [07:02<06:03, 23.79it/s]

 54%|█████▍    | 10112/18769 [07:02<06:03, 23.79it/s]

 54%|█████▍    | 10115/18769 [07:02<06:04, 23.76it/s]

 54%|█████▍    | 10118/18769 [07:02<06:04, 23.71it/s]

 54%|█████▍    | 10121/18769 [07:02<06:04, 23.72it/s]

 54%|█████▍    | 10124/18769 [07:02<06:04, 23.72it/s]

 54%|█████▍    | 10127/18769 [07:02<06:04, 23.72it/s]

 54%|█████▍    | 10130/18769 [07:02<06:04, 23.69it/s]

 54%|█████▍    | 10133/18769 [07:03<06:05, 23.65it/s]

 54%|█████▍    | 10136/18769 [07:03<06:04, 23.68it/s]

 54%|█████▍    | 10139/18769 [07:03<06:03, 23.75it/s]

 54%|█████▍    | 10142/18769 [07:03<06:01, 23.83it/s]

 54%|█████▍    | 10145/18769 [07:03<06:01, 23.87it/s]

 54%|█████▍    | 10148/18769 [07:03<06:00, 23.91it/s]

 54%|█████▍    | 10151/18769 [07:03<06:00, 23.94it/s]

 54%|█████▍    | 10154/18769 [07:03<05:59, 23.95it/s]

 54%|█████▍    | 10157/18769 [07:04<05:59, 23.98it/s]

 54%|█████▍    | 10160/18769 [07:04<05:59, 23.97it/s]

 54%|█████▍    | 10163/18769 [07:04<05:58, 24.00it/s]

 54%|█████▍    | 10166/18769 [07:04<05:57, 24.04it/s]

 54%|█████▍    | 10169/18769 [07:04<05:57, 24.05it/s]

 54%|█████▍    | 10172/18769 [07:04<05:57, 24.04it/s]

 54%|█████▍    | 10175/18769 [07:04<05:57, 24.01it/s]

 54%|█████▍    | 10178/18769 [07:04<05:57, 24.00it/s]

 54%|█████▍    | 10181/18769 [07:05<06:02, 23.68it/s]

 54%|█████▍    | 10184/18769 [07:05<06:00, 23.82it/s]

 54%|█████▍    | 10187/18769 [07:05<05:58, 23.92it/s]

 54%|█████▍    | 10190/18769 [07:05<06:00, 23.81it/s]

 54%|█████▍    | 10193/18769 [07:05<05:59, 23.82it/s]

 54%|█████▍    | 10196/18769 [07:05<06:01, 23.73it/s]

 54%|█████▍    | 10199/18769 [07:05<06:02, 23.67it/s]

 54%|█████▍    | 10202/18769 [07:05<06:03, 23.57it/s]

 54%|█████▍    | 10205/18769 [07:06<06:03, 23.53it/s]

 54%|█████▍    | 10208/18769 [07:06<06:04, 23.51it/s]

 54%|█████▍    | 10211/18769 [07:06<06:04, 23.50it/s]

 54%|█████▍    | 10215/18769 [07:06<05:36, 25.41it/s]

 54%|█████▍    | 10218/18769 [07:06<05:44, 24.84it/s]

 54%|█████▍    | 10221/18769 [07:06<05:49, 24.47it/s]

 54%|█████▍    | 10224/18769 [07:06<05:52, 24.21it/s]

 54%|█████▍    | 10227/18769 [07:07<05:56, 23.99it/s]

 55%|█████▍    | 10230/18769 [07:07<05:57, 23.91it/s]

 55%|█████▍    | 10233/18769 [07:07<05:58, 23.80it/s]

 55%|█████▍    | 10236/18769 [07:07<05:59, 23.74it/s]

 55%|█████▍    | 10239/18769 [07:07<06:00, 23.69it/s]

 55%|█████▍    | 10242/18769 [07:07<06:00, 23.68it/s]

 55%|█████▍    | 10245/18769 [07:07<06:00, 23.67it/s]

 55%|█████▍    | 10248/18769 [07:07<06:00, 23.63it/s]

 55%|█████▍    | 10251/18769 [07:08<05:58, 23.75it/s]

 55%|█████▍    | 10254/18769 [07:08<05:58, 23.77it/s]

 55%|█████▍    | 10257/18769 [07:08<05:57, 23.80it/s]

 55%|█████▍    | 10260/18769 [07:08<05:57, 23.81it/s]

 55%|█████▍    | 10263/18769 [07:08<05:56, 23.84it/s]

 55%|█████▍    | 10266/18769 [07:08<05:56, 23.83it/s]

 55%|█████▍    | 10269/18769 [07:08<05:56, 23.85it/s]

 55%|█████▍    | 10272/18769 [07:08<05:56, 23.86it/s]

 55%|█████▍    | 10275/18769 [07:09<05:54, 23.97it/s]

 55%|█████▍    | 10278/18769 [07:09<05:53, 24.04it/s]

 55%|█████▍    | 10281/18769 [07:09<05:51, 24.13it/s]

 55%|█████▍    | 10284/18769 [07:09<05:51, 24.14it/s]

 55%|█████▍    | 10287/18769 [07:09<05:51, 24.15it/s]

 55%|█████▍    | 10290/18769 [07:09<05:50, 24.20it/s]

 55%|█████▍    | 10293/18769 [07:09<05:49, 24.22it/s]

 55%|█████▍    | 10296/18769 [07:09<05:50, 24.18it/s]

 55%|█████▍    | 10299/18769 [07:10<05:50, 24.18it/s]

 55%|█████▍    | 10302/18769 [07:10<05:50, 24.13it/s]

 55%|█████▍    | 10305/18769 [07:10<05:50, 24.15it/s]

 55%|█████▍    | 10308/18769 [07:10<05:50, 24.13it/s]

 55%|█████▍    | 10311/18769 [07:10<05:52, 23.97it/s]

 55%|█████▍    | 10314/18769 [07:10<05:51, 24.08it/s]

 55%|█████▍    | 10317/18769 [07:10<05:50, 24.12it/s]

 55%|█████▍    | 10320/18769 [07:10<05:49, 24.20it/s]

 55%|█████▌    | 10323/18769 [07:11<05:55, 23.75it/s]

 55%|█████▌    | 10326/18769 [07:11<06:00, 23.43it/s]

 55%|█████▌    | 10329/18769 [07:11<06:00, 23.39it/s]

 55%|█████▌    | 10332/18769 [07:11<06:01, 23.33it/s]

 55%|█████▌    | 10335/18769 [07:11<06:02, 23.25it/s]

 55%|█████▌    | 10338/18769 [07:11<06:01, 23.33it/s]

 55%|█████▌    | 10341/18769 [07:11<06:00, 23.36it/s]

 55%|█████▌    | 10344/18769 [07:11<06:00, 23.39it/s]

 55%|█████▌    | 10347/18769 [07:12<06:00, 23.38it/s]

 55%|█████▌    | 10350/18769 [07:12<06:01, 23.32it/s]

 55%|█████▌    | 10354/18769 [07:12<05:33, 25.27it/s]

 55%|█████▌    | 10357/18769 [07:12<05:39, 24.79it/s]

 55%|█████▌    | 10360/18769 [07:12<05:46, 24.25it/s]

 55%|█████▌    | 10363/18769 [07:12<05:48, 24.12it/s]

 55%|█████▌    | 10366/18769 [07:12<05:52, 23.83it/s]

 55%|█████▌    | 10369/18769 [07:12<05:53, 23.73it/s]

 55%|█████▌    | 10372/18769 [07:13<05:53, 23.76it/s]

 55%|█████▌    | 10375/18769 [07:13<05:53, 23.75it/s]

 55%|█████▌    | 10378/18769 [07:13<05:52, 23.80it/s]

 55%|█████▌    | 10381/18769 [07:13<05:52, 23.80it/s]

 55%|█████▌    | 10384/18769 [07:13<05:52, 23.77it/s]

 55%|█████▌    | 10387/18769 [07:13<05:52, 23.80it/s]

 55%|█████▌    | 10390/18769 [07:13<05:51, 23.85it/s]

 55%|█████▌    | 10393/18769 [07:13<05:51, 23.86it/s]

 55%|█████▌    | 10396/18769 [07:14<05:50, 23.88it/s]

 55%|█████▌    | 10399/18769 [07:14<05:50, 23.86it/s]

 55%|█████▌    | 10402/18769 [07:14<05:51, 23.82it/s]

 55%|█████▌    | 10405/18769 [07:14<05:51, 23.81it/s]

 55%|█████▌    | 10408/18769 [07:14<05:51, 23.81it/s]

 55%|█████▌    | 10411/18769 [07:14<05:50, 23.87it/s]

 55%|█████▌    | 10414/18769 [07:14<05:48, 23.98it/s]

 56%|█████▌    | 10417/18769 [07:14<05:46, 24.09it/s]

 56%|█████▌    | 10420/18769 [07:15<05:45, 24.14it/s]

 56%|█████▌    | 10423/18769 [07:15<05:45, 24.17it/s]

 56%|█████▌    | 10426/18769 [07:15<05:44, 24.23it/s]

 56%|█████▌    | 10429/18769 [07:15<05:44, 24.23it/s]

 56%|█████▌    | 10432/18769 [07:15<05:43, 24.26it/s]

 56%|█████▌    | 10435/18769 [07:15<05:43, 24.28it/s]

 56%|█████▌    | 10438/18769 [07:15<05:43, 24.27it/s]

 56%|█████▌    | 10441/18769 [07:15<05:43, 24.24it/s]

 56%|█████▌    | 10444/18769 [07:16<05:44, 24.16it/s]

 56%|█████▌    | 10447/18769 [07:16<05:46, 24.05it/s]

 56%|█████▌    | 10450/18769 [07:16<05:45, 24.07it/s]

 56%|█████▌    | 10453/18769 [07:16<05:45, 24.09it/s]

 56%|█████▌    | 10456/18769 [07:16<05:47, 23.95it/s]

 56%|█████▌    | 10459/18769 [07:16<05:45, 24.06it/s]

 56%|█████▌    | 10462/18769 [07:16<05:44, 24.13it/s]

 56%|█████▌    | 10465/18769 [07:16<05:43, 24.16it/s]

 56%|█████▌    | 10468/18769 [07:17<05:46, 23.94it/s]

 56%|█████▌    | 10471/18769 [07:17<05:48, 23.82it/s]

 56%|█████▌    | 10474/18769 [07:17<05:49, 23.74it/s]

 56%|█████▌    | 10477/18769 [07:17<05:50, 23.64it/s]

 56%|█████▌    | 10480/18769 [07:17<05:51, 23.56it/s]

 56%|█████▌    | 10483/18769 [07:17<05:51, 23.55it/s]

 56%|█████▌    | 10486/18769 [07:17<05:51, 23.55it/s]

 56%|█████▌    | 10490/18769 [07:17<05:25, 25.44it/s]

 56%|█████▌    | 10493/18769 [07:18<05:31, 24.93it/s]

 56%|█████▌    | 10496/18769 [07:18<05:36, 24.56it/s]

 56%|█████▌    | 10499/18769 [07:18<05:39, 24.33it/s]

 56%|█████▌    | 10502/18769 [07:18<05:42, 24.13it/s]

 56%|█████▌    | 10505/18769 [07:18<05:46, 23.82it/s]

 56%|█████▌    | 10508/18769 [07:18<05:47, 23.78it/s]

 56%|█████▌    | 10511/18769 [07:18<05:47, 23.77it/s]

 56%|█████▌    | 10514/18769 [07:18<05:46, 23.80it/s]

 56%|█████▌    | 10517/18769 [07:19<05:47, 23.78it/s]

 56%|█████▌    | 10520/18769 [07:19<05:47, 23.76it/s]

 56%|█████▌    | 10523/18769 [07:19<05:47, 23.76it/s]

 56%|█████▌    | 10526/18769 [07:19<05:47, 23.71it/s]

 56%|█████▌    | 10529/18769 [07:19<05:47, 23.71it/s]

 56%|█████▌    | 10532/18769 [07:19<05:46, 23.76it/s]

 56%|█████▌    | 10535/18769 [07:19<05:46, 23.79it/s]

 56%|█████▌    | 10538/18769 [07:19<05:46, 23.78it/s]

 56%|█████▌    | 10541/18769 [07:20<05:45, 23.79it/s]

 56%|█████▌    | 10544/18769 [07:20<05:46, 23.77it/s]

 56%|█████▌    | 10547/18769 [07:20<05:46, 23.76it/s]

 56%|█████▌    | 10550/18769 [07:20<05:44, 23.89it/s]

 56%|█████▌    | 10553/18769 [07:20<05:47, 23.64it/s]

 56%|█████▌    | 10556/18769 [07:20<05:45, 23.77it/s]

 56%|█████▋    | 10559/18769 [07:20<05:43, 23.88it/s]

 56%|█████▋    | 10562/18769 [07:21<05:42, 23.93it/s]

 56%|█████▋    | 10565/18769 [07:21<05:42, 23.99it/s]

 56%|█████▋    | 10568/18769 [07:21<05:42, 23.97it/s]

 56%|█████▋    | 10571/18769 [07:21<05:42, 23.97it/s]

 56%|█████▋    | 10574/18769 [07:21<05:41, 24.01it/s]

 56%|█████▋    | 10577/18769 [07:21<05:41, 23.96it/s]

 56%|█████▋    | 10580/18769 [07:21<05:41, 23.97it/s]

 56%|█████▋    | 10583/18769 [07:21<05:41, 23.99it/s]

 56%|█████▋    | 10586/18769 [07:22<05:40, 24.06it/s]

 56%|█████▋    | 10589/18769 [07:22<05:39, 24.06it/s]

 56%|█████▋    | 10592/18769 [07:22<05:40, 24.04it/s]

 56%|█████▋    | 10595/18769 [07:22<05:39, 24.05it/s]

 56%|█████▋    | 10598/18769 [07:22<05:39, 24.09it/s]

 56%|█████▋    | 10601/18769 [07:22<05:41, 23.92it/s]

 56%|█████▋    | 10604/18769 [07:22<05:41, 23.91it/s]

 57%|█████▋    | 10607/18769 [07:22<05:43, 23.74it/s]

 57%|█████▋    | 10610/18769 [07:23<05:44, 23.65it/s]

 57%|█████▋    | 10613/18769 [07:23<05:45, 23.60it/s]

 57%|█████▋    | 10616/18769 [07:23<05:46, 23.52it/s]

 57%|█████▋    | 10619/18769 [07:23<05:47, 23.45it/s]

 57%|█████▋    | 10622/18769 [07:23<05:48, 23.40it/s]

 57%|█████▋    | 10625/18769 [07:23<05:48, 23.38it/s]

 57%|█████▋    | 10629/18769 [07:23<05:21, 25.33it/s]

 57%|█████▋    | 10632/18769 [07:23<05:28, 24.80it/s]

 57%|█████▋    | 10635/18769 [07:24<05:33, 24.41it/s]

 57%|█████▋    | 10638/18769 [07:24<05:37, 24.12it/s]

 57%|█████▋    | 10641/18769 [07:24<05:39, 23.94it/s]

 57%|█████▋    | 10644/18769 [07:24<05:41, 23.82it/s]

 57%|█████▋    | 10647/18769 [07:24<05:41, 23.77it/s]

 57%|█████▋    | 10650/18769 [07:24<05:44, 23.55it/s]

 57%|█████▋    | 10653/18769 [07:24<05:44, 23.58it/s]

 57%|█████▋    | 10656/18769 [07:24<05:43, 23.63it/s]

 57%|█████▋    | 10659/18769 [07:25<05:43, 23.61it/s]

 57%|█████▋    | 10662/18769 [07:25<05:43, 23.63it/s]

 57%|█████▋    | 10665/18769 [07:25<05:43, 23.62it/s]

 57%|█████▋    | 10668/18769 [07:25<05:42, 23.63it/s]

 57%|█████▋    | 10671/18769 [07:25<05:43, 23.60it/s]

 57%|█████▋    | 10674/18769 [07:25<05:43, 23.60it/s]

 57%|█████▋    | 10677/18769 [07:25<05:42, 23.62it/s]

 57%|█████▋    | 10680/18769 [07:25<05:42, 23.62it/s]

 57%|█████▋    | 10683/18769 [07:26<05:42, 23.61it/s]

 57%|█████▋    | 10686/18769 [07:26<05:42, 23.62it/s]

 57%|█████▋    | 10689/18769 [07:26<05:44, 23.42it/s]

 57%|█████▋    | 10692/18769 [07:26<05:46, 23.30it/s]

 57%|█████▋    | 10695/18769 [07:26<05:43, 23.48it/s]

 57%|█████▋    | 10698/18769 [07:26<05:43, 23.51it/s]

 57%|█████▋    | 10701/18769 [07:26<05:40, 23.70it/s]

 57%|█████▋    | 10704/18769 [07:26<05:38, 23.84it/s]

 57%|█████▋    | 10707/18769 [07:27<05:37, 23.92it/s]

 57%|█████▋    | 10710/18769 [07:27<05:36, 23.98it/s]

 57%|█████▋    | 10713/18769 [07:27<05:35, 24.03it/s]

 57%|█████▋    | 10716/18769 [07:27<05:34, 24.05it/s]

 57%|█████▋    | 10719/18769 [07:27<05:34, 24.10it/s]

 57%|█████▋    | 10722/18769 [07:27<05:33, 24.10it/s]

 57%|█████▋    | 10725/18769 [07:27<05:33, 24.11it/s]

 57%|█████▋    | 10728/18769 [07:27<05:34, 24.05it/s]

 57%|█████▋    | 10731/18769 [07:28<05:33, 24.10it/s]

 57%|█████▋    | 10734/18769 [07:28<05:33, 24.09it/s]

 57%|█████▋    | 10737/18769 [07:28<05:32, 24.12it/s]

 57%|█████▋    | 10740/18769 [07:28<05:32, 24.18it/s]

 57%|█████▋    | 10743/18769 [07:28<05:33, 24.04it/s]

 57%|█████▋    | 10746/18769 [07:28<05:37, 23.77it/s]

 57%|█████▋    | 10749/18769 [07:28<05:37, 23.75it/s]

 57%|█████▋    | 10752/18769 [07:28<05:37, 23.74it/s]

 57%|█████▋    | 10755/18769 [07:29<05:37, 23.73it/s]

 57%|█████▋    | 10758/18769 [07:29<05:37, 23.71it/s]

 57%|█████▋    | 10761/18769 [07:29<05:37, 23.70it/s]

 57%|█████▋    | 10764/18769 [07:29<05:37, 23.69it/s]

 57%|█████▋    | 10768/18769 [07:29<05:12, 25.57it/s]

 57%|█████▋    | 10771/18769 [07:29<05:21, 24.85it/s]

 57%|█████▋    | 10774/18769 [07:29<05:27, 24.38it/s]

 57%|█████▋    | 10777/18769 [07:29<05:31, 24.08it/s]

 57%|█████▋    | 10780/18769 [07:30<05:33, 23.93it/s]

 57%|█████▋    | 10783/18769 [07:30<05:35, 23.80it/s]

 57%|█████▋    | 10786/18769 [07:30<05:36, 23.73it/s]

 57%|█████▋    | 10789/18769 [07:30<05:36, 23.69it/s]

 57%|█████▋    | 10792/18769 [07:30<05:37, 23.65it/s]

 58%|█████▊    | 10795/18769 [07:30<05:39, 23.47it/s]

 58%|█████▊    | 10798/18769 [07:30<05:39, 23.46it/s]

 58%|█████▊    | 10801/18769 [07:31<05:38, 23.55it/s]

 58%|█████▊    | 10804/18769 [07:31<05:37, 23.58it/s]

 58%|█████▊    | 10807/18769 [07:31<05:37, 23.59it/s]

 58%|█████▊    | 10810/18769 [07:31<05:37, 23.59it/s]

 58%|█████▊    | 10813/18769 [07:31<05:37, 23.58it/s]

 58%|█████▊    | 10816/18769 [07:31<05:37, 23.59it/s]

 58%|█████▊    | 10819/18769 [07:31<05:37, 23.57it/s]

 58%|█████▊    | 10822/18769 [07:31<05:36, 23.62it/s]

 58%|█████▊    | 10825/18769 [07:32<05:33, 23.80it/s]

 58%|█████▊    | 10828/18769 [07:32<05:32, 23.91it/s]

 58%|█████▊    | 10831/18769 [07:32<05:30, 24.03it/s]

 58%|█████▊    | 10834/18769 [07:32<05:29, 24.10it/s]

 58%|█████▊    | 10837/18769 [07:32<05:28, 24.17it/s]

 58%|█████▊    | 10840/18769 [07:32<05:27, 24.20it/s]

 58%|█████▊    | 10843/18769 [07:32<05:29, 24.04it/s]

 58%|█████▊    | 10846/18769 [07:32<05:30, 23.96it/s]

 58%|█████▊    | 10849/18769 [07:33<05:29, 24.05it/s]

 58%|█████▊    | 10852/18769 [07:33<05:28, 24.11it/s]

 58%|█████▊    | 10855/18769 [07:33<05:27, 24.16it/s]

 58%|█████▊    | 10858/18769 [07:33<05:27, 24.16it/s]

 58%|█████▊    | 10861/18769 [07:33<05:27, 24.15it/s]

 58%|█████▊    | 10864/18769 [07:33<05:27, 24.15it/s]

 58%|█████▊    | 10867/18769 [07:33<05:30, 23.91it/s]

 58%|█████▊    | 10870/18769 [07:33<05:29, 24.00it/s]

 58%|█████▊    | 10873/18769 [07:34<05:27, 24.09it/s]

 58%|█████▊    | 10876/18769 [07:34<05:27, 24.09it/s]

 58%|█████▊    | 10879/18769 [07:34<05:28, 24.05it/s]

 58%|█████▊    | 10882/18769 [07:34<05:28, 23.99it/s]

 58%|█████▊    | 10885/18769 [07:34<05:29, 23.90it/s]

 58%|█████▊    | 10888/18769 [07:34<05:29, 23.89it/s]

 58%|█████▊    | 10891/18769 [07:34<05:30, 23.87it/s]

 58%|█████▊    | 10894/18769 [07:34<05:29, 23.88it/s]

 58%|█████▊    | 10897/18769 [07:35<05:29, 23.90it/s]

 58%|█████▊    | 10900/18769 [07:35<05:30, 23.78it/s]

 58%|█████▊    | 10904/18769 [07:35<05:06, 25.67it/s]

 58%|█████▊    | 10907/18769 [07:35<05:15, 24.91it/s]

 58%|█████▊    | 10910/18769 [07:35<05:20, 24.50it/s]

 58%|█████▊    | 10913/18769 [07:35<05:24, 24.20it/s]

 58%|█████▊    | 10916/18769 [07:35<05:29, 23.82it/s]

 58%|█████▊    | 10919/18769 [07:35<05:30, 23.77it/s]

 58%|█████▊    | 10922/18769 [07:36<05:30, 23.73it/s]

 58%|█████▊    | 10925/18769 [07:36<05:32, 23.62it/s]

 58%|█████▊    | 10928/18769 [07:36<05:32, 23.59it/s]

 58%|█████▊    | 10931/18769 [07:36<05:31, 23.61it/s]

 58%|█████▊    | 10934/18769 [07:36<05:31, 23.66it/s]

 58%|█████▊    | 10937/18769 [07:36<05:30, 23.67it/s]

 58%|█████▊    | 10940/18769 [07:36<05:30, 23.67it/s]

 58%|█████▊    | 10943/18769 [07:36<05:30, 23.68it/s]

 58%|█████▊    | 10946/18769 [07:37<05:30, 23.69it/s]

 58%|█████▊    | 10949/18769 [07:37<05:30, 23.68it/s]

 58%|█████▊    | 10952/18769 [07:37<05:29, 23.71it/s]

 58%|█████▊    | 10955/18769 [07:37<05:29, 23.70it/s]

 58%|█████▊    | 10958/18769 [07:37<05:29, 23.71it/s]

 58%|█████▊    | 10961/18769 [07:37<05:26, 23.89it/s]

 58%|█████▊    | 10964/18769 [07:37<05:27, 23.81it/s]

 58%|█████▊    | 10967/18769 [07:37<05:26, 23.93it/s]

 58%|█████▊    | 10970/18769 [07:38<05:24, 24.02it/s]

 58%|█████▊    | 10973/18769 [07:38<05:23, 24.08it/s]

 58%|█████▊    | 10976/18769 [07:38<05:23, 24.12it/s]

 58%|█████▊    | 10979/18769 [07:38<05:22, 24.15it/s]

 59%|█████▊    | 10982/18769 [07:38<05:22, 24.16it/s]

 59%|█████▊    | 10985/18769 [07:38<05:21, 24.20it/s]

 59%|█████▊    | 10988/18769 [07:38<05:21, 24.21it/s]

 59%|█████▊    | 10991/18769 [07:38<05:21, 24.23it/s]

 59%|█████▊    | 10994/18769 [07:39<05:22, 24.12it/s]

 59%|█████▊    | 10997/18769 [07:39<05:21, 24.15it/s]

 59%|█████▊    | 11000/18769 [07:39<05:21, 24.17it/s]

 59%|█████▊    | 11003/18769 [07:39<05:21, 24.13it/s]

 59%|█████▊    | 11006/18769 [07:39<05:21, 24.16it/s]

 59%|█████▊    | 11009/18769 [07:39<05:20, 24.18it/s]

 59%|█████▊    | 11012/18769 [07:39<05:22, 24.02it/s]

 59%|█████▊    | 11015/18769 [07:39<05:22, 24.03it/s]

 59%|█████▊    | 11018/18769 [07:40<05:24, 23.91it/s]

 59%|█████▊    | 11021/18769 [07:40<05:25, 23.83it/s]

 59%|█████▊    | 11024/18769 [07:40<05:25, 23.79it/s]

 59%|█████▉    | 11027/18769 [07:40<05:25, 23.77it/s]

 59%|█████▉    | 11030/18769 [07:40<05:25, 23.78it/s]

 59%|█████▉    | 11033/18769 [07:40<05:25, 23.76it/s]

 59%|█████▉    | 11036/18769 [07:40<05:25, 23.77it/s]

 59%|█████▉    | 11039/18769 [07:40<05:24, 23.79it/s]

 59%|█████▉    | 11043/18769 [07:41<05:02, 25.52it/s]

 59%|█████▉    | 11046/18769 [07:41<05:10, 24.90it/s]

 59%|█████▉    | 11049/18769 [07:41<05:14, 24.52it/s]

 59%|█████▉    | 11052/18769 [07:41<05:18, 24.25it/s]

 59%|█████▉    | 11055/18769 [07:41<05:20, 24.07it/s]

 59%|█████▉    | 11058/18769 [07:41<05:22, 23.94it/s]

 59%|█████▉    | 11061/18769 [07:41<05:25, 23.69it/s]

 59%|█████▉    | 11064/18769 [07:41<05:25, 23.70it/s]

 59%|█████▉    | 11067/18769 [07:42<05:24, 23.71it/s]

 59%|█████▉    | 11070/18769 [07:42<05:24, 23.70it/s]

 59%|█████▉    | 11073/18769 [07:42<05:24, 23.69it/s]

 59%|█████▉    | 11076/18769 [07:42<05:24, 23.72it/s]

 59%|█████▉    | 11079/18769 [07:42<05:24, 23.69it/s]

 59%|█████▉    | 11082/18769 [07:42<05:24, 23.70it/s]

 59%|█████▉    | 11085/18769 [07:42<05:24, 23.68it/s]

 59%|█████▉    | 11088/18769 [07:42<05:26, 23.53it/s]

 59%|█████▉    | 11091/18769 [07:43<05:26, 23.54it/s]

 59%|█████▉    | 11094/18769 [07:43<05:26, 23.53it/s]

 59%|█████▉    | 11097/18769 [07:43<05:26, 23.51it/s]

 59%|█████▉    | 11100/18769 [07:43<05:24, 23.66it/s]

 59%|█████▉    | 11103/18769 [07:43<05:21, 23.81it/s]

 59%|█████▉    | 11106/18769 [07:43<05:20, 23.94it/s]

 59%|█████▉    | 11109/18769 [07:43<05:18, 24.02it/s]

 59%|█████▉    | 11112/18769 [07:43<05:18, 24.05it/s]

 59%|█████▉    | 11115/18769 [07:44<05:17, 24.08it/s]

 59%|█████▉    | 11118/18769 [07:44<05:17, 24.09it/s]

 59%|█████▉    | 11121/18769 [07:44<05:17, 24.10it/s]

 59%|█████▉    | 11124/18769 [07:44<05:17, 24.12it/s]

 59%|█████▉    | 11127/18769 [07:44<05:17, 24.10it/s]

 59%|█████▉    | 11130/18769 [07:44<05:16, 24.12it/s]

 59%|█████▉    | 11133/18769 [07:44<05:16, 24.12it/s]

 59%|█████▉    | 11136/18769 [07:44<05:16, 24.10it/s]

 59%|█████▉    | 11139/18769 [07:45<05:16, 24.08it/s]

 59%|█████▉    | 11142/18769 [07:45<05:16, 24.08it/s]

 59%|█████▉    | 11145/18769 [07:45<05:16, 24.09it/s]

 59%|█████▉    | 11148/18769 [07:45<05:16, 24.11it/s]

 59%|█████▉    | 11151/18769 [07:45<05:15, 24.12it/s]

 59%|█████▉    | 11154/18769 [07:45<05:17, 23.98it/s]

 59%|█████▉    | 11157/18769 [07:45<05:18, 23.87it/s]

 59%|█████▉    | 11160/18769 [07:45<05:19, 23.83it/s]

 59%|█████▉    | 11163/18769 [07:46<05:20, 23.76it/s]

 59%|█████▉    | 11166/18769 [07:46<05:19, 23.76it/s]

 60%|█████▉    | 11169/18769 [07:46<05:20, 23.74it/s]

 60%|█████▉    | 11172/18769 [07:46<05:20, 23.73it/s]

 60%|█████▉    | 11175/18769 [07:46<05:19, 23.74it/s]

 60%|█████▉    | 11178/18769 [07:46<05:21, 23.63it/s]

 60%|█████▉    | 11182/18769 [07:46<04:57, 25.48it/s]

 60%|█████▉    | 11185/18769 [07:46<05:04, 24.87it/s]

 60%|█████▉    | 11188/18769 [07:47<05:10, 24.39it/s]

 60%|█████▉    | 11191/18769 [07:47<05:13, 24.17it/s]

 60%|█████▉    | 11194/18769 [07:47<05:16, 23.97it/s]

 60%|█████▉    | 11197/18769 [07:47<05:17, 23.85it/s]

 60%|█████▉    | 11200/18769 [07:47<05:18, 23.74it/s]

 60%|█████▉    | 11203/18769 [07:47<05:19, 23.71it/s]

 60%|█████▉    | 11206/18769 [07:47<05:22, 23.43it/s]

 60%|█████▉    | 11209/18769 [07:48<05:21, 23.50it/s]

 60%|█████▉    | 11212/18769 [07:48<05:21, 23.49it/s]

 60%|█████▉    | 11215/18769 [07:48<05:21, 23.52it/s]

 60%|█████▉    | 11218/18769 [07:48<05:20, 23.56it/s]

 60%|█████▉    | 11221/18769 [07:48<05:23, 23.32it/s]

 60%|█████▉    | 11224/18769 [07:48<05:22, 23.38it/s]

 60%|█████▉    | 11227/18769 [07:48<05:21, 23.45it/s]

 60%|█████▉    | 11230/18769 [07:48<05:21, 23.43it/s]

 60%|█████▉    | 11233/18769 [07:49<05:20, 23.54it/s]

 60%|█████▉    | 11236/18769 [07:49<05:18, 23.68it/s]

 60%|█████▉    | 11239/18769 [07:49<05:16, 23.80it/s]

 60%|█████▉    | 11242/18769 [07:49<05:14, 23.91it/s]

 60%|█████▉    | 11245/18769 [07:49<05:12, 24.06it/s]

 60%|█████▉    | 11248/18769 [07:49<05:12, 24.11it/s]

 60%|█████▉    | 11251/18769 [07:49<05:11, 24.16it/s]

 60%|█████▉    | 11254/18769 [07:49<05:10, 24.17it/s]

 60%|█████▉    | 11257/18769 [07:50<05:10, 24.16it/s]

 60%|█████▉    | 11260/18769 [07:50<05:10, 24.17it/s]

 60%|██████    | 11263/18769 [07:50<05:10, 24.19it/s]

 60%|██████    | 11266/18769 [07:50<05:09, 24.21it/s]

 60%|██████    | 11269/18769 [07:50<05:10, 24.19it/s]

 60%|██████    | 11272/18769 [07:50<05:09, 24.21it/s]

 60%|██████    | 11275/18769 [07:50<05:09, 24.18it/s]

 60%|██████    | 11278/18769 [07:50<05:10, 24.12it/s]

 60%|██████    | 11281/18769 [07:51<05:10, 24.11it/s]

 60%|██████    | 11284/18769 [07:51<05:10, 24.12it/s]

 60%|██████    | 11287/18769 [07:51<05:10, 24.12it/s]

 60%|██████    | 11290/18769 [07:51<05:11, 24.01it/s]

 60%|██████    | 11293/18769 [07:51<05:12, 23.95it/s]

 60%|██████    | 11296/18769 [07:51<05:12, 23.92it/s]

 60%|██████    | 11299/18769 [07:51<05:12, 23.92it/s]

 60%|██████    | 11302/18769 [07:51<05:15, 23.69it/s]

 60%|██████    | 11305/18769 [07:52<05:14, 23.72it/s]

 60%|██████    | 11308/18769 [07:52<05:14, 23.76it/s]

 60%|██████    | 11311/18769 [07:52<05:13, 23.78it/s]

 60%|██████    | 11314/18769 [07:52<05:14, 23.74it/s]

 60%|██████    | 11318/18769 [07:52<04:51, 25.58it/s]

 60%|██████    | 11321/18769 [07:52<04:57, 24.99it/s]

 60%|██████    | 11324/18769 [07:52<05:03, 24.55it/s]

 60%|██████    | 11327/18769 [07:52<05:06, 24.30it/s]

 60%|██████    | 11330/18769 [07:53<05:08, 24.12it/s]

 60%|██████    | 11333/18769 [07:53<05:11, 23.85it/s]

 60%|██████    | 11336/18769 [07:53<05:12, 23.78it/s]

 60%|██████    | 11339/18769 [07:53<05:13, 23.74it/s]

 60%|██████    | 11342/18769 [07:53<05:13, 23.65it/s]

 60%|██████    | 11345/18769 [07:53<05:14, 23.60it/s]

 60%|██████    | 11348/18769 [07:53<05:14, 23.58it/s]

 60%|██████    | 11351/18769 [07:53<05:14, 23.58it/s]

 60%|██████    | 11354/18769 [07:54<05:14, 23.57it/s]

 61%|██████    | 11357/18769 [07:54<05:14, 23.57it/s]

 61%|██████    | 11360/18769 [07:54<05:14, 23.56it/s]

 61%|██████    | 11363/18769 [07:54<05:14, 23.56it/s]

 61%|██████    | 11366/18769 [07:54<05:14, 23.54it/s]

 61%|██████    | 11369/18769 [07:54<05:14, 23.55it/s]

 61%|██████    | 11372/18769 [07:54<05:12, 23.71it/s]

 61%|██████    | 11375/18769 [07:54<05:10, 23.81it/s]

 61%|██████    | 11378/18769 [07:55<05:09, 23.90it/s]

 61%|██████    | 11381/18769 [07:55<05:08, 23.96it/s]

 61%|██████    | 11384/18769 [07:55<05:07, 24.01it/s]

 61%|██████    | 11387/18769 [07:55<05:07, 24.03it/s]

 61%|██████    | 11390/18769 [07:55<05:06, 24.06it/s]

 61%|██████    | 11393/18769 [07:55<05:06, 24.10it/s]

 61%|██████    | 11396/18769 [07:55<05:06, 24.08it/s]

 61%|██████    | 11399/18769 [07:55<05:06, 24.05it/s]

 61%|██████    | 11402/18769 [07:56<05:05, 24.10it/s]

 61%|██████    | 11405/18769 [07:56<05:06, 24.04it/s]

 61%|██████    | 11408/18769 [07:56<05:06, 24.02it/s]

 61%|██████    | 11411/18769 [07:56<05:05, 24.07it/s]

 61%|██████    | 11414/18769 [07:56<05:05, 24.04it/s]

 61%|██████    | 11417/18769 [07:56<05:05, 24.07it/s]

 61%|██████    | 11420/18769 [07:56<05:05, 24.07it/s]

 61%|██████    | 11423/18769 [07:56<05:05, 24.03it/s]

 61%|██████    | 11426/18769 [07:57<05:05, 24.00it/s]

 61%|██████    | 11429/18769 [07:57<05:07, 23.89it/s]

 61%|██████    | 11432/18769 [07:57<05:07, 23.85it/s]

 61%|██████    | 11435/18769 [07:57<05:08, 23.80it/s]

 61%|██████    | 11438/18769 [07:57<05:08, 23.79it/s]

 61%|██████    | 11441/18769 [07:57<05:07, 23.80it/s]

 61%|██████    | 11444/18769 [07:57<05:08, 23.77it/s]

 61%|██████    | 11447/18769 [07:57<05:08, 23.74it/s]

 61%|██████    | 11450/18769 [07:58<05:08, 23.71it/s]

 61%|██████    | 11453/18769 [07:58<05:10, 23.56it/s]

 61%|██████    | 11457/18769 [07:58<04:47, 25.41it/s]

 61%|██████    | 11460/18769 [07:58<04:54, 24.82it/s]

 61%|██████    | 11463/18769 [07:58<04:59, 24.42it/s]

 61%|██████    | 11466/18769 [07:58<05:02, 24.15it/s]

 61%|██████    | 11469/18769 [07:58<05:04, 23.97it/s]

 61%|██████    | 11472/18769 [07:58<05:08, 23.66it/s]

 61%|██████    | 11475/18769 [07:59<05:08, 23.62it/s]

 61%|██████    | 11478/18769 [07:59<05:10, 23.51it/s]

 61%|██████    | 11481/18769 [07:59<05:10, 23.47it/s]

 61%|██████    | 11484/18769 [07:59<05:10, 23.46it/s]

 61%|██████    | 11487/18769 [07:59<05:11, 23.40it/s]

 61%|██████    | 11490/18769 [07:59<05:10, 23.47it/s]

 61%|██████    | 11493/18769 [07:59<05:09, 23.50it/s]

 61%|██████    | 11496/18769 [07:59<05:09, 23.49it/s]

 61%|██████▏   | 11499/18769 [08:00<05:09, 23.50it/s]

 61%|██████▏   | 11502/18769 [08:00<05:09, 23.50it/s]

 61%|██████▏   | 11505/18769 [08:00<05:08, 23.52it/s]

 61%|██████▏   | 11508/18769 [08:00<05:06, 23.70it/s]

 61%|██████▏   | 11511/18769 [08:00<05:04, 23.82it/s]

 61%|██████▏   | 11514/18769 [08:00<05:03, 23.91it/s]

 61%|██████▏   | 11517/18769 [08:00<05:02, 23.99it/s]

 61%|██████▏   | 11520/18769 [08:01<05:04, 23.84it/s]

 61%|██████▏   | 11523/18769 [08:01<05:02, 23.93it/s]

 61%|██████▏   | 11526/18769 [08:01<05:01, 24.00it/s]

 61%|██████▏   | 11529/18769 [08:01<05:00, 24.06it/s]

 61%|██████▏   | 11532/18769 [08:01<05:00, 24.11it/s]

 61%|██████▏   | 11535/18769 [08:01<04:59, 24.13it/s]

 61%|██████▏   | 11538/18769 [08:01<04:58, 24.24it/s]

 61%|██████▏   | 11541/18769 [08:01<04:58, 24.22it/s]

 62%|██████▏   | 11544/18769 [08:01<04:58, 24.23it/s]

 62%|██████▏   | 11547/18769 [08:02<04:58, 24.23it/s]

 62%|██████▏   | 11550/18769 [08:02<04:57, 24.23it/s]

 62%|██████▏   | 11553/18769 [08:02<04:57, 24.28it/s]

 62%|██████▏   | 11556/18769 [08:02<04:57, 24.26it/s]

 62%|██████▏   | 11559/18769 [08:02<04:57, 24.20it/s]

 62%|██████▏   | 11562/18769 [08:02<04:57, 24.19it/s]

 62%|██████▏   | 11565/18769 [08:02<04:59, 24.04it/s]

 62%|██████▏   | 11568/18769 [08:02<05:04, 23.65it/s]

 62%|██████▏   | 11571/18769 [08:03<05:03, 23.69it/s]

 62%|██████▏   | 11574/18769 [08:03<05:03, 23.72it/s]

 62%|██████▏   | 11577/18769 [08:03<05:03, 23.70it/s]

 62%|██████▏   | 11580/18769 [08:03<05:03, 23.65it/s]

 62%|██████▏   | 11583/18769 [08:03<05:03, 23.69it/s]

 62%|██████▏   | 11586/18769 [08:03<05:03, 23.70it/s]

 62%|██████▏   | 11589/18769 [08:03<05:03, 23.68it/s]

 62%|██████▏   | 11592/18769 [08:04<05:03, 23.64it/s]

 62%|██████▏   | 11596/18769 [08:04<04:41, 25.50it/s]

 62%|██████▏   | 11599/18769 [08:04<04:49, 24.74it/s]

 62%|██████▏   | 11602/18769 [08:04<04:54, 24.34it/s]

 62%|██████▏   | 11605/18769 [08:04<04:56, 24.13it/s]

 62%|██████▏   | 11608/18769 [08:04<04:58, 24.00it/s]

 62%|██████▏   | 11611/18769 [08:04<04:59, 23.90it/s]

 62%|██████▏   | 11614/18769 [08:04<05:00, 23.81it/s]

 62%|██████▏   | 11617/18769 [08:05<05:03, 23.59it/s]

 62%|██████▏   | 11620/18769 [08:05<05:04, 23.49it/s]

 62%|██████▏   | 11623/18769 [08:05<05:04, 23.50it/s]

 62%|██████▏   | 11626/18769 [08:05<05:03, 23.54it/s]

 62%|██████▏   | 11629/18769 [08:05<05:02, 23.60it/s]

 62%|██████▏   | 11632/18769 [08:05<05:02, 23.61it/s]

 62%|██████▏   | 11635/18769 [08:05<05:02, 23.60it/s]

 62%|██████▏   | 11638/18769 [08:05<05:02, 23.59it/s]

 62%|██████▏   | 11641/18769 [08:06<05:02, 23.58it/s]

 62%|██████▏   | 11644/18769 [08:06<05:02, 23.59it/s]

 62%|██████▏   | 11647/18769 [08:06<05:00, 23.73it/s]

 62%|██████▏   | 11650/18769 [08:06<04:59, 23.79it/s]

 62%|██████▏   | 11653/18769 [08:06<04:57, 23.89it/s]

 62%|██████▏   | 11656/18769 [08:06<04:56, 23.99it/s]

 62%|██████▏   | 11659/18769 [08:06<04:55, 24.05it/s]

 62%|██████▏   | 11662/18769 [08:06<04:55, 24.06it/s]

 62%|██████▏   | 11665/18769 [08:07<04:57, 23.87it/s]

 62%|██████▏   | 11668/18769 [08:07<04:56, 23.93it/s]

 62%|██████▏   | 11671/18769 [08:07<04:56, 23.93it/s]

 62%|██████▏   | 11674/18769 [08:07<04:56, 23.92it/s]

 62%|██████▏   | 11677/18769 [08:07<04:55, 23.98it/s]

 62%|██████▏   | 11680/18769 [08:07<04:55, 23.99it/s]

 62%|██████▏   | 11683/18769 [08:07<04:54, 24.05it/s]

 62%|██████▏   | 11686/18769 [08:07<04:54, 24.03it/s]

 62%|██████▏   | 11689/18769 [08:08<04:54, 24.05it/s]

 62%|██████▏   | 11692/18769 [08:08<04:54, 24.04it/s]

 62%|██████▏   | 11695/18769 [08:08<04:54, 24.04it/s]

 62%|██████▏   | 11698/18769 [08:08<04:54, 24.04it/s]

 62%|██████▏   | 11701/18769 [08:08<04:54, 23.98it/s]

 62%|██████▏   | 11704/18769 [08:08<04:55, 23.92it/s]

 62%|██████▏   | 11707/18769 [08:08<04:56, 23.85it/s]

 62%|██████▏   | 11710/18769 [08:08<04:56, 23.79it/s]

 62%|██████▏   | 11713/18769 [08:09<04:59, 23.60it/s]

 62%|██████▏   | 11716/18769 [08:09<04:58, 23.62it/s]

 62%|██████▏   | 11719/18769 [08:09<05:01, 23.41it/s]

 62%|██████▏   | 11722/18769 [08:09<05:01, 23.39it/s]

 62%|██████▏   | 11725/18769 [08:09<04:59, 23.51it/s]

 62%|██████▏   | 11728/18769 [08:09<04:58, 23.57it/s]

 63%|██████▎   | 11732/18769 [08:09<04:36, 25.44it/s]

 63%|██████▎   | 11735/18769 [08:09<04:43, 24.79it/s]

 63%|██████▎   | 11738/18769 [08:10<04:49, 24.26it/s]

 63%|██████▎   | 11741/18769 [08:10<04:51, 24.08it/s]

 63%|██████▎   | 11744/18769 [08:10<04:52, 24.00it/s]

 63%|██████▎   | 11747/18769 [08:10<04:54, 23.87it/s]

 63%|██████▎   | 11750/18769 [08:10<04:54, 23.80it/s]

 63%|██████▎   | 11753/18769 [08:10<04:55, 23.74it/s]

 63%|██████▎   | 11756/18769 [08:10<04:56, 23.69it/s]

 63%|██████▎   | 11759/18769 [08:10<04:56, 23.63it/s]

 63%|██████▎   | 11762/18769 [08:11<04:57, 23.55it/s]

 63%|██████▎   | 11765/18769 [08:11<04:57, 23.51it/s]

 63%|██████▎   | 11768/18769 [08:11<04:58, 23.49it/s]

 63%|██████▎   | 11771/18769 [08:11<04:58, 23.47it/s]

 63%|██████▎   | 11774/18769 [08:11<04:57, 23.48it/s]

 63%|██████▎   | 11777/18769 [08:11<04:57, 23.52it/s]

 63%|██████▎   | 11780/18769 [08:11<04:57, 23.53it/s]

 63%|██████▎   | 11783/18769 [08:11<04:54, 23.71it/s]

 63%|██████▎   | 11786/18769 [08:12<04:53, 23.81it/s]

 63%|██████▎   | 11789/18769 [08:12<04:53, 23.81it/s]

 63%|██████▎   | 11792/18769 [08:12<04:53, 23.77it/s]

 63%|██████▎   | 11795/18769 [08:12<04:52, 23.81it/s]

 63%|██████▎   | 11798/18769 [08:12<04:53, 23.75it/s]

 63%|██████▎   | 11801/18769 [08:12<04:53, 23.76it/s]

 63%|██████▎   | 11804/18769 [08:12<04:53, 23.75it/s]

 63%|██████▎   | 11807/18769 [08:13<04:52, 23.81it/s]

 63%|██████▎   | 11810/18769 [08:13<04:53, 23.75it/s]

 63%|██████▎   | 11813/18769 [08:13<04:51, 23.90it/s]

 63%|██████▎   | 11816/18769 [08:13<04:50, 23.96it/s]

 63%|██████▎   | 11819/18769 [08:13<04:49, 24.00it/s]

 63%|██████▎   | 11822/18769 [08:13<04:48, 24.04it/s]

 63%|██████▎   | 11825/18769 [08:13<04:48, 24.06it/s]

 63%|██████▎   | 11828/18769 [08:13<04:48, 24.10it/s]

 63%|██████▎   | 11831/18769 [08:13<04:47, 24.12it/s]

 63%|██████▎   | 11834/18769 [08:14<04:49, 23.95it/s]

 63%|██████▎   | 11837/18769 [08:14<04:48, 24.01it/s]

 63%|██████▎   | 11840/18769 [08:14<04:55, 23.42it/s]

 63%|██████▎   | 11843/18769 [08:14<04:54, 23.53it/s]

 63%|██████▎   | 11846/18769 [08:14<04:53, 23.59it/s]

 63%|██████▎   | 11849/18769 [08:14<04:52, 23.62it/s]

 63%|██████▎   | 11852/18769 [08:14<04:52, 23.68it/s]

 63%|██████▎   | 11855/18769 [08:15<04:51, 23.71it/s]

 63%|██████▎   | 11858/18769 [08:15<04:51, 23.71it/s]

 63%|██████▎   | 11861/18769 [08:15<04:51, 23.71it/s]

 63%|██████▎   | 11864/18769 [08:15<04:52, 23.62it/s]

 63%|██████▎   | 11867/18769 [08:15<04:52, 23.56it/s]

 63%|██████▎   | 11871/18769 [08:15<04:31, 25.42it/s]

 63%|██████▎   | 11874/18769 [08:15<04:38, 24.76it/s]

 63%|██████▎   | 11877/18769 [08:15<04:42, 24.37it/s]

 63%|██████▎   | 11880/18769 [08:16<04:45, 24.13it/s]

 63%|██████▎   | 11883/18769 [08:16<04:50, 23.71it/s]

 63%|██████▎   | 11886/18769 [08:16<04:51, 23.65it/s]

 63%|██████▎   | 11889/18769 [08:16<04:51, 23.62it/s]

 63%|██████▎   | 11892/18769 [08:16<04:51, 23.58it/s]

 63%|██████▎   | 11895/18769 [08:16<04:51, 23.58it/s]

 63%|██████▎   | 11898/18769 [08:16<04:51, 23.57it/s]

 63%|██████▎   | 11901/18769 [08:16<04:51, 23.57it/s]

 63%|██████▎   | 11904/18769 [08:17<04:50, 23.62it/s]

 63%|██████▎   | 11907/18769 [08:17<04:52, 23.43it/s]

 63%|██████▎   | 11910/18769 [08:17<04:51, 23.51it/s]

 63%|██████▎   | 11913/18769 [08:17<04:51, 23.54it/s]

 63%|██████▎   | 11916/18769 [08:17<04:50, 23.57it/s]

 64%|██████▎   | 11919/18769 [08:17<04:49, 23.68it/s]

 64%|██████▎   | 11922/18769 [08:17<04:48, 23.70it/s]

 64%|██████▎   | 11925/18769 [08:17<04:48, 23.76it/s]

 64%|██████▎   | 11928/18769 [08:18<04:46, 23.88it/s]

 64%|██████▎   | 11931/18769 [08:18<04:46, 23.89it/s]

 64%|██████▎   | 11934/18769 [08:18<04:46, 23.87it/s]

 64%|██████▎   | 11937/18769 [08:18<04:46, 23.88it/s]

 64%|██████▎   | 11940/18769 [08:18<04:45, 23.91it/s]

 64%|██████▎   | 11943/18769 [08:18<04:44, 23.95it/s]

 64%|██████▎   | 11946/18769 [08:18<04:44, 23.97it/s]

 64%|██████▎   | 11949/18769 [08:18<04:43, 24.08it/s]

 64%|██████▎   | 11952/18769 [08:19<04:43, 24.08it/s]

 64%|██████▎   | 11955/18769 [08:19<04:45, 23.87it/s]

 64%|██████▎   | 11958/18769 [08:19<04:44, 23.94it/s]

 64%|██████▎   | 11961/18769 [08:19<04:44, 23.93it/s]

 64%|██████▎   | 11964/18769 [08:19<04:43, 24.00it/s]

 64%|██████▍   | 11967/18769 [08:19<04:42, 24.07it/s]

 64%|██████▍   | 11970/18769 [08:19<04:41, 24.12it/s]

 64%|██████▍   | 11973/18769 [08:19<04:41, 24.13it/s]

 64%|██████▍   | 11976/18769 [08:20<04:42, 24.04it/s]

 64%|██████▍   | 11979/18769 [08:20<04:44, 23.84it/s]

 64%|██████▍   | 11982/18769 [08:20<04:45, 23.81it/s]

 64%|██████▍   | 11985/18769 [08:20<04:44, 23.84it/s]

 64%|██████▍   | 11988/18769 [08:20<04:44, 23.84it/s]

 64%|██████▍   | 11991/18769 [08:20<04:44, 23.80it/s]

 64%|██████▍   | 11994/18769 [08:20<04:44, 23.84it/s]

 64%|██████▍   | 11997/18769 [08:20<04:44, 23.82it/s]

 64%|██████▍   | 12000/18769 [08:21<04:44, 23.79it/s]

 64%|██████▍   | 12003/18769 [08:21<04:44, 23.74it/s]

 64%|██████▍   | 12006/18769 [08:21<04:46, 23.57it/s]

 64%|██████▍   | 12010/18769 [08:21<04:26, 25.41it/s]

 64%|██████▍   | 12013/18769 [08:21<04:32, 24.81it/s]

 64%|██████▍   | 12016/18769 [08:21<04:36, 24.46it/s]

 64%|██████▍   | 12019/18769 [08:21<04:38, 24.23it/s]

 64%|██████▍   | 12022/18769 [08:21<04:40, 24.08it/s]

 64%|██████▍   | 12025/18769 [08:22<04:41, 23.92it/s]

 64%|██████▍   | 12028/18769 [08:22<04:42, 23.83it/s]

 64%|██████▍   | 12031/18769 [08:22<04:42, 23.82it/s]

 64%|██████▍   | 12034/18769 [08:22<04:43, 23.77it/s]

 64%|██████▍   | 12037/18769 [08:22<04:43, 23.75it/s]

 64%|██████▍   | 12040/18769 [08:22<04:43, 23.69it/s]

 64%|██████▍   | 12043/18769 [08:22<04:44, 23.67it/s]

 64%|██████▍   | 12046/18769 [08:22<04:44, 23.60it/s]

 64%|██████▍   | 12049/18769 [08:23<04:44, 23.59it/s]

 64%|██████▍   | 12052/18769 [08:23<04:44, 23.58it/s]

 64%|██████▍   | 12055/18769 [08:23<04:44, 23.58it/s]

 64%|██████▍   | 12058/18769 [08:23<04:43, 23.67it/s]

 64%|██████▍   | 12061/18769 [08:23<04:42, 23.71it/s]

 64%|██████▍   | 12064/18769 [08:23<04:42, 23.76it/s]

 64%|██████▍   | 12067/18769 [08:23<04:41, 23.80it/s]

 64%|██████▍   | 12070/18769 [08:24<04:41, 23.79it/s]

 64%|██████▍   | 12073/18769 [08:24<04:43, 23.58it/s]

 64%|██████▍   | 12076/18769 [08:24<04:43, 23.60it/s]

 64%|██████▍   | 12079/18769 [08:24<04:42, 23.72it/s]

 64%|██████▍   | 12082/18769 [08:24<04:41, 23.78it/s]

 64%|██████▍   | 12085/18769 [08:24<04:41, 23.76it/s]

 64%|██████▍   | 12088/18769 [08:24<04:40, 23.83it/s]

 64%|██████▍   | 12091/18769 [08:24<04:40, 23.80it/s]

 64%|██████▍   | 12094/18769 [08:25<04:40, 23.82it/s]

 64%|██████▍   | 12097/18769 [08:25<04:42, 23.65it/s]

 64%|██████▍   | 12100/18769 [08:25<04:41, 23.73it/s]

 64%|██████▍   | 12103/18769 [08:25<04:40, 23.78it/s]

 64%|██████▍   | 12106/18769 [08:25<04:39, 23.84it/s]

 65%|██████▍   | 12109/18769 [08:25<04:38, 23.87it/s]

 65%|██████▍   | 12112/18769 [08:25<04:39, 23.84it/s]

 65%|██████▍   | 12115/18769 [08:25<04:39, 23.77it/s]

 65%|██████▍   | 12118/18769 [08:26<04:40, 23.74it/s]

 65%|██████▍   | 12121/18769 [08:26<04:40, 23.71it/s]

 65%|██████▍   | 12124/18769 [08:26<04:40, 23.65it/s]

 65%|██████▍   | 12127/18769 [08:26<04:41, 23.63it/s]

 65%|██████▍   | 12130/18769 [08:26<04:40, 23.64it/s]

 65%|██████▍   | 12133/18769 [08:26<04:40, 23.64it/s]

 65%|██████▍   | 12136/18769 [08:26<04:40, 23.61it/s]

 65%|██████▍   | 12139/18769 [08:26<04:41, 23.56it/s]

 65%|██████▍   | 12142/18769 [08:27<04:42, 23.46it/s]

 65%|██████▍   | 12146/18769 [08:27<04:23, 25.12it/s]

 65%|██████▍   | 12149/18769 [08:27<04:30, 24.52it/s]

 65%|██████▍   | 12152/18769 [08:27<04:33, 24.19it/s]

 65%|██████▍   | 12155/18769 [08:27<04:36, 23.95it/s]

 65%|██████▍   | 12158/18769 [08:27<04:37, 23.83it/s]

 65%|██████▍   | 12161/18769 [08:27<04:38, 23.76it/s]

 65%|██████▍   | 12164/18769 [08:27<04:39, 23.66it/s]

 65%|██████▍   | 12167/18769 [08:28<04:39, 23.61it/s]

 65%|██████▍   | 12170/18769 [08:28<04:40, 23.49it/s]

 65%|██████▍   | 12173/18769 [08:28<04:40, 23.49it/s]

 65%|██████▍   | 12176/18769 [08:28<04:40, 23.48it/s]

 65%|██████▍   | 12179/18769 [08:28<04:40, 23.48it/s]

 65%|██████▍   | 12182/18769 [08:28<04:40, 23.49it/s]

 65%|██████▍   | 12185/18769 [08:28<04:40, 23.50it/s]

 65%|██████▍   | 12188/18769 [08:28<04:40, 23.46it/s]

 65%|██████▍   | 12191/18769 [08:29<04:40, 23.49it/s]

 65%|██████▍   | 12194/18769 [08:29<04:40, 23.45it/s]

 65%|██████▍   | 12197/18769 [08:29<04:37, 23.65it/s]

 65%|██████▌   | 12200/18769 [08:29<04:35, 23.81it/s]

 65%|██████▌   | 12203/18769 [08:29<04:34, 23.93it/s]

 65%|██████▌   | 12206/18769 [08:29<04:33, 24.03it/s]

 65%|██████▌   | 12209/18769 [08:29<04:32, 24.05it/s]

 65%|██████▌   | 12212/18769 [08:29<04:32, 24.09it/s]

 65%|██████▌   | 12215/18769 [08:30<04:31, 24.11it/s]

 65%|██████▌   | 12218/18769 [08:30<04:32, 24.07it/s]

 65%|██████▌   | 12221/18769 [08:30<04:32, 24.07it/s]

 65%|██████▌   | 12224/18769 [08:30<04:31, 24.08it/s]

 65%|██████▌   | 12227/18769 [08:30<04:31, 24.13it/s]

 65%|██████▌   | 12230/18769 [08:30<04:31, 24.12it/s]

 65%|██████▌   | 12233/18769 [08:30<04:30, 24.13it/s]

 65%|██████▌   | 12236/18769 [08:30<04:30, 24.13it/s]

 65%|██████▌   | 12239/18769 [08:31<04:30, 24.17it/s]

 65%|██████▌   | 12242/18769 [08:31<04:32, 23.98it/s]

 65%|██████▌   | 12245/18769 [08:31<04:31, 24.03it/s]

 65%|██████▌   | 12248/18769 [08:31<04:32, 23.95it/s]

 65%|██████▌   | 12251/18769 [08:31<04:32, 23.90it/s]

 65%|██████▌   | 12254/18769 [08:31<04:32, 23.88it/s]

 65%|██████▌   | 12257/18769 [08:31<04:32, 23.88it/s]

 65%|██████▌   | 12260/18769 [08:31<04:32, 23.87it/s]

 65%|██████▌   | 12263/18769 [08:32<04:32, 23.85it/s]

 65%|██████▌   | 12266/18769 [08:32<04:33, 23.78it/s]

 65%|██████▌   | 12269/18769 [08:32<04:33, 23.78it/s]

 65%|██████▌   | 12272/18769 [08:32<04:33, 23.74it/s]

 65%|██████▌   | 12275/18769 [08:32<04:34, 23.69it/s]

 65%|██████▌   | 12278/18769 [08:32<04:34, 23.63it/s]

 65%|██████▌   | 12281/18769 [08:32<04:35, 23.53it/s]

 65%|██████▌   | 12285/18769 [08:32<04:16, 25.32it/s]

 65%|██████▌   | 12288/18769 [08:33<04:21, 24.76it/s]

 65%|██████▌   | 12291/18769 [08:33<04:27, 24.20it/s]

 66%|██████▌   | 12294/18769 [08:33<04:29, 24.01it/s]

 66%|██████▌   | 12297/18769 [08:33<04:30, 23.89it/s]

 66%|██████▌   | 12300/18769 [08:33<04:31, 23.85it/s]

 66%|██████▌   | 12303/18769 [08:33<04:32, 23.74it/s]

 66%|██████▌   | 12306/18769 [08:33<04:33, 23.66it/s]

 66%|██████▌   | 12309/18769 [08:34<04:33, 23.63it/s]

 66%|██████▌   | 12312/18769 [08:34<04:33, 23.59it/s]

 66%|██████▌   | 12315/18769 [08:34<04:34, 23.53it/s]

 66%|██████▌   | 12318/18769 [08:34<04:33, 23.55it/s]

 66%|██████▌   | 12321/18769 [08:34<04:32, 23.62it/s]

 66%|██████▌   | 12324/18769 [08:34<04:32, 23.61it/s]

 66%|██████▌   | 12327/18769 [08:34<04:33, 23.56it/s]

 66%|██████▌   | 12330/18769 [08:34<04:31, 23.70it/s]

 66%|██████▌   | 12333/18769 [08:35<04:30, 23.79it/s]

 66%|██████▌   | 12336/18769 [08:35<04:29, 23.85it/s]

 66%|██████▌   | 12339/18769 [08:35<04:30, 23.80it/s]

 66%|██████▌   | 12342/18769 [08:35<04:29, 23.88it/s]

 66%|██████▌   | 12345/18769 [08:35<04:28, 23.94it/s]

 66%|██████▌   | 12348/18769 [08:35<04:27, 23.99it/s]

 66%|██████▌   | 12351/18769 [08:35<04:26, 24.04it/s]

 66%|██████▌   | 12354/18769 [08:35<04:26, 24.04it/s]

 66%|██████▌   | 12357/18769 [08:36<04:26, 24.05it/s]

 66%|██████▌   | 12360/18769 [08:36<04:27, 23.93it/s]

 66%|██████▌   | 12363/18769 [08:36<04:28, 23.88it/s]

 66%|██████▌   | 12366/18769 [08:36<04:27, 23.95it/s]

 66%|██████▌   | 12369/18769 [08:36<04:26, 23.98it/s]

 66%|██████▌   | 12372/18769 [08:36<04:26, 24.02it/s]

 66%|██████▌   | 12375/18769 [08:36<04:25, 24.09it/s]

 66%|██████▌   | 12378/18769 [08:36<04:25, 24.11it/s]

 66%|██████▌   | 12381/18769 [08:37<04:24, 24.14it/s]

 66%|██████▌   | 12384/18769 [08:37<04:24, 24.10it/s]

 66%|██████▌   | 12387/18769 [08:37<04:26, 23.96it/s]

 66%|██████▌   | 12390/18769 [08:37<04:27, 23.86it/s]

 66%|██████▌   | 12393/18769 [08:37<04:27, 23.82it/s]

 66%|██████▌   | 12396/18769 [08:37<04:27, 23.78it/s]

 66%|██████▌   | 12399/18769 [08:37<04:27, 23.77it/s]

 66%|██████▌   | 12402/18769 [08:37<04:30, 23.56it/s]

 66%|██████▌   | 12405/18769 [08:38<04:29, 23.62it/s]

 66%|██████▌   | 12408/18769 [08:38<04:29, 23.62it/s]

 66%|██████▌   | 12411/18769 [08:38<04:29, 23.59it/s]

 66%|██████▌   | 12414/18769 [08:38<04:29, 23.56it/s]

 66%|██████▌   | 12417/18769 [08:38<04:30, 23.45it/s]

 66%|██████▌   | 12420/18769 [08:38<04:31, 23.40it/s]

 66%|██████▌   | 12424/18769 [08:38<04:10, 25.33it/s]

 66%|██████▌   | 12427/18769 [08:38<04:15, 24.78it/s]

 66%|██████▌   | 12430/18769 [08:39<04:19, 24.41it/s]

 66%|██████▌   | 12433/18769 [08:39<04:22, 24.16it/s]

 66%|██████▋   | 12436/18769 [08:39<04:27, 23.71it/s]

 66%|██████▋   | 12439/18769 [08:39<04:27, 23.63it/s]

 66%|██████▋   | 12442/18769 [08:39<04:28, 23.60it/s]

 66%|██████▋   | 12445/18769 [08:39<04:27, 23.60it/s]

 66%|██████▋   | 12448/18769 [08:39<04:27, 23.63it/s]

 66%|██████▋   | 12451/18769 [08:39<04:27, 23.61it/s]

 66%|██████▋   | 12454/18769 [08:40<04:27, 23.63it/s]

 66%|██████▋   | 12457/18769 [08:40<04:27, 23.56it/s]

 66%|██████▋   | 12460/18769 [08:40<04:28, 23.52it/s]

 66%|██████▋   | 12463/18769 [08:40<04:27, 23.54it/s]

 66%|██████▋   | 12466/18769 [08:40<04:27, 23.60it/s]

 66%|██████▋   | 12469/18769 [08:40<04:25, 23.75it/s]

 66%|██████▋   | 12472/18769 [08:40<04:24, 23.84it/s]

 66%|██████▋   | 12475/18769 [08:40<04:23, 23.91it/s]

 66%|██████▋   | 12478/18769 [08:41<04:22, 23.97it/s]

 66%|██████▋   | 12481/18769 [08:41<04:21, 24.00it/s]

 67%|██████▋   | 12484/18769 [08:41<04:23, 23.81it/s]

 67%|██████▋   | 12487/18769 [08:41<04:22, 23.89it/s]

 67%|██████▋   | 12490/18769 [08:41<04:21, 23.98it/s]

 67%|██████▋   | 12493/18769 [08:41<04:21, 23.98it/s]

 67%|██████▋   | 12496/18769 [08:41<04:26, 23.57it/s]

 67%|██████▋   | 12499/18769 [08:41<04:24, 23.67it/s]

 67%|██████▋   | 12502/18769 [08:42<04:23, 23.78it/s]

 67%|██████▋   | 12505/18769 [08:42<04:21, 23.91it/s]

 67%|██████▋   | 12508/18769 [08:42<04:21, 23.91it/s]

 67%|██████▋   | 12511/18769 [08:42<04:21, 23.95it/s]

 67%|██████▋   | 12514/18769 [08:42<04:20, 24.00it/s]

 67%|██████▋   | 12517/18769 [08:42<04:19, 24.07it/s]

 67%|██████▋   | 12520/18769 [08:42<04:19, 24.11it/s]

 67%|██████▋   | 12523/18769 [08:42<04:20, 24.02it/s]

 67%|██████▋   | 12526/18769 [08:43<04:20, 23.97it/s]

 67%|██████▋   | 12529/18769 [08:43<04:22, 23.78it/s]

 67%|██████▋   | 12532/18769 [08:43<04:23, 23.70it/s]

 67%|██████▋   | 12535/18769 [08:43<04:23, 23.67it/s]

 67%|██████▋   | 12538/18769 [08:43<04:23, 23.68it/s]

 67%|██████▋   | 12541/18769 [08:43<04:23, 23.66it/s]

 67%|██████▋   | 12544/18769 [08:43<04:23, 23.65it/s]

 67%|██████▋   | 12547/18769 [08:43<04:22, 23.67it/s]

 67%|██████▋   | 12550/18769 [08:44<04:23, 23.63it/s]

 67%|██████▋   | 12553/18769 [08:44<04:24, 23.51it/s]

 67%|██████▋   | 12556/18769 [08:44<04:25, 23.39it/s]

 67%|██████▋   | 12560/18769 [08:44<04:05, 25.27it/s]

 67%|██████▋   | 12563/18769 [08:44<04:10, 24.73it/s]

 67%|██████▋   | 12566/18769 [08:44<04:14, 24.40it/s]

 67%|██████▋   | 12569/18769 [08:44<04:16, 24.16it/s]

 67%|██████▋   | 12572/18769 [08:45<04:18, 24.00it/s]

 67%|██████▋   | 12575/18769 [08:45<04:19, 23.83it/s]

 67%|██████▋   | 12578/18769 [08:45<04:20, 23.78it/s]

 67%|██████▋   | 12581/18769 [08:45<04:23, 23.52it/s]

 67%|██████▋   | 12584/18769 [08:45<04:22, 23.55it/s]

 67%|██████▋   | 12587/18769 [08:45<04:22, 23.57it/s]

 67%|██████▋   | 12590/18769 [08:45<04:22, 23.56it/s]

 67%|██████▋   | 12593/18769 [08:45<04:22, 23.53it/s]

 67%|██████▋   | 12596/18769 [08:46<04:22, 23.53it/s]

 67%|██████▋   | 12599/18769 [08:46<04:22, 23.47it/s]

 67%|██████▋   | 12602/18769 [08:46<04:22, 23.49it/s]

 67%|██████▋   | 12605/18769 [08:46<04:21, 23.61it/s]

 67%|██████▋   | 12608/18769 [08:46<04:19, 23.71it/s]

 67%|██████▋   | 12611/18769 [08:46<04:18, 23.82it/s]

 67%|██████▋   | 12614/18769 [08:46<04:17, 23.90it/s]

 67%|██████▋   | 12617/18769 [08:46<04:16, 23.94it/s]

 67%|██████▋   | 12620/18769 [08:47<04:16, 23.97it/s]

 67%|██████▋   | 12623/18769 [08:47<04:15, 24.01it/s]

 67%|██████▋   | 12626/18769 [08:47<04:15, 24.02it/s]

 67%|██████▋   | 12629/18769 [08:47<04:17, 23.82it/s]

 67%|██████▋   | 12632/18769 [08:47<04:17, 23.85it/s]

 67%|██████▋   | 12635/18769 [08:47<04:16, 23.91it/s]

 67%|██████▋   | 12638/18769 [08:47<04:15, 23.96it/s]

 67%|██████▋   | 12641/18769 [08:47<04:15, 24.01it/s]

 67%|██████▋   | 12644/18769 [08:48<04:14, 24.04it/s]

 67%|██████▋   | 12647/18769 [08:48<04:14, 24.03it/s]

 67%|██████▋   | 12650/18769 [08:48<04:14, 24.08it/s]

 67%|██████▋   | 12653/18769 [08:48<04:14, 24.08it/s]

 67%|██████▋   | 12656/18769 [08:48<04:13, 24.12it/s]

 67%|██████▋   | 12659/18769 [08:48<04:13, 24.09it/s]

 67%|██████▋   | 12662/18769 [08:48<04:14, 24.00it/s]

 67%|██████▋   | 12665/18769 [08:48<04:14, 23.95it/s]

 67%|██████▋   | 12668/18769 [08:49<04:15, 23.90it/s]

 68%|██████▊   | 12671/18769 [08:49<04:15, 23.88it/s]

 68%|██████▊   | 12674/18769 [08:49<04:15, 23.88it/s]

 68%|██████▊   | 12677/18769 [08:49<04:15, 23.82it/s]

 68%|██████▊   | 12680/18769 [08:49<04:15, 23.82it/s]

 68%|██████▊   | 12683/18769 [08:49<04:16, 23.75it/s]

 68%|██████▊   | 12686/18769 [08:49<04:16, 23.72it/s]

 68%|██████▊   | 12689/18769 [08:49<04:16, 23.69it/s]

 68%|██████▊   | 12692/18769 [08:50<04:17, 23.64it/s]

 68%|██████▊   | 12695/18769 [08:50<04:17, 23.59it/s]

 68%|██████▊   | 12699/18769 [08:50<03:57, 25.53it/s]

 68%|██████▊   | 12702/18769 [08:50<04:03, 24.96it/s]

 68%|██████▊   | 12705/18769 [08:50<04:06, 24.57it/s]

 68%|██████▊   | 12708/18769 [08:50<04:09, 24.32it/s]

 68%|██████▊   | 12711/18769 [08:50<04:11, 24.11it/s]

 68%|██████▊   | 12714/18769 [08:50<04:13, 23.93it/s]

 68%|██████▊   | 12717/18769 [08:51<04:13, 23.85it/s]

 68%|██████▊   | 12720/18769 [08:51<04:14, 23.78it/s]

 68%|██████▊   | 12723/18769 [08:51<04:14, 23.77it/s]

 68%|██████▊   | 12726/18769 [08:51<04:15, 23.69it/s]

 68%|██████▊   | 12729/18769 [08:51<04:15, 23.68it/s]

 68%|██████▊   | 12732/18769 [08:51<04:14, 23.68it/s]

 68%|██████▊   | 12735/18769 [08:51<04:15, 23.64it/s]

 68%|██████▊   | 12738/18769 [08:51<04:15, 23.64it/s]

 68%|██████▊   | 12741/18769 [08:52<04:14, 23.71it/s]

 68%|██████▊   | 12744/18769 [08:52<04:13, 23.75it/s]

 68%|██████▊   | 12747/18769 [08:52<04:12, 23.84it/s]

 68%|██████▊   | 12750/18769 [08:52<04:13, 23.72it/s]

 68%|██████▊   | 12753/18769 [08:52<04:12, 23.82it/s]

 68%|██████▊   | 12756/18769 [08:52<04:11, 23.90it/s]

 68%|██████▊   | 12759/18769 [08:52<04:11, 23.93it/s]

 68%|██████▊   | 12762/18769 [08:52<04:11, 23.84it/s]

 68%|██████▊   | 12765/18769 [08:53<04:10, 23.92it/s]

 68%|██████▊   | 12768/18769 [08:53<04:09, 24.01it/s]

 68%|██████▊   | 12771/18769 [08:53<04:10, 23.91it/s]

 68%|██████▊   | 12774/18769 [08:53<04:10, 23.92it/s]

 68%|██████▊   | 12777/18769 [08:53<04:10, 23.96it/s]

 68%|██████▊   | 12780/18769 [08:53<04:09, 24.01it/s]

 68%|██████▊   | 12783/18769 [08:53<04:10, 23.92it/s]

 68%|██████▊   | 12786/18769 [08:53<04:09, 23.99it/s]

 68%|██████▊   | 12789/18769 [08:54<04:09, 23.95it/s]

 68%|██████▊   | 12792/18769 [08:54<04:09, 23.96it/s]

 68%|██████▊   | 12795/18769 [08:54<04:09, 23.98it/s]

 68%|██████▊   | 12798/18769 [08:54<04:10, 23.85it/s]

 68%|██████▊   | 12801/18769 [08:54<04:10, 23.83it/s]

 68%|██████▊   | 12804/18769 [08:54<04:10, 23.78it/s]

 68%|██████▊   | 12807/18769 [08:54<04:11, 23.71it/s]

 68%|██████▊   | 12810/18769 [08:54<04:11, 23.71it/s]

 68%|██████▊   | 12813/18769 [08:55<04:11, 23.73it/s]

 68%|██████▊   | 12816/18769 [08:55<04:11, 23.70it/s]

 68%|██████▊   | 12819/18769 [08:55<04:10, 23.71it/s]

 68%|██████▊   | 12822/18769 [08:55<04:14, 23.41it/s]

 68%|██████▊   | 12825/18769 [08:55<04:13, 23.42it/s]

 68%|██████▊   | 12828/18769 [08:55<04:12, 23.48it/s]

 68%|██████▊   | 12831/18769 [08:55<04:12, 23.49it/s]

 68%|██████▊   | 12834/18769 [08:55<04:12, 23.49it/s]

 68%|██████▊   | 12838/18769 [08:56<03:53, 25.37it/s]

 68%|██████▊   | 12841/18769 [08:56<04:00, 24.67it/s]

 68%|██████▊   | 12844/18769 [08:56<04:03, 24.29it/s]

 68%|██████▊   | 12847/18769 [08:56<04:06, 24.06it/s]

 68%|██████▊   | 12850/18769 [08:56<04:08, 23.84it/s]

 68%|██████▊   | 12853/18769 [08:56<04:09, 23.73it/s]

 68%|██████▊   | 12856/18769 [08:56<04:09, 23.68it/s]

 69%|██████▊   | 12859/18769 [08:57<04:10, 23.57it/s]

 69%|██████▊   | 12862/18769 [08:57<04:12, 23.42it/s]

 69%|██████▊   | 12865/18769 [08:57<04:11, 23.44it/s]

 69%|██████▊   | 12868/18769 [08:57<04:12, 23.40it/s]

 69%|██████▊   | 12871/18769 [08:57<04:14, 23.19it/s]

 69%|██████▊   | 12874/18769 [08:57<04:13, 23.29it/s]

 69%|██████▊   | 12877/18769 [08:57<04:11, 23.46it/s]

 69%|██████▊   | 12880/18769 [08:57<04:09, 23.63it/s]

 69%|██████▊   | 12883/18769 [08:58<04:07, 23.82it/s]

 69%|██████▊   | 12886/18769 [08:58<04:05, 23.93it/s]

 69%|██████▊   | 12889/18769 [08:58<04:05, 23.98it/s]

 69%|██████▊   | 12892/18769 [08:58<04:04, 24.03it/s]

 69%|██████▊   | 12895/18769 [08:58<04:04, 24.01it/s]

 69%|██████▊   | 12898/18769 [08:58<04:03, 24.11it/s]

 69%|██████▊   | 12901/18769 [08:58<04:02, 24.16it/s]

 69%|██████▉   | 12904/18769 [08:58<04:02, 24.17it/s]

 69%|██████▉   | 12907/18769 [08:59<04:02, 24.19it/s]

 69%|██████▉   | 12910/18769 [08:59<04:02, 24.21it/s]

 69%|██████▉   | 12913/18769 [08:59<04:01, 24.20it/s]

 69%|██████▉   | 12916/18769 [08:59<04:03, 24.08it/s]

 69%|██████▉   | 12919/18769 [08:59<04:05, 23.80it/s]

 69%|██████▉   | 12922/18769 [08:59<04:04, 23.94it/s]

 69%|██████▉   | 12925/18769 [08:59<04:03, 24.03it/s]

 69%|██████▉   | 12928/18769 [08:59<04:03, 24.01it/s]

 69%|██████▉   | 12931/18769 [09:00<04:02, 24.09it/s]

 69%|██████▉   | 12934/18769 [09:00<04:03, 23.97it/s]

 69%|██████▉   | 12937/18769 [09:00<04:04, 23.82it/s]

 69%|██████▉   | 12940/18769 [09:00<04:05, 23.79it/s]

 69%|██████▉   | 12943/18769 [09:00<04:04, 23.80it/s]

 69%|██████▉   | 12946/18769 [09:00<04:04, 23.78it/s]

 69%|██████▉   | 12949/18769 [09:00<04:04, 23.80it/s]

 69%|██████▉   | 12952/18769 [09:00<04:04, 23.78it/s]

 69%|██████▉   | 12955/18769 [09:01<04:04, 23.77it/s]

 69%|██████▉   | 12958/18769 [09:01<04:04, 23.74it/s]

 69%|██████▉   | 12961/18769 [09:01<04:04, 23.72it/s]

 69%|██████▉   | 12964/18769 [09:01<04:05, 23.67it/s]

 69%|██████▉   | 12967/18769 [09:01<04:07, 23.45it/s]

 69%|██████▉   | 12970/18769 [09:01<04:07, 23.47it/s]

 69%|██████▉   | 12974/18769 [09:01<03:48, 25.41it/s]

 69%|██████▉   | 12977/18769 [09:01<03:53, 24.79it/s]

 69%|██████▉   | 12980/18769 [09:02<03:57, 24.42it/s]

 69%|██████▉   | 12983/18769 [09:02<03:59, 24.19it/s]

 69%|██████▉   | 12986/18769 [09:02<04:00, 24.00it/s]

 69%|██████▉   | 12989/18769 [09:02<04:01, 23.90it/s]

 69%|██████▉   | 12992/18769 [09:02<04:03, 23.75it/s]

 69%|██████▉   | 12995/18769 [09:02<04:03, 23.69it/s]

 69%|██████▉   | 12998/18769 [09:02<04:04, 23.64it/s]

 69%|██████▉   | 13001/18769 [09:02<04:05, 23.54it/s]

 69%|██████▉   | 13004/18769 [09:03<04:05, 23.53it/s]

 69%|██████▉   | 13007/18769 [09:03<04:04, 23.52it/s]

 69%|██████▉   | 13010/18769 [09:03<04:05, 23.51it/s]

 69%|██████▉   | 13013/18769 [09:03<04:05, 23.48it/s]

 69%|██████▉   | 13016/18769 [09:03<04:04, 23.50it/s]

 69%|██████▉   | 13019/18769 [09:03<04:02, 23.72it/s]

 69%|██████▉   | 13022/18769 [09:03<04:00, 23.85it/s]

 69%|██████▉   | 13025/18769 [09:03<03:59, 24.00it/s]

 69%|██████▉   | 13028/18769 [09:04<03:58, 24.09it/s]

 69%|██████▉   | 13031/18769 [09:04<03:58, 24.09it/s]

 69%|██████▉   | 13034/18769 [09:04<03:58, 24.08it/s]

 69%|██████▉   | 13037/18769 [09:04<03:57, 24.14it/s]

 69%|██████▉   | 13040/18769 [09:04<03:57, 24.13it/s]

 69%|██████▉   | 13043/18769 [09:04<03:56, 24.16it/s]

 70%|██████▉   | 13046/18769 [09:04<03:56, 24.22it/s]

 70%|██████▉   | 13049/18769 [09:04<03:56, 24.19it/s]

 70%|██████▉   | 13052/18769 [09:05<03:56, 24.21it/s]

 70%|██████▉   | 13055/18769 [09:05<03:56, 24.20it/s]

 70%|██████▉   | 13058/18769 [09:05<03:57, 24.06it/s]

 70%|██████▉   | 13061/18769 [09:05<03:56, 24.11it/s]

 70%|██████▉   | 13064/18769 [09:05<03:58, 23.94it/s]

 70%|██████▉   | 13067/18769 [09:05<03:57, 24.03it/s]

 70%|██████▉   | 13070/18769 [09:05<03:58, 23.93it/s]

 70%|██████▉   | 13073/18769 [09:05<03:58, 23.87it/s]

 70%|██████▉   | 13076/18769 [09:06<03:58, 23.83it/s]

 70%|██████▉   | 13079/18769 [09:06<03:59, 23.76it/s]

 70%|██████▉   | 13082/18769 [09:06<03:59, 23.76it/s]

 70%|██████▉   | 13085/18769 [09:06<03:59, 23.74it/s]

 70%|██████▉   | 13088/18769 [09:06<04:00, 23.64it/s]

 70%|██████▉   | 13091/18769 [09:06<03:59, 23.67it/s]

 70%|██████▉   | 13094/18769 [09:06<04:00, 23.63it/s]

 70%|██████▉   | 13097/18769 [09:06<04:00, 23.61it/s]

 70%|██████▉   | 13100/18769 [09:07<03:59, 23.64it/s]

 70%|██████▉   | 13103/18769 [09:07<03:59, 23.63it/s]

 70%|██████▉   | 13106/18769 [09:07<03:59, 23.63it/s]

 70%|██████▉   | 13109/18769 [09:07<04:02, 23.31it/s]

 70%|██████▉   | 13113/18769 [09:07<03:45, 25.05it/s]

 70%|██████▉   | 13116/18769 [09:07<03:50, 24.54it/s]

 70%|██████▉   | 13119/18769 [09:07<03:53, 24.24it/s]

 70%|██████▉   | 13122/18769 [09:08<03:55, 24.00it/s]

 70%|██████▉   | 13125/18769 [09:08<03:57, 23.78it/s]

 70%|██████▉   | 13128/18769 [09:08<03:58, 23.62it/s]

 70%|██████▉   | 13131/18769 [09:08<03:59, 23.54it/s]

 70%|██████▉   | 13134/18769 [09:08<03:59, 23.48it/s]

 70%|██████▉   | 13137/18769 [09:08<04:00, 23.42it/s]

 70%|███████   | 13140/18769 [09:08<04:00, 23.42it/s]

 70%|███████   | 13143/18769 [09:08<04:00, 23.44it/s]

 70%|███████   | 13146/18769 [09:09<04:00, 23.41it/s]

 70%|███████   | 13149/18769 [09:09<04:01, 23.28it/s]

 70%|███████   | 13152/18769 [09:09<03:59, 23.41it/s]

 70%|███████   | 13155/18769 [09:09<04:02, 23.12it/s]

 70%|███████   | 13158/18769 [09:09<04:03, 23.08it/s]

 70%|███████   | 13161/18769 [09:09<04:00, 23.35it/s]

 70%|███████   | 13164/18769 [09:09<03:57, 23.59it/s]

 70%|███████   | 13167/18769 [09:09<03:56, 23.66it/s]

 70%|███████   | 13170/18769 [09:10<03:56, 23.70it/s]

 70%|███████   | 13173/18769 [09:10<03:56, 23.70it/s]

 70%|███████   | 13176/18769 [09:10<03:56, 23.69it/s]

 70%|███████   | 13179/18769 [09:10<03:55, 23.77it/s]

 70%|███████   | 13182/18769 [09:10<03:54, 23.85it/s]

 70%|███████   | 13185/18769 [09:10<03:53, 23.91it/s]

 70%|███████   | 13188/18769 [09:10<03:52, 23.96it/s]

 70%|███████   | 13191/18769 [09:10<03:52, 23.98it/s]

 70%|███████   | 13194/18769 [09:11<03:52, 23.99it/s]

 70%|███████   | 13197/18769 [09:11<03:54, 23.80it/s]

 70%|███████   | 13200/18769 [09:11<03:54, 23.78it/s]

 70%|███████   | 13203/18769 [09:11<03:55, 23.68it/s]

 70%|███████   | 13206/18769 [09:11<03:57, 23.39it/s]

 70%|███████   | 13209/18769 [09:11<03:58, 23.34it/s]

 70%|███████   | 13212/18769 [09:11<03:57, 23.40it/s]

 70%|███████   | 13215/18769 [09:11<03:57, 23.41it/s]

 70%|███████   | 13218/18769 [09:12<03:58, 23.28it/s]

 70%|███████   | 13221/18769 [09:12<03:58, 23.26it/s]

 70%|███████   | 13224/18769 [09:12<03:57, 23.38it/s]

 70%|███████   | 13227/18769 [09:12<03:56, 23.43it/s]

 70%|███████   | 13230/18769 [09:12<03:56, 23.45it/s]

 71%|███████   | 13233/18769 [09:12<03:56, 23.39it/s]

 71%|███████   | 13236/18769 [09:12<03:58, 23.23it/s]

 71%|███████   | 13239/18769 [09:12<03:58, 23.18it/s]

 71%|███████   | 13242/18769 [09:13<03:58, 23.21it/s]

 71%|███████   | 13245/18769 [09:13<03:58, 23.13it/s]

 71%|███████   | 13248/18769 [09:13<03:58, 23.13it/s]

 71%|███████   | 13252/18769 [09:13<03:40, 25.04it/s]

 71%|███████   | 13255/18769 [09:13<03:47, 24.24it/s]

 71%|███████   | 13258/18769 [09:13<03:49, 23.96it/s]

 71%|███████   | 13261/18769 [09:13<03:52, 23.72it/s]

 71%|███████   | 13264/18769 [09:14<03:54, 23.51it/s]

 71%|███████   | 13267/18769 [09:14<03:54, 23.51it/s]

 71%|███████   | 13270/18769 [09:14<03:53, 23.51it/s]

 71%|███████   | 13273/18769 [09:14<03:53, 23.51it/s]

 71%|███████   | 13276/18769 [09:14<03:53, 23.51it/s]

 71%|███████   | 13279/18769 [09:14<03:53, 23.47it/s]

 71%|███████   | 13282/18769 [09:14<03:53, 23.48it/s]

 71%|███████   | 13285/18769 [09:14<03:53, 23.45it/s]

 71%|███████   | 13288/18769 [09:15<03:52, 23.53it/s]

 71%|███████   | 13291/18769 [09:15<03:51, 23.63it/s]

 71%|███████   | 13294/18769 [09:15<03:50, 23.76it/s]

 71%|███████   | 13297/18769 [09:15<03:49, 23.88it/s]

 71%|███████   | 13300/18769 [09:15<03:48, 23.93it/s]

 71%|███████   | 13303/18769 [09:15<03:49, 23.77it/s]

 71%|███████   | 13306/18769 [09:15<03:48, 23.91it/s]

 71%|███████   | 13309/18769 [09:15<03:47, 23.98it/s]

 71%|███████   | 13312/18769 [09:16<03:47, 24.03it/s]

 71%|███████   | 13315/18769 [09:16<03:46, 24.04it/s]

 71%|███████   | 13318/18769 [09:16<03:46, 24.04it/s]

 71%|███████   | 13321/18769 [09:16<03:46, 24.06it/s]

 71%|███████   | 13324/18769 [09:16<03:46, 24.08it/s]

 71%|███████   | 13327/18769 [09:16<03:46, 24.08it/s]

 71%|███████   | 13330/18769 [09:16<03:45, 24.10it/s]

 71%|███████   | 13333/18769 [09:16<03:45, 24.08it/s]

 71%|███████   | 13336/18769 [09:17<03:45, 24.06it/s]

 71%|███████   | 13339/18769 [09:17<03:45, 24.07it/s]

 71%|███████   | 13342/18769 [09:17<03:45, 24.10it/s]

 71%|███████   | 13345/18769 [09:17<03:46, 23.99it/s]

 71%|███████   | 13348/18769 [09:17<03:46, 23.91it/s]

 71%|███████   | 13351/18769 [09:17<03:47, 23.85it/s]

 71%|███████   | 13354/18769 [09:17<03:47, 23.81it/s]

 71%|███████   | 13357/18769 [09:17<03:47, 23.81it/s]

 71%|███████   | 13360/18769 [09:18<03:47, 23.83it/s]

 71%|███████   | 13363/18769 [09:18<03:46, 23.82it/s]

 71%|███████   | 13366/18769 [09:18<03:47, 23.78it/s]

 71%|███████   | 13369/18769 [09:18<03:47, 23.77it/s]

 71%|███████   | 13372/18769 [09:18<03:47, 23.74it/s]

 71%|███████▏  | 13375/18769 [09:18<03:47, 23.71it/s]

 71%|███████▏  | 13378/18769 [09:18<03:47, 23.70it/s]

 71%|███████▏  | 13381/18769 [09:18<03:47, 23.69it/s]

 71%|███████▏  | 13384/18769 [09:19<03:47, 23.66it/s]

 71%|███████▏  | 13388/18769 [09:19<03:30, 25.55it/s]

 71%|███████▏  | 13391/18769 [09:19<03:36, 24.89it/s]

 71%|███████▏  | 13394/18769 [09:19<03:39, 24.44it/s]

 71%|███████▏  | 13397/18769 [09:19<03:42, 24.14it/s]

 71%|███████▏  | 13400/18769 [09:19<03:45, 23.76it/s]

 71%|███████▏  | 13403/18769 [09:19<03:46, 23.72it/s]

 71%|███████▏  | 13406/18769 [09:19<03:46, 23.67it/s]

 71%|███████▏  | 13409/18769 [09:20<03:46, 23.62it/s]

 71%|███████▏  | 13412/18769 [09:20<03:47, 23.56it/s]

 71%|███████▏  | 13415/18769 [09:20<03:47, 23.52it/s]

 71%|███████▏  | 13418/18769 [09:20<03:47, 23.55it/s]

 72%|███████▏  | 13421/18769 [09:20<03:47, 23.52it/s]

 72%|███████▏  | 13424/18769 [09:20<03:47, 23.49it/s]

 72%|███████▏  | 13427/18769 [09:20<03:45, 23.66it/s]

 72%|███████▏  | 13430/18769 [09:20<03:44, 23.73it/s]

 72%|███████▏  | 13433/18769 [09:21<03:44, 23.81it/s]

 72%|███████▏  | 13436/18769 [09:21<03:43, 23.91it/s]

 72%|███████▏  | 13439/18769 [09:21<03:42, 23.98it/s]

 72%|███████▏  | 13442/18769 [09:21<03:41, 24.00it/s]

 72%|███████▏  | 13445/18769 [09:21<03:41, 24.04it/s]

 72%|███████▏  | 13448/18769 [09:21<03:42, 23.89it/s]

 72%|███████▏  | 13451/18769 [09:21<03:41, 23.96it/s]

 72%|███████▏  | 13454/18769 [09:21<03:41, 24.02it/s]

 72%|███████▏  | 13457/18769 [09:22<03:40, 24.05it/s]

 72%|███████▏  | 13460/18769 [09:22<03:40, 24.06it/s]

 72%|███████▏  | 13463/18769 [09:22<03:40, 24.10it/s]

 72%|███████▏  | 13466/18769 [09:22<03:40, 24.10it/s]

 72%|███████▏  | 13469/18769 [09:22<03:40, 24.09it/s]

 72%|███████▏  | 13472/18769 [09:22<03:39, 24.10it/s]

 72%|███████▏  | 13475/18769 [09:22<03:39, 24.10it/s]

 72%|███████▏  | 13478/18769 [09:22<03:39, 24.06it/s]

 72%|███████▏  | 13481/18769 [09:23<03:40, 24.02it/s]

 72%|███████▏  | 13484/18769 [09:23<03:41, 23.91it/s]

 72%|███████▏  | 13487/18769 [09:23<03:41, 23.83it/s]

 72%|███████▏  | 13490/18769 [09:23<03:41, 23.79it/s]

 72%|███████▏  | 13493/18769 [09:23<03:42, 23.75it/s]

 72%|███████▏  | 13496/18769 [09:23<03:44, 23.52it/s]

 72%|███████▏  | 13499/18769 [09:23<03:43, 23.56it/s]

 72%|███████▏  | 13502/18769 [09:23<03:43, 23.57it/s]

 72%|███████▏  | 13505/18769 [09:24<03:42, 23.61it/s]

 72%|███████▏  | 13508/18769 [09:24<03:43, 23.55it/s]

 72%|███████▏  | 13511/18769 [09:24<03:43, 23.56it/s]

 72%|███████▏  | 13514/18769 [09:24<03:43, 23.55it/s]

 72%|███████▏  | 13517/18769 [09:24<03:43, 23.52it/s]

 72%|███████▏  | 13520/18769 [09:24<03:43, 23.50it/s]

 72%|███████▏  | 13523/18769 [09:24<03:43, 23.50it/s]

 72%|███████▏  | 13527/18769 [09:25<03:26, 25.40it/s]

 72%|███████▏  | 13530/18769 [09:25<03:31, 24.79it/s]

 72%|███████▏  | 13533/18769 [09:25<03:34, 24.36it/s]

 72%|███████▏  | 13536/18769 [09:25<03:37, 24.02it/s]

 72%|███████▏  | 13539/18769 [09:25<03:39, 23.87it/s]

 72%|███████▏  | 13542/18769 [09:25<03:39, 23.78it/s]

 72%|███████▏  | 13545/18769 [09:25<03:40, 23.68it/s]

 72%|███████▏  | 13548/18769 [09:25<03:40, 23.63it/s]

 72%|███████▏  | 13551/18769 [09:26<03:41, 23.60it/s]

 72%|███████▏  | 13554/18769 [09:26<03:42, 23.47it/s]

 72%|███████▏  | 13557/18769 [09:26<03:42, 23.46it/s]

 72%|███████▏  | 13560/18769 [09:26<03:41, 23.48it/s]

 72%|███████▏  | 13563/18769 [09:26<03:40, 23.66it/s]

 72%|███████▏  | 13566/18769 [09:26<03:38, 23.77it/s]

 72%|███████▏  | 13569/18769 [09:26<03:37, 23.91it/s]

 72%|███████▏  | 13572/18769 [09:26<03:36, 23.98it/s]

 72%|███████▏  | 13575/18769 [09:27<03:35, 24.05it/s]

 72%|███████▏  | 13578/18769 [09:27<03:35, 24.09it/s]

 72%|███████▏  | 13581/18769 [09:27<03:34, 24.14it/s]

 72%|███████▏  | 13584/18769 [09:27<03:34, 24.15it/s]

 72%|███████▏  | 13587/18769 [09:27<03:34, 24.18it/s]

 72%|███████▏  | 13590/18769 [09:27<03:34, 24.17it/s]

 72%|███████▏  | 13593/18769 [09:27<03:34, 24.13it/s]

 72%|███████▏  | 13596/18769 [09:27<03:34, 24.14it/s]

 72%|███████▏  | 13599/18769 [09:28<03:33, 24.16it/s]

 72%|███████▏  | 13602/18769 [09:28<03:34, 24.13it/s]

 72%|███████▏  | 13605/18769 [09:28<03:34, 24.10it/s]

 73%|███████▎  | 13608/18769 [09:28<03:34, 24.10it/s]

 73%|███████▎  | 13611/18769 [09:28<03:33, 24.12it/s]

 73%|███████▎  | 13614/18769 [09:28<03:33, 24.13it/s]

 73%|███████▎  | 13617/18769 [09:28<03:33, 24.15it/s]

 73%|███████▎  | 13620/18769 [09:28<03:34, 23.98it/s]

 73%|███████▎  | 13623/18769 [09:29<03:35, 23.92it/s]

 73%|███████▎  | 13626/18769 [09:29<03:35, 23.88it/s]

 73%|███████▎  | 13629/18769 [09:29<03:35, 23.85it/s]

 73%|███████▎  | 13632/18769 [09:29<03:35, 23.85it/s]

 73%|███████▎  | 13635/18769 [09:29<03:35, 23.85it/s]

 73%|███████▎  | 13638/18769 [09:29<03:35, 23.83it/s]

 73%|███████▎  | 13641/18769 [09:29<03:36, 23.64it/s]

 73%|███████▎  | 13644/18769 [09:29<03:36, 23.66it/s]

 73%|███████▎  | 13647/18769 [09:30<03:36, 23.67it/s]

 73%|███████▎  | 13650/18769 [09:30<03:36, 23.65it/s]

 73%|███████▎  | 13653/18769 [09:30<03:36, 23.64it/s]

 73%|███████▎  | 13656/18769 [09:30<03:36, 23.65it/s]

 73%|███████▎  | 13659/18769 [09:30<03:36, 23.64it/s]

 73%|███████▎  | 13662/18769 [09:30<03:36, 23.56it/s]

 73%|███████▎  | 13666/18769 [09:30<03:20, 25.50it/s]

 73%|███████▎  | 13669/18769 [09:30<03:25, 24.88it/s]

 73%|███████▎  | 13672/18769 [09:31<03:28, 24.44it/s]

 73%|███████▎  | 13675/18769 [09:31<03:31, 24.14it/s]

 73%|███████▎  | 13678/18769 [09:31<03:32, 23.96it/s]

 73%|███████▎  | 13681/18769 [09:31<03:33, 23.81it/s]

 73%|███████▎  | 13684/18769 [09:31<03:34, 23.72it/s]

 73%|███████▎  | 13687/18769 [09:31<03:34, 23.65it/s]

 73%|███████▎  | 13690/18769 [09:31<03:37, 23.39it/s]

 73%|███████▎  | 13693/18769 [09:31<03:36, 23.42it/s]

 73%|███████▎  | 13696/18769 [09:32<03:36, 23.41it/s]

 73%|███████▎  | 13699/18769 [09:32<03:35, 23.51it/s]

 73%|███████▎  | 13702/18769 [09:32<03:34, 23.67it/s]

 73%|███████▎  | 13705/18769 [09:32<03:32, 23.83it/s]

 73%|███████▎  | 13708/18769 [09:32<03:31, 23.93it/s]

 73%|███████▎  | 13711/18769 [09:32<03:30, 23.99it/s]

 73%|███████▎  | 13714/18769 [09:32<03:30, 24.05it/s]

 73%|███████▎  | 13717/18769 [09:32<03:30, 24.02it/s]

 73%|███████▎  | 13720/18769 [09:33<03:29, 24.11it/s]

 73%|███████▎  | 13723/18769 [09:33<03:28, 24.15it/s]

 73%|███████▎  | 13726/18769 [09:33<03:28, 24.20it/s]

 73%|███████▎  | 13729/18769 [09:33<03:28, 24.22it/s]

 73%|███████▎  | 13732/18769 [09:33<03:27, 24.22it/s]

 73%|███████▎  | 13735/18769 [09:33<03:27, 24.23it/s]

 73%|███████▎  | 13738/18769 [09:33<03:27, 24.20it/s]

 73%|███████▎  | 13741/18769 [09:33<03:27, 24.18it/s]

 73%|███████▎  | 13744/18769 [09:34<03:27, 24.19it/s]

 73%|███████▎  | 13747/18769 [09:34<03:27, 24.22it/s]

 73%|███████▎  | 13750/18769 [09:34<03:27, 24.21it/s]

 73%|███████▎  | 13753/18769 [09:34<03:27, 24.18it/s]

 73%|███████▎  | 13756/18769 [09:34<03:28, 24.07it/s]

 73%|███████▎  | 13759/18769 [09:34<03:29, 23.97it/s]

 73%|███████▎  | 13762/18769 [09:34<03:31, 23.69it/s]

 73%|███████▎  | 13765/18769 [09:34<03:30, 23.76it/s]

 73%|███████▎  | 13768/18769 [09:35<03:30, 23.78it/s]

 73%|███████▎  | 13771/18769 [09:35<03:29, 23.81it/s]

 73%|███████▎  | 13774/18769 [09:35<03:29, 23.79it/s]

 73%|███████▎  | 13777/18769 [09:35<03:30, 23.73it/s]

 73%|███████▎  | 13780/18769 [09:35<03:30, 23.65it/s]

 73%|███████▎  | 13783/18769 [09:35<03:30, 23.63it/s]

 73%|███████▎  | 13786/18769 [09:35<03:30, 23.62it/s]

 73%|███████▎  | 13789/18769 [09:35<03:30, 23.63it/s]

 73%|███████▎  | 13792/18769 [09:36<03:30, 23.61it/s]

 73%|███████▎  | 13795/18769 [09:36<03:31, 23.53it/s]

 74%|███████▎  | 13798/18769 [09:36<03:31, 23.49it/s]

 74%|███████▎  | 13802/18769 [09:36<03:15, 25.37it/s]

 74%|███████▎  | 13805/18769 [09:36<03:20, 24.74it/s]

 74%|███████▎  | 13808/18769 [09:36<03:23, 24.35it/s]

 74%|███████▎  | 13811/18769 [09:36<03:28, 23.79it/s]

 74%|███████▎  | 13814/18769 [09:36<03:29, 23.70it/s]

 74%|███████▎  | 13817/18769 [09:37<03:29, 23.68it/s]

 74%|███████▎  | 13820/18769 [09:37<03:29, 23.60it/s]

 74%|███████▎  | 13823/18769 [09:37<03:29, 23.57it/s]

 74%|███████▎  | 13826/18769 [09:37<03:29, 23.54it/s]

 74%|███████▎  | 13829/18769 [09:37<03:29, 23.53it/s]

 74%|███████▎  | 13832/18769 [09:37<03:29, 23.54it/s]

 74%|███████▎  | 13835/18769 [09:37<03:29, 23.52it/s]

 74%|███████▎  | 13838/18769 [09:38<03:28, 23.70it/s]

 74%|███████▎  | 13841/18769 [09:38<03:26, 23.83it/s]

 74%|███████▍  | 13844/18769 [09:38<03:26, 23.88it/s]

 74%|███████▍  | 13847/18769 [09:38<03:25, 23.98it/s]

 74%|███████▍  | 13850/18769 [09:38<03:24, 24.00it/s]

 74%|███████▍  | 13853/18769 [09:38<03:24, 24.06it/s]

 74%|███████▍  | 13856/18769 [09:38<03:23, 24.09it/s]

 74%|███████▍  | 13859/18769 [09:38<03:25, 23.89it/s]

 74%|███████▍  | 13862/18769 [09:39<03:24, 23.95it/s]

 74%|███████▍  | 13865/18769 [09:39<03:24, 23.98it/s]

 74%|███████▍  | 13868/18769 [09:39<03:24, 24.01it/s]

 74%|███████▍  | 13871/18769 [09:39<03:24, 23.99it/s]

 74%|███████▍  | 13874/18769 [09:39<03:23, 24.00it/s]

 74%|███████▍  | 13877/18769 [09:39<03:24, 23.98it/s]

 74%|███████▍  | 13880/18769 [09:39<03:23, 24.01it/s]

 74%|███████▍  | 13883/18769 [09:39<03:23, 24.02it/s]

 74%|███████▍  | 13886/18769 [09:40<03:22, 24.06it/s]

 74%|███████▍  | 13889/18769 [09:40<03:22, 24.07it/s]

 74%|███████▍  | 13892/18769 [09:40<03:22, 24.04it/s]

 74%|███████▍  | 13895/18769 [09:40<03:23, 23.94it/s]

 74%|███████▍  | 13898/18769 [09:40<03:23, 23.92it/s]

 74%|███████▍  | 13901/18769 [09:40<03:23, 23.88it/s]

 74%|███████▍  | 13904/18769 [09:40<03:24, 23.83it/s]

 74%|███████▍  | 13907/18769 [09:40<03:26, 23.59it/s]

 74%|███████▍  | 13910/18769 [09:41<03:25, 23.60it/s]

 74%|███████▍  | 13913/18769 [09:41<03:25, 23.63it/s]

 74%|███████▍  | 13916/18769 [09:41<03:25, 23.65it/s]

 74%|███████▍  | 13919/18769 [09:41<03:25, 23.64it/s]

 74%|███████▍  | 13922/18769 [09:41<03:25, 23.64it/s]

 74%|███████▍  | 13925/18769 [09:41<03:24, 23.63it/s]

 74%|███████▍  | 13928/18769 [09:41<03:24, 23.64it/s]

 74%|███████▍  | 13931/18769 [09:41<03:24, 23.61it/s]

 74%|███████▍  | 13934/18769 [09:42<03:24, 23.59it/s]

 74%|███████▍  | 13937/18769 [09:42<03:25, 23.56it/s]

 74%|███████▍  | 13941/18769 [09:42<03:09, 25.49it/s]

 74%|███████▍  | 13944/18769 [09:42<03:14, 24.85it/s]

 74%|███████▍  | 13947/18769 [09:42<03:17, 24.42it/s]

 74%|███████▍  | 13950/18769 [09:42<03:19, 24.15it/s]

 74%|███████▍  | 13953/18769 [09:42<03:21, 23.94it/s]

 74%|███████▍  | 13956/18769 [09:42<03:24, 23.49it/s]

 74%|███████▍  | 13959/18769 [09:43<03:25, 23.45it/s]

 74%|███████▍  | 13962/18769 [09:43<03:24, 23.48it/s]

 74%|███████▍  | 13965/18769 [09:43<03:40, 21.77it/s]

 74%|███████▍  | 13968/18769 [09:43<03:36, 22.21it/s]

 74%|███████▍  | 13971/18769 [09:43<03:32, 22.58it/s]

 74%|███████▍  | 13974/18769 [09:43<03:28, 22.98it/s]

 74%|███████▍  | 13977/18769 [09:43<03:25, 23.33it/s]

 74%|███████▍  | 13980/18769 [09:43<03:23, 23.56it/s]

 75%|███████▍  | 13983/18769 [09:44<03:21, 23.77it/s]

 75%|███████▍  | 13986/18769 [09:44<03:20, 23.87it/s]

 75%|███████▍  | 13989/18769 [09:44<03:19, 23.97it/s]

 75%|███████▍  | 13992/18769 [09:44<03:18, 24.02it/s]

 75%|███████▍  | 13995/18769 [09:44<03:18, 24.10it/s]

 75%|███████▍  | 13998/18769 [09:44<03:17, 24.20it/s]

 75%|███████▍  | 14001/18769 [09:44<03:19, 23.86it/s]

 75%|███████▍  | 14004/18769 [09:44<03:19, 23.88it/s]

 75%|███████▍  | 14007/18769 [09:45<03:18, 23.93it/s]

 75%|███████▍  | 14010/18769 [09:45<03:19, 23.91it/s]

 75%|███████▍  | 14013/18769 [09:45<03:18, 23.96it/s]

 75%|███████▍  | 14016/18769 [09:45<03:17, 24.02it/s]

 75%|███████▍  | 14019/18769 [09:45<03:17, 24.09it/s]

 75%|███████▍  | 14022/18769 [09:45<03:16, 24.15it/s]

 75%|███████▍  | 14025/18769 [09:45<03:16, 24.15it/s]

 75%|███████▍  | 14028/18769 [09:45<03:16, 24.12it/s]

 75%|███████▍  | 14031/18769 [09:46<03:17, 23.99it/s]

 75%|███████▍  | 14034/18769 [09:46<03:17, 23.95it/s]

 75%|███████▍  | 14037/18769 [09:46<03:18, 23.90it/s]

 75%|███████▍  | 14040/18769 [09:46<03:18, 23.88it/s]

 75%|███████▍  | 14043/18769 [09:46<03:18, 23.87it/s]

 75%|███████▍  | 14046/18769 [09:46<03:18, 23.83it/s]

 75%|███████▍  | 14049/18769 [09:46<03:18, 23.80it/s]

 75%|███████▍  | 14052/18769 [09:46<03:19, 23.62it/s]

 75%|███████▍  | 14055/18769 [09:47<03:19, 23.59it/s]

 75%|███████▍  | 14058/18769 [09:47<03:19, 23.60it/s]

 75%|███████▍  | 14061/18769 [09:47<03:19, 23.57it/s]

 75%|███████▍  | 14064/18769 [09:47<03:20, 23.46it/s]

 75%|███████▍  | 14067/18769 [09:47<03:20, 23.49it/s]

 75%|███████▍  | 14070/18769 [09:47<03:20, 23.49it/s]

 75%|███████▍  | 14073/18769 [09:47<03:19, 23.50it/s]

 75%|███████▍  | 14076/18769 [09:48<03:19, 23.51it/s]

 75%|███████▌  | 14080/18769 [09:48<03:04, 25.38it/s]

 75%|███████▌  | 14083/18769 [09:48<03:09, 24.67it/s]

 75%|███████▌  | 14086/18769 [09:48<03:12, 24.30it/s]

 75%|███████▌  | 14089/18769 [09:48<03:14, 24.05it/s]

 75%|███████▌  | 14092/18769 [09:48<03:17, 23.64it/s]

 75%|███████▌  | 14095/18769 [09:48<03:18, 23.60it/s]

 75%|███████▌  | 14098/18769 [09:48<03:19, 23.36it/s]

 75%|███████▌  | 14101/18769 [09:49<03:19, 23.41it/s]

 75%|███████▌  | 14104/18769 [09:49<03:18, 23.48it/s]

 75%|███████▌  | 14107/18769 [09:49<03:18, 23.50it/s]

 75%|███████▌  | 14110/18769 [09:49<03:17, 23.63it/s]

 75%|███████▌  | 14113/18769 [09:49<03:15, 23.79it/s]

 75%|███████▌  | 14116/18769 [09:49<03:14, 23.92it/s]

 75%|███████▌  | 14119/18769 [09:49<03:13, 24.02it/s]

 75%|███████▌  | 14122/18769 [09:49<03:13, 24.05it/s]

 75%|███████▌  | 14125/18769 [09:50<03:12, 24.09it/s]

 75%|███████▌  | 14128/18769 [09:50<03:12, 24.10it/s]

 75%|███████▌  | 14131/18769 [09:50<03:11, 24.17it/s]

 75%|███████▌  | 14134/18769 [09:50<03:11, 24.15it/s]

 75%|███████▌  | 14137/18769 [09:50<03:11, 24.16it/s]

 75%|███████▌  | 14140/18769 [09:50<03:11, 24.14it/s]

 75%|███████▌  | 14143/18769 [09:50<03:11, 24.15it/s]

 75%|███████▌  | 14146/18769 [09:50<03:12, 24.03it/s]

 75%|███████▌  | 14149/18769 [09:51<03:12, 23.95it/s]

 75%|███████▌  | 14152/18769 [09:51<03:12, 23.95it/s]

 75%|███████▌  | 14155/18769 [09:51<03:12, 24.02it/s]

 75%|███████▌  | 14158/18769 [09:51<03:11, 24.04it/s]

 75%|███████▌  | 14161/18769 [09:51<03:11, 24.06it/s]

 75%|███████▌  | 14164/18769 [09:51<03:11, 24.11it/s]

 75%|███████▌  | 14167/18769 [09:51<03:11, 24.06it/s]

 75%|███████▌  | 14170/18769 [09:51<03:11, 23.98it/s]

 76%|███████▌  | 14173/18769 [09:52<03:12, 23.89it/s]

 76%|███████▌  | 14176/18769 [09:52<03:13, 23.78it/s]

 76%|███████▌  | 14179/18769 [09:52<03:13, 23.75it/s]

 76%|███████▌  | 14182/18769 [09:52<03:13, 23.75it/s]

 76%|███████▌  | 14185/18769 [09:52<03:13, 23.71it/s]

 76%|███████▌  | 14188/18769 [09:52<03:13, 23.71it/s]

 76%|███████▌  | 14191/18769 [09:52<03:13, 23.64it/s]

 76%|███████▌  | 14194/18769 [09:52<03:13, 23.60it/s]

 76%|███████▌  | 14197/18769 [09:53<03:14, 23.48it/s]

 76%|███████▌  | 14200/18769 [09:53<03:14, 23.47it/s]

 76%|███████▌  | 14203/18769 [09:53<03:14, 23.49it/s]

 76%|███████▌  | 14206/18769 [09:53<03:14, 23.47it/s]

 76%|███████▌  | 14209/18769 [09:53<03:14, 23.47it/s]

 76%|███████▌  | 14212/18769 [09:53<03:14, 23.47it/s]

 76%|███████▌  | 14216/18769 [09:53<02:59, 25.37it/s]

 76%|███████▌  | 14219/18769 [09:53<03:04, 24.69it/s]

 76%|███████▌  | 14222/18769 [09:54<03:07, 24.25it/s]

 76%|███████▌  | 14225/18769 [09:54<03:09, 23.96it/s]

 76%|███████▌  | 14228/18769 [09:54<03:10, 23.78it/s]

 76%|███████▌  | 14231/18769 [09:54<03:11, 23.68it/s]

 76%|███████▌  | 14234/18769 [09:54<03:12, 23.61it/s]

 76%|███████▌  | 14237/18769 [09:54<03:12, 23.57it/s]

 76%|███████▌  | 14240/18769 [09:54<03:12, 23.53it/s]

 76%|███████▌  | 14243/18769 [09:54<03:14, 23.31it/s]

 76%|███████▌  | 14246/18769 [09:55<03:14, 23.28it/s]

 76%|███████▌  | 14249/18769 [09:55<03:12, 23.50it/s]

 76%|███████▌  | 14252/18769 [09:55<03:10, 23.66it/s]

 76%|███████▌  | 14255/18769 [09:55<03:09, 23.79it/s]

 76%|███████▌  | 14258/18769 [09:55<03:08, 23.88it/s]

 76%|███████▌  | 14261/18769 [09:55<03:08, 23.94it/s]

 76%|███████▌  | 14264/18769 [09:55<03:07, 24.01it/s]

 76%|███████▌  | 14267/18769 [09:55<03:07, 23.99it/s]

 76%|███████▌  | 14270/18769 [09:56<03:07, 24.02it/s]

 76%|███████▌  | 14273/18769 [09:56<03:07, 24.01it/s]

 76%|███████▌  | 14276/18769 [09:56<03:07, 24.01it/s]

 76%|███████▌  | 14279/18769 [09:56<03:06, 24.05it/s]

 76%|███████▌  | 14282/18769 [09:56<03:06, 24.04it/s]

 76%|███████▌  | 14285/18769 [09:56<03:06, 24.01it/s]

 76%|███████▌  | 14288/18769 [09:56<03:06, 24.02it/s]

 76%|███████▌  | 14291/18769 [09:56<03:06, 24.00it/s]

 76%|███████▌  | 14294/18769 [09:57<03:06, 24.02it/s]

 76%|███████▌  | 14297/18769 [09:57<03:05, 24.06it/s]

 76%|███████▌  | 14300/18769 [09:57<03:05, 24.11it/s]

 76%|███████▌  | 14303/18769 [09:57<03:05, 24.10it/s]

 76%|███████▌  | 14306/18769 [09:57<03:05, 24.01it/s]

 76%|███████▌  | 14309/18769 [09:57<03:06, 23.94it/s]

 76%|███████▋  | 14312/18769 [09:57<03:06, 23.89it/s]

 76%|███████▋  | 14315/18769 [09:57<03:07, 23.80it/s]

 76%|███████▋  | 14318/18769 [09:58<03:07, 23.75it/s]

 76%|███████▋  | 14321/18769 [09:58<03:07, 23.73it/s]

 76%|███████▋  | 14324/18769 [09:58<03:07, 23.76it/s]

 76%|███████▋  | 14327/18769 [09:58<03:07, 23.72it/s]

 76%|███████▋  | 14330/18769 [09:58<03:07, 23.64it/s]

 76%|███████▋  | 14333/18769 [09:58<03:07, 23.65it/s]

 76%|███████▋  | 14336/18769 [09:58<03:07, 23.63it/s]

 76%|███████▋  | 14339/18769 [09:59<03:07, 23.61it/s]

 76%|███████▋  | 14342/18769 [09:59<03:07, 23.57it/s]

 76%|███████▋  | 14345/18769 [09:59<03:08, 23.52it/s]

 76%|███████▋  | 14348/18769 [09:59<03:08, 23.49it/s]

 76%|███████▋  | 14351/18769 [09:59<03:08, 23.48it/s]

 76%|███████▋  | 14355/18769 [09:59<02:54, 25.36it/s]

 76%|███████▋  | 14358/18769 [09:59<02:57, 24.80it/s]

 77%|███████▋  | 14361/18769 [09:59<03:00, 24.40it/s]

 77%|███████▋  | 14364/18769 [10:00<03:03, 24.07it/s]

 77%|███████▋  | 14367/18769 [10:00<03:04, 23.82it/s]

 77%|███████▋  | 14370/18769 [10:00<03:05, 23.67it/s]

 77%|███████▋  | 14373/18769 [10:00<03:06, 23.57it/s]

 77%|███████▋  | 14376/18769 [10:00<03:06, 23.55it/s]

 77%|███████▋  | 14379/18769 [10:00<03:06, 23.49it/s]

 77%|███████▋  | 14382/18769 [10:00<03:06, 23.50it/s]

 77%|███████▋  | 14385/18769 [10:00<03:05, 23.64it/s]

 77%|███████▋  | 14388/18769 [10:01<03:04, 23.76it/s]

 77%|███████▋  | 14391/18769 [10:01<03:03, 23.83it/s]

 77%|███████▋  | 14394/18769 [10:01<03:02, 23.93it/s]

 77%|███████▋  | 14397/18769 [10:01<03:02, 24.01it/s]

 77%|███████▋  | 14400/18769 [10:01<03:01, 24.06it/s]

 77%|███████▋  | 14403/18769 [10:01<03:01, 24.11it/s]

 77%|███████▋  | 14406/18769 [10:01<03:00, 24.12it/s]

 77%|███████▋  | 14409/18769 [10:01<03:00, 24.12it/s]

 77%|███████▋  | 14412/18769 [10:02<03:01, 24.04it/s]

 77%|███████▋  | 14415/18769 [10:02<03:00, 24.08it/s]

 77%|███████▋  | 14418/18769 [10:02<03:00, 24.11it/s]

 77%|███████▋  | 14421/18769 [10:02<03:00, 24.10it/s]

 77%|███████▋  | 14424/18769 [10:02<03:00, 24.13it/s]

 77%|███████▋  | 14427/18769 [10:02<02:59, 24.13it/s]

 77%|███████▋  | 14430/18769 [10:02<03:00, 24.09it/s]

 77%|███████▋  | 14433/18769 [10:02<02:59, 24.13it/s]

 77%|███████▋  | 14436/18769 [10:03<03:00, 23.98it/s]

 77%|███████▋  | 14439/18769 [10:03<03:00, 24.01it/s]

 77%|███████▋  | 14442/18769 [10:03<03:00, 23.92it/s]

 77%|███████▋  | 14445/18769 [10:03<03:01, 23.86it/s]

 77%|███████▋  | 14448/18769 [10:03<03:01, 23.80it/s]

 77%|███████▋  | 14451/18769 [10:03<03:01, 23.80it/s]

 77%|███████▋  | 14454/18769 [10:03<03:01, 23.83it/s]

 77%|███████▋  | 14457/18769 [10:03<03:01, 23.82it/s]

 77%|███████▋  | 14460/18769 [10:04<03:02, 23.58it/s]

 77%|███████▋  | 14463/18769 [10:04<03:02, 23.63it/s]

 77%|███████▋  | 14466/18769 [10:04<03:02, 23.61it/s]

 77%|███████▋  | 14469/18769 [10:04<03:02, 23.58it/s]

 77%|███████▋  | 14472/18769 [10:04<03:02, 23.58it/s]

 77%|███████▋  | 14475/18769 [10:04<03:01, 23.61it/s]

 77%|███████▋  | 14478/18769 [10:04<03:01, 23.64it/s]

 77%|███████▋  | 14481/18769 [10:04<03:01, 23.59it/s]

 77%|███████▋  | 14484/18769 [10:05<03:01, 23.58it/s]

 77%|███████▋  | 14487/18769 [10:05<03:02, 23.49it/s]

 77%|███████▋  | 14490/18769 [10:05<03:02, 23.47it/s]

 77%|███████▋  | 14494/18769 [10:05<02:48, 25.38it/s]

 77%|███████▋  | 14497/18769 [10:05<02:52, 24.74it/s]

 77%|███████▋  | 14500/18769 [10:05<02:55, 24.36it/s]

 77%|███████▋  | 14503/18769 [10:05<02:57, 24.08it/s]

 77%|███████▋  | 14506/18769 [10:05<02:58, 23.89it/s]

 77%|███████▋  | 14509/18769 [10:06<02:59, 23.72it/s]

 77%|███████▋  | 14512/18769 [10:06<03:00, 23.60it/s]

 77%|███████▋  | 14515/18769 [10:06<03:00, 23.51it/s]

 77%|███████▋  | 14518/18769 [10:06<03:01, 23.46it/s]

 77%|███████▋  | 14521/18769 [10:06<03:00, 23.55it/s]

 77%|███████▋  | 14524/18769 [10:06<02:59, 23.70it/s]

 77%|███████▋  | 14527/18769 [10:06<02:57, 23.84it/s]

 77%|███████▋  | 14530/18769 [10:06<02:57, 23.91it/s]

 77%|███████▋  | 14533/18769 [10:07<02:57, 23.92it/s]

 77%|███████▋  | 14536/18769 [10:07<02:56, 23.94it/s]

 77%|███████▋  | 14539/18769 [10:07<02:56, 24.01it/s]

 77%|███████▋  | 14542/18769 [10:07<02:55, 24.05it/s]

 77%|███████▋  | 14545/18769 [10:07<02:55, 24.08it/s]

 78%|███████▊  | 14548/18769 [10:07<02:54, 24.13it/s]

 78%|███████▊  | 14551/18769 [10:07<02:54, 24.12it/s]

 78%|███████▊  | 14554/18769 [10:07<02:54, 24.11it/s]

 78%|███████▊  | 14557/18769 [10:08<02:54, 24.11it/s]

 78%|███████▊  | 14560/18769 [10:08<02:54, 24.07it/s]

 78%|███████▊  | 14563/18769 [10:08<02:54, 24.07it/s]

 78%|███████▊  | 14566/18769 [10:08<02:54, 24.10it/s]

 78%|███████▊  | 14569/18769 [10:08<02:54, 24.10it/s]

 78%|███████▊  | 14572/18769 [10:08<02:53, 24.13it/s]

 78%|███████▊  | 14575/18769 [10:08<02:53, 24.16it/s]

 78%|███████▊  | 14578/18769 [10:08<02:53, 24.12it/s]

 78%|███████▊  | 14581/18769 [10:09<02:54, 24.00it/s]

 78%|███████▊  | 14584/18769 [10:09<02:54, 23.94it/s]

 78%|███████▊  | 14587/18769 [10:09<02:55, 23.86it/s]

 78%|███████▊  | 14590/18769 [10:09<02:55, 23.82it/s]

 78%|███████▊  | 14593/18769 [10:09<02:55, 23.79it/s]

 78%|███████▊  | 14596/18769 [10:09<02:59, 23.21it/s]

 78%|███████▊  | 14599/18769 [10:09<02:58, 23.38it/s]

 78%|███████▊  | 14602/18769 [10:09<02:57, 23.46it/s]

 78%|███████▊  | 14605/18769 [10:10<02:58, 23.32it/s]

 78%|███████▊  | 14608/18769 [10:10<02:57, 23.40it/s]

 78%|███████▊  | 14611/18769 [10:10<02:57, 23.42it/s]

 78%|███████▊  | 14614/18769 [10:10<02:57, 23.42it/s]

 78%|███████▊  | 14617/18769 [10:10<02:59, 23.09it/s]

 78%|███████▊  | 14620/18769 [10:10<02:58, 23.22it/s]

 78%|███████▊  | 14623/18769 [10:10<02:57, 23.36it/s]

 78%|███████▊  | 14626/18769 [10:11<02:56, 23.44it/s]

 78%|███████▊  | 14630/18769 [10:11<02:43, 25.33it/s]

 78%|███████▊  | 14633/18769 [10:11<02:46, 24.78it/s]

 78%|███████▊  | 14636/18769 [10:11<02:49, 24.40it/s]

 78%|███████▊  | 14639/18769 [10:11<02:51, 24.12it/s]

 78%|███████▊  | 14642/18769 [10:11<02:52, 23.95it/s]

 78%|███████▊  | 14645/18769 [10:11<02:53, 23.83it/s]

 78%|███████▊  | 14648/18769 [10:11<02:53, 23.74it/s]

 78%|███████▊  | 14651/18769 [10:12<02:53, 23.71it/s]

 78%|███████▊  | 14654/18769 [10:12<02:55, 23.44it/s]

 78%|███████▊  | 14657/18769 [10:12<02:55, 23.46it/s]

 78%|███████▊  | 14660/18769 [10:12<02:53, 23.67it/s]

 78%|███████▊  | 14663/18769 [10:12<02:52, 23.74it/s]

 78%|███████▊  | 14666/18769 [10:12<02:52, 23.81it/s]

 78%|███████▊  | 14669/18769 [10:12<02:51, 23.86it/s]

 78%|███████▊  | 14672/18769 [10:12<02:51, 23.88it/s]

 78%|███████▊  | 14675/18769 [10:13<02:52, 23.78it/s]

 78%|███████▊  | 14678/18769 [10:13<02:52, 23.78it/s]

 78%|███████▊  | 14681/18769 [10:13<02:51, 23.80it/s]

 78%|███████▊  | 14684/18769 [10:13<02:51, 23.82it/s]

 78%|███████▊  | 14687/18769 [10:13<02:51, 23.84it/s]

 78%|███████▊  | 14690/18769 [10:13<02:50, 23.87it/s]

 78%|███████▊  | 14693/18769 [10:13<02:50, 23.87it/s]

 78%|███████▊  | 14696/18769 [10:13<02:50, 23.89it/s]

 78%|███████▊  | 14699/18769 [10:14<02:50, 23.87it/s]

 78%|███████▊  | 14702/18769 [10:14<02:50, 23.81it/s]

 78%|███████▊  | 14705/18769 [10:14<02:50, 23.88it/s]

 78%|███████▊  | 14708/18769 [10:14<02:49, 23.90it/s]

 78%|███████▊  | 14711/18769 [10:14<02:49, 23.89it/s]

 78%|███████▊  | 14714/18769 [10:14<02:49, 23.87it/s]

 78%|███████▊  | 14717/18769 [10:14<02:50, 23.76it/s]

 78%|███████▊  | 14720/18769 [10:14<02:51, 23.67it/s]

 78%|███████▊  | 14723/18769 [10:15<02:51, 23.63it/s]

 78%|███████▊  | 14726/18769 [10:15<02:52, 23.38it/s]

 78%|███████▊  | 14729/18769 [10:15<02:52, 23.40it/s]

 78%|███████▊  | 14732/18769 [10:15<02:52, 23.42it/s]

 79%|███████▊  | 14735/18769 [10:15<02:52, 23.43it/s]

 79%|███████▊  | 14738/18769 [10:15<02:51, 23.46it/s]

 79%|███████▊  | 14741/18769 [10:15<02:51, 23.43it/s]

 79%|███████▊  | 14744/18769 [10:15<02:51, 23.45it/s]

 79%|███████▊  | 14747/18769 [10:16<02:52, 23.37it/s]

 79%|███████▊  | 14750/18769 [10:16<02:53, 23.20it/s]

 79%|███████▊  | 14753/18769 [10:16<02:53, 23.18it/s]

 79%|███████▊  | 14756/18769 [10:16<02:53, 23.17it/s]

 79%|███████▊  | 14759/18769 [10:16<02:53, 23.18it/s]

 79%|███████▊  | 14762/18769 [10:16<02:52, 23.26it/s]

 79%|███████▊  | 14765/18769 [10:16<02:52, 23.26it/s]

 79%|███████▊  | 14769/18769 [10:17<02:38, 25.18it/s]

 79%|███████▊  | 14772/18769 [10:17<02:44, 24.37it/s]

 79%|███████▊  | 14775/18769 [10:17<02:46, 23.92it/s]

 79%|███████▊  | 14778/18769 [10:17<02:48, 23.74it/s]

 79%|███████▉  | 14781/18769 [10:17<02:48, 23.61it/s]

 79%|███████▉  | 14784/18769 [10:17<02:49, 23.56it/s]

 79%|███████▉  | 14787/18769 [10:17<02:49, 23.48it/s]

 79%|███████▉  | 14790/18769 [10:17<02:50, 23.40it/s]

 79%|███████▉  | 14793/18769 [10:18<02:50, 23.39it/s]

 79%|███████▉  | 14796/18769 [10:18<02:48, 23.54it/s]

 79%|███████▉  | 14799/18769 [10:18<02:47, 23.72it/s]

 79%|███████▉  | 14802/18769 [10:18<02:45, 23.91it/s]

 79%|███████▉  | 14805/18769 [10:18<02:44, 24.04it/s]

 79%|███████▉  | 14808/18769 [10:18<02:44, 24.15it/s]

 79%|███████▉  | 14811/18769 [10:18<02:43, 24.17it/s]

 79%|███████▉  | 14814/18769 [10:18<02:43, 24.21it/s]

 79%|███████▉  | 14817/18769 [10:19<02:43, 24.21it/s]

 79%|███████▉  | 14820/18769 [10:19<02:42, 24.25it/s]

 79%|███████▉  | 14823/18769 [10:19<02:43, 24.21it/s]

 79%|███████▉  | 14826/18769 [10:19<02:44, 24.04it/s]

 79%|███████▉  | 14829/18769 [10:19<02:43, 24.04it/s]

 79%|███████▉  | 14832/18769 [10:19<02:43, 24.08it/s]

 79%|███████▉  | 14835/18769 [10:19<02:42, 24.18it/s]

 79%|███████▉  | 14838/18769 [10:19<02:42, 24.22it/s]

 79%|███████▉  | 14841/18769 [10:20<02:42, 24.24it/s]

 79%|███████▉  | 14844/18769 [10:20<02:42, 24.14it/s]

 79%|███████▉  | 14847/18769 [10:20<02:42, 24.08it/s]

 79%|███████▉  | 14850/18769 [10:20<02:47, 23.33it/s]

 79%|███████▉  | 14853/18769 [10:20<02:46, 23.47it/s]

 79%|███████▉  | 14856/18769 [10:20<02:45, 23.58it/s]

 79%|███████▉  | 14859/18769 [10:20<02:45, 23.67it/s]

 79%|███████▉  | 14862/18769 [10:20<02:44, 23.74it/s]

 79%|███████▉  | 14865/18769 [10:21<02:44, 23.80it/s]

 79%|███████▉  | 14868/18769 [10:21<02:43, 23.83it/s]

 79%|███████▉  | 14871/18769 [10:21<02:43, 23.83it/s]

 79%|███████▉  | 14874/18769 [10:21<02:43, 23.80it/s]

 79%|███████▉  | 14877/18769 [10:21<02:43, 23.75it/s]

 79%|███████▉  | 14880/18769 [10:21<02:43, 23.75it/s]

 79%|███████▉  | 14883/18769 [10:21<02:43, 23.74it/s]

 79%|███████▉  | 14886/18769 [10:21<02:43, 23.71it/s]

 79%|███████▉  | 14889/18769 [10:22<02:43, 23.74it/s]

 79%|███████▉  | 14892/18769 [10:22<02:43, 23.64it/s]

 79%|███████▉  | 14895/18769 [10:22<02:44, 23.59it/s]

 79%|███████▉  | 14898/18769 [10:22<02:44, 23.55it/s]

 79%|███████▉  | 14901/18769 [10:22<02:44, 23.47it/s]

 79%|███████▉  | 14904/18769 [10:22<02:44, 23.46it/s]

 79%|███████▉  | 14908/18769 [10:22<02:32, 25.36it/s]

 79%|███████▉  | 14911/18769 [10:22<02:36, 24.72it/s]

 79%|███████▉  | 14914/18769 [10:23<02:39, 24.22it/s]

 79%|███████▉  | 14917/18769 [10:23<02:40, 23.97it/s]

 79%|███████▉  | 14920/18769 [10:23<02:41, 23.82it/s]

 80%|███████▉  | 14923/18769 [10:23<02:42, 23.66it/s]

 80%|███████▉  | 14926/18769 [10:23<02:42, 23.59it/s]

 80%|███████▉  | 14929/18769 [10:23<02:42, 23.56it/s]

 80%|███████▉  | 14932/18769 [10:23<02:42, 23.66it/s]

 80%|███████▉  | 14935/18769 [10:23<02:41, 23.78it/s]

 80%|███████▉  | 14938/18769 [10:24<02:40, 23.89it/s]

 80%|███████▉  | 14941/18769 [10:24<02:40, 23.88it/s]

 80%|███████▉  | 14944/18769 [10:24<02:39, 23.95it/s]

 80%|███████▉  | 14947/18769 [10:24<02:39, 24.01it/s]

 80%|███████▉  | 14950/18769 [10:24<02:38, 24.03it/s]

 80%|███████▉  | 14953/18769 [10:24<02:38, 24.05it/s]

 80%|███████▉  | 14956/18769 [10:24<02:38, 24.06it/s]

 80%|███████▉  | 14959/18769 [10:24<02:38, 24.09it/s]

 80%|███████▉  | 14962/18769 [10:25<02:38, 24.09it/s]

 80%|███████▉  | 14965/18769 [10:25<02:37, 24.11it/s]

 80%|███████▉  | 14968/18769 [10:25<02:38, 24.05it/s]

 80%|███████▉  | 14971/18769 [10:25<02:37, 24.04it/s]

 80%|███████▉  | 14974/18769 [10:25<02:37, 24.04it/s]

 80%|███████▉  | 14977/18769 [10:25<02:37, 24.04it/s]

 80%|███████▉  | 14980/18769 [10:25<02:37, 24.07it/s]

 80%|███████▉  | 14983/18769 [10:25<02:37, 24.08it/s]

 80%|███████▉  | 14986/18769 [10:26<02:37, 24.07it/s]

 80%|███████▉  | 14989/18769 [10:26<02:37, 23.96it/s]

 80%|███████▉  | 14992/18769 [10:26<02:38, 23.85it/s]

 80%|███████▉  | 14995/18769 [10:26<02:38, 23.79it/s]

 80%|███████▉  | 14998/18769 [10:26<02:38, 23.76it/s]

 80%|███████▉  | 15001/18769 [10:26<02:38, 23.76it/s]

 80%|███████▉  | 15004/18769 [10:26<02:38, 23.75it/s]

 80%|███████▉  | 15007/18769 [10:26<02:38, 23.71it/s]

 80%|███████▉  | 15010/18769 [10:27<02:38, 23.70it/s]

 80%|███████▉  | 15013/18769 [10:27<02:38, 23.66it/s]

 80%|████████  | 15016/18769 [10:27<02:39, 23.58it/s]

 80%|████████  | 15019/18769 [10:27<02:39, 23.52it/s]

 80%|████████  | 15022/18769 [10:27<02:39, 23.48it/s]

 80%|████████  | 15025/18769 [10:27<02:39, 23.50it/s]

 80%|████████  | 15028/18769 [10:27<02:39, 23.48it/s]

 80%|████████  | 15031/18769 [10:27<02:39, 23.43it/s]

 80%|████████  | 15034/18769 [10:28<02:39, 23.40it/s]

 80%|████████  | 15037/18769 [10:28<02:40, 23.31it/s]

 80%|████████  | 15040/18769 [10:28<02:39, 23.32it/s]

 80%|████████  | 15044/18769 [10:28<02:27, 25.18it/s]

 80%|████████  | 15047/18769 [10:28<02:31, 24.59it/s]

 80%|████████  | 15050/18769 [10:28<02:33, 24.26it/s]

 80%|████████  | 15053/18769 [10:28<02:34, 23.99it/s]

 80%|████████  | 15056/18769 [10:29<02:36, 23.80it/s]

 80%|████████  | 15059/18769 [10:29<02:36, 23.68it/s]

 80%|████████  | 15062/18769 [10:29<02:37, 23.59it/s]

 80%|████████  | 15065/18769 [10:29<02:37, 23.56it/s]

 80%|████████  | 15068/18769 [10:29<02:37, 23.45it/s]

 80%|████████  | 15071/18769 [10:29<02:36, 23.64it/s]

 80%|████████  | 15074/18769 [10:29<02:35, 23.76it/s]

 80%|████████  | 15077/18769 [10:29<02:34, 23.84it/s]

 80%|████████  | 15080/18769 [10:30<02:34, 23.89it/s]

 80%|████████  | 15083/18769 [10:30<02:33, 23.95it/s]

 80%|████████  | 15086/18769 [10:30<02:34, 23.82it/s]

 80%|████████  | 15089/18769 [10:30<02:37, 23.42it/s]

 80%|████████  | 15092/18769 [10:30<02:35, 23.63it/s]

 80%|████████  | 15095/18769 [10:30<02:34, 23.77it/s]

 80%|████████  | 15098/18769 [10:30<02:33, 23.86it/s]

 80%|████████  | 15101/18769 [10:30<02:33, 23.90it/s]

 80%|████████  | 15104/18769 [10:31<02:33, 23.94it/s]

 80%|████████  | 15107/18769 [10:31<02:32, 24.00it/s]

 81%|████████  | 15110/18769 [10:31<02:32, 24.04it/s]

 81%|████████  | 15113/18769 [10:31<02:32, 24.02it/s]

 81%|████████  | 15116/18769 [10:31<02:31, 24.04it/s]

 81%|████████  | 15119/18769 [10:31<02:31, 24.06it/s]

 81%|████████  | 15122/18769 [10:31<02:31, 24.07it/s]

 81%|████████  | 15125/18769 [10:31<02:31, 24.09it/s]

 81%|████████  | 15128/18769 [10:32<02:31, 24.03it/s]

 81%|████████  | 15131/18769 [10:32<02:32, 23.92it/s]

 81%|████████  | 15134/18769 [10:32<02:32, 23.85it/s]

 81%|████████  | 15137/18769 [10:32<02:32, 23.80it/s]

 81%|████████  | 15140/18769 [10:32<02:32, 23.82it/s]

 81%|████████  | 15143/18769 [10:32<02:32, 23.80it/s]

 81%|████████  | 15146/18769 [10:32<02:32, 23.78it/s]

 81%|████████  | 15149/18769 [10:32<02:32, 23.72it/s]

 81%|████████  | 15152/18769 [10:33<02:32, 23.66it/s]

 81%|████████  | 15155/18769 [10:33<02:32, 23.65it/s]

 81%|████████  | 15158/18769 [10:33<02:33, 23.46it/s]

 81%|████████  | 15161/18769 [10:33<02:33, 23.48it/s]

 81%|████████  | 15164/18769 [10:33<02:33, 23.49it/s]

 81%|████████  | 15167/18769 [10:33<02:33, 23.53it/s]

 81%|████████  | 15170/18769 [10:33<02:33, 23.51it/s]

 81%|████████  | 15173/18769 [10:33<02:32, 23.54it/s]

 81%|████████  | 15176/18769 [10:34<02:33, 23.44it/s]

 81%|████████  | 15179/18769 [10:34<02:33, 23.40it/s]

 81%|████████  | 15183/18769 [10:34<02:22, 25.15it/s]

 81%|████████  | 15186/18769 [10:34<02:26, 24.54it/s]

 81%|████████  | 15189/18769 [10:34<02:28, 24.16it/s]

 81%|████████  | 15192/18769 [10:34<02:29, 23.95it/s]

 81%|████████  | 15195/18769 [10:34<02:29, 23.83it/s]

 81%|████████  | 15198/18769 [10:34<02:30, 23.70it/s]

 81%|████████  | 15201/18769 [10:35<02:30, 23.64it/s]

 81%|████████  | 15204/18769 [10:35<02:31, 23.57it/s]

 81%|████████  | 15207/18769 [10:35<02:30, 23.70it/s]

 81%|████████  | 15210/18769 [10:35<02:29, 23.76it/s]

 81%|████████  | 15213/18769 [10:35<02:29, 23.75it/s]

 81%|████████  | 15216/18769 [10:35<02:28, 23.88it/s]

 81%|████████  | 15219/18769 [10:35<02:28, 23.97it/s]

 81%|████████  | 15222/18769 [10:35<02:27, 24.04it/s]

 81%|████████  | 15225/18769 [10:36<02:27, 24.04it/s]

 81%|████████  | 15228/18769 [10:36<02:27, 24.03it/s]

 81%|████████  | 15231/18769 [10:36<02:28, 23.84it/s]

 81%|████████  | 15234/18769 [10:36<02:27, 23.94it/s]

 81%|████████  | 15237/18769 [10:36<02:26, 24.04it/s]

 81%|████████  | 15240/18769 [10:36<02:26, 24.10it/s]

 81%|████████  | 15243/18769 [10:36<02:26, 24.11it/s]

 81%|████████  | 15246/18769 [10:36<02:26, 24.08it/s]

 81%|████████  | 15249/18769 [10:37<02:26, 24.07it/s]

 81%|████████▏ | 15252/18769 [10:37<02:25, 24.11it/s]

 81%|████████▏ | 15255/18769 [10:37<02:25, 24.09it/s]

 81%|████████▏ | 15258/18769 [10:37<02:25, 24.11it/s]

 81%|████████▏ | 15261/18769 [10:37<02:25, 24.14it/s]

 81%|████████▏ | 15264/18769 [10:37<02:25, 24.05it/s]

 81%|████████▏ | 15267/18769 [10:37<02:26, 23.95it/s]

 81%|████████▏ | 15270/18769 [10:37<02:26, 23.90it/s]

 81%|████████▏ | 15273/18769 [10:38<02:26, 23.87it/s]

 81%|████████▏ | 15276/18769 [10:38<02:26, 23.87it/s]

 81%|████████▏ | 15279/18769 [10:38<02:27, 23.64it/s]

 81%|████████▏ | 15282/18769 [10:38<02:27, 23.68it/s]

 81%|████████▏ | 15285/18769 [10:38<02:27, 23.70it/s]

 81%|████████▏ | 15288/18769 [10:38<02:27, 23.68it/s]

 81%|████████▏ | 15291/18769 [10:38<02:27, 23.64it/s]

 81%|████████▏ | 15294/18769 [10:38<02:27, 23.63it/s]

 82%|████████▏ | 15297/18769 [10:39<02:27, 23.60it/s]

 82%|████████▏ | 15300/18769 [10:39<02:27, 23.60it/s]

 82%|████████▏ | 15303/18769 [10:39<02:27, 23.49it/s]

 82%|████████▏ | 15306/18769 [10:39<02:27, 23.46it/s]

 82%|████████▏ | 15309/18769 [10:39<02:27, 23.45it/s]

 82%|████████▏ | 15312/18769 [10:39<02:27, 23.43it/s]

 82%|████████▏ | 15315/18769 [10:39<02:27, 23.42it/s]

 82%|████████▏ | 15318/18769 [10:40<02:27, 23.45it/s]

 82%|████████▏ | 15322/18769 [10:40<02:16, 25.32it/s]

 82%|████████▏ | 15325/18769 [10:40<02:19, 24.67it/s]

 82%|████████▏ | 15328/18769 [10:40<02:23, 24.03it/s]

 82%|████████▏ | 15331/18769 [10:40<02:24, 23.83it/s]

 82%|████████▏ | 15334/18769 [10:40<02:25, 23.69it/s]

 82%|████████▏ | 15337/18769 [10:40<02:27, 23.28it/s]

 82%|████████▏ | 15340/18769 [10:40<02:26, 23.34it/s]

 82%|████████▏ | 15343/18769 [10:41<02:25, 23.48it/s]

 82%|████████▏ | 15346/18769 [10:41<02:29, 22.85it/s]

 82%|████████▏ | 15349/18769 [10:41<02:27, 23.20it/s]

 82%|████████▏ | 15352/18769 [10:41<02:29, 22.78it/s]

 82%|████████▏ | 15355/18769 [10:41<02:27, 23.13it/s]

 82%|████████▏ | 15358/18769 [10:41<02:25, 23.43it/s]

 82%|████████▏ | 15361/18769 [10:41<02:23, 23.68it/s]

 82%|████████▏ | 15364/18769 [10:41<02:22, 23.89it/s]

 82%|████████▏ | 15367/18769 [10:42<02:21, 24.01it/s]

 82%|████████▏ | 15370/18769 [10:42<02:21, 24.08it/s]

 82%|████████▏ | 15373/18769 [10:42<02:20, 24.14it/s]

 82%|████████▏ | 15376/18769 [10:42<02:20, 24.18it/s]

 82%|████████▏ | 15379/18769 [10:42<02:20, 24.18it/s]

 82%|████████▏ | 15382/18769 [10:42<02:19, 24.21it/s]

 82%|████████▏ | 15385/18769 [10:42<02:19, 24.23it/s]

 82%|████████▏ | 15388/18769 [10:42<02:19, 24.20it/s]

 82%|████████▏ | 15391/18769 [10:43<02:19, 24.23it/s]

 82%|████████▏ | 15394/18769 [10:43<02:19, 24.22it/s]

 82%|████████▏ | 15397/18769 [10:43<02:27, 22.83it/s]

 82%|████████▏ | 15400/18769 [10:43<02:27, 22.91it/s]

 82%|████████▏ | 15403/18769 [10:43<02:25, 23.15it/s]

 82%|████████▏ | 15406/18769 [10:43<02:24, 23.29it/s]

 82%|████████▏ | 15409/18769 [10:43<02:23, 23.46it/s]

 82%|████████▏ | 15412/18769 [10:43<02:22, 23.56it/s]

 82%|████████▏ | 15415/18769 [10:44<02:21, 23.64it/s]

 82%|████████▏ | 15418/18769 [10:44<02:21, 23.65it/s]

 82%|████████▏ | 15421/18769 [10:44<02:22, 23.54it/s]

 82%|████████▏ | 15424/18769 [10:44<02:22, 23.51it/s]

 82%|████████▏ | 15427/18769 [10:44<02:21, 23.56it/s]

 82%|████████▏ | 15430/18769 [10:44<02:21, 23.59it/s]

 82%|████████▏ | 15433/18769 [10:44<02:21, 23.60it/s]

 82%|████████▏ | 15436/18769 [10:44<02:21, 23.62it/s]

 82%|████████▏ | 15439/18769 [10:45<02:21, 23.59it/s]

 82%|████████▏ | 15442/18769 [10:45<02:20, 23.60it/s]

 82%|████████▏ | 15445/18769 [10:45<02:21, 23.56it/s]

 82%|████████▏ | 15448/18769 [10:45<02:22, 23.31it/s]

 82%|████████▏ | 15451/18769 [10:45<02:22, 23.34it/s]

 82%|████████▏ | 15454/18769 [10:45<02:21, 23.35it/s]

 82%|████████▏ | 15458/18769 [10:45<02:10, 25.30it/s]

 82%|████████▏ | 15461/18769 [10:46<02:13, 24.70it/s]

 82%|████████▏ | 15464/18769 [10:46<02:16, 24.26it/s]

 82%|████████▏ | 15467/18769 [10:46<02:17, 23.96it/s]

 82%|████████▏ | 15470/18769 [10:46<02:18, 23.76it/s]

 82%|████████▏ | 15473/18769 [10:46<02:19, 23.68it/s]

 82%|████████▏ | 15476/18769 [10:46<02:19, 23.62it/s]

 82%|████████▏ | 15479/18769 [10:46<02:19, 23.60it/s]

 82%|████████▏ | 15482/18769 [10:46<02:18, 23.77it/s]

 83%|████████▎ | 15485/18769 [10:47<02:17, 23.84it/s]

 83%|████████▎ | 15488/18769 [10:47<02:17, 23.87it/s]

 83%|████████▎ | 15491/18769 [10:47<02:16, 23.95it/s]

 83%|████████▎ | 15494/18769 [10:47<02:16, 23.94it/s]

 83%|████████▎ | 15497/18769 [10:47<02:16, 23.96it/s]

 83%|████████▎ | 15500/18769 [10:47<02:16, 23.99it/s]

 83%|████████▎ | 15503/18769 [10:47<02:15, 24.04it/s]

 83%|████████▎ | 15506/18769 [10:47<02:15, 24.04it/s]

 83%|████████▎ | 15509/18769 [10:48<02:15, 24.06it/s]

 83%|████████▎ | 15512/18769 [10:48<02:15, 24.06it/s]

 83%|████████▎ | 15515/18769 [10:48<02:15, 24.01it/s]

 83%|████████▎ | 15518/18769 [10:48<02:15, 24.05it/s]

 83%|████████▎ | 15521/18769 [10:48<02:15, 24.02it/s]

 83%|████████▎ | 15524/18769 [10:48<02:15, 24.00it/s]

 83%|████████▎ | 15527/18769 [10:48<02:15, 24.01it/s]

 83%|████████▎ | 15530/18769 [10:48<02:14, 24.05it/s]

 83%|████████▎ | 15533/18769 [10:49<02:14, 24.04it/s]

 83%|████████▎ | 15536/18769 [10:49<02:14, 24.00it/s]

 83%|████████▎ | 15539/18769 [10:49<02:15, 23.91it/s]

 83%|████████▎ | 15542/18769 [10:49<02:15, 23.80it/s]

 83%|████████▎ | 15545/18769 [10:49<02:16, 23.56it/s]

 83%|████████▎ | 15548/18769 [10:49<02:16, 23.57it/s]

 83%|████████▎ | 15551/18769 [10:49<02:16, 23.56it/s]

 83%|████████▎ | 15554/18769 [10:49<02:16, 23.59it/s]

 83%|████████▎ | 15557/18769 [10:50<02:15, 23.63it/s]

 83%|████████▎ | 15560/18769 [10:50<02:15, 23.60it/s]

 83%|████████▎ | 15563/18769 [10:50<02:15, 23.58it/s]

 83%|████████▎ | 15566/18769 [10:50<02:16, 23.51it/s]

 83%|████████▎ | 15569/18769 [10:50<02:16, 23.50it/s]

 83%|████████▎ | 15572/18769 [10:50<02:16, 23.49it/s]

 83%|████████▎ | 15575/18769 [10:50<02:16, 23.46it/s]

 83%|████████▎ | 15578/18769 [10:50<02:16, 23.40it/s]

 83%|████████▎ | 15581/18769 [10:51<02:16, 23.37it/s]

 83%|████████▎ | 15584/18769 [10:51<02:16, 23.32it/s]

 83%|████████▎ | 15587/18769 [10:51<02:16, 23.30it/s]

 83%|████████▎ | 15590/18769 [10:51<02:16, 23.26it/s]

 83%|████████▎ | 15593/18769 [10:51<02:16, 23.29it/s]

 83%|████████▎ | 15597/18769 [10:51<02:06, 25.17it/s]

 83%|████████▎ | 15600/18769 [10:51<02:08, 24.60it/s]

 83%|████████▎ | 15603/18769 [10:51<02:10, 24.20it/s]

 83%|████████▎ | 15606/18769 [10:52<02:12, 23.94it/s]

 83%|████████▎ | 15609/18769 [10:52<02:13, 23.72it/s]

 83%|████████▎ | 15612/18769 [10:52<02:13, 23.61it/s]

 83%|████████▎ | 15615/18769 [10:52<02:14, 23.52it/s]

 83%|████████▎ | 15618/18769 [10:52<02:13, 23.61it/s]

 83%|████████▎ | 15621/18769 [10:52<02:12, 23.75it/s]

 83%|████████▎ | 15624/18769 [10:52<02:11, 23.88it/s]

 83%|████████▎ | 15627/18769 [10:52<02:11, 23.97it/s]

 83%|████████▎ | 15630/18769 [10:53<02:10, 24.05it/s]

 83%|████████▎ | 15633/18769 [10:53<02:09, 24.12it/s]

 83%|████████▎ | 15636/18769 [10:53<02:09, 24.14it/s]

 83%|████████▎ | 15639/18769 [10:53<02:09, 24.14it/s]

 83%|████████▎ | 15642/18769 [10:53<02:09, 24.18it/s]

 83%|████████▎ | 15645/18769 [10:53<02:09, 24.14it/s]

 83%|████████▎ | 15648/18769 [10:53<02:09, 24.16it/s]

 83%|████████▎ | 15651/18769 [10:53<02:09, 24.14it/s]

 83%|████████▎ | 15654/18769 [10:54<02:08, 24.17it/s]

 83%|████████▎ | 15657/18769 [10:54<02:08, 24.16it/s]

 83%|████████▎ | 15660/18769 [10:54<02:08, 24.11it/s]

 83%|████████▎ | 15663/18769 [10:54<02:08, 24.13it/s]

 83%|████████▎ | 15666/18769 [10:54<02:08, 24.17it/s]

 83%|████████▎ | 15669/18769 [10:54<02:08, 24.20it/s]

 83%|████████▎ | 15672/18769 [10:54<02:08, 24.19it/s]

 84%|████████▎ | 15675/18769 [10:54<02:08, 24.02it/s]

 84%|████████▎ | 15678/18769 [10:55<02:09, 23.95it/s]

 84%|████████▎ | 15681/18769 [10:55<02:09, 23.92it/s]

 84%|████████▎ | 15684/18769 [10:55<02:08, 23.91it/s]

 84%|████████▎ | 15687/18769 [10:55<02:09, 23.85it/s]

 84%|████████▎ | 15690/18769 [10:55<02:09, 23.83it/s]

 84%|████████▎ | 15693/18769 [10:55<02:09, 23.84it/s]

 84%|████████▎ | 15696/18769 [10:55<02:08, 23.88it/s]

 84%|████████▎ | 15699/18769 [10:55<02:08, 23.83it/s]

 84%|████████▎ | 15702/18769 [10:56<02:09, 23.77it/s]

 84%|████████▎ | 15705/18769 [10:56<02:09, 23.70it/s]

 84%|████████▎ | 15708/18769 [10:56<02:09, 23.66it/s]

 84%|████████▎ | 15711/18769 [10:56<02:09, 23.63it/s]

 84%|████████▎ | 15714/18769 [10:56<02:09, 23.59it/s]

 84%|████████▎ | 15717/18769 [10:56<02:09, 23.57it/s]

 84%|████████▍ | 15720/18769 [10:56<02:09, 23.55it/s]

 84%|████████▍ | 15723/18769 [10:57<02:09, 23.54it/s]

 84%|████████▍ | 15726/18769 [10:57<02:09, 23.47it/s]

 84%|████████▍ | 15729/18769 [10:57<02:09, 23.48it/s]

 84%|████████▍ | 15732/18769 [10:57<02:09, 23.44it/s]

 84%|████████▍ | 15736/18769 [10:57<01:59, 25.35it/s]

 84%|████████▍ | 15739/18769 [10:57<02:02, 24.73it/s]

 84%|████████▍ | 15742/18769 [10:57<02:04, 24.33it/s]

 84%|████████▍ | 15745/18769 [10:57<02:05, 24.03it/s]

 84%|████████▍ | 15748/18769 [10:58<02:06, 23.86it/s]

 84%|████████▍ | 15751/18769 [10:58<02:07, 23.75it/s]

 84%|████████▍ | 15754/18769 [10:58<02:06, 23.76it/s]

 84%|████████▍ | 15757/18769 [10:58<02:06, 23.88it/s]

 84%|████████▍ | 15760/18769 [10:58<02:05, 23.95it/s]

 84%|████████▍ | 15763/18769 [10:58<02:05, 24.03it/s]

 84%|████████▍ | 15766/18769 [10:58<02:04, 24.13it/s]

 84%|████████▍ | 15769/18769 [10:58<02:04, 24.18it/s]

 84%|████████▍ | 15772/18769 [10:59<02:03, 24.17it/s]

 84%|████████▍ | 15775/18769 [10:59<02:03, 24.18it/s]

 84%|████████▍ | 15778/18769 [10:59<02:03, 24.19it/s]

 84%|████████▍ | 15781/18769 [10:59<02:03, 24.20it/s]

 84%|████████▍ | 15784/18769 [10:59<02:03, 24.22it/s]

 84%|████████▍ | 15787/18769 [10:59<02:03, 24.17it/s]

 84%|████████▍ | 15790/18769 [10:59<02:03, 24.15it/s]

 84%|████████▍ | 15793/18769 [10:59<02:03, 24.19it/s]

 84%|████████▍ | 15796/18769 [11:00<02:02, 24.19it/s]

 84%|████████▍ | 15799/18769 [11:00<02:03, 24.13it/s]

 84%|████████▍ | 15802/18769 [11:00<02:02, 24.16it/s]

 84%|████████▍ | 15805/18769 [11:00<02:02, 24.17it/s]

 84%|████████▍ | 15808/18769 [11:00<02:02, 24.21it/s]

 84%|████████▍ | 15811/18769 [11:00<02:02, 24.13it/s]

 84%|████████▍ | 15814/18769 [11:00<02:02, 24.07it/s]

 84%|████████▍ | 15817/18769 [11:00<02:03, 23.97it/s]

 84%|████████▍ | 15820/18769 [11:01<02:03, 23.97it/s]

 84%|████████▍ | 15823/18769 [11:01<02:03, 23.92it/s]

 84%|████████▍ | 15826/18769 [11:01<02:02, 23.94it/s]

 84%|████████▍ | 15829/18769 [11:01<02:02, 23.92it/s]

 84%|████████▍ | 15832/18769 [11:01<02:02, 23.94it/s]

 84%|████████▍ | 15835/18769 [11:01<02:03, 23.72it/s]

 84%|████████▍ | 15838/18769 [11:01<02:03, 23.73it/s]

 84%|████████▍ | 15841/18769 [11:01<02:03, 23.70it/s]

 84%|████████▍ | 15844/18769 [11:02<02:03, 23.66it/s]

 84%|████████▍ | 15847/18769 [11:02<02:03, 23.62it/s]

 84%|████████▍ | 15850/18769 [11:02<02:03, 23.55it/s]

 84%|████████▍ | 15853/18769 [11:02<02:03, 23.52it/s]

 84%|████████▍ | 15856/18769 [11:02<02:03, 23.50it/s]

 84%|████████▍ | 15859/18769 [11:02<02:04, 23.46it/s]

 85%|████████▍ | 15862/18769 [11:02<02:03, 23.48it/s]

 85%|████████▍ | 15865/18769 [11:02<02:03, 23.43it/s]

 85%|████████▍ | 15868/18769 [11:03<02:03, 23.44it/s]

 85%|████████▍ | 15872/18769 [11:03<01:54, 25.32it/s]

 85%|████████▍ | 15875/18769 [11:03<01:57, 24.73it/s]

 85%|████████▍ | 15878/18769 [11:03<01:59, 24.29it/s]

 85%|████████▍ | 15881/18769 [11:03<02:00, 24.02it/s]

 85%|████████▍ | 15884/18769 [11:03<02:00, 23.85it/s]

 85%|████████▍ | 15887/18769 [11:03<02:01, 23.72it/s]

 85%|████████▍ | 15890/18769 [11:03<02:01, 23.66it/s]

 85%|████████▍ | 15893/18769 [11:04<02:00, 23.77it/s]

 85%|████████▍ | 15896/18769 [11:04<02:00, 23.89it/s]

 85%|████████▍ | 15899/18769 [11:04<02:00, 23.89it/s]

 85%|████████▍ | 15902/18769 [11:04<01:59, 23.98it/s]

 85%|████████▍ | 15905/18769 [11:04<01:59, 23.99it/s]

 85%|████████▍ | 15908/18769 [11:04<01:59, 23.98it/s]

 85%|████████▍ | 15911/18769 [11:04<01:59, 24.00it/s]

 85%|████████▍ | 15914/18769 [11:04<01:58, 24.04it/s]

 85%|████████▍ | 15917/18769 [11:05<01:58, 24.10it/s]

 85%|████████▍ | 15920/18769 [11:05<01:58, 24.13it/s]

 85%|████████▍ | 15923/18769 [11:05<01:58, 24.12it/s]

 85%|████████▍ | 15926/18769 [11:05<01:57, 24.15it/s]

 85%|████████▍ | 15929/18769 [11:05<01:57, 24.15it/s]

 85%|████████▍ | 15932/18769 [11:05<01:58, 23.98it/s]

 85%|████████▍ | 15935/18769 [11:05<01:57, 24.02it/s]

 85%|████████▍ | 15938/18769 [11:05<01:57, 24.03it/s]

 85%|████████▍ | 15941/18769 [11:06<01:57, 24.06it/s]

 85%|████████▍ | 15944/18769 [11:06<01:57, 24.00it/s]

 85%|████████▍ | 15947/18769 [11:06<01:57, 23.99it/s]

 85%|████████▍ | 15950/18769 [11:06<01:57, 23.91it/s]

 85%|████████▍ | 15953/18769 [11:06<01:58, 23.86it/s]

 85%|████████▌ | 15956/18769 [11:06<01:58, 23.81it/s]

 85%|████████▌ | 15959/18769 [11:06<01:58, 23.80it/s]

 85%|████████▌ | 15962/18769 [11:06<01:58, 23.76it/s]

 85%|████████▌ | 15965/18769 [11:07<01:58, 23.74it/s]

 85%|████████▌ | 15968/18769 [11:07<01:57, 23.75it/s]

 85%|████████▌ | 15971/18769 [11:07<01:57, 23.71it/s]

 85%|████████▌ | 15974/18769 [11:07<01:58, 23.68it/s]

 85%|████████▌ | 15977/18769 [11:07<01:58, 23.63it/s]

 85%|████████▌ | 15980/18769 [11:07<01:58, 23.60it/s]

 85%|████████▌ | 15983/18769 [11:07<01:58, 23.56it/s]

 85%|████████▌ | 15986/18769 [11:07<01:58, 23.55it/s]

 85%|████████▌ | 15989/18769 [11:08<01:58, 23.51it/s]

 85%|████████▌ | 15992/18769 [11:08<01:58, 23.50it/s]

 85%|████████▌ | 15995/18769 [11:08<01:58, 23.45it/s]

 85%|████████▌ | 15998/18769 [11:08<01:58, 23.42it/s]

 85%|████████▌ | 16001/18769 [11:08<01:59, 23.16it/s]

 85%|████████▌ | 16004/18769 [11:08<01:58, 23.25it/s]

 85%|████████▌ | 16007/18769 [11:08<01:58, 23.30it/s]

 85%|████████▌ | 16011/18769 [11:08<01:49, 25.24it/s]

 85%|████████▌ | 16014/18769 [11:09<01:51, 24.68it/s]

 85%|████████▌ | 16017/18769 [11:09<01:53, 24.26it/s]

 85%|████████▌ | 16020/18769 [11:09<01:54, 24.00it/s]

 85%|████████▌ | 16023/18769 [11:09<01:55, 23.86it/s]

 85%|████████▌ | 16026/18769 [11:09<01:55, 23.73it/s]

 85%|████████▌ | 16029/18769 [11:09<01:54, 23.83it/s]

 85%|████████▌ | 16032/18769 [11:09<01:54, 23.92it/s]

 85%|████████▌ | 16035/18769 [11:10<01:54, 23.98it/s]

 85%|████████▌ | 16038/18769 [11:10<01:54, 23.94it/s]

 85%|████████▌ | 16041/18769 [11:10<01:53, 23.96it/s]

 85%|████████▌ | 16044/18769 [11:10<01:53, 24.06it/s]

 85%|████████▌ | 16047/18769 [11:10<01:53, 24.05it/s]

 86%|████████▌ | 16050/18769 [11:10<01:54, 23.84it/s]

 86%|████████▌ | 16053/18769 [11:10<01:53, 23.86it/s]

 86%|████████▌ | 16056/18769 [11:10<01:53, 23.92it/s]

 86%|████████▌ | 16059/18769 [11:11<01:53, 23.98it/s]

 86%|████████▌ | 16062/18769 [11:11<01:53, 23.94it/s]

 86%|████████▌ | 16065/18769 [11:11<01:53, 23.92it/s]

 86%|████████▌ | 16068/18769 [11:11<01:52, 23.92it/s]

 86%|████████▌ | 16071/18769 [11:11<01:52, 23.88it/s]

 86%|████████▌ | 16074/18769 [11:11<01:53, 23.84it/s]

 86%|████████▌ | 16077/18769 [11:11<01:54, 23.45it/s]

 86%|████████▌ | 16080/18769 [11:11<01:53, 23.68it/s]

 86%|████████▌ | 16083/18769 [11:12<01:52, 23.84it/s]

 86%|████████▌ | 16086/18769 [11:12<01:52, 23.83it/s]

 86%|████████▌ | 16089/18769 [11:12<01:52, 23.78it/s]

 86%|████████▌ | 16092/18769 [11:12<01:52, 23.77it/s]

 86%|████████▌ | 16095/18769 [11:12<01:52, 23.75it/s]

 86%|████████▌ | 16098/18769 [11:12<01:53, 23.62it/s]

 86%|████████▌ | 16101/18769 [11:12<01:52, 23.64it/s]

 86%|████████▌ | 16104/18769 [11:12<01:52, 23.65it/s]

 86%|████████▌ | 16107/18769 [11:13<01:52, 23.62it/s]

 86%|████████▌ | 16110/18769 [11:13<01:52, 23.55it/s]

 86%|████████▌ | 16113/18769 [11:13<01:52, 23.51it/s]

 86%|████████▌ | 16116/18769 [11:13<01:52, 23.51it/s]

 86%|████████▌ | 16119/18769 [11:13<01:52, 23.54it/s]

 86%|████████▌ | 16122/18769 [11:13<01:52, 23.53it/s]

 86%|████████▌ | 16125/18769 [11:13<01:52, 23.52it/s]

 86%|████████▌ | 16128/18769 [11:13<01:52, 23.49it/s]

 86%|████████▌ | 16131/18769 [11:14<01:52, 23.50it/s]

 86%|████████▌ | 16134/18769 [11:14<01:52, 23.47it/s]

 86%|████████▌ | 16137/18769 [11:14<01:52, 23.46it/s]

 86%|████████▌ | 16140/18769 [11:14<01:51, 23.50it/s]

 86%|████████▌ | 16143/18769 [11:14<01:51, 23.45it/s]

 86%|████████▌ | 16146/18769 [11:14<01:52, 23.29it/s]

 86%|████████▌ | 16150/18769 [11:14<01:43, 25.26it/s]

 86%|████████▌ | 16153/18769 [11:14<01:46, 24.66it/s]

 86%|████████▌ | 16156/18769 [11:15<01:47, 24.29it/s]

 86%|████████▌ | 16159/18769 [11:15<01:48, 24.01it/s]

 86%|████████▌ | 16162/18769 [11:15<01:49, 23.83it/s]

 86%|████████▌ | 16165/18769 [11:15<01:50, 23.64it/s]

 86%|████████▌ | 16168/18769 [11:15<01:49, 23.79it/s]

 86%|████████▌ | 16171/18769 [11:15<01:48, 23.85it/s]

 86%|████████▌ | 16174/18769 [11:15<01:48, 23.94it/s]

 86%|████████▌ | 16177/18769 [11:15<01:48, 23.99it/s]

 86%|████████▌ | 16180/18769 [11:16<01:47, 24.03it/s]

 86%|████████▌ | 16183/18769 [11:16<01:51, 23.22it/s]

 86%|████████▌ | 16186/18769 [11:16<01:51, 23.11it/s]

 86%|████████▋ | 16189/18769 [11:16<01:52, 23.02it/s]

 86%|████████▋ | 16192/18769 [11:16<01:52, 22.92it/s]

 86%|████████▋ | 16195/18769 [11:16<01:52, 22.83it/s]

 86%|████████▋ | 16198/18769 [11:16<01:50, 23.22it/s]

 86%|████████▋ | 16201/18769 [11:17<01:49, 23.51it/s]

 86%|████████▋ | 16204/18769 [11:17<01:48, 23.72it/s]

 86%|████████▋ | 16207/18769 [11:17<01:47, 23.86it/s]

 86%|████████▋ | 16210/18769 [11:17<01:46, 23.96it/s]

 86%|████████▋ | 16213/18769 [11:17<01:46, 24.02it/s]

 86%|████████▋ | 16216/18769 [11:17<01:45, 24.11it/s]

 86%|████████▋ | 16219/18769 [11:17<01:46, 23.92it/s]

 86%|████████▋ | 16222/18769 [11:17<01:46, 23.90it/s]

 86%|████████▋ | 16225/18769 [11:18<01:46, 23.88it/s]

 86%|████████▋ | 16228/18769 [11:18<01:46, 23.87it/s]

 86%|████████▋ | 16231/18769 [11:18<01:46, 23.89it/s]

 86%|████████▋ | 16234/18769 [11:18<01:46, 23.87it/s]

 87%|████████▋ | 16237/18769 [11:18<01:46, 23.87it/s]

 87%|████████▋ | 16240/18769 [11:18<01:46, 23.73it/s]

 87%|████████▋ | 16243/18769 [11:18<01:46, 23.76it/s]

 87%|████████▋ | 16246/18769 [11:18<01:46, 23.71it/s]

 87%|████████▋ | 16249/18769 [11:19<01:46, 23.67it/s]

 87%|████████▋ | 16252/18769 [11:19<01:46, 23.69it/s]

 87%|████████▋ | 16255/18769 [11:19<01:46, 23.68it/s]

 87%|████████▋ | 16258/18769 [11:19<01:46, 23.68it/s]

 87%|████████▋ | 16261/18769 [11:19<01:46, 23.53it/s]

 87%|████████▋ | 16264/18769 [11:19<01:46, 23.48it/s]

 87%|████████▋ | 16267/18769 [11:19<01:47, 23.28it/s]

 87%|████████▋ | 16270/18769 [11:19<01:46, 23.36it/s]

 87%|████████▋ | 16273/18769 [11:20<01:46, 23.44it/s]

 87%|████████▋ | 16276/18769 [11:20<01:46, 23.42it/s]

 87%|████████▋ | 16279/18769 [11:20<01:46, 23.48it/s]

 87%|████████▋ | 16282/18769 [11:20<01:46, 23.37it/s]

 87%|████████▋ | 16286/18769 [11:20<01:38, 25.32it/s]

 87%|████████▋ | 16289/18769 [11:20<01:40, 24.73it/s]

 87%|████████▋ | 16292/18769 [11:20<01:41, 24.31it/s]

 87%|████████▋ | 16295/18769 [11:20<01:42, 24.04it/s]

 87%|████████▋ | 16298/18769 [11:21<01:43, 23.92it/s]

 87%|████████▋ | 16301/18769 [11:21<01:43, 23.75it/s]

 87%|████████▋ | 16304/18769 [11:21<01:43, 23.77it/s]

 87%|████████▋ | 16307/18769 [11:21<01:43, 23.78it/s]

 87%|████████▋ | 16310/18769 [11:21<01:43, 23.87it/s]

 87%|████████▋ | 16313/18769 [11:21<01:42, 23.96it/s]

 87%|████████▋ | 16316/18769 [11:21<01:43, 23.81it/s]

 87%|████████▋ | 16319/18769 [11:21<01:42, 23.93it/s]

 87%|████████▋ | 16322/18769 [11:22<01:41, 24.04it/s]

 87%|████████▋ | 16325/18769 [11:22<01:41, 24.08it/s]

 87%|████████▋ | 16328/18769 [11:22<01:41, 24.08it/s]

 87%|████████▋ | 16331/18769 [11:22<01:41, 24.07it/s]

 87%|████████▋ | 16334/18769 [11:22<01:40, 24.12it/s]

 87%|████████▋ | 16337/18769 [11:22<01:40, 24.14it/s]

 87%|████████▋ | 16340/18769 [11:22<01:40, 24.12it/s]

 87%|████████▋ | 16343/18769 [11:22<01:40, 24.10it/s]

 87%|████████▋ | 16346/18769 [11:23<01:41, 23.99it/s]

 87%|████████▋ | 16349/18769 [11:23<01:40, 24.02it/s]

 87%|████████▋ | 16352/18769 [11:23<01:40, 24.09it/s]

 87%|████████▋ | 16355/18769 [11:23<01:40, 24.06it/s]

 87%|████████▋ | 16358/18769 [11:23<01:40, 24.02it/s]

 87%|████████▋ | 16361/18769 [11:23<01:40, 23.93it/s]

 87%|████████▋ | 16364/18769 [11:23<01:41, 23.67it/s]

 87%|████████▋ | 16367/18769 [11:23<01:41, 23.68it/s]

 87%|████████▋ | 16370/18769 [11:24<01:41, 23.73it/s]

 87%|████████▋ | 16373/18769 [11:24<01:40, 23.77it/s]

 87%|████████▋ | 16376/18769 [11:24<01:40, 23.78it/s]

 87%|████████▋ | 16379/18769 [11:24<01:40, 23.74it/s]

 87%|████████▋ | 16382/18769 [11:24<01:40, 23.70it/s]

 87%|████████▋ | 16385/18769 [11:24<01:40, 23.68it/s]

 87%|████████▋ | 16388/18769 [11:24<01:40, 23.62it/s]

 87%|████████▋ | 16391/18769 [11:24<01:40, 23.58it/s]

 87%|████████▋ | 16394/18769 [11:25<01:40, 23.57it/s]

 87%|████████▋ | 16397/18769 [11:25<01:40, 23.57it/s]

 87%|████████▋ | 16400/18769 [11:25<01:40, 23.53it/s]

 87%|████████▋ | 16403/18769 [11:25<01:40, 23.50it/s]

 87%|████████▋ | 16406/18769 [11:25<01:40, 23.49it/s]

 87%|████████▋ | 16409/18769 [11:25<01:40, 23.48it/s]

 87%|████████▋ | 16412/18769 [11:25<01:40, 23.41it/s]

 87%|████████▋ | 16415/18769 [11:25<01:40, 23.39it/s]

 87%|████████▋ | 16418/18769 [11:26<01:40, 23.38it/s]

 87%|████████▋ | 16421/18769 [11:26<01:40, 23.38it/s]

 88%|████████▊ | 16425/18769 [11:26<01:32, 25.28it/s]

 88%|████████▊ | 16428/18769 [11:26<01:34, 24.69it/s]

 88%|████████▊ | 16431/18769 [11:26<01:36, 24.28it/s]

 88%|████████▊ | 16434/18769 [11:26<01:37, 24.03it/s]

 88%|████████▊ | 16437/18769 [11:26<01:37, 23.82it/s]

 88%|████████▊ | 16440/18769 [11:27<01:37, 23.86it/s]

 88%|████████▊ | 16443/18769 [11:27<01:37, 23.88it/s]

 88%|████████▊ | 16446/18769 [11:27<01:37, 23.94it/s]

 88%|████████▊ | 16449/18769 [11:27<01:36, 23.94it/s]

 88%|████████▊ | 16452/18769 [11:27<01:36, 23.93it/s]

 88%|████████▊ | 16455/18769 [11:27<01:36, 23.91it/s]

 88%|████████▊ | 16458/18769 [11:27<01:36, 24.00it/s]

 88%|████████▊ | 16461/18769 [11:27<01:36, 24.00it/s]

 88%|████████▊ | 16464/18769 [11:28<01:35, 24.02it/s]

 88%|████████▊ | 16467/18769 [11:28<01:35, 24.02it/s]

 88%|████████▊ | 16470/18769 [11:28<01:35, 24.03it/s]

 88%|████████▊ | 16473/18769 [11:28<01:35, 24.06it/s]

 88%|████████▊ | 16476/18769 [11:28<01:35, 24.07it/s]

 88%|████████▊ | 16479/18769 [11:28<01:35, 24.07it/s]

 88%|████████▊ | 16482/18769 [11:28<01:35, 24.02it/s]

 88%|████████▊ | 16485/18769 [11:28<01:35, 24.02it/s]

 88%|████████▊ | 16488/18769 [11:29<01:34, 24.05it/s]

 88%|████████▊ | 16491/18769 [11:29<01:34, 24.08it/s]

 88%|████████▊ | 16494/18769 [11:29<01:34, 24.08it/s]

 88%|████████▊ | 16497/18769 [11:29<01:34, 23.96it/s]

 88%|████████▊ | 16500/18769 [11:29<01:34, 23.91it/s]

 88%|████████▊ | 16503/18769 [11:29<01:34, 23.86it/s]

 88%|████████▊ | 16506/18769 [11:29<01:35, 23.79it/s]

 88%|████████▊ | 16509/18769 [11:29<01:35, 23.77it/s]

 88%|████████▊ | 16512/18769 [11:30<01:34, 23.76it/s]

 88%|████████▊ | 16515/18769 [11:30<01:34, 23.73it/s]

 88%|████████▊ | 16518/18769 [11:30<01:34, 23.73it/s]

 88%|████████▊ | 16521/18769 [11:30<01:35, 23.64it/s]

 88%|████████▊ | 16524/18769 [11:30<01:35, 23.59it/s]

 88%|████████▊ | 16527/18769 [11:30<01:35, 23.55it/s]

 88%|████████▊ | 16530/18769 [11:30<01:35, 23.52it/s]

 88%|████████▊ | 16533/18769 [11:30<01:35, 23.50it/s]

 88%|████████▊ | 16536/18769 [11:31<01:35, 23.47it/s]

 88%|████████▊ | 16539/18769 [11:31<01:35, 23.46it/s]

 88%|████████▊ | 16542/18769 [11:31<01:35, 23.38it/s]

 88%|████████▊ | 16545/18769 [11:31<01:35, 23.37it/s]

 88%|████████▊ | 16548/18769 [11:31<01:35, 23.32it/s]

 88%|████████▊ | 16551/18769 [11:31<01:35, 23.28it/s]

 88%|████████▊ | 16554/18769 [11:31<01:35, 23.28it/s]

 88%|████████▊ | 16557/18769 [11:31<01:34, 23.29it/s]

 88%|████████▊ | 16560/18769 [11:32<01:34, 23.29it/s]

 88%|████████▊ | 16564/18769 [11:32<01:27, 25.19it/s]

 88%|████████▊ | 16567/18769 [11:32<01:29, 24.58it/s]

 88%|████████▊ | 16570/18769 [11:32<01:30, 24.21it/s]

 88%|████████▊ | 16573/18769 [11:32<01:31, 23.95it/s]

 88%|████████▊ | 16576/18769 [11:32<01:31, 23.84it/s]

 88%|████████▊ | 16579/18769 [11:32<01:31, 23.89it/s]

 88%|████████▊ | 16582/18769 [11:32<01:31, 23.88it/s]

 88%|████████▊ | 16585/18769 [11:33<01:31, 23.88it/s]

 88%|████████▊ | 16588/18769 [11:33<01:31, 23.91it/s]

 88%|████████▊ | 16591/18769 [11:33<01:30, 23.96it/s]

 88%|████████▊ | 16594/18769 [11:33<01:30, 23.95it/s]

 88%|████████▊ | 16597/18769 [11:33<01:30, 23.96it/s]

 88%|████████▊ | 16600/18769 [11:33<01:30, 23.94it/s]

 88%|████████▊ | 16603/18769 [11:33<01:30, 24.01it/s]

 88%|████████▊ | 16606/18769 [11:33<01:30, 23.96it/s]

 88%|████████▊ | 16609/18769 [11:34<01:30, 23.96it/s]

 89%|████████▊ | 16612/18769 [11:34<01:30, 23.92it/s]

 89%|████████▊ | 16615/18769 [11:34<01:29, 23.96it/s]

 89%|████████▊ | 16618/18769 [11:34<01:29, 23.96it/s]

 89%|████████▊ | 16621/18769 [11:34<01:29, 23.98it/s]

 89%|████████▊ | 16624/18769 [11:34<01:29, 24.00it/s]

 89%|████████▊ | 16627/18769 [11:34<01:29, 23.88it/s]

 89%|████████▊ | 16630/18769 [11:34<01:29, 23.90it/s]

 89%|████████▊ | 16633/18769 [11:35<01:29, 23.87it/s]

 89%|████████▊ | 16636/18769 [11:35<01:29, 23.78it/s]

 89%|████████▊ | 16639/18769 [11:35<01:29, 23.69it/s]

 89%|████████▊ | 16642/18769 [11:35<01:29, 23.65it/s]

 89%|████████▊ | 16645/18769 [11:35<01:29, 23.63it/s]

 89%|████████▊ | 16648/18769 [11:35<01:29, 23.59it/s]

 89%|████████▊ | 16651/18769 [11:35<01:30, 23.41it/s]

 89%|████████▊ | 16654/18769 [11:35<01:30, 23.48it/s]

 89%|████████▊ | 16657/18769 [11:36<01:29, 23.51it/s]

 89%|████████▉ | 16660/18769 [11:36<01:30, 23.39it/s]

 89%|████████▉ | 16663/18769 [11:36<01:30, 23.33it/s]

 89%|████████▉ | 16666/18769 [11:36<01:29, 23.37it/s]

 89%|████████▉ | 16669/18769 [11:36<01:29, 23.36it/s]

 89%|████████▉ | 16672/18769 [11:36<01:29, 23.35it/s]

 89%|████████▉ | 16675/18769 [11:36<01:29, 23.31it/s]

 89%|████████▉ | 16678/18769 [11:37<01:29, 23.31it/s]

 89%|████████▉ | 16681/18769 [11:37<01:29, 23.27it/s]

 89%|████████▉ | 16684/18769 [11:37<01:29, 23.27it/s]

 89%|████████▉ | 16687/18769 [11:37<01:29, 23.29it/s]

 89%|████████▉ | 16690/18769 [11:37<01:29, 23.33it/s]

 89%|████████▉ | 16693/18769 [11:37<01:28, 23.33it/s]

 89%|████████▉ | 16696/18769 [11:37<01:29, 23.25it/s]

 89%|████████▉ | 16700/18769 [11:37<01:22, 24.93it/s]

 89%|████████▉ | 16703/18769 [11:38<01:24, 24.43it/s]

 89%|████████▉ | 16706/18769 [11:38<01:25, 24.10it/s]

 89%|████████▉ | 16709/18769 [11:38<01:26, 23.85it/s]

 89%|████████▉ | 16712/18769 [11:38<01:26, 23.70it/s]

 89%|████████▉ | 16715/18769 [11:38<01:26, 23.81it/s]

 89%|████████▉ | 16718/18769 [11:38<01:25, 23.86it/s]

 89%|████████▉ | 16721/18769 [11:38<01:25, 23.93it/s]

 89%|████████▉ | 16724/18769 [11:38<01:25, 23.94it/s]

 89%|████████▉ | 16727/18769 [11:39<01:25, 23.97it/s]

 89%|████████▉ | 16730/18769 [11:39<01:24, 24.03it/s]

 89%|████████▉ | 16733/18769 [11:39<01:24, 24.08it/s]

 89%|████████▉ | 16736/18769 [11:39<01:24, 24.06it/s]

 89%|████████▉ | 16739/18769 [11:39<01:24, 24.05it/s]

 89%|████████▉ | 16742/18769 [11:39<01:24, 24.06it/s]

 89%|████████▉ | 16745/18769 [11:39<01:24, 24.09it/s]

 89%|████████▉ | 16748/18769 [11:39<01:24, 23.91it/s]

 89%|████████▉ | 16751/18769 [11:40<01:24, 23.95it/s]

 89%|████████▉ | 16754/18769 [11:40<01:23, 24.00it/s]

 89%|████████▉ | 16757/18769 [11:40<01:23, 24.02it/s]

 89%|████████▉ | 16760/18769 [11:40<01:23, 24.04it/s]

 89%|████████▉ | 16763/18769 [11:40<01:24, 23.79it/s]

 89%|████████▉ | 16766/18769 [11:40<01:23, 23.88it/s]

 89%|████████▉ | 16769/18769 [11:40<01:23, 23.92it/s]

 89%|████████▉ | 16772/18769 [11:40<01:23, 23.83it/s]

 89%|████████▉ | 16775/18769 [11:41<01:23, 23.80it/s]

 89%|████████▉ | 16778/18769 [11:41<01:23, 23.75it/s]

 89%|████████▉ | 16781/18769 [11:41<01:23, 23.73it/s]

 89%|████████▉ | 16784/18769 [11:41<01:23, 23.70it/s]

 89%|████████▉ | 16787/18769 [11:41<01:23, 23.72it/s]

 89%|████████▉ | 16790/18769 [11:41<01:23, 23.77it/s]

 89%|████████▉ | 16793/18769 [11:41<01:23, 23.70it/s]

 89%|████████▉ | 16796/18769 [11:41<01:23, 23.64it/s]

 90%|████████▉ | 16799/18769 [11:42<01:23, 23.61it/s]

 90%|████████▉ | 16802/18769 [11:42<01:23, 23.60it/s]

 90%|████████▉ | 16805/18769 [11:42<01:23, 23.56it/s]

 90%|████████▉ | 16808/18769 [11:42<01:23, 23.52it/s]

 90%|████████▉ | 16811/18769 [11:42<01:23, 23.48it/s]

 90%|████████▉ | 16814/18769 [11:42<01:23, 23.47it/s]

 90%|████████▉ | 16817/18769 [11:42<01:24, 23.11it/s]

 90%|████████▉ | 16820/18769 [11:42<01:24, 23.02it/s]

 90%|████████▉ | 16823/18769 [11:43<01:24, 23.03it/s]

 90%|████████▉ | 16826/18769 [11:43<01:23, 23.17it/s]

 90%|████████▉ | 16829/18769 [11:43<01:23, 23.23it/s]

 90%|████████▉ | 16832/18769 [11:43<01:23, 23.30it/s]

 90%|████████▉ | 16835/18769 [11:43<01:22, 23.36it/s]

 90%|████████▉ | 16839/18769 [11:43<01:16, 25.21it/s]

 90%|████████▉ | 16842/18769 [11:43<01:18, 24.69it/s]

 90%|████████▉ | 16845/18769 [11:44<01:19, 24.08it/s]

 90%|████████▉ | 16848/18769 [11:44<01:20, 23.87it/s]

 90%|████████▉ | 16851/18769 [11:44<01:20, 23.89it/s]

 90%|████████▉ | 16854/18769 [11:44<01:20, 23.91it/s]

 90%|████████▉ | 16857/18769 [11:44<01:19, 23.96it/s]

 90%|████████▉ | 16860/18769 [11:44<01:19, 23.99it/s]

 90%|████████▉ | 16863/18769 [11:44<01:19, 24.01it/s]

 90%|████████▉ | 16866/18769 [11:44<01:19, 24.04it/s]

 90%|████████▉ | 16869/18769 [11:45<01:19, 24.00it/s]

 90%|████████▉ | 16872/18769 [11:45<01:19, 24.01it/s]

 90%|████████▉ | 16875/18769 [11:45<01:18, 24.02it/s]

 90%|████████▉ | 16878/18769 [11:45<01:18, 24.04it/s]

 90%|████████▉ | 16881/18769 [11:45<01:18, 24.04it/s]

 90%|████████▉ | 16884/18769 [11:45<01:18, 23.95it/s]

 90%|████████▉ | 16887/18769 [11:45<01:20, 23.49it/s]

 90%|████████▉ | 16890/18769 [11:45<01:21, 22.92it/s]

 90%|█████████ | 16893/18769 [11:46<01:21, 23.03it/s]

 90%|█████████ | 16896/18769 [11:46<01:20, 23.29it/s]

 90%|█████████ | 16899/18769 [11:46<01:19, 23.54it/s]

 90%|█████████ | 16902/18769 [11:46<01:18, 23.70it/s]

 90%|█████████ | 16905/18769 [11:46<01:18, 23.84it/s]

 90%|█████████ | 16908/18769 [11:46<01:18, 23.73it/s]

 90%|█████████ | 16911/18769 [11:46<01:18, 23.71it/s]

 90%|█████████ | 16914/18769 [11:46<01:18, 23.68it/s]

 90%|█████████ | 16917/18769 [11:47<01:18, 23.61it/s]

 90%|█████████ | 16920/18769 [11:47<01:18, 23.64it/s]

 90%|█████████ | 16923/18769 [11:47<01:17, 23.70it/s]

 90%|█████████ | 16926/18769 [11:47<01:17, 23.71it/s]

 90%|█████████ | 16929/18769 [11:47<01:17, 23.69it/s]

 90%|█████████ | 16932/18769 [11:47<01:17, 23.68it/s]

 90%|█████████ | 16935/18769 [11:47<01:17, 23.64it/s]

 90%|█████████ | 16938/18769 [11:47<01:17, 23.63it/s]

 90%|█████████ | 16941/18769 [11:48<01:18, 23.33it/s]

 90%|█████████ | 16944/18769 [11:48<01:18, 23.39it/s]

 90%|█████████ | 16947/18769 [11:48<01:17, 23.40it/s]

 90%|█████████ | 16950/18769 [11:48<01:17, 23.39it/s]

 90%|█████████ | 16953/18769 [11:48<01:17, 23.41it/s]

 90%|█████████ | 16956/18769 [11:48<01:17, 23.42it/s]

 90%|█████████ | 16959/18769 [11:48<01:17, 23.39it/s]

 90%|█████████ | 16962/18769 [11:48<01:17, 23.28it/s]

 90%|█████████ | 16965/18769 [11:49<01:17, 23.27it/s]

 90%|█████████ | 16968/18769 [11:49<01:17, 23.30it/s]

 90%|█████████ | 16971/18769 [11:49<01:17, 23.34it/s]

 90%|█████████ | 16974/18769 [11:49<01:16, 23.37it/s]

 90%|█████████ | 16978/18769 [11:49<01:10, 25.25it/s]

 90%|█████████ | 16981/18769 [11:49<01:12, 24.71it/s]

 90%|█████████ | 16984/18769 [11:49<01:13, 24.33it/s]

 91%|█████████ | 16987/18769 [11:49<01:14, 23.87it/s]

 91%|█████████ | 16990/18769 [11:50<01:14, 23.92it/s]

 91%|█████████ | 16993/18769 [11:50<01:13, 24.03it/s]

 91%|█████████ | 16996/18769 [11:50<01:13, 24.14it/s]

 91%|█████████ | 16999/18769 [11:50<01:13, 24.15it/s]

 91%|█████████ | 17002/18769 [11:50<01:13, 24.19it/s]

 91%|█████████ | 17005/18769 [11:50<01:12, 24.18it/s]

 91%|█████████ | 17008/18769 [11:50<01:12, 24.18it/s]

 91%|█████████ | 17011/18769 [11:50<01:12, 24.16it/s]

 91%|█████████ | 17014/18769 [11:51<01:12, 24.13it/s]

 91%|█████████ | 17017/18769 [11:51<01:12, 24.11it/s]

 91%|█████████ | 17020/18769 [11:51<01:12, 24.17it/s]

 91%|█████████ | 17023/18769 [11:51<01:12, 24.16it/s]

 91%|█████████ | 17026/18769 [11:51<01:12, 24.18it/s]

 91%|█████████ | 17029/18769 [11:51<01:12, 24.06it/s]

 91%|█████████ | 17032/18769 [11:51<01:12, 24.06it/s]

 91%|█████████ | 17035/18769 [11:51<01:12, 24.07it/s]

 91%|█████████ | 17038/18769 [11:52<01:11, 24.13it/s]

 91%|█████████ | 17041/18769 [11:52<01:11, 24.02it/s]

 91%|█████████ | 17044/18769 [11:52<01:11, 23.97it/s]

 91%|█████████ | 17047/18769 [11:52<01:11, 23.95it/s]

 91%|█████████ | 17050/18769 [11:52<01:11, 23.92it/s]

 91%|█████████ | 17053/18769 [11:52<01:11, 23.93it/s]

 91%|█████████ | 17056/18769 [11:52<01:11, 23.92it/s]

 91%|█████████ | 17059/18769 [11:52<01:11, 23.90it/s]

 91%|█████████ | 17062/18769 [11:53<01:12, 23.69it/s]

 91%|█████████ | 17065/18769 [11:53<01:11, 23.76it/s]

 91%|█████████ | 17068/18769 [11:53<01:11, 23.77it/s]

 91%|█████████ | 17071/18769 [11:53<01:11, 23.72it/s]

 91%|█████████ | 17074/18769 [11:53<01:11, 23.71it/s]

 91%|█████████ | 17077/18769 [11:53<01:11, 23.70it/s]

 91%|█████████ | 17080/18769 [11:53<01:11, 23.65it/s]

 91%|█████████ | 17083/18769 [11:54<01:11, 23.64it/s]

 91%|█████████ | 17086/18769 [11:54<01:11, 23.43it/s]

 91%|█████████ | 17089/18769 [11:54<01:11, 23.46it/s]

 91%|█████████ | 17092/18769 [11:54<01:11, 23.52it/s]

 91%|█████████ | 17095/18769 [11:54<01:11, 23.54it/s]

 91%|█████████ | 17098/18769 [11:54<01:10, 23.55it/s]

 91%|█████████ | 17101/18769 [11:54<01:10, 23.56it/s]

 91%|█████████ | 17104/18769 [11:54<01:10, 23.56it/s]

 91%|█████████ | 17107/18769 [11:55<01:10, 23.54it/s]

 91%|█████████ | 17110/18769 [11:55<01:10, 23.49it/s]

 91%|█████████ | 17114/18769 [11:55<01:05, 25.42it/s]

 91%|█████████ | 17117/18769 [11:55<01:06, 24.76it/s]

 91%|█████████ | 17120/18769 [11:55<01:07, 24.34it/s]

 91%|█████████ | 17123/18769 [11:55<01:08, 24.12it/s]

 91%|█████████ | 17126/18769 [11:55<01:07, 24.18it/s]

 91%|█████████▏| 17129/18769 [11:55<01:07, 24.20it/s]

 91%|█████████▏| 17132/18769 [11:56<01:07, 24.23it/s]

 91%|█████████▏| 17135/18769 [11:56<01:07, 24.18it/s]

 91%|█████████▏| 17138/18769 [11:56<01:07, 24.16it/s]

 91%|█████████▏| 17141/18769 [11:56<01:07, 24.19it/s]

 91%|█████████▏| 17144/18769 [11:56<01:07, 24.21it/s]

 91%|█████████▏| 17147/18769 [11:56<01:06, 24.22it/s]

 91%|█████████▏| 17150/18769 [11:56<01:06, 24.24it/s]

 91%|█████████▏| 17153/18769 [11:56<01:06, 24.23it/s]

 91%|█████████▏| 17156/18769 [11:57<01:06, 24.26it/s]

 91%|█████████▏| 17159/18769 [11:57<01:07, 23.99it/s]

 91%|█████████▏| 17162/18769 [11:57<01:06, 24.07it/s]

 91%|█████████▏| 17165/18769 [11:57<01:06, 24.09it/s]

 91%|█████████▏| 17168/18769 [11:57<01:06, 24.11it/s]

 91%|█████████▏| 17171/18769 [11:57<01:06, 24.12it/s]

 92%|█████████▏| 17174/18769 [11:57<01:06, 24.16it/s]

 92%|█████████▏| 17177/18769 [11:57<01:05, 24.15it/s]

 92%|█████████▏| 17180/18769 [11:58<01:05, 24.12it/s]

 92%|█████████▏| 17183/18769 [11:58<01:06, 24.00it/s]

 92%|█████████▏| 17186/18769 [11:58<01:06, 23.95it/s]

 92%|█████████▏| 17189/18769 [11:58<01:06, 23.93it/s]

 92%|█████████▏| 17192/18769 [11:58<01:06, 23.89it/s]

 92%|█████████▏| 17195/18769 [11:58<01:05, 23.86it/s]

 92%|█████████▏| 17198/18769 [11:58<01:05, 23.86it/s]

 92%|█████████▏| 17201/18769 [11:58<01:05, 23.85it/s]

 92%|█████████▏| 17204/18769 [11:59<01:05, 23.84it/s]

 92%|█████████▏| 17207/18769 [11:59<01:06, 23.54it/s]

 92%|█████████▏| 17210/18769 [11:59<01:06, 23.55it/s]

 92%|█████████▏| 17213/18769 [11:59<01:06, 23.56it/s]

 92%|█████████▏| 17216/18769 [11:59<01:06, 23.53it/s]

 92%|█████████▏| 17219/18769 [11:59<01:05, 23.52it/s]

 92%|█████████▏| 17222/18769 [11:59<01:06, 23.43it/s]

 92%|█████████▏| 17225/18769 [11:59<01:05, 23.48it/s]

 92%|█████████▏| 17228/18769 [12:00<01:05, 23.52it/s]

 92%|█████████▏| 17231/18769 [12:00<01:05, 23.46it/s]

 92%|█████████▏| 17234/18769 [12:00<01:05, 23.44it/s]

 92%|█████████▏| 17237/18769 [12:00<01:05, 23.47it/s]

 92%|█████████▏| 17240/18769 [12:00<01:05, 23.47it/s]

 92%|█████████▏| 17243/18769 [12:00<01:05, 23.47it/s]

 92%|█████████▏| 17246/18769 [12:00<01:05, 23.39it/s]

 92%|█████████▏| 17249/18769 [12:00<01:04, 23.40it/s]

 92%|█████████▏| 17253/18769 [12:01<00:59, 25.35it/s]

 92%|█████████▏| 17256/18769 [12:01<01:01, 24.54it/s]

 92%|█████████▏| 17259/18769 [12:01<01:02, 24.24it/s]

 92%|█████████▏| 17262/18769 [12:01<01:02, 24.19it/s]

 92%|█████████▏| 17265/18769 [12:01<01:02, 24.15it/s]

 92%|█████████▏| 17268/18769 [12:01<01:02, 24.20it/s]

 92%|█████████▏| 17271/18769 [12:01<01:01, 24.21it/s]

 92%|█████████▏| 17274/18769 [12:01<01:01, 24.21it/s]

 92%|█████████▏| 17277/18769 [12:02<01:01, 24.22it/s]

 92%|█████████▏| 17280/18769 [12:02<01:01, 24.02it/s]

 92%|█████████▏| 17283/18769 [12:02<01:01, 24.09it/s]

 92%|█████████▏| 17286/18769 [12:02<01:01, 24.15it/s]

 92%|█████████▏| 17289/18769 [12:02<01:01, 24.12it/s]

 92%|█████████▏| 17292/18769 [12:02<01:01, 24.17it/s]

 92%|█████████▏| 17295/18769 [12:02<01:00, 24.20it/s]

 92%|█████████▏| 17298/18769 [12:02<01:00, 24.20it/s]

 92%|█████████▏| 17301/18769 [12:03<01:00, 24.10it/s]

 92%|█████████▏| 17304/18769 [12:03<01:00, 24.05it/s]

 92%|█████████▏| 17307/18769 [12:03<01:00, 24.14it/s]

 92%|█████████▏| 17310/18769 [12:03<01:00, 24.13it/s]

 92%|█████████▏| 17313/18769 [12:03<01:00, 24.15it/s]

 92%|█████████▏| 17316/18769 [12:03<01:00, 24.16it/s]

 92%|█████████▏| 17319/18769 [12:03<01:00, 24.05it/s]

 92%|█████████▏| 17322/18769 [12:03<01:00, 24.02it/s]

 92%|█████████▏| 17325/18769 [12:04<01:00, 23.98it/s]

 92%|█████████▏| 17328/18769 [12:04<01:00, 23.66it/s]

 92%|█████████▏| 17331/18769 [12:04<01:00, 23.70it/s]

 92%|█████████▏| 17334/18769 [12:04<01:00, 23.73it/s]

 92%|█████████▏| 17337/18769 [12:04<01:00, 23.76it/s]

 92%|█████████▏| 17340/18769 [12:04<01:00, 23.78it/s]

 92%|█████████▏| 17343/18769 [12:04<01:00, 23.75it/s]

 92%|█████████▏| 17346/18769 [12:04<00:59, 23.72it/s]

 92%|█████████▏| 17349/18769 [12:05<00:59, 23.71it/s]

 92%|█████████▏| 17352/18769 [12:05<00:59, 23.68it/s]

 92%|█████████▏| 17355/18769 [12:05<00:59, 23.68it/s]

 92%|█████████▏| 17358/18769 [12:05<00:59, 23.64it/s]

 92%|█████████▏| 17361/18769 [12:05<00:59, 23.65it/s]

 93%|█████████▎| 17364/18769 [12:05<00:59, 23.65it/s]

 93%|█████████▎| 17367/18769 [12:05<00:59, 23.54it/s]

 93%|█████████▎| 17370/18769 [12:05<00:59, 23.54it/s]

 93%|█████████▎| 17373/18769 [12:06<00:59, 23.52it/s]

 93%|█████████▎| 17376/18769 [12:06<00:59, 23.44it/s]

 93%|█████████▎| 17379/18769 [12:06<00:59, 23.43it/s]

 93%|█████████▎| 17382/18769 [12:06<00:59, 23.47it/s]

 93%|█████████▎| 17385/18769 [12:06<00:58, 23.48it/s]

 93%|█████████▎| 17388/18769 [12:06<00:58, 23.51it/s]

 93%|█████████▎| 17392/18769 [12:06<00:54, 25.44it/s]

 93%|█████████▎| 17395/18769 [12:07<00:55, 24.87it/s]

 93%|█████████▎| 17398/18769 [12:07<00:55, 24.53it/s]

 93%|█████████▎| 17401/18769 [12:07<00:55, 24.43it/s]

 93%|█████████▎| 17404/18769 [12:07<00:56, 24.34it/s]

 93%|█████████▎| 17407/18769 [12:07<00:56, 24.26it/s]

 93%|█████████▎| 17410/18769 [12:07<00:56, 24.26it/s]

 93%|█████████▎| 17413/18769 [12:07<00:55, 24.25it/s]

 93%|█████████▎| 17416/18769 [12:07<00:55, 24.23it/s]

 93%|█████████▎| 17419/18769 [12:07<00:55, 24.23it/s]

 93%|█████████▎| 17422/18769 [12:08<00:55, 24.22it/s]

 93%|█████████▎| 17425/18769 [12:08<00:55, 24.18it/s]

 93%|█████████▎| 17428/18769 [12:08<00:55, 24.19it/s]

 93%|█████████▎| 17431/18769 [12:08<00:55, 24.20it/s]

 93%|█████████▎| 17434/18769 [12:08<00:55, 24.19it/s]

 93%|█████████▎| 17437/18769 [12:08<00:55, 24.20it/s]

 93%|█████████▎| 17440/18769 [12:08<00:54, 24.21it/s]

 93%|█████████▎| 17443/18769 [12:08<00:54, 24.22it/s]

 93%|█████████▎| 17446/18769 [12:09<00:54, 24.24it/s]

 93%|█████████▎| 17449/18769 [12:09<00:54, 24.03it/s]

 93%|█████████▎| 17452/18769 [12:09<00:54, 24.11it/s]

 93%|█████████▎| 17455/18769 [12:09<00:54, 24.04it/s]

 93%|█████████▎| 17458/18769 [12:09<00:54, 23.94it/s]

 93%|█████████▎| 17461/18769 [12:09<00:54, 23.92it/s]

 93%|█████████▎| 17464/18769 [12:09<00:54, 23.92it/s]

 93%|█████████▎| 17467/18769 [12:09<00:54, 23.89it/s]

 93%|█████████▎| 17470/18769 [12:10<00:54, 23.87it/s]

 93%|█████████▎| 17473/18769 [12:10<00:54, 23.86it/s]

 93%|█████████▎| 17476/18769 [12:10<00:54, 23.82it/s]

 93%|█████████▎| 17479/18769 [12:10<00:54, 23.80it/s]

 93%|█████████▎| 17482/18769 [12:10<00:54, 23.70it/s]

 93%|█████████▎| 17485/18769 [12:10<00:54, 23.66it/s]

 93%|█████████▎| 17488/18769 [12:10<00:54, 23.64it/s]

 93%|█████████▎| 17491/18769 [12:11<00:54, 23.60it/s]

 93%|█████████▎| 17494/18769 [12:11<00:54, 23.55it/s]

 93%|█████████▎| 17497/18769 [12:11<00:54, 23.47it/s]

 93%|█████████▎| 17500/18769 [12:11<00:54, 23.46it/s]

 93%|█████████▎| 17503/18769 [12:11<00:54, 23.35it/s]

 93%|█████████▎| 17506/18769 [12:11<00:54, 23.34it/s]

 93%|█████████▎| 17509/18769 [12:11<00:53, 23.33it/s]

 93%|█████████▎| 17512/18769 [12:11<00:54, 23.26it/s]

 93%|█████████▎| 17515/18769 [12:12<00:53, 23.30it/s]

 93%|█████████▎| 17518/18769 [12:12<00:53, 23.32it/s]

 93%|█████████▎| 17521/18769 [12:12<00:53, 23.29it/s]

 93%|█████████▎| 17524/18769 [12:12<00:53, 23.31it/s]

 93%|█████████▎| 17528/18769 [12:12<00:49, 25.16it/s]

 93%|█████████▎| 17531/18769 [12:12<00:50, 24.62it/s]

 93%|█████████▎| 17534/18769 [12:12<00:50, 24.25it/s]

 93%|█████████▎| 17537/18769 [12:12<00:50, 24.19it/s]

 93%|█████████▎| 17540/18769 [12:13<00:51, 24.08it/s]

 93%|█████████▎| 17543/18769 [12:13<00:50, 24.09it/s]

 93%|█████████▎| 17546/18769 [12:13<00:50, 24.04it/s]

 93%|█████████▎| 17549/18769 [12:13<00:50, 24.06it/s]

 94%|█████████▎| 17552/18769 [12:13<00:50, 24.04it/s]

 94%|█████████▎| 17555/18769 [12:13<00:50, 24.03it/s]

 94%|█████████▎| 17558/18769 [12:13<00:50, 24.07it/s]

 94%|█████████▎| 17561/18769 [12:13<00:50, 23.69it/s]

 94%|█████████▎| 17564/18769 [12:14<00:50, 23.84it/s]

 94%|█████████▎| 17567/18769 [12:14<00:50, 23.92it/s]

 94%|█████████▎| 17570/18769 [12:14<00:50, 23.75it/s]

 94%|█████████▎| 17573/18769 [12:14<00:50, 23.88it/s]

 94%|█████████▎| 17576/18769 [12:14<00:49, 23.95it/s]

 94%|█████████▎| 17579/18769 [12:14<00:49, 24.00it/s]

 94%|█████████▎| 17582/18769 [12:14<00:49, 24.08it/s]

 94%|█████████▎| 17585/18769 [12:14<00:49, 24.09it/s]

 94%|█████████▎| 17588/18769 [12:15<00:49, 24.08it/s]

 94%|█████████▎| 17591/18769 [12:15<00:48, 24.06it/s]

 94%|█████████▎| 17594/18769 [12:15<00:48, 23.99it/s]

 94%|█████████▍| 17597/18769 [12:15<00:49, 23.90it/s]

 94%|█████████▍| 17600/18769 [12:15<00:49, 23.84it/s]

 94%|█████████▍| 17603/18769 [12:15<00:48, 23.81it/s]

 94%|█████████▍| 17606/18769 [12:15<00:48, 23.83it/s]

 94%|█████████▍| 17609/18769 [12:15<00:48, 23.78it/s]

 94%|█████████▍| 17612/18769 [12:16<00:48, 23.79it/s]

 94%|█████████▍| 17615/18769 [12:16<00:48, 23.70it/s]

 94%|█████████▍| 17618/18769 [12:16<00:48, 23.59it/s]

 94%|█████████▍| 17621/18769 [12:16<00:48, 23.59it/s]

 94%|█████████▍| 17624/18769 [12:16<00:48, 23.58it/s]

 94%|█████████▍| 17627/18769 [12:16<00:48, 23.56it/s]

 94%|█████████▍| 17630/18769 [12:16<00:48, 23.54it/s]

 94%|█████████▍| 17633/18769 [12:16<00:48, 23.50it/s]

 94%|█████████▍| 17636/18769 [12:17<00:48, 23.50it/s]

 94%|█████████▍| 17639/18769 [12:17<00:48, 23.50it/s]

 94%|█████████▍| 17642/18769 [12:17<00:48, 23.45it/s]

 94%|█████████▍| 17645/18769 [12:17<00:47, 23.45it/s]

 94%|█████████▍| 17648/18769 [12:17<00:47, 23.43it/s]

 94%|█████████▍| 17651/18769 [12:17<00:47, 23.43it/s]

 94%|█████████▍| 17654/18769 [12:17<00:47, 23.42it/s]

 94%|█████████▍| 17657/18769 [12:17<00:47, 23.42it/s]

 94%|█████████▍| 17660/18769 [12:18<00:47, 23.46it/s]

 94%|█████████▍| 17663/18769 [12:18<00:47, 23.49it/s]

 94%|█████████▍| 17667/18769 [12:18<00:43, 25.38it/s]

 94%|█████████▍| 17670/18769 [12:18<00:44, 24.78it/s]

 94%|█████████▍| 17673/18769 [12:18<00:44, 24.57it/s]

 94%|█████████▍| 17676/18769 [12:18<00:44, 24.41it/s]

 94%|█████████▍| 17679/18769 [12:18<00:44, 24.30it/s]

 94%|█████████▍| 17682/18769 [12:19<00:45, 23.72it/s]

 94%|█████████▍| 17685/18769 [12:19<00:45, 23.82it/s]

 94%|█████████▍| 17688/18769 [12:19<00:45, 23.90it/s]

 94%|█████████▍| 17691/18769 [12:19<00:45, 23.94it/s]

 94%|█████████▍| 17694/18769 [12:19<00:44, 23.99it/s]

 94%|█████████▍| 17697/18769 [12:19<00:44, 23.94it/s]

 94%|█████████▍| 17700/18769 [12:19<00:44, 23.98it/s]

 94%|█████████▍| 17703/18769 [12:19<00:44, 24.05it/s]

 94%|█████████▍| 17706/18769 [12:20<00:44, 23.90it/s]

 94%|█████████▍| 17709/18769 [12:20<00:44, 23.97it/s]

 94%|█████████▍| 17712/18769 [12:20<00:44, 24.00it/s]

 94%|█████████▍| 17715/18769 [12:20<00:43, 24.04it/s]

 94%|█████████▍| 17718/18769 [12:20<00:43, 24.06it/s]

 94%|█████████▍| 17721/18769 [12:20<00:43, 24.10it/s]

 94%|█████████▍| 17724/18769 [12:20<00:43, 24.13it/s]

 94%|█████████▍| 17727/18769 [12:20<00:43, 24.18it/s]

 94%|█████████▍| 17730/18769 [12:21<00:43, 24.04it/s]

 94%|█████████▍| 17733/18769 [12:21<00:43, 23.96it/s]

 94%|█████████▍| 17736/18769 [12:21<00:43, 23.90it/s]

 95%|█████████▍| 17739/18769 [12:21<00:43, 23.85it/s]

 95%|█████████▍| 17742/18769 [12:21<00:43, 23.75it/s]

 95%|█████████▍| 17745/18769 [12:21<00:43, 23.72it/s]

 95%|█████████▍| 17748/18769 [12:21<00:42, 23.75it/s]

 95%|█████████▍| 17751/18769 [12:21<00:42, 23.77it/s]

 95%|█████████▍| 17754/18769 [12:22<00:47, 21.23it/s]

 95%|█████████▍| 17757/18769 [12:22<00:46, 21.89it/s]

 95%|█████████▍| 17760/18769 [12:22<00:45, 22.40it/s]

 95%|█████████▍| 17763/18769 [12:22<00:44, 22.72it/s]

 95%|█████████▍| 17766/18769 [12:22<00:43, 22.99it/s]

 95%|█████████▍| 17769/18769 [12:22<00:43, 23.03it/s]

 95%|█████████▍| 17772/18769 [12:22<00:43, 23.09it/s]

 95%|█████████▍| 17775/18769 [12:22<00:42, 23.19it/s]

 95%|█████████▍| 17778/18769 [12:23<00:42, 23.29it/s]

 95%|█████████▍| 17781/18769 [12:23<00:42, 23.35it/s]

 95%|█████████▍| 17784/18769 [12:23<00:42, 23.33it/s]

 95%|█████████▍| 17787/18769 [12:23<00:42, 23.33it/s]

 95%|█████████▍| 17790/18769 [12:23<00:41, 23.37it/s]

 95%|█████████▍| 17793/18769 [12:23<00:41, 23.38it/s]

 95%|█████████▍| 17796/18769 [12:23<00:41, 23.29it/s]

 95%|█████████▍| 17799/18769 [12:23<00:41, 23.29it/s]

 95%|█████████▍| 17802/18769 [12:24<00:41, 23.35it/s]

 95%|█████████▍| 17806/18769 [12:24<00:38, 25.27it/s]

 95%|█████████▍| 17809/18769 [12:24<00:38, 24.80it/s]

 95%|█████████▍| 17812/18769 [12:24<00:38, 24.57it/s]

 95%|█████████▍| 17815/18769 [12:24<00:39, 24.42it/s]

 95%|█████████▍| 17818/18769 [12:24<00:39, 24.34it/s]

 95%|█████████▍| 17821/18769 [12:24<00:38, 24.31it/s]

 95%|█████████▍| 17824/18769 [12:24<00:38, 24.24it/s]

 95%|█████████▍| 17827/18769 [12:25<00:38, 24.25it/s]

 95%|█████████▍| 17830/18769 [12:25<00:38, 24.21it/s]

 95%|█████████▌| 17833/18769 [12:25<00:38, 24.18it/s]

 95%|█████████▌| 17836/18769 [12:25<00:38, 24.19it/s]

 95%|█████████▌| 17839/18769 [12:25<00:38, 24.23it/s]

 95%|█████████▌| 17842/18769 [12:25<00:38, 24.24it/s]

 95%|█████████▌| 17845/18769 [12:25<00:38, 24.20it/s]

 95%|█████████▌| 17848/18769 [12:25<00:38, 24.19it/s]

 95%|█████████▌| 17851/18769 [12:26<00:38, 24.15it/s]

 95%|█████████▌| 17854/18769 [12:26<00:37, 24.12it/s]

 95%|█████████▌| 17857/18769 [12:26<00:37, 24.10it/s]

 95%|█████████▌| 17860/18769 [12:26<00:37, 24.11it/s]

 95%|█████████▌| 17863/18769 [12:26<00:37, 24.10it/s]

 95%|█████████▌| 17866/18769 [12:26<00:37, 24.02it/s]

 95%|█████████▌| 17869/18769 [12:26<00:37, 23.90it/s]

 95%|█████████▌| 17872/18769 [12:26<00:37, 23.82it/s]

 95%|█████████▌| 17875/18769 [12:27<00:37, 23.80it/s]

 95%|█████████▌| 17878/18769 [12:27<00:37, 23.74it/s]

 95%|█████████▌| 17881/18769 [12:27<00:37, 23.69it/s]

 95%|█████████▌| 17884/18769 [12:27<00:37, 23.65it/s]

 95%|█████████▌| 17887/18769 [12:27<00:37, 23.65it/s]

 95%|█████████▌| 17890/18769 [12:27<00:37, 23.62it/s]

 95%|█████████▌| 17893/18769 [12:27<00:37, 23.61it/s]

 95%|█████████▌| 17896/18769 [12:28<00:37, 23.58it/s]

 95%|█████████▌| 17899/18769 [12:28<00:36, 23.55it/s]

 95%|█████████▌| 17902/18769 [12:28<00:36, 23.52it/s]

 95%|█████████▌| 17905/18769 [12:28<00:37, 23.30it/s]

 95%|█████████▌| 17908/18769 [12:28<00:36, 23.30it/s]

 95%|█████████▌| 17911/18769 [12:28<00:36, 23.31it/s]

 95%|█████████▌| 17914/18769 [12:28<00:36, 23.34it/s]

 95%|█████████▌| 17917/18769 [12:28<00:36, 23.38it/s]

 95%|█████████▌| 17920/18769 [12:29<00:36, 23.37it/s]

 95%|█████████▌| 17923/18769 [12:29<00:36, 23.39it/s]

 96%|█████████▌| 17926/18769 [12:29<00:35, 23.43it/s]

 96%|█████████▌| 17929/18769 [12:29<00:35, 23.45it/s]

 96%|█████████▌| 17932/18769 [12:29<00:35, 23.46it/s]

 96%|█████████▌| 17935/18769 [12:29<00:35, 23.48it/s]

 96%|█████████▌| 17938/18769 [12:29<00:35, 23.47it/s]

 96%|█████████▌| 17942/18769 [12:29<00:32, 25.35it/s]

 96%|█████████▌| 17945/18769 [12:30<00:33, 24.77it/s]

 96%|█████████▌| 17948/18769 [12:30<00:33, 24.62it/s]

 96%|█████████▌| 17951/18769 [12:30<00:33, 24.50it/s]

 96%|█████████▌| 17954/18769 [12:30<00:33, 24.13it/s]

 96%|█████████▌| 17957/18769 [12:30<00:33, 24.15it/s]

 96%|█████████▌| 17960/18769 [12:30<00:33, 24.17it/s]

 96%|█████████▌| 17963/18769 [12:30<00:33, 24.14it/s]

 96%|█████████▌| 17966/18769 [12:30<00:33, 24.13it/s]

 96%|█████████▌| 17969/18769 [12:31<00:33, 24.09it/s]

 96%|█████████▌| 17972/18769 [12:31<00:33, 24.13it/s]

 96%|█████████▌| 17975/18769 [12:31<00:32, 24.11it/s]

 96%|█████████▌| 17978/18769 [12:31<00:32, 24.07it/s]

 96%|█████████▌| 17981/18769 [12:31<00:32, 24.09it/s]

 96%|█████████▌| 17984/18769 [12:31<00:32, 24.09it/s]

 96%|█████████▌| 17987/18769 [12:31<00:32, 24.12it/s]

 96%|█████████▌| 17990/18769 [12:31<00:32, 24.11it/s]

 96%|█████████▌| 17993/18769 [12:32<00:32, 24.12it/s]

 96%|█████████▌| 17996/18769 [12:32<00:32, 24.12it/s]

 96%|█████████▌| 17999/18769 [12:32<00:31, 24.12it/s]

 96%|█████████▌| 18002/18769 [12:32<00:32, 23.86it/s]

 96%|█████████▌| 18005/18769 [12:32<00:32, 23.83it/s]

 96%|█████████▌| 18008/18769 [12:32<00:32, 23.76it/s]

 96%|█████████▌| 18011/18769 [12:32<00:31, 23.75it/s]

 96%|█████████▌| 18014/18769 [12:32<00:31, 23.71it/s]

 96%|█████████▌| 18017/18769 [12:33<00:31, 23.61it/s]

 96%|█████████▌| 18020/18769 [12:33<00:31, 23.67it/s]

 96%|█████████▌| 18023/18769 [12:33<00:31, 23.72it/s]

 96%|█████████▌| 18026/18769 [12:33<00:31, 23.68it/s]

 96%|█████████▌| 18029/18769 [12:33<00:31, 23.61it/s]

 96%|█████████▌| 18032/18769 [12:33<00:31, 23.58it/s]

 96%|█████████▌| 18035/18769 [12:33<00:31, 23.55it/s]

 96%|█████████▌| 18038/18769 [12:33<00:31, 23.53it/s]

 96%|█████████▌| 18041/18769 [12:34<00:30, 23.52it/s]

 96%|█████████▌| 18044/18769 [12:34<00:30, 23.51it/s]

 96%|█████████▌| 18047/18769 [12:34<00:30, 23.50it/s]

 96%|█████████▌| 18050/18769 [12:34<00:30, 23.49it/s]

 96%|█████████▌| 18053/18769 [12:34<00:30, 23.47it/s]

 96%|█████████▌| 18056/18769 [12:34<00:30, 23.43it/s]

 96%|█████████▌| 18059/18769 [12:34<00:30, 23.42it/s]

 96%|█████████▌| 18062/18769 [12:34<00:30, 23.41it/s]

 96%|█████████▌| 18065/18769 [12:35<00:30, 23.42it/s]

 96%|█████████▋| 18068/18769 [12:35<00:29, 23.42it/s]

 96%|█████████▋| 18071/18769 [12:35<00:29, 23.42it/s]

 96%|█████████▋| 18074/18769 [12:35<00:30, 23.13it/s]

 96%|█████████▋| 18077/18769 [12:35<00:29, 23.21it/s]

 96%|█████████▋| 18081/18769 [12:35<00:27, 25.14it/s]

 96%|█████████▋| 18084/18769 [12:35<00:27, 24.78it/s]

 96%|█████████▋| 18087/18769 [12:36<00:27, 24.55it/s]

 96%|█████████▋| 18090/18769 [12:36<00:27, 24.41it/s]

 96%|█████████▋| 18093/18769 [12:36<00:27, 24.29it/s]

 96%|█████████▋| 18096/18769 [12:36<00:27, 24.26it/s]

 96%|█████████▋| 18099/18769 [12:36<00:27, 24.23it/s]

 96%|█████████▋| 18102/18769 [12:36<00:27, 24.18it/s]

 96%|█████████▋| 18105/18769 [12:36<00:27, 24.16it/s]

 96%|█████████▋| 18108/18769 [12:36<00:27, 24.14it/s]

 96%|█████████▋| 18111/18769 [12:36<00:27, 24.14it/s]

 97%|█████████▋| 18114/18769 [12:37<00:27, 24.11it/s]

 97%|█████████▋| 18117/18769 [12:37<00:27, 24.11it/s]

 97%|█████████▋| 18120/18769 [12:37<00:26, 24.15it/s]

 97%|█████████▋| 18123/18769 [12:37<00:27, 23.89it/s]

 97%|█████████▋| 18126/18769 [12:37<00:26, 23.94it/s]

 97%|█████████▋| 18129/18769 [12:37<00:26, 24.03it/s]

 97%|█████████▋| 18132/18769 [12:37<00:26, 24.04it/s]

 97%|█████████▋| 18135/18769 [12:37<00:26, 24.05it/s]

 97%|█████████▋| 18138/18769 [12:38<00:26, 24.10it/s]

 97%|█████████▋| 18141/18769 [12:38<00:26, 23.94it/s]

 97%|█████████▋| 18144/18769 [12:38<00:26, 23.86it/s]

 97%|█████████▋| 18147/18769 [12:38<00:26, 23.79it/s]

 97%|█████████▋| 18150/18769 [12:38<00:26, 23.72it/s]

 97%|█████████▋| 18153/18769 [12:38<00:25, 23.74it/s]

 97%|█████████▋| 18156/18769 [12:38<00:25, 23.73it/s]

 97%|█████████▋| 18159/18769 [12:39<00:25, 23.68it/s]

 97%|█████████▋| 18162/18769 [12:39<00:26, 23.26it/s]

 97%|█████████▋| 18165/18769 [12:39<00:25, 23.35it/s]

 97%|█████████▋| 18168/18769 [12:39<00:25, 23.37it/s]

 97%|█████████▋| 18171/18769 [12:39<00:25, 23.15it/s]

 97%|█████████▋| 18174/18769 [12:39<00:25, 23.24it/s]

 97%|█████████▋| 18177/18769 [12:39<00:25, 23.35it/s]

 97%|█████████▋| 18180/18769 [12:39<00:25, 23.38it/s]

 97%|█████████▋| 18183/18769 [12:40<00:25, 23.39it/s]

 97%|█████████▋| 18186/18769 [12:40<00:24, 23.41it/s]

 97%|█████████▋| 18189/18769 [12:40<00:24, 23.41it/s]

 97%|█████████▋| 18192/18769 [12:40<00:24, 23.40it/s]

 97%|█████████▋| 18195/18769 [12:40<00:24, 23.39it/s]

 97%|█████████▋| 18198/18769 [12:40<00:24, 23.45it/s]

 97%|█████████▋| 18201/18769 [12:40<00:24, 23.52it/s]

 97%|█████████▋| 18204/18769 [12:40<00:23, 23.55it/s]

 97%|█████████▋| 18207/18769 [12:41<00:23, 23.57it/s]

 97%|█████████▋| 18210/18769 [12:41<00:23, 23.59it/s]

 97%|█████████▋| 18213/18769 [12:41<00:23, 23.60it/s]

 97%|█████████▋| 18216/18769 [12:41<00:23, 23.59it/s]

 97%|█████████▋| 18220/18769 [12:41<00:21, 25.58it/s]

 97%|█████████▋| 18223/18769 [12:41<00:21, 25.16it/s]

 97%|█████████▋| 18226/18769 [12:41<00:21, 24.85it/s]

 97%|█████████▋| 18229/18769 [12:41<00:21, 24.61it/s]

 97%|█████████▋| 18232/18769 [12:42<00:21, 24.50it/s]

 97%|█████████▋| 18235/18769 [12:42<00:21, 24.43it/s]

 97%|█████████▋| 18238/18769 [12:42<00:21, 24.33it/s]

 97%|█████████▋| 18241/18769 [12:42<00:21, 24.25it/s]

 97%|█████████▋| 18244/18769 [12:42<00:21, 23.93it/s]

 97%|█████████▋| 18247/18769 [12:42<00:21, 23.91it/s]

 97%|█████████▋| 18250/18769 [12:42<00:21, 24.00it/s]

 97%|█████████▋| 18253/18769 [12:42<00:21, 23.96it/s]

 97%|█████████▋| 18256/18769 [12:43<00:21, 23.90it/s]

 97%|█████████▋| 18259/18769 [12:43<00:21, 23.88it/s]

 97%|█████████▋| 18262/18769 [12:43<00:21, 23.81it/s]

 97%|█████████▋| 18265/18769 [12:43<00:21, 23.88it/s]

 97%|█████████▋| 18268/18769 [12:43<00:21, 23.84it/s]

 97%|█████████▋| 18271/18769 [12:43<00:20, 23.90it/s]

 97%|█████████▋| 18274/18769 [12:43<00:20, 23.99it/s]

 97%|█████████▋| 18277/18769 [12:43<00:20, 23.92it/s]

 97%|█████████▋| 18280/18769 [12:44<00:20, 23.86it/s]

 97%|█████████▋| 18283/18769 [12:44<00:20, 23.80it/s]

 97%|█████████▋| 18286/18769 [12:44<00:20, 23.78it/s]

 97%|█████████▋| 18289/18769 [12:44<00:20, 23.79it/s]

 97%|█████████▋| 18292/18769 [12:44<00:20, 23.61it/s]

 97%|█████████▋| 18295/18769 [12:44<00:20, 23.63it/s]

 97%|█████████▋| 18298/18769 [12:44<00:19, 23.70it/s]

 98%|█████████▊| 18301/18769 [12:44<00:19, 23.71it/s]

 98%|█████████▊| 18304/18769 [12:45<00:19, 23.70it/s]

 98%|█████████▊| 18307/18769 [12:45<00:19, 23.64it/s]

 98%|█████████▊| 18310/18769 [12:45<00:19, 23.59it/s]

 98%|█████████▊| 18313/18769 [12:45<00:19, 23.59it/s]

 98%|█████████▊| 18316/18769 [12:45<00:19, 23.55it/s]

 98%|█████████▊| 18319/18769 [12:45<00:19, 23.51it/s]

 98%|█████████▊| 18322/18769 [12:45<00:19, 23.46it/s]

 98%|█████████▊| 18325/18769 [12:45<00:18, 23.43it/s]

 98%|█████████▊| 18328/18769 [12:46<00:19, 23.11it/s]

 98%|█████████▊| 18331/18769 [12:46<00:18, 23.15it/s]

 98%|█████████▊| 18334/18769 [12:46<00:18, 23.21it/s]

 98%|█████████▊| 18337/18769 [12:46<00:18, 23.29it/s]

 98%|█████████▊| 18340/18769 [12:46<00:18, 23.11it/s]

 98%|█████████▊| 18343/18769 [12:46<00:18, 23.22it/s]

 98%|█████████▊| 18346/18769 [12:46<00:18, 23.34it/s]

 98%|█████████▊| 18349/18769 [12:47<00:17, 23.40it/s]

 98%|█████████▊| 18352/18769 [12:47<00:17, 23.36it/s]

 98%|█████████▊| 18356/18769 [12:47<00:16, 25.26it/s]

 98%|█████████▊| 18359/18769 [12:47<00:16, 24.92it/s]

 98%|█████████▊| 18362/18769 [12:47<00:16, 24.64it/s]

 98%|█████████▊| 18365/18769 [12:47<00:16, 24.49it/s]

 98%|█████████▊| 18368/18769 [12:47<00:16, 24.38it/s]

 98%|█████████▊| 18371/18769 [12:47<00:16, 24.34it/s]

 98%|█████████▊| 18374/18769 [12:48<00:16, 24.30it/s]

 98%|█████████▊| 18377/18769 [12:48<00:16, 24.24it/s]

 98%|█████████▊| 18380/18769 [12:48<00:16, 24.21it/s]

 98%|█████████▊| 18383/18769 [12:48<00:15, 24.16it/s]

 98%|█████████▊| 18386/18769 [12:48<00:15, 24.18it/s]

 98%|█████████▊| 18389/18769 [12:48<00:15, 23.97it/s]

 98%|█████████▊| 18392/18769 [12:48<00:15, 24.02it/s]

 98%|█████████▊| 18395/18769 [12:48<00:15, 24.09it/s]

 98%|█████████▊| 18398/18769 [12:49<00:15, 24.13it/s]

 98%|█████████▊| 18401/18769 [12:49<00:15, 24.16it/s]

 98%|█████████▊| 18404/18769 [12:49<00:15, 24.22it/s]

 98%|█████████▊| 18407/18769 [12:49<00:14, 24.25it/s]

 98%|█████████▊| 18410/18769 [12:49<00:14, 24.24it/s]

 98%|█████████▊| 18413/18769 [12:49<00:14, 24.16it/s]

 98%|█████████▊| 18416/18769 [12:49<00:14, 24.04it/s]

 98%|█████████▊| 18419/18769 [12:49<00:14, 23.98it/s]

 98%|█████████▊| 18422/18769 [12:50<00:14, 23.92it/s]

 98%|█████████▊| 18425/18769 [12:50<00:14, 23.94it/s]

 98%|█████████▊| 18428/18769 [12:50<00:14, 23.95it/s]

 98%|█████████▊| 18431/18769 [12:50<00:14, 23.97it/s]

 98%|█████████▊| 18434/18769 [12:50<00:13, 23.95it/s]

 98%|█████████▊| 18437/18769 [12:50<00:14, 23.66it/s]

 98%|█████████▊| 18440/18769 [12:50<00:13, 23.69it/s]

 98%|█████████▊| 18443/18769 [12:50<00:13, 23.74it/s]

 98%|█████████▊| 18446/18769 [12:51<00:13, 23.75it/s]

 98%|█████████▊| 18449/18769 [12:51<00:13, 23.73it/s]

 98%|█████████▊| 18452/18769 [12:51<00:13, 23.75it/s]

 98%|█████████▊| 18455/18769 [12:51<00:13, 23.71it/s]

 98%|█████████▊| 18458/18769 [12:51<00:13, 23.74it/s]

 98%|█████████▊| 18461/18769 [12:51<00:12, 23.70it/s]

 98%|█████████▊| 18464/18769 [12:51<00:12, 23.71it/s]

 98%|█████████▊| 18467/18769 [12:51<00:12, 23.67it/s]

 98%|█████████▊| 18470/18769 [12:52<00:12, 23.66it/s]

 98%|█████████▊| 18473/18769 [12:52<00:12, 23.67it/s]

 98%|█████████▊| 18476/18769 [12:52<00:12, 23.67it/s]

 98%|█████████▊| 18479/18769 [12:52<00:12, 23.66it/s]

 98%|█████████▊| 18482/18769 [12:52<00:12, 23.69it/s]

 98%|█████████▊| 18485/18769 [12:52<00:12, 23.46it/s]

 99%|█████████▊| 18488/18769 [12:52<00:11, 23.54it/s]

 99%|█████████▊| 18491/18769 [12:52<00:11, 23.56it/s]

 99%|█████████▊| 18495/18769 [12:53<00:10, 25.51it/s]

 99%|█████████▊| 18498/18769 [12:53<00:10, 25.06it/s]

 99%|█████████▊| 18501/18769 [12:53<00:10, 24.80it/s]

 99%|█████████▊| 18504/18769 [12:53<00:10, 24.63it/s]

 99%|█████████▊| 18507/18769 [12:53<00:10, 24.47it/s]

 99%|█████████▊| 18510/18769 [12:53<00:10, 24.33it/s]

 99%|█████████▊| 18513/18769 [12:53<00:10, 24.28it/s]

 99%|█████████▊| 18516/18769 [12:53<00:10, 24.25it/s]

 99%|█████████▊| 18519/18769 [12:54<00:10, 24.27it/s]

 99%|█████████▊| 18522/18769 [12:54<00:10, 24.27it/s]

 99%|█████████▊| 18525/18769 [12:54<00:10, 24.29it/s]

 99%|█████████▊| 18528/18769 [12:54<00:09, 24.29it/s]

 99%|█████████▊| 18531/18769 [12:54<00:09, 24.31it/s]

 99%|█████████▊| 18534/18769 [12:54<00:09, 24.06it/s]

 99%|█████████▉| 18537/18769 [12:54<00:09, 24.08it/s]

 99%|█████████▉| 18540/18769 [12:54<00:09, 24.15it/s]

 99%|█████████▉| 18543/18769 [12:55<00:09, 24.19it/s]

 99%|█████████▉| 18546/18769 [12:55<00:09, 24.22it/s]

 99%|█████████▉| 18549/18769 [12:55<00:09, 24.25it/s]

 99%|█████████▉| 18552/18769 [12:55<00:08, 24.25it/s]

 99%|█████████▉| 18555/18769 [12:55<00:08, 24.23it/s]

 99%|█████████▉| 18558/18769 [12:55<00:08, 24.00it/s]

 99%|█████████▉| 18561/18769 [12:55<00:08, 24.05it/s]

 99%|█████████▉| 18564/18769 [12:55<00:08, 24.08it/s]

 99%|█████████▉| 18567/18769 [12:56<00:08, 24.14it/s]

 99%|█████████▉| 18570/18769 [12:56<00:08, 24.15it/s]

 99%|█████████▉| 18573/18769 [12:56<00:08, 24.14it/s]

 99%|█████████▉| 18576/18769 [12:56<00:07, 24.16it/s]

 99%|█████████▉| 18579/18769 [12:56<00:07, 24.19it/s]

 99%|█████████▉| 18582/18769 [12:56<00:07, 24.17it/s]

 99%|█████████▉| 18585/18769 [12:56<00:07, 24.15it/s]

 99%|█████████▉| 18588/18769 [12:56<00:07, 24.18it/s]

 99%|█████████▉| 18591/18769 [12:57<00:07, 24.23it/s]

 99%|█████████▉| 18594/18769 [12:57<00:07, 24.25it/s]

 99%|█████████▉| 18597/18769 [12:57<00:07, 24.23it/s]

 99%|█████████▉| 18600/18769 [12:57<00:06, 24.24it/s]

 99%|█████████▉| 18603/18769 [12:57<00:06, 24.19it/s]

 99%|█████████▉| 18606/18769 [12:57<00:06, 23.99it/s]

 99%|█████████▉| 18609/18769 [12:57<00:06, 24.02it/s]

 99%|█████████▉| 18612/18769 [12:57<00:06, 24.06it/s]

 99%|█████████▉| 18615/18769 [12:58<00:06, 24.12it/s]

 99%|█████████▉| 18618/18769 [12:58<00:06, 24.13it/s]

 99%|█████████▉| 18621/18769 [12:58<00:06, 24.13it/s]

 99%|█████████▉| 18624/18769 [12:58<00:05, 24.17it/s]

 99%|█████████▉| 18627/18769 [12:58<00:05, 24.19it/s]

 99%|█████████▉| 18630/18769 [12:58<00:05, 24.23it/s]

 99%|█████████▉| 18634/18769 [12:58<00:05, 26.15it/s]

 99%|█████████▉| 18637/18769 [12:58<00:05, 25.57it/s]

 99%|█████████▉| 18640/18769 [12:59<00:05, 25.17it/s]

 99%|█████████▉| 18643/18769 [12:59<00:05, 24.91it/s]

 99%|█████████▉| 18646/18769 [12:59<00:04, 24.67it/s]

 99%|█████████▉| 18649/18769 [12:59<00:04, 24.53it/s]

 99%|█████████▉| 18652/18769 [12:59<00:04, 24.42it/s]

 99%|█████████▉| 18655/18769 [12:59<00:04, 24.36it/s]

 99%|█████████▉| 18658/18769 [12:59<00:04, 24.12it/s]

 99%|█████████▉| 18661/18769 [12:59<00:04, 24.18it/s]

 99%|█████████▉| 18664/18769 [13:00<00:04, 24.20it/s]

 99%|█████████▉| 18667/18769 [13:00<00:04, 24.16it/s]

 99%|█████████▉| 18670/18769 [13:00<00:04, 24.17it/s]

 99%|█████████▉| 18673/18769 [13:00<00:03, 24.18it/s]

100%|█████████▉| 18676/18769 [13:00<00:03, 24.20it/s]

100%|█████████▉| 18679/18769 [13:00<00:03, 24.17it/s]

100%|█████████▉| 18682/18769 [13:00<00:03, 23.98it/s]

100%|█████████▉| 18685/18769 [13:00<00:03, 24.06it/s]

100%|█████████▉| 18688/18769 [13:01<00:03, 24.16it/s]

100%|█████████▉| 18691/18769 [13:01<00:03, 24.23it/s]

100%|█████████▉| 18694/18769 [13:01<00:03, 24.29it/s]

100%|█████████▉| 18697/18769 [13:01<00:02, 24.29it/s]

100%|█████████▉| 18700/18769 [13:01<00:02, 24.30it/s]

100%|█████████▉| 18703/18769 [13:01<00:02, 24.34it/s]

100%|█████████▉| 18706/18769 [13:01<00:02, 24.31it/s]

100%|█████████▉| 18709/18769 [13:01<00:02, 24.33it/s]

100%|█████████▉| 18712/18769 [13:01<00:02, 24.31it/s]

100%|█████████▉| 18715/18769 [13:02<00:02, 24.33it/s]

100%|█████████▉| 18718/18769 [13:02<00:02, 24.29it/s]

100%|█████████▉| 18721/18769 [13:02<00:01, 24.28it/s]

100%|█████████▉| 18724/18769 [13:02<00:01, 24.28it/s]

100%|█████████▉| 18727/18769 [13:02<00:01, 24.31it/s]

100%|█████████▉| 18730/18769 [13:02<00:01, 24.12it/s]

100%|█████████▉| 18733/18769 [13:02<00:01, 24.17it/s]

100%|█████████▉| 18736/18769 [13:02<00:01, 24.20it/s]

100%|█████████▉| 18739/18769 [13:03<00:01, 24.13it/s]

100%|█████████▉| 18742/18769 [13:03<00:01, 24.16it/s]

100%|█████████▉| 18745/18769 [13:03<00:00, 24.27it/s]

100%|█████████▉| 18748/18769 [13:03<00:00, 24.30it/s]

100%|█████████▉| 18751/18769 [13:03<00:00, 24.32it/s]

100%|█████████▉| 18754/18769 [13:03<00:00, 24.31it/s]

100%|█████████▉| 18757/18769 [13:03<00:00, 24.31it/s]

100%|█████████▉| 18760/18769 [13:03<00:00, 24.33it/s]

100%|█████████▉| 18763/18769 [13:04<00:00, 24.36it/s]

100%|█████████▉| 18766/18769 [13:04<00:00, 24.36it/s]

100%|██████████| 18769/18769 [13:04<00:00, 23.93it/s]

In [21]:
res_df

,Column Configuration,Differentia Bit Width,Stratum Retention Policy,Stratum Retention Policy Resolution Parameter,Stratigraphic Column Expected Retained Bits,Stratigraphic Column Mean Actual Retained Bits,Stratigraphic Column Target Retained Bits,Stratigraphic Column Expected Retained Bits Error,Stratigraphic Column Actual Num Retained Strata,Taxon Compared From,Taxon Compared To,Generation of Taxon Compared From,Generation of Taxon Compared To,Generation Of MRCA Lower Bound (inclusive),Generation Of MRCA Upper Bound (exclusive),MRCA Bound Confidence,Rank of Earliest Detectable Mrca With
0,actual_bits=63+actual_strata=63+bits_error=-1+...,1,TaperedDepthProportionalResolution,31,63,63.000000,64,-1,63,286082,286081,3001,3001,2880,3001,0.968750,256
1,actual_bits=56+actual_strata=7+bits_error=-8+d...,8,TaperedDepthProportionalResolution,3,56,56.000000,64,-8,7,286082,286081,3001,3001,2560,3000,0.996094,0
2,actual_bits=192+actual_strata=3+bits_error=128...,64,TaperedDepthProportionalResolution,1,192,192.000000,64,128,3,286082,286081,3001,3001,2048,3000,1.000000,0
3,actual_bits=511+actual_strata=511+bits_error=-...,1,TaperedDepthProportionalResolution,255,511,510.226277,512,-1,511,286082,286081,3001,3001,2972,2992,0.968750,32
4,actual_bits=504+actual_strata=63+bits_error=-8...,8,TaperedDepthProportionalResolution,31,504,504.000000,512,-8,63,286082,286081,3001,3001,2976,3000,0.996094,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
335371,actual_bits=456+actual_strata=57+bits_error=-5...,8,RecencyProportionalResolution,5,456,450.919708,512,-56,57,286033,285894,3001,3000,2980,2982,0.996094,0
335372,actual_bits=576+actual_strata=9+bits_error=64+...,64,RecencyProportionalResolution,0,576,535.357664,512,64,9,286033,285894,3001,3000,2976,2992,1.000000,0
335373,actual_bits=2999+actual_strata=2999+bits_error...,1,RecencyProportionalResolution,2999,2999,3000.532847,4096,-1097,2999,286033,285894,3001,3000,2979,2984,0.968750,4
335374,actual_bits=4096+actual_strata=512+bits_error=...,8,RecencyProportionalResolution,83,4096,4090.919708,4096,0,512,286033,285894,3001,3000,2981,2982,0.996094,0
335375,actual_bits=3648+actual_strata=57+bits_error=-...,64,RecencyProportionalResolution,5,3648,3607.357664,4096,-448,57,286033,285894,3001,3000,2980,2982,1.000000,0

In [22]:
nbm.print_dataframe_synopsis(res_df)

digest: ee5a6c49fffb1e477caab78758d0a885c247cabadd6c367719fd684f129bfa29
manifest:
  Column Configuration: '                              18#   ex., actual_bits=63+actual_strata=63+bits_error=-1+differentia=1+policy=TaperedDepthProportionalResolution+resolution=31+target_bits=64'
  Differentia Bit Width: '                             3#    ex., 1'
  Generation Of MRCA Lower Bound (inclusive): '        47#   ex., 2880'
  Generation Of MRCA Upper Bound (exclusive): '        29#   ex., 3001'
  Generation of Taxon Compared From: '                 7#    ex., 3001'
  Generation of Taxon Compared To: '                   7#    ex., 3001'
  MRCA Bound Confidence: '                             3#    ex., 0.96875'
  Rank of Earliest Detectable Mrca With: '             6#    ex., 256'
  Stratigraphic Column Actual Num Retained Strata: '   8#    ex., 63'
  Stratigraphic Column Expected Retained Bits: '       16#   ex., 63'
  Stratigraphic Column Expected Retained Bits Error: ' 12#   ex., -1'
  Stratigraphic Column Mean Actual Retained Bits: '    16#   ex., 63.0'
  Stratigraphic Column Target Retained Bits: '         3#    ex., 64'
  Stratum Retention Policy: '                          2#    ex., TaperedDepthProportionalResolution'
  Stratum Retention Policy Resolution Parameter: '     8#    ex., 31'
  Taxon Compared From: '                               137#  ex., 286082'
  Taxon Compared To: '                                 137#  ex., 286081'
num cols: 17
num cols all na: 0
num cols any na: 0
num na: 0
num rows: 335376
num rows all na: 0
num rows any na: 0
size: 225M

# Save Pairwise MRCA Estimates to File

In [23]:
res_df.to_csv(
    f'a=pairwise_mrca_estimates+source={data_filename}.gz',
    compression='gzip',
)
res_df.to_csv(
    f'a=pairwise_mrca_estimates+source={data_filename}',
)