In [1]:
import endomill
from nbmetalog import nbmetalog as nbm

In [2]:
nbm.print_metadata()

context: ci
hostname: f300977a64bd
interpreter: 3.8.10 (default, Nov 22 2023, 10:22:35)  [GCC 9.4.0]
nbcellexec: 2
nbname: phylogeny_simulation_mill
nbpath: /opt/hereditary-stratigraph-concept/binder/phylogenetic-inference/phylogeny_simulation_mill.ipynb
revision: null
session: 0020b03d-a786-45e2-a8c2-dc78d2435f7f
timestamp: 2024-04-07T00:40:01Z00:00


IPython==7.16.1
keyname==0.4.1
yaml==5.3.1
endomill==0.1.3
nbmetalog==0.2.6
re==2.2.1
ipython_genutils==0.2.0
logging==0.5.1.2
zmq==22.3.0
json==2.0.9
ipykernel==5.5.3

In [3]:
endomill.instantiate_over(
    parameter_packs=[
        {
            'data_url': data_url,
            'data_filename': data_filename,
        }
        for data_filename, data_url in [
            (
                'nk_ecoeaselection_seed110_pop100_mut.01_snapshot_3000.csv',
                'https://osf.io/5d3be/',
            ),
            (
                'nk_lexicaseselection_seed110_pop165_mut.01_snapshot_500.csv',
                'https://osf.io/8ycq7/',
            ),
            (
                'nk_randomselection_seed7_pop100_mut.01_snapshot_5000.csv',
                'https://osf.io/ydxt7/',
            ),
            (
                'nk_sharingselection_seed10_pop100_mut.01_snapshot_5000.csv',
                'https://osf.io/cz9fk/',
            ),
            (
                'nk_tournamentselection_seed140_pop100_mut.01_snapshot_5000.csv',
                'https://osf.io/5ubn8/',
            )
        ]
    ],
)

detected executing.endomill.ipynb file
skipping instantiate_over

In [4]:
# define papermill parameters
data_url: str
data_filename: str

In [5]:
# Parameters
data_url = "https://osf.io/cz9fk/"
data_filename = "nk_sharingselection_seed10_pop100_mut.01_snapshot_5000.csv"

In [6]:
import anytree
from bs4 import BeautifulSoup
from collections import defaultdict
from hstrat import hstrat
from interval_search import doubling_search
from iterpop import iterpop as ip
import itertools as it
from keyname import keyname as kn
import numpy as np
import opytional as opyt
import pandas as pd
import random
import sys
from tqdm import tqdm
from urllib import request

In [7]:
random.seed(1) # ensure reproducibility
sys.setrecursionlimit(100000) # anytree exceeds default recursion limit on our data

In [8]:
from nbmetalog import nbmetalog as nbm
nbm.print_metadata()

context: ci
hostname: f300977a64bd
interpreter: 3.8.10 (default, Nov 22 2023, 10:22:35)  [GCC 9.4.0]
nbcellexec: 8
nbname: phylogeny_simulation_mill
nbpath: /opt/hereditary-stratigraph-concept/binder/phylogenetic-inference/phylogeny_simulation_mill.ipynb
revision: null
session: 0020b03d-a786-45e2-a8c2-dc78d2435f7f
timestamp: 2024-04-07T00:40:01Z00:00


IPython==7.16.1
endomill==0.1.3
ipykernel==5.5.3
ipython_genutils==0.2.0
json==2.0.9
keyname==0.4.1
logging==0.5.1.2
nbmetalog==0.2.6
re==2.2.1
yaml==5.3.1
zmq==22.3.0
anytree==2.8.0
hstrat==0.3.2
iterpop==0.4.0
numpy==1.21.5
opytional==0.1.0
pandas==2.0.3

In [9]:
endomill.add_instance_outpath(
    f'a=phylogeny_simulation+source={data_filename}.endomill.ipynb',
)

# Retrieve Target Phylogeny from OSF

In [10]:
target_phylogeny_df = pd.read_csv(
    f'{data_url}/download',
)

nbm.print_dataframe_synopsis(target_phylogeny_df)

digest: eb5c427177485bfdabc5055e6a2eff557af995416bcd8a6165cf3c9fb86b3f04
manifest:
  ancestor_list: '    3241#  ex., [316428]'
  depth: '            3048#  ex., 3042'
  destruction_time: ' 2547#  ex., inf'
  id: '               3313#  ex., 316653'
  num_offspring: '    6#     ex., 0'
  num_orgs: '         3#     ex., 1'
  origin_time: '      3057#  ex., 5000'
  phenotype: '        3297#  ex., [ 0.600023 0.795695 0.965585 0.391101 0.863194 0.982911
    0.43849 0.470596 0.690861 0.73147 0.936691 0.993888 0.891655 0.889409 0.120467
    0.918155 0.649416 0.985481 0.545775 0.298241 0.0437687 0.00350497 0.882206 0.411082
    0.641201 0.171095 0.713238 0.633266 0.28839 0.159282 0.854242 0.975637 0.947336
    0.949524 0.970265 0.26913 0.342512 0.973407 0.68399 0.507257 0.897186 0.263287
    0.611318 0.628408 0.961238 0.395228 0.281177 0.992705 0.577607 0.00370154 0.582243
    0.242543 0.0358797 0.847181 0.0894643 0.492351 0.713603 0.176921 0.459707 0.661723
    0.478606 0.402292 0.69406 0.437268 0.369061 0.0575504 0.973395 0.667286 0.844737
    0.893853 0.821753 0.93823 0.00185849 0.353298 0.711089 0.488041 0.47589 0.496097
    0.0305838 0.751224 0.139532 0.801073 0.283332 0.905512 0.383913 0.622401 0.872785
    0.491975 0.611419 0.889081 0.691663 0.415139 0.993533 0.456529 0.238585 0.305074
    0.980006 0.839736 0.858255 0.83839 0.609048 0.985491 0.540334 0.794705 0.267969
    0.950693 0.481515 0.86484 0.335679 0.556956 0.802243 0.919962 0.599126 0.549362
    0.502464 0.999716 0.150077 0.641708 0.355093 0.906703 0.559155 0.187845 0.220546
    0.98075 0.774822 0.627027 0.986346 0.32117 0.820058 0.829237 0.599416 0.133963
    0.561524 0.54154 0.0387326 0.499079 0.578324 0.201001 0.694904 0.684175 0.760845
    0.417248 0.757352 0.88265 0.876087 0.791392 0.163295 0.842781 0.905466 0.535074
    0.557476 0.159216 0.930153 0.993369 0.161186 0.269624 0.723977 0.896475 0.408876
    0.110413 0.894564 0.143454 0.853905 0.605213 0.2938 0.880745 0.380635 0.00117603
    0.484501 0.0376294 0.122365 0.0332639 0.521317 0.995499 0.070027 0.939414 0.642372
    0.750248 0.713292 0.897311 0.0499372 0.11574 0.481757 0.337829 0.0147815 0.775276
    0.605081 0.231544 0.770302 0.320008 0.143194 0.564844 0.823918 0.968807 0.756002
    0.12325 0.373133 0.611552 0.114399 0.0265516 ]'
  tot_orgs: '         14#    ex., 1'
  total_offspring: '  24#    ex., 0'
num cols: 10
num cols all na: 0
num cols any na: 0
num na: 0
num rows: 3313
num rows all na: 0
num rows any na: 0
size: 6M

# Create a Tree with Target Phylogeny Structure

In [11]:
# map id to anytree node
nodes = defaultdict(anytree.AnyNode)
for __, row in target_phylogeny_df.iterrows():
    node = nodes[row['id']]
    node.id = row['id']
    node.origin_time = row['origin_time']
    if 'NONE' not in row['ancestor_list']:
        ancestor_id = ip.popsingleton(
            eval(row['ancestor_list'])
        )
        node.parent = nodes[ancestor_id]

roots = {node.root for node in nodes.values()}

In [12]:
root = ip.popsingleton(roots)
root.height

3047

In [13]:
max_origin_time = target_phylogeny_df['origin_time'].max()
max_origin_time

5000

In [14]:
mean_leaf_origin_time = np.mean([
    leaf.origin_time
    for leaf in root.leaves
])
mean_leaf_origin_time

4999.890410958904

# Pick Parameters for Hereditary Stratigraphic Columns

In [15]:
def make_conditions(num_generations: int) -> pd.DataFrame:
    res = []
    for condemner_factory, target_column_bits, differentia_bit_width in it.product(
        [
            hstrat.StratumRetentionCondemnerTaperedDepthProportionalResolution,
            hstrat.StratumRetentionCondemnerRecencyProportionalResolution,
        ],
        [
            64,
            64 * 8,
            64 * 64,
        ],
        [
            1,
            8,
            64,
        ],
    ):
        policy_param = doubling_search(
            lambda x: \
                condemner_factory(x + 1).CalcNumStrataRetainedExact(num_generations)
                * differentia_bit_width > target_column_bits or x >= num_generations,
            {
                hstrat.StratumRetentionCondemnerTaperedDepthProportionalResolution: 1,
                hstrat.StratumRetentionCondemnerRecencyProportionalResolution: 0,
            }[condemner_factory],
        )

        actual_column_strata = condemner_factory(policy_param).CalcNumStrataRetainedExact(num_generations)
        actual_column_bits = actual_column_strata * differentia_bit_width

        res.append({
            'Retention Policy' : condemner_factory.__name__[25:],
            'Differentia Bit Width' : differentia_bit_width,
            'Retention Policy Resolution Parameter' : policy_param,
            'Target Retained Bits' : target_column_bits,
            'Actual Retained Bits' : actual_column_bits,
            'Retained Bits Error' : actual_column_bits - target_column_bits,
            'Actual Retained Strata' : actual_column_strata,
            'condemner' : condemner_factory(policy_param),
        })
    return pd.DataFrame.from_records(res)

In [16]:
conditions_df = make_conditions(int(mean_leaf_origin_time))
conditions_df.drop('condemner', axis=1)

,Retention Policy,Differentia Bit Width,Retention Policy Resolution Parameter,Target Retained Bits,Actual Retained Bits,Retained Bits Error,Actual Retained Strata
0,TaperedDepthProportionalResolution,1,31,64,63,-1,63
1,TaperedDepthProportionalResolution,8,3,64,56,-8,7
2,TaperedDepthProportionalResolution,64,1,64,192,128,3
3,TaperedDepthProportionalResolution,1,255,512,511,-1,511
4,TaperedDepthProportionalResolution,8,31,512,504,-8,63
5,TaperedDepthProportionalResolution,64,3,512,448,-64,7
6,TaperedDepthProportionalResolution,1,2048,4096,4096,0,4096
7,TaperedDepthProportionalResolution,8,255,4096,4088,-8,511
8,TaperedDepthProportionalResolution,64,31,4096,4032,-64,63
9,RecencyProportionalResolution,1,5,64,59,-5,59
10,RecencyProportionalResolution,8,0,64,56,-8,7
11,RecencyProportionalResolution,64,0,64,448,384,7
12,RecencyProportionalResolution,1,71,512,507,-5,507
13,RecencyProportionalResolution,8,5,512,472,-40,59
14,RecencyProportionalResolution,64,0,512,448,-64,7
15,RecencyProportionalResolution,1,1596,4096,4096,0,4096
16,RecencyProportionalResolution,8,71,4096,4056,-40,507
17,RecencyProportionalResolution,64,5,4096,3776,-320,59

# Set Up Ancestor Column

In [17]:
bundle = hstrat.HereditaryStratigraphicColumnBundle({
    kn.pack({
        'differentia' : row['Differentia Bit Width'],
        'policy' : row['Retention Policy'],
        'resolution' : row['Retention Policy Resolution Parameter'],
        'target_bits' : row['Target Retained Bits'],
        'actual_bits' : row['Actual Retained Bits'],
        'bits_error' : row['Retained Bits Error'],
        'actual_strata' : row['Actual Retained Strata'],
    }) \
        : hstrat.HereditaryStratigraphicColumn(
            stratum_differentia_bit_width=row['Differentia Bit Width'],
            stratum_retention_condemner=row['condemner'],
    )
    for __, row in conditions_df.iterrows()
})

# Simulate Inheritance of Ancestor Column Down Phylogenetic Tree

In [18]:
root = ip.popsingleton(roots)
root.hstrat_column = bundle

for node in anytree.LevelOrderIter(ip.popsingleton(roots)):
    parent = node.parent
    if parent is not None:
        node.hstrat_column = parent.hstrat_column.Clone()
        for __ in range(node.origin_time - parent.origin_time): node.hstrat_column.DepositStratum()

# Extract Pairwise MRCA Estimates for Extant Organisms

In [19]:
# impl -> mean retained bits
mean_retained_bits = {
    impl: np.mean([
        node.hstrat_column.GetNumStrataRetained()[impl]
        * int(kn.unpack(impl)['differentia'])
        for node in root.leaves
    ])
    for impl in bundle
}

records = [
    {
        **{
            'Mean Actual Retained Bits': v,
        },
        **kn.unpack(k)
    }
    for k, v in mean_retained_bits.items()
]
actual_retained_bits_df = pd.DataFrame.from_records(records)
actual_retained_bits_df.to_csv(
    f'a=actual_retained_bits+source={data_filename}',
)

actual_retained_bits_df

,Mean Actual Retained Bits,actual_bits,actual_strata,bits_error,differentia,policy,resolution,target_bits,_
0,63.000000,63,63,-1,1,TaperedDepthProportionalResolution,31,64,actual_bits=63+actual_strata=63+bits_error=-1+...
1,56.000000,56,7,-8,8,TaperedDepthProportionalResolution,3,64,actual_bits=56+actual_strata=7+bits_error=-8+d...
2,192.000000,192,3,128,64,TaperedDepthProportionalResolution,1,64,actual_bits=192+actual_strata=3+bits_error=128...
3,510.095890,511,511,-1,1,TaperedDepthProportionalResolution,255,512,actual_bits=511+actual_strata=511+bits_error=-...
4,504.000000,504,63,-8,8,TaperedDepthProportionalResolution,31,512,actual_bits=504+actual_strata=63+bits_error=-8...
5,448.000000,448,7,-64,64,TaperedDepthProportionalResolution,3,512,actual_bits=448+actual_strata=7+bits_error=-64...
6,4096.000000,4096,4096,0,1,TaperedDepthProportionalResolution,2048,4096,actual_bits=4096+actual_strata=4096+bits_error...
7,4080.767123,4088,511,-8,8,TaperedDepthProportionalResolution,255,4096,actual_bits=4088+actual_strata=511+bits_error=...
8,4032.000000,4032,63,-64,64,TaperedDepthProportionalResolution,31,4096,actual_bits=4032+actual_strata=63+bits_error=-...
9,58.178082,59,59,-5,1,RecencyProportionalResolution,5,64,actual_bits=59+actual_strata=59+bits_error=-5+...
10,49.424658,56,7,-8,8,RecencyProportionalResolution,0,64,actual_bits=56+actual_strata=7+bits_error=-8+d...
11,395.397260,448,7,384,64,RecencyProportionalResolution,0,64,actual_bits=448+actual_strata=7+bits_error=384...
12,506.178082,507,507,-5,1,RecencyProportionalResolution,71,512,actual_bits=507+actual_strata=507+bits_error=-...
13,465.424658,472,59,-40,8,RecencyProportionalResolution,5,512,actual_bits=472+actual_strata=59+bits_error=-4...
14,395.397260,448,7,-64,64,RecencyProportionalResolution,0,512,actual_bits=448+actual_strata=7+bits_error=-64...
15,4096.986301,4096,4096,0,1,RecencyProportionalResolution,1596,4096,actual_bits=4096+actual_strata=4096+bits_error...
16,4049.424658,4056,507,-40,8,RecencyProportionalResolution,71,4096,actual_bits=4056+actual_strata=507+bits_error=...
17,3723.397260,3776,59,-320,64,RecencyProportionalResolution,5,4096,actual_bits=3776+actual_strata=59+bits_error=-...

In [20]:
res = []
for extant1, extant2 in tqdm([*it.product(root.leaves, root.leaves)]):
    if extant1 != extant2:
        bounds = extant1.hstrat_column.CalcRankOfMrcaBoundsWith(extant2.hstrat_column)
        for impl in extant1.hstrat_column:
            res.append({
                'Column Configuration' \
                    : impl,
                'Differentia Bit Width' \
                    : kn.unpack(impl)['differentia'],
                'Stratum Retention Policy' \
                    : kn.unpack(impl)['policy'],
                'Stratum Retention Policy Resolution Parameter' \
                    : kn.unpack(impl)['resolution'],
                'Stratigraphic Column Expected Retained Bits' \
                    : kn.unpack(impl)['actual_bits'],
                'Stratigraphic Column Mean Actual Retained Bits' \
                    : mean_retained_bits[impl],
                'Stratigraphic Column Target Retained Bits' \
                    : kn.unpack(impl)['target_bits'],
                'Stratigraphic Column Expected Retained Bits Error' \
                    : kn.unpack(impl)['bits_error'],
                'Stratigraphic Column Actual Num Retained Strata' \
                    : kn.unpack(impl)['actual_strata'],
                'Taxon Compared From' \
                    : extant1.id,
                'Taxon Compared To' \
                    : extant2.id,
                'Generation of Taxon Compared From' \
                    : extant1.hstrat_column.GetNumStrataDeposited(),
                'Generation of Taxon Compared To' \
                    : extant2.hstrat_column.GetNumStrataDeposited(),
                'Generation Of MRCA Lower Bound (inclusive)' \
                    : opyt.apply_if(
                        bounds[impl],
                        lambda x: x[0],
                    ),
                'Generation Of MRCA Upper Bound (exclusive)' \
                    : opyt.apply_if(
                        bounds[impl],
                        lambda x: x[1],
                    ),
                'MRCA Bound Confidence' \
                    : extant1.hstrat_column[impl].CalcRankOfMrcaBoundsWithProvidedConfidenceLevel(),
                'Rank of Earliest Detectable Mrca With' \
                    : extant1.hstrat_column[impl].CalcRankOfEarliestDetectableMrcaWith(extant2.hstrat_column[impl]),
            })

res_df = pd.DataFrame.from_records(res)

  0%|          | 0/5329 [00:00<?, ?it/s]

  0%|          | 3/5329 [00:00<03:16, 27.17it/s]

  0%|          | 5/5329 [00:00<03:44, 23.75it/s]

  0%|          | 7/5329 [00:00<04:03, 21.84it/s]

  0%|          | 9/5329 [00:00<04:18, 20.62it/s]

  0%|          | 11/5329 [00:00<04:27, 19.91it/s]

  0%|          | 13/5329 [00:00<04:33, 19.45it/s]

  0%|          | 15/5329 [00:00<04:37, 19.18it/s]

  0%|          | 17/5329 [00:00<04:38, 19.06it/s]

  0%|          | 19/5329 [00:00<04:39, 18.99it/s]

  0%|          | 21/5329 [00:01<04:40, 18.93it/s]

  0%|          | 23/5329 [00:01<04:40, 18.89it/s]

  0%|          | 25/5329 [00:01<04:41, 18.84it/s]

  1%|          | 27/5329 [00:01<04:41, 18.81it/s]

  1%|          | 29/5329 [00:01<04:42, 18.79it/s]

  1%|          | 31/5329 [00:01<04:44, 18.65it/s]

  1%|          | 33/5329 [00:01<04:43, 18.71it/s]

  1%|          | 35/5329 [00:01<04:42, 18.77it/s]

  1%|          | 37/5329 [00:01<04:41, 18.82it/s]

  1%|          | 39/5329 [00:02<04:41, 18.80it/s]

  1%|          | 41/5329 [00:02<04:41, 18.77it/s]

  1%|          | 43/5329 [00:02<04:41, 18.78it/s]

  1%|          | 45/5329 [00:02<04:41, 18.74it/s]

  1%|          | 47/5329 [00:02<04:43, 18.61it/s]

  1%|          | 49/5329 [00:02<04:48, 18.29it/s]

  1%|          | 51/5329 [00:02<04:49, 18.21it/s]

  1%|          | 53/5329 [00:02<04:48, 18.26it/s]

  1%|          | 55/5329 [00:02<04:52, 18.02it/s]

  1%|          | 57/5329 [00:03<04:53, 17.97it/s]

  1%|          | 59/5329 [00:03<04:52, 18.00it/s]

  1%|          | 61/5329 [00:03<04:52, 17.98it/s]

  1%|          | 63/5329 [00:03<04:51, 18.06it/s]

  1%|          | 65/5329 [00:03<04:50, 18.15it/s]

  1%|▏         | 67/5329 [00:03<04:52, 17.98it/s]

  1%|▏         | 69/5329 [00:03<04:55, 17.81it/s]

  1%|▏         | 71/5329 [00:03<04:54, 17.87it/s]

  1%|▏         | 73/5329 [00:03<04:54, 17.87it/s]

  1%|▏         | 76/5329 [00:04<04:26, 19.70it/s]

  1%|▏         | 79/5329 [00:04<04:38, 18.88it/s]

  2%|▏         | 81/5329 [00:04<04:43, 18.51it/s]

  2%|▏         | 83/5329 [00:04<04:46, 18.29it/s]

  2%|▏         | 85/5329 [00:04<04:49, 18.12it/s]

  2%|▏         | 87/5329 [00:04<04:50, 18.02it/s]

  2%|▏         | 89/5329 [00:04<04:53, 17.83it/s]

  2%|▏         | 91/5329 [00:04<04:53, 17.87it/s]

  2%|▏         | 93/5329 [00:05<04:53, 17.86it/s]

  2%|▏         | 95/5329 [00:05<04:52, 17.86it/s]

  2%|▏         | 97/5329 [00:05<04:54, 17.78it/s]

  2%|▏         | 99/5329 [00:05<04:50, 17.98it/s]

  2%|▏         | 101/5329 [00:05<04:48, 18.11it/s]

  2%|▏         | 103/5329 [00:05<04:49, 18.06it/s]

  2%|▏         | 105/5329 [00:05<04:47, 18.15it/s]

  2%|▏         | 107/5329 [00:05<04:46, 18.20it/s]

  2%|▏         | 109/5329 [00:05<04:46, 18.23it/s]

  2%|▏         | 111/5329 [00:05<04:46, 18.23it/s]

  2%|▏         | 113/5329 [00:06<04:45, 18.25it/s]

  2%|▏         | 115/5329 [00:06<04:46, 18.20it/s]

  2%|▏         | 117/5329 [00:06<04:45, 18.24it/s]

  2%|▏         | 119/5329 [00:06<04:43, 18.38it/s]

  2%|▏         | 121/5329 [00:06<04:42, 18.41it/s]

  2%|▏         | 123/5329 [00:06<04:44, 18.31it/s]

  2%|▏         | 125/5329 [00:06<04:47, 18.11it/s]

  2%|▏         | 127/5329 [00:06<04:45, 18.20it/s]

  2%|▏         | 129/5329 [00:06<04:41, 18.49it/s]

  2%|▏         | 131/5329 [00:07<04:36, 18.77it/s]

  2%|▏         | 133/5329 [00:07<04:35, 18.87it/s]

  3%|▎         | 135/5329 [00:07<04:33, 18.96it/s]

  3%|▎         | 137/5329 [00:07<04:32, 19.04it/s]

  3%|▎         | 139/5329 [00:07<04:32, 19.06it/s]

  3%|▎         | 141/5329 [00:07<04:31, 19.12it/s]

  3%|▎         | 143/5329 [00:07<04:30, 19.16it/s]

  3%|▎         | 145/5329 [00:07<04:31, 19.09it/s]

  3%|▎         | 147/5329 [00:07<04:32, 19.03it/s]

  3%|▎         | 150/5329 [00:08<04:05, 21.08it/s]

  3%|▎         | 153/5329 [00:08<04:19, 19.94it/s]

  3%|▎         | 156/5329 [00:08<04:25, 19.47it/s]

  3%|▎         | 158/5329 [00:08<04:27, 19.31it/s]

  3%|▎         | 160/5329 [00:08<04:29, 19.17it/s]

  3%|▎         | 162/5329 [00:08<04:29, 19.17it/s]

  3%|▎         | 164/5329 [00:08<04:31, 19.04it/s]

  3%|▎         | 166/5329 [00:08<04:30, 19.10it/s]

  3%|▎         | 168/5329 [00:08<04:33, 18.86it/s]

  3%|▎         | 170/5329 [00:09<04:32, 18.92it/s]

  3%|▎         | 172/5329 [00:09<04:31, 19.01it/s]

  3%|▎         | 174/5329 [00:09<04:31, 19.02it/s]

  3%|▎         | 176/5329 [00:09<04:29, 19.09it/s]

  3%|▎         | 178/5329 [00:09<04:28, 19.22it/s]

  3%|▎         | 180/5329 [00:09<04:27, 19.23it/s]

  3%|▎         | 182/5329 [00:09<04:27, 19.28it/s]

  3%|▎         | 184/5329 [00:09<04:28, 19.20it/s]

  3%|▎         | 186/5329 [00:09<04:27, 19.23it/s]

  4%|▎         | 188/5329 [00:10<04:27, 19.21it/s]

  4%|▎         | 190/5329 [00:10<04:28, 19.13it/s]

  4%|▎         | 192/5329 [00:10<04:27, 19.19it/s]

  4%|▎         | 194/5329 [00:10<04:26, 19.25it/s]

  4%|▎         | 196/5329 [00:10<04:27, 19.20it/s]

  4%|▎         | 198/5329 [00:10<04:26, 19.26it/s]

  4%|▍         | 200/5329 [00:10<04:25, 19.30it/s]

  4%|▍         | 202/5329 [00:10<04:28, 19.09it/s]

  4%|▍         | 204/5329 [00:10<04:28, 19.05it/s]

  4%|▍         | 206/5329 [00:10<04:27, 19.16it/s]

  4%|▍         | 208/5329 [00:11<04:26, 19.24it/s]

  4%|▍         | 210/5329 [00:11<04:26, 19.23it/s]

  4%|▍         | 212/5329 [00:11<04:26, 19.24it/s]

  4%|▍         | 214/5329 [00:11<04:26, 19.22it/s]

  4%|▍         | 216/5329 [00:11<04:24, 19.30it/s]

  4%|▍         | 218/5329 [00:11<04:25, 19.27it/s]

  4%|▍         | 220/5329 [00:11<04:26, 19.19it/s]

  4%|▍         | 222/5329 [00:11<04:28, 19.05it/s]

  4%|▍         | 225/5329 [00:11<04:01, 21.17it/s]

  4%|▍         | 228/5329 [00:12<04:10, 20.34it/s]

  4%|▍         | 231/5329 [00:12<04:16, 19.86it/s]

  4%|▍         | 234/5329 [00:12<04:20, 19.53it/s]

  4%|▍         | 236/5329 [00:12<04:22, 19.40it/s]

  4%|▍         | 238/5329 [00:12<04:24, 19.28it/s]

  5%|▍         | 240/5329 [00:12<04:26, 19.13it/s]

  5%|▍         | 242/5329 [00:12<04:26, 19.10it/s]

  5%|▍         | 244/5329 [00:12<04:27, 19.04it/s]

  5%|▍         | 246/5329 [00:13<04:27, 18.99it/s]

  5%|▍         | 248/5329 [00:13<04:28, 18.95it/s]

  5%|▍         | 250/5329 [00:13<04:26, 19.04it/s]

  5%|▍         | 252/5329 [00:13<04:25, 19.12it/s]

  5%|▍         | 254/5329 [00:13<04:25, 19.12it/s]

  5%|▍         | 256/5329 [00:13<04:24, 19.15it/s]

  5%|▍         | 258/5329 [00:13<04:24, 19.15it/s]

  5%|▍         | 260/5329 [00:13<04:24, 19.15it/s]

  5%|▍         | 262/5329 [00:13<04:25, 19.09it/s]

  5%|▍         | 264/5329 [00:13<04:24, 19.18it/s]

  5%|▍         | 266/5329 [00:14<04:23, 19.20it/s]

  5%|▌         | 268/5329 [00:14<04:23, 19.22it/s]

  5%|▌         | 270/5329 [00:14<04:23, 19.23it/s]

  5%|▌         | 272/5329 [00:14<04:22, 19.25it/s]

  5%|▌         | 274/5329 [00:14<04:23, 19.18it/s]

  5%|▌         | 276/5329 [00:14<04:25, 19.05it/s]

  5%|▌         | 278/5329 [00:14<04:24, 19.07it/s]

  5%|▌         | 280/5329 [00:14<04:25, 18.98it/s]

  5%|▌         | 282/5329 [00:14<04:25, 19.01it/s]

  5%|▌         | 284/5329 [00:15<04:25, 19.01it/s]

  5%|▌         | 286/5329 [00:15<04:24, 19.07it/s]

  5%|▌         | 288/5329 [00:15<04:23, 19.15it/s]

  5%|▌         | 290/5329 [00:15<04:23, 19.14it/s]

  5%|▌         | 292/5329 [00:15<04:22, 19.18it/s]

  6%|▌         | 294/5329 [00:15<04:25, 18.98it/s]

  6%|▌         | 296/5329 [00:15<04:27, 18.85it/s]

  6%|▌         | 299/5329 [00:15<04:00, 20.89it/s]

  6%|▌         | 302/5329 [00:15<04:09, 20.17it/s]

  6%|▌         | 305/5329 [00:16<04:15, 19.67it/s]

  6%|▌         | 308/5329 [00:16<04:18, 19.43it/s]

  6%|▌         | 310/5329 [00:16<04:20, 19.24it/s]

  6%|▌         | 312/5329 [00:16<04:23, 19.06it/s]

  6%|▌         | 314/5329 [00:16<04:23, 19.04it/s]

  6%|▌         | 316/5329 [00:16<04:23, 19.01it/s]

  6%|▌         | 318/5329 [00:16<04:25, 18.88it/s]

  6%|▌         | 320/5329 [00:16<04:26, 18.82it/s]

  6%|▌         | 322/5329 [00:16<04:26, 18.80it/s]

  6%|▌         | 324/5329 [00:17<04:25, 18.88it/s]

  6%|▌         | 326/5329 [00:17<04:23, 18.97it/s]

  6%|▌         | 328/5329 [00:17<04:24, 18.88it/s]

  6%|▌         | 330/5329 [00:17<04:24, 18.90it/s]

  6%|▌         | 332/5329 [00:17<04:23, 18.94it/s]

  6%|▋         | 334/5329 [00:17<04:22, 19.01it/s]

  6%|▋         | 336/5329 [00:17<04:23, 18.95it/s]

  6%|▋         | 338/5329 [00:17<04:23, 18.96it/s]

  6%|▋         | 340/5329 [00:17<04:23, 18.92it/s]

  6%|▋         | 342/5329 [00:18<04:25, 18.76it/s]

  6%|▋         | 344/5329 [00:18<04:25, 18.79it/s]

  6%|▋         | 346/5329 [00:18<04:24, 18.86it/s]

  7%|▋         | 348/5329 [00:18<04:24, 18.81it/s]

  7%|▋         | 350/5329 [00:18<04:27, 18.63it/s]

  7%|▋         | 352/5329 [00:18<04:25, 18.73it/s]

  7%|▋         | 354/5329 [00:18<04:23, 18.88it/s]

  7%|▋         | 356/5329 [00:18<04:23, 18.89it/s]

  7%|▋         | 358/5329 [00:18<04:22, 18.92it/s]

  7%|▋         | 360/5329 [00:18<04:21, 18.97it/s]

  7%|▋         | 362/5329 [00:19<04:20, 19.07it/s]

  7%|▋         | 364/5329 [00:19<04:20, 19.03it/s]

  7%|▋         | 366/5329 [00:19<04:22, 18.94it/s]

  7%|▋         | 368/5329 [00:19<04:22, 18.91it/s]

  7%|▋         | 370/5329 [00:19<04:24, 18.74it/s]

  7%|▋         | 373/5329 [00:19<03:58, 20.81it/s]

  7%|▋         | 376/5329 [00:19<04:04, 20.22it/s]

  7%|▋         | 379/5329 [00:19<04:10, 19.73it/s]

  7%|▋         | 382/5329 [00:20<04:13, 19.53it/s]

  7%|▋         | 384/5329 [00:20<04:15, 19.38it/s]

  7%|▋         | 386/5329 [00:20<04:16, 19.25it/s]

  7%|▋         | 388/5329 [00:20<04:17, 19.22it/s]

  7%|▋         | 390/5329 [00:20<04:17, 19.15it/s]

  7%|▋         | 392/5329 [00:20<04:18, 19.09it/s]

  7%|▋         | 394/5329 [00:20<04:18, 19.10it/s]

  7%|▋         | 396/5329 [00:20<04:17, 19.14it/s]

  7%|▋         | 398/5329 [00:20<04:17, 19.15it/s]

  8%|▊         | 400/5329 [00:21<04:16, 19.21it/s]

  8%|▊         | 402/5329 [00:21<04:16, 19.22it/s]

  8%|▊         | 404/5329 [00:21<04:15, 19.27it/s]

  8%|▊         | 406/5329 [00:21<04:15, 19.28it/s]

  8%|▊         | 408/5329 [00:21<04:15, 19.23it/s]

  8%|▊         | 410/5329 [00:21<04:14, 19.34it/s]

  8%|▊         | 412/5329 [00:21<04:13, 19.40it/s]

  8%|▊         | 414/5329 [00:21<04:13, 19.41it/s]

  8%|▊         | 416/5329 [00:21<04:13, 19.41it/s]

  8%|▊         | 418/5329 [00:21<04:12, 19.46it/s]

  8%|▊         | 420/5329 [00:22<04:12, 19.44it/s]

  8%|▊         | 422/5329 [00:22<04:12, 19.42it/s]

  8%|▊         | 424/5329 [00:22<04:12, 19.46it/s]

  8%|▊         | 426/5329 [00:22<04:13, 19.35it/s]

  8%|▊         | 428/5329 [00:22<04:13, 19.34it/s]

  8%|▊         | 430/5329 [00:22<04:12, 19.40it/s]

  8%|▊         | 432/5329 [00:22<04:11, 19.44it/s]

  8%|▊         | 434/5329 [00:22<04:13, 19.33it/s]

  8%|▊         | 436/5329 [00:22<04:13, 19.34it/s]

  8%|▊         | 438/5329 [00:23<04:12, 19.38it/s]

  8%|▊         | 440/5329 [00:23<04:14, 19.20it/s]

  8%|▊         | 442/5329 [00:23<04:16, 19.07it/s]

  8%|▊         | 444/5329 [00:23<04:16, 19.02it/s]

  8%|▊         | 447/5329 [00:23<03:51, 21.08it/s]

  8%|▊         | 450/5329 [00:23<03:59, 20.41it/s]

  9%|▊         | 453/5329 [00:23<04:04, 19.94it/s]

  9%|▊         | 456/5329 [00:23<04:07, 19.67it/s]

  9%|▊         | 458/5329 [00:24<04:09, 19.49it/s]

  9%|▊         | 460/5329 [00:24<04:11, 19.38it/s]

  9%|▊         | 462/5329 [00:24<04:12, 19.28it/s]

  9%|▊         | 464/5329 [00:24<04:14, 19.14it/s]

  9%|▊         | 466/5329 [00:24<04:14, 19.13it/s]

  9%|▉         | 468/5329 [00:24<04:14, 19.12it/s]

  9%|▉         | 470/5329 [00:24<04:12, 19.21it/s]

  9%|▉         | 472/5329 [00:24<04:11, 19.28it/s]

  9%|▉         | 474/5329 [00:24<04:11, 19.30it/s]

  9%|▉         | 476/5329 [00:24<04:11, 19.29it/s]

  9%|▉         | 478/5329 [00:25<04:10, 19.34it/s]

  9%|▉         | 480/5329 [00:25<04:10, 19.38it/s]

  9%|▉         | 482/5329 [00:25<04:10, 19.32it/s]

  9%|▉         | 484/5329 [00:25<04:11, 19.30it/s]

  9%|▉         | 486/5329 [00:25<04:10, 19.32it/s]

  9%|▉         | 488/5329 [00:25<04:10, 19.34it/s]

  9%|▉         | 490/5329 [00:25<04:10, 19.31it/s]

  9%|▉         | 492/5329 [00:25<04:09, 19.36it/s]

  9%|▉         | 494/5329 [00:25<04:10, 19.32it/s]

  9%|▉         | 496/5329 [00:25<04:10, 19.32it/s]

  9%|▉         | 498/5329 [00:26<04:09, 19.33it/s]

  9%|▉         | 500/5329 [00:26<04:09, 19.37it/s]

  9%|▉         | 502/5329 [00:26<04:09, 19.35it/s]

  9%|▉         | 504/5329 [00:26<04:09, 19.33it/s]

  9%|▉         | 506/5329 [00:26<04:09, 19.34it/s]

 10%|▉         | 508/5329 [00:26<04:08, 19.37it/s]

 10%|▉         | 510/5329 [00:26<04:09, 19.34it/s]

 10%|▉         | 512/5329 [00:26<04:09, 19.30it/s]

 10%|▉         | 514/5329 [00:26<04:10, 19.20it/s]

 10%|▉         | 516/5329 [00:27<04:12, 19.09it/s]

 10%|▉         | 518/5329 [00:27<04:12, 19.03it/s]

 10%|▉         | 521/5329 [00:27<03:47, 21.12it/s]

 10%|▉         | 524/5329 [00:27<03:54, 20.46it/s]

 10%|▉         | 527/5329 [00:27<03:59, 20.08it/s]

 10%|▉         | 530/5329 [00:27<04:01, 19.83it/s]

 10%|█         | 533/5329 [00:27<04:05, 19.55it/s]

 10%|█         | 535/5329 [00:27<04:07, 19.41it/s]

 10%|█         | 537/5329 [00:28<04:08, 19.31it/s]

 10%|█         | 539/5329 [00:28<04:08, 19.30it/s]

 10%|█         | 541/5329 [00:28<04:08, 19.30it/s]

 10%|█         | 543/5329 [00:28<04:07, 19.34it/s]

 10%|█         | 545/5329 [00:28<04:07, 19.34it/s]

 10%|█         | 547/5329 [00:28<04:06, 19.37it/s]

 10%|█         | 549/5329 [00:28<04:06, 19.36it/s]

 10%|█         | 551/5329 [00:28<04:08, 19.22it/s]

 10%|█         | 553/5329 [00:28<04:07, 19.30it/s]

 10%|█         | 555/5329 [00:28<04:06, 19.36it/s]

 10%|█         | 557/5329 [00:29<04:06, 19.39it/s]

 10%|█         | 559/5329 [00:29<04:06, 19.34it/s]

 11%|█         | 561/5329 [00:29<04:05, 19.40it/s]

 11%|█         | 563/5329 [00:29<04:05, 19.43it/s]

 11%|█         | 565/5329 [00:29<04:05, 19.42it/s]

 11%|█         | 567/5329 [00:29<04:05, 19.39it/s]

 11%|█         | 569/5329 [00:29<04:04, 19.46it/s]

 11%|█         | 571/5329 [00:29<04:05, 19.40it/s]

 11%|█         | 573/5329 [00:29<04:06, 19.28it/s]

 11%|█         | 575/5329 [00:30<04:10, 18.99it/s]

 11%|█         | 577/5329 [00:30<04:07, 19.17it/s]

 11%|█         | 579/5329 [00:30<04:06, 19.25it/s]

 11%|█         | 581/5329 [00:30<04:05, 19.34it/s]

 11%|█         | 583/5329 [00:30<04:05, 19.36it/s]

 11%|█         | 585/5329 [00:30<04:05, 19.31it/s]

 11%|█         | 587/5329 [00:30<04:06, 19.23it/s]

 11%|█         | 589/5329 [00:30<04:06, 19.20it/s]

 11%|█         | 591/5329 [00:30<04:08, 19.09it/s]

 11%|█         | 594/5329 [00:30<03:43, 21.16it/s]

 11%|█         | 597/5329 [00:31<03:51, 20.47it/s]

 11%|█▏        | 600/5329 [00:31<03:55, 20.05it/s]

 11%|█▏        | 603/5329 [00:31<03:58, 19.85it/s]

 11%|█▏        | 606/5329 [00:31<04:00, 19.67it/s]

 11%|█▏        | 608/5329 [00:31<04:01, 19.56it/s]

 11%|█▏        | 610/5329 [00:31<04:01, 19.50it/s]

 11%|█▏        | 612/5329 [00:31<04:04, 19.32it/s]

 12%|█▏        | 614/5329 [00:32<04:04, 19.31it/s]

 12%|█▏        | 616/5329 [00:32<04:03, 19.39it/s]

 12%|█▏        | 618/5329 [00:32<04:02, 19.41it/s]

 12%|█▏        | 620/5329 [00:32<04:02, 19.39it/s]

 12%|█▏        | 622/5329 [00:32<04:03, 19.31it/s]

 12%|█▏        | 624/5329 [00:32<04:03, 19.34it/s]

 12%|█▏        | 626/5329 [00:32<04:03, 19.30it/s]

 12%|█▏        | 628/5329 [00:32<04:03, 19.27it/s]

 12%|█▏        | 630/5329 [00:32<04:03, 19.31it/s]

 12%|█▏        | 632/5329 [00:32<04:03, 19.31it/s]

 12%|█▏        | 634/5329 [00:33<04:03, 19.29it/s]

 12%|█▏        | 636/5329 [00:33<04:02, 19.32it/s]

 12%|█▏        | 638/5329 [00:33<04:02, 19.36it/s]

 12%|█▏        | 640/5329 [00:33<04:02, 19.35it/s]

 12%|█▏        | 642/5329 [00:33<04:02, 19.31it/s]

 12%|█▏        | 644/5329 [00:33<04:02, 19.35it/s]

 12%|█▏        | 646/5329 [00:33<04:01, 19.37it/s]

 12%|█▏        | 648/5329 [00:33<04:01, 19.37it/s]

 12%|█▏        | 650/5329 [00:33<04:01, 19.41it/s]

 12%|█▏        | 652/5329 [00:33<04:01, 19.40it/s]

 12%|█▏        | 654/5329 [00:34<04:01, 19.39it/s]

 12%|█▏        | 656/5329 [00:34<04:01, 19.37it/s]

 12%|█▏        | 658/5329 [00:34<04:01, 19.32it/s]

 12%|█▏        | 660/5329 [00:34<04:03, 19.16it/s]

 12%|█▏        | 662/5329 [00:34<04:04, 19.08it/s]

 12%|█▏        | 664/5329 [00:34<04:05, 19.04it/s]

 12%|█▏        | 666/5329 [00:34<04:05, 19.02it/s]

 13%|█▎        | 669/5329 [00:34<03:41, 21.01it/s]

 13%|█▎        | 672/5329 [00:34<03:48, 20.34it/s]

 13%|█▎        | 675/5329 [00:35<03:52, 20.01it/s]

 13%|█▎        | 678/5329 [00:35<03:54, 19.80it/s]

 13%|█▎        | 681/5329 [00:35<03:56, 19.63it/s]

 13%|█▎        | 683/5329 [00:35<03:58, 19.50it/s]

 13%|█▎        | 685/5329 [00:35<03:59, 19.42it/s]

 13%|█▎        | 687/5329 [00:35<04:00, 19.33it/s]

 13%|█▎        | 689/5329 [00:35<03:59, 19.33it/s]

 13%|█▎        | 691/5329 [00:35<04:01, 19.20it/s]

 13%|█▎        | 693/5329 [00:36<04:01, 19.22it/s]

 13%|█▎        | 695/5329 [00:36<04:00, 19.28it/s]

 13%|█▎        | 697/5329 [00:36<03:59, 19.32it/s]

 13%|█▎        | 699/5329 [00:36<03:59, 19.36it/s]

 13%|█▎        | 701/5329 [00:36<03:59, 19.35it/s]

 13%|█▎        | 703/5329 [00:36<03:59, 19.34it/s]

 13%|█▎        | 705/5329 [00:36<03:58, 19.35it/s]

 13%|█▎        | 707/5329 [00:36<03:58, 19.39it/s]

 13%|█▎        | 709/5329 [00:36<03:58, 19.34it/s]

 13%|█▎        | 711/5329 [00:36<03:58, 19.33it/s]

 13%|█▎        | 713/5329 [00:37<03:58, 19.34it/s]

 13%|█▎        | 715/5329 [00:37<03:58, 19.34it/s]

 13%|█▎        | 717/5329 [00:37<03:58, 19.33it/s]

 13%|█▎        | 719/5329 [00:37<03:58, 19.36it/s]

 14%|█▎        | 721/5329 [00:37<03:57, 19.39it/s]

 14%|█▎        | 723/5329 [00:37<03:57, 19.38it/s]

 14%|█▎        | 725/5329 [00:37<03:57, 19.39it/s]

 14%|█▎        | 727/5329 [00:37<03:57, 19.41it/s]

 14%|█▎        | 729/5329 [00:37<04:00, 19.16it/s]

 14%|█▎        | 731/5329 [00:38<03:59, 19.16it/s]

 14%|█▍        | 733/5329 [00:38<04:00, 19.08it/s]

 14%|█▍        | 735/5329 [00:38<04:01, 19.06it/s]

 14%|█▍        | 737/5329 [00:38<04:01, 18.98it/s]

 14%|█▍        | 739/5329 [00:38<04:02, 18.96it/s]

 14%|█▍        | 742/5329 [00:38<03:38, 21.03it/s]

 14%|█▍        | 745/5329 [00:38<03:45, 20.32it/s]

 14%|█▍        | 748/5329 [00:38<03:49, 20.00it/s]

 14%|█▍        | 751/5329 [00:39<03:53, 19.64it/s]

 14%|█▍        | 753/5329 [00:39<03:54, 19.52it/s]

 14%|█▍        | 755/5329 [00:39<03:55, 19.43it/s]

 14%|█▍        | 757/5329 [00:39<03:56, 19.37it/s]

 14%|█▍        | 759/5329 [00:39<03:56, 19.33it/s]

 14%|█▍        | 761/5329 [00:39<03:55, 19.36it/s]

 14%|█▍        | 763/5329 [00:39<03:55, 19.39it/s]

 14%|█▍        | 765/5329 [00:39<03:54, 19.42it/s]

 14%|█▍        | 767/5329 [00:39<03:54, 19.45it/s]

 14%|█▍        | 769/5329 [00:39<03:55, 19.33it/s]

 14%|█▍        | 771/5329 [00:40<03:55, 19.34it/s]

 15%|█▍        | 773/5329 [00:40<03:54, 19.40it/s]

 15%|█▍        | 775/5329 [00:40<03:53, 19.47it/s]

 15%|█▍        | 777/5329 [00:40<03:54, 19.44it/s]

 15%|█▍        | 779/5329 [00:40<03:53, 19.49it/s]

 15%|█▍        | 781/5329 [00:40<03:52, 19.54it/s]

 15%|█▍        | 783/5329 [00:40<03:52, 19.52it/s]

 15%|█▍        | 785/5329 [00:40<03:52, 19.54it/s]

 15%|█▍        | 787/5329 [00:40<03:54, 19.39it/s]

 15%|█▍        | 789/5329 [00:40<03:54, 19.39it/s]

 15%|█▍        | 791/5329 [00:41<03:54, 19.35it/s]

 15%|█▍        | 793/5329 [00:41<03:53, 19.39it/s]

 15%|█▍        | 795/5329 [00:41<03:53, 19.41it/s]

 15%|█▍        | 797/5329 [00:41<03:53, 19.42it/s]

 15%|█▍        | 799/5329 [00:41<03:53, 19.41it/s]

 15%|█▌        | 801/5329 [00:41<03:53, 19.41it/s]

 15%|█▌        | 803/5329 [00:41<03:52, 19.43it/s]

 15%|█▌        | 805/5329 [00:41<03:55, 19.23it/s]

 15%|█▌        | 807/5329 [00:41<03:56, 19.11it/s]

 15%|█▌        | 809/5329 [00:42<03:57, 19.01it/s]

 15%|█▌        | 811/5329 [00:42<03:57, 18.99it/s]

 15%|█▌        | 813/5329 [00:42<03:57, 19.00it/s]

 15%|█▌        | 816/5329 [00:42<03:34, 21.04it/s]

 15%|█▌        | 819/5329 [00:42<03:41, 20.40it/s]

 15%|█▌        | 822/5329 [00:42<03:44, 20.09it/s]

 15%|█▌        | 825/5329 [00:42<03:46, 19.85it/s]

 16%|█▌        | 828/5329 [00:42<03:49, 19.65it/s]

 16%|█▌        | 830/5329 [00:43<03:49, 19.56it/s]

 16%|█▌        | 832/5329 [00:43<03:51, 19.46it/s]

 16%|█▌        | 834/5329 [00:43<03:51, 19.45it/s]

 16%|█▌        | 836/5329 [00:43<03:50, 19.49it/s]

 16%|█▌        | 838/5329 [00:43<03:50, 19.47it/s]

 16%|█▌        | 840/5329 [00:43<03:50, 19.45it/s]

 16%|█▌        | 842/5329 [00:43<03:50, 19.49it/s]

 16%|█▌        | 844/5329 [00:43<03:49, 19.50it/s]

 16%|█▌        | 846/5329 [00:43<03:50, 19.45it/s]

 16%|█▌        | 848/5329 [00:44<03:50, 19.46it/s]

 16%|█▌        | 850/5329 [00:44<03:50, 19.45it/s]

 16%|█▌        | 852/5329 [00:44<03:50, 19.44it/s]

 16%|█▌        | 854/5329 [00:44<03:50, 19.41it/s]

 16%|█▌        | 856/5329 [00:44<03:50, 19.44it/s]

 16%|█▌        | 858/5329 [00:44<03:50, 19.43it/s]

 16%|█▌        | 860/5329 [00:44<03:50, 19.38it/s]

 16%|█▌        | 862/5329 [00:44<03:50, 19.39it/s]

 16%|█▌        | 864/5329 [00:44<03:50, 19.37it/s]

 16%|█▋        | 866/5329 [00:44<03:50, 19.34it/s]

 16%|█▋        | 868/5329 [00:45<03:52, 19.22it/s]

 16%|█▋        | 870/5329 [00:45<03:51, 19.30it/s]

 16%|█▋        | 872/5329 [00:45<03:50, 19.36it/s]

 16%|█▋        | 874/5329 [00:45<03:50, 19.32it/s]

 16%|█▋        | 876/5329 [00:45<03:50, 19.35it/s]

 16%|█▋        | 878/5329 [00:45<03:50, 19.30it/s]

 17%|█▋        | 880/5329 [00:45<03:51, 19.18it/s]

 17%|█▋        | 882/5329 [00:45<03:52, 19.16it/s]

 17%|█▋        | 884/5329 [00:45<03:52, 19.16it/s]

 17%|█▋        | 886/5329 [00:45<03:53, 19.07it/s]

 17%|█▋        | 888/5329 [00:46<03:53, 19.04it/s]

 17%|█▋        | 891/5329 [00:46<03:29, 21.15it/s]

 17%|█▋        | 894/5329 [00:46<03:35, 20.60it/s]

 17%|█▋        | 897/5329 [00:46<03:39, 20.17it/s]

 17%|█▋        | 900/5329 [00:46<03:42, 19.94it/s]

 17%|█▋        | 903/5329 [00:46<03:43, 19.76it/s]

 17%|█▋        | 905/5329 [00:46<03:46, 19.53it/s]

 17%|█▋        | 907/5329 [00:47<03:48, 19.32it/s]

 17%|█▋        | 909/5329 [00:47<03:48, 19.33it/s]

 17%|█▋        | 911/5329 [00:47<03:47, 19.42it/s]

 17%|█▋        | 913/5329 [00:47<03:47, 19.43it/s]

 17%|█▋        | 915/5329 [00:47<03:46, 19.46it/s]

 17%|█▋        | 917/5329 [00:47<03:46, 19.48it/s]

 17%|█▋        | 919/5329 [00:47<03:46, 19.50it/s]

 17%|█▋        | 921/5329 [00:47<03:46, 19.49it/s]

 17%|█▋        | 923/5329 [00:47<03:46, 19.48it/s]

 17%|█▋        | 925/5329 [00:47<03:45, 19.52it/s]

 17%|█▋        | 927/5329 [00:48<03:45, 19.49it/s]

 17%|█▋        | 929/5329 [00:48<03:46, 19.44it/s]

 17%|█▋        | 931/5329 [00:48<03:45, 19.49it/s]

 18%|█▊        | 933/5329 [00:48<03:46, 19.45it/s]

 18%|█▊        | 935/5329 [00:48<03:46, 19.44it/s]

 18%|█▊        | 937/5329 [00:48<03:45, 19.44it/s]

 18%|█▊        | 939/5329 [00:48<03:45, 19.49it/s]

 18%|█▊        | 941/5329 [00:48<03:44, 19.50it/s]

 18%|█▊        | 943/5329 [00:48<03:45, 19.48it/s]

 18%|█▊        | 945/5329 [00:48<03:45, 19.47it/s]

 18%|█▊        | 947/5329 [00:49<03:46, 19.31it/s]

 18%|█▊        | 949/5329 [00:49<03:48, 19.19it/s]

 18%|█▊        | 951/5329 [00:49<03:49, 19.11it/s]

 18%|█▊        | 953/5329 [00:49<03:49, 19.05it/s]

 18%|█▊        | 955/5329 [00:49<03:49, 19.02it/s]

 18%|█▊        | 957/5329 [00:49<03:49, 19.02it/s]

 18%|█▊        | 959/5329 [00:49<03:49, 19.03it/s]

 18%|█▊        | 961/5329 [00:49<03:50, 18.98it/s]

 18%|█▊        | 964/5329 [00:49<03:27, 21.08it/s]

 18%|█▊        | 967/5329 [00:50<03:32, 20.51it/s]

 18%|█▊        | 970/5329 [00:50<03:37, 20.07it/s]

 18%|█▊        | 973/5329 [00:50<03:39, 19.85it/s]

 18%|█▊        | 976/5329 [00:50<03:41, 19.68it/s]

 18%|█▊        | 978/5329 [00:50<03:42, 19.54it/s]

 18%|█▊        | 980/5329 [00:50<03:42, 19.54it/s]

 18%|█▊        | 982/5329 [00:50<03:42, 19.52it/s]

 18%|█▊        | 984/5329 [00:50<03:42, 19.51it/s]

 19%|█▊        | 986/5329 [00:51<03:43, 19.44it/s]

 19%|█▊        | 988/5329 [00:51<03:43, 19.45it/s]

 19%|█▊        | 990/5329 [00:51<03:43, 19.46it/s]

 19%|█▊        | 992/5329 [00:51<03:42, 19.47it/s]

 19%|█▊        | 994/5329 [00:51<03:42, 19.52it/s]

 19%|█▊        | 996/5329 [00:51<03:41, 19.53it/s]

 19%|█▊        | 998/5329 [00:51<03:41, 19.53it/s]

 19%|█▉        | 1000/5329 [00:51<03:41, 19.55it/s]

 19%|█▉        | 1002/5329 [00:51<03:41, 19.56it/s]

 19%|█▉        | 1004/5329 [00:51<03:41, 19.52it/s]

 19%|█▉        | 1006/5329 [00:52<03:43, 19.38it/s]

 19%|█▉        | 1008/5329 [00:52<03:42, 19.41it/s]

 19%|█▉        | 1010/5329 [00:52<03:42, 19.42it/s]

 19%|█▉        | 1012/5329 [00:52<03:43, 19.36it/s]

 19%|█▉        | 1014/5329 [00:52<03:42, 19.38it/s]

 19%|█▉        | 1016/5329 [00:52<03:42, 19.38it/s]

 19%|█▉        | 1018/5329 [00:52<03:42, 19.42it/s]

 19%|█▉        | 1020/5329 [00:52<03:41, 19.42it/s]

 19%|█▉        | 1022/5329 [00:52<03:42, 19.36it/s]

 19%|█▉        | 1024/5329 [00:53<03:43, 19.25it/s]

 19%|█▉        | 1026/5329 [00:53<03:44, 19.14it/s]

 19%|█▉        | 1028/5329 [00:53<03:44, 19.17it/s]

 19%|█▉        | 1030/5329 [00:53<03:44, 19.15it/s]

 19%|█▉        | 1032/5329 [00:53<03:45, 19.08it/s]

 19%|█▉        | 1034/5329 [00:53<03:45, 19.02it/s]

 19%|█▉        | 1036/5329 [00:53<03:46, 18.99it/s]

 19%|█▉        | 1039/5329 [00:53<03:22, 21.18it/s]

 20%|█▉        | 1042/5329 [00:53<03:28, 20.58it/s]

 20%|█▉        | 1045/5329 [00:54<03:33, 20.10it/s]

 20%|█▉        | 1048/5329 [00:54<03:35, 19.85it/s]

 20%|█▉        | 1051/5329 [00:54<03:36, 19.72it/s]

 20%|█▉        | 1053/5329 [00:54<03:37, 19.64it/s]

 20%|█▉        | 1055/5329 [00:54<03:37, 19.65it/s]

 20%|█▉        | 1057/5329 [00:54<03:37, 19.64it/s]

 20%|█▉        | 1059/5329 [00:54<03:38, 19.56it/s]

 20%|█▉        | 1061/5329 [00:54<03:37, 19.59it/s]

 20%|█▉        | 1063/5329 [00:54<03:37, 19.62it/s]

 20%|█▉        | 1065/5329 [00:55<03:38, 19.55it/s]

 20%|██        | 1067/5329 [00:55<03:38, 19.52it/s]

 20%|██        | 1069/5329 [00:55<03:37, 19.56it/s]

 20%|██        | 1071/5329 [00:55<03:37, 19.57it/s]

 20%|██        | 1073/5329 [00:55<03:37, 19.55it/s]

 20%|██        | 1075/5329 [00:55<03:37, 19.59it/s]

 20%|██        | 1077/5329 [00:55<03:37, 19.59it/s]

 20%|██        | 1079/5329 [00:55<03:37, 19.55it/s]

 20%|██        | 1081/5329 [00:55<03:37, 19.55it/s]

 20%|██        | 1083/5329 [00:56<03:37, 19.57it/s]

 20%|██        | 1085/5329 [00:56<03:38, 19.43it/s]

 20%|██        | 1087/5329 [00:56<03:37, 19.48it/s]

 20%|██        | 1089/5329 [00:56<03:37, 19.52it/s]

 20%|██        | 1091/5329 [00:56<03:36, 19.54it/s]

 21%|██        | 1093/5329 [00:56<03:37, 19.50it/s]

 21%|██        | 1095/5329 [00:56<03:36, 19.52it/s]

 21%|██        | 1097/5329 [00:56<03:37, 19.50it/s]

 21%|██        | 1099/5329 [00:56<03:37, 19.45it/s]

 21%|██        | 1101/5329 [00:56<03:37, 19.43it/s]

 21%|██        | 1103/5329 [00:57<03:38, 19.36it/s]

 21%|██        | 1105/5329 [00:57<03:38, 19.34it/s]

 21%|██        | 1107/5329 [00:57<03:38, 19.28it/s]

 21%|██        | 1109/5329 [00:57<03:38, 19.28it/s]

 21%|██        | 1112/5329 [00:57<03:17, 21.39it/s]

 21%|██        | 1115/5329 [00:57<03:24, 20.64it/s]

 21%|██        | 1118/5329 [00:57<03:28, 20.16it/s]

 21%|██        | 1121/5329 [00:57<03:33, 19.68it/s]

 21%|██        | 1124/5329 [00:58<03:36, 19.39it/s]

 21%|██        | 1126/5329 [00:58<03:37, 19.35it/s]

 21%|██        | 1128/5329 [00:58<03:36, 19.38it/s]

 21%|██        | 1130/5329 [00:58<03:36, 19.42it/s]

 21%|██        | 1132/5329 [00:58<03:35, 19.45it/s]

 21%|██▏       | 1134/5329 [00:58<03:35, 19.49it/s]

 21%|██▏       | 1136/5329 [00:58<03:35, 19.50it/s]

 21%|██▏       | 1138/5329 [00:58<03:34, 19.52it/s]

 21%|██▏       | 1140/5329 [00:58<03:35, 19.42it/s]

 21%|██▏       | 1142/5329 [00:59<03:35, 19.44it/s]

 21%|██▏       | 1144/5329 [00:59<03:35, 19.41it/s]

 22%|██▏       | 1146/5329 [00:59<03:35, 19.45it/s]

 22%|██▏       | 1148/5329 [00:59<03:36, 19.35it/s]

 22%|██▏       | 1150/5329 [00:59<03:39, 19.07it/s]

 22%|██▏       | 1152/5329 [00:59<03:38, 19.16it/s]

 22%|██▏       | 1154/5329 [00:59<03:36, 19.29it/s]

 22%|██▏       | 1156/5329 [00:59<03:35, 19.33it/s]

 22%|██▏       | 1158/5329 [00:59<03:35, 19.39it/s]

 22%|██▏       | 1160/5329 [00:59<03:33, 19.48it/s]

 22%|██▏       | 1162/5329 [01:00<03:34, 19.46it/s]

 22%|██▏       | 1164/5329 [01:00<03:41, 18.80it/s]

 22%|██▏       | 1166/5329 [01:00<03:39, 18.98it/s]

 22%|██▏       | 1168/5329 [01:00<03:37, 19.10it/s]

 22%|██▏       | 1170/5329 [01:00<03:36, 19.17it/s]

 22%|██▏       | 1172/5329 [01:00<03:35, 19.25it/s]

 22%|██▏       | 1174/5329 [01:00<03:35, 19.27it/s]

 22%|██▏       | 1176/5329 [01:00<03:34, 19.32it/s]

 22%|██▏       | 1178/5329 [01:00<03:34, 19.34it/s]

 22%|██▏       | 1180/5329 [01:00<03:34, 19.30it/s]

 22%|██▏       | 1182/5329 [01:01<03:35, 19.29it/s]

 22%|██▏       | 1184/5329 [01:01<03:35, 19.21it/s]

 22%|██▏       | 1187/5329 [01:01<03:14, 21.29it/s]

 22%|██▏       | 1190/5329 [01:01<03:21, 20.58it/s]

 22%|██▏       | 1193/5329 [01:01<03:25, 20.11it/s]

 22%|██▏       | 1196/5329 [01:01<03:28, 19.82it/s]

 22%|██▏       | 1199/5329 [01:01<03:30, 19.66it/s]

 23%|██▎       | 1201/5329 [01:02<03:30, 19.65it/s]

 23%|██▎       | 1203/5329 [01:02<03:30, 19.59it/s]

 23%|██▎       | 1205/5329 [01:02<03:30, 19.58it/s]

 23%|██▎       | 1207/5329 [01:02<03:30, 19.57it/s]

 23%|██▎       | 1209/5329 [01:02<03:30, 19.53it/s]

 23%|██▎       | 1211/5329 [01:02<03:30, 19.54it/s]

 23%|██▎       | 1213/5329 [01:02<03:30, 19.56it/s]

 23%|██▎       | 1215/5329 [01:02<03:30, 19.55it/s]

 23%|██▎       | 1217/5329 [01:02<03:30, 19.54it/s]

 23%|██▎       | 1219/5329 [01:02<03:30, 19.52it/s]

 23%|██▎       | 1221/5329 [01:03<03:30, 19.55it/s]

 23%|██▎       | 1223/5329 [01:03<03:30, 19.52it/s]

 23%|██▎       | 1225/5329 [01:03<03:30, 19.47it/s]

 23%|██▎       | 1227/5329 [01:03<03:30, 19.49it/s]

 23%|██▎       | 1229/5329 [01:03<03:30, 19.50it/s]

 23%|██▎       | 1231/5329 [01:03<03:30, 19.49it/s]

 23%|██▎       | 1233/5329 [01:03<03:29, 19.51it/s]

 23%|██▎       | 1235/5329 [01:03<03:29, 19.53it/s]

 23%|██▎       | 1237/5329 [01:03<03:29, 19.49it/s]

 23%|██▎       | 1239/5329 [01:03<03:30, 19.47it/s]

 23%|██▎       | 1241/5329 [01:04<03:30, 19.47it/s]

 23%|██▎       | 1243/5329 [01:04<04:42, 14.48it/s]

 23%|██▎       | 1245/5329 [01:04<04:21, 15.64it/s]

 23%|██▎       | 1247/5329 [01:04<04:06, 16.58it/s]

 23%|██▎       | 1249/5329 [01:04<03:56, 17.29it/s]

 23%|██▎       | 1251/5329 [01:04<03:48, 17.83it/s]

 24%|██▎       | 1253/5329 [01:04<03:43, 18.24it/s]

 24%|██▎       | 1255/5329 [01:04<03:39, 18.55it/s]

 24%|██▎       | 1257/5329 [01:05<03:37, 18.72it/s]

 24%|██▎       | 1260/5329 [01:05<03:15, 20.85it/s]

 24%|██▎       | 1263/5329 [01:05<03:20, 20.26it/s]

 24%|██▍       | 1266/5329 [01:05<03:25, 19.82it/s]

 24%|██▍       | 1269/5329 [01:05<03:27, 19.61it/s]

 24%|██▍       | 1271/5329 [01:05<03:28, 19.42it/s]

 24%|██▍       | 1273/5329 [01:05<03:28, 19.42it/s]

 24%|██▍       | 1275/5329 [01:05<03:28, 19.44it/s]

 24%|██▍       | 1277/5329 [01:06<03:28, 19.41it/s]

 24%|██▍       | 1279/5329 [01:06<03:28, 19.41it/s]

 24%|██▍       | 1281/5329 [01:06<03:28, 19.44it/s]

 24%|██▍       | 1283/5329 [01:06<03:27, 19.49it/s]

 24%|██▍       | 1285/5329 [01:06<03:27, 19.45it/s]

 24%|██▍       | 1287/5329 [01:06<03:27, 19.44it/s]

 24%|██▍       | 1289/5329 [01:06<03:27, 19.48it/s]

 24%|██▍       | 1291/5329 [01:06<03:27, 19.44it/s]

 24%|██▍       | 1293/5329 [01:06<03:27, 19.42it/s]

 24%|██▍       | 1295/5329 [01:06<03:27, 19.49it/s]

 24%|██▍       | 1297/5329 [01:07<03:26, 19.48it/s]

 24%|██▍       | 1299/5329 [01:07<03:27, 19.42it/s]

 24%|██▍       | 1301/5329 [01:07<03:27, 19.40it/s]

 24%|██▍       | 1303/5329 [01:07<03:27, 19.43it/s]

 24%|██▍       | 1305/5329 [01:07<03:26, 19.48it/s]

 25%|██▍       | 1307/5329 [01:07<03:26, 19.45it/s]

 25%|██▍       | 1309/5329 [01:07<03:26, 19.46it/s]

 25%|██▍       | 1311/5329 [01:07<03:25, 19.51it/s]

 25%|██▍       | 1313/5329 [01:07<03:26, 19.43it/s]

 25%|██▍       | 1315/5329 [01:07<03:27, 19.34it/s]

 25%|██▍       | 1317/5329 [01:08<03:27, 19.33it/s]

 25%|██▍       | 1319/5329 [01:08<03:27, 19.33it/s]

 25%|██▍       | 1321/5329 [01:08<03:27, 19.31it/s]

 25%|██▍       | 1323/5329 [01:08<03:27, 19.32it/s]

 25%|██▍       | 1325/5329 [01:08<03:26, 19.36it/s]

 25%|██▍       | 1327/5329 [01:08<03:27, 19.31it/s]

 25%|██▍       | 1329/5329 [01:08<03:26, 19.35it/s]

 25%|██▍       | 1331/5329 [01:08<03:27, 19.26it/s]

 25%|██▌       | 1334/5329 [01:08<03:09, 21.07it/s]

 25%|██▌       | 1337/5329 [01:09<03:15, 20.47it/s]

 25%|██▌       | 1340/5329 [01:09<03:19, 20.03it/s]

 25%|██▌       | 1343/5329 [01:09<03:21, 19.75it/s]

 25%|██▌       | 1345/5329 [01:09<03:22, 19.64it/s]

 25%|██▌       | 1347/5329 [01:09<03:23, 19.61it/s]

 25%|██▌       | 1349/5329 [01:09<03:23, 19.51it/s]

 25%|██▌       | 1351/5329 [01:09<03:23, 19.50it/s]

 25%|██▌       | 1353/5329 [01:09<03:23, 19.51it/s]

 25%|██▌       | 1355/5329 [01:10<03:23, 19.50it/s]

 25%|██▌       | 1357/5329 [01:10<03:23, 19.48it/s]

 26%|██▌       | 1359/5329 [01:10<03:23, 19.52it/s]

 26%|██▌       | 1361/5329 [01:10<03:23, 19.51it/s]

 26%|██▌       | 1363/5329 [01:10<03:24, 19.37it/s]

 26%|██▌       | 1365/5329 [01:10<03:25, 19.26it/s]

 26%|██▌       | 1367/5329 [01:10<03:24, 19.35it/s]

 26%|██▌       | 1369/5329 [01:10<03:24, 19.40it/s]

 26%|██▌       | 1371/5329 [01:10<03:23, 19.44it/s]

 26%|██▌       | 1373/5329 [01:10<03:23, 19.43it/s]

 26%|██▌       | 1375/5329 [01:11<03:23, 19.41it/s]

 26%|██▌       | 1377/5329 [01:11<03:23, 19.39it/s]

 26%|██▌       | 1379/5329 [01:11<03:22, 19.47it/s]

 26%|██▌       | 1381/5329 [01:11<03:22, 19.51it/s]

 26%|██▌       | 1383/5329 [01:11<03:22, 19.49it/s]

 26%|██▌       | 1385/5329 [01:11<03:22, 19.46it/s]

 26%|██▌       | 1387/5329 [01:11<03:22, 19.51it/s]

 26%|██▌       | 1389/5329 [01:11<03:23, 19.39it/s]

 26%|██▌       | 1391/5329 [01:11<03:23, 19.35it/s]

 26%|██▌       | 1393/5329 [01:11<03:23, 19.34it/s]

 26%|██▌       | 1395/5329 [01:12<03:23, 19.33it/s]

 26%|██▌       | 1397/5329 [01:12<03:24, 19.25it/s]

 26%|██▋       | 1399/5329 [01:12<03:24, 19.26it/s]

 26%|██▋       | 1401/5329 [01:12<03:24, 19.24it/s]

 26%|██▋       | 1403/5329 [01:12<03:25, 19.15it/s]

 26%|██▋       | 1405/5329 [01:12<03:25, 19.11it/s]

 26%|██▋       | 1408/5329 [01:12<03:04, 21.20it/s]

 26%|██▋       | 1411/5329 [01:12<03:11, 20.49it/s]

 27%|██▋       | 1414/5329 [01:13<03:14, 20.09it/s]

 27%|██▋       | 1417/5329 [01:13<03:17, 19.77it/s]

 27%|██▋       | 1420/5329 [01:13<03:18, 19.71it/s]

 27%|██▋       | 1422/5329 [01:13<03:18, 19.64it/s]

 27%|██▋       | 1424/5329 [01:13<03:20, 19.51it/s]

 27%|██▋       | 1426/5329 [01:13<03:19, 19.52it/s]

 27%|██▋       | 1428/5329 [01:13<03:19, 19.54it/s]

 27%|██▋       | 1430/5329 [01:13<03:19, 19.50it/s]

 27%|██▋       | 1432/5329 [01:13<03:20, 19.46it/s]

 27%|██▋       | 1434/5329 [01:14<03:20, 19.46it/s]

 27%|██▋       | 1436/5329 [01:14<03:20, 19.42it/s]

 27%|██▋       | 1438/5329 [01:14<03:20, 19.37it/s]

 27%|██▋       | 1440/5329 [01:14<03:20, 19.39it/s]

 27%|██▋       | 1442/5329 [01:14<03:20, 19.43it/s]

 27%|██▋       | 1444/5329 [01:14<03:20, 19.41it/s]

 27%|██▋       | 1446/5329 [01:14<03:20, 19.38it/s]

 27%|██▋       | 1448/5329 [01:14<03:20, 19.38it/s]

 27%|██▋       | 1450/5329 [01:14<03:20, 19.39it/s]

 27%|██▋       | 1452/5329 [01:14<03:20, 19.38it/s]

 27%|██▋       | 1454/5329 [01:15<03:19, 19.38it/s]

 27%|██▋       | 1456/5329 [01:15<03:19, 19.38it/s]

 27%|██▋       | 1458/5329 [01:15<03:20, 19.31it/s]

 27%|██▋       | 1460/5329 [01:15<03:20, 19.30it/s]

 27%|██▋       | 1462/5329 [01:15<03:20, 19.30it/s]

 27%|██▋       | 1464/5329 [01:15<03:20, 19.31it/s]

 28%|██▊       | 1466/5329 [01:15<03:20, 19.30it/s]

 28%|██▊       | 1468/5329 [01:15<03:20, 19.28it/s]

 28%|██▊       | 1470/5329 [01:15<03:20, 19.27it/s]

 28%|██▊       | 1472/5329 [01:16<03:20, 19.25it/s]

 28%|██▊       | 1474/5329 [01:16<03:20, 19.25it/s]

 28%|██▊       | 1476/5329 [01:16<03:20, 19.21it/s]

 28%|██▊       | 1478/5329 [01:16<03:21, 19.12it/s]

 28%|██▊       | 1480/5329 [01:16<03:22, 19.05it/s]

 28%|██▊       | 1483/5329 [01:16<03:01, 21.14it/s]

 28%|██▊       | 1486/5329 [01:16<03:07, 20.51it/s]

 28%|██▊       | 1489/5329 [01:16<03:11, 20.08it/s]

 28%|██▊       | 1492/5329 [01:17<03:13, 19.83it/s]

 28%|██▊       | 1495/5329 [01:17<03:14, 19.72it/s]

 28%|██▊       | 1497/5329 [01:17<03:14, 19.65it/s]

 28%|██▊       | 1499/5329 [01:17<03:15, 19.62it/s]

 28%|██▊       | 1501/5329 [01:17<03:15, 19.56it/s]

 28%|██▊       | 1503/5329 [01:17<03:15, 19.55it/s]

 28%|██▊       | 1505/5329 [01:17<03:15, 19.56it/s]

 28%|██▊       | 1507/5329 [01:17<03:16, 19.50it/s]

 28%|██▊       | 1509/5329 [01:17<03:16, 19.43it/s]

 28%|██▊       | 1511/5329 [01:17<03:16, 19.39it/s]

 28%|██▊       | 1513/5329 [01:18<03:16, 19.37it/s]

 28%|██▊       | 1515/5329 [01:18<03:16, 19.38it/s]

 28%|██▊       | 1517/5329 [01:18<03:16, 19.42it/s]

 29%|██▊       | 1519/5329 [01:18<03:16, 19.43it/s]

 29%|██▊       | 1521/5329 [01:18<03:16, 19.40it/s]

 29%|██▊       | 1523/5329 [01:18<03:15, 19.45it/s]

 29%|██▊       | 1525/5329 [01:18<03:15, 19.47it/s]

 29%|██▊       | 1527/5329 [01:18<03:15, 19.46it/s]

 29%|██▊       | 1529/5329 [01:18<03:15, 19.44it/s]

 29%|██▊       | 1531/5329 [01:19<03:15, 19.40it/s]

 29%|██▉       | 1533/5329 [01:19<03:14, 19.47it/s]

 29%|██▉       | 1535/5329 [01:19<03:15, 19.41it/s]

 29%|██▉       | 1537/5329 [01:19<03:15, 19.40it/s]

 29%|██▉       | 1539/5329 [01:19<03:15, 19.41it/s]

 29%|██▉       | 1541/5329 [01:19<03:15, 19.35it/s]

 29%|██▉       | 1543/5329 [01:19<03:16, 19.31it/s]

 29%|██▉       | 1545/5329 [01:19<03:15, 19.33it/s]

 29%|██▉       | 1547/5329 [01:19<03:15, 19.33it/s]

 29%|██▉       | 1549/5329 [01:19<03:17, 19.13it/s]

 29%|██▉       | 1551/5329 [01:20<03:18, 19.07it/s]

 29%|██▉       | 1553/5329 [01:20<03:18, 19.04it/s]

 29%|██▉       | 1556/5329 [01:20<02:58, 21.11it/s]

 29%|██▉       | 1559/5329 [01:20<03:04, 20.48it/s]

 29%|██▉       | 1562/5329 [01:20<03:07, 20.06it/s]

 29%|██▉       | 1565/5329 [01:20<03:09, 19.84it/s]

 29%|██▉       | 1568/5329 [01:20<03:10, 19.78it/s]

 29%|██▉       | 1570/5329 [01:20<03:11, 19.66it/s]

 29%|██▉       | 1572/5329 [01:21<03:11, 19.62it/s]

 30%|██▉       | 1574/5329 [01:21<03:11, 19.58it/s]

 30%|██▉       | 1576/5329 [01:21<03:12, 19.51it/s]

 30%|██▉       | 1578/5329 [01:21<03:12, 19.49it/s]

 30%|██▉       | 1580/5329 [01:21<03:12, 19.50it/s]

 30%|██▉       | 1582/5329 [01:21<03:12, 19.49it/s]

 30%|██▉       | 1584/5329 [01:21<03:12, 19.48it/s]

 30%|██▉       | 1586/5329 [01:21<03:11, 19.51it/s]

 30%|██▉       | 1588/5329 [01:21<03:11, 19.51it/s]

 30%|██▉       | 1590/5329 [01:22<03:12, 19.45it/s]

 30%|██▉       | 1592/5329 [01:22<03:12, 19.44it/s]

 30%|██▉       | 1594/5329 [01:22<03:12, 19.45it/s]

 30%|██▉       | 1596/5329 [01:22<03:11, 19.46it/s]

 30%|██▉       | 1598/5329 [01:22<03:11, 19.44it/s]

 30%|███       | 1600/5329 [01:22<03:11, 19.47it/s]

 30%|███       | 1602/5329 [01:22<03:11, 19.50it/s]

 30%|███       | 1604/5329 [01:22<03:11, 19.44it/s]

 30%|███       | 1606/5329 [01:22<03:11, 19.46it/s]

 30%|███       | 1608/5329 [01:22<03:11, 19.44it/s]

 30%|███       | 1610/5329 [01:23<03:12, 19.36it/s]

 30%|███       | 1612/5329 [01:23<03:12, 19.32it/s]

 30%|███       | 1614/5329 [01:23<03:12, 19.30it/s]

 30%|███       | 1616/5329 [01:23<03:12, 19.29it/s]

 30%|███       | 1618/5329 [01:23<03:12, 19.29it/s]

 30%|███       | 1620/5329 [01:23<03:11, 19.34it/s]

 30%|███       | 1622/5329 [01:23<03:13, 19.18it/s]

 30%|███       | 1624/5329 [01:23<03:14, 19.06it/s]

 31%|███       | 1626/5329 [01:23<03:14, 19.02it/s]

 31%|███       | 1628/5329 [01:23<03:14, 19.02it/s]

 31%|███       | 1631/5329 [01:24<02:54, 21.13it/s]

 31%|███       | 1634/5329 [01:24<03:00, 20.49it/s]

 31%|███       | 1637/5329 [01:24<03:03, 20.14it/s]

 31%|███       | 1640/5329 [01:24<03:04, 19.96it/s]

 31%|███       | 1643/5329 [01:24<03:05, 19.88it/s]

 31%|███       | 1646/5329 [01:24<03:05, 19.81it/s]

 31%|███       | 1648/5329 [01:24<03:07, 19.68it/s]

 31%|███       | 1650/5329 [01:25<03:07, 19.63it/s]

 31%|███       | 1652/5329 [01:25<03:07, 19.56it/s]

 31%|███       | 1654/5329 [01:25<03:08, 19.49it/s]

 31%|███       | 1656/5329 [01:25<03:08, 19.52it/s]

 31%|███       | 1658/5329 [01:25<03:08, 19.51it/s]

 31%|███       | 1660/5329 [01:25<03:07, 19.52it/s]

 31%|███       | 1662/5329 [01:25<03:07, 19.53it/s]

 31%|███       | 1664/5329 [01:25<03:07, 19.59it/s]

 31%|███▏      | 1666/5329 [01:25<03:07, 19.57it/s]

 31%|███▏      | 1668/5329 [01:25<03:07, 19.54it/s]

 31%|███▏      | 1670/5329 [01:26<03:07, 19.56it/s]

 31%|███▏      | 1672/5329 [01:26<03:06, 19.56it/s]

 31%|███▏      | 1674/5329 [01:26<03:07, 19.54it/s]

 31%|███▏      | 1676/5329 [01:26<03:06, 19.56it/s]

 31%|███▏      | 1678/5329 [01:26<03:06, 19.55it/s]

 32%|███▏      | 1680/5329 [01:26<03:07, 19.50it/s]

 32%|███▏      | 1682/5329 [01:26<03:07, 19.49it/s]

 32%|███▏      | 1684/5329 [01:26<03:06, 19.51it/s]

 32%|███▏      | 1686/5329 [01:26<03:07, 19.47it/s]

 32%|███▏      | 1688/5329 [01:27<03:07, 19.42it/s]

 32%|███▏      | 1690/5329 [01:27<03:07, 19.41it/s]

 32%|███▏      | 1692/5329 [01:27<03:08, 19.34it/s]

 32%|███▏      | 1694/5329 [01:27<03:08, 19.32it/s]

 32%|███▏      | 1696/5329 [01:27<03:08, 19.27it/s]

 32%|███▏      | 1698/5329 [01:27<03:08, 19.25it/s]

 32%|███▏      | 1700/5329 [01:27<03:09, 19.17it/s]

 32%|███▏      | 1702/5329 [01:27<03:09, 19.11it/s]

 32%|███▏      | 1705/5329 [01:27<02:50, 21.21it/s]

 32%|███▏      | 1708/5329 [01:28<02:56, 20.52it/s]

 32%|███▏      | 1711/5329 [01:28<02:59, 20.14it/s]

 32%|███▏      | 1714/5329 [01:28<03:01, 19.94it/s]

 32%|███▏      | 1717/5329 [01:28<03:02, 19.75it/s]

 32%|███▏      | 1719/5329 [01:28<03:03, 19.68it/s]

 32%|███▏      | 1721/5329 [01:28<03:03, 19.63it/s]

 32%|███▏      | 1723/5329 [01:28<03:04, 19.55it/s]

 32%|███▏      | 1725/5329 [01:28<03:04, 19.53it/s]

 32%|███▏      | 1727/5329 [01:28<03:04, 19.51it/s]

 32%|███▏      | 1729/5329 [01:29<03:04, 19.50it/s]

 32%|███▏      | 1731/5329 [01:29<03:04, 19.50it/s]

 33%|███▎      | 1733/5329 [01:29<03:05, 19.44it/s]

 33%|███▎      | 1735/5329 [01:29<03:04, 19.46it/s]

 33%|███▎      | 1737/5329 [01:29<03:04, 19.47it/s]

 33%|███▎      | 1739/5329 [01:29<03:04, 19.51it/s]

 33%|███▎      | 1741/5329 [01:29<03:03, 19.55it/s]

 33%|███▎      | 1743/5329 [01:29<03:03, 19.56it/s]

 33%|███▎      | 1745/5329 [01:29<03:02, 19.60it/s]

 33%|███▎      | 1747/5329 [01:30<03:02, 19.61it/s]

 33%|███▎      | 1749/5329 [01:30<03:03, 19.54it/s]

 33%|███▎      | 1751/5329 [01:30<03:04, 19.38it/s]

 33%|███▎      | 1753/5329 [01:30<03:04, 19.41it/s]

 33%|███▎      | 1755/5329 [01:30<03:04, 19.39it/s]

 33%|███▎      | 1757/5329 [01:30<03:04, 19.37it/s]

 33%|███▎      | 1759/5329 [01:30<03:04, 19.39it/s]

 33%|███▎      | 1761/5329 [01:30<03:04, 19.38it/s]

 33%|███▎      | 1763/5329 [01:30<03:04, 19.36it/s]

 33%|███▎      | 1765/5329 [01:30<03:04, 19.33it/s]

 33%|███▎      | 1767/5329 [01:31<03:04, 19.33it/s]

 33%|███▎      | 1769/5329 [01:31<03:04, 19.25it/s]

 33%|███▎      | 1771/5329 [01:31<03:05, 19.15it/s]

 33%|███▎      | 1773/5329 [01:31<03:06, 19.12it/s]

 33%|███▎      | 1775/5329 [01:31<03:06, 19.05it/s]

 33%|███▎      | 1778/5329 [01:31<02:47, 21.15it/s]

 33%|███▎      | 1781/5329 [01:31<02:52, 20.51it/s]

 33%|███▎      | 1784/5329 [01:31<02:55, 20.18it/s]

 34%|███▎      | 1787/5329 [01:32<02:57, 19.98it/s]

 34%|███▎      | 1790/5329 [01:32<02:58, 19.85it/s]

 34%|███▎      | 1793/5329 [01:32<02:59, 19.73it/s]

 34%|███▎      | 1795/5329 [01:32<03:00, 19.62it/s]

 34%|███▎      | 1797/5329 [01:32<03:00, 19.61it/s]

 34%|███▍      | 1799/5329 [01:32<03:00, 19.57it/s]

 34%|███▍      | 1801/5329 [01:32<03:00, 19.58it/s]

 34%|███▍      | 1803/5329 [01:32<03:00, 19.56it/s]

 34%|███▍      | 1805/5329 [01:32<03:00, 19.54it/s]

 34%|███▍      | 1807/5329 [01:33<03:00, 19.56it/s]

 34%|███▍      | 1809/5329 [01:33<03:00, 19.55it/s]

 34%|███▍      | 1811/5329 [01:33<03:00, 19.54it/s]

 34%|███▍      | 1813/5329 [01:33<03:00, 19.50it/s]

 34%|███▍      | 1815/5329 [01:33<02:59, 19.53it/s]

 34%|███▍      | 1817/5329 [01:33<02:59, 19.56it/s]

 34%|███▍      | 1819/5329 [01:33<02:59, 19.51it/s]

 34%|███▍      | 1821/5329 [01:33<02:59, 19.54it/s]

 34%|███▍      | 1823/5329 [01:33<02:59, 19.49it/s]

 34%|███▍      | 1825/5329 [01:33<03:00, 19.45it/s]

 34%|███▍      | 1827/5329 [01:34<03:00, 19.40it/s]

 34%|███▍      | 1829/5329 [01:34<03:00, 19.41it/s]

 34%|███▍      | 1831/5329 [01:34<03:00, 19.36it/s]

 34%|███▍      | 1833/5329 [01:34<03:00, 19.32it/s]

 34%|███▍      | 1835/5329 [01:34<03:00, 19.33it/s]

 34%|███▍      | 1837/5329 [01:34<03:00, 19.38it/s]

 35%|███▍      | 1839/5329 [01:34<03:00, 19.35it/s]

 35%|███▍      | 1841/5329 [01:34<03:00, 19.33it/s]

 35%|███▍      | 1843/5329 [01:34<03:00, 19.29it/s]

 35%|███▍      | 1845/5329 [01:35<03:02, 19.13it/s]

 35%|███▍      | 1847/5329 [01:35<03:01, 19.13it/s]

 35%|███▍      | 1849/5329 [01:35<03:01, 19.13it/s]

 35%|███▍      | 1852/5329 [01:35<02:43, 21.25it/s]

 35%|███▍      | 1855/5329 [01:35<02:49, 20.52it/s]

 35%|███▍      | 1858/5329 [01:35<02:51, 20.26it/s]

 35%|███▍      | 1861/5329 [01:35<02:52, 20.06it/s]

 35%|███▍      | 1864/5329 [01:35<02:53, 19.93it/s]

 35%|███▌      | 1867/5329 [01:36<02:54, 19.81it/s]

 35%|███▌      | 1869/5329 [01:36<02:55, 19.72it/s]

 35%|███▌      | 1871/5329 [01:36<02:56, 19.57it/s]

 35%|███▌      | 1873/5329 [01:36<02:56, 19.55it/s]

 35%|███▌      | 1875/5329 [01:36<02:56, 19.52it/s]

 35%|███▌      | 1877/5329 [01:36<02:56, 19.56it/s]

 35%|███▌      | 1879/5329 [01:36<02:56, 19.60it/s]

 35%|███▌      | 1881/5329 [01:36<02:55, 19.60it/s]

 35%|███▌      | 1883/5329 [01:36<02:55, 19.58it/s]

 35%|███▌      | 1885/5329 [01:37<02:55, 19.59it/s]

 35%|███▌      | 1887/5329 [01:37<02:55, 19.58it/s]

 35%|███▌      | 1889/5329 [01:37<02:55, 19.56it/s]

 35%|███▌      | 1891/5329 [01:37<02:55, 19.56it/s]

 36%|███▌      | 1893/5329 [01:37<02:55, 19.57it/s]

 36%|███▌      | 1895/5329 [01:37<02:55, 19.56it/s]

 36%|███▌      | 1897/5329 [01:37<02:55, 19.55it/s]

 36%|███▌      | 1899/5329 [01:37<02:55, 19.52it/s]

 36%|███▌      | 1901/5329 [01:37<02:55, 19.48it/s]

 36%|███▌      | 1903/5329 [01:37<02:56, 19.36it/s]

 36%|███▌      | 1905/5329 [01:38<02:56, 19.35it/s]

 36%|███▌      | 1907/5329 [01:38<02:56, 19.35it/s]

 36%|███▌      | 1909/5329 [01:38<02:57, 19.22it/s]

 36%|███▌      | 1911/5329 [01:38<02:57, 19.21it/s]

 36%|███▌      | 1913/5329 [01:38<02:57, 19.26it/s]

 36%|███▌      | 1915/5329 [01:38<02:57, 19.21it/s]

 36%|███▌      | 1917/5329 [01:38<02:58, 19.11it/s]

 36%|███▌      | 1919/5329 [01:38<02:58, 19.13it/s]

 36%|███▌      | 1921/5329 [01:38<02:58, 19.12it/s]

 36%|███▌      | 1923/5329 [01:39<02:58, 19.11it/s]

 36%|███▌      | 1926/5329 [01:39<02:40, 21.21it/s]

 36%|███▌      | 1929/5329 [01:39<02:45, 20.57it/s]

 36%|███▋      | 1932/5329 [01:39<02:47, 20.23it/s]

 36%|███▋      | 1935/5329 [01:39<02:49, 20.07it/s]

 36%|███▋      | 1938/5329 [01:39<02:50, 19.92it/s]

 36%|███▋      | 1941/5329 [01:39<02:50, 19.83it/s]

 36%|███▋      | 1943/5329 [01:39<02:51, 19.73it/s]

 36%|███▋      | 1945/5329 [01:40<02:52, 19.65it/s]

 37%|███▋      | 1947/5329 [01:40<02:52, 19.60it/s]

 37%|███▋      | 1949/5329 [01:40<02:53, 19.52it/s]

 37%|███▋      | 1951/5329 [01:40<02:54, 19.38it/s]

 37%|███▋      | 1953/5329 [01:40<02:54, 19.40it/s]

 37%|███▋      | 1955/5329 [01:40<02:53, 19.42it/s]

 37%|███▋      | 1957/5329 [01:40<02:53, 19.40it/s]

 37%|███▋      | 1959/5329 [01:40<02:53, 19.41it/s]

 37%|███▋      | 1961/5329 [01:40<02:53, 19.43it/s]

 37%|███▋      | 1963/5329 [01:41<02:53, 19.44it/s]

 37%|███▋      | 1965/5329 [01:41<02:53, 19.37it/s]

 37%|███▋      | 1967/5329 [01:41<02:53, 19.42it/s]

 37%|███▋      | 1969/5329 [01:41<02:53, 19.39it/s]

 37%|███▋      | 1971/5329 [01:41<02:53, 19.37it/s]

 37%|███▋      | 1973/5329 [01:41<02:53, 19.36it/s]

 37%|███▋      | 1975/5329 [01:41<02:53, 19.33it/s]

 37%|███▋      | 1977/5329 [01:41<02:53, 19.32it/s]

 37%|███▋      | 1979/5329 [01:41<02:53, 19.30it/s]

 37%|███▋      | 1981/5329 [01:41<02:53, 19.30it/s]

 37%|███▋      | 1983/5329 [01:42<02:53, 19.30it/s]

 37%|███▋      | 1985/5329 [01:42<02:53, 19.27it/s]

 37%|███▋      | 1987/5329 [01:42<02:53, 19.24it/s]

 37%|███▋      | 1989/5329 [01:42<02:54, 19.15it/s]

 37%|███▋      | 1991/5329 [01:42<02:55, 18.97it/s]

 37%|███▋      | 1993/5329 [01:42<02:55, 18.98it/s]

 37%|███▋      | 1995/5329 [01:42<02:55, 18.99it/s]

 37%|███▋      | 1997/5329 [01:42<02:55, 18.98it/s]

 38%|███▊      | 2000/5329 [01:42<02:38, 21.04it/s]

 38%|███▊      | 2003/5329 [01:43<02:42, 20.52it/s]

 38%|███▊      | 2006/5329 [01:43<02:44, 20.17it/s]

 38%|███▊      | 2009/5329 [01:43<02:47, 19.81it/s]

 38%|███▊      | 2012/5329 [01:43<02:48, 19.71it/s]

 38%|███▊      | 2014/5329 [01:43<02:49, 19.57it/s]

 38%|███▊      | 2016/5329 [01:43<02:49, 19.56it/s]

 38%|███▊      | 2018/5329 [01:43<02:49, 19.49it/s]

 38%|███▊      | 2020/5329 [01:43<02:50, 19.44it/s]

 38%|███▊      | 2022/5329 [01:44<02:49, 19.46it/s]

 38%|███▊      | 2024/5329 [01:44<02:49, 19.47it/s]

 38%|███▊      | 2026/5329 [01:44<02:50, 19.42it/s]

 38%|███▊      | 2028/5329 [01:44<02:51, 19.24it/s]

 38%|███▊      | 2030/5329 [01:44<02:50, 19.31it/s]

 38%|███▊      | 2032/5329 [01:44<02:50, 19.36it/s]

 38%|███▊      | 2034/5329 [01:44<02:50, 19.34it/s]

 38%|███▊      | 2036/5329 [01:44<02:49, 19.40it/s]

 38%|███▊      | 2038/5329 [01:44<02:49, 19.39it/s]

 38%|███▊      | 2040/5329 [01:44<02:50, 19.32it/s]

 38%|███▊      | 2042/5329 [01:45<02:51, 19.14it/s]

 38%|███▊      | 2044/5329 [01:45<02:50, 19.24it/s]

 38%|███▊      | 2046/5329 [01:45<02:51, 19.19it/s]

 38%|███▊      | 2048/5329 [01:45<02:51, 19.14it/s]

 38%|███▊      | 2050/5329 [01:45<02:51, 19.13it/s]

 39%|███▊      | 2052/5329 [01:45<02:51, 19.11it/s]

 39%|███▊      | 2054/5329 [01:45<02:51, 19.12it/s]

 39%|███▊      | 2056/5329 [01:45<02:51, 19.12it/s]

 39%|███▊      | 2058/5329 [01:45<02:51, 19.10it/s]

 39%|███▊      | 2060/5329 [01:46<02:51, 19.11it/s]

 39%|███▊      | 2062/5329 [01:46<02:51, 19.02it/s]

 39%|███▊      | 2064/5329 [01:46<02:52, 18.97it/s]

 39%|███▉      | 2066/5329 [01:46<02:53, 18.82it/s]

 39%|███▉      | 2068/5329 [01:46<02:53, 18.85it/s]

 39%|███▉      | 2070/5329 [01:46<02:52, 18.86it/s]

 39%|███▉      | 2072/5329 [01:46<02:52, 18.88it/s]

 39%|███▉      | 2075/5329 [01:46<02:34, 21.03it/s]

 39%|███▉      | 2078/5329 [01:46<02:38, 20.54it/s]

 39%|███▉      | 2081/5329 [01:47<02:41, 20.12it/s]

 39%|███▉      | 2084/5329 [01:47<02:43, 19.88it/s]

 39%|███▉      | 2087/5329 [01:47<02:44, 19.74it/s]

 39%|███▉      | 2089/5329 [01:47<02:44, 19.64it/s]

 39%|███▉      | 2091/5329 [01:47<02:45, 19.57it/s]

 39%|███▉      | 2093/5329 [01:47<02:45, 19.50it/s]

 39%|███▉      | 2095/5329 [01:47<02:46, 19.47it/s]

 39%|███▉      | 2097/5329 [01:47<02:46, 19.44it/s]

 39%|███▉      | 2099/5329 [01:47<02:46, 19.38it/s]

 39%|███▉      | 2101/5329 [01:48<02:46, 19.35it/s]

 39%|███▉      | 2103/5329 [01:48<02:46, 19.35it/s]

 40%|███▉      | 2105/5329 [01:48<02:48, 19.17it/s]

 40%|███▉      | 2107/5329 [01:48<02:47, 19.24it/s]

 40%|███▉      | 2109/5329 [01:48<02:46, 19.31it/s]

 40%|███▉      | 2111/5329 [01:48<02:46, 19.34it/s]

 40%|███▉      | 2113/5329 [01:48<02:46, 19.35it/s]

 40%|███▉      | 2115/5329 [01:48<02:46, 19.31it/s]

 40%|███▉      | 2117/5329 [01:48<02:46, 19.34it/s]

 40%|███▉      | 2119/5329 [01:49<02:46, 19.30it/s]

 40%|███▉      | 2121/5329 [01:49<02:46, 19.30it/s]

 40%|███▉      | 2123/5329 [01:49<02:46, 19.28it/s]

 40%|███▉      | 2125/5329 [01:49<02:46, 19.22it/s]

 40%|███▉      | 2127/5329 [01:49<02:46, 19.21it/s]

 40%|███▉      | 2129/5329 [01:49<02:46, 19.17it/s]

 40%|███▉      | 2131/5329 [01:49<02:46, 19.16it/s]

 40%|████      | 2133/5329 [01:49<02:46, 19.15it/s]

 40%|████      | 2135/5329 [01:49<02:46, 19.13it/s]

 40%|████      | 2137/5329 [01:49<02:47, 19.10it/s]

 40%|████      | 2139/5329 [01:50<02:47, 19.05it/s]

 40%|████      | 2141/5329 [01:50<02:46, 19.10it/s]

 40%|████      | 2143/5329 [01:50<02:46, 19.14it/s]

 40%|████      | 2145/5329 [01:50<02:46, 19.09it/s]

 40%|████      | 2148/5329 [01:50<02:29, 21.25it/s]

 40%|████      | 2151/5329 [01:50<02:33, 20.67it/s]

 40%|████      | 2154/5329 [01:50<02:36, 20.30it/s]

 40%|████      | 2157/5329 [01:50<02:37, 20.13it/s]

 41%|████      | 2160/5329 [01:51<02:38, 19.97it/s]

 41%|████      | 2163/5329 [01:51<02:39, 19.87it/s]

 41%|████      | 2166/5329 [01:51<02:39, 19.79it/s]

 41%|████      | 2168/5329 [01:51<02:40, 19.69it/s]

 41%|████      | 2170/5329 [01:51<02:41, 19.59it/s]

 41%|████      | 2172/5329 [01:51<02:41, 19.60it/s]

 41%|████      | 2174/5329 [01:51<02:41, 19.54it/s]

 41%|████      | 2176/5329 [01:51<02:41, 19.51it/s]

 41%|████      | 2178/5329 [01:52<02:41, 19.54it/s]

 41%|████      | 2180/5329 [01:52<02:41, 19.51it/s]

 41%|████      | 2182/5329 [01:52<02:41, 19.54it/s]

 41%|████      | 2184/5329 [01:52<02:40, 19.56it/s]

 41%|████      | 2186/5329 [01:52<02:41, 19.49it/s]

 41%|████      | 2188/5329 [01:52<02:41, 19.46it/s]

 41%|████      | 2190/5329 [01:52<02:41, 19.48it/s]

 41%|████      | 2192/5329 [01:52<02:40, 19.53it/s]

 41%|████      | 2194/5329 [01:52<02:42, 19.31it/s]

 41%|████      | 2196/5329 [01:52<02:44, 19.09it/s]

 41%|████      | 2198/5329 [01:53<02:44, 19.01it/s]

 41%|████▏     | 2200/5329 [01:53<02:44, 19.03it/s]

 41%|████▏     | 2202/5329 [01:53<02:44, 19.01it/s]

 41%|████▏     | 2204/5329 [01:53<02:44, 19.04it/s]

 41%|████▏     | 2206/5329 [01:53<02:43, 19.07it/s]

 41%|████▏     | 2208/5329 [01:53<02:42, 19.23it/s]

 41%|████▏     | 2210/5329 [01:53<02:42, 19.17it/s]

 42%|████▏     | 2212/5329 [01:53<02:42, 19.22it/s]

 42%|████▏     | 2214/5329 [01:53<02:41, 19.28it/s]

 42%|████▏     | 2216/5329 [01:53<02:41, 19.29it/s]

 42%|████▏     | 2218/5329 [01:54<02:40, 19.38it/s]

 42%|████▏     | 2220/5329 [01:54<02:40, 19.43it/s]

 42%|████▏     | 2223/5329 [01:54<02:24, 21.47it/s]

 42%|████▏     | 2226/5329 [01:54<02:29, 20.71it/s]

 42%|████▏     | 2229/5329 [01:54<02:32, 20.27it/s]

 42%|████▏     | 2232/5329 [01:54<02:34, 20.00it/s]

 42%|████▏     | 2235/5329 [01:54<02:36, 19.80it/s]

 42%|████▏     | 2237/5329 [01:55<02:37, 19.61it/s]

 42%|████▏     | 2239/5329 [01:55<02:38, 19.52it/s]

 42%|████▏     | 2241/5329 [01:55<02:39, 19.41it/s]

 42%|████▏     | 2243/5329 [01:55<02:41, 19.08it/s]

 42%|████▏     | 2245/5329 [01:55<02:41, 19.04it/s]

 42%|████▏     | 2247/5329 [01:55<02:41, 19.05it/s]

 42%|████▏     | 2249/5329 [01:55<02:41, 19.04it/s]

 42%|████▏     | 2251/5329 [01:55<02:42, 18.98it/s]

 42%|████▏     | 2253/5329 [01:55<02:42, 18.92it/s]

 42%|████▏     | 2255/5329 [01:55<02:42, 18.97it/s]

 42%|████▏     | 2257/5329 [01:56<02:41, 19.02it/s]

 42%|████▏     | 2259/5329 [01:56<02:40, 19.09it/s]

 42%|████▏     | 2261/5329 [01:56<02:40, 19.07it/s]

 42%|████▏     | 2263/5329 [01:56<02:42, 18.85it/s]

 43%|████▎     | 2265/5329 [01:56<02:41, 18.98it/s]

 43%|████▎     | 2267/5329 [01:56<02:41, 18.98it/s]

 43%|████▎     | 2269/5329 [01:56<02:41, 18.95it/s]

 43%|████▎     | 2271/5329 [01:56<02:41, 18.96it/s]

 43%|████▎     | 2273/5329 [01:56<02:40, 19.00it/s]

 43%|████▎     | 2275/5329 [01:57<02:40, 19.00it/s]

 43%|████▎     | 2277/5329 [01:57<02:39, 19.10it/s]

 43%|████▎     | 2279/5329 [01:57<02:38, 19.21it/s]

 43%|████▎     | 2281/5329 [01:57<02:39, 19.15it/s]

 43%|████▎     | 2283/5329 [01:57<02:39, 19.14it/s]

 43%|████▎     | 2285/5329 [01:57<02:39, 19.11it/s]

 43%|████▎     | 2287/5329 [01:57<02:39, 19.11it/s]

 43%|████▎     | 2289/5329 [01:57<02:39, 19.05it/s]

 43%|████▎     | 2291/5329 [01:57<02:39, 19.04it/s]

 43%|████▎     | 2293/5329 [01:57<02:38, 19.09it/s]

 43%|████▎     | 2296/5329 [01:58<02:23, 21.11it/s]

 43%|████▎     | 2299/5329 [01:58<02:29, 20.25it/s]

 43%|████▎     | 2302/5329 [01:58<02:34, 19.63it/s]

 43%|████▎     | 2305/5329 [01:58<02:36, 19.36it/s]

 43%|████▎     | 2307/5329 [01:58<02:37, 19.21it/s]

 43%|████▎     | 2309/5329 [01:58<02:37, 19.15it/s]

 43%|████▎     | 2311/5329 [01:58<02:38, 19.03it/s]

 43%|████▎     | 2313/5329 [01:58<02:40, 18.82it/s]

 43%|████▎     | 2315/5329 [01:59<02:40, 18.80it/s]

 43%|████▎     | 2317/5329 [01:59<02:38, 18.97it/s]

 44%|████▎     | 2319/5329 [01:59<02:39, 18.92it/s]

 44%|████▎     | 2321/5329 [01:59<02:38, 18.92it/s]

 44%|████▎     | 2323/5329 [01:59<02:38, 19.01it/s]

 44%|████▎     | 2325/5329 [01:59<02:37, 19.07it/s]

 44%|████▎     | 2327/5329 [01:59<02:37, 19.09it/s]

 44%|████▎     | 2329/5329 [01:59<02:36, 19.11it/s]

 44%|████▎     | 2331/5329 [01:59<02:37, 19.09it/s]

 44%|████▍     | 2333/5329 [02:00<02:38, 18.95it/s]

 44%|████▍     | 2335/5329 [02:00<02:38, 18.86it/s]

 44%|████▍     | 2337/5329 [02:00<02:37, 18.97it/s]

 44%|████▍     | 2339/5329 [02:00<02:36, 19.07it/s]

 44%|████▍     | 2341/5329 [02:00<02:36, 19.13it/s]

 44%|████▍     | 2343/5329 [02:00<02:37, 18.91it/s]

 44%|████▍     | 2345/5329 [02:00<02:38, 18.87it/s]

 44%|████▍     | 2347/5329 [02:00<02:38, 18.76it/s]

 44%|████▍     | 2349/5329 [02:00<02:38, 18.82it/s]

 44%|████▍     | 2351/5329 [02:00<02:36, 19.03it/s]

 44%|████▍     | 2353/5329 [02:01<02:35, 19.10it/s]

 44%|████▍     | 2355/5329 [02:01<02:36, 18.98it/s]

 44%|████▍     | 2357/5329 [02:01<02:35, 19.13it/s]

 44%|████▍     | 2359/5329 [02:01<02:35, 19.10it/s]

 44%|████▍     | 2361/5329 [02:01<02:34, 19.21it/s]

 44%|████▍     | 2363/5329 [02:01<02:33, 19.31it/s]

 44%|████▍     | 2365/5329 [02:01<02:33, 19.32it/s]

 44%|████▍     | 2367/5329 [02:01<02:34, 19.20it/s]

 44%|████▍     | 2370/5329 [02:01<02:19, 21.20it/s]

 45%|████▍     | 2373/5329 [02:02<02:23, 20.55it/s]

 45%|████▍     | 2376/5329 [02:02<02:26, 20.11it/s]

 45%|████▍     | 2379/5329 [02:02<02:30, 19.56it/s]

 45%|████▍     | 2381/5329 [02:02<02:34, 19.04it/s]

 45%|████▍     | 2383/5329 [02:02<02:36, 18.78it/s]

 45%|████▍     | 2385/5329 [02:02<02:36, 18.79it/s]

 45%|████▍     | 2387/5329 [02:02<02:36, 18.86it/s]

 45%|████▍     | 2389/5329 [02:02<02:35, 18.90it/s]

 45%|████▍     | 2391/5329 [02:03<02:36, 18.83it/s]

 45%|████▍     | 2393/5329 [02:03<02:35, 18.87it/s]

 45%|████▍     | 2395/5329 [02:03<02:34, 18.95it/s]

 45%|████▍     | 2397/5329 [02:03<02:36, 18.70it/s]

 45%|████▌     | 2399/5329 [02:03<02:36, 18.77it/s]

 45%|████▌     | 2401/5329 [02:03<02:34, 18.91it/s]

 45%|████▌     | 2403/5329 [02:03<02:34, 18.97it/s]

 45%|████▌     | 2405/5329 [02:03<02:33, 19.05it/s]

 45%|████▌     | 2407/5329 [02:03<02:33, 19.02it/s]

 45%|████▌     | 2409/5329 [02:04<02:33, 19.06it/s]

 45%|████▌     | 2411/5329 [02:04<02:32, 19.13it/s]

 45%|████▌     | 2413/5329 [02:04<02:31, 19.21it/s]

 45%|████▌     | 2415/5329 [02:04<02:31, 19.26it/s]

 45%|████▌     | 2417/5329 [02:04<02:32, 19.09it/s]

 45%|████▌     | 2419/5329 [02:04<02:32, 19.08it/s]

 45%|████▌     | 2421/5329 [02:04<02:32, 19.09it/s]

 45%|████▌     | 2423/5329 [02:04<02:33, 18.97it/s]

 46%|████▌     | 2425/5329 [02:04<02:33, 18.97it/s]

 46%|████▌     | 2427/5329 [02:04<02:32, 19.00it/s]

 46%|████▌     | 2429/5329 [02:05<02:32, 19.02it/s]

 46%|████▌     | 2431/5329 [02:05<02:33, 18.83it/s]

 46%|████▌     | 2433/5329 [02:05<02:33, 18.90it/s]

 46%|████▌     | 2435/5329 [02:05<02:33, 18.90it/s]

 46%|████▌     | 2437/5329 [02:05<02:34, 18.75it/s]

 46%|████▌     | 2439/5329 [02:05<02:33, 18.77it/s]

 46%|████▌     | 2441/5329 [02:05<02:34, 18.73it/s]

 46%|████▌     | 2444/5329 [02:05<02:19, 20.69it/s]

 46%|████▌     | 2447/5329 [02:05<02:23, 20.07it/s]

 46%|████▌     | 2450/5329 [02:06<02:25, 19.76it/s]

 46%|████▌     | 2453/5329 [02:06<02:27, 19.47it/s]

 46%|████▌     | 2455/5329 [02:06<02:30, 19.04it/s]

 46%|████▌     | 2457/5329 [02:06<02:32, 18.84it/s]

 46%|████▌     | 2459/5329 [02:06<02:32, 18.76it/s]

 46%|████▌     | 2461/5329 [02:06<02:33, 18.69it/s]

 46%|████▌     | 2463/5329 [02:06<02:32, 18.75it/s]

 46%|████▋     | 2465/5329 [02:06<02:32, 18.75it/s]

 46%|████▋     | 2467/5329 [02:07<02:33, 18.69it/s]

 46%|████▋     | 2469/5329 [02:07<02:32, 18.76it/s]

 46%|████▋     | 2471/5329 [02:07<02:31, 18.83it/s]

 46%|████▋     | 2473/5329 [02:07<02:31, 18.80it/s]

 46%|████▋     | 2475/5329 [02:07<02:31, 18.81it/s]

 46%|████▋     | 2477/5329 [02:07<02:31, 18.86it/s]

 47%|████▋     | 2479/5329 [02:07<02:30, 18.91it/s]

 47%|████▋     | 2481/5329 [02:07<02:31, 18.83it/s]

 47%|████▋     | 2483/5329 [02:07<02:30, 18.91it/s]

 47%|████▋     | 2485/5329 [02:07<02:30, 18.84it/s]

 47%|████▋     | 2487/5329 [02:08<02:29, 18.99it/s]

 47%|████▋     | 2489/5329 [02:08<02:28, 19.12it/s]

 47%|████▋     | 2491/5329 [02:08<02:27, 19.20it/s]

 47%|████▋     | 2493/5329 [02:08<02:28, 19.11it/s]

 47%|████▋     | 2495/5329 [02:08<02:28, 19.15it/s]

 47%|████▋     | 2497/5329 [02:08<02:27, 19.22it/s]

 47%|████▋     | 2499/5329 [02:08<02:27, 19.25it/s]

 47%|████▋     | 2501/5329 [02:08<02:26, 19.28it/s]

 47%|████▋     | 2503/5329 [02:08<02:26, 19.32it/s]

 47%|████▋     | 2505/5329 [02:09<02:25, 19.37it/s]

 47%|████▋     | 2507/5329 [02:09<02:25, 19.40it/s]

 47%|████▋     | 2509/5329 [02:09<02:25, 19.44it/s]

 47%|████▋     | 2511/5329 [02:09<02:24, 19.47it/s]

 47%|████▋     | 2513/5329 [02:09<02:25, 19.30it/s]

 47%|████▋     | 2515/5329 [02:09<02:27, 19.14it/s]

 47%|████▋     | 2518/5329 [02:09<02:13, 21.07it/s]

 47%|████▋     | 2521/5329 [02:09<02:17, 20.40it/s]

 47%|████▋     | 2524/5329 [02:09<02:20, 19.95it/s]

 47%|████▋     | 2527/5329 [02:10<02:22, 19.69it/s]

 47%|████▋     | 2529/5329 [02:10<02:23, 19.48it/s]

 47%|████▋     | 2531/5329 [02:10<02:24, 19.40it/s]

 48%|████▊     | 2533/5329 [02:10<02:24, 19.32it/s]

 48%|████▊     | 2535/5329 [02:10<02:25, 19.25it/s]

 48%|████▊     | 2537/5329 [02:10<02:25, 19.16it/s]

 48%|████▊     | 2539/5329 [02:10<02:25, 19.13it/s]

 48%|████▊     | 2541/5329 [02:10<02:26, 19.08it/s]

 48%|████▊     | 2543/5329 [02:10<02:26, 19.01it/s]

 48%|████▊     | 2545/5329 [02:11<02:26, 18.95it/s]

 48%|████▊     | 2547/5329 [02:11<02:28, 18.70it/s]

 48%|████▊     | 2549/5329 [02:11<02:27, 18.79it/s]

 48%|████▊     | 2551/5329 [02:11<02:27, 18.88it/s]

 48%|████▊     | 2553/5329 [02:11<02:27, 18.87it/s]

 48%|████▊     | 2555/5329 [02:11<02:26, 18.94it/s]

 48%|████▊     | 2557/5329 [02:11<02:25, 18.99it/s]

 48%|████▊     | 2559/5329 [02:11<02:25, 19.08it/s]

 48%|████▊     | 2561/5329 [02:11<02:24, 19.20it/s]

 48%|████▊     | 2563/5329 [02:12<02:24, 19.18it/s]

 48%|████▊     | 2565/5329 [02:12<02:23, 19.22it/s]

 48%|████▊     | 2567/5329 [02:12<02:23, 19.21it/s]

 48%|████▊     | 2569/5329 [02:12<02:23, 19.24it/s]

 48%|████▊     | 2571/5329 [02:12<02:24, 19.10it/s]

 48%|████▊     | 2573/5329 [02:12<02:23, 19.14it/s]

 48%|████▊     | 2575/5329 [02:12<02:24, 19.12it/s]

 48%|████▊     | 2577/5329 [02:12<02:23, 19.14it/s]

 48%|████▊     | 2579/5329 [02:12<02:23, 19.19it/s]

 48%|████▊     | 2581/5329 [02:12<02:23, 19.21it/s]

 48%|████▊     | 2583/5329 [02:13<02:23, 19.16it/s]

 49%|████▊     | 2585/5329 [02:13<02:23, 19.18it/s]

 49%|████▊     | 2587/5329 [02:13<02:23, 19.05it/s]

 49%|████▊     | 2589/5329 [02:13<02:24, 18.95it/s]

 49%|████▊     | 2592/5329 [02:13<02:10, 20.95it/s]

 49%|████▊     | 2595/5329 [02:13<02:14, 20.39it/s]

 49%|████▉     | 2598/5329 [02:13<02:16, 19.98it/s]

 49%|████▉     | 2601/5329 [02:13<02:18, 19.67it/s]

 49%|████▉     | 2603/5329 [02:14<02:19, 19.48it/s]

 49%|████▉     | 2605/5329 [02:14<02:21, 19.30it/s]

 49%|████▉     | 2607/5329 [02:14<02:21, 19.20it/s]

 49%|████▉     | 2609/5329 [02:14<02:21, 19.17it/s]

 49%|████▉     | 2611/5329 [02:14<02:23, 18.95it/s]

 49%|████▉     | 2613/5329 [02:14<02:23, 18.92it/s]

 49%|████▉     | 2615/5329 [02:14<02:23, 18.91it/s]

 49%|████▉     | 2617/5329 [02:14<02:23, 18.93it/s]

 49%|████▉     | 2619/5329 [02:14<02:22, 18.97it/s]

 49%|████▉     | 2621/5329 [02:15<02:22, 18.99it/s]

 49%|████▉     | 2623/5329 [02:15<02:22, 19.01it/s]

 49%|████▉     | 2625/5329 [02:15<02:22, 19.01it/s]

 49%|████▉     | 2627/5329 [02:15<02:22, 18.96it/s]

 49%|████▉     | 2629/5329 [02:15<02:22, 19.00it/s]

 49%|████▉     | 2631/5329 [02:15<02:22, 18.93it/s]

 49%|████▉     | 2633/5329 [02:15<02:21, 19.03it/s]

 49%|████▉     | 2635/5329 [02:15<02:20, 19.16it/s]

 49%|████▉     | 2637/5329 [02:15<02:20, 19.22it/s]

 50%|████▉     | 2639/5329 [02:15<02:19, 19.29it/s]

 50%|████▉     | 2641/5329 [02:16<02:19, 19.29it/s]

 50%|████▉     | 2643/5329 [02:16<02:19, 19.32it/s]

 50%|████▉     | 2645/5329 [02:16<02:18, 19.34it/s]

 50%|████▉     | 2647/5329 [02:16<02:18, 19.32it/s]

 50%|████▉     | 2649/5329 [02:16<02:20, 19.12it/s]

 50%|████▉     | 2651/5329 [02:16<02:20, 19.02it/s]

 50%|████▉     | 2653/5329 [02:16<02:21, 18.91it/s]

 50%|████▉     | 2655/5329 [02:16<02:20, 19.02it/s]

 50%|████▉     | 2657/5329 [02:16<02:20, 19.08it/s]

 50%|████▉     | 2659/5329 [02:17<02:19, 19.08it/s]

 50%|████▉     | 2661/5329 [02:17<02:21, 18.87it/s]

 50%|████▉     | 2663/5329 [02:17<02:21, 18.88it/s]

 50%|█████     | 2666/5329 [02:17<02:07, 20.95it/s]

 50%|█████     | 2669/5329 [02:17<02:11, 20.24it/s]

 50%|█████     | 2672/5329 [02:17<02:13, 19.86it/s]

 50%|█████     | 2675/5329 [02:17<02:15, 19.61it/s]

 50%|█████     | 2677/5329 [02:17<02:17, 19.33it/s]

 50%|█████     | 2679/5329 [02:18<02:17, 19.24it/s]

 50%|█████     | 2681/5329 [02:18<02:18, 19.06it/s]

 50%|█████     | 2683/5329 [02:18<02:19, 19.01it/s]

 50%|█████     | 2685/5329 [02:18<02:19, 19.02it/s]

 50%|█████     | 2687/5329 [02:18<02:18, 19.02it/s]

 50%|█████     | 2689/5329 [02:18<02:19, 18.97it/s]

 50%|█████     | 2691/5329 [02:18<02:18, 19.01it/s]

 51%|█████     | 2693/5329 [02:18<02:18, 19.06it/s]

 51%|█████     | 2695/5329 [02:18<02:18, 19.08it/s]

 51%|█████     | 2697/5329 [02:18<02:17, 19.08it/s]

 51%|█████     | 2699/5329 [02:19<02:17, 19.08it/s]

 51%|█████     | 2701/5329 [02:19<02:17, 19.05it/s]

 51%|█████     | 2703/5329 [02:19<02:18, 19.02it/s]

 51%|█████     | 2705/5329 [02:19<02:17, 19.14it/s]

 51%|█████     | 2707/5329 [02:19<02:17, 19.11it/s]

 51%|█████     | 2709/5329 [02:19<02:23, 18.30it/s]

 51%|█████     | 2711/5329 [02:19<02:20, 18.65it/s]

 51%|█████     | 2713/5329 [02:19<02:18, 18.86it/s]

 51%|█████     | 2715/5329 [02:19<02:17, 19.01it/s]

 51%|█████     | 2717/5329 [02:20<02:16, 19.07it/s]

 51%|█████     | 2719/5329 [02:20<02:16, 19.15it/s]

 51%|█████     | 2721/5329 [02:20<02:16, 19.17it/s]

 51%|█████     | 2723/5329 [02:20<02:16, 19.12it/s]

 51%|█████     | 2725/5329 [02:20<02:16, 19.04it/s]

 51%|█████     | 2727/5329 [02:20<02:16, 19.07it/s]

 51%|█████     | 2729/5329 [02:20<02:16, 19.10it/s]

 51%|█████     | 2731/5329 [02:20<02:15, 19.14it/s]

 51%|█████▏    | 2733/5329 [02:20<02:15, 19.15it/s]

 51%|█████▏    | 2735/5329 [02:20<02:15, 19.10it/s]

 51%|█████▏    | 2737/5329 [02:21<02:15, 19.09it/s]

 51%|█████▏    | 2740/5329 [02:21<02:02, 21.16it/s]

 51%|█████▏    | 2743/5329 [02:21<02:06, 20.37it/s]

 52%|█████▏    | 2746/5329 [02:21<02:10, 19.86it/s]

 52%|█████▏    | 2749/5329 [02:21<02:12, 19.53it/s]

 52%|█████▏    | 2751/5329 [02:21<02:13, 19.32it/s]

 52%|█████▏    | 2753/5329 [02:21<02:14, 19.20it/s]

 52%|█████▏    | 2755/5329 [02:21<02:14, 19.15it/s]

 52%|█████▏    | 2757/5329 [02:22<02:14, 19.11it/s]

 52%|█████▏    | 2759/5329 [02:22<02:14, 19.08it/s]

 52%|█████▏    | 2761/5329 [02:22<02:15, 18.98it/s]

 52%|█████▏    | 2763/5329 [02:22<02:15, 18.89it/s]

 52%|█████▏    | 2765/5329 [02:22<02:16, 18.72it/s]

 52%|█████▏    | 2767/5329 [02:22<02:16, 18.82it/s]

 52%|█████▏    | 2769/5329 [02:22<02:15, 18.90it/s]

 52%|█████▏    | 2771/5329 [02:22<02:14, 18.99it/s]

 52%|█████▏    | 2773/5329 [02:22<02:15, 18.86it/s]

 52%|█████▏    | 2775/5329 [02:23<02:14, 19.01it/s]

 52%|█████▏    | 2777/5329 [02:23<02:13, 19.11it/s]

 52%|█████▏    | 2779/5329 [02:23<02:13, 19.11it/s]

 52%|█████▏    | 2781/5329 [02:23<02:12, 19.21it/s]

 52%|█████▏    | 2783/5329 [02:23<02:12, 19.29it/s]

 52%|█████▏    | 2785/5329 [02:23<02:12, 19.25it/s]

 52%|█████▏    | 2787/5329 [02:23<02:13, 19.11it/s]

 52%|█████▏    | 2789/5329 [02:23<02:13, 19.09it/s]

 52%|█████▏    | 2791/5329 [02:23<02:12, 19.15it/s]

 52%|█████▏    | 2793/5329 [02:23<02:12, 19.13it/s]

 52%|█████▏    | 2795/5329 [02:24<02:12, 19.12it/s]

 52%|█████▏    | 2797/5329 [02:24<02:11, 19.18it/s]

 53%|█████▎    | 2799/5329 [02:24<02:11, 19.20it/s]

 53%|█████▎    | 2801/5329 [02:24<02:11, 19.20it/s]

 53%|█████▎    | 2803/5329 [02:24<02:11, 19.23it/s]

 53%|█████▎    | 2805/5329 [02:24<02:11, 19.24it/s]

 53%|█████▎    | 2807/5329 [02:24<02:11, 19.14it/s]

 53%|█████▎    | 2809/5329 [02:24<02:12, 19.08it/s]

 53%|█████▎    | 2811/5329 [02:24<02:11, 19.08it/s]

 53%|█████▎    | 2814/5329 [02:25<01:58, 21.16it/s]

 53%|█████▎    | 2817/5329 [02:25<02:02, 20.47it/s]

 53%|█████▎    | 2820/5329 [02:25<02:05, 19.96it/s]

 53%|█████▎    | 2823/5329 [02:25<02:07, 19.61it/s]

 53%|█████▎    | 2825/5329 [02:25<02:09, 19.39it/s]

 53%|█████▎    | 2827/5329 [02:25<02:09, 19.31it/s]

 53%|█████▎    | 2829/5329 [02:25<02:10, 19.16it/s]

 53%|█████▎    | 2831/5329 [02:25<02:10, 19.10it/s]

 53%|█████▎    | 2833/5329 [02:26<02:10, 19.10it/s]

 53%|█████▎    | 2835/5329 [02:26<02:10, 19.06it/s]

 53%|█████▎    | 2837/5329 [02:26<02:10, 19.10it/s]

 53%|█████▎    | 2839/5329 [02:26<02:10, 19.11it/s]

 53%|█████▎    | 2841/5329 [02:26<02:10, 19.03it/s]

 53%|█████▎    | 2843/5329 [02:26<02:10, 19.01it/s]

 53%|█████▎    | 2845/5329 [02:26<02:10, 18.99it/s]

 53%|█████▎    | 2847/5329 [02:26<02:10, 19.04it/s]

 53%|█████▎    | 2849/5329 [02:26<02:09, 19.12it/s]

 53%|█████▎    | 2851/5329 [02:26<02:08, 19.22it/s]

 54%|█████▎    | 2853/5329 [02:27<02:08, 19.32it/s]

 54%|█████▎    | 2855/5329 [02:27<02:07, 19.33it/s]

 54%|█████▎    | 2857/5329 [02:27<02:07, 19.37it/s]

 54%|█████▎    | 2859/5329 [02:27<02:07, 19.37it/s]

 54%|█████▎    | 2861/5329 [02:27<02:07, 19.38it/s]

 54%|█████▎    | 2863/5329 [02:27<02:07, 19.36it/s]

 54%|█████▍    | 2865/5329 [02:27<02:06, 19.40it/s]

 54%|█████▍    | 2867/5329 [02:27<02:06, 19.46it/s]

 54%|█████▍    | 2869/5329 [02:27<02:06, 19.47it/s]

 54%|█████▍    | 2871/5329 [02:27<02:06, 19.48it/s]

 54%|█████▍    | 2873/5329 [02:28<02:05, 19.53it/s]

 54%|█████▍    | 2875/5329 [02:28<02:05, 19.55it/s]

 54%|█████▍    | 2877/5329 [02:28<02:05, 19.54it/s]

 54%|█████▍    | 2879/5329 [02:28<02:05, 19.48it/s]

 54%|█████▍    | 2881/5329 [02:28<02:06, 19.39it/s]

 54%|█████▍    | 2883/5329 [02:28<02:07, 19.24it/s]

 54%|█████▍    | 2885/5329 [02:28<02:07, 19.22it/s]

 54%|█████▍    | 2888/5329 [02:28<01:54, 21.33it/s]

 54%|█████▍    | 2891/5329 [02:28<01:58, 20.55it/s]

 54%|█████▍    | 2894/5329 [02:29<02:01, 20.06it/s]

 54%|█████▍    | 2897/5329 [02:29<02:03, 19.72it/s]

 54%|█████▍    | 2900/5329 [02:29<02:05, 19.43it/s]

 54%|█████▍    | 2902/5329 [02:29<02:06, 19.12it/s]

 54%|█████▍    | 2904/5329 [02:29<02:07, 19.00it/s]

 55%|█████▍    | 2906/5329 [02:29<02:07, 18.93it/s]

 55%|█████▍    | 2908/5329 [02:29<02:07, 18.97it/s]

 55%|█████▍    | 2910/5329 [02:29<02:07, 19.00it/s]

 55%|█████▍    | 2912/5329 [02:30<02:07, 18.96it/s]

 55%|█████▍    | 2914/5329 [02:30<02:07, 18.96it/s]

 55%|█████▍    | 2916/5329 [02:30<02:07, 18.91it/s]

 55%|█████▍    | 2918/5329 [02:30<02:07, 18.84it/s]

 55%|█████▍    | 2920/5329 [02:30<02:07, 18.87it/s]

 55%|█████▍    | 2922/5329 [02:30<02:07, 18.92it/s]

 55%|█████▍    | 2924/5329 [02:30<02:07, 18.85it/s]

 55%|█████▍    | 2926/5329 [02:30<02:08, 18.66it/s]

 55%|█████▍    | 2928/5329 [02:30<02:07, 18.87it/s]

 55%|█████▍    | 2930/5329 [02:31<02:06, 18.94it/s]

 55%|█████▌    | 2932/5329 [02:31<02:05, 19.09it/s]

 55%|█████▌    | 2934/5329 [02:31<02:04, 19.17it/s]

 55%|█████▌    | 2936/5329 [02:31<02:03, 19.33it/s]

 55%|█████▌    | 2938/5329 [02:31<02:03, 19.42it/s]

 55%|█████▌    | 2940/5329 [02:31<02:04, 19.21it/s]

 55%|█████▌    | 2942/5329 [02:31<02:03, 19.28it/s]

 55%|█████▌    | 2944/5329 [02:31<02:03, 19.37it/s]

 55%|█████▌    | 2946/5329 [02:31<02:02, 19.40it/s]

 55%|█████▌    | 2948/5329 [02:31<02:02, 19.46it/s]

 55%|█████▌    | 2950/5329 [02:32<02:01, 19.52it/s]

 55%|█████▌    | 2952/5329 [02:32<02:02, 19.41it/s]

 55%|█████▌    | 2954/5329 [02:32<02:02, 19.36it/s]

 55%|█████▌    | 2956/5329 [02:32<02:02, 19.33it/s]

 56%|█████▌    | 2958/5329 [02:32<02:03, 19.13it/s]

 56%|█████▌    | 2960/5329 [02:32<02:04, 18.95it/s]

 56%|█████▌    | 2963/5329 [02:32<01:53, 20.85it/s]

 56%|█████▌    | 2966/5329 [02:32<01:58, 20.02it/s]

 56%|█████▌    | 2969/5329 [02:33<01:59, 19.67it/s]

 56%|█████▌    | 2972/5329 [02:33<02:01, 19.48it/s]

 56%|█████▌    | 2974/5329 [02:33<02:03, 19.09it/s]

 56%|█████▌    | 2976/5329 [02:33<02:03, 18.98it/s]

 56%|█████▌    | 2978/5329 [02:33<02:03, 19.01it/s]

 56%|█████▌    | 2980/5329 [02:33<02:03, 18.95it/s]

 56%|█████▌    | 2982/5329 [02:33<02:03, 19.02it/s]

 56%|█████▌    | 2984/5329 [02:33<02:02, 19.12it/s]

 56%|█████▌    | 2986/5329 [02:33<02:02, 19.16it/s]

 56%|█████▌    | 2988/5329 [02:34<02:02, 19.14it/s]

 56%|█████▌    | 2990/5329 [02:34<02:01, 19.23it/s]

 56%|█████▌    | 2992/5329 [02:34<02:01, 19.21it/s]

 56%|█████▌    | 2994/5329 [02:34<02:01, 19.17it/s]

 56%|█████▌    | 2996/5329 [02:34<02:01, 19.24it/s]

 56%|█████▋    | 2998/5329 [02:34<02:00, 19.32it/s]

 56%|█████▋    | 3000/5329 [02:34<02:00, 19.39it/s]

 56%|█████▋    | 3002/5329 [02:34<01:59, 19.40it/s]

 56%|█████▋    | 3004/5329 [02:34<01:59, 19.46it/s]

 56%|█████▋    | 3006/5329 [02:34<01:59, 19.49it/s]

 56%|█████▋    | 3008/5329 [02:35<01:59, 19.46it/s]

 56%|█████▋    | 3010/5329 [02:35<01:58, 19.49it/s]

 57%|█████▋    | 3012/5329 [02:35<01:58, 19.50it/s]

 57%|█████▋    | 3014/5329 [02:35<01:58, 19.49it/s]

 57%|█████▋    | 3016/5329 [02:35<01:58, 19.48it/s]

 57%|█████▋    | 3018/5329 [02:35<01:59, 19.40it/s]

 57%|█████▋    | 3020/5329 [02:35<01:59, 19.39it/s]

 57%|█████▋    | 3022/5329 [02:35<01:58, 19.40it/s]

 57%|█████▋    | 3024/5329 [02:35<01:58, 19.42it/s]

 57%|█████▋    | 3026/5329 [02:35<01:58, 19.38it/s]

 57%|█████▋    | 3028/5329 [02:36<01:59, 19.33it/s]

 57%|█████▋    | 3030/5329 [02:36<01:59, 19.21it/s]

 57%|█████▋    | 3032/5329 [02:36<02:00, 19.02it/s]

 57%|█████▋    | 3034/5329 [02:36<02:01, 18.89it/s]

 57%|█████▋    | 3037/5329 [02:36<01:49, 20.93it/s]

 57%|█████▋    | 3040/5329 [02:36<01:53, 20.24it/s]

 57%|█████▋    | 3043/5329 [02:36<01:55, 19.80it/s]

 57%|█████▋    | 3046/5329 [02:36<01:56, 19.53it/s]

 57%|█████▋    | 3048/5329 [02:37<01:57, 19.37it/s]

 57%|█████▋    | 3050/5329 [02:37<01:58, 19.19it/s]

 57%|█████▋    | 3052/5329 [02:37<01:59, 19.04it/s]

 57%|█████▋    | 3054/5329 [02:37<02:00, 18.94it/s]

 57%|█████▋    | 3056/5329 [02:37<02:01, 18.75it/s]

 57%|█████▋    | 3058/5329 [02:37<02:02, 18.48it/s]

 57%|█████▋    | 3060/5329 [02:37<02:03, 18.40it/s]

 57%|█████▋    | 3062/5329 [02:37<02:03, 18.38it/s]

 57%|█████▋    | 3064/5329 [02:37<02:04, 18.20it/s]

 58%|█████▊    | 3066/5329 [02:38<02:04, 18.11it/s]

 58%|█████▊    | 3068/5329 [02:38<02:03, 18.31it/s]

 58%|█████▊    | 3070/5329 [02:38<02:02, 18.40it/s]

 58%|█████▊    | 3072/5329 [02:38<02:02, 18.49it/s]

 58%|█████▊    | 3074/5329 [02:38<02:02, 18.47it/s]

 58%|█████▊    | 3076/5329 [02:38<02:02, 18.41it/s]

 58%|█████▊    | 3078/5329 [02:38<02:02, 18.36it/s]

 58%|█████▊    | 3080/5329 [02:38<02:02, 18.38it/s]

 58%|█████▊    | 3082/5329 [02:38<02:01, 18.44it/s]

 58%|█████▊    | 3084/5329 [02:39<02:01, 18.52it/s]

 58%|█████▊    | 3086/5329 [02:39<02:01, 18.51it/s]

 58%|█████▊    | 3088/5329 [02:39<02:01, 18.51it/s]

 58%|█████▊    | 3090/5329 [02:39<02:01, 18.46it/s]

 58%|█████▊    | 3092/5329 [02:39<02:01, 18.43it/s]

 58%|█████▊    | 3094/5329 [02:39<02:01, 18.35it/s]

 58%|█████▊    | 3096/5329 [02:39<02:01, 18.40it/s]

 58%|█████▊    | 3098/5329 [02:39<02:01, 18.30it/s]

 58%|█████▊    | 3100/5329 [02:39<02:02, 18.27it/s]

 58%|█████▊    | 3102/5329 [02:40<02:01, 18.37it/s]

 58%|█████▊    | 3104/5329 [02:40<02:00, 18.40it/s]

 58%|█████▊    | 3106/5329 [02:40<02:00, 18.41it/s]

 58%|█████▊    | 3108/5329 [02:40<02:00, 18.45it/s]

 58%|█████▊    | 3111/5329 [02:40<01:48, 20.48it/s]

 58%|█████▊    | 3114/5329 [02:40<01:52, 19.76it/s]

 58%|█████▊    | 3117/5329 [02:40<01:53, 19.49it/s]

 59%|█████▊    | 3119/5329 [02:40<01:55, 19.20it/s]

 59%|█████▊    | 3121/5329 [02:41<01:56, 19.00it/s]

 59%|█████▊    | 3123/5329 [02:41<01:56, 18.90it/s]

 59%|█████▊    | 3125/5329 [02:41<01:58, 18.65it/s]

 59%|█████▊    | 3127/5329 [02:41<01:58, 18.64it/s]

 59%|█████▊    | 3129/5329 [02:41<01:57, 18.68it/s]

 59%|█████▉    | 3131/5329 [02:41<01:57, 18.67it/s]

 59%|█████▉    | 3133/5329 [02:41<01:58, 18.53it/s]

 59%|█████▉    | 3135/5329 [02:41<01:59, 18.43it/s]

 59%|█████▉    | 3137/5329 [02:41<02:00, 18.25it/s]

 59%|█████▉    | 3139/5329 [02:41<01:59, 18.38it/s]

 59%|█████▉    | 3141/5329 [02:42<01:57, 18.55it/s]

 59%|█████▉    | 3143/5329 [02:42<01:56, 18.70it/s]

 59%|█████▉    | 3145/5329 [02:42<01:56, 18.76it/s]

 59%|█████▉    | 3147/5329 [02:42<01:57, 18.62it/s]

 59%|█████▉    | 3149/5329 [02:42<01:57, 18.59it/s]

 59%|█████▉    | 3151/5329 [02:42<01:57, 18.53it/s]

 59%|█████▉    | 3153/5329 [02:42<01:57, 18.50it/s]

 59%|█████▉    | 3155/5329 [02:42<01:57, 18.54it/s]

 59%|█████▉    | 3157/5329 [02:42<01:56, 18.58it/s]

 59%|█████▉    | 3159/5329 [02:43<01:56, 18.59it/s]

 59%|█████▉    | 3161/5329 [02:43<01:56, 18.63it/s]

 59%|█████▉    | 3163/5329 [02:43<01:56, 18.62it/s]

 59%|█████▉    | 3165/5329 [02:43<01:56, 18.64it/s]

 59%|█████▉    | 3167/5329 [02:43<01:55, 18.66it/s]

 59%|█████▉    | 3169/5329 [02:43<01:55, 18.69it/s]

 60%|█████▉    | 3171/5329 [02:43<01:55, 18.62it/s]

 60%|█████▉    | 3173/5329 [02:43<01:57, 18.40it/s]

 60%|█████▉    | 3175/5329 [02:43<01:57, 18.39it/s]

 60%|█████▉    | 3177/5329 [02:44<01:56, 18.45it/s]

 60%|█████▉    | 3179/5329 [02:44<01:56, 18.43it/s]

 60%|█████▉    | 3181/5329 [02:44<01:57, 18.35it/s]

 60%|█████▉    | 3184/5329 [02:44<01:45, 20.35it/s]

 60%|█████▉    | 3187/5329 [02:44<01:48, 19.77it/s]

 60%|█████▉    | 3190/5329 [02:44<01:50, 19.33it/s]

 60%|█████▉    | 3192/5329 [02:44<01:52, 19.06it/s]

 60%|█████▉    | 3194/5329 [02:44<01:53, 18.88it/s]

 60%|█████▉    | 3196/5329 [02:45<01:53, 18.75it/s]

 60%|██████    | 3198/5329 [02:45<01:54, 18.56it/s]

 60%|██████    | 3200/5329 [02:45<01:54, 18.52it/s]

 60%|██████    | 3202/5329 [02:45<01:55, 18.49it/s]

 60%|██████    | 3204/5329 [02:45<01:55, 18.42it/s]

 60%|██████    | 3206/5329 [02:45<01:55, 18.37it/s]

 60%|██████    | 3208/5329 [02:45<01:55, 18.30it/s]

 60%|██████    | 3210/5329 [02:45<01:56, 18.15it/s]

 60%|██████    | 3212/5329 [02:45<01:56, 18.20it/s]

 60%|██████    | 3214/5329 [02:45<01:55, 18.35it/s]

 60%|██████    | 3216/5329 [02:46<01:54, 18.49it/s]

 60%|██████    | 3218/5329 [02:46<01:53, 18.52it/s]

 60%|██████    | 3220/5329 [02:46<01:53, 18.54it/s]

 60%|██████    | 3222/5329 [02:46<01:53, 18.50it/s]

 60%|██████    | 3224/5329 [02:46<01:53, 18.51it/s]

 61%|██████    | 3226/5329 [02:46<01:54, 18.37it/s]

 61%|██████    | 3228/5329 [02:46<01:54, 18.33it/s]

 61%|██████    | 3230/5329 [02:46<01:55, 18.18it/s]

 61%|██████    | 3232/5329 [02:46<01:56, 18.01it/s]

 61%|██████    | 3234/5329 [02:47<01:56, 18.04it/s]

 61%|██████    | 3236/5329 [02:47<01:58, 17.72it/s]

 61%|██████    | 3238/5329 [02:47<01:57, 17.74it/s]

 61%|██████    | 3240/5329 [02:47<01:57, 17.81it/s]

 61%|██████    | 3242/5329 [02:47<01:56, 17.93it/s]

 61%|██████    | 3244/5329 [02:47<01:56, 17.85it/s]

 61%|██████    | 3246/5329 [02:47<01:56, 17.84it/s]

 61%|██████    | 3248/5329 [02:47<01:57, 17.75it/s]

 61%|██████    | 3250/5329 [02:47<01:57, 17.66it/s]

 61%|██████    | 3252/5329 [02:48<01:57, 17.62it/s]

 61%|██████    | 3254/5329 [02:48<01:57, 17.66it/s]

 61%|██████    | 3256/5329 [02:48<01:57, 17.62it/s]

 61%|██████    | 3259/5329 [02:48<01:46, 19.49it/s]

 61%|██████    | 3262/5329 [02:48<01:48, 19.00it/s]

 61%|██████    | 3264/5329 [02:48<01:51, 18.50it/s]

 61%|██████▏   | 3266/5329 [02:48<01:52, 18.27it/s]

 61%|██████▏   | 3268/5329 [02:48<01:54, 18.01it/s]

 61%|██████▏   | 3270/5329 [02:49<01:55, 17.90it/s]

 61%|██████▏   | 3272/5329 [02:49<01:54, 17.99it/s]

 61%|██████▏   | 3274/5329 [02:49<01:54, 17.95it/s]

 61%|██████▏   | 3276/5329 [02:49<01:55, 17.82it/s]

 62%|██████▏   | 3278/5329 [02:49<01:55, 17.83it/s]

 62%|██████▏   | 3280/5329 [02:49<01:56, 17.66it/s]

 62%|██████▏   | 3282/5329 [02:49<01:55, 17.68it/s]

 62%|██████▏   | 3284/5329 [02:49<01:55, 17.70it/s]

 62%|██████▏   | 3286/5329 [02:49<01:55, 17.76it/s]

 62%|██████▏   | 3288/5329 [02:50<01:54, 17.84it/s]

 62%|██████▏   | 3290/5329 [02:50<01:53, 18.03it/s]

 62%|██████▏   | 3292/5329 [02:50<01:52, 18.13it/s]

 62%|██████▏   | 3294/5329 [02:50<01:52, 18.06it/s]

 62%|██████▏   | 3296/5329 [02:50<01:51, 18.20it/s]

 62%|██████▏   | 3298/5329 [02:50<01:52, 18.11it/s]

 62%|██████▏   | 3300/5329 [02:50<01:51, 18.14it/s]

 62%|██████▏   | 3302/5329 [02:50<01:52, 18.05it/s]

 62%|██████▏   | 3304/5329 [02:50<01:52, 18.07it/s]

 62%|██████▏   | 3306/5329 [02:51<01:52, 17.98it/s]

 62%|██████▏   | 3308/5329 [02:51<01:52, 18.04it/s]

 62%|██████▏   | 3310/5329 [02:51<01:52, 18.00it/s]

 62%|██████▏   | 3312/5329 [02:51<01:51, 18.02it/s]

 62%|██████▏   | 3314/5329 [02:51<01:51, 18.12it/s]

 62%|██████▏   | 3316/5329 [02:51<01:51, 18.03it/s]

 62%|██████▏   | 3318/5329 [02:51<01:52, 17.92it/s]

 62%|██████▏   | 3320/5329 [02:51<01:50, 18.11it/s]

 62%|██████▏   | 3322/5329 [02:51<01:52, 17.86it/s]

 62%|██████▏   | 3324/5329 [02:52<01:52, 17.82it/s]

 62%|██████▏   | 3326/5329 [02:52<01:52, 17.88it/s]

 62%|██████▏   | 3328/5329 [02:52<01:53, 17.69it/s]

 62%|██████▏   | 3330/5329 [02:52<01:53, 17.60it/s]

 63%|██████▎   | 3333/5329 [02:52<01:42, 19.54it/s]

 63%|██████▎   | 3336/5329 [02:52<01:43, 19.20it/s]

 63%|██████▎   | 3338/5329 [02:52<01:45, 18.92it/s]

 63%|██████▎   | 3340/5329 [02:52<01:45, 18.89it/s]

 63%|██████▎   | 3342/5329 [02:53<01:44, 18.97it/s]

 63%|██████▎   | 3344/5329 [02:53<01:45, 18.90it/s]

 63%|██████▎   | 3346/5329 [02:53<01:44, 18.89it/s]

 63%|██████▎   | 3348/5329 [02:53<01:45, 18.83it/s]

 63%|██████▎   | 3350/5329 [02:53<01:44, 18.86it/s]

 63%|██████▎   | 3352/5329 [02:53<01:45, 18.79it/s]

 63%|██████▎   | 3354/5329 [02:53<01:45, 18.66it/s]

 63%|██████▎   | 3356/5329 [02:53<01:47, 18.44it/s]

 63%|██████▎   | 3358/5329 [02:53<01:46, 18.56it/s]

 63%|██████▎   | 3360/5329 [02:53<01:45, 18.74it/s]

 63%|██████▎   | 3362/5329 [02:54<01:44, 18.88it/s]

 63%|██████▎   | 3364/5329 [02:54<01:43, 18.90it/s]

 63%|██████▎   | 3366/5329 [02:54<01:43, 19.00it/s]

 63%|██████▎   | 3368/5329 [02:54<01:43, 18.96it/s]

 63%|██████▎   | 3370/5329 [02:54<01:43, 19.00it/s]

 63%|██████▎   | 3372/5329 [02:54<01:42, 19.10it/s]

 63%|██████▎   | 3374/5329 [02:54<01:42, 19.08it/s]

 63%|██████▎   | 3376/5329 [02:54<01:42, 18.99it/s]

 63%|██████▎   | 3378/5329 [02:54<01:42, 18.97it/s]

 63%|██████▎   | 3380/5329 [02:55<01:42, 19.03it/s]

 63%|██████▎   | 3382/5329 [02:55<01:42, 18.95it/s]

 64%|██████▎   | 3384/5329 [02:55<01:42, 18.92it/s]

 64%|██████▎   | 3386/5329 [02:55<01:42, 18.99it/s]

 64%|██████▎   | 3388/5329 [02:55<01:42, 18.98it/s]

 64%|██████▎   | 3390/5329 [02:55<01:42, 18.99it/s]

 64%|██████▎   | 3392/5329 [02:55<01:42, 18.95it/s]

 64%|██████▎   | 3394/5329 [02:55<01:42, 18.87it/s]

 64%|██████▎   | 3396/5329 [02:55<01:42, 18.82it/s]

 64%|██████▍   | 3398/5329 [02:55<01:42, 18.85it/s]

 64%|██████▍   | 3400/5329 [02:56<01:42, 18.83it/s]

 64%|██████▍   | 3402/5329 [02:56<01:42, 18.84it/s]

 64%|██████▍   | 3404/5329 [02:56<01:42, 18.78it/s]

 64%|██████▍   | 3407/5329 [02:56<01:32, 20.87it/s]

 64%|██████▍   | 3410/5329 [02:56<01:35, 20.11it/s]

 64%|██████▍   | 3413/5329 [02:56<01:38, 19.51it/s]

 64%|██████▍   | 3415/5329 [02:56<01:39, 19.23it/s]

 64%|██████▍   | 3417/5329 [02:56<01:40, 19.10it/s]

 64%|██████▍   | 3419/5329 [02:57<01:40, 18.99it/s]

 64%|██████▍   | 3421/5329 [02:57<01:41, 18.88it/s]

 64%|██████▍   | 3423/5329 [02:57<01:41, 18.86it/s]

 64%|██████▍   | 3425/5329 [02:57<01:41, 18.81it/s]

 64%|██████▍   | 3427/5329 [02:57<01:41, 18.66it/s]

 64%|██████▍   | 3429/5329 [02:57<01:41, 18.67it/s]

 64%|██████▍   | 3431/5329 [02:57<01:41, 18.75it/s]

 64%|██████▍   | 3433/5329 [02:57<01:40, 18.81it/s]

 64%|██████▍   | 3435/5329 [02:57<01:40, 18.81it/s]

 64%|██████▍   | 3437/5329 [02:58<01:40, 18.87it/s]

 65%|██████▍   | 3439/5329 [02:58<01:40, 18.72it/s]

 65%|██████▍   | 3441/5329 [02:58<01:40, 18.70it/s]

 65%|██████▍   | 3443/5329 [02:58<01:40, 18.79it/s]

 65%|██████▍   | 3445/5329 [02:58<01:39, 18.94it/s]

 65%|██████▍   | 3447/5329 [02:58<01:39, 18.91it/s]

 65%|██████▍   | 3449/5329 [02:58<01:39, 18.91it/s]

 65%|██████▍   | 3451/5329 [02:58<01:40, 18.77it/s]

 65%|██████▍   | 3453/5329 [02:58<01:39, 18.91it/s]

 65%|██████▍   | 3455/5329 [02:58<01:38, 18.95it/s]

 65%|██████▍   | 3457/5329 [02:59<01:37, 19.10it/s]

 65%|██████▍   | 3459/5329 [02:59<01:38, 19.08it/s]

 65%|██████▍   | 3461/5329 [02:59<01:38, 18.91it/s]

 65%|██████▍   | 3463/5329 [02:59<01:39, 18.81it/s]

 65%|██████▌   | 3465/5329 [02:59<01:39, 18.71it/s]

 65%|██████▌   | 3467/5329 [02:59<01:39, 18.68it/s]

 65%|██████▌   | 3469/5329 [02:59<01:39, 18.68it/s]

 65%|██████▌   | 3471/5329 [02:59<01:39, 18.75it/s]

 65%|██████▌   | 3473/5329 [02:59<01:39, 18.65it/s]

 65%|██████▌   | 3475/5329 [03:00<01:39, 18.58it/s]

 65%|██████▌   | 3477/5329 [03:00<01:39, 18.54it/s]

 65%|██████▌   | 3480/5329 [03:00<01:29, 20.62it/s]

 65%|██████▌   | 3483/5329 [03:00<01:32, 20.00it/s]

 65%|██████▌   | 3486/5329 [03:00<01:34, 19.59it/s]

 65%|██████▌   | 3489/5329 [03:00<01:35, 19.32it/s]

 66%|██████▌   | 3491/5329 [03:00<01:35, 19.23it/s]

 66%|██████▌   | 3493/5329 [03:00<01:35, 19.26it/s]

 66%|██████▌   | 3495/5329 [03:01<01:35, 19.16it/s]

 66%|██████▌   | 3497/5329 [03:01<01:36, 19.07it/s]

 66%|██████▌   | 3499/5329 [03:01<01:36, 19.00it/s]

 66%|██████▌   | 3501/5329 [03:01<01:35, 19.07it/s]

 66%|██████▌   | 3503/5329 [03:01<01:35, 19.04it/s]

 66%|██████▌   | 3505/5329 [03:01<01:35, 19.14it/s]

 66%|██████▌   | 3507/5329 [03:01<01:35, 19.13it/s]

 66%|██████▌   | 3509/5329 [03:01<01:34, 19.17it/s]

 66%|██████▌   | 3511/5329 [03:01<01:34, 19.21it/s]

 66%|██████▌   | 3513/5329 [03:01<01:34, 19.19it/s]

 66%|██████▌   | 3515/5329 [03:02<01:34, 19.16it/s]

 66%|██████▌   | 3517/5329 [03:02<01:34, 19.19it/s]

 66%|██████▌   | 3519/5329 [03:02<01:34, 19.08it/s]

 66%|██████▌   | 3521/5329 [03:02<01:35, 19.02it/s]

 66%|██████▌   | 3523/5329 [03:02<01:35, 18.93it/s]

 66%|██████▌   | 3525/5329 [03:02<01:35, 18.98it/s]

 66%|██████▌   | 3527/5329 [03:02<01:34, 19.04it/s]

 66%|██████▌   | 3529/5329 [03:02<01:33, 19.15it/s]

 66%|██████▋   | 3531/5329 [03:02<01:34, 19.13it/s]

 66%|██████▋   | 3533/5329 [03:03<01:33, 19.17it/s]

 66%|██████▋   | 3535/5329 [03:03<01:33, 19.15it/s]

 66%|██████▋   | 3537/5329 [03:03<01:33, 19.07it/s]

 66%|██████▋   | 3539/5329 [03:03<01:34, 18.92it/s]

 66%|██████▋   | 3541/5329 [03:03<01:34, 18.84it/s]

 66%|██████▋   | 3543/5329 [03:03<01:35, 18.78it/s]

 67%|██████▋   | 3545/5329 [03:03<01:35, 18.72it/s]

 67%|██████▋   | 3547/5329 [03:03<01:35, 18.63it/s]

 67%|██████▋   | 3549/5329 [03:03<01:35, 18.74it/s]

 67%|██████▋   | 3551/5329 [03:03<01:34, 18.73it/s]

 67%|██████▋   | 3554/5329 [03:04<01:25, 20.84it/s]

 67%|██████▋   | 3557/5329 [03:04<01:30, 19.55it/s]

 67%|██████▋   | 3560/5329 [03:04<01:31, 19.25it/s]

 67%|██████▋   | 3562/5329 [03:04<01:32, 19.15it/s]

 67%|██████▋   | 3564/5329 [03:04<01:32, 19.04it/s]

 67%|██████▋   | 3566/5329 [03:04<01:33, 18.84it/s]

 67%|██████▋   | 3568/5329 [03:04<01:33, 18.79it/s]

 67%|██████▋   | 3570/5329 [03:04<01:33, 18.86it/s]

 67%|██████▋   | 3572/5329 [03:05<01:33, 18.80it/s]

 67%|██████▋   | 3574/5329 [03:05<01:33, 18.82it/s]

 67%|██████▋   | 3576/5329 [03:05<01:33, 18.71it/s]

 67%|██████▋   | 3578/5329 [03:05<01:32, 18.88it/s]

 67%|██████▋   | 3580/5329 [03:05<01:32, 18.90it/s]

 67%|██████▋   | 3582/5329 [03:05<01:32, 18.98it/s]

 67%|██████▋   | 3584/5329 [03:05<01:31, 19.01it/s]

 67%|██████▋   | 3586/5329 [03:05<01:31, 19.03it/s]

 67%|██████▋   | 3588/5329 [03:05<01:31, 19.10it/s]

 67%|██████▋   | 3590/5329 [03:06<01:30, 19.16it/s]

 67%|██████▋   | 3592/5329 [03:06<01:30, 19.23it/s]

 67%|██████▋   | 3594/5329 [03:06<01:30, 19.16it/s]

 67%|██████▋   | 3596/5329 [03:06<01:29, 19.29it/s]

 68%|██████▊   | 3598/5329 [03:06<01:29, 19.31it/s]

 68%|██████▊   | 3600/5329 [03:06<01:30, 19.20it/s]

 68%|██████▊   | 3602/5329 [03:06<01:30, 19.15it/s]

 68%|██████▊   | 3604/5329 [03:06<01:30, 19.16it/s]

 68%|██████▊   | 3606/5329 [03:06<01:29, 19.18it/s]

 68%|██████▊   | 3608/5329 [03:06<01:29, 19.17it/s]

 68%|██████▊   | 3610/5329 [03:07<01:29, 19.14it/s]

 68%|██████▊   | 3612/5329 [03:07<01:29, 19.11it/s]

 68%|██████▊   | 3614/5329 [03:07<01:30, 18.95it/s]

 68%|██████▊   | 3616/5329 [03:07<01:30, 18.89it/s]

 68%|██████▊   | 3618/5329 [03:07<01:31, 18.79it/s]

 68%|██████▊   | 3620/5329 [03:07<01:30, 18.79it/s]

 68%|██████▊   | 3622/5329 [03:07<01:31, 18.63it/s]

 68%|██████▊   | 3624/5329 [03:07<01:31, 18.68it/s]

 68%|██████▊   | 3626/5329 [03:07<01:31, 18.64it/s]

 68%|██████▊   | 3629/5329 [03:08<01:21, 20.75it/s]

 68%|██████▊   | 3632/5329 [03:08<01:24, 20.15it/s]

 68%|██████▊   | 3635/5329 [03:08<01:25, 19.79it/s]

 68%|██████▊   | 3638/5329 [03:08<01:26, 19.44it/s]

 68%|██████▊   | 3640/5329 [03:08<01:27, 19.22it/s]

 68%|██████▊   | 3642/5329 [03:08<01:28, 19.04it/s]

 68%|██████▊   | 3644/5329 [03:08<01:28, 18.96it/s]

 68%|██████▊   | 3646/5329 [03:08<01:29, 18.71it/s]

 68%|██████▊   | 3648/5329 [03:09<01:29, 18.70it/s]

 68%|██████▊   | 3650/5329 [03:09<01:29, 18.71it/s]

 69%|██████▊   | 3652/5329 [03:09<01:28, 18.87it/s]

 69%|██████▊   | 3654/5329 [03:09<01:28, 18.90it/s]

 69%|██████▊   | 3656/5329 [03:09<01:28, 18.98it/s]

 69%|██████▊   | 3658/5329 [03:09<01:27, 19.07it/s]

 69%|██████▊   | 3660/5329 [03:09<01:27, 19.09it/s]

 69%|██████▊   | 3662/5329 [03:09<01:27, 19.05it/s]

 69%|██████▉   | 3664/5329 [03:09<01:27, 19.03it/s]

 69%|██████▉   | 3666/5329 [03:09<01:27, 19.05it/s]

 69%|██████▉   | 3668/5329 [03:10<01:26, 19.11it/s]

 69%|██████▉   | 3670/5329 [03:10<01:26, 19.12it/s]

 69%|██████▉   | 3672/5329 [03:10<01:26, 19.13it/s]

 69%|██████▉   | 3674/5329 [03:10<01:26, 19.14it/s]

 69%|██████▉   | 3676/5329 [03:10<01:26, 19.13it/s]

 69%|██████▉   | 3678/5329 [03:10<01:26, 19.13it/s]

 69%|██████▉   | 3680/5329 [03:10<01:26, 19.15it/s]

 69%|██████▉   | 3682/5329 [03:10<01:26, 19.12it/s]

 69%|██████▉   | 3684/5329 [03:10<01:26, 19.07it/s]

 69%|██████▉   | 3686/5329 [03:11<01:25, 19.14it/s]

 69%|██████▉   | 3688/5329 [03:11<01:25, 19.18it/s]

 69%|██████▉   | 3690/5329 [03:11<01:25, 19.12it/s]

 69%|██████▉   | 3692/5329 [03:11<01:25, 19.07it/s]

 69%|██████▉   | 3694/5329 [03:11<01:25, 19.06it/s]

 69%|██████▉   | 3696/5329 [03:11<01:25, 19.05it/s]

 69%|██████▉   | 3698/5329 [03:11<01:25, 19.02it/s]

 69%|██████▉   | 3700/5329 [03:11<01:25, 18.94it/s]

 69%|██████▉   | 3703/5329 [03:11<01:17, 21.03it/s]

 70%|██████▉   | 3706/5329 [03:12<01:19, 20.39it/s]

 70%|██████▉   | 3709/5329 [03:12<01:21, 19.98it/s]

 70%|██████▉   | 3712/5329 [03:12<01:22, 19.70it/s]

 70%|██████▉   | 3714/5329 [03:12<01:23, 19.39it/s]

 70%|██████▉   | 3716/5329 [03:12<01:23, 19.27it/s]

 70%|██████▉   | 3718/5329 [03:12<01:23, 19.28it/s]

 70%|██████▉   | 3720/5329 [03:12<01:23, 19.21it/s]

 70%|██████▉   | 3722/5329 [03:12<01:23, 19.28it/s]

 70%|██████▉   | 3724/5329 [03:12<01:22, 19.35it/s]

 70%|██████▉   | 3726/5329 [03:13<01:22, 19.45it/s]

 70%|██████▉   | 3728/5329 [03:13<01:21, 19.55it/s]

 70%|██████▉   | 3730/5329 [03:13<01:21, 19.59it/s]

 70%|███████   | 3732/5329 [03:13<01:21, 19.48it/s]

 70%|███████   | 3734/5329 [03:13<01:21, 19.51it/s]

 70%|███████   | 3736/5329 [03:13<01:21, 19.50it/s]

 70%|███████   | 3738/5329 [03:13<01:21, 19.56it/s]

 70%|███████   | 3740/5329 [03:13<01:21, 19.48it/s]

 70%|███████   | 3742/5329 [03:13<01:21, 19.54it/s]

 70%|███████   | 3744/5329 [03:13<01:20, 19.62it/s]

 70%|███████   | 3746/5329 [03:14<01:20, 19.63it/s]

 70%|███████   | 3748/5329 [03:14<01:20, 19.73it/s]

 70%|███████   | 3750/5329 [03:14<01:20, 19.73it/s]

 70%|███████   | 3752/5329 [03:14<01:19, 19.76it/s]

 70%|███████   | 3754/5329 [03:14<01:20, 19.67it/s]

 70%|███████   | 3756/5329 [03:14<01:20, 19.65it/s]

 71%|███████   | 3758/5329 [03:14<01:20, 19.42it/s]

 71%|███████   | 3760/5329 [03:14<01:20, 19.38it/s]

 71%|███████   | 3762/5329 [03:14<01:21, 19.25it/s]

 71%|███████   | 3764/5329 [03:15<01:21, 19.27it/s]

 71%|███████   | 3766/5329 [03:15<01:21, 19.28it/s]

 71%|███████   | 3768/5329 [03:15<01:21, 19.21it/s]

 71%|███████   | 3770/5329 [03:15<01:21, 19.24it/s]

 71%|███████   | 3772/5329 [03:15<01:21, 19.15it/s]

 71%|███████   | 3774/5329 [03:15<01:21, 19.11it/s]

 71%|███████   | 3777/5329 [03:15<01:13, 21.25it/s]

 71%|███████   | 3780/5329 [03:15<01:15, 20.61it/s]

 71%|███████   | 3783/5329 [03:15<01:16, 20.17it/s]

 71%|███████   | 3786/5329 [03:16<01:17, 19.93it/s]

 71%|███████   | 3789/5329 [03:16<01:18, 19.68it/s]

 71%|███████   | 3791/5329 [03:16<01:19, 19.38it/s]

 71%|███████   | 3793/5329 [03:16<01:19, 19.26it/s]

 71%|███████   | 3795/5329 [03:16<01:20, 19.14it/s]

 71%|███████▏  | 3797/5329 [03:16<01:20, 19.14it/s]

 71%|███████▏  | 3799/5329 [03:16<01:19, 19.16it/s]

 71%|███████▏  | 3801/5329 [03:16<01:19, 19.18it/s]

 71%|███████▏  | 3803/5329 [03:17<01:19, 19.23it/s]

 71%|███████▏  | 3805/5329 [03:17<01:18, 19.34it/s]

 71%|███████▏  | 3807/5329 [03:17<01:18, 19.40it/s]

 71%|███████▏  | 3809/5329 [03:17<01:18, 19.36it/s]

 72%|███████▏  | 3811/5329 [03:17<01:17, 19.47it/s]

 72%|███████▏  | 3813/5329 [03:17<01:17, 19.50it/s]

 72%|███████▏  | 3815/5329 [03:17<01:17, 19.53it/s]

 72%|███████▏  | 3817/5329 [03:17<01:17, 19.49it/s]

 72%|███████▏  | 3819/5329 [03:17<01:18, 19.36it/s]

 72%|███████▏  | 3821/5329 [03:17<01:18, 19.26it/s]

 72%|███████▏  | 3823/5329 [03:18<01:17, 19.34it/s]

 72%|███████▏  | 3825/5329 [03:18<01:17, 19.33it/s]

 72%|███████▏  | 3827/5329 [03:18<01:17, 19.40it/s]

 72%|███████▏  | 3829/5329 [03:18<01:17, 19.41it/s]

 72%|███████▏  | 3831/5329 [03:18<01:17, 19.27it/s]

 72%|███████▏  | 3833/5329 [03:18<01:17, 19.33it/s]

 72%|███████▏  | 3835/5329 [03:18<01:17, 19.29it/s]

 72%|███████▏  | 3837/5329 [03:18<01:17, 19.24it/s]

 72%|███████▏  | 3839/5329 [03:18<01:17, 19.17it/s]

 72%|███████▏  | 3841/5329 [03:18<01:17, 19.20it/s]

 72%|███████▏  | 3843/5329 [03:19<01:17, 19.15it/s]

 72%|███████▏  | 3845/5329 [03:19<01:17, 19.09it/s]

 72%|███████▏  | 3847/5329 [03:19<01:17, 19.13it/s]

 72%|███████▏  | 3850/5329 [03:19<01:09, 21.14it/s]

 72%|███████▏  | 3853/5329 [03:19<01:11, 20.52it/s]

 72%|███████▏  | 3856/5329 [03:19<01:13, 20.09it/s]

 72%|███████▏  | 3859/5329 [03:19<01:15, 19.53it/s]

 72%|███████▏  | 3861/5329 [03:19<01:15, 19.34it/s]

 72%|███████▏  | 3863/5329 [03:20<01:15, 19.32it/s]

 73%|███████▎  | 3865/5329 [03:20<01:15, 19.32it/s]

 73%|███████▎  | 3867/5329 [03:20<01:15, 19.33it/s]

 73%|███████▎  | 3869/5329 [03:20<01:15, 19.26it/s]

 73%|███████▎  | 3871/5329 [03:20<01:15, 19.37it/s]

 73%|███████▎  | 3873/5329 [03:20<01:15, 19.38it/s]

 73%|███████▎  | 3875/5329 [03:20<01:14, 19.40it/s]

 73%|███████▎  | 3877/5329 [03:20<01:14, 19.46it/s]

 73%|███████▎  | 3879/5329 [03:20<01:14, 19.39it/s]

 73%|███████▎  | 3881/5329 [03:21<01:14, 19.46it/s]

 73%|███████▎  | 3883/5329 [03:21<01:14, 19.47it/s]

 73%|███████▎  | 3885/5329 [03:21<01:14, 19.47it/s]

 73%|███████▎  | 3887/5329 [03:21<01:13, 19.55it/s]

 73%|███████▎  | 3889/5329 [03:21<01:13, 19.54it/s]

 73%|███████▎  | 3891/5329 [03:21<01:13, 19.50it/s]

 73%|███████▎  | 3893/5329 [03:21<01:13, 19.51it/s]

 73%|███████▎  | 3895/5329 [03:21<01:13, 19.60it/s]

 73%|███████▎  | 3897/5329 [03:21<01:13, 19.55it/s]

 73%|███████▎  | 3899/5329 [03:21<01:12, 19.61it/s]

 73%|███████▎  | 3901/5329 [03:22<01:13, 19.55it/s]

 73%|███████▎  | 3903/5329 [03:22<01:12, 19.56it/s]

 73%|███████▎  | 3905/5329 [03:22<01:12, 19.58it/s]

 73%|███████▎  | 3907/5329 [03:22<01:12, 19.54it/s]

 73%|███████▎  | 3909/5329 [03:22<01:12, 19.47it/s]

 73%|███████▎  | 3911/5329 [03:22<01:12, 19.43it/s]

 73%|███████▎  | 3913/5329 [03:22<01:13, 19.37it/s]

 73%|███████▎  | 3915/5329 [03:22<01:13, 19.35it/s]

 74%|███████▎  | 3917/5329 [03:22<01:13, 19.17it/s]

 74%|███████▎  | 3919/5329 [03:22<01:13, 19.23it/s]

 74%|███████▎  | 3921/5329 [03:23<01:13, 19.23it/s]

 74%|███████▎  | 3924/5329 [03:23<01:05, 21.42it/s]

 74%|███████▎  | 3927/5329 [03:23<01:07, 20.71it/s]

 74%|███████▎  | 3930/5329 [03:23<01:08, 20.31it/s]

 74%|███████▍  | 3933/5329 [03:23<01:09, 20.06it/s]

 74%|███████▍  | 3936/5329 [03:23<01:17, 17.98it/s]

 74%|███████▍  | 3938/5329 [03:23<01:15, 18.34it/s]

 74%|███████▍  | 3940/5329 [03:24<01:15, 18.31it/s]

 74%|███████▍  | 3942/5329 [03:24<01:15, 18.40it/s]

 74%|███████▍  | 3944/5329 [03:24<01:13, 18.75it/s]

 74%|███████▍  | 3946/5329 [03:24<01:12, 18.96it/s]

 74%|███████▍  | 3948/5329 [03:24<01:12, 19.14it/s]

 74%|███████▍  | 3950/5329 [03:24<01:11, 19.26it/s]

 74%|███████▍  | 3952/5329 [03:24<01:10, 19.41it/s]

 74%|███████▍  | 3954/5329 [03:24<01:10, 19.42it/s]

 74%|███████▍  | 3956/5329 [03:24<01:10, 19.34it/s]

 74%|███████▍  | 3958/5329 [03:24<01:11, 19.29it/s]

 74%|███████▍  | 3960/5329 [03:25<01:10, 19.29it/s]

 74%|███████▍  | 3962/5329 [03:25<01:10, 19.33it/s]

 74%|███████▍  | 3964/5329 [03:25<01:10, 19.37it/s]

 74%|███████▍  | 3966/5329 [03:25<01:09, 19.49it/s]

 74%|███████▍  | 3968/5329 [03:25<01:09, 19.64it/s]

 74%|███████▍  | 3970/5329 [03:25<01:09, 19.63it/s]

 75%|███████▍  | 3972/5329 [03:25<01:09, 19.64it/s]

 75%|███████▍  | 3974/5329 [03:25<01:09, 19.53it/s]

 75%|███████▍  | 3976/5329 [03:25<01:09, 19.42it/s]

 75%|███████▍  | 3978/5329 [03:26<01:09, 19.51it/s]

 75%|███████▍  | 3980/5329 [03:26<01:09, 19.55it/s]

 75%|███████▍  | 3982/5329 [03:26<01:09, 19.50it/s]

 75%|███████▍  | 3984/5329 [03:26<01:09, 19.49it/s]

 75%|███████▍  | 3986/5329 [03:26<01:08, 19.49it/s]

 75%|███████▍  | 3988/5329 [03:26<01:09, 19.39it/s]

 75%|███████▍  | 3990/5329 [03:26<01:09, 19.37it/s]

 75%|███████▍  | 3992/5329 [03:26<01:09, 19.36it/s]

 75%|███████▍  | 3994/5329 [03:26<01:09, 19.28it/s]

 75%|███████▍  | 3996/5329 [03:26<01:09, 19.26it/s]

 75%|███████▌  | 3999/5329 [03:27<01:02, 21.44it/s]

 75%|███████▌  | 4002/5329 [03:27<01:03, 20.85it/s]

 75%|███████▌  | 4005/5329 [03:27<01:04, 20.44it/s]

 75%|███████▌  | 4008/5329 [03:27<01:05, 20.15it/s]

 75%|███████▌  | 4011/5329 [03:27<01:05, 20.02it/s]

 75%|███████▌  | 4014/5329 [03:27<01:06, 19.75it/s]

 75%|███████▌  | 4016/5329 [03:27<01:07, 19.57it/s]

 75%|███████▌  | 4018/5329 [03:28<01:06, 19.60it/s]

 75%|███████▌  | 4020/5329 [03:28<01:06, 19.62it/s]

 75%|███████▌  | 4022/5329 [03:28<01:06, 19.66it/s]

 76%|███████▌  | 4024/5329 [03:28<01:06, 19.64it/s]

 76%|███████▌  | 4026/5329 [03:28<01:06, 19.57it/s]

 76%|███████▌  | 4028/5329 [03:28<01:06, 19.53it/s]

 76%|███████▌  | 4030/5329 [03:28<01:06, 19.59it/s]

 76%|███████▌  | 4032/5329 [03:28<01:06, 19.59it/s]

 76%|███████▌  | 4034/5329 [03:28<01:06, 19.45it/s]

 76%|███████▌  | 4036/5329 [03:28<01:07, 19.21it/s]

 76%|███████▌  | 4038/5329 [03:29<01:07, 19.26it/s]

 76%|███████▌  | 4040/5329 [03:29<01:06, 19.31it/s]

 76%|███████▌  | 4042/5329 [03:29<01:06, 19.33it/s]

 76%|███████▌  | 4044/5329 [03:29<01:06, 19.24it/s]

 76%|███████▌  | 4046/5329 [03:29<01:06, 19.19it/s]

 76%|███████▌  | 4048/5329 [03:29<01:06, 19.28it/s]

 76%|███████▌  | 4050/5329 [03:29<01:06, 19.32it/s]

 76%|███████▌  | 4052/5329 [03:29<01:06, 19.26it/s]

 76%|███████▌  | 4054/5329 [03:29<01:06, 19.16it/s]

 76%|███████▌  | 4056/5329 [03:29<01:06, 19.14it/s]

 76%|███████▌  | 4058/5329 [03:30<01:06, 19.15it/s]

 76%|███████▌  | 4060/5329 [03:30<01:06, 19.14it/s]

 76%|███████▌  | 4062/5329 [03:30<01:06, 19.14it/s]

 76%|███████▋  | 4064/5329 [03:30<01:06, 19.13it/s]

 76%|███████▋  | 4066/5329 [03:30<01:05, 19.20it/s]

 76%|███████▋  | 4068/5329 [03:30<01:05, 19.15it/s]

 76%|███████▋  | 4070/5329 [03:30<01:05, 19.26it/s]

 76%|███████▋  | 4073/5329 [03:30<00:58, 21.43it/s]

 76%|███████▋  | 4076/5329 [03:30<01:00, 20.77it/s]

 77%|███████▋  | 4079/5329 [03:31<01:01, 20.29it/s]

 77%|███████▋  | 4082/5329 [03:31<01:02, 20.03it/s]

 77%|███████▋  | 4085/5329 [03:31<01:02, 19.80it/s]

 77%|███████▋  | 4088/5329 [03:31<01:03, 19.63it/s]

 77%|███████▋  | 4090/5329 [03:31<01:02, 19.69it/s]

 77%|███████▋  | 4092/5329 [03:31<01:02, 19.67it/s]

 77%|███████▋  | 4094/5329 [03:31<01:03, 19.59it/s]

 77%|███████▋  | 4096/5329 [03:31<01:02, 19.68it/s]

 77%|███████▋  | 4099/5329 [03:32<01:02, 19.79it/s]

 77%|███████▋  | 4101/5329 [03:32<01:02, 19.73it/s]

 77%|███████▋  | 4103/5329 [03:32<01:01, 19.81it/s]

 77%|███████▋  | 4105/5329 [03:32<01:01, 19.83it/s]

 77%|███████▋  | 4107/5329 [03:32<01:01, 19.78it/s]

 77%|███████▋  | 4109/5329 [03:32<01:01, 19.74it/s]

 77%|███████▋  | 4112/5329 [03:32<01:01, 19.84it/s]

 77%|███████▋  | 4115/5329 [03:32<01:00, 19.95it/s]

 77%|███████▋  | 4117/5329 [03:33<01:00, 19.95it/s]

 77%|███████▋  | 4120/5329 [03:33<01:00, 20.08it/s]

 77%|███████▋  | 4123/5329 [03:33<01:00, 20.10it/s]

 77%|███████▋  | 4126/5329 [03:33<01:00, 20.02it/s]

 77%|███████▋  | 4129/5329 [03:33<00:59, 20.02it/s]

 78%|███████▊  | 4132/5329 [03:33<00:59, 19.95it/s]

 78%|███████▊  | 4134/5329 [03:33<01:00, 19.78it/s]

 78%|███████▊  | 4137/5329 [03:34<00:59, 19.88it/s]

 78%|███████▊  | 4140/5329 [03:34<00:59, 19.95it/s]

 78%|███████▊  | 4142/5329 [03:34<00:59, 19.95it/s]

 78%|███████▊  | 4144/5329 [03:34<00:59, 19.79it/s]

 78%|███████▊  | 4147/5329 [03:34<00:53, 21.95it/s]

 78%|███████▊  | 4150/5329 [03:34<00:55, 21.21it/s]

 78%|███████▊  | 4153/5329 [03:34<00:57, 20.44it/s]

 78%|███████▊  | 4156/5329 [03:34<00:59, 19.87it/s]

 78%|███████▊  | 4159/5329 [03:35<01:00, 19.34it/s]

 78%|███████▊  | 4161/5329 [03:35<01:01, 19.15it/s]

 78%|███████▊  | 4163/5329 [03:35<01:00, 19.37it/s]

 78%|███████▊  | 4166/5329 [03:35<00:59, 19.63it/s]

 78%|███████▊  | 4168/5329 [03:35<00:59, 19.49it/s]

 78%|███████▊  | 4170/5329 [03:35<00:59, 19.33it/s]

 78%|███████▊  | 4172/5329 [03:35<00:59, 19.32it/s]

 78%|███████▊  | 4174/5329 [03:35<00:59, 19.41it/s]

 78%|███████▊  | 4177/5329 [03:36<00:58, 19.71it/s]

 78%|███████▊  | 4180/5329 [03:36<00:57, 19.92it/s]

 78%|███████▊  | 4182/5329 [03:36<00:57, 19.93it/s]

 79%|███████▊  | 4185/5329 [03:36<00:57, 20.02it/s]

 79%|███████▊  | 4188/5329 [03:36<00:56, 20.15it/s]

 79%|███████▊  | 4191/5329 [03:36<00:56, 20.20it/s]

 79%|███████▊  | 4194/5329 [03:36<00:56, 20.15it/s]

 79%|███████▉  | 4197/5329 [03:37<00:56, 20.18it/s]

 79%|███████▉  | 4200/5329 [03:37<00:56, 20.09it/s]

 79%|███████▉  | 4203/5329 [03:37<00:56, 20.01it/s]

 79%|███████▉  | 4206/5329 [03:37<00:56, 19.94it/s]

 79%|███████▉  | 4208/5329 [03:37<00:56, 19.92it/s]

 79%|███████▉  | 4211/5329 [03:37<00:55, 20.01it/s]

 79%|███████▉  | 4214/5329 [03:37<00:56, 19.82it/s]

 79%|███████▉  | 4216/5329 [03:38<00:56, 19.85it/s]

 79%|███████▉  | 4218/5329 [03:38<00:56, 19.84it/s]

 79%|███████▉  | 4221/5329 [03:38<00:50, 22.03it/s]

 79%|███████▉  | 4224/5329 [03:38<00:51, 21.33it/s]

 79%|███████▉  | 4227/5329 [03:38<00:52, 20.82it/s]

 79%|███████▉  | 4230/5329 [03:38<00:53, 20.46it/s]

 79%|███████▉  | 4233/5329 [03:38<00:54, 20.24it/s]

 79%|███████▉  | 4236/5329 [03:38<00:54, 20.18it/s]

 80%|███████▉  | 4239/5329 [03:39<00:53, 20.19it/s]

 80%|███████▉  | 4242/5329 [03:39<00:53, 20.16it/s]

 80%|███████▉  | 4245/5329 [03:39<00:53, 20.13it/s]

 80%|███████▉  | 4248/5329 [03:39<00:53, 20.14it/s]

 80%|███████▉  | 4251/5329 [03:39<00:53, 20.19it/s]

 80%|███████▉  | 4254/5329 [03:39<00:53, 20.25it/s]

 80%|███████▉  | 4257/5329 [03:40<00:53, 20.20it/s]

 80%|███████▉  | 4260/5329 [03:40<00:52, 20.26it/s]

 80%|███████▉  | 4263/5329 [03:40<00:52, 20.27it/s]

 80%|████████  | 4266/5329 [03:40<00:52, 20.18it/s]

 80%|████████  | 4269/5329 [03:40<00:52, 20.12it/s]

 80%|████████  | 4272/5329 [03:40<00:52, 20.02it/s]

 80%|████████  | 4275/5329 [03:40<00:52, 19.91it/s]

 80%|████████  | 4277/5329 [03:41<00:52, 19.88it/s]

 80%|████████  | 4280/5329 [03:41<00:52, 19.99it/s]

 80%|████████  | 4282/5329 [03:41<00:52, 19.96it/s]

 80%|████████  | 4284/5329 [03:41<00:52, 19.90it/s]

 80%|████████  | 4287/5329 [03:41<00:52, 19.95it/s]

 80%|████████  | 4289/5329 [03:41<00:52, 19.91it/s]

 81%|████████  | 4291/5329 [03:41<00:52, 19.89it/s]

 81%|████████  | 4294/5329 [03:41<00:47, 21.99it/s]

 81%|████████  | 4297/5329 [03:41<00:48, 21.19it/s]

 81%|████████  | 4300/5329 [03:42<00:49, 20.69it/s]

 81%|████████  | 4303/5329 [03:42<00:50, 20.35it/s]

 81%|████████  | 4306/5329 [03:42<00:51, 19.91it/s]

 81%|████████  | 4309/5329 [03:42<00:51, 19.91it/s]

 81%|████████  | 4312/5329 [03:42<00:50, 19.97it/s]

 81%|████████  | 4315/5329 [03:42<00:50, 19.96it/s]

 81%|████████  | 4318/5329 [03:43<00:50, 19.99it/s]

 81%|████████  | 4321/5329 [03:43<00:50, 20.03it/s]

 81%|████████  | 4324/5329 [03:43<00:50, 19.94it/s]

 81%|████████  | 4327/5329 [03:43<00:49, 20.06it/s]

 81%|████████▏ | 4330/5329 [03:43<00:49, 20.14it/s]

 81%|████████▏ | 4333/5329 [03:43<00:49, 20.12it/s]

 81%|████████▏ | 4336/5329 [03:43<00:49, 20.03it/s]

 81%|████████▏ | 4339/5329 [03:44<00:49, 20.09it/s]

 81%|████████▏ | 4342/5329 [03:44<00:49, 20.14it/s]

 82%|████████▏ | 4345/5329 [03:44<00:48, 20.14it/s]

 82%|████████▏ | 4348/5329 [03:44<00:48, 20.14it/s]

 82%|████████▏ | 4351/5329 [03:44<00:48, 20.15it/s]

 82%|████████▏ | 4354/5329 [03:44<00:48, 20.13it/s]

 82%|████████▏ | 4357/5329 [03:44<00:48, 20.07it/s]

 82%|████████▏ | 4360/5329 [03:45<00:48, 20.00it/s]

 82%|████████▏ | 4363/5329 [03:45<00:48, 20.03it/s]

 82%|████████▏ | 4366/5329 [03:45<00:48, 19.99it/s]

 82%|████████▏ | 4369/5329 [03:45<00:43, 22.17it/s]

 82%|████████▏ | 4372/5329 [03:45<00:44, 21.38it/s]

 82%|████████▏ | 4375/5329 [03:45<00:45, 20.87it/s]

 82%|████████▏ | 4378/5329 [03:45<00:47, 20.23it/s]

 82%|████████▏ | 4381/5329 [03:46<00:46, 20.20it/s]

 82%|████████▏ | 4384/5329 [03:46<00:46, 20.34it/s]

 82%|████████▏ | 4387/5329 [03:46<00:46, 20.35it/s]

 82%|████████▏ | 4390/5329 [03:46<00:46, 20.34it/s]

 82%|████████▏ | 4393/5329 [03:46<00:45, 20.37it/s]

 82%|████████▏ | 4396/5329 [03:46<00:45, 20.38it/s]

 83%|████████▎ | 4399/5329 [03:47<00:45, 20.39it/s]

 83%|████████▎ | 4402/5329 [03:47<00:45, 20.38it/s]

 83%|████████▎ | 4405/5329 [03:47<00:45, 20.46it/s]

 83%|████████▎ | 4408/5329 [03:47<00:45, 20.41it/s]

 83%|████████▎ | 4411/5329 [03:47<00:44, 20.42it/s]

 83%|████████▎ | 4414/5329 [03:47<00:44, 20.34it/s]

 83%|████████▎ | 4417/5329 [03:47<00:45, 20.26it/s]

 83%|████████▎ | 4420/5329 [03:48<00:45, 20.13it/s]

 83%|████████▎ | 4423/5329 [03:48<00:45, 20.05it/s]

 83%|████████▎ | 4426/5329 [03:48<00:44, 20.10it/s]

 83%|████████▎ | 4429/5329 [03:48<00:45, 19.98it/s]

 83%|████████▎ | 4432/5329 [03:48<00:44, 20.05it/s]

 83%|████████▎ | 4435/5329 [03:48<00:44, 20.07it/s]

 83%|████████▎ | 4438/5329 [03:48<00:44, 19.94it/s]

 83%|████████▎ | 4440/5329 [03:49<00:44, 19.95it/s]

 83%|████████▎ | 4443/5329 [03:49<00:39, 22.16it/s]

 83%|████████▎ | 4446/5329 [03:49<00:41, 21.47it/s]

 83%|████████▎ | 4449/5329 [03:49<00:41, 20.96it/s]

 84%|████████▎ | 4452/5329 [03:49<00:42, 20.72it/s]

 84%|████████▎ | 4455/5329 [03:49<00:42, 20.65it/s]

 84%|████████▎ | 4458/5329 [03:49<00:42, 20.58it/s]

 84%|████████▎ | 4461/5329 [03:50<00:42, 20.56it/s]

 84%|████████▍ | 4464/5329 [03:50<00:42, 20.55it/s]

 84%|████████▍ | 4467/5329 [03:50<00:41, 20.55it/s]

 84%|████████▍ | 4470/5329 [03:50<00:41, 20.59it/s]

 84%|████████▍ | 4473/5329 [03:50<00:41, 20.63it/s]

 84%|████████▍ | 4476/5329 [03:50<00:41, 20.63it/s]

 84%|████████▍ | 4479/5329 [03:50<00:41, 20.57it/s]

 84%|████████▍ | 4482/5329 [03:51<00:41, 20.50it/s]

 84%|████████▍ | 4485/5329 [03:51<00:41, 20.42it/s]

 84%|████████▍ | 4488/5329 [03:51<00:41, 20.37it/s]

 84%|████████▍ | 4491/5329 [03:51<00:41, 20.30it/s]

 84%|████████▍ | 4494/5329 [03:51<00:41, 20.28it/s]

 84%|████████▍ | 4497/5329 [03:51<00:41, 20.26it/s]

 84%|████████▍ | 4500/5329 [03:51<00:41, 20.21it/s]

 84%|████████▍ | 4503/5329 [03:52<00:40, 20.20it/s]

 85%|████████▍ | 4506/5329 [03:52<00:40, 20.16it/s]

 85%|████████▍ | 4509/5329 [03:52<00:40, 20.15it/s]

 85%|████████▍ | 4512/5329 [03:52<00:40, 20.08it/s]

 85%|████████▍ | 4516/5329 [03:52<00:37, 21.77it/s]

 85%|████████▍ | 4519/5329 [03:52<00:38, 21.22it/s]

 85%|████████▍ | 4522/5329 [03:52<00:38, 20.94it/s]

 85%|████████▍ | 4525/5329 [03:53<00:39, 20.60it/s]

 85%|████████▍ | 4528/5329 [03:53<00:38, 20.62it/s]

 85%|████████▌ | 4531/5329 [03:53<00:38, 20.48it/s]

 85%|████████▌ | 4534/5329 [03:53<00:39, 20.34it/s]

 85%|████████▌ | 4537/5329 [03:53<00:38, 20.33it/s]

 85%|████████▌ | 4540/5329 [03:53<00:38, 20.24it/s]

 85%|████████▌ | 4543/5329 [03:54<00:38, 20.24it/s]

 85%|████████▌ | 4546/5329 [03:54<00:38, 20.33it/s]

 85%|████████▌ | 4549/5329 [03:54<00:38, 20.34it/s]

 85%|████████▌ | 4552/5329 [03:54<00:38, 20.37it/s]

 85%|████████▌ | 4555/5329 [03:54<00:37, 20.42it/s]

 86%|████████▌ | 4558/5329 [03:54<00:37, 20.43it/s]

 86%|████████▌ | 4561/5329 [03:54<00:37, 20.39it/s]

 86%|████████▌ | 4564/5329 [03:55<00:37, 20.31it/s]

 86%|████████▌ | 4567/5329 [03:55<00:37, 20.27it/s]

 86%|████████▌ | 4570/5329 [03:55<00:37, 20.23it/s]

 86%|████████▌ | 4573/5329 [03:55<00:37, 20.06it/s]

 86%|████████▌ | 4576/5329 [03:55<00:41, 17.94it/s]

 86%|████████▌ | 4578/5329 [03:55<00:40, 18.51it/s]

 86%|████████▌ | 4580/5329 [03:55<00:39, 18.92it/s]

 86%|████████▌ | 4583/5329 [03:56<00:38, 19.29it/s]

 86%|████████▌ | 4586/5329 [03:56<00:38, 19.52it/s]

 86%|████████▌ | 4588/5329 [03:56<00:37, 19.61it/s]

 86%|████████▌ | 4591/5329 [03:56<00:33, 21.77it/s]

 86%|████████▌ | 4594/5329 [03:56<00:34, 21.16it/s]

 86%|████████▋ | 4597/5329 [03:56<00:35, 20.79it/s]

 86%|████████▋ | 4600/5329 [03:56<00:35, 20.57it/s]

 86%|████████▋ | 4603/5329 [03:57<00:35, 20.60it/s]

 86%|████████▋ | 4606/5329 [03:57<00:35, 20.54it/s]

 86%|████████▋ | 4609/5329 [03:57<00:35, 20.50it/s]

 87%|████████▋ | 4612/5329 [03:57<00:34, 20.50it/s]

 87%|████████▋ | 4615/5329 [03:57<00:34, 20.42it/s]

 87%|████████▋ | 4618/5329 [03:57<00:34, 20.45it/s]

 87%|████████▋ | 4621/5329 [03:57<00:34, 20.46it/s]

 87%|████████▋ | 4624/5329 [03:58<00:34, 20.50it/s]

 87%|████████▋ | 4627/5329 [03:58<00:34, 20.42it/s]

 87%|████████▋ | 4630/5329 [03:58<00:34, 20.25it/s]

 87%|████████▋ | 4633/5329 [03:58<00:34, 20.26it/s]

 87%|████████▋ | 4636/5329 [03:58<00:34, 20.21it/s]

 87%|████████▋ | 4639/5329 [03:58<00:34, 20.18it/s]

 87%|████████▋ | 4642/5329 [03:58<00:34, 20.04it/s]

 87%|████████▋ | 4645/5329 [03:59<00:34, 20.07it/s]

 87%|████████▋ | 4648/5329 [03:59<00:33, 20.07it/s]

 87%|████████▋ | 4651/5329 [03:59<00:33, 19.94it/s]

 87%|████████▋ | 4654/5329 [03:59<00:33, 20.01it/s]

 87%|████████▋ | 4657/5329 [03:59<00:33, 20.08it/s]

 87%|████████▋ | 4660/5329 [03:59<00:33, 20.02it/s]

 88%|████████▊ | 4663/5329 [03:59<00:29, 22.20it/s]

 88%|████████▊ | 4666/5329 [04:00<00:30, 21.49it/s]

 88%|████████▊ | 4669/5329 [04:00<00:31, 20.97it/s]

 88%|████████▊ | 4672/5329 [04:00<00:31, 20.64it/s]

 88%|████████▊ | 4675/5329 [04:00<00:31, 20.58it/s]

 88%|████████▊ | 4678/5329 [04:00<00:31, 20.59it/s]

 88%|████████▊ | 4681/5329 [04:00<00:31, 20.59it/s]

 88%|████████▊ | 4684/5329 [04:00<00:31, 20.63it/s]

 88%|████████▊ | 4687/5329 [04:01<00:31, 20.60it/s]

 88%|████████▊ | 4690/5329 [04:01<00:31, 20.60it/s]

 88%|████████▊ | 4693/5329 [04:01<00:30, 20.63it/s]

 88%|████████▊ | 4696/5329 [04:01<00:30, 20.71it/s]

 88%|████████▊ | 4699/5329 [04:01<00:30, 20.61it/s]

 88%|████████▊ | 4702/5329 [04:01<00:30, 20.54it/s]

 88%|████████▊ | 4705/5329 [04:02<00:30, 20.34it/s]

 88%|████████▊ | 4708/5329 [04:02<00:30, 20.32it/s]

 88%|████████▊ | 4711/5329 [04:02<00:30, 20.19it/s]

 88%|████████▊ | 4714/5329 [04:02<00:30, 20.03it/s]

 89%|████████▊ | 4717/5329 [04:02<00:30, 20.10it/s]

 89%|████████▊ | 4720/5329 [04:02<00:30, 20.04it/s]

 89%|████████▊ | 4723/5329 [04:02<00:30, 20.09it/s]

 89%|████████▊ | 4726/5329 [04:03<00:30, 20.07it/s]

 89%|████████▊ | 4729/5329 [04:03<00:29, 20.08it/s]

 89%|████████▉ | 4732/5329 [04:03<00:29, 20.11it/s]

 89%|████████▉ | 4735/5329 [04:03<00:29, 20.14it/s]

 89%|████████▉ | 4738/5329 [04:03<00:26, 22.34it/s]

 89%|████████▉ | 4741/5329 [04:03<00:27, 21.55it/s]

 89%|████████▉ | 4744/5329 [04:03<00:27, 21.15it/s]

 89%|████████▉ | 4747/5329 [04:04<00:27, 20.92it/s]

 89%|████████▉ | 4750/5329 [04:04<00:27, 20.75it/s]

 89%|████████▉ | 4753/5329 [04:04<00:27, 20.63it/s]

 89%|████████▉ | 4756/5329 [04:04<00:27, 20.48it/s]

 89%|████████▉ | 4759/5329 [04:04<00:27, 20.49it/s]

 89%|████████▉ | 4762/5329 [04:04<00:27, 20.41it/s]

 89%|████████▉ | 4765/5329 [04:04<00:27, 20.34it/s]

 89%|████████▉ | 4768/5329 [04:05<00:27, 20.28it/s]

 90%|████████▉ | 4771/5329 [04:05<00:27, 20.34it/s]

 90%|████████▉ | 4774/5329 [04:05<00:27, 20.33it/s]

 90%|████████▉ | 4777/5329 [04:05<00:27, 20.29it/s]

 90%|████████▉ | 4780/5329 [04:05<00:27, 20.24it/s]

 90%|████████▉ | 4783/5329 [04:05<00:27, 20.15it/s]

 90%|████████▉ | 4786/5329 [04:05<00:27, 20.11it/s]

 90%|████████▉ | 4789/5329 [04:06<00:26, 20.16it/s]

 90%|████████▉ | 4792/5329 [04:06<00:26, 20.24it/s]

 90%|████████▉ | 4795/5329 [04:06<00:26, 20.16it/s]

 90%|█████████ | 4798/5329 [04:06<00:26, 20.18it/s]

 90%|█████████ | 4801/5329 [04:06<00:26, 20.16it/s]

 90%|█████████ | 4804/5329 [04:06<00:26, 20.09it/s]

 90%|█████████ | 4807/5329 [04:07<00:26, 20.03it/s]

 90%|█████████ | 4810/5329 [04:07<00:25, 20.08it/s]

 90%|█████████ | 4813/5329 [04:07<00:23, 22.29it/s]

 90%|█████████ | 4816/5329 [04:07<00:23, 21.54it/s]

 90%|█████████ | 4819/5329 [04:07<00:24, 21.16it/s]

 90%|█████████ | 4822/5329 [04:07<00:24, 21.04it/s]

 91%|█████████ | 4825/5329 [04:07<00:24, 20.88it/s]

 91%|█████████ | 4828/5329 [04:08<00:24, 20.69it/s]

 91%|█████████ | 4831/5329 [04:08<00:24, 20.67it/s]

 91%|█████████ | 4834/5329 [04:08<00:23, 20.71it/s]

 91%|█████████ | 4837/5329 [04:08<00:23, 20.72it/s]

 91%|█████████ | 4840/5329 [04:08<00:23, 20.69it/s]

 91%|█████████ | 4843/5329 [04:08<00:23, 20.69it/s]

 91%|█████████ | 4846/5329 [04:08<00:23, 20.49it/s]

 91%|█████████ | 4849/5329 [04:09<00:23, 20.49it/s]

 91%|█████████ | 4852/5329 [04:09<00:23, 20.45it/s]

 91%|█████████ | 4855/5329 [04:09<00:23, 20.36it/s]

 91%|█████████ | 4858/5329 [04:09<00:23, 20.35it/s]

 91%|█████████ | 4861/5329 [04:09<00:23, 20.26it/s]

 91%|█████████▏| 4864/5329 [04:09<00:22, 20.26it/s]

 91%|█████████▏| 4867/5329 [04:09<00:22, 20.27it/s]

 91%|█████████▏| 4870/5329 [04:10<00:22, 20.18it/s]

 91%|█████████▏| 4873/5329 [04:10<00:22, 20.23it/s]

 91%|█████████▏| 4876/5329 [04:10<00:22, 20.16it/s]

 92%|█████████▏| 4879/5329 [04:10<00:22, 20.06it/s]

 92%|█████████▏| 4882/5329 [04:10<00:22, 20.03it/s]

 92%|█████████▏| 4885/5329 [04:10<00:20, 22.19it/s]

 92%|█████████▏| 4888/5329 [04:10<00:20, 21.53it/s]

 92%|█████████▏| 4891/5329 [04:11<00:20, 21.02it/s]

 92%|█████████▏| 4894/5329 [04:11<00:20, 20.84it/s]

 92%|█████████▏| 4897/5329 [04:11<00:20, 20.77it/s]

 92%|█████████▏| 4900/5329 [04:11<00:20, 20.54it/s]

 92%|█████████▏| 4903/5329 [04:11<00:20, 20.45it/s]

 92%|█████████▏| 4906/5329 [04:11<00:20, 20.34it/s]

 92%|█████████▏| 4909/5329 [04:11<00:20, 20.32it/s]

 92%|█████████▏| 4912/5329 [04:12<00:20, 20.21it/s]

 92%|█████████▏| 4915/5329 [04:12<00:20, 20.28it/s]

 92%|█████████▏| 4918/5329 [04:12<00:20, 20.36it/s]

 92%|█████████▏| 4921/5329 [04:12<00:19, 20.43it/s]

 92%|█████████▏| 4924/5329 [04:12<00:19, 20.33it/s]

 92%|█████████▏| 4927/5329 [04:12<00:19, 20.26it/s]

 93%|█████████▎| 4930/5329 [04:12<00:19, 20.28it/s]

 93%|█████████▎| 4933/5329 [04:13<00:19, 20.29it/s]

 93%|█████████▎| 4936/5329 [04:13<00:19, 20.33it/s]

 93%|█████████▎| 4939/5329 [04:13<00:19, 20.30it/s]

 93%|█████████▎| 4942/5329 [04:13<00:19, 20.33it/s]

 93%|█████████▎| 4945/5329 [04:13<00:18, 20.37it/s]

 93%|█████████▎| 4948/5329 [04:13<00:18, 20.28it/s]

 93%|█████████▎| 4951/5329 [04:14<00:18, 20.28it/s]

 93%|█████████▎| 4954/5329 [04:14<00:18, 20.25it/s]

 93%|█████████▎| 4957/5329 [04:14<00:18, 20.25it/s]

 93%|█████████▎| 4960/5329 [04:14<00:16, 22.40it/s]

 93%|█████████▎| 4963/5329 [04:14<00:16, 21.67it/s]

 93%|█████████▎| 4966/5329 [04:14<00:17, 21.33it/s]

 93%|█████████▎| 4969/5329 [04:14<00:17, 21.10it/s]

 93%|█████████▎| 4972/5329 [04:15<00:17, 20.86it/s]

 93%|█████████▎| 4975/5329 [04:15<00:17, 20.57it/s]

 93%|█████████▎| 4978/5329 [04:15<00:17, 20.60it/s]

 93%|█████████▎| 4981/5329 [04:15<00:16, 20.59it/s]

 94%|█████████▎| 4984/5329 [04:15<00:16, 20.63it/s]

 94%|█████████▎| 4987/5329 [04:15<00:16, 20.61it/s]

 94%|█████████▎| 4990/5329 [04:15<00:16, 20.66it/s]

 94%|█████████▎| 4993/5329 [04:16<00:16, 20.61it/s]

 94%|█████████▍| 4996/5329 [04:16<00:16, 20.43it/s]

 94%|█████████▍| 4999/5329 [04:16<00:16, 20.40it/s]

 94%|█████████▍| 5002/5329 [04:16<00:16, 20.32it/s]

 94%|█████████▍| 5005/5329 [04:16<00:15, 20.31it/s]

 94%|█████████▍| 5008/5329 [04:16<00:15, 20.32it/s]

 94%|█████████▍| 5011/5329 [04:16<00:15, 20.31it/s]

 94%|█████████▍| 5014/5329 [04:17<00:15, 20.30it/s]

 94%|█████████▍| 5017/5329 [04:17<00:15, 20.27it/s]

 94%|█████████▍| 5020/5329 [04:17<00:15, 20.25it/s]

 94%|█████████▍| 5023/5329 [04:17<00:15, 20.13it/s]

 94%|█████████▍| 5026/5329 [04:17<00:15, 20.07it/s]

 94%|█████████▍| 5029/5329 [04:17<00:14, 20.10it/s]

 94%|█████████▍| 5032/5329 [04:17<00:14, 20.12it/s]

 94%|█████████▍| 5035/5329 [04:18<00:13, 22.24it/s]

 95%|█████████▍| 5038/5329 [04:18<00:13, 21.49it/s]

 95%|█████████▍| 5041/5329 [04:18<00:13, 21.22it/s]

 95%|█████████▍| 5044/5329 [04:18<00:13, 20.98it/s]

 95%|█████████▍| 5047/5329 [04:18<00:13, 20.85it/s]

 95%|█████████▍| 5050/5329 [04:18<00:13, 20.80it/s]

 95%|█████████▍| 5053/5329 [04:18<00:13, 20.79it/s]

 95%|█████████▍| 5056/5329 [04:19<00:13, 20.63it/s]

 95%|█████████▍| 5059/5329 [04:19<00:13, 20.56it/s]

 95%|█████████▍| 5062/5329 [04:19<00:12, 20.54it/s]

 95%|█████████▌| 5065/5329 [04:19<00:12, 20.54it/s]

 95%|█████████▌| 5068/5329 [04:19<00:12, 20.58it/s]

 95%|█████████▌| 5071/5329 [04:19<00:12, 20.50it/s]

 95%|█████████▌| 5074/5329 [04:19<00:12, 20.42it/s]

 95%|█████████▌| 5077/5329 [04:20<00:12, 20.28it/s]

 95%|█████████▌| 5080/5329 [04:20<00:12, 20.19it/s]

 95%|█████████▌| 5083/5329 [04:20<00:12, 20.17it/s]

 95%|█████████▌| 5086/5329 [04:20<00:12, 20.13it/s]

 95%|█████████▌| 5089/5329 [04:20<00:11, 20.10it/s]

 96%|█████████▌| 5092/5329 [04:20<00:11, 20.07it/s]

 96%|█████████▌| 5095/5329 [04:21<00:11, 19.99it/s]

 96%|█████████▌| 5097/5329 [04:21<00:11, 19.81it/s]

 96%|█████████▌| 5099/5329 [04:21<00:11, 19.84it/s]

 96%|█████████▌| 5101/5329 [04:21<00:11, 19.86it/s]

 96%|█████████▌| 5103/5329 [04:21<00:11, 19.89it/s]

 96%|█████████▌| 5105/5329 [04:21<00:11, 19.91it/s]

 96%|█████████▌| 5108/5329 [04:21<00:10, 22.08it/s]

 96%|█████████▌| 5111/5329 [04:21<00:10, 21.31it/s]

 96%|█████████▌| 5114/5329 [04:21<00:10, 20.94it/s]

 96%|█████████▌| 5117/5329 [04:22<00:10, 20.71it/s]

 96%|█████████▌| 5120/5329 [04:22<00:10, 20.47it/s]

 96%|█████████▌| 5123/5329 [04:22<00:10, 20.34it/s]

 96%|█████████▌| 5126/5329 [04:22<00:10, 20.14it/s]

 96%|█████████▌| 5129/5329 [04:22<00:09, 20.12it/s]

 96%|█████████▋| 5132/5329 [04:22<00:09, 20.07it/s]

 96%|█████████▋| 5135/5329 [04:22<00:09, 20.00it/s]

 96%|█████████▋| 5138/5329 [04:23<00:09, 19.96it/s]

 96%|█████████▋| 5140/5329 [04:23<00:09, 19.91it/s]

 96%|█████████▋| 5142/5329 [04:23<00:09, 19.87it/s]

 97%|█████████▋| 5144/5329 [04:23<00:09, 19.84it/s]

 97%|█████████▋| 5146/5329 [04:23<00:09, 19.71it/s]

 97%|█████████▋| 5148/5329 [04:23<00:09, 19.75it/s]

 97%|█████████▋| 5150/5329 [04:23<00:09, 19.61it/s]

 97%|█████████▋| 5152/5329 [04:23<00:09, 19.46it/s]

 97%|█████████▋| 5154/5329 [04:23<00:09, 19.32it/s]

 97%|█████████▋| 5156/5329 [04:24<00:08, 19.27it/s]

 97%|█████████▋| 5158/5329 [04:24<00:08, 19.34it/s]

 97%|█████████▋| 5160/5329 [04:24<00:08, 19.32it/s]

 97%|█████████▋| 5162/5329 [04:24<00:08, 19.45it/s]

 97%|█████████▋| 5164/5329 [04:24<00:08, 19.51it/s]

 97%|█████████▋| 5166/5329 [04:24<00:08, 19.56it/s]

 97%|█████████▋| 5168/5329 [04:24<00:08, 19.66it/s]

 97%|█████████▋| 5170/5329 [04:24<00:08, 19.65it/s]

 97%|█████████▋| 5172/5329 [04:24<00:08, 19.61it/s]

 97%|█████████▋| 5174/5329 [04:24<00:07, 19.62it/s]

 97%|█████████▋| 5176/5329 [04:25<00:07, 19.65it/s]

 97%|█████████▋| 5178/5329 [04:25<00:07, 19.60it/s]

 97%|█████████▋| 5180/5329 [04:25<00:07, 19.60it/s]

 97%|█████████▋| 5183/5329 [04:25<00:06, 21.72it/s]

 97%|█████████▋| 5186/5329 [04:25<00:06, 21.32it/s]

 97%|█████████▋| 5189/5329 [04:25<00:06, 21.04it/s]

 97%|█████████▋| 5192/5329 [04:25<00:06, 20.79it/s]

 97%|█████████▋| 5195/5329 [04:25<00:06, 20.62it/s]

 98%|█████████▊| 5198/5329 [04:26<00:06, 20.52it/s]

 98%|█████████▊| 5201/5329 [04:26<00:06, 20.45it/s]

 98%|█████████▊| 5204/5329 [04:26<00:06, 20.45it/s]

 98%|█████████▊| 5207/5329 [04:26<00:05, 20.37it/s]

 98%|█████████▊| 5210/5329 [04:26<00:05, 20.27it/s]

 98%|█████████▊| 5213/5329 [04:26<00:05, 20.34it/s]

 98%|█████████▊| 5216/5329 [04:27<00:05, 20.29it/s]

 98%|█████████▊| 5219/5329 [04:27<00:05, 20.26it/s]

 98%|█████████▊| 5222/5329 [04:27<00:05, 20.19it/s]

 98%|█████████▊| 5225/5329 [04:27<00:05, 20.20it/s]

 98%|█████████▊| 5228/5329 [04:27<00:05, 20.13it/s]

 98%|█████████▊| 5231/5329 [04:27<00:04, 20.05it/s]

 98%|█████████▊| 5234/5329 [04:27<00:04, 20.07it/s]

 98%|█████████▊| 5237/5329 [04:28<00:04, 20.07it/s]

 98%|█████████▊| 5240/5329 [04:28<00:04, 20.03it/s]

 98%|█████████▊| 5243/5329 [04:28<00:04, 19.98it/s]

 98%|█████████▊| 5246/5329 [04:28<00:04, 20.03it/s]

 98%|█████████▊| 5249/5329 [04:28<00:04, 20.00it/s]

 99%|█████████▊| 5252/5329 [04:28<00:03, 20.02it/s]

 99%|█████████▊| 5255/5329 [04:28<00:03, 22.04it/s]

 99%|█████████▊| 5258/5329 [04:29<00:03, 21.52it/s]

 99%|█████████▊| 5261/5329 [04:29<00:03, 21.16it/s]

 99%|█████████▉| 5264/5329 [04:29<00:03, 20.91it/s]

 99%|█████████▉| 5267/5329 [04:29<00:02, 20.69it/s]

 99%|█████████▉| 5270/5329 [04:29<00:02, 20.67it/s]

 99%|█████████▉| 5273/5329 [04:29<00:02, 20.63it/s]

 99%|█████████▉| 5276/5329 [04:29<00:02, 20.53it/s]

 99%|█████████▉| 5279/5329 [04:30<00:02, 20.45it/s]

 99%|█████████▉| 5282/5329 [04:30<00:02, 20.51it/s]

 99%|█████████▉| 5285/5329 [04:30<00:02, 20.49it/s]

 99%|█████████▉| 5288/5329 [04:30<00:02, 20.37it/s]

 99%|█████████▉| 5291/5329 [04:30<00:01, 20.27it/s]

 99%|█████████▉| 5294/5329 [04:30<00:01, 20.32it/s]

 99%|█████████▉| 5297/5329 [04:30<00:01, 20.31it/s]

 99%|█████████▉| 5300/5329 [04:31<00:01, 20.14it/s]

100%|█████████▉| 5303/5329 [04:31<00:01, 20.11it/s]

100%|█████████▉| 5306/5329 [04:31<00:01, 20.08it/s]

100%|█████████▉| 5309/5329 [04:31<00:01, 19.97it/s]

100%|█████████▉| 5311/5329 [04:31<00:00, 19.72it/s]

100%|█████████▉| 5314/5329 [04:31<00:00, 19.84it/s]

100%|█████████▉| 5316/5329 [04:31<00:00, 19.81it/s]

100%|█████████▉| 5318/5329 [04:32<00:00, 19.81it/s]

100%|█████████▉| 5320/5329 [04:32<00:00, 19.83it/s]

100%|█████████▉| 5322/5329 [04:32<00:00, 19.86it/s]

100%|█████████▉| 5324/5329 [04:32<00:00, 19.83it/s]

100%|█████████▉| 5326/5329 [04:32<00:00, 19.86it/s]

100%|█████████▉| 5328/5329 [04:32<00:00, 19.89it/s]

100%|██████████| 5329/5329 [04:32<00:00, 19.55it/s]

In [21]:
res_df

,Column Configuration,Differentia Bit Width,Stratum Retention Policy,Stratum Retention Policy Resolution Parameter,Stratigraphic Column Expected Retained Bits,Stratigraphic Column Mean Actual Retained Bits,Stratigraphic Column Target Retained Bits,Stratigraphic Column Expected Retained Bits Error,Stratigraphic Column Actual Num Retained Strata,Taxon Compared From,Taxon Compared To,Generation of Taxon Compared From,Generation of Taxon Compared To,Generation Of MRCA Lower Bound (inclusive),Generation Of MRCA Upper Bound (exclusive),MRCA Bound Confidence,Rank of Earliest Detectable Mrca With
0,actual_bits=63+actual_strata=63+bits_error=-1+...,1,TaperedDepthProportionalResolution,31,63,63.000000,64,-1,63,316622,316618,5001,5001,4800,5001,0.968750,512
1,actual_bits=56+actual_strata=7+bits_error=-8+d...,8,TaperedDepthProportionalResolution,3,56,56.000000,64,-8,7,316622,316618,5001,5001,4608,5000,0.996094,0
2,actual_bits=192+actual_strata=3+bits_error=128...,64,TaperedDepthProportionalResolution,1,192,192.000000,64,128,3,316622,316618,5001,5001,4096,5000,1.000000,0
3,actual_bits=511+actual_strata=511+bits_error=-...,1,TaperedDepthProportionalResolution,255,511,510.095890,512,-1,511,316622,316618,5001,5001,4960,5000,0.968750,64
4,actual_bits=504+actual_strata=63+bits_error=-8...,8,TaperedDepthProportionalResolution,31,504,504.000000,512,-8,63,316622,316618,5001,5001,4992,5000,0.996094,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
94603,actual_bits=472+actual_strata=59+bits_error=-4...,8,RecencyProportionalResolution,5,472,465.424658,512,-40,59,316643,316640,5001,5001,4999,5000,0.996094,0
94604,actual_bits=448+actual_strata=7+bits_error=-64...,64,RecencyProportionalResolution,0,448,395.397260,512,-64,7,316643,316640,5001,5001,4992,5000,1.000000,0
94605,actual_bits=4096+actual_strata=4096+bits_error...,1,RecencyProportionalResolution,1596,4096,4096.986301,4096,0,4096,316643,316640,5001,5001,4995,5000,0.968750,8
94606,actual_bits=4056+actual_strata=507+bits_error=...,8,RecencyProportionalResolution,71,4056,4049.424658,4096,-40,507,316643,316640,5001,5001,4999,5000,0.996094,0
94607,actual_bits=3776+actual_strata=59+bits_error=-...,64,RecencyProportionalResolution,5,3776,3723.397260,4096,-320,59,316643,316640,5001,5001,4999,5000,1.000000,0

In [22]:
nbm.print_dataframe_synopsis(res_df)

digest: df1610ca5746491e194f5807f3b6f82e35c7bf2618c4cf48e69db3d1b08f32d7
manifest:
  Column Configuration: '                              18#  ex., actual_bits=63+actual_strata=63+bits_error=-1+differentia=1+policy=TaperedDepthProportionalResolution+resolution=31+target_bits=64'
  Differentia Bit Width: '                             3#   ex., 1'
  Generation Of MRCA Lower Bound (inclusive): '        45#  ex., 4800'
  Generation Of MRCA Upper Bound (exclusive): '        32#  ex., 5001'
  Generation of Taxon Compared From: '                 3#   ex., 5001'
  Generation of Taxon Compared To: '                   3#   ex., 5001'
  MRCA Bound Confidence: '                             3#   ex., 0.96875'
  Rank of Earliest Detectable Mrca With: '             6#   ex., 512'
  Stratigraphic Column Actual Num Retained Strata: '   7#   ex., 63'
  Stratigraphic Column Expected Retained Bits: '       14#  ex., 63'
  Stratigraphic Column Expected Retained Bits Error: ' 9#   ex., -1'
  Stratigraphic Column Mean Actual Retained Bits: '    17#  ex., 63.0'
  Stratigraphic Column Target Retained Bits: '         3#   ex., 64'
  Stratum Retention Policy: '                          2#   ex., TaperedDepthProportionalResolution'
  Stratum Retention Policy Resolution Parameter: '     9#   ex., 31'
  Taxon Compared From: '                               73#  ex., 316622'
  Taxon Compared To: '                                 73#  ex., 316618'
num cols: 17
num cols all na: 0
num cols any na: 0
num na: 0
num rows: 94608
num rows all na: 0
num rows any na: 0
size: 63M

# Save Pairwise MRCA Estimates to File

In [23]:
res_df.to_csv(
    f'a=pairwise_mrca_estimates+source={data_filename}.gz',
    compression='gzip',
)
res_df.to_csv(
    f'a=pairwise_mrca_estimates+source={data_filename}',
)